PDL for FM Family: Base Timer (BT)
Base Timer (BT)
Data Structures
struct stc_pwm_irq_en
structure to enable the PWM interrupts
struct stc_pwm_int_cb
structure to set the PWM interrupt callback function
struct stc_bt_pwm_config
Structure of PWM configuration.
struct stc_ppg_irq_en
structure to enable the PPG interrupts
struct stc_ppg_int_cb
structure to set the PPG interrupt callback function
struct stc_bt_ppg_config
Structure of PPG configuration.
struct stc_rt_irq_en
structure to enable the Reload timer interrupts
struct stc_rt_irq_cb
structure to set the Reload timer interrupt callback function
struct stc_bt_rt_config
Structure of Reload timer configuration.
struct stc_pwc_irq_en
structure to enable the PWC timer interrupts
struct stc_pwc_int_cb
structure to set the PWC timer interrupt callback function
struct stc_bt_pwc_config
Structure of PWC timer configuration.
struct stc_bt_intern_data
BT internal data.
struct stc_bt_instance_data
BT instance data.
Defines
#define stc_btn_t FM_BT_PWM_TypeDef
#define BT0 (*((volatile stc_btn_t *) FM_BT0_PWM_BASE))
#define BT1 (*((volatile stc_btn_t *) FM_BT1_PWM_BASE))
#define BT2 (*((volatile stc_btn_t *) FM_BT2_PWM_BASE))
#define BT3 (*((volatile stc_btn_t *) FM_BT3_PWM_BASE))
#define BT4 (*((volatile stc_btn_t *) FM_BT4_PWM_BASE))
#define BT5 (*((volatile stc_btn_t *) FM_BT5_PWM_BASE))
#define BT6 (*((volatile stc_btn_t *) FM_BT6_PWM_BASE))
#define BT7 (*((volatile stc_btn_t *) FM_BT7_PWM_BASE))
#define BT8 (*((volatile stc_btn_t *) FM_BT8_PWM_BASE))
#define BT9 (*((volatile stc_btn_t *) FM_BT9_PWM_BASE))
#define BT10 (*((volatile stc_btn_t *) FM_BT10_PWM_BASE))
#define BT11 (*((volatile stc_btn_t *) FM_BT11_PWM_BASE))
#define BT12 (*((volatile stc_btn_t *) FM_BT12_PWM_BASE))
#define BT13 (*((volatile stc_btn_t *) FM_BT13_PWM_BASE))
#define BT14 (*((volatile stc_btn_t *) FM_BT14_PWM_BASE))
#define BT15 (*((volatile stc_btn_t *) FM_BT15_PWM_BASE))
#define BT_INSTANCE_COUNT
#define PDL_INTERRUPT_BT_ACTIVE
Typedefs
typedef enum en_bt_instance_index en_bt_instance_index_t
Enumeration to define an index for each BT instance.
typedef enum en_bt_io_mode en_bt_io_mode_t
Enumeration to define BT IO mode.
typedef enum en_bt_timer_mode en_bt_timer_mode_t
Enumeration to define timer mode of BT.
typedef enum en_pwm_clock_pres en_pwm_clock_pres_t
Enumeration to define clock prescaler of PWM timer.
typedef enum en_pwm_restart_enable en_pwm_restart_enable_t
Enumeration to define the configuration of PWM restart option.
typedef enum en_pwm_output_mask en_pwm_output_mask_t
Enumeration to define the configuration of PWM output mask.
typedef enum en_pwm_ext_trig en_pwm_ext_trig_t
Enumeration to define external trigger of PWM.
typedef enum en_pwm_output_polarity en_pwm_output_polarity_t
Enumeration to define PWM initial polarity.
typedef enum en_pwm_mode en_pwm_mode_t
Enumeration to define PWM timer mode.
typedef struct stc_pwm_irq_en stc_pwm_irq_en_t
structure to enable the PWM interrupts
typedef enum en_pwm_irq_sel en_pwm_irq_sel_t
enumeration to select the PWM interrupt
typedef struct stc_pwm_int_cb stc_pwm_irq_cb_t
structure to set the PWM interrupt callback function
typedef struct stc_bt_pwm_config stc_bt_pwm_config_t
Structure of PWM configuration.
typedef enum en_ppg_clock_pres en_ppg_clock_pres_t
Enumeration to define clock prescaler of PPG timer.
typedef enum en_ppg_restart_enable en_ppg_restart_enable_t
Enumeration to define the configuration of PPG restart option.
typedef enum en_ppg_output_mask en_ppg_output_mask_t
Enumeration to define the configuration of PPG output mask.
typedef enum en_ppg_ext_trig en_ppg_ext_trig_t
Enumeration to define external trigger of PPG.
typedef enum en_ppg_output_polarity en_ppg_output_polarity_t
Enumeration to define PWM initial polarity.
typedef enum en_ppg_mode en_ppg_mode_t
Enumeration to define PWM timer mode.
typedef struct stc_ppg_irq_en stc_ppg_irq_en_t
structure to enable the PPG interrupts
typedef enum en_ppg_irq_sel en_ppg_irq_sel_t
enumeration to select the PPG interrupt
typedef struct stc_ppg_int_cb stc_ppg_irq_cb_t
structure to set the PPG interrupt callback function
typedef struct stc_bt_ppg_config stc_bt_ppg_config_t
Structure of PPG configuration.
typedef enum en_rt_clock_pres en_rt_clock_pres_t
Enumeration to define clock prescaler of Reload timer.
typedef enum en_rt_ext_trigger en_rt_ext_trigger_t
Enumeration to define external trigger of Reload timer.
typedef enum en_rt_output_polarity en_rt_output_polarity_t
Enumeration to define Reload timer output initial polarity.
typedef enum en_rt_mode en_rt_mode_t
Enumeration to define Reload timer mode.
typedef enum en_rt_timer_size en_rt_timer_size_t
Enumeration to define Reload timer size.
typedef struct stc_rt_irq_en stc_rt_irq_en_t
structure to enable the Reload timer interrupts
typedef enum en_rt_irq_sel en_rt_irq_sel_t
enumeration to select the Reload timer interrupt
typedef struct stc_rt_irq_cb stc_rt_irq_cb_t
structure to set the Reload timer interrupt callback function
typedef struct stc_bt_rt_config stc_bt_rt_config_t
Structure of Reload timer configuration.
typedef enum en_pwc_clock_pres en_pwc_clock_pres_t
Enumeration to define clock prescaler of PWC timer.
typedef enum en_pwc_measure_edge en_pwc_measure_edge_t
Enumeration to define measure mode of PWC timer.
typedef enum en_pwc_mode en_pwc_mode_t
Enumeration to define PWC timer mode.
typedef enum en_pwc_timer_size en_pwc_timer_size_t
Enumeration to define Reload timer size.
typedef struct stc_pwc_irq_en stc_pwc_irq_en_t
structure to enable the PWC timer interrupts
typedef enum en_pwc_irq_sel en_pwc_irq_sel_t
structure to select the PWC timer interrupt
typedef struct stc_pwc_int_cb stc_pwc_irq_cb_t
structure to set the PWC timer interrupt callback function
typedef struct stc_bt_pwc_config stc_bt_pwc_config_t
Structure of PWC timer configuration.
typedef struct stc_bt_intern_data stc_bt_intern_data_t
BT internal data.
typedef struct stc_bt_instance_data stc_bt_instance_data_t
BT instance data.
Enumerations
enum en_bt_instance_index {
BtInstanceIndexBt0, BtInstanceIndexBt1, BtInstanceIndexBt2, BtInstanceIndexBt3,
BtInstanceIndexBt4, BtInstanceIndexBt5, BtInstanceIndexBt6, BtInstanceIndexBt7,
BtInstanceIndexBt8, BtInstanceIndexBt9, BtInstanceIndexBt10, BtInstanceIndexBt11,
BtInstanceIndexBt12, BtInstanceIndexBt13, BtInstanceIndexBt14, BtInstanceIndexBt15,
BtInstanceIndexMax
}
Enumeration to define an index for each BT instance.
enum en_bt_io_mode {
BtIoMode0 = 0u, BtIoMode1 = 1u, BtIoMode2 = 2u, BtIoMode3 = 3u,
BtIoMode4 = 4u, BtIoMode5 = 5u, BtIoMode6 = 6u, BtIoMode7 = 7u,
BtIoMode8 = 8u
}
Enumeration to define BT IO mode.
enum en_bt_timer_mode {
BtResetMode = 0u, BtPwmMode = 1u, BtPpgMode = 2u, BtRtMode = 3u,
BtPwcMode = 4u
}
Enumeration to define timer mode of BT.
enum en_pwm_clock_pres {
PwmPresNone = 0u, PwmPres1Div4 = 1u, PwmPres1Div16 = 2u, PwmPres1Div128 = 3u,
PwmPres1Div256 = 4u, PwmPres1ExtClkRising = 5u, PwmPres1ExtClkFalling = 6u, PwmPres1ExtClkBoth = 7u,
PwmPres1Div512 = 8u, PwmPres1Div1024 = 9u, PwmPres1Div2048 = 10u
}
Enumeration to define clock prescaler of PWM timer.
enum en_pwm_restart_enable { PwmRestartDisable = 0u, PwmRestartEnable = 1u }
Enumeration to define the configuration of PWM restart option.
enum en_pwm_output_mask { PwmOutputNormal = 0u, PwmOutputMask = 1u }
Enumeration to define the configuration of PWM output mask.
enum en_pwm_ext_trig { PwmExtTrigDisable = 0u, PwmExtTrigRising = 1u, PwmExtTrigFalling = 2u, PwmExtTrigBoth = 3u }
Enumeration to define external trigger of PWM.
enum en_pwm_output_polarity { PwmPolarityLow = 0u, PwmPolarityHigh = 1u }
Enumeration to define PWM initial polarity.
enum en_pwm_mode { PwmContinuous = 0u, PwmOneshot = 1u }
Enumeration to define PWM timer mode.
enum en_pwm_irq_sel { PwmTrigIrq = 0u, PwmDutyMatchIrq = 1u, PwmUnderflowIrq = 2u }
enumeration to select the PWM interrupt
enum en_ppg_clock_pres {
PpgPresNone = 0u, PpgPres1Div4 = 1u, PpgPres1Div16 = 2u, PpgPres1Div128 = 3u,
PpgPres1Div256 = 4u, PpgPres1ExtClkRising = 5u, PpgPres1ExtClkFalling = 6u, PpgPres1ExtClkBoth = 7u,
PpgPres1Div512 = 8u, PpgPres1Div1024 = 9u, PpgPres1Div2048 = 10u
}
Enumeration to define clock prescaler of PPG timer.
enum en_ppg_restart_enable { PpgRestartDisable = 0u, PpgRestartEnable = 1u }
Enumeration to define the configuration of PPG restart option.
enum en_ppg_output_mask { PpgOutputNormal = 0u, PpgOutputMask = 1u }
Enumeration to define the configuration of PPG output mask.
enum en_ppg_ext_trig { PpgExtTrigDisable = 0u, PpgExtTrigRising = 1u, PpgExtTrigFalling = 2u, PpgExtTrigBoth = 3u }
Enumeration to define external trigger of PPG.
enum en_ppg_output_polarity { PpgPolarityLow = 0u, PpgPolarityHigh = 1u }
Enumeration to define PWM initial polarity.
enum en_ppg_mode { PpgContinuous = 0u, PpgOneshot = 1u }
Enumeration to define PWM timer mode.
enum en_ppg_irq_sel { PpgTrigIrq = 0u, PpgUnderflowIrq = 1u }
enumeration to select the PPG interrupt
enum en_rt_clock_pres {
RtPresNone = 0u, RtPres1Div4 = 1u, RtPres1Div16 = 2u, RtPres1Div128 = 3u,
RtPres1Div256 = 4u, RtPres1ExtClkRising = 5u, RtPres1ExtClkFalling = 6u, RtPres1ExtClkBoth = 7u,
RtPres1Div512 = 8u, RtPres1Div1024 = 9u, RtPres1Div2048 = 10u
}
Enumeration to define clock prescaler of Reload timer.
enum en_rt_ext_trigger {
RtExtTiggerDisable = 0u, RtExtTiggerRisingEdge = 1u, RtExtTiggerFallingEdge = 2u, RtExtTiggerBothEdge = 3u,
RtExtTiggerLowLevel = 4u, RtExtTiggerHighLevel = 5u
}
Enumeration to define external trigger of Reload timer.
enum en_rt_output_polarity { RtPolarityLow = 0u, RtPolarityHigh = 1u }
Enumeration to define Reload timer output initial polarity.
enum en_rt_mode { RtReload = 0u, RtOneshot = 1u }
Enumeration to define Reload timer mode.
enum en_rt_timer_size { RtSize16Bit = 0u, RtSize32Bit = 1u }
Enumeration to define Reload timer size.
enum en_rt_irq_sel { RtTrigIrq = 0u, RtUnderflowIrq = 1u }
enumeration to select the Reload timer interrupt
enum en_pwc_clock_pres {
PwcPresNone = 0u, PwcPres1Div4 = 1u, PwcPres1Div16 = 2u, PwcPres1Div128 = 3u,
PwcPres1Div256 = 4u, PwcPres1Div512 = 8u, PwcPres1Div1024 = 9u, PwcPres1Div2048 = 10u
}
Enumeration to define clock prescaler of PWC timer.
enum en_pwc_measure_edge {
PwcMeasureRisingToFalling = 0u, PwcMeasureRisingToRising = 1u, PwcMeasureFallingToFalling = 2u, PwcMeasureEitherToEither = 3u,
PwcMeasureFallingToRising = 4u
}
Enumeration to define measure mode of PWC timer.
enum en_pwc_mode { PwcContinuous = 0u, PwcOneshot = 1u }
Enumeration to define PWC timer mode.
enum en_pwc_timer_size { PwcSize16Bit = 0u, PwcSize32Bit = 1u }
Enumeration to define Reload timer size.
enum en_pwc_irq_sel { PwcMeasureCompleteIrq = 0u, PwcMeasureOverflowIrq = 1u }
structure to select the PWC timer interrupt
Functions
static stc_bt_intern_data_t * BtGetInternDataPtr (volatile FM_BT_PWM_TypeDef *pstcBt)
Return the internal data for a certain BT instance.
void Bt_IrqHandler (volatile FM_BT_PWM_TypeDef *pstcBt, stc_bt_intern_data_t *pstcBtInternData)
BT interrupt service routine.
static void BtInitNvic (volatile FM_BT_PWM_TypeDef *pstcBt)
Set NVIC Interrupt depending on BT instance.
static void BtDeInitNvic (volatile FM_BT_PWM_TypeDef *pstcBt)
Clear NVIC Interrupt depending on BT instance.
en_result_t Bt_ConfigIOMode (volatile FM_BT_PWM_TypeDef *pstcBt, en_bt_io_mode_t enIoMode)
Configure BT IO mode.
en_result_t Bt_Pwm_Init (volatile FM_BT_PWM_TypeDef *pstcBt, stc_bt_pwm_config_t *pstcPwmConfig)
Initialize PWM function of BT.
en_result_t Bt_Pwm_DeInit (volatile FM_BT_PWM_TypeDef *pstcBt, boolean_t bTouchNvic)
De-Initialize PWM function of BT.
en_result_t Bt_Pwm_EnableCount (volatile FM_BT_PWM_TypeDef *pstcBt)
Enable PWM timer counting.
en_result_t Bt_Pwm_DisableCount (volatile FM_BT_PWM_TypeDef *pstcBt)
Disable PWM timer counting.
en_result_t Bt_Pwm_EnableSwTrig (volatile FM_BT_PWM_TypeDef *pstcBt)
Start PWM timer by software.
en_result_t Bt_Pwm_EnableIrq (volatile FM_BT_PWM_TypeDef *pstcBt, en_pwm_irq_sel_t enIrqSel)
Enable PWM timer interrupt.
en_result_t Bt_Pwm_DisableIrq (volatile FM_BT_PWM_TypeDef *pstcBt, en_pwm_irq_sel_t enIrqSel)
Disable PWM timer interrupt.
en_irq_flag_t Bt_Pwm_GetIrqFlag (volatile FM_BT_PWM_TypeDef *pstcBt, en_pwm_irq_sel_t enIrqSel)
Get interrupt flag of PWM timer.
en_result_t Bt_Pwm_ClrIrqFlag (volatile FM_BT_PWM_TypeDef *pstcBt, en_pwm_irq_sel_t enIrqSel)
Clear interrupt flag of PWM timer.
en_result_t Bt_Pwm_WriteCycleVal (volatile FM_BT_PWM_TypeDef *pstcBt, uint16_t u16Cycle)
Write Cycle value of PWM timer.
en_result_t Bt_Pwm_WriteDutyVal (volatile FM_BT_PWM_TypeDef *pstcBt, uint16_t u16Duty)
Write duty value of PWM timer.
uint16_t Bt_Pwm_ReadCurCnt (volatile FM_BT_PWM_TypeDef *pstcBt)
Read current count value of PWM timer.
en_result_t Bt_Ppg_Init (volatile FM_BT_PWM_TypeDef *pstcBt, stc_bt_ppg_config_t *pstcPpgConfig)
Initialize PPG function of BT.
en_result_t Bt_Ppg_DeInit (volatile FM_BT_PWM_TypeDef *pstcBt, boolean_t bTouchNvic)
De-Initialize PPG function of BT.
en_result_t Bt_Ppg_EnableCount (volatile FM_BT_PWM_TypeDef *pstcBt)
Enable PPG timer counting.
en_result_t Bt_Ppg_DisableCount (volatile FM_BT_PWM_TypeDef *pstcBt)
Disable PPG timer counting.
en_result_t Bt_Ppg_EnableSwTrig (volatile FM_BT_PWM_TypeDef *pstcBt)
Start PPG timer by software.
en_result_t Bt_Ppg_EnableIrq (volatile FM_BT_PWM_TypeDef *pstcBt, en_ppg_irq_sel_t enIrqSel)
Enable PPG timer interrupt.
en_result_t Bt_Ppg_DisableIrq (volatile FM_BT_PWM_TypeDef *pstcBt, en_ppg_irq_sel_t enIrqSel)
Disable PPG timer interrupt.
en_irq_flag_t Bt_Ppg_GetIrqFlag (volatile FM_BT_PWM_TypeDef *pstcBt, en_ppg_irq_sel_t enIrqSel)
Get interrupt flag of PPG timer.
en_result_t Bt_Ppg_ClrIrqFlag (volatile FM_BT_PWM_TypeDef *pstcBt, en_ppg_irq_sel_t enIrqSel)
Clear interrupt flag of PPG timer.
en_result_t Bt_Ppg_WriteLowWidthVal (volatile FM_BT_PWM_TypeDef *pstcBt, uint16_t u16Val)
Write low width count value of PPG timer.
en_result_t Bt_Ppg_WriteHighWidthVal (volatile FM_BT_PWM_TypeDef *pstcBt, uint16_t u16Val)
Write high width count value of PPG timer.
uint16_t Bt_Ppg_ReadCurCnt (volatile FM_BT_PWM_TypeDef *pstcBt)
Read current count value of PPG timer.
en_result_t Bt_Rt_Init (volatile FM_BT_PWM_TypeDef *pstcBt, stc_bt_rt_config_t *pstcRtConfig)
Initialize RT function of BT.
en_result_t Bt_Rt_DeInit (volatile FM_BT_PWM_TypeDef *pstcBt, boolean_t bTouchNvic)
De-Initialize RT function of BT.
en_result_t Bt_Rt_EnableCount (volatile FM_BT_PWM_TypeDef *pstcBt)
Enable Reload timer counting.
en_result_t Bt_Rt_DisableCount (volatile FM_BT_PWM_TypeDef *pstcBt)
Disable Reload timer counting.
en_result_t Bt_Rt_EnableSwTrig (volatile FM_BT_PWM_TypeDef *pstcBt)
Start Reload timer by software.
en_result_t Bt_Rt_EnableIrq (volatile FM_BT_PWM_TypeDef *pstcBt, en_rt_irq_sel_t enIrqSel)
Enable Reload timer interrupt.
en_result_t Bt_Rt_DisableIrq (volatile FM_BT_PWM_TypeDef *pstcBt, en_rt_irq_sel_t enIrqSel)
Disable Reload timer interrupt.
en_irq_flag_t Bt_Rt_GetIrqFlag (volatile FM_BT_PWM_TypeDef *pstcBt, en_rt_irq_sel_t enIrqSel)
Get interrupt flag of Reload timer.
en_result_t Bt_Rt_ClrIrqFlag (volatile FM_BT_PWM_TypeDef *pstcBt, en_rt_irq_sel_t enIrqSel)
Clear interrupt flag of Reload timer.
en_result_t Bt_Rt_WriteCycleVal (volatile FM_BT_PWM_TypeDef *pstcBt, uint16_t u16Val)
Write count cycle of Reload timer.
uint16_t Bt_Rt_ReadCurCnt (volatile FM_BT_PWM_TypeDef *pstcBt)
Read current count value of Reload timer.
en_result_t Bt_Pwc_Init (volatile FM_BT_PWM_TypeDef *pstcBt, stc_bt_pwc_config_t *pstcPwcConfig)
Initialize PWC function of BT.
en_result_t Bt_Pwc_DeInit (volatile FM_BT_PWM_TypeDef *pstcBt, boolean_t bTouchNvic)
De-Initialize PWC function of BT.
en_result_t Bt_Pwc_EnableCount (volatile FM_BT_PWM_TypeDef *pstcBt)
Enable PWC timer counting.
en_result_t Bt_Pwc_DisableCount (volatile FM_BT_PWM_TypeDef *pstcBt)
Disable PWC timer counting.
en_result_t Bt_Pwc_EnableIrq (volatile FM_BT_PWM_TypeDef *pstcBt, en_pwc_irq_sel_t enIrqSel)
Enable PWC timer interrupt.
en_result_t Bt_Pwc_DisableIrq (volatile FM_BT_PWM_TypeDef *pstcBt, en_pwc_irq_sel_t enIrqSel)
Disable PWC timer interrupt.
en_irq_flag_t Bt_Pwc_GetIrqFlag (volatile FM_BT_PWM_TypeDef *pstcBt, en_pwc_irq_sel_t enIrqSel)
Get interrupt flag of PWC timer.
en_result_t Bt_Pwc_ClrIrqFlag (volatile FM_BT_PWM_TypeDef *pstcBt, en_pwc_irq_sel_t enIrqSel)
Clear interrupt flag of PWC timer.
en_stat_flag_t Bt_Pwc_GetErrorFlag (volatile FM_BT_PWM_TypeDef *pstcBt)
Get error flag of PWC timer.
uint16_t Bt_Pwc_Get16BitMeasureData (volatile FM_BT_PWM_TypeDef *pstcBt)
Get 16 bits measure data of PWC timer.
uint32_t Bt_Pwc_Get32BitMeasureData (volatile FM_BT_PWM_TypeDef *pstcBt)
Get 32 bits measure data of PWC timer.
void Bt_SetSimultaneousStart (uint16_t u16Value)
Set the Simultaneous Start register of Base timer.
Variables
stc_bt_instance_data_t m_astcBtInstanceDataLut [((PDL_PERIPHERAL_ENABLE_BT0==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT1==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT2==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT3==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT4==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT5==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT6==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT7==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT8==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT9==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT10==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT11==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT12==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT13==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT14==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT15==PDL_ON)?1u:0u)]
Look-up table for all enabled BT instances and their internal data.
stc_bt_instance_data_t m_astcBtInstanceDataLut [((PDL_PERIPHERAL_ENABLE_BT0==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT1==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT2==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT3==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT4==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT5==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT6==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT7==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT8==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT9==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT10==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT11==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT12==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT13==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT14==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT15==PDL_ON)?1u:0u)]
Look-up table for all enabled BT instances and their internal data.
Detailed Description
Provided BT module functions:
Bt_ConfigIOMode()
Bt_Pwm_Init()
Bt_Pwm_EnableCount()
Bt_Pwm_DisableCount()
Bt_Pwm_EnableSwTrig()
Bt_Pwm_EnableIrq()
Bt_Pwm_DisableIrq()
Bt_Pwm_GetIrqFlag()
Bt_Pwm_ClrIrqFlag()
Bt_Pwm_WriteCycleVal()
Bt_Pwm_WriteDutyVal()
Bt_Pwm_ReadCurCnt()
Bt_Ppg_Init()
Bt_Ppg_EnableCount()
Bt_Ppg_DisableCount()
Bt_Ppg_EnableSwTrig()
Bt_Ppg_EnableIrq()
Bt_Ppg_DisableIrq()
Bt_Ppg_GetIrqFlag()
Bt_Ppg_ClrIrqFlag()
Bt_Ppg_WriteLowWidthVal()
Bt_Ppg_WriteHighWidthVal()
Bt_Ppg_ReadCurCnt()
Bt_Rt_Init()
Bt_Rt_EnableCount()
Bt_Rt_DisableCount()
Bt_Rt_EnableSwTrig()
Bt_Rt_EnableIrq()
Bt_Rt_DisableIrq()
Bt_Rt_GetIrqFlag()
Bt_Rt_ClrIrqFlag()
Bt_Rt_WriteCycleVal()
Bt_Rt_ReadCurCnt()
Bt_Pwc_Init()
Bt_Pwc_EnableCount()
Bt_Pwc_DisableCount()
Bt_Pwc_EnableIrq()
Bt_Pwc_DisableIrq()
Bt_Pwc_GetIrqFlag()
Bt_Pwc_ClrIrqFlag()
Bt_Pwc_GetErrorFlag()
Bt_Pwc_Get16BitMeasureData()
Bt_Pwc_Get32BitMeasureData()
Bt_SetSimultaneousStart()
How to use PWM timer function of BT module?
Bt_ConfigIOMode() must be used to configure BT I/O mode to I/O mode 0 first.
Bt_Pwm_Init() is used to initialize PWM timer source clock, output polarity, operation mode and so on. Following operation mode can set:
Continuous mode
One-shot mode
The interrupts can be configured first in Bt_Pwm_Init(), after initialization, a PWM interrupt can be enabled by the function Bt_Pwm_EnableIrq() and a PWM interrupt can be disabled by the function Bt_Pwm_DisableIrq()
With Bt_Pwm_WriteCycleVal() the PWM cycle counter is set to the value given in the parameter Bt_Pwm_WriteCycleVal::u16Cycle.
With Bt_Pwm_WriteDutyVal() the PWM duty counter is set to the value given in the parameter Bt_Pwm_WriteDutyVal::u16Duty.
Notes that PWM can be only set to 16-bit mode, so above two parameters should be 16-bit.
Bt_Pwm_EnableCount() is used to enabe PWM counter.
After above setting is done, calling Bt_Pwm_EnableSwTrig() will start PWM timer.
With Bt_Pwm_ReadCurCnt() the current PWM count can be read when PWM timer is running.
With interrupt mode, when the interrupt occurs, the interrupt flag will be cleared and run into user interrupt callback function.
With polling mode, user can use Bt_Pwm_GetIrqFlag() to check if the interrupt occurs, and clear the interrupt flag by Bt_Pwm_ClrIrqFlag().
When stopping the PWM timer, use Bt_Pwm_DisableCount() to disable PWM counter.
How to use PPG timer function of BT module?
Bt_ConfigIOMode() must be used to configure BT I/O mode to I/O mode 0 first.
Bt_Ppg_Init() is used to initialize PPG timer source clock, output polarity, operation mode and so on. Following operation mode can set:
Continuous mode
One-shot mode
The interrupts can be configured first in Bt_Ppg_Init(), after initialization, a PPG interrupt can be enabled by the function Bt_Ppg_EnableIrq(). This function can set callback function for each channel too.
With Bt_Ppg_WriteLowWidthVal() the PPG low width is set to the value given in the parameter Bt_Ppg_WriteLowWidthVal::u16Cycle.
With Bt_Ppg_WriteHighWidthVal() the PPG high width is set to the value given in the parameter Bt_Ppg_WriteHighWidthVal::u16Cycle.
Notes that PPG can be only set to 16-bit mode, so above two parameters should be 16-bit.
Bt_Ppg_EnableCount() is used to enabe PPG counter.
After above setting is done, calling Bt_Ppg_EnableSwTrig() will start PPG timer.
With Bt_Ppg_ReadCurCnt() the current PPG count can be read when PPG timer is running.
With interrupt mode, when the interrupt occurs, the interrupt flag will be cleared and run into user interrupt callback function.
With polling mode, user can use Bt_Ppg_GetIrqFlag() to check if the interrupt occurs, and clear the interrupt flag by Bt_Ppg_ClrIrqFlag().
When stopping the PPG timer, use Bt_Ppg_DisableCount() to disable PPG counter and Bt_Ppg_DisableIrq() to disable PPG interrupt.
How to use Reload Timer (RT) function of BT module?
Bt_ConfigIOMode() must be used to configure BT I/O mode to I/O mode 0 first.
Bt_Rt_Init() is used to initialize RT source clock, output polarity, operation mode and so on. Following operation mode can set:
Reload mode
One-shot mode
The interrupts can be configured first in Bt_Rt_Init(), after initialization, a RT interrupt can be enabled by the function Bt_Rt_EnableIrq(). This function can set callback function for each channel too.
RT can be set to 16-bit mode or 32-bit mode. In 16-bit mode, Bt_Rt_WriteCycleVal() set the RT counter cycle of according channel. In the 32-bit mode, Bt_Rt_WriteCycleVal() with even channel register pointer as paremater set the low 16-bit cycle value and Bt_Rt_WriteCycleVal() with odd channel register pointer as paremater set the high 16-bit cycle value.
Bt_Rt_EnableCount() is used to enabe RT counter.
After above setting is done, calling Bt_Rt_EnableSwTrig() will start Reload Timer.
With Bt_Rt_ReadCurCnt() the current RT count can be read when Reload Timer is running.
With interrupt mode, when the interrupt occurs, the interrupt flag will be cleared and run into user interrupt callback function.
With polling mode, user can use Bt_Rt_GetIrqFlag() to check if the interrupt occurs, and clear the interrupt flag by Rt_Ppg_ClrIrqFlag().
When stopping the PPG timer, use Bt_Rt_DisableCount() to disable RT counter and Bt_Rt_DisableIrq() to disable RT interrupt.
How to use PWC timer function of BT module?
Bt_ConfigIOMode() must be used to configure BT I/O mode to I/O mode 0 first.
Bt_Pwc_Init() is used to initialize PWC timer source clock, measurement mode and so on.
Following measurement mode can set:
High pulse width measurement
Cycle measurement with rising edges
Cycle measurement with falling edges
Interval measurement between all edges
Low pulse width measurement
Following operation mode can be set:
Continuous mode
One-shot mode
The interrupts can be configured first in Bt_Pwc_Init(), after initialization, a PWC interrupt can be enabled by the function Bt_Pwc_EnableIrq(). This function can set callback function for each channel too.
Bt_Pwc_EnableCount() is used to enabe PWC counter.
After above setting is done, when the valid edge (1st) is detected, the measurement starts, and the valid edge (2nd) is detected, the measurement ends, the interrupt request flag is set at the same time.
PWC timer can be set to 16-bit mode and 32-bit mode. In the 16-bit mode, with Bt_Pwc_Get16BitMeasureData() the measured value can be read after measurement completes, in the 32-bit mode, with Bt_Pwc_Get32BitMeasureData() the measured value can be read.
With interrupt mode, when the interrupt occurs, the interrupt flag will be cleared and the code runs into user interrupt callback function.
With polling mode, user can use Bt_Pwc_GetIrqFlag() to check if the completion interrupt occurs, and clear the interrupt flag by Bt_Pwc_ClrIrqFlag(). Bt_Pwc_GetErrorFlag() is used to get the error flag of PWC measurement.
When stopping the PWC timer, use Bt_Pwc_DisableCount() to disable PWC counter and Bt_Pwc_DisableIrq() to disable PWC interrupt.
Define Documentation
#define BT0 (*((volatile stc_btn_t *) FM_BT0_PWM_BASE))
Definition at line 281 of file bt.h.
Referenced by Bt_ConfigIOMode(), BtDeInitNvic(), and BtInitNvic().
#define BT1 (*((volatile stc_btn_t *) FM_BT1_PWM_BASE))
Definition at line 282 of file bt.h.
Referenced by Bt_ConfigIOMode(), Bt_Pwc_Get32BitMeasureData(), BtDeInitNvic(), and BtInitNvic().
#define BT10 (*((volatile stc_btn_t *) FM_BT10_PWM_BASE))
Definition at line 292 of file bt.h.
Referenced by BtDeInitNvic(), and BtInitNvic().
#define BT11 (*((volatile stc_btn_t *) FM_BT11_PWM_BASE))
Definition at line 293 of file bt.h.
Referenced by BtDeInitNvic(), and BtInitNvic().
#define BT12 (*((volatile stc_btn_t *) FM_BT12_PWM_BASE))
Definition at line 294 of file bt.h.
Referenced by BtDeInitNvic(), and BtInitNvic().
#define BT13 (*((volatile stc_btn_t *) FM_BT13_PWM_BASE))
Definition at line 295 of file bt.h.
Referenced by BtDeInitNvic(), and BtInitNvic().
#define BT14 (*((volatile stc_btn_t *) FM_BT14_PWM_BASE))
Definition at line 296 of file bt.h.
Referenced by BtDeInitNvic(), and BtInitNvic().
#define BT15 (*((volatile stc_btn_t *) FM_BT15_PWM_BASE))
Definition at line 297 of file bt.h.
Referenced by BtDeInitNvic(), and BtInitNvic().
#define BT2 (*((volatile stc_btn_t *) FM_BT2_PWM_BASE))
Definition at line 283 of file bt.h.
Referenced by Bt_ConfigIOMode(), BtDeInitNvic(), and BtInitNvic().
#define BT3 (*((volatile stc_btn_t *) FM_BT3_PWM_BASE))
Definition at line 284 of file bt.h.
Referenced by Bt_ConfigIOMode(), Bt_Pwc_Get32BitMeasureData(), BtDeInitNvic(), and BtInitNvic().
#define BT4 (*((volatile stc_btn_t *) FM_BT4_PWM_BASE))
Definition at line 285 of file bt.h.
Referenced by Bt_ConfigIOMode(), BtDeInitNvic(), and BtInitNvic().
#define BT5 (*((volatile stc_btn_t *) FM_BT5_PWM_BASE))
Definition at line 286 of file bt.h.
Referenced by Bt_ConfigIOMode(), Bt_Pwc_Get32BitMeasureData(), BtDeInitNvic(), and BtInitNvic().
#define BT6 (*((volatile stc_btn_t *) FM_BT6_PWM_BASE))
Definition at line 287 of file bt.h.
Referenced by Bt_ConfigIOMode(), BtDeInitNvic(), and BtInitNvic().
#define BT7 (*((volatile stc_btn_t *) FM_BT7_PWM_BASE))
Definition at line 288 of file bt.h.
Referenced by Bt_ConfigIOMode(), Bt_Pwc_Get32BitMeasureData(), BtDeInitNvic(), and BtInitNvic().
#define BT8 (*((volatile stc_btn_t *) FM_BT8_PWM_BASE))
Definition at line 290 of file bt.h.
Referenced by BtDeInitNvic(), and BtInitNvic().
#define BT9 (*((volatile stc_btn_t *) FM_BT9_PWM_BASE))
Definition at line 291 of file bt.h.
Referenced by BtDeInitNvic(), and BtInitNvic().
#define BT_INSTANCE_COUNT
Value:
((PDL_PERIPHERAL_ENABLE_BT0 == PDL_ON) ? 1u : 0u)  + \
                                ((PDL_PERIPHERAL_ENABLE_BT1 == PDL_ON) ? 1u : 0u) + \
                                ((PDL_PERIPHERAL_ENABLE_BT2 == PDL_ON) ? 1u : 0u) + \
                                ((PDL_PERIPHERAL_ENABLE_BT3 == PDL_ON) ? 1u : 0u) + \
                                ((PDL_PERIPHERAL_ENABLE_BT4 == PDL_ON) ? 1u : 0u) + \
                                ((PDL_PERIPHERAL_ENABLE_BT5 == PDL_ON) ? 1u : 0u) + \
                                ((PDL_PERIPHERAL_ENABLE_BT6 == PDL_ON) ? 1u : 0u) + \
                                ((PDL_PERIPHERAL_ENABLE_BT7 == PDL_ON) ? 1u : 0u) + \
                                ((PDL_PERIPHERAL_ENABLE_BT8 == PDL_ON) ? 1u : 0u) + \
                                ((PDL_PERIPHERAL_ENABLE_BT9 == PDL_ON) ? 1u : 0u)  + \
                                ((PDL_PERIPHERAL_ENABLE_BT10 == PDL_ON) ? 1u : 0u) + \
                                ((PDL_PERIPHERAL_ENABLE_BT11 == PDL_ON) ? 1u : 0u) + \
                                ((PDL_PERIPHERAL_ENABLE_BT12 == PDL_ON) ? 1u : 0u) + \
                                ((PDL_PERIPHERAL_ENABLE_BT13 == PDL_ON) ? 1u : 0u) + \
                                ((PDL_PERIPHERAL_ENABLE_BT14 == PDL_ON) ? 1u : 0u) + \
                                ((PDL_PERIPHERAL_ENABLE_BT15 == PDL_ON) ? 1u : 0u)
Definition at line 300 of file bt.h.
Referenced by BtGetInternDataPtr().
#define PDL_INTERRUPT_BT_ACTIVE
Definition at line 326 of file bt.h.
#define stc_btn_t FM_BT_PWM_TypeDef
Definition at line 279 of file bt.h.
Typedef Documentation
typedef enum en_bt_instance_index en_bt_instance_index_t
Enumeration to define an index for each BT instance.
typedef enum en_bt_io_mode en_bt_io_mode_t
Enumeration to define BT IO mode.
typedef enum en_bt_timer_mode en_bt_timer_mode_t
Enumeration to define timer mode of BT.
typedef enum en_ppg_clock_pres en_ppg_clock_pres_t
Enumeration to define clock prescaler of PPG timer.
typedef enum en_ppg_ext_trig en_ppg_ext_trig_t
Enumeration to define external trigger of PPG.
typedef enum en_ppg_irq_sel en_ppg_irq_sel_t
enumeration to select the PPG interrupt
typedef enum en_ppg_mode en_ppg_mode_t
Enumeration to define PWM timer mode.
typedef enum en_ppg_output_mask en_ppg_output_mask_t
Enumeration to define the configuration of PPG output mask.
typedef enum en_ppg_output_polarity en_ppg_output_polarity_t
Enumeration to define PWM initial polarity.
typedef enum en_ppg_restart_enable en_ppg_restart_enable_t
Enumeration to define the configuration of PPG restart option.
typedef enum en_pwc_clock_pres en_pwc_clock_pres_t
Enumeration to define clock prescaler of PWC timer.
typedef enum en_pwc_irq_sel en_pwc_irq_sel_t
structure to select the PWC timer interrupt
typedef enum en_pwc_measure_edge en_pwc_measure_edge_t
Enumeration to define measure mode of PWC timer.
typedef enum en_pwc_mode en_pwc_mode_t
Enumeration to define PWC timer mode.
typedef enum en_pwc_timer_size en_pwc_timer_size_t
Enumeration to define Reload timer size.
typedef enum en_pwm_clock_pres en_pwm_clock_pres_t
Enumeration to define clock prescaler of PWM timer.
typedef enum en_pwm_ext_trig en_pwm_ext_trig_t
Enumeration to define external trigger of PWM.
typedef enum en_pwm_irq_sel en_pwm_irq_sel_t
enumeration to select the PWM interrupt
typedef enum en_pwm_mode en_pwm_mode_t
Enumeration to define PWM timer mode.
typedef enum en_pwm_output_mask en_pwm_output_mask_t
Enumeration to define the configuration of PWM output mask.
typedef enum en_pwm_output_polarity en_pwm_output_polarity_t
Enumeration to define PWM initial polarity.
typedef enum en_pwm_restart_enable en_pwm_restart_enable_t
Enumeration to define the configuration of PWM restart option.
typedef enum en_rt_clock_pres en_rt_clock_pres_t
Enumeration to define clock prescaler of Reload timer.
typedef enum en_rt_ext_trigger en_rt_ext_trigger_t
Enumeration to define external trigger of Reload timer.
typedef enum en_rt_irq_sel en_rt_irq_sel_t
enumeration to select the Reload timer interrupt
typedef enum en_rt_mode en_rt_mode_t
Enumeration to define Reload timer mode.
typedef enum en_rt_output_polarity en_rt_output_polarity_t
Enumeration to define Reload timer output initial polarity.
typedef enum en_rt_timer_size en_rt_timer_size_t
Enumeration to define Reload timer size.
typedef struct stc_bt_instance_data stc_bt_instance_data_t
BT instance data.
typedef struct stc_bt_intern_data stc_bt_intern_data_t
BT internal data.
typedef struct stc_bt_ppg_config stc_bt_ppg_config_t
Structure of PPG configuration.
typedef struct stc_bt_pwc_config stc_bt_pwc_config_t
Structure of PWC timer configuration.
typedef struct stc_bt_pwm_config stc_bt_pwm_config_t
Structure of PWM configuration.
typedef struct stc_bt_rt_config stc_bt_rt_config_t
Structure of Reload timer configuration.
typedef struct stc_ppg_int_cb stc_ppg_irq_cb_t
structure to set the PPG interrupt callback function
typedef struct stc_ppg_irq_en stc_ppg_irq_en_t
structure to enable the PPG interrupts
typedef struct stc_pwc_int_cb stc_pwc_irq_cb_t
structure to set the PWC timer interrupt callback function
typedef struct stc_pwc_irq_en stc_pwc_irq_en_t
structure to enable the PWC timer interrupts
typedef struct stc_pwm_int_cb stc_pwm_irq_cb_t
structure to set the PWM interrupt callback function
typedef struct stc_pwm_irq_en stc_pwm_irq_en_t
structure to enable the PWM interrupts
typedef struct stc_rt_irq_cb stc_rt_irq_cb_t
structure to set the Reload timer interrupt callback function
typedef struct stc_rt_irq_en stc_rt_irq_en_t
structure to enable the Reload timer interrupts
Enumeration Type Documentation
enum en_bt_instance_index
Enumeration to define an index for each BT instance.
Enumerator:
BtInstanceIndexBt0
Instance index of BT0.
BtInstanceIndexBt1
Instance index of BT1.
BtInstanceIndexBt2
Instance index of BT2.
BtInstanceIndexBt3
Instance index of BT3.
BtInstanceIndexBt4
Instance index of BT4.
BtInstanceIndexBt5
Instance index of BT5.
BtInstanceIndexBt6
Instance index of BT6.
BtInstanceIndexBt7
Instance index of BT7.
BtInstanceIndexBt8
Instance index of BT8.
BtInstanceIndexBt9
Instance index of BT9.
BtInstanceIndexBt10
Instance index of BT10.
BtInstanceIndexBt11
Instance index of BT11.
BtInstanceIndexBt12
Instance index of BT12.
BtInstanceIndexBt13
Instance index of BT13.
BtInstanceIndexBt14
Instance index of BT14.
BtInstanceIndexBt15
Instance index of BT15.
BtInstanceIndexMax
Maximum instance index.
Definition at line 337 of file bt.h.
enum en_bt_io_mode
Enumeration to define BT IO mode.
Enumerator:
BtIoMode0
BT IO mode 0.
BtIoMode1
BT IO mode 1.
BtIoMode2
BT IO mode 2.
BtIoMode3
BT IO mode 3.
BtIoMode4
BT IO mode 4.
BtIoMode5
BT IO mode 5.
BtIoMode6
BT IO mode 6.
BtIoMode7
BT IO mode 7.
BtIoMode8
BT IO mode 8.
Definition at line 394 of file bt.h.
enum en_bt_timer_mode
Enumeration to define timer mode of BT.
Enumerator:
BtResetMode
Reset mode.
BtPwmMode
PWM timer mode.
BtPpgMode
PPG timer mode.
BtRtMode
Reload timer mode.
BtPwcMode
PWC timer mode.
Definition at line 412 of file bt.h.
enum en_ppg_clock_pres
Enumeration to define clock prescaler of PPG timer.
Enumerator:
PpgPresNone
PPG prescaler clock: no division.
PpgPres1Div4
PPG prescaler clock: 1/4.
PpgPres1Div16
PPG prescaler clock: 1/16.
PpgPres1Div128
PPG prescaler clock: 1/128.
PpgPres1Div256
PPG prescaler clock: 1/256.
PpgPres1ExtClkRising
Use external clock and count at rising edge.
PpgPres1ExtClkFalling
Use external clock and count at falling edge.
PpgPres1ExtClkBoth
Use external clock and count at both edge.
PpgPres1Div512
PPG prescaler clock: 1/512.
PpgPres1Div1024
PPG prescaler clock: 1/1024.
PpgPres1Div2048
PPG prescaler clock: 1/2048.
Definition at line 559 of file bt.h.
enum en_ppg_ext_trig
Enumeration to define external trigger of PPG.
Enumerator:
PpgExtTrigDisable
Disable external trigger.
PpgExtTrigRising
Enable external trigger with rising edge.
PpgExtTrigFalling
Enable external trigger with falling edge.
PpgExtTrigBoth
Enable external trigger with both edge.
Definition at line 601 of file bt.h.
enum en_ppg_irq_sel
enumeration to select the PPG interrupt
Enumerator:
PpgTrigIrq
PPG trigger interrupt.
PpgUnderflowIrq
PPG underflow interrupt.
Definition at line 647 of file bt.h.
enum en_ppg_mode
Enumeration to define PWM timer mode.
Enumerator:
PpgContinuous
Continuous mode.
PpgOneshot
One-shot mode.
Definition at line 625 of file bt.h.
enum en_ppg_output_mask
Enumeration to define the configuration of PPG output mask.
Enumerator:
PpgOutputNormal
Output normal PPG wave.
PpgOutputMask
Mask PPG wave.
Definition at line 590 of file bt.h.
enum en_ppg_output_polarity
Enumeration to define PWM initial polarity.
Enumerator:
PpgPolarityLow
Initial polarity: low.
PpgPolarityHigh
Initial polarity: high.
Definition at line 614 of file bt.h.
enum en_ppg_restart_enable
Enumeration to define the configuration of PPG restart option.
Enumerator:
PpgRestartDisable
Disable PPG restart.
PpgRestartEnable
Enable PPG restart.
Definition at line 579 of file bt.h.
enum en_pwc_clock_pres
Enumeration to define clock prescaler of PWC timer.
Enumerator:
PwcPresNone
PWC timer prescaler clock: no division.
PwcPres1Div4
PWC timer prescaler clock: 1/4.
PwcPres1Div16
PWC timer prescaler clock: 1/16.
PwcPres1Div128
PWC timer prescaler clock: 1/128.
PwcPres1Div256
PWC timer prescaler clock: 1/256.
PwcPres1Div512
PWC timer prescaler clock: 1/512.
PwcPres1Div1024
PWC timer prescaler clock: 1/1024.
PwcPres1Div2048
PWC timer prescaler clock: 1/2048.
Definition at line 808 of file bt.h.
enum en_pwc_irq_sel
structure to select the PWC timer interrupt
Enumerator:
PwcMeasureCompleteIrq
PWC measure completion IRQ.
PwcMeasureOverflowIrq
PWC measure overflow IRQ.
Definition at line 872 of file bt.h.
enum en_pwc_measure_edge
Enumeration to define measure mode of PWC timer.
Enumerator:
PwcMeasureRisingToFalling
Measure between rising edge with falling edge.
PwcMeasureRisingToRising
Measure between rising edge with rising edge.
PwcMeasureFallingToFalling
Measure between falling edge with falling edge.
PwcMeasureEitherToEither
Measure between either edge with either edge.
PwcMeasureFallingToRising
Measure between falling edge with falling edge.
Definition at line 825 of file bt.h.
enum en_pwc_mode
Enumeration to define PWC timer mode.
Enumerator:
PwcContinuous
Continuous mode.
PwcOneshot
One-shot mode.
Definition at line 839 of file bt.h.
enum en_pwc_timer_size
Enumeration to define Reload timer size.
Enumerator:
PwcSize16Bit
16-bit mode
PwcSize32Bit
32-bit mode
Definition at line 850 of file bt.h.
enum en_pwm_clock_pres
Enumeration to define clock prescaler of PWM timer.
Enumerator:
PwmPresNone
PWM prescaler clock: no division.
PwmPres1Div4
PWM prescaler clock: 1/4.
PwmPres1Div16
PWM prescaler clock: 1/16.
PwmPres1Div128
PWM prescaler clock: 1/128.
PwmPres1Div256
PWM prescaler clock: 1/256.
PwmPres1ExtClkRising
Use external clock and count at rising edge.
PwmPres1ExtClkFalling
Use external clock and count at falling edge.
PwmPres1ExtClkBoth
Use external clock and count at both edge.
PwmPres1Div512
PWM prescaler clock: 1/512.
PwmPres1Div1024
PWM prescaler clock: 1/1024.
PwmPres1Div2048
PWM prescaler clock: 1/2048.
Definition at line 426 of file bt.h.
enum en_pwm_ext_trig
Enumeration to define external trigger of PWM.
Enumerator:
PwmExtTrigDisable
Disable external trigger.
PwmExtTrigRising
Enable external trigger with rising edge.
PwmExtTrigFalling
Enable external trigger with falling edge.
PwmExtTrigBoth
Enable external trigger with both edge.
Definition at line 468 of file bt.h.
enum en_pwm_irq_sel
enumeration to select the PWM interrupt
Enumerator:
PwmTrigIrq
PWM trigger interrupt.
PwmDutyMatchIrq
PWM duty match interrupt.
PwmUnderflowIrq
PWM underflow interrupt.
Definition at line 515 of file bt.h.
enum en_pwm_mode
Enumeration to define PWM timer mode.
Enumerator:
PwmContinuous
Continuous mode.
PwmOneshot
One-shot mode.
Definition at line 492 of file bt.h.
enum en_pwm_output_mask
Enumeration to define the configuration of PWM output mask.
Enumerator:
PwmOutputNormal
Output normal PWM wave.
PwmOutputMask
Mask PWM wave.
Definition at line 457 of file bt.h.
enum en_pwm_output_polarity
Enumeration to define PWM initial polarity.
Enumerator:
PwmPolarityLow
Initial polarity: low.
PwmPolarityHigh
Initial polarity: high.
Definition at line 481 of file bt.h.
enum en_pwm_restart_enable
Enumeration to define the configuration of PWM restart option.
Enumerator:
PwmRestartDisable
Disable PWM restart.
PwmRestartEnable
Enable PWM restart.
Definition at line 446 of file bt.h.
enum en_rt_clock_pres
Enumeration to define clock prescaler of Reload timer.
Enumerator:
RtPresNone
Reload timer prescaler clock: no division.
RtPres1Div4
Reload timer prescaler clock: 1/4.
RtPres1Div16
Reload timer prescaler clock: 1/16.
RtPres1Div128
Reload timer prescaler clock: 1/128.
RtPres1Div256
Reload timer prescaler clock: 1/256.
RtPres1ExtClkRising
Use external clock and count at rising edge.
RtPres1ExtClkFalling
Use external clock and count at falling edge.
RtPres1ExtClkBoth
Use external clock and count at both edge.
RtPres1Div512
Reload timer prescaler clock: 1/512.
RtPres1Div1024
Reload timer prescaler clock: 1/1024.
RtPres1Div2048
Reload timer prescaler clock: 1/2048.
Definition at line 688 of file bt.h.
enum en_rt_ext_trigger
Enumeration to define external trigger of Reload timer.
Enumerator:
RtExtTiggerDisable
Disable external trigger.
RtExtTiggerRisingEdge
Enable external trigger with rising edge.
RtExtTiggerFallingEdge
Enable external trigger with falling edge.
RtExtTiggerBothEdge
Enable external trigger with both edge.
RtExtTiggerLowLevel
Enable external trigger with low level.
RtExtTiggerHighLevel
Enable external trigger with high level.
Definition at line 708 of file bt.h.
enum en_rt_irq_sel
enumeration to select the Reload timer interrupt
Enumerator:
RtTrigIrq
Reload Timer trigger interrupt.
RtUnderflowIrq
Reload Timer underflow interrupt.
Definition at line 768 of file bt.h.
enum en_rt_mode
Enumeration to define Reload timer mode.
Enumerator:
RtReload
Reload mode.
RtOneshot
One-shot mode.
Definition at line 735 of file bt.h.
enum en_rt_output_polarity
Enumeration to define Reload timer output initial polarity.
Enumerator:
RtPolarityLow
Initial polarity: low.
RtPolarityHigh
Initial polarity: high.
Definition at line 724 of file bt.h.
enum en_rt_timer_size
Enumeration to define Reload timer size.
Enumerator:
RtSize16Bit
16-bit mode
RtSize32Bit
32-bit mode
Definition at line 746 of file bt.h.
Function Documentation
en_result_t Bt_ConfigIOMode (volatile FM_BT_PWM_TypeDef * pstcBt, en_bt_io_mode_t enIoMode)
Configure BT IO mode.
Parameters:
[in] pstcBt BT instance
[in] enIoMode BT IO mode
BtIoMode0 BT IO mode 0
BtIoMode1 BT IO mode 1
BtIoMode2 BT IO mode 2
BtIoMode3 BT IO mode 3
BtIoMode4 BT IO mode 4
BtIoMode5 BT IO mode 5
BtIoMode6 BT IO mode 6
BtIoMode7 BT IO mode 7
BtIoMode8 BT IO mode 8
Return values:
Ok BT IO mode has been set successfully
ErrorInvalidParameter If one of following cases match:
pstcBt == NULL
Other invalid configuration
Definition at line 596 of file bt.c.
References BT0, BT1, BT2, BT3, BT4, BT5, BT6, BT7, BtGetInternDataPtr(), and BtIoMode8.
void Bt_IrqHandler (volatile FM_BT_PWM_TypeDef * pstcBt, stc_bt_intern_data_t * pstcBtInternData)
BT interrupt service routine.
Parameters:
pstcBt BT instance
pstcBtInternData Pointer to BT internal data
Definition at line 202 of file bt.c.
References stc_bt_intern_data::pfnBit0IrqCb, stc_bt_intern_data::pfnBit1IrqCb, and stc_bt_intern_data::pfnBit2IrqCb.
en_result_t Bt_Ppg_ClrIrqFlag (volatile FM_BT_PWM_TypeDef * pstcBt, en_ppg_irq_sel_t enIrqSel)
Clear interrupt flag of PPG timer.
Parameters:
[in] pstcBt BT instance
[in] enIrqSel PPG timer interrupt type
PpgTrigIrq PPG trigger detection interrupt
PpgUnderflowIrq PPG underflow interrupt
Return values:
ErrorInvalidParameter If one of following cases match:
pstcBt == NULL
enIntType > PwmUnderflowInt
Ok Clear interrupt flag successfully
Definition at line 1527 of file bt.c.
References PpgTrigIrq, and PpgUnderflowIrq.
en_result_t Bt_Ppg_DeInit (volatile FM_BT_PWM_TypeDef * pstcBt, boolean_t bTouchNvic)
De-Initialize PPG function of BT.
Parameters:
[in] pstcBt BT instance
[in] bTouchNvic Touch NVIC or not
Return values:
Ok PPG function has been de-initialized successfully
ErrorInvalidParameter If one of following cases match:
pstcBt == NULL
Other invalid configuration
Definition at line 1298 of file bt.c.
References BtDeInitNvic(), and BtGetInternDataPtr().
en_result_t Bt_Ppg_DisableCount (volatile FM_BT_PWM_TypeDef * pstcBt)
Disable PPG timer counting.
Parameters:
[in] pstcBt BT instance
Return values:
Ok Disable PPG timer counting successfully
ErrorInvalidParameter pstcBt == NULL
Definition at line 1362 of file bt.c.
en_result_t Bt_Ppg_DisableIrq (volatile FM_BT_PWM_TypeDef * pstcBt, en_ppg_irq_sel_t enIrqSel)
Disable PPG timer interrupt.
Parameters:
[in] pstcBt BT instance
[in] enIrqSel PPG timer interrupt type
PpgTrigIrq PPG trigger detection interrupt
PpgUnderflowIrq PPG underflow interrupt
Return values:
Ok Disable PPG timer interrupt successfully
ErrorInvalidParameter If one of following cases match:
pstcBt == NULL
Other invalid configuration
Definition at line 1457 of file bt.c.
References PpgTrigIrq, and PpgUnderflowIrq.
en_result_t Bt_Ppg_EnableCount (volatile FM_BT_PWM_TypeDef * pstcBt)
Enable PPG timer counting.
Parameters:
[in] pstcBt BT instance
Return values:
Ok Enable PPG timer counting successfully
ErrorInvalidParameter pstcBt == NULL
Definition at line 1341 of file bt.c.
en_result_t Bt_Ppg_EnableIrq (volatile FM_BT_PWM_TypeDef * pstcBt, en_ppg_irq_sel_t enIrqSel)
Enable PPG timer interrupt.
Parameters:
[in] pstcBt BT instance
[in] enIrqSel PPG timer interrupt type
PpgTrigIrq PPG trigger detection interrupt
PpgUnderflowIrq PPG underflow interrupt
Return values:
Ok Enable PPG timer interrupt successfully
ErrorInvalidParameter If one of following cases match:
pstcBt == NULL
Other invalid configuration
Definition at line 1410 of file bt.c.
References BtGetInternDataPtr(), PpgTrigIrq, and PpgUnderflowIrq.
en_result_t Bt_Ppg_EnableSwTrig (volatile FM_BT_PWM_TypeDef * pstcBt)
Start PPG timer by software.
Parameters:
[in] pstcBt BT instance
Return values:
Ok Start PPG timer successfully
ErrorInvalidParameter pstcBt == NULL
Definition at line 1383 of file bt.c.
en_irq_flag_t Bt_Ppg_GetIrqFlag (volatile FM_BT_PWM_TypeDef * pstcBt, en_ppg_irq_sel_t enIrqSel)
Get interrupt flag of PPG timer.
Parameters:
[in] pstcBt BT instance
[in] enIrqSel PPG timer interrupt type
PpgTrigIrq PPG trigger detection interrupt
PpgUnderflowIrq PPG underflow interrupt
Return values:
PdlSet Interrupt flag is set
PdlClr Interrupt flag is clear
Definition at line 1494 of file bt.c.
References PdlClr, PdlSet, PpgTrigIrq, and PpgUnderflowIrq.
en_result_t Bt_Ppg_Init (volatile FM_BT_PWM_TypeDef * pstcBt, stc_bt_ppg_config_t * pstcPpgConfig)
Initialize PPG function of BT.
Parameters:
[in] pstcBt BT instance
[in] pstcPpgConfig Pointer to PPG configuration
Return values:
Ok PPG function has been configured successfully
ErrorInvalidParameter If one of following cases match:
pstcBt == NULL
Other invalid configuration
Definition at line 1139 of file bt.c.
References stc_ppg_irq_en::bPpgTrigIrq, stc_ppg_irq_en::bPpgUnderflowIrq, BtGetInternDataPtr(), BtInitNvic(), stc_bt_ppg_config::bTouchNvic, BtPpgMode, BtResetMode, stc_bt_ppg_config::enExtTrig, stc_bt_ppg_config::enMode, stc_bt_ppg_config::enOutputMask, stc_bt_ppg_config::enOutputPolarity, stc_bt_ppg_config::enPres, stc_bt_ppg_config::enRestartEn, stc_bt_intern_data::pfnBit0IrqCb, stc_bt_intern_data::pfnBit2IrqCb, stc_ppg_int_cb::pfnPpgTrigIrqCb, stc_ppg_int_cb::pfnPpgUnderflowIrqCb, PpgContinuous, PpgExtTrigBoth, PpgExtTrigDisable, PpgExtTrigFalling, PpgExtTrigRising, PpgOneshot, PpgOutputMask, PpgOutputNormal, PpgPolarityHigh, PpgPolarityLow, PpgPres1Div1024, PpgPres1Div128, PpgPres1Div16, PpgPres1Div2048, PpgPres1Div256, PpgPres1Div4, PpgPres1Div512, PpgPres1ExtClkBoth, PpgPres1ExtClkFalling, PpgPres1ExtClkRising, PpgPresNone, PpgRestartDisable, PpgRestartEnable, stc_bt_ppg_config::pstcPpgIrqCb, and stc_bt_ppg_config::pstcPpgIrqEn.
uint16_t Bt_Ppg_ReadCurCnt (volatile FM_BT_PWM_TypeDef * pstcBt)
Read current count value of PPG timer.
Parameters:
[in] pstcBt BT instance
Return values:
Current count value
Definition at line 1601 of file bt.c.
en_result_t Bt_Ppg_WriteHighWidthVal (volatile FM_BT_PWM_TypeDef * pstcBt, uint16_t u16Val)
Write high width count value of PPG timer.
Parameters:
[in] pstcBt BT instance
[in] u16Val High width count value
Return values:
Ok Write high width count value successfully
ErrorInvalidParameter pstcBt == NULL
Definition at line 1581 of file bt.c.
en_result_t Bt_Ppg_WriteLowWidthVal (volatile FM_BT_PWM_TypeDef * pstcBt, uint16_t u16Val)
Write low width count value of PPG timer.
Parameters:
[in] pstcBt BT instance
[in] u16Val Low width count value
Return values:
Ok Write low width count value successfully
ErrorInvalidParameter pstcBt == NULL
Definition at line 1559 of file bt.c.
en_result_t Bt_Pwc_ClrIrqFlag (volatile FM_BT_PWM_TypeDef * pstcBt, en_pwc_irq_sel_t enIrqSel)
Clear interrupt flag of PWC timer.
Parameters:
[in] pstcBt BT instance
[in] enIrqSel PWC timer interrupt type
PwcMeasureCompleteIrq PWC measure complete interrupt
PwcMeasureOverflowIrq PWC overflow interrupt
Return values:
ErrorInvalidParameter If one of following cases match:
pstcBt == NULL
enIntType > PwcMeasureOverflowIrq
Ok Clear interrupt flag successfully
Definition at line 2396 of file bt.c.
References PwcMeasureCompleteIrq, and PwcMeasureOverflowIrq.
en_result_t Bt_Pwc_DeInit (volatile FM_BT_PWM_TypeDef * pstcBt, boolean_t bTouchNvic)
De-Initialize PWC function of BT.
Parameters:
[in] pstcBt BT instance
[in] bTouchNvic Touch NVIC or not
Return values:
Ok PWC function has been de-initialized successfully
ErrorInvalidParameter If one of following cases match:
pstcBt == NULL
Other invalid configuration
Definition at line 2201 of file bt.c.
References BtDeInitNvic(), and BtGetInternDataPtr().
en_result_t Bt_Pwc_DisableCount (volatile FM_BT_PWM_TypeDef * pstcBt)
Disable PWC timer counting.
Parameters:
[in] pstcBt BT instance
Return values:
Ok Disable PWC timer counting successfully
ErrorInvalidParameter pstcBt == NULL
Definition at line 2263 of file bt.c.
en_result_t Bt_Pwc_DisableIrq (volatile FM_BT_PWM_TypeDef * pstcBt, en_pwc_irq_sel_t enIrqSel)
Disable PWC timer interrupt.
Parameters:
[in] pstcBt BT instance
[in] enIrqSel PWC timer interrupt type
PwcMeasureCompleteIrq PWC measure complete interrupt
PwcMeasureOverflowIrq PWC overflow interrupt
Return values:
Ok Disable PWC timer interrupt successfully
ErrorInvalidParameter If one of following cases match:
pstcBt == NULL
Other invalid configuration
Definition at line 2327 of file bt.c.
References PwcMeasureCompleteIrq, and PwcMeasureOverflowIrq.
en_result_t Bt_Pwc_EnableCount (volatile FM_BT_PWM_TypeDef * pstcBt)
Enable PWC timer counting.
Parameters:
[in] pstcBt BT instance
Return values:
Ok Enable PWC timer counting successfully
ErrorInvalidParameter pstcBt == NULL
Definition at line 2242 of file bt.c.
en_result_t Bt_Pwc_EnableIrq (volatile FM_BT_PWM_TypeDef * pstcBt, en_pwc_irq_sel_t enIrqSel)
Enable PWC timer interrupt.
Parameters:
[in] pstcBt BT instance
[in] enIrqSel PWC timer interrupt type
PwcMeasureCompleteIrq PWC measure complete interrupt
PwcMeasureOverflowIrq PWC overflow interrupt
Return values:
Ok Enable PWC timer interrupt successfully
ErrorInvalidParameter If one of following cases match:
pstcBt == NULL
Other invalid configuration
Definition at line 2290 of file bt.c.
References PwcMeasureCompleteIrq, and PwcMeasureOverflowIrq.
uint16_t Bt_Pwc_Get16BitMeasureData (volatile FM_BT_PWM_TypeDef * pstcBt)
Get 16 bits measure data of PWC timer.
This function reads measure data in 16-bit timer mode.
Parameters:
[in] pstcBt BT instance
Return values:
Measure data
Definition at line 2448 of file bt.c.
uint32_t Bt_Pwc_Get32BitMeasureData (volatile FM_BT_PWM_TypeDef * pstcBt)
Get 32 bits measure data of PWC timer.
This function reads measure data in 32-bit timer mode, the input BT instance should point to register base address of even channel.
Parameters:
[in] pstcBt BT instance
Return values:
Measure data
Definition at line 2466 of file bt.c.
References BT1, BT3, BT5, and BT7.
en_stat_flag_t Bt_Pwc_GetErrorFlag (volatile FM_BT_PWM_TypeDef * pstcBt)
Get error flag of PWC timer.
If the measured data is not read out when the next data is coming, the error flag will be set.
Parameters:
[in] pstcBt BT instance
Return values:
PdlSet Error flag is set
PdlClr Error flag is clear
Definition at line 2429 of file bt.c.
References PdlClr, and PdlSet.
en_irq_flag_t Bt_Pwc_GetIrqFlag (volatile FM_BT_PWM_TypeDef * pstcBt, en_pwc_irq_sel_t enIrqSel)
Get interrupt flag of PWC timer.
Parameters:
[in] pstcBt BT instance
[in] enIrqSel PWC timer interrupt type
PwcMeasureCompleteIrq PWC measure complete interrupt
PwcMeasureOverflowIrq PWC overflow interrupt
Return values:
PdlSet Interrupt flag is set
PdlClr Interrupt flag is clear
Definition at line 2363 of file bt.c.
References PdlClr, PdlSet, PwcMeasureCompleteIrq, and PwcMeasureOverflowIrq.
en_result_t Bt_Pwc_Init (volatile FM_BT_PWM_TypeDef * pstcBt, stc_bt_pwc_config_t * pstcPwcConfig)
Initialize PWC function of BT.
Parameters:
[in] pstcBt BT instance
[in] pstcPwcConfig Pointer to PWC configuration
Return values:
Ok PWC function has been configured successfully
ErrorInvalidParameter If one of following cases match:
pstcBt == NULL
Other invalid configuration
Definition at line 2065 of file bt.c.
References stc_pwc_irq_en::bPwcMeasureCompleteIrq, stc_pwc_irq_en::bPwcMeasureOverflowIrq, BtGetInternDataPtr(), BtInitNvic(), stc_bt_pwc_config::bTouchNvic, BtPwcMode, BtResetMode, stc_bt_pwc_config::enMeasureEdge, stc_bt_pwc_config::enMode, stc_bt_pwc_config::enPres, stc_bt_pwc_config::enSize, stc_bt_intern_data::pfnBit0IrqCb, stc_bt_intern_data::pfnBit2IrqCb, stc_pwc_int_cb::pfnPwcMeasureCompleteIrqCb, stc_pwc_int_cb::pfnPwcMeasureOverflowIrqCb, stc_bt_pwc_config::pstcPwcIrqCb, stc_bt_pwc_config::pstcPwcIrqEn, PwcContinuous, PwcMeasureEitherToEither, PwcMeasureFallingToFalling, PwcMeasureFallingToRising, PwcMeasureRisingToFalling, PwcMeasureRisingToRising, PwcOneshot, PwcPres1Div1024, PwcPres1Div128, PwcPres1Div16, PwcPres1Div2048, PwcPres1Div256, PwcPres1Div4, PwcPres1Div512, PwcPresNone, PwcSize16Bit, and PwcSize32Bit.
en_result_t Bt_Pwm_ClrIrqFlag (volatile FM_BT_PWM_TypeDef * pstcBt, en_pwm_irq_sel_t enIrqSel)
Clear interrupt flag of PWM timer.
Parameters:
[in] pstcBt BT instance
[in] enIrqSel PWM timer interrupt type
PwmTrigIrq PWM trigger detection interrupt
PwmDutyMatchIrq PWM duty match interrupt
PwmUnderflowIrq PWM underflow interrupt
Return values:
ErrorInvalidParameter If one of following cases match:
pstcBt == NULL
enIntType > PwmUnderflowInt
Ok Clear interrupt flag successfully
Definition at line 1043 of file bt.c.
References PwmDutyMatchIrq, PwmTrigIrq, and PwmUnderflowIrq.
en_result_t Bt_Pwm_DeInit (volatile FM_BT_PWM_TypeDef * pstcBt, boolean_t bTouchNvic)
De-Initialize PWM function of BT.
Parameters:
[in] pstcBt BT instance
[in] bTouchNvic Touch NVIC or not
Return values:
Ok PWM function has been de-initialized successfully
ErrorInvalidParameter If one of following cases match:
pstcBt == NULL
Other invalid configuration
Definition at line 811 of file bt.c.
References BtDeInitNvic(), and BtGetInternDataPtr().
en_result_t Bt_Pwm_DisableCount (volatile FM_BT_PWM_TypeDef * pstcBt)
Disable PWM timer counting.
Parameters:
[in] pstcBt BT instance
Return values:
Ok Disable PWM timer counting successfully
ErrorInvalidParameter pstcBt == NULL
Definition at line 875 of file bt.c.
en_result_t Bt_Pwm_DisableIrq (volatile FM_BT_PWM_TypeDef * pstcBt, en_pwm_irq_sel_t enIrqSel)
Disable PWM timer interrupt.
Parameters:
[in] pstcBt BT instance
[in] enIrqSel PWM timer interrupt type
PwmTrigIrq PWM trigger detection interrupt
PwmDutyMatchIrq PWM duty match interrupt
PwmUnderflowIrq PWM underflow interrupt
Return values:
Ok Disable PWM timer interrupt successfully
ErrorInvalidParameter If one of following cases match:
pstcBt == NULL
Other invalid configuration
Definition at line 965 of file bt.c.
References PwmDutyMatchIrq, PwmTrigIrq, and PwmUnderflowIrq.
en_result_t Bt_Pwm_EnableCount (volatile FM_BT_PWM_TypeDef * pstcBt)
Enable PWM timer counting.
Parameters:
[in] pstcBt BT instance
Return values:
Ok Enable PWM timer counting successfully
ErrorInvalidParameter pstcBt == NULL
Definition at line 854 of file bt.c.
en_result_t Bt_Pwm_EnableIrq (volatile FM_BT_PWM_TypeDef * pstcBt, en_pwm_irq_sel_t enIrqSel)
Enable PWM timer interrupt.
Parameters:
[in] pstcBt BT instance
[in] enIrqSel PWM timer interrupt type
PwmTrigIrq PWM trigger detection interrupt
PwmDutyMatchIrq PWM duty match interrupt
PwmUnderflowIrq PWM underflow interrupt
Return values:
Ok Enable PWM timer interrupt successfully
ErrorInvalidParameter If one of following cases match:
pstcBt == NULL
Other invalid configuration
Definition at line 924 of file bt.c.
References PwmDutyMatchIrq, PwmTrigIrq, and PwmUnderflowIrq.
en_result_t Bt_Pwm_EnableSwTrig (volatile FM_BT_PWM_TypeDef * pstcBt)
Start PWM timer by software.
Parameters:
[in] pstcBt BT instance
Return values:
Ok Start PWM timer successfully
ErrorInvalidParameter pstcBt == NULL
Definition at line 896 of file bt.c.
en_irq_flag_t Bt_Pwm_GetIrqFlag (volatile FM_BT_PWM_TypeDef * pstcBt, en_pwm_irq_sel_t enIrqSel)
Get interrupt flag of PWM timer.
Parameters:
[in] pstcBt BT instance
[in] enIrqSel PWM timer interrupt type
PwmTrigIrq PWM trigger detection interrupt
PwmDutyMatchIrq PWM duty match interrupt
PwmUnderflowIrq PWM underflow interrupt
Return values:
PdlSet Interrupt flag is set
PdlClr Interrupt flag is clear
Definition at line 1006 of file bt.c.
References PdlClr, PdlSet, PwmDutyMatchIrq, PwmTrigIrq, and PwmUnderflowIrq.
en_result_t Bt_Pwm_Init (volatile FM_BT_PWM_TypeDef * pstcBt, stc_bt_pwm_config_t * pstcPwmConfig)
Initialize PWM function of BT.
Parameters:
[in] pstcBt BT instance
[in] pstcPwmConfig Pointer to PWM configuration
Return values:
Ok PWM function has been configured successfully
ErrorInvalidParameter If one of following cases match:
pstcBt == NULL
Other invalid configuration
Definition at line 647 of file bt.c.
References stc_pwm_irq_en::bPwmDutyMatchIrq, stc_pwm_irq_en::bPwmTrigIrq, stc_pwm_irq_en::bPwmUnderflowIrq, BtGetInternDataPtr(), BtInitNvic(), stc_bt_pwm_config::bTouchNvic, BtPwmMode, BtResetMode, stc_bt_pwm_config::enExtTrig, stc_bt_pwm_config::enMode, stc_bt_pwm_config::enOutputMask, stc_bt_pwm_config::enOutputPolarity, stc_bt_pwm_config::enPres, stc_bt_pwm_config::enRestartEn, stc_bt_intern_data::pfnBit0IrqCb, stc_bt_intern_data::pfnBit1IrqCb, stc_bt_intern_data::pfnBit2IrqCb, stc_pwm_int_cb::pfnPwmDutyMatchIrqCb, stc_pwm_int_cb::pfnPwmTrigIrqCb, stc_pwm_int_cb::pfnPwmUnderflowIrqCb, stc_bt_pwm_config::pstcPwmIrqCb, stc_bt_pwm_config::pstcPwmIrqEn, PwmContinuous, PwmExtTrigBoth, PwmExtTrigDisable, PwmExtTrigFalling, PwmExtTrigRising, PwmOneshot, PwmOutputMask, PwmOutputNormal, PwmPolarityHigh, PwmPolarityLow, PwmPres1Div1024, PwmPres1Div128, PwmPres1Div16, PwmPres1Div2048, PwmPres1Div256, PwmPres1Div4, PwmPres1Div512, PwmPres1ExtClkBoth, PwmPres1ExtClkFalling, PwmPres1ExtClkRising, PwmPresNone, PwmRestartDisable, and PwmRestartEnable.
uint16_t Bt_Pwm_ReadCurCnt (volatile FM_BT_PWM_TypeDef * pstcBt)
Read current count value of PWM timer.
Parameters:
[in] pstcBt BT instance
Return values:
Current count value
Definition at line 1120 of file bt.c.
en_result_t Bt_Pwm_WriteCycleVal (volatile FM_BT_PWM_TypeDef * pstcBt, uint16_t u16Cycle)
Write Cycle value of PWM timer.
Parameters:
[in] pstcBt BT instance
[in] u16Cycle Cycle value
Return values:
Ok Write Cycle value successfully
ErrorInvalidParameter pstcBt == NULL
Definition at line 1078 of file bt.c.
en_result_t Bt_Pwm_WriteDutyVal (volatile FM_BT_PWM_TypeDef * pstcBt, uint16_t u16Duty)
Write duty value of PWM timer.
Parameters:
[in] pstcBt BT instance
[in] u16Duty Duty value
Return values:
Ok Write duty value successfully
ErrorInvalidParameter pstcBt == NUL
Definition at line 1100 of file bt.c.
en_result_t Bt_Rt_ClrIrqFlag (volatile FM_BT_PWM_TypeDef * pstcBt, en_rt_irq_sel_t enIrqSel)
Clear interrupt flag of Reload timer.
Parameters:
[in] pstcBt BT instance
[in] enIrqSel Reload timer interrupt type
RtTrigIrq Reload timer trigger detection flag
RtUnderflowIrq Reload timer underflow interrupt flag
Return values:
ErrorInvalidParameter If one of following cases match:
pstcBt == NULL
enIntType > RtUnderflowIrq
Ok Clear interrupt flag successfully
Definition at line 1995 of file bt.c.
References RtTrigIrq, and RtUnderflowIrq.
en_result_t Bt_Rt_DeInit (volatile FM_BT_PWM_TypeDef * pstcBt, boolean_t bTouchNvic)
De-Initialize RT function of BT.
Parameters:
[in] pstcBt BT instance
[in] bTouchNvic Touch NVIC or not
Return values:
Ok RT function has been de-initialized successfully
ErrorInvalidParameter If one of following cases match:
pstcBt == NULL
Other invalid configuration
Definition at line 1776 of file bt.c.
References BtDeInitNvic(), and BtGetInternDataPtr().
en_result_t Bt_Rt_DisableCount (volatile FM_BT_PWM_TypeDef * pstcBt)
Disable Reload timer counting.
Parameters:
[in] pstcBt BT instance
Return values:
Ok Disable RT timer counting successfully
ErrorInvalidParameter pstcBt == NULL
Definition at line 1840 of file bt.c.
en_result_t Bt_Rt_DisableIrq (volatile FM_BT_PWM_TypeDef * pstcBt, en_rt_irq_sel_t enIrqSel)
Disable Reload timer interrupt.
Parameters:
[in] pstcBt BT instance
[in] enIrqSel Reload Timer interrupt type
RtTrigIrq Reload timer trigger detection flag
RtUnderflowIrq Reload timer underflow interrupt flag
Return values:
Ok Disable Reload timer interrupt successfully
ErrorInvalidParameter If one of following cases match:
pstcBt == NULL
Other invalid configuration
Definition at line 1925 of file bt.c.
References RtTrigIrq, and RtUnderflowIrq.
en_result_t Bt_Rt_EnableCount (volatile FM_BT_PWM_TypeDef * pstcBt)
Enable Reload timer counting.
Parameters:
[in] pstcBt BT instance
Return values:
Ok Enable RT timer counting successfully
ErrorInvalidParameter pstcBt == NULL
Definition at line 1819 of file bt.c.
en_result_t Bt_Rt_EnableIrq (volatile FM_BT_PWM_TypeDef * pstcBt, en_rt_irq_sel_t enIrqSel)
Enable Reload timer interrupt.
Parameters:
[in] pstcBt BT instance
[in] enIrqSel Reload Timer interrupt type
RtTrigIrq Reload timer trigger detection flag
RtUnderflowIrq Reload timer underflow interrupt flag
Return values:
Ok Enable Reload timer interrupt successfully
ErrorInvalidParameter If one of following cases match:
pstcBt == NULL
Other invalid configuration
Definition at line 1888 of file bt.c.
References RtTrigIrq, and RtUnderflowIrq.
en_result_t Bt_Rt_EnableSwTrig (volatile FM_BT_PWM_TypeDef * pstcBt)
Start Reload timer by software.
Parameters:
[in] pstcBt BT instance
Return values:
Ok Start Reload timer successfully
ErrorInvalidParameter pstcBt == NULL
Definition at line 1861 of file bt.c.
en_irq_flag_t Bt_Rt_GetIrqFlag (volatile FM_BT_PWM_TypeDef * pstcBt, en_rt_irq_sel_t enIrqSel)
Get interrupt flag of Reload timer.
Parameters:
[in] pstcBt BT instance
[in] enIrqSel Reload timer interrupt type
RtTrigIrq Reload timer trigger detection flag
RtUnderflowIrq Reload timer underflow interrupt flag
Return values:
PdlSet Interrupt flag is set
PdlClr Interrupt flag is clear
Definition at line 1962 of file bt.c.
References PdlClr, PdlSet, RtTrigIrq, and RtUnderflowIrq.
en_result_t Bt_Rt_Init (volatile FM_BT_PWM_TypeDef * pstcBt, stc_bt_rt_config_t * pstcRtConfig)
Initialize RT function of BT.
Parameters:
[in] pstcBt BT instance
[in] pstcRtConfig Pointer to RT configuration
Return values:
Ok RT function has been configured successfully
ErrorInvalidParameter If one of following cases match:
pstcBt == NULL
Other invalid configuration
Definition at line 1620 of file bt.c.
References stc_rt_irq_en::bRtTrigIrq, stc_rt_irq_en::bRtUnderflowIrq, BtGetInternDataPtr(), BtInitNvic(), stc_bt_rt_config::bTouchNvic, BtResetMode, BtRtMode, stc_bt_rt_config::enExtTrig, stc_bt_rt_config::enMode, stc_bt_rt_config::enOutputPolarity, stc_bt_rt_config::enPres, stc_bt_rt_config::enSize, stc_bt_intern_data::pfnBit0IrqCb, stc_bt_intern_data::pfnBit2IrqCb, stc_rt_irq_cb::pfnRtTrigIrqCb, stc_rt_irq_cb::pfnRtUnderflowIrqCb, stc_bt_rt_config::pstcRtIrqCb, stc_bt_rt_config::pstcRtIrqEn, RtExtTiggerBothEdge, RtExtTiggerDisable, RtExtTiggerFallingEdge, RtExtTiggerHighLevel, RtExtTiggerLowLevel, RtExtTiggerRisingEdge, RtOneshot, RtPolarityHigh, RtPolarityLow, RtPres1Div1024, RtPres1Div128, RtPres1Div16, RtPres1Div2048, RtPres1Div256, RtPres1Div4, RtPres1Div512, RtPres1ExtClkBoth, RtPres1ExtClkFalling, RtPres1ExtClkRising, RtPresNone, RtReload, RtSize16Bit, and RtSize32Bit.
uint16_t Bt_Rt_ReadCurCnt (volatile FM_BT_PWM_TypeDef * pstcBt)
Read current count value of Reload timer.
Parameters:
[in] pstcBt BT instance
Return values:
Current count value
Definition at line 2046 of file bt.c.
en_result_t Bt_Rt_WriteCycleVal (volatile FM_BT_PWM_TypeDef * pstcBt, uint16_t u16Val)
Write count cycle of Reload timer.
Parameters:
[in] pstcBt BT instance
[in] u16Val Cycle value
Return values:
Ok Write count cycle successfully
ErrorInvalidParameter pstcBt == NULL
Definition at line 2026 of file bt.c.
void Bt_SetSimultaneousStart (uint16_t u16Value)
Set the Simultaneous Start register of Base timer.
This function is only valid in BTIO mode 5 and mode 6, otherwise don't use this function!
Parameters:
[in] u16Value Bit0 ----- Ch.0 Bit1 ----- Ch.1 ... Bit15 ----- Ch.15
Return values:
None
Definition at line 2495 of file bt.c.
static void BtDeInitNvic (volatile FM_BT_PWM_TypeDef * pstcBt) [static]
Clear NVIC Interrupt depending on BT instance.
Parameters:
pstcBt Pointer to BT instance
Definition at line 427 of file bt.c.
References BT0, BT1, BT10, BT11, BT12, BT13, BT14, BT15, BT2, BT3, BT4, BT5, BT6, BT7, BT8, BT9, and PDL_DEFAULT_INTERRUPT_LEVEL.
Referenced by Bt_Ppg_DeInit(), Bt_Pwc_DeInit(), Bt_Pwm_DeInit(), and Bt_Rt_DeInit().
static stc_bt_intern_data_t* BtGetInternDataPtr (volatile FM_BT_PWM_TypeDef * pstcBt) [static]
Return the internal data for a certain BT instance.
Parameters:
pstcBt Pointer to BT instance
Returns:
Pointer to internal data or NULL if instance is not enabled (or not known)
Definition at line 178 of file bt.c.
References BT_INSTANCE_COUNT, and stc_bt_instance_data::stcInternData.
Referenced by Bt_ConfigIOMode(), Bt_Ppg_DeInit(), Bt_Ppg_EnableIrq(), Bt_Ppg_Init(), Bt_Pwc_DeInit(), Bt_Pwc_Init(), Bt_Pwm_DeInit(), Bt_Pwm_Init(), Bt_Rt_DeInit(), and Bt_Rt_Init().
static void BtInitNvic (volatile FM_BT_PWM_TypeDef * pstcBt) [static]
Set NVIC Interrupt depending on BT instance.
Parameters:
pstcBt Pointer to BT instance
Definition at line 263 of file bt.c.
References BT0, BT1, BT10, BT11, BT12, BT13, BT14, BT15, BT2, BT3, BT4, BT5, BT6, BT7, BT8, BT9, PDL_IRQ_LEVEL_BT0_4, PDL_IRQ_LEVEL_BT1_5, PDL_IRQ_LEVEL_BT2_6, and PDL_IRQ_LEVEL_BT3_7.
Referenced by Bt_Ppg_Init(), Bt_Pwc_Init(), Bt_Pwm_Init(), and Bt_Rt_Init().
Variable Documentation
stc_bt_instance_data_t m_astcBtInstanceDataLut[((PDL_PERIPHERAL_ENABLE_BT0==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT1==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT2==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT3==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT4==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT5==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT6==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT7==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT8==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT9==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT10==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT11==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT12==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT13==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT14==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT15==PDL_ON)?1u:0u)]
Look-up table for all enabled BT instances and their internal data.
Definition at line 69 of file bt.c.
stc_bt_instance_data_t m_astcBtInstanceDataLut[((PDL_PERIPHERAL_ENABLE_BT0==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT1==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT2==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT3==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT4==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT5==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT6==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT7==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT8==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT9==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT10==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT11==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT12==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT13==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT14==PDL_ON)?1u:0u)+((PDL_PERIPHERAL_ENABLE_BT15==PDL_ON)?1u:0u)]
Look-up table for all enabled BT instances and their internal data.
Definition at line 69 of file bt.c.