PDL for FM Family: External Interrupts (EXINT)
External Interrupts (EXINT)
How to use External Interrupts.
Data Structures
struct stc_exint_config
EXINT configuration.
struct stc_exint_intern_data
Datatype for holding internal data needed for EXINT.
struct stc_exint_nmi_config
NMI configuration.
struct stc_exint_nmi_intern_data
Datatype for holding internal data needed for NMI.
Defines
#define PDL_EXINT_CHANNELS (32u)
#define PDL_EXINT_INSTANCE_COUNT
Typedefs
typedef enum en_exint_level en_exint_level_t
typedef struct stc_exint_config stc_exint_config_t
EXINT configuration.
typedef struct
stc_exint_intern_data stc_exint_intern_data_t
Datatype for holding internal data needed for EXINT.
typedef struct stc_exint_nmi_config stc_exint_nmi_config_t
NMI configuration.
typedef struct
stc_exint_nmi_intern_data stc_exint_nmi_intern_data_t
Datatype for holding internal data needed for NMI.
typedef enum
en_exint_instance_index en_exint_instance_index_t
Enumeration to define an index for each enabled external interrupt instance.
Enumerations
enum en_exint_level {
ExIntLowLevel = 0u, ExIntHighLevel = 1u, ExIntRisingEdge = 2u, ExIntFallingEdge = 3u,
ExIntBothEdge = 4u
}
enum en_exint_instance_index {
ExintInstanceIndexExint0, ExintInstanceIndexExint1, ExintInstanceIndexExint2, ExintInstanceIndexExint3,
ExintInstanceIndexExint4, ExintInstanceIndexExint5, ExintInstanceIndexExint6, ExintInstanceIndexExint7,
ExintInstanceIndexExint8, ExintInstanceIndexExint9, ExintInstanceIndexExint10, ExintInstanceIndexExint11,
ExintInstanceIndexExint12, ExintInstanceIndexExint13, ExintInstanceIndexExint14, ExintInstanceIndexExint15,
ExintInstanceIndexExint16, ExintInstanceIndexExint17, ExintInstanceIndexExint18, ExintInstanceIndexExint19,
ExintInstanceIndexExint20, ExintInstanceIndexExint21, ExintInstanceIndexExint22, ExintInstanceIndexExint23,
ExintInstanceIndexExint24, ExintInstanceIndexExint25, ExintInstanceIndexExint26, ExintInstanceIndexExint27,
ExintInstanceIndexExint28, ExintInstanceIndexExint29, ExintInstanceIndexExint30, ExintInstanceIndexExint31,
ExintInstanceIndexMax
}
Enumeration to define an index for each enabled external interrupt instance.
Functions
static uint8_t ExintGetInternDataIdx (uint8_t u8Channel)
Return the internal reference index of an Exint channel.
void Exint_IrqHandler (uint8_t u8Channel)
Interrupt handlers for External interrupts 0.
en_result_t Exint_Init (stc_exint_config_t *pstcConfig)
Init External Interrupts.
en_result_t Exint_DeInit (void)
Init External Interrupts.
en_result_t Exint_EnableChannel (uint8_t u8Channel)
Enable a single External Interrupt.
en_result_t Exint_DisableChannel (uint8_t u8Channel)
Disable a single External Interrupt.
en_result_t Exint_SetDetectMode (uint8_t u8Channel, en_exint_level_t enLevel)
Set external interrupt detect mode.
en_exint_level_t Exint_GetDetectMode (uint8_t u8Channel)
Get the external interrupt detection mode.
void Exint_Nmi_IrqHandler (void)
Interrupt handler for None-Maskable Interrupt (NMI)
en_result_t Exint_Nmi_Init (stc_exint_nmi_config_t *pstcConfig)
Init Non-Maskable Interrupt (NMI)
en_result_t Exint_Nmi_DeInit (stc_exint_nmi_config_t *pstcConfig)
De-Init Non-Maskable Interrupt (NMI)
Variables
stc_exint_intern_data_t stcExintInternData
const uint8_t cau8ExintReferenceLut [(32u)+1]
stc_exint_nmi_intern_data_t stcExintNMIInternData
stc_exint_intern_data_t stcExintInternData
stc_exint_nmi_intern_data_t stcExintNMIInternData
Detailed Description
How to use External Interrupts.
Provided functions of EXINT module:
Exint_Init()
Exint_DeInit()
Exint_EnableChannel()
Exint_DisableChannel()
Exint_SetDetectMode()
Exint_GetDetectMode()
Exint_Nmi_Init()
Exint_Nmi_DeInit()
With Exint_Init() the external interrupts are enabled as given in the configuration. Note, that both external interrupt groups (0-7 and 8-15) can be enabled individually.
If a single channel may be disabled and reenabled during runtime the functions Exint_DisableChannel() and Exint_EnableChannel() can be used.
Exint_SetDetectMode() is used to change the detect mode of single channel. And Exint_GetDetectMode gets the detect mode of single channel.
The external interrupts are disabled globally by Exint_DeInit().
Each channel provides an individually callback function which is handled in the interrupt service routine.
Exint_Nmi_Init() "initializes" the None-Maskable Interrupt, which means that the callback function is set to the dedicated internal data.
Define Documentation
#define PDL_EXINT_CHANNELS (32u)
Definition at line 113 of file exint.h.
Referenced by Exint_SetDetectMode(), and ExintGetInternDataIdx().
#define PDL_EXINT_INSTANCE_COUNT
Definition at line 114 of file exint.h.
Referenced by Exint_Init().
Typedef Documentation
typedef enum en_exint_instance_index en_exint_instance_index_t
Enumeration to define an index for each enabled external interrupt instance.
typedef enum en_exint_level en_exint_level_t
typedef struct stc_exint_config stc_exint_config_t
EXINT configuration.
External Interrupt configuration
The EXINT configuration
typedef struct stc_exint_intern_data stc_exint_intern_data_t
Datatype for holding internal data needed for EXINT.
typedef struct stc_exint_nmi_config stc_exint_nmi_config_t
NMI configuration.
The NMI configuration
typedef struct stc_exint_nmi_intern_data stc_exint_nmi_intern_data_t
Datatype for holding internal data needed for NMI.
Enumeration Type Documentation
enum en_exint_instance_index
Enumeration to define an index for each enabled external interrupt instance.
Enumerator:
ExintInstanceIndexExint0
ExintInstanceIndexExint1
ExintInstanceIndexExint2
ExintInstanceIndexExint3
ExintInstanceIndexExint4
ExintInstanceIndexExint5
ExintInstanceIndexExint6
ExintInstanceIndexExint7
ExintInstanceIndexExint8
ExintInstanceIndexExint9
ExintInstanceIndexExint10
ExintInstanceIndexExint11
ExintInstanceIndexExint12
ExintInstanceIndexExint13
ExintInstanceIndexExint14
ExintInstanceIndexExint15
ExintInstanceIndexExint16
ExintInstanceIndexExint17
ExintInstanceIndexExint18
ExintInstanceIndexExint19
ExintInstanceIndexExint20
ExintInstanceIndexExint21
ExintInstanceIndexExint22
ExintInstanceIndexExint23
ExintInstanceIndexExint24
ExintInstanceIndexExint25
ExintInstanceIndexExint26
ExintInstanceIndexExint27
ExintInstanceIndexExint28
ExintInstanceIndexExint29
ExintInstanceIndexExint30
ExintInstanceIndexExint31
ExintInstanceIndexMax
Definition at line 216 of file exint.h.
enum en_exint_level
Enumerator:
ExIntLowLevel
"L" level detection
ExIntHighLevel
"H" level detection
ExIntRisingEdge
Rising edge detection.
ExIntFallingEdge
Falling edge detection.
ExIntBothEdge
Both edge detection.
Definition at line 151 of file exint.h.
Function Documentation
en_result_t Exint_DeInit (void)
Init External Interrupts.
This function de-initializes all external interrupts.
Return values:
Ok EXINT sucessful disabled
Definition at line 572 of file exint.c.
References PDL_DEFAULT_INTERRUPT_LEVEL.
en_result_t Exint_DisableChannel (uint8_t u8Channel)
Disable a single External Interrupt.
This function disables a single External Interrupt.
Note:
This function does not clear stc_exint_config_t::abEnable[u8Channel]!
Parameters:
[in] u8Channel External Interrupt channel number
Return values:
Ok Channel enabled
ErrorInvalidParameter Invalid channel number or channel
Definition at line 794 of file exint.c.
en_result_t Exint_EnableChannel (uint8_t u8Channel)
Enable a single External Interrupt.
This function enables a single External Interrupt.
Note:
This function does not set stc_exint_config_t::abEnable[u8Channel]!
Parameters:
[in] u8Channel External Interrupt channel number
Return values:
Ok Channel enabled
ErrorInvalidParameter Invalid channel number
Definition at line 766 of file exint.c.
en_exint_level_t Exint_GetDetectMode (uint8_t u8Channel)
Get the external interrupt detection mode.
Parameters:
u8Channel 0~31
Return values:
ExIntLowLevel Low level is active edge for interrupt detection
ExIntHighLevel High level is active edge for interrupt detection
ExIntRisingEdge Rising edge is active edge for interrupt detection
ExIntFallingEdge Falling edge is active edge for interrupt detection
Definition at line 873 of file exint.c.
en_result_t Exint_Init (stc_exint_config_t * pstcConfig)
Init External Interrupts.
This function initializes the external interrupts according the given configuration.
Parameters:
[in] pstcConfig EXINT configuration parameters
Return values:
Ok EXINT initialized
ErrorInvalidParameter pstcConfig == NULL or Illegal mode
Definition at line 260 of file exint.c.
References stc_exint_config::abEnable, stc_exint_config::aenLevel, stc_exint_config::apfnExintCallback, stc_exint_intern_data::apfnExintCallback, stc_exint_config::bTouchNvic, cau8ExintReferenceLut, ExIntBothEdge, ExIntFallingEdge, ExIntHighLevel, ExIntLowLevel, ExIntRisingEdge, PDL_EXINT_INSTANCE_COUNT, PDL_IRQ_LEVEL_EXINT0_1, PDL_IRQ_LEVEL_EXINT12_13, PDL_IRQ_LEVEL_EXINT15, PDL_IRQ_LEVEL_EXINT2_3, PDL_IRQ_LEVEL_EXINT4_5, PDL_IRQ_LEVEL_EXINT6_7, and PDL_IRQ_LEVEL_EXINT8.
void Exint_IrqHandler (uint8_t u8Channel)
Interrupt handlers for External interrupts 0.
This function clears the cause bit and calls the callback function, if specified.
Definition at line 234 of file exint.c.
References stc_exint_intern_data::apfnExintCallback, and ExintGetInternDataIdx().
en_result_t Exint_Nmi_DeInit (stc_exint_nmi_config_t * pstcConfig)
De-Init Non-Maskable Interrupt (NMI)
This function de-initializes the NMI according to the given configuration.
Parameters:
[in] pstcConfig NMI configuration parameters
Return values:
Ok NMI initialized
ErrorInvalidParameter pstcConfig == NULL
Definition at line 947 of file exint.c.
References stc_exint_nmi_intern_data::pfnNmiCallback.
en_result_t Exint_Nmi_Init (stc_exint_nmi_config_t * pstcConfig)
Init Non-Maskable Interrupt (NMI)
This function initializes the NMI according to the given configuration.
Parameters:
[in] pstcConfig NMI configuration parameters
Return values:
Ok NMI initialized
ErrorInvalidParameter pstcConfig == NULL
Definition at line 917 of file exint.c.
References stc_exint_nmi_config::pfnNmiCallback, and stc_exint_nmi_intern_data::pfnNmiCallback.
void Exint_Nmi_IrqHandler (void)
Interrupt handler for None-Maskable Interrupt (NMI)
This function clears the cause bit and calls the NMI callback function, if specified.
Definition at line 891 of file exint.c.
References stc_exint_nmi_intern_data::pfnNmiCallback.
en_result_t Exint_SetDetectMode (uint8_t u8Channel, en_exint_level_t enLevel)
Set external interrupt detect mode.
Parameters:
u8Channel 0~31
enLevel
ExIntLowLevel Low level is active edge for interrupt detection
ExIntHighLevel High level is active edge for interrupt detection
ExIntRisingEdge Rising edge is active edge for interrupt detection
ExIntFallingEdge Falling edge is active edge for interrupt detection
Return values:
Ok Interreupt detection edge set normmally
ErrorInvalidParameter u8Ch > EXINT_MAX_CH_INDEX invalid setting for enLevel
Definition at line 822 of file exint.c.
References ExIntBothEdge, ExIntFallingEdge, ExIntHighLevel, ExIntLowLevel, ExIntRisingEdge, and PDL_EXINT_CHANNELS.
static uint8_t ExintGetInternDataIdx (uint8_t u8Channel) [static]
Return the internal reference index of an Exint channel.
Parameters:
u8Channel Exint channel number
Returns:
uint8_t Reference index (255 if not found or u8Channel > 31)
Definition at line 199 of file exint.c.
References cau8ExintReferenceLut, and PDL_EXINT_CHANNELS.
Referenced by Exint_IrqHandler().
Variable Documentation
const uint8_t cau8ExintReferenceLut[(32u)+1]
Definition at line 73 of file exint.c.
Referenced by Exint_Init(), and ExintGetInternDataIdx().
stc_exint_intern_data_t stcExintInternData
Definition at line 71 of file exint.c.
stc_exint_intern_data_t stcExintInternData
Definition at line 71 of file exint.c.
stc_exint_nmi_intern_data_t stcExintNMIInternData
Definition at line 177 of file exint.c.
stc_exint_nmi_intern_data_t stcExintNMIInternData
Definition at line 177 of file exint.c.