PDL for FM Family: High Speed Quad Serial Peripheral Interface (HSSPI)
High Speed Quad Serial Peripheral Interface (HSSPI)
Data Structures
struct stc_hsspi_config
(High speed) SPI configuration.
struct stc_hsspi_ext_device_config
(High Speed) SPI external device configuration.
struct stc_hsspi_command_sequencer_control
(High Speed) SPI command sequencer control command.
struct stc_hsspi_linked_data_list
(High Speed) SPI linked data list.
struct stc_hsspi_intern_data
HS-SPI instance internal data, storing internal information for each enabled HS-SPI instance.
struct stc_hsspi_instance_data
HS-SPI instance data type.
Defines
#define HS_SPI_MAX_FIFO_DEPTH (16u)
Transmit and receive maximum FIFO depth.
#define HSSPI_DIRECT_MODE_TX_RX_SINGLE_MODE (0x0u)
HS-SPI transfer mode (hardware).
#define HSSPI_DIRECT_MODE_RX_ONLY_SINGLE_MODE (0x4u)
Receive only, in single mode.
#define HSSPI_DIRECT_MODE_RX_ONLY_DUAL_MODE (0x5u)
Receive only, in dual mode.
#define HSSPI_DIRECT_MODE_RX_ONLY_QUAD_MODE (0x6u)
Receive only, in quad mode.
#define HSSPI_DIRECT_MODE_TX_ONLY_SINGLE_MODE (0x8u)
Transmit only, in single mode.
#define HSSPI_DIRECT_MODE_TX_ONLY_DUAL_MODE (0x9u)
Transmit only, in dual mode.
#define HSSPI_DIRECT_MODE_TX_ONLY_QUAD_MODE (0xAu)
Transmit only, in quad mode.
#define stc_hsspin_t FM_HSSPI_TypeDef
#define HSSPI0 (*((volatile stc_hsspin_t *) FM_HSSPI_BASE))
#define HS_SPI_INSTANCE_COUNT (uint8_t)(PDL_PERIPHERAL_ENABLE_HSSPI0 == PDL_ON)
#define HS_SPI_DEFAULT_CLK_DIV HsSpiClkDividerDiv8
Default clock divider (will set 20MHz @ 160MHz main clock)
#define HS_SPI_DEFAULT_MODE HsSpiClkHighOutFallingInRising
Default SPI mode.
#define HS_SPI_DEFAULT_PROTOCOL_MODE HsSpiProtocolModeLegacy
Default SPI protocol mode.
Typedefs
typedef enum en_hsspi_rx_status en_hsspi_rx_status_t
High speed SPI reception status.
typedef enum en_hsspi_tx_status en_hsspi_tx_status_t
High speed SPI transmission status.
typedef enum en_hsspi_fifo_width en_hsspi_fifo_width_t
High speed SPI FIFO width.
typedef enum en_hsspi_error en_hsspi_error_t
High speed SPI error types.
typedef void(* hsspi_rx_func_ptr_t)(en_hsspi_rx_status_t enRxStatus)
High speed SPI receive callback function.
typedef void(* hsspi_tx_func_ptr_t)(en_hsspi_tx_status_t enTxStatus)
High speed SPI transmit callback function.
typedef enum en_hsspi_clk_selection en_hsspi_clk_selection_t
High speed SPI clock selection.
typedef enum en_hsspi_bank_size en_hsspi_bank_size_t
High speed SPI bank size.
typedef enum
en_hsspi_command_sequencer_control en_hsspi_command_sequencer_control_t
High speed SPI command sequencer control.
typedef enum en_hsspi_clk_mode en_hsspi_clk_mode_t
High speed SPI clock mode.
typedef enum en_hsspi_protocol_mode en_hsspi_protocol_mode_t
SPI transfer mode (used for Command Sequencer and Direct mode)
typedef enum
en_hsspi_protocol_direction en_hsspi_protocol_direction_t
SPI transfer direction.
typedef enum en_hsspi_memory_type en_hsspi_memory_type_t
High speed SPI memory type.
typedef enum en_hsspi_clk_divider en_hsspi_clk_divider_t
High Speed SPI clock divider.
typedef enum en_hsspi_clk_delay en_hsspi_clk_delay_t
High Speed SPI clock delay.
typedef enum en_hsspi_mode en_hsspi_mode_t
High speed SPI mode.
typedef enum en_hsspi_endianess en_hsspi_endianess_t
High speed SPI endianess.
typedef enum
en_hsspi_transfer_protocol en_hsspi_transfer_protocol_t
High speed SPI transfer protocol.
typedef struct stc_hsspi_config stc_hsspi_config_t
(High speed) SPI configuration.
typedef struct
stc_hsspi_ext_device_config stc_hsspi_ext_device_config_t
(High Speed) SPI external device configuration.
typedef struct
stc_hsspi_command_sequencer_control stc_hsspi_command_sequencer_control_t
(High Speed) SPI command sequencer control command.
typedef struct
stc_hsspi_linked_data_list stc_hsspi_linked_data_list_t
(High Speed) SPI linked data list.
typedef enum
en_hsspi_instance_index en_hsspi_instance_index_t
Enumeration to define an index for each enabled HS-SPI instance.
typedef struct
stc_hsspi_intern_data stc_hsspi_intern_data_t
HS-SPI instance internal data, storing internal information for each enabled HS-SPI instance.
typedef struct
stc_hsspi_instance_data stc_hsspi_instance_data_t
HS-SPI instance data type.
Enumerations
enum en_hsspi_rx_status { HsSpiRxFinished = 0u, HsSpiRxFifoLow = 1u, HsSpiRxNoStatusAvailable = 2u }
High speed SPI reception status.
enum en_hsspi_tx_status { HsSpiModeError = -1, HsSpiTxFinished = 0u, HsSpiTxFifoLow = 1u, HsSpiTxNoStatusAvailable = 2u }
High speed SPI transmission status.
enum en_hsspi_fifo_width { HsSpiFifoWidth8 = 0u, HsSpiFifoWidth16 = 1u, HsSpiFifoWidth24 = 2u, HsSpiFifoWidth32 = 3u }
High speed SPI FIFO width.
enum en_hsspi_error {
HsSpiErrorNo = 0u, HsSpiErrorUnmappedMemoryAccessFault = 1u, HsSpiErrorWriteAccessFault = 2u, HsSpiErrorProtectionViolation = 3u,
HsSpiErrorDmaWrChBlockSize = 4u, HsSpiErrorDmaRdChBlockSize = 5u
}
High speed SPI error types.
enum en_hsspi_clk_selection { HsSpiClockAhb = 0u, HsSpiClockPeripheral = 1u }
High speed SPI clock selection.
enum en_hsspi_bank_size {
HsSpiBankSize8kB = 0x0u, HsSpiBankSize16kB = 0x1u, HsSpiBankSize32kB = 0x2u, HsSpiBankSize64kB = 0x3u,
HsSpiBankSize128kB = 0x4u, HsSpiBankSize256kB = 0x5u, HsSpiBankSize512kB = 0x6u, HsSpiBankSize1MB = 0x7u,
HsSpiBankSize2MB = 0x8u, HsSpiBankSize4MB = 0x9u, HsSpiBankSize8MB = 0xAu, HsSpiBankSize16MB = 0xBu,
HsSpiBankSize32MB = 0xCu, HsSpiBankSize64MB = 0xDu, HsSpiBankSize128MB = 0xEu, HsSpiBankSize256MB = 0xFu
}
High speed SPI bank size.
enum en_hsspi_command_sequencer_control {
HsSpiCmdTransmitAddress07To00 = 0u, HsSpiCmdTransmitAddress08To15 = 1u, HsSpiCmdTransmitAddress16To23 = 2u, HsSpiCmdTransmitAddress24To31 = 3u,
HsSpiCmdTransmitHighZStateByte = 4u, HsSpiCmdTransmitHighZStateNibble = 5u, HsSpiCmdTransmitData = 6u, HsSpiCmdEndOfList = 7u
}
High speed SPI command sequencer control.
enum en_hsspi_clk_mode {
HsSpiClkLowOutFallingInRising = 0u, HsSpiClkLowOutRisingInFalling = 1u, HsSpiClkHighOutRisingInFalling = 2u, HsSpiClkHighOutFallingInRising = 3u,
HsSpiClkLowOutFallingInFalling = 4u, HsSpiClkLowOutRisingInRising = 5u, HsSpiClkHighOutRisingInRising = 6u, HsSpiClkHighOutFallingInFalling = 7u
}
High speed SPI clock mode.
enum en_hsspi_protocol_mode { HsSpiProtocolModeSingle = 0u, HsSpiProtocolModeDual = 1u, HsSpiProtocolModeQuad = 2u }
SPI transfer mode (used for Command Sequencer and Direct mode)
enum en_hsspi_protocol_direction { HsSpiProtocolTxRx = 0u, HsSpiProtocolTx = 1u, HsSpiProtocolRx = 2u }
SPI transfer direction.
enum en_hsspi_memory_type { HsSpiFlash = 0u, HsSpiSram = 1u }
High speed SPI memory type.
enum en_hsspi_clk_divider {
HsSpiClkDividerDiv1 = 0u, HsSpiClkDividerDiv2 = 1u, HsSpiClkDividerDiv3 = 2u, HsSpiClkDividerDiv4 = 3u,
HsSpiClkDividerDiv5 = 4u, HsSpiClkDividerDiv6 = 5u, HsSpiClkDividerDiv7 = 6u, HsSpiClkDividerDiv8 = 7u,
HsSpiClkDividerDiv9 = 8u, HsSpiClkDividerDiv10 = 9u, HsSpiClkDividerDiv11 = 10u, HsSpiClkDividerDiv12 = 11u,
HsSpiClkDividerDiv13 = 12u, HsSpiClkDividerDiv14 = 13u, HsSpiClkDividerDiv15 = 14u, HsSpiClkDividerDiv16 = 15u,
HsSpiClkDividerDiv17 = 16u, HsSpiClkDividerDiv18 = 17u, HsSpiClkDividerDiv19 = 18u, HsSpiClkDividerDiv20 = 19u,
HsSpiClkDividerDiv21 = 20u, HsSpiClkDividerDiv22 = 21u, HsSpiClkDividerDiv23 = 22u, HsSpiClkDividerDiv24 = 23u,
HsSpiClkDividerDiv25 = 24u, HsSpiClkDividerDiv26 = 25u, HsSpiClkDividerDiv27 = 26u, HsSpiClkDividerDiv28 = 27u,
HsSpiClkDividerDiv29 = 28u, HsSpiClkDividerDiv30 = 29u, HsSpiClkDividerDiv31 = 30u, HsSpiClkDividerDiv32 = 31u,
HsSpiClkDividerDiv33 = 32u, HsSpiClkDividerDiv34 = 33u, HsSpiClkDividerDiv35 = 34u, HsSpiClkDividerDiv36 = 35u,
HsSpiClkDividerDiv37 = 36u, HsSpiClkDividerDiv38 = 37u, HsSpiClkDividerDiv39 = 38u, HsSpiClkDividerDiv40 = 39u,
HsSpiClkDividerDiv41 = 40u, HsSpiClkDividerDiv42 = 41u, HsSpiClkDividerDiv43 = 42u, HsSpiClkDividerDiv44 = 43u,
HsSpiClkDividerDiv45 = 44u, HsSpiClkDividerDiv46 = 45u, HsSpiClkDividerDiv47 = 46u, HsSpiClkDividerDiv48 = 47u,
HsSpiClkDividerDiv49 = 48u, HsSpiClkDividerDiv50 = 49u, HsSpiClkDividerDiv51 = 50u, HsSpiClkDividerDiv52 = 51u,
HsSpiClkDividerDiv53 = 52u, HsSpiClkDividerDiv54 = 53u, HsSpiClkDividerDiv55 = 54u, HsSpiClkDividerDiv56 = 55u,
HsSpiClkDividerDiv57 = 56u, HsSpiClkDividerDiv58 = 57u, HsSpiClkDividerDiv59 = 58u, HsSpiClkDividerDiv60 = 59u,
HsSpiClkDividerDiv61 = 60u, HsSpiClkDividerDiv62 = 61u, HsSpiClkDividerDiv63 = 62u, HsSpiClkDividerDiv64 = 63u,
HsSpiClkDividerDiv65 = 64u, HsSpiClkDividerDiv66 = 65u, HsSpiClkDividerDiv67 = 66u, HsSpiClkDividerDiv68 = 67u,
HsSpiClkDividerDiv69 = 68u, HsSpiClkDividerDiv70 = 69u, HsSpiClkDividerDiv71 = 70u, HsSpiClkDividerDiv72 = 71u,
HsSpiClkDividerDiv73 = 72u, HsSpiClkDividerDiv74 = 73u, HsSpiClkDividerDiv75 = 74u, HsSpiClkDividerDiv76 = 75u,
HsSpiClkDividerDiv77 = 76u, HsSpiClkDividerDiv78 = 77u, HsSpiClkDividerDiv79 = 78u, HsSpiClkDividerDiv80 = 79u,
HsSpiClkDividerDiv81 = 80u, HsSpiClkDividerDiv82 = 81u, HsSpiClkDividerDiv83 = 82u, HsSpiClkDividerDiv84 = 83u,
HsSpiClkDividerDiv85 = 84u, HsSpiClkDividerDiv86 = 85u, HsSpiClkDividerDiv87 = 86u, HsSpiClkDividerDiv88 = 87u,
HsSpiClkDividerDiv89 = 88u, HsSpiClkDividerDiv90 = 89u, HsSpiClkDividerDiv91 = 90u, HsSpiClkDividerDiv92 = 91u,
HsSpiClkDividerDiv93 = 92u, HsSpiClkDividerDiv94 = 93u, HsSpiClkDividerDiv95 = 94u, HsSpiClkDividerDiv96 = 95u,
HsSpiClkDividerDiv97 = 96u, HsSpiClkDividerDiv98 = 97u, HsSpiClkDividerDiv99 = 98u, HsSpiClkDividerDiv100 = 99u,
HsSpiClkDividerDiv101 = 100u, HsSpiClkDividerDiv102 = 101u, HsSpiClkDividerDiv103 = 102u, HsSpiClkDividerDiv104 = 103u,
HsSpiClkDividerDiv105 = 104u, HsSpiClkDividerDiv106 = 105u, HsSpiClkDividerDiv107 = 106u, HsSpiClkDividerDiv108 = 107u,
HsSpiClkDividerDiv109 = 108u, HsSpiClkDividerDiv110 = 109u, HsSpiClkDividerDiv111 = 110u, HsSpiClkDividerDiv112 = 111u,
HsSpiClkDividerDiv113 = 112u, HsSpiClkDividerDiv114 = 113u, HsSpiClkDividerDiv115 = 114u, HsSpiClkDividerDiv116 = 115u,
HsSpiClkDividerDiv117 = 116u, HsSpiClkDividerDiv118 = 117u, HsSpiClkDividerDiv119 = 118u, HsSpiClkDividerDiv120 = 119u,
HsSpiClkDividerDiv121 = 120u, HsSpiClkDividerDiv122 = 121u, HsSpiClkDividerDiv123 = 122u, HsSpiClkDividerDiv124 = 123u,
HsSpiClkDividerDiv125 = 124u, HsSpiClkDividerDiv126 = 125u, HsSpiClkDividerDiv127 = 126u, HsSpiClkDividerDiv128 = 127u,
HsSpiClkDividerDiv129 = 128u, HsSpiClkDividerDiv130 = 129u, HsSpiClkDividerDiv131 = 130u, HsSpiClkDividerDiv132 = 131u,
HsSpiClkDividerDiv133 = 132u, HsSpiClkDividerDiv134 = 133u, HsSpiClkDividerDiv135 = 134u, HsSpiClkDividerDiv136 = 135u,
HsSpiClkDividerDiv137 = 136u, HsSpiClkDividerDiv138 = 137u, HsSpiClkDividerDiv139 = 138u, HsSpiClkDividerDiv140 = 139u,
HsSpiClkDividerDiv141 = 140u, HsSpiClkDividerDiv142 = 141u, HsSpiClkDividerDiv143 = 142u, HsSpiClkDividerDiv144 = 143u,
HsSpiClkDividerDiv145 = 144u, HsSpiClkDividerDiv146 = 145u, HsSpiClkDividerDiv147 = 146u, HsSpiClkDividerDiv148 = 147u,
HsSpiClkDividerDiv149 = 148u, HsSpiClkDividerDiv150 = 149u, HsSpiClkDividerDiv151 = 150u, HsSpiClkDividerDiv152 = 151u,
HsSpiClkDividerDiv153 = 152u, HsSpiClkDividerDiv154 = 153u, HsSpiClkDividerDiv155 = 154u, HsSpiClkDividerDiv156 = 155u,
HsSpiClkDividerDiv157 = 156u, HsSpiClkDividerDiv158 = 157u, HsSpiClkDividerDiv159 = 158u, HsSpiClkDividerDiv160 = 159u,
HsSpiClkDividerDiv161 = 160u, HsSpiClkDividerDiv162 = 161u, HsSpiClkDividerDiv163 = 162u, HsSpiClkDividerDiv164 = 163u,
HsSpiClkDividerDiv165 = 164u, HsSpiClkDividerDiv166 = 165u, HsSpiClkDividerDiv167 = 166u, HsSpiClkDividerDiv168 = 167u,
HsSpiClkDividerDiv169 = 168u, HsSpiClkDividerDiv170 = 169u, HsSpiClkDividerDiv171 = 170u, HsSpiClkDividerDiv172 = 171u,
HsSpiClkDividerDiv173 = 172u, HsSpiClkDividerDiv174 = 173u, HsSpiClkDividerDiv175 = 174u, HsSpiClkDividerDiv176 = 175u,
HsSpiClkDividerDiv177 = 176u, HsSpiClkDividerDiv178 = 177u, HsSpiClkDividerDiv179 = 178u, HsSpiClkDividerDiv180 = 179u,
HsSpiClkDividerDiv181 = 180u, HsSpiClkDividerDiv182 = 181u, HsSpiClkDividerDiv183 = 182u, HsSpiClkDividerDiv184 = 183u,
HsSpiClkDividerDiv185 = 184u, HsSpiClkDividerDiv186 = 185u, HsSpiClkDividerDiv187 = 186u, HsSpiClkDividerDiv188 = 187u,
HsSpiClkDividerDiv189 = 188u, HsSpiClkDividerDiv190 = 189u, HsSpiClkDividerDiv191 = 190u, HsSpiClkDividerDiv192 = 191u,
HsSpiClkDividerDiv193 = 192u, HsSpiClkDividerDiv194 = 193u, HsSpiClkDividerDiv195 = 194u, HsSpiClkDividerDiv196 = 195u,
HsSpiClkDividerDiv197 = 196u, HsSpiClkDividerDiv198 = 197u, HsSpiClkDividerDiv199 = 198u, HsSpiClkDividerDiv200 = 199u,
HsSpiClkDividerDiv201 = 200u, HsSpiClkDividerDiv202 = 201u, HsSpiClkDividerDiv203 = 202u, HsSpiClkDividerDiv204 = 203u,
HsSpiClkDividerDiv205 = 204u, HsSpiClkDividerDiv206 = 205u, HsSpiClkDividerDiv207 = 206u, HsSpiClkDividerDiv208 = 207u,
HsSpiClkDividerDiv209 = 208u, HsSpiClkDividerDiv210 = 209u, HsSpiClkDividerDiv211 = 210u, HsSpiClkDividerDiv212 = 211u,
HsSpiClkDividerDiv213 = 212u, HsSpiClkDividerDiv214 = 213u, HsSpiClkDividerDiv215 = 214u, HsSpiClkDividerDiv216 = 215u,
HsSpiClkDividerDiv217 = 216u, HsSpiClkDividerDiv218 = 217u, HsSpiClkDividerDiv219 = 218u, HsSpiClkDividerDiv220 = 219u,
HsSpiClkDividerDiv221 = 220u, HsSpiClkDividerDiv222 = 221u, HsSpiClkDividerDiv223 = 222u, HsSpiClkDividerDiv224 = 223u,
HsSpiClkDividerDiv225 = 224u, HsSpiClkDividerDiv226 = 225u, HsSpiClkDividerDiv227 = 226u, HsSpiClkDividerDiv228 = 227u,
HsSpiClkDividerDiv229 = 228u, HsSpiClkDividerDiv230 = 229u, HsSpiClkDividerDiv231 = 230u, HsSpiClkDividerDiv232 = 231u,
HsSpiClkDividerDiv233 = 232u, HsSpiClkDividerDiv234 = 233u, HsSpiClkDividerDiv235 = 234u, HsSpiClkDividerDiv236 = 235u,
HsSpiClkDividerDiv237 = 236u, HsSpiClkDividerDiv238 = 237u, HsSpiClkDividerDiv239 = 238u, HsSpiClkDividerDiv240 = 239u,
HsSpiClkDividerDiv241 = 240u, HsSpiClkDividerDiv242 = 241u, HsSpiClkDividerDiv243 = 242u, HsSpiClkDividerDiv244 = 243u,
HsSpiClkDividerDiv245 = 244u, HsSpiClkDividerDiv246 = 245u, HsSpiClkDividerDiv247 = 246u, HsSpiClkDividerDiv248 = 247u,
HsSpiClkDividerDiv249 = 248u, HsSpiClkDividerDiv250 = 249u, HsSpiClkDividerDiv251 = 250u, HsSpiClkDividerDiv252 = 251u,
HsSpiClkDividerDiv253 = 252u, HsSpiClkDividerDiv254 = 253u, HsSpiClkDividerDiv255 = 254u, HsSpiClkDividerDiv256 = 255u
}
High Speed SPI clock divider.
enum en_hsspi_clk_delay { HsSpiClkStart1ClkAfterSlaveSelect = 0u, HsSpiClkStart2ClkAfterSlaveSelect = 1u, HsSpiClkStart3ClkAfterSlaveSelect = 2u, HsSpiClkStart4ClkAfterSlaveSelect = 3u }
High Speed SPI clock delay.
enum en_hsspi_mode { HsSpiModeDirect = 0u, HsSpiModeCmdSequencer = 1u }
High speed SPI mode.
enum en_hsspi_endianess { HsSpiBigEndian = 0u, HsSpiLittleEndian = 1u }
High speed SPI endianess.
enum en_hsspi_transfer_protocol { HsSpiSerialIf = 0u, HsSpiDualBitMode = 1u, HsSpiQuadBitMode = 2u, HsSpiSingleBitMode = 3u }
High speed SPI transfer protocol.
enum en_hsspi_instance_index { HsSpiInstanceIndexHsSpi0, HsSpiInstanceIndexMax }
Enumeration to define an index for each enabled HS-SPI instance.
Functions
static en_result_t HsSpi_ModuleEnable (volatile FM_HSSPI_TypeDef *pstcHsSpi)
Globally enable SPI module by setting bit MEN.
static en_result_t HsSpi_ModuleDisable (volatile FM_HSSPI_TypeDef *pstcHsSpi)
Globally disable HS-SPI module by clearing bit MEN.
static stc_hsspi_intern_data_t * HsSpiGetInternDataPtr (volatile FM_HSSPI_TypeDef *pstcHsSpi)
Return the internal data for a certain HS-SPI instance.
en_result_t HsSpi_Init (volatile FM_HSSPI_TypeDef *pstcHsSpi, const stc_hsspi_config_t *pstcConfig)
Initialisation of the HS-SPI module. FIFO width is limited to 8 bit and DMA is not supported in direct mode. The (high speed) SPI module is initialized in direct mode after call of Spi_Init().
en_result_t HsSpi_DeInit (volatile FM_HSSPI_TypeDef *pstcHsSpi)
De-Initializes the HS-SPI unit. All registers which are used by HS-SPI will be reset to their default value.
en_result_t HsSpi_SetMode (volatile FM_HSSPI_TypeDef *pstcHsSpi, en_hsspi_mode_t enMode, en_hsspi_protocol_mode_t enProtocolMode, en_hsspi_protocol_direction_t enProtocolDirection)
Set mode of the HS-SPI unit.
en_result_t HsSpi_SetExternalDeviceConfig (volatile FM_HSSPI_TypeDef *pstcHsSpi, uint8_t u8DeviceNumber, const stc_hsspi_ext_device_config_t *pstcConfig)
Configures the communication parameters of an external device.
en_result_t HsSpi_DirectModeTransferHalfDuplex (volatile FM_HSSPI_TypeDef *pstcHsSpi, uint8_t u8DeviceNumber, const uint8_t *pu8TxData, uint16_t u16TxSize, uint8_t *pu8RxData, uint16_t u16RxSize, boolean_t bEnableTxDmaRequest)
Transfers data in direct half-duplex mode.
en_result_t HsSpi_DirectModeTransferHalfDuplexList (volatile FM_HSSPI_TypeDef *pstcHsSpi, uint8_t u8DeviceNumber, const stc_hsspi_linked_data_list_t *pstcTxData, uint8_t *pu8RxData, uint16_t u16RxSize, boolean_t bEnableTxDmaRequest)
Transfers linked data in direct half-duplex mode.
en_result_t HsSpi_SetReadCommandSequence (volatile FM_HSSPI_TypeDef *pstcHsSpi, const stc_hsspi_command_sequencer_control_t *pstcCmdSequence)
Set read command sequence for command sequencer mode.
en_result_t HsSpi_SetWriteCommandSequence (volatile FM_HSSPI_TypeDef *pstcHsSpi, const stc_hsspi_command_sequencer_control_t *pstcCmdSequence)
Set write command sequence for command sequencer mode.
en_result_t HsSpi_MultiModeTransfer (volatile FM_HSSPI_TypeDef *pstcHsSpi, uint8_t u8DeviceNumber, const uint8_t *pu8LegacyData, uint8_t u8LegacyTxSize, const uint8_t *pu8TxData, uint8_t u8TxSize, uint8_t *pu8RxData, uint8_t u8RxSize)
Starts transfer in legacy mode and then switches to quad mode.
Variables
stc_hsspi_instance_data_t m_astcHsSpiInstanceDataLut [(uint8_t)(PDL_PERIPHERAL_ENABLE_HSSPI0==PDL_ON)]
Look-up table for all enabled I2S instances and their internal data.
stc_hsspi_instance_data_t m_astcHsSpiInstanceDataLut [(uint8_t)(PDL_PERIPHERAL_ENABLE_HSSPI0==PDL_ON)]
Look-up table for all enabled ADC instances and their internal data.
Detailed Description
Supporterd functions:
HsSpi_Init()
HsSpi_DeInit()
HsSpi_SetMode()
HsSpi_SetExternalDeviceConfig()
HsSpi_DirectModeTransferHalfDuplex()
HsSpi_DirectModeTransferHalfDuplexList()
HsSpi_SetReadCommandSequence()
HsSpi_SetWriteCommandSequence()
HsSpi_MultiModeTransfer()
This module covers functionality for all HS-SPI modules including the command sequencer mode. It supports the direct master mode for setting up the external device and command sequencer mode to read/write to memory devices attached to a HS-SPI peripheral.
Direct slave mode is not supported.
Standard initialization flow:
HsSpi_Init() (Direct mode is initially set after init.)
HsSpi_SetExternalDeviceConfig() (Multiple times, up to 4 devices possible.)
HsSpi_SetMode() (To change between direct and command sequencer mode.)
HsSpi_DirectModeTransferHalfDuplex()
HsSpi_DirectModeTransferHalfDuplexList()
HsSpi_MultiModeTransfer()
HsSpi_SetReadCommandSequence();
HsSpi_SetWriteCommandSequence();
Define Documentation
#define HS_SPI_DEFAULT_CLK_DIV HsSpiClkDividerDiv8
Default clock divider (will set 20MHz @ 160MHz main clock)
Definition at line 113 of file hsspi.h.
#define HS_SPI_DEFAULT_MODE HsSpiClkHighOutFallingInRising
Default SPI mode.
Definition at line 116 of file hsspi.h.
#define HS_SPI_DEFAULT_PROTOCOL_MODE HsSpiProtocolModeLegacy
Default SPI protocol mode.
Definition at line 119 of file hsspi.h.
#define HS_SPI_INSTANCE_COUNT (uint8_t)(PDL_PERIPHERAL_ENABLE_HSSPI0 == PDL_ON)
Definition at line 109 of file hsspi.h.
Referenced by HsSpiGetInternDataPtr().
#define HS_SPI_MAX_FIFO_DEPTH (16u)
Transmit and receive maximum FIFO depth.
Definition at line 71 of file hsspi.c.
Referenced by HsSpi_DirectModeTransferHalfDuplexList(), HsSpi_Init(), and HsSpi_MultiModeTransfer().
#define HSSPI0 (*((volatile stc_hsspin_t *) FM_HSSPI_BASE))
Definition at line 107 of file hsspi.h.
#define HSSPI_DIRECT_MODE_RX_ONLY_DUAL_MODE (0x5u)
Receive only, in dual mode.
Definition at line 81 of file hsspi.c.
#define HSSPI_DIRECT_MODE_RX_ONLY_QUAD_MODE (0x6u)
Receive only, in quad mode.
Definition at line 82 of file hsspi.c.
Referenced by HsSpi_MultiModeTransfer().
#define HSSPI_DIRECT_MODE_RX_ONLY_SINGLE_MODE (0x4u)
Receive only, in single mode.
Definition at line 80 of file hsspi.c.
#define HSSPI_DIRECT_MODE_TX_ONLY_DUAL_MODE (0x9u)
Transmit only, in dual mode.
Definition at line 84 of file hsspi.c.
#define HSSPI_DIRECT_MODE_TX_ONLY_QUAD_MODE (0xAu)
Transmit only, in quad mode.
Definition at line 85 of file hsspi.c.
Referenced by HsSpi_MultiModeTransfer().
#define HSSPI_DIRECT_MODE_TX_ONLY_SINGLE_MODE (0x8u)
Transmit only, in single mode.
Definition at line 83 of file hsspi.c.
Referenced by HsSpi_MultiModeTransfer().
#define HSSPI_DIRECT_MODE_TX_RX_SINGLE_MODE (0x0u)
HS-SPI transfer mode (hardware).
Selects hardware transfer mode of the HS-SPI core. Transmit and receive in single mode.
Definition at line 79 of file hsspi.c.
Referenced by HsSpi_DirectModeTransferHalfDuplexList().
#define stc_hsspin_t FM_HSSPI_TypeDef
Definition at line 106 of file hsspi.h.
Typedef Documentation
typedef enum en_hsspi_bank_size en_hsspi_bank_size_t
High speed SPI bank size.
This enum indicates the range of the AHB address space associated with each slave select line. It also indicates the size of each memory banks in the selected device.
typedef enum en_hsspi_clk_delay en_hsspi_clk_delay_t
High Speed SPI clock delay.
Slave-Select to Clock Delay of Peripheral 0 (SS2CD[1:0]). This bit is used only when HS-SPI is configured as SPI master in direct mode or in command sequencer mode. It defines a setup time for the slave device. By delaying the toggling of SCLK, SPI delays the data transmission (of slave) from the chip select active edge by a multiple of SCLK cycles.
If SPIn_PCC0~3:CPHA = '0', the delay between assertion of slave select and first edge on the SCLK is given by: (SS2CD + 0.5) number of clock periods of SCLK. If SPIn_PCC0~3:CPHA = '1', the delay between assertion of slave select and first edge on the SCLK is given by: (SS2CD) number of clock periods of SCLK.
When the slave select becomes active, the slave has to prepare data transfer within the delay time de?ned by SS2CD bits.
typedef enum en_hsspi_clk_divider en_hsspi_clk_divider_t
High Speed SPI clock divider.
This field decides the clock division ratio of the internal clock divider.
typedef enum en_hsspi_clk_mode en_hsspi_clk_mode_t
High speed SPI clock mode.
The API must use the enum with the attributes that match the communication attributes of the serial peripheral that is to be interfaced on the corresponding slave select line.
typedef enum en_hsspi_clk_selection en_hsspi_clk_selection_t
High speed SPI clock selection.
The internal clock divider can divide either the AHB clock (i.e. HCLK) or the peripheral clock (i.e. PCLKn).
typedef enum en_hsspi_command_sequencer_control en_hsspi_command_sequencer_control_t
High speed SPI command sequencer control.
This enum is used to configure the phases of the serial transaction generated by the command sequencer for memory read or write operations.
typedef enum en_hsspi_endianess en_hsspi_endianess_t
High speed SPI endianess.
typedef enum en_hsspi_error en_hsspi_error_t
High speed SPI error types.
These error codes will be returned by HsSpi_HandleError() function.
typedef enum en_hsspi_fifo_width en_hsspi_fifo_width_t
High speed SPI FIFO width.
Width of FIFO. Depending on the configured width, the usable size of the shift register in the SPI core also changes.
typedef enum en_hsspi_instance_index en_hsspi_instance_index_t
Enumeration to define an index for each enabled HS-SPI instance.
typedef enum en_hsspi_memory_type en_hsspi_memory_type_t
High speed SPI memory type.
Serial SRAM or Serial Flash Memory Type Select (SRAM) This bit should only be set if serial SRAM devices are memory mapped through (HS)SPI.
typedef enum en_hsspi_mode en_hsspi_mode_t
High speed SPI mode.
Used to switch between direct and command sequencer mode.
typedef enum en_hsspi_protocol_direction en_hsspi_protocol_direction_t
SPI transfer direction.
typedef enum en_hsspi_protocol_mode en_hsspi_protocol_mode_t
SPI transfer mode (used for Command Sequencer and Direct mode)
Selects transfer protocol mode. The direct mode is active after call of HsSpi_Init, and can be changed by function HsSpi_SetMode(). RxTx-,RxOnly- and TxOnly modes will be selected automatically by the transfer functions.
typedef enum en_hsspi_rx_status en_hsspi_rx_status_t
High speed SPI reception status.
Status value used either in SpiRxStatus callback function or in HsSpi_GetDirectModeRxStatus() function (for direct mode polling operation).
typedef enum en_hsspi_transfer_protocol en_hsspi_transfer_protocol_t
High speed SPI transfer protocol.
typedef enum en_hsspi_tx_status en_hsspi_tx_status_t
High speed SPI transmission status.
Status value used either in SpiTxStatus callback function or in HsSpi_GetDirectModeTxStatus() function (for direct mode polling operation).
typedef void(* hsspi_rx_func_ptr_t)(en_hsspi_rx_status_t enRxStatus)
High speed SPI receive callback function.
< Prototype for transmit status callback function
Definition at line 192 of file hsspi.h.
typedef void(* hsspi_tx_func_ptr_t)(en_hsspi_tx_status_t enTxStatus)
High speed SPI transmit callback function.
< Prototype for transmit status callback function
Definition at line 199 of file hsspi.h.
typedef struct stc_hsspi_command_sequencer_control stc_hsspi_command_sequencer_control_t
(High Speed) SPI command sequencer control command.
Used to configure the command sequence with defined parameters or with user defined data values (by setting enCommand to HsSpiCmdTransmitData).
typedef struct stc_hsspi_config stc_hsspi_config_t
(High speed) SPI configuration.
Struct used for initialisation of SSPI module in direct mode, direct and command sequence related parameter can be configured at once, afterwards it is possible to switch between modes with HsSpi_SetMode().
typedef struct stc_hsspi_ext_device_config stc_hsspi_ext_device_config_t
(High Speed) SPI external device configuration.
This struct is used to configure 1 of 4 possible devices by calling the HsSpi_SetExternalDeviceConfig() function.
typedef struct stc_hsspi_instance_data stc_hsspi_instance_data_t
HS-SPI instance data type.
typedef struct stc_hsspi_intern_data stc_hsspi_intern_data_t
HS-SPI instance internal data, storing internal information for each enabled HS-SPI instance.
typedef struct stc_hsspi_linked_data_list stc_hsspi_linked_data_list_t
(High Speed) SPI linked data list.
Used to connect various different buffer sources that shall be transmitted during the same transaction, e.g. Ethernet packet with different buffers for for the ISO/OSI layer headers (external Ethernet MAC connected via HS-SPI).
Enumeration Type Documentation
enum en_hsspi_bank_size
High speed SPI bank size.
This enum indicates the range of the AHB address space associated with each slave select line. It also indicates the size of each memory banks in the selected device.
Enumerator:
HsSpiBankSize8kB
8 kB
HsSpiBankSize16kB
16 kB
HsSpiBankSize32kB
32 kB
HsSpiBankSize64kB
64 kB
HsSpiBankSize128kB
128 kB
HsSpiBankSize256kB
256 kB
HsSpiBankSize512kB
512 kB
HsSpiBankSize1MB
1 MB
HsSpiBankSize2MB
2 MB
HsSpiBankSize4MB
4 MB
HsSpiBankSize8MB
8 MB
HsSpiBankSize16MB
16 MB
HsSpiBankSize32MB
32 MB
HsSpiBankSize64MB
64 MB
HsSpiBankSize128MB
128 MB
HsSpiBankSize256MB
256 MB
Definition at line 222 of file hsspi.h.
enum en_hsspi_clk_delay
High Speed SPI clock delay.
Slave-Select to Clock Delay of Peripheral 0 (SS2CD[1:0]). This bit is used only when HS-SPI is configured as SPI master in direct mode or in command sequencer mode. It defines a setup time for the slave device. By delaying the toggling of SCLK, SPI delays the data transmission (of slave) from the chip select active edge by a multiple of SCLK cycles.
If SPIn_PCC0~3:CPHA = '0', the delay between assertion of slave select and first edge on the SCLK is given by: (SS2CD + 0.5) number of clock periods of SCLK. If SPIn_PCC0~3:CPHA = '1', the delay between assertion of slave select and first edge on the SCLK is given by: (SS2CD) number of clock periods of SCLK.
When the slave select becomes active, the slave has to prepare data transfer within the delay time de?ned by SS2CD bits.
Enumerator:
HsSpiClkStart1ClkAfterSlaveSelect
HsSpiClkStart2ClkAfterSlaveSelect
HsSpiClkStart3ClkAfterSlaveSelect
HsSpiClkStart4ClkAfterSlaveSelect
Definition at line 611 of file hsspi.h.
enum en_hsspi_clk_divider
High Speed SPI clock divider.
This field decides the clock division ratio of the internal clock divider.
Enumerator:
HsSpiClkDividerDiv1
Clock divider is 1.
HsSpiClkDividerDiv2
Clock divider is 2.
HsSpiClkDividerDiv3
Clock divider is 3.
HsSpiClkDividerDiv4
Clock divider is 4.
HsSpiClkDividerDiv5
Clock divider is 5.
HsSpiClkDividerDiv6
Clock divider is 6.
HsSpiClkDividerDiv7
Clock divider is 7.
HsSpiClkDividerDiv8
Clock divider is 8.
HsSpiClkDividerDiv9
Clock divider is 9.
HsSpiClkDividerDiv10
Clock divider is 10.
HsSpiClkDividerDiv11
Clock divider is 11.
HsSpiClkDividerDiv12
Clock divider is 12.
HsSpiClkDividerDiv13
Clock divider is 13.
HsSpiClkDividerDiv14
Clock divider is 14.
HsSpiClkDividerDiv15
Clock divider is 15.
HsSpiClkDividerDiv16
Clock divider is 16.
HsSpiClkDividerDiv17
Clock divider is 17.
HsSpiClkDividerDiv18
Clock divider is 18.
HsSpiClkDividerDiv19
Clock divider is 19.
HsSpiClkDividerDiv20
Clock divider is 20.
HsSpiClkDividerDiv21
Clock divider is 21.
HsSpiClkDividerDiv22
Clock divider is 22.
HsSpiClkDividerDiv23
Clock divider is 23.
HsSpiClkDividerDiv24
Clock divider is 24.
HsSpiClkDividerDiv25
Clock divider is 25.
HsSpiClkDividerDiv26
Clock divider is 26.
HsSpiClkDividerDiv27
Clock divider is 27.
HsSpiClkDividerDiv28
Clock divider is 28.
HsSpiClkDividerDiv29
Clock divider is 29.
HsSpiClkDividerDiv30
Clock divider is 30.
HsSpiClkDividerDiv31
Clock divider is 31.
HsSpiClkDividerDiv32
Clock divider is 32.
HsSpiClkDividerDiv33
Clock divider is 33.
HsSpiClkDividerDiv34
Clock divider is 34.
HsSpiClkDividerDiv35
Clock divider is 35.
HsSpiClkDividerDiv36
Clock divider is 36.
HsSpiClkDividerDiv37
Clock divider is 37.
HsSpiClkDividerDiv38
Clock divider is 38.
HsSpiClkDividerDiv39
Clock divider is 39.
HsSpiClkDividerDiv40
Clock divider is 40.
HsSpiClkDividerDiv41
Clock divider is 41.
HsSpiClkDividerDiv42
Clock divider is 42.
HsSpiClkDividerDiv43
Clock divider is 43.
HsSpiClkDividerDiv44
Clock divider is 44.
HsSpiClkDividerDiv45
Clock divider is 45.
HsSpiClkDividerDiv46
Clock divider is 46.
HsSpiClkDividerDiv47
Clock divider is 47.
HsSpiClkDividerDiv48
Clock divider is 48.
HsSpiClkDividerDiv49
Clock divider is 49.
HsSpiClkDividerDiv50
Clock divider is 50.
HsSpiClkDividerDiv51
Clock divider is 51.
HsSpiClkDividerDiv52
Clock divider is 52.
HsSpiClkDividerDiv53
Clock divider is 53.
HsSpiClkDividerDiv54
Clock divider is 54.
HsSpiClkDividerDiv55
Clock divider is 55.
HsSpiClkDividerDiv56
Clock divider is 56.
HsSpiClkDividerDiv57
Clock divider is 57.
HsSpiClkDividerDiv58
Clock divider is 58.
HsSpiClkDividerDiv59
Clock divider is 59.
HsSpiClkDividerDiv60
Clock divider is 60.
HsSpiClkDividerDiv61
Clock divider is 61.
HsSpiClkDividerDiv62
Clock divider is 62.
HsSpiClkDividerDiv63
Clock divider is 63.
HsSpiClkDividerDiv64
Clock divider is 64.
HsSpiClkDividerDiv65
Clock divider is 65.
HsSpiClkDividerDiv66
Clock divider is 66.
HsSpiClkDividerDiv67
Clock divider is 67.
HsSpiClkDividerDiv68
Clock divider is 68.
HsSpiClkDividerDiv69
Clock divider is 69.
HsSpiClkDividerDiv70
Clock divider is 70.
HsSpiClkDividerDiv71
Clock divider is 71.
HsSpiClkDividerDiv72
Clock divider is 72.
HsSpiClkDividerDiv73
Clock divider is 73.
HsSpiClkDividerDiv74
Clock divider is 74.
HsSpiClkDividerDiv75
Clock divider is 75.
HsSpiClkDividerDiv76
Clock divider is 76.
HsSpiClkDividerDiv77
Clock divider is 77.
HsSpiClkDividerDiv78
Clock divider is 78.
HsSpiClkDividerDiv79
Clock divider is 79.
HsSpiClkDividerDiv80
Clock divider is 80.
HsSpiClkDividerDiv81
Clock divider is 81.
HsSpiClkDividerDiv82
Clock divider is 82.
HsSpiClkDividerDiv83
Clock divider is 83.
HsSpiClkDividerDiv84
Clock divider is 84.
HsSpiClkDividerDiv85
Clock divider is 85.
HsSpiClkDividerDiv86
Clock divider is 86.
HsSpiClkDividerDiv87
Clock divider is 87.
HsSpiClkDividerDiv88
Clock divider is 88.
HsSpiClkDividerDiv89
Clock divider is 89.
HsSpiClkDividerDiv90
Clock divider is 90.
HsSpiClkDividerDiv91
Clock divider is 91.
HsSpiClkDividerDiv92
Clock divider is 92.
HsSpiClkDividerDiv93
Clock divider is 93.
HsSpiClkDividerDiv94
Clock divider is 94.
HsSpiClkDividerDiv95
Clock divider is 95.
HsSpiClkDividerDiv96
Clock divider is 96.
HsSpiClkDividerDiv97
Clock divider is 97.
HsSpiClkDividerDiv98
Clock divider is 98.
HsSpiClkDividerDiv99
Clock divider is 99.
HsSpiClkDividerDiv100
Clock divider is 100.
HsSpiClkDividerDiv101
Clock divider is 101.
HsSpiClkDividerDiv102
Clock divider is 102.
HsSpiClkDividerDiv103
Clock divider is 103.
HsSpiClkDividerDiv104
Clock divider is 104.
HsSpiClkDividerDiv105
Clock divider is 105.
HsSpiClkDividerDiv106
Clock divider is 106.
HsSpiClkDividerDiv107
Clock divider is 107.
HsSpiClkDividerDiv108
Clock divider is 108.
HsSpiClkDividerDiv109
Clock divider is 109.
HsSpiClkDividerDiv110
Clock divider is 110.
HsSpiClkDividerDiv111
Clock divider is 111.
HsSpiClkDividerDiv112
Clock divider is 112.
HsSpiClkDividerDiv113
Clock divider is 113.
HsSpiClkDividerDiv114
Clock divider is 114.
HsSpiClkDividerDiv115
Clock divider is 115.
HsSpiClkDividerDiv116
Clock divider is 116.
HsSpiClkDividerDiv117
Clock divider is 117.
HsSpiClkDividerDiv118
Clock divider is 118.
HsSpiClkDividerDiv119
Clock divider is 119.
HsSpiClkDividerDiv120
Clock divider is 120.
HsSpiClkDividerDiv121
Clock divider is 121.
HsSpiClkDividerDiv122
Clock divider is 122.
HsSpiClkDividerDiv123
Clock divider is 123.
HsSpiClkDividerDiv124
Clock divider is 124.
HsSpiClkDividerDiv125
Clock divider is 125.
HsSpiClkDividerDiv126
Clock divider is 126.
HsSpiClkDividerDiv127
Clock divider is 127.
HsSpiClkDividerDiv128
Clock divider is 128.
HsSpiClkDividerDiv129
Clock divider is 129.
HsSpiClkDividerDiv130
Clock divider is 130.
HsSpiClkDividerDiv131
Clock divider is 131.
HsSpiClkDividerDiv132
Clock divider is 132.
HsSpiClkDividerDiv133
Clock divider is 133.
HsSpiClkDividerDiv134
Clock divider is 134.
HsSpiClkDividerDiv135
Clock divider is 135.
HsSpiClkDividerDiv136
Clock divider is 136.
HsSpiClkDividerDiv137
Clock divider is 137.
HsSpiClkDividerDiv138
Clock divider is 138.
HsSpiClkDividerDiv139
Clock divider is 139.
HsSpiClkDividerDiv140
Clock divider is 140.
HsSpiClkDividerDiv141
Clock divider is 141.
HsSpiClkDividerDiv142
Clock divider is 142.
HsSpiClkDividerDiv143
Clock divider is 143.
HsSpiClkDividerDiv144
Clock divider is 144.
HsSpiClkDividerDiv145
Clock divider is 145.
HsSpiClkDividerDiv146
Clock divider is 146.
HsSpiClkDividerDiv147
Clock divider is 147.
HsSpiClkDividerDiv148
Clock divider is 148.
HsSpiClkDividerDiv149
Clock divider is 149.
HsSpiClkDividerDiv150
Clock divider is 150.
HsSpiClkDividerDiv151
Clock divider is 151.
HsSpiClkDividerDiv152
Clock divider is 152.
HsSpiClkDividerDiv153
Clock divider is 153.
HsSpiClkDividerDiv154
Clock divider is 154.
HsSpiClkDividerDiv155
Clock divider is 155.
HsSpiClkDividerDiv156
Clock divider is 156.
HsSpiClkDividerDiv157
Clock divider is 157.
HsSpiClkDividerDiv158
Clock divider is 158.
HsSpiClkDividerDiv159
Clock divider is 159.
HsSpiClkDividerDiv160
Clock divider is 160.
HsSpiClkDividerDiv161
Clock divider is 161.
HsSpiClkDividerDiv162
Clock divider is 162.
HsSpiClkDividerDiv163
Clock divider is 163.
HsSpiClkDividerDiv164
Clock divider is 164.
HsSpiClkDividerDiv165
Clock divider is 165.
HsSpiClkDividerDiv166
Clock divider is 166.
HsSpiClkDividerDiv167
Clock divider is 167.
HsSpiClkDividerDiv168
Clock divider is 168.
HsSpiClkDividerDiv169
Clock divider is 169.
HsSpiClkDividerDiv170
Clock divider is 170.
HsSpiClkDividerDiv171
Clock divider is 171.
HsSpiClkDividerDiv172
Clock divider is 172.
HsSpiClkDividerDiv173
Clock divider is 173.
HsSpiClkDividerDiv174
Clock divider is 174.
HsSpiClkDividerDiv175
Clock divider is 175.
HsSpiClkDividerDiv176
Clock divider is 176.
HsSpiClkDividerDiv177
Clock divider is 177.
HsSpiClkDividerDiv178
Clock divider is 178.
HsSpiClkDividerDiv179
Clock divider is 179.
HsSpiClkDividerDiv180
Clock divider is 180.
HsSpiClkDividerDiv181
Clock divider is 181.
HsSpiClkDividerDiv182
Clock divider is 182.
HsSpiClkDividerDiv183
Clock divider is 183.
HsSpiClkDividerDiv184
Clock divider is 184.
HsSpiClkDividerDiv185
Clock divider is 185.
HsSpiClkDividerDiv186
Clock divider is 186.
HsSpiClkDividerDiv187
Clock divider is 187.
HsSpiClkDividerDiv188
Clock divider is 188.
HsSpiClkDividerDiv189
Clock divider is 189.
HsSpiClkDividerDiv190
Clock divider is 190.
HsSpiClkDividerDiv191
Clock divider is 191.
HsSpiClkDividerDiv192
Clock divider is 192.
HsSpiClkDividerDiv193
Clock divider is 193.
HsSpiClkDividerDiv194
Clock divider is 194.
HsSpiClkDividerDiv195
Clock divider is 195.
HsSpiClkDividerDiv196
Clock divider is 196.
HsSpiClkDividerDiv197
Clock divider is 197.
HsSpiClkDividerDiv198
Clock divider is 198.
HsSpiClkDividerDiv199
Clock divider is 199.
HsSpiClkDividerDiv200
Clock divider is 200.
HsSpiClkDividerDiv201
Clock divider is 201.
HsSpiClkDividerDiv202
Clock divider is 202.
HsSpiClkDividerDiv203
Clock divider is 203.
HsSpiClkDividerDiv204
Clock divider is 204.
HsSpiClkDividerDiv205
Clock divider is 205.
HsSpiClkDividerDiv206
Clock divider is 206.
HsSpiClkDividerDiv207
Clock divider is 207.
HsSpiClkDividerDiv208
Clock divider is 208.
HsSpiClkDividerDiv209
Clock divider is 209.
HsSpiClkDividerDiv210
Clock divider is 210.
HsSpiClkDividerDiv211
Clock divider is 211.
HsSpiClkDividerDiv212
Clock divider is 212.
HsSpiClkDividerDiv213
Clock divider is 213.
HsSpiClkDividerDiv214
Clock divider is 214.
HsSpiClkDividerDiv215
Clock divider is 215.
HsSpiClkDividerDiv216
Clock divider is 216.
HsSpiClkDividerDiv217
Clock divider is 217.
HsSpiClkDividerDiv218
Clock divider is 218.
HsSpiClkDividerDiv219
Clock divider is 219.
HsSpiClkDividerDiv220
Clock divider is 220.
HsSpiClkDividerDiv221
Clock divider is 221.
HsSpiClkDividerDiv222
Clock divider is 222.
HsSpiClkDividerDiv223
Clock divider is 223.
HsSpiClkDividerDiv224
Clock divider is 224.
HsSpiClkDividerDiv225
Clock divider is 225.
HsSpiClkDividerDiv226
Clock divider is 226.
HsSpiClkDividerDiv227
Clock divider is 227.
HsSpiClkDividerDiv228
Clock divider is 228.
HsSpiClkDividerDiv229
Clock divider is 229.
HsSpiClkDividerDiv230
Clock divider is 230.
HsSpiClkDividerDiv231
Clock divider is 231.
HsSpiClkDividerDiv232
Clock divider is 232.
HsSpiClkDividerDiv233
Clock divider is 233.
HsSpiClkDividerDiv234
Clock divider is 234.
HsSpiClkDividerDiv235
Clock divider is 235.
HsSpiClkDividerDiv236
Clock divider is 236.
HsSpiClkDividerDiv237
Clock divider is 237.
HsSpiClkDividerDiv238
Clock divider is 238.
HsSpiClkDividerDiv239
Clock divider is 239.
HsSpiClkDividerDiv240
Clock divider is 240.
HsSpiClkDividerDiv241
Clock divider is 241.
HsSpiClkDividerDiv242
Clock divider is 242.
HsSpiClkDividerDiv243
Clock divider is 243.
HsSpiClkDividerDiv244
Clock divider is 244.
HsSpiClkDividerDiv245
Clock divider is 245.
HsSpiClkDividerDiv246
Clock divider is 246.
HsSpiClkDividerDiv247
Clock divider is 247.
HsSpiClkDividerDiv248
Clock divider is 248.
HsSpiClkDividerDiv249
Clock divider is 249.
HsSpiClkDividerDiv250
Clock divider is 250.
HsSpiClkDividerDiv251
Clock divider is 251.
HsSpiClkDividerDiv252
Clock divider is 252.
HsSpiClkDividerDiv253
Clock divider is 253.
HsSpiClkDividerDiv254
Clock divider is 254.
HsSpiClkDividerDiv255
Clock divider is 255.
HsSpiClkDividerDiv256
Clock divider is 256.
Definition at line 329 of file hsspi.h.
enum en_hsspi_clk_mode
High speed SPI clock mode.
The API must use the enum with the attributes that match the communication attributes of the serial peripheral that is to be interfaced on the corresponding slave select line.
Enumerator:
HsSpiClkLowOutFallingInRising
Serial clock low during idle, data output set with falling clock edge, data input sampling with rising clock edge.
HsSpiClkLowOutRisingInFalling
Serial clock low during idle, data output set with rising clock edge, data input sampling with falling clock edge.
HsSpiClkHighOutRisingInFalling
Serial clock high during idle, data output set with rising clock edge, data input sampling with falling clock edge.
HsSpiClkHighOutFallingInRising
Serial clock high during idle, data output set with falling clock edge, data input sampling with rising clock edge.
HsSpiClkLowOutFallingInFalling
Serial clock low during idle, data output set with falling clock edge, data input sampling with falling clock edge.
HsSpiClkLowOutRisingInRising
Serial clock low during idle, data output set with rising clock edge, data input sampling with rising clock edge.
HsSpiClkHighOutRisingInRising
Serial clock high during idle, data output set with rising clock edge, data input sampling with rising clock edge.
HsSpiClkHighOutFallingInFalling
Serial clock high during idle, data output set with falling clock edge, data input sampling with falling clock edge.
Definition at line 270 of file hsspi.h.
enum en_hsspi_clk_selection
High speed SPI clock selection.
The internal clock divider can divide either the AHB clock (i.e. HCLK) or the peripheral clock (i.e. PCLKn).
Enumerator:
HsSpiClockAhb
Clock divider uses AHB clock.
HsSpiClockPeripheral
Clock divider uses peripheral clock.
Definition at line 208 of file hsspi.h.
enum en_hsspi_command_sequencer_control
High speed SPI command sequencer control.
This enum is used to configure the phases of the serial transaction generated by the command sequencer for memory read or write operations.
Enumerator:
HsSpiCmdTransmitAddress07To00
Transmit address bits 7:0 of serial memory address, DEC = 1.
HsSpiCmdTransmitAddress08To15
Transmit address bits 15:8 of serial memory address, DEC = 1.
HsSpiCmdTransmitAddress16To23
Transmit address bits 23:16 of serial memory address, DEC = 1.
HsSpiCmdTransmitAddress24To31
Transmit address bits 31:24 of serial memory address, DEC = 1.
HsSpiCmdTransmitHighZStateByte
High-Z byte, output signals are tri-stated for 1 byte time, DEC = 1.
HsSpiCmdTransmitHighZStateNibble
High-Z nibble, output signals are tri-stated for 1 nibble time after 4 bits of the transmit data have been sent,DEC = 1
HsSpiCmdTransmitData
Data "as it is", no decoding, DEC = 0.
HsSpiCmdEndOfList
End of list, DEC = 1.
Definition at line 249 of file hsspi.h.
enum en_hsspi_endianess
High speed SPI endianess.
Enumerator:
HsSpiBigEndian
Big Endian.
HsSpiLittleEndian
Little Endian.
Definition at line 635 of file hsspi.h.
enum en_hsspi_error
High speed SPI error types.
These error codes will be returned by HsSpi_HandleError() function.
Enumerator:
HsSpiErrorNo
No error indicated.
HsSpiErrorUnmappedMemoryAccessFault
An unmapped memory access fault has occurred.
HsSpiErrorWriteAccessFault
Write access fault has occurred (is used in command sequencer mode).
HsSpiErrorProtectionViolation
PPU protection violation has occurred.
HsSpiErrorDmaWrChBlockSize
DMA Write Channel Block Size Fault has occurred.
HsSpiErrorDmaRdChBlockSize
DMA Read Channel Block Size Fault has occurred.
Definition at line 177 of file hsspi.h.
enum en_hsspi_fifo_width
High speed SPI FIFO width.
Width of FIFO. Depending on the configured width, the usable size of the shift register in the SPI core also changes.
Enumerator:
HsSpiFifoWidth8
8-bit FiFo width
HsSpiFifoWidth16
16-bit FiFo width
HsSpiFifoWidth24
24-bit FiFo width
HsSpiFifoWidth32
32-bit FiFo width
Definition at line 163 of file hsspi.h.
enum en_hsspi_instance_index
Enumeration to define an index for each enabled HS-SPI instance.
Enumerator:
HsSpiInstanceIndexHsSpi0
HsSpiInstanceIndexMax
Definition at line 731 of file hsspi.h.
enum en_hsspi_memory_type
High speed SPI memory type.
Serial SRAM or Serial Flash Memory Type Select (SRAM) This bit should only be set if serial SRAM devices are memory mapped through (HS)SPI.
Enumerator:
HsSpiFlash
Serial Flash memory devices are connected. Writes are disabled.
HsSpiSram
Serial SRAM memory devices are connected. Writes are enabled.
Definition at line 317 of file hsspi.h.
enum en_hsspi_mode
High speed SPI mode.
Used to switch between direct and command sequencer mode.
Enumerator:
HsSpiModeDirect
Direct mode is enabled, command sequencer is disabled.
HsSpiModeCmdSequencer
Command sequencer is enabled, direct mode is disabled.
Definition at line 625 of file hsspi.h.
enum en_hsspi_protocol_direction
SPI transfer direction.
Enumerator:
HsSpiProtocolTxRx
TX and RX direction.
HsSpiProtocolTx
TX direction only.
HsSpiProtocolRx
RX direction only.
Definition at line 302 of file hsspi.h.
enum en_hsspi_protocol_mode
SPI transfer mode (used for Command Sequencer and Direct mode)
Selects transfer protocol mode. The direct mode is active after call of HsSpi_Init, and can be changed by function HsSpi_SetMode(). RxTx-,RxOnly- and TxOnly modes will be selected automatically by the transfer functions.
Enumerator:
HsSpiProtocolModeSingle
Single mode.
HsSpiProtocolModeDual
Dual mode, can only be used with the half-duplex functions.
HsSpiProtocolModeQuad
Quad mode, can only be used with the half-duplex functions.
Definition at line 291 of file hsspi.h.
enum en_hsspi_rx_status
High speed SPI reception status.
Status value used either in SpiRxStatus callback function or in HsSpi_GetDirectModeRxStatus() function (for direct mode polling operation).
Enumerator:
HsSpiRxFinished
Receive FIFO and shift register is empty.
HsSpiRxFifoLow
Receive FIFO fill level is less or equal to threshold.
HsSpiRxNoStatusAvailable
SPI instance is not valid, mode is set to command sequencer or reception is ongoing and FIFO level is higher than threshold.
Definition at line 132 of file hsspi.h.
enum en_hsspi_transfer_protocol
High speed SPI transfer protocol.
Enumerator:
HsSpiSerialIf
Serial interface bit width complies with HSSPIn_CSCFG:MDM[1:0] setting.
HsSpiDualBitMode
Dual-bit mode.
HsSpiQuadBitMode
Quad-bit mode.
HsSpiSingleBitMode
Single-bit mode.
Definition at line 645 of file hsspi.h.
enum en_hsspi_tx_status
High speed SPI transmission status.
Status value used either in SpiTxStatus callback function or in HsSpi_GetDirectModeTxStatus() function (for direct mode polling operation).
Enumerator:
HsSpiModeError
Illegal mode or parameter error.
HsSpiTxFinished
Transmit FIFO and shift register is empty.
HsSpiTxFifoLow
Transmit FIFO fill level is less or equal to threshold.
HsSpiTxNoStatusAvailable
SPI instance is not valid, mode is set to command sequencer or transmission is ongoing and FIFO level is higher than threshold.
Definition at line 147 of file hsspi.h.
Function Documentation
en_result_t HsSpi_DeInit (volatile FM_HSSPI_TypeDef * pstcHsSpi)
De-Initializes the HS-SPI unit. All registers which are used by HS-SPI will be reset to their default value.
Parameters:
[in] pstcHsSpi HS-SPI module instance (register start address of HS-SPI module).
Return values:
Ok
ErrorInvalidParameter If one of the following conditions are met:
pstcHsSpi == NULL
pstcHsSpiInternData == NULL (invalid or disabled HS-SPI unit (PDL_PERIPHERAL_ENABLE_HSSPIn))
Error If HsSpi disable/enable failed
Definition at line 413 of file hsspi.c.
References HsSpi_ModuleDisable(), HsSpiGetInternDataPtr(), stc_hsspi_intern_data::pfnTxStatusCallbackFunction, and stc_hsspi_intern_data::pu8RXBuffer.
en_result_t HsSpi_DirectModeTransferHalfDuplex (volatile FM_HSSPI_TypeDef * pstcHsSpi, uint8_t u8DeviceNumber, const uint8_t * pu8TxData, uint16_t u16TxSize, uint8_t * pu8RxData, uint16_t u16RxSize, boolean_t bEnableTxDmaRequest)
Transfers data in direct half-duplex mode.
Note that direct mode transfer protocol is changed during operation and previous mode is restored after operation has finished.
Note:
This function does not work for HS-SPI clock modes 4-7
This function is restricted to HS-SPI protocol mode 'Legacy'. i.e. does not support half duplex transfer in case of 'Dual' or 'Quad' mode.
Parameters:
[in] pstcHsSpi HS-SPI module instance (register start address of (high speed) SPI module).
[in] u8DeviceNumber Slave which is connected to corresponding signal SSEL0..3.
[in] pu8TxData Pointer to transmit buffer
[in] u16TxSize Number of data bytes to transmit. Must be greater than 0.
[in] pu8RxData Pointer to receive buffer, can be NULL.
[in] u16RxSize Number of data bytes to receive, can be 0
[in] bEnableTxDmaRequest Enable or disable DMA request on TX FIFO interrupts (less or equal threshold level). -> currently not supported
Return values:
Ok Setup or transmission of data successful.
ErrorOperationInProgress A transmission is still ongoing.
ErrorInvalidMode HS-SPI module is in command sequencer mode. or protocol mode is not "SpiProtocolModeLegacy" or clock mode >= "SpiClkLowOutFallingInFalling"
ErrorInvalidParameter If one of following conditions are met:
pstcHsSpi == NULL
pu8TxData == NULL
u8DeviceNumber > 3
u16TxSize == 0
u16TxSize + u16RxSize > (2^16 - 1)
pstcHsSpiInternData == NULL (invalid or disabled HS-SPI unit (PDL_PERIPHERAL_ENABLE_HSSPIn))
Definition at line 866 of file hsspi.c.
References HsSpi_DirectModeTransferHalfDuplexList(), stc_hsspi_linked_data_list::pstcNext, stc_hsspi_linked_data_list::pu8Data, and stc_hsspi_linked_data_list::u16ListItemDataSize.
en_result_t HsSpi_DirectModeTransferHalfDuplexList (volatile FM_HSSPI_TypeDef * pstcHsSpi, uint8_t u8DeviceNumber, const stc_hsspi_linked_data_list_t * pstcTxData, uint8_t * pu8RxData, uint16_t u16RxSize, boolean_t bEnableTxDmaRequest)
Transfers linked data in direct half-duplex mode.
Note that direct mode transfer protocol is changed during operation and previous mode is restored after operation has finished.
Note:
This function does not work for HS-SPI clock modes 4-7
This function is restricted to HS-SPI protocol mode 'Legacy'. i.e. does not support half duplex transfer in case of 'Dual' or 'Quad' mode.
Parameters:
[in] pstcHsSpi HS-SPI module instance (register start address of (high speed) SPI module).
[in] u8DeviceNumber Slave which is connected to corresponding signal SSEL0..3.
[in] pstcTxData Pointer to first item of linked transmit data list The total size of transmit data must be greater than 0
[in] pu8RxData Pointer to receive buffer, can be NULL.
[in] u16RxSize Number of data bytes to receive, can be 0
[in] bEnableTxDmaRequest Enable or disable DMA request on TX FIFO interrupts (less or equal threshold level). -> currently not supported
Return values:
Ok Setup or transmission of data successful.
ErrorOperationInProgress A transmission is still ongoing.
ErrorInvalidMode SPI module is in command sequencer mode. or protocol mode is not "HsSpiProtocolModeLegacy" or clock mode >= "HsSpiClkLowOutFallingInFalling"
ErrorInvalidParameter If one of following conditions are met:
pstcHsSpi == NULL
pstcTxData == NULL
pstcTxData->pu8Data == NULL
u8DeviceNumber > 3
total size of transmit data == 0
total size of transmit data + u16RxSize > (2^16 - 1)
pstcHsSpiInternData == NULL (invalid or disabled HS-SPI unit (PDL_PERIPHERAL_ENABLE_HSSPIn))
Error If HsSpi disable/enable failed
Definition at line 917 of file hsspi.c.
References stc_hsspi_intern_data::enClkMode, HS_SPI_MAX_FIFO_DEPTH, HSSPI_DIRECT_MODE_TX_RX_SINGLE_MODE, HsSpi_ModuleDisable(), HsSpi_ModuleEnable(), HsSpiClkLowOutFallingInFalling, HsSpiGetInternDataPtr(), PDL_WAIT_LOOP_HOOK(), stc_hsspi_linked_data_list::pstcNext, stc_hsspi_linked_data_list::pu8Data, stc_hsspi_intern_data::pu8RXBuffer, and stc_hsspi_linked_data_list::u16ListItemDataSize.
Referenced by HsSpi_DirectModeTransferHalfDuplex().
en_result_t HsSpi_Init (volatile FM_HSSPI_TypeDef * pstcHsSpi, const stc_hsspi_config_t * pstcConfig)
Initialisation of the HS-SPI module. FIFO width is limited to 8 bit and DMA is not supported in direct mode. The (high speed) SPI module is initialized in direct mode after call of Spi_Init().
Parameters:
[in] pstcHsSpi HS-SPI module instance (register start address of HS-SPI module).
[in] pstcConfig HS-SPI configuration parameters.
Return values:
Ok HS-SPI module successfully initialised.
ErrorInvalidParameter If one of the following conditions are met:
pstcHsSpi == NULL
pstcConfig == NULL
pstcConfig->u8TxFifoThresholdLow > (HS_SPI_MAX_FIFO_DEPTH - 1)
pstcHsSpiInternData == NULL (invalid or disabled HS-SPI unit (PDL_PERIPHERAL_ENABLE_HSSPIn))
Error If HsSpi disable/enable failed
Definition at line 244 of file hsspi.c.
References stc_hsspi_config::bMasterOperation, stc_hsspi_intern_data::bMasterOperation, stc_hsspi_config::bRxDmaBridgeEnable, stc_hsspi_config::bTxDmaBridgeEnable, stc_hsspi_config::enClockDivider, stc_hsspi_config::enCommandSequencerModeProtocol, stc_hsspi_config::enDirectModeProtocol, stc_hsspi_intern_data::enDirectModeProtocol, stc_hsspi_config::enFifoWidth, stc_hsspi_config::enMemoryBankSize, stc_hsspi_config::enMemoryType, HS_SPI_MAX_FIFO_DEPTH, HsSpi_ModuleDisable(), HsSpi_ModuleEnable(), HsSpiClkDividerDiv1, HsSpiClkDividerDiv10, HsSpiClkDividerDiv11, HsSpiClkDividerDiv12, HsSpiClkDividerDiv13, HsSpiClkDividerDiv14, HsSpiClkDividerDiv15, HsSpiClkDividerDiv16, HsSpiClkDividerDiv2, HsSpiClkDividerDiv3, HsSpiClkDividerDiv4, HsSpiClkDividerDiv5, HsSpiClkDividerDiv6, HsSpiClkDividerDiv7, HsSpiClkDividerDiv8, HsSpiClkDividerDiv9, HsSpiGetInternDataPtr(), PDL_ZERO_STRUCT, stc_hsspi_config::pfnTxStatusCallback, stc_hsspi_intern_data::pfnTxStatusCallbackFunction, stc_hsspi_config::u16IdleTimeOut, and stc_hsspi_config::u8TxFifoThresholdLow.
static en_result_t HsSpi_ModuleDisable (volatile FM_HSSPI_TypeDef * pstcHsSpi) [static]
Globally disable HS-SPI module by clearing bit MEN.
Parameters:
[in] pstcHsSpi Pointer to HS-SPI instance
Return values:
Ok HS-SPI module successfully Disabled.
Error Operation timed out, pstcHsSpi == NULL
Definition at line 196 of file hsspi.c.
References PDL_WAIT_LOOP_HOOK().
Referenced by HsSpi_DeInit(), HsSpi_DirectModeTransferHalfDuplexList(), HsSpi_Init(), HsSpi_SetExternalDeviceConfig(), HsSpi_SetMode(), HsSpi_SetReadCommandSequence(), and HsSpi_SetWriteCommandSequence().
static en_result_t HsSpi_ModuleEnable (volatile FM_HSSPI_TypeDef * pstcHsSpi) [static]
Globally enable SPI module by setting bit MEN.
Parameters:
[in] pstcHsSpi Pointer to HS-SPI instance
Return values:
Ok HS-SPI module successfully Enaabled.
Error pstcHsSpi == NULL
ErrorTimeout Operation timed out
Definition at line 159 of file hsspi.c.
References PDL_WAIT_LOOP_HOOK().
Referenced by HsSpi_DirectModeTransferHalfDuplexList(), HsSpi_Init(), HsSpi_SetExternalDeviceConfig(), HsSpi_SetMode(), HsSpi_SetReadCommandSequence(), and HsSpi_SetWriteCommandSequence().
en_result_t HsSpi_MultiModeTransfer (volatile FM_HSSPI_TypeDef * pstcHsSpi, uint8_t u8DeviceNumber, const uint8_t * pu8LegacyData, uint8_t u8LegacyTxSize, const uint8_t * pu8TxData, uint8_t u8TxSize, uint8_t * pu8RxData, uint8_t u8RxSize)
Starts transfer in legacy mode and then switches to quad mode.
Some HS-SPI devices may require an access sequence where the first part of a command is transmitted in legacy mode and afterwards further parameters or the response from the device are transmitted in quad mode. This function allows to execute such an SPI transaction.
Note that direct mode transfer protocol is changed during operation and previous mode is restored after operation has finished.
Parameters:
[in] pstcHsSpi HS-SPI module instance (register start address of high speed SPI module).
[in] u8DeviceNumber Slave which is connected to corresponding SSEL0..3 line
[in] pu8LegacyData Pointer to transmit buffer for legacy mode
[in] u8LegacyTxSize Number of data bytes to transmit in legacy mode
[in] pu8TxData Pointer to transmit buffer for quad mode, can be NULL.
[in] u8TxSize Number of data bytes to transmit in quad mode Valid range from 0 to HS_SPI_MAX_FIFO_DEPTH.
[in] pu8RxData Pointer to receive buffer for quad mode, can be NULL.
[in] u8RxSize Number of data bytes to receive in quad mode. Valid range from 0 to HS_SPI_MAX_FIFO_DEPTH.
Return values:
Ok Setup or transmission of data successful.
ErrorOperationInProgress u8TxSize > 0 and a transmission is still ongoing.
ErrorInvalidMode SPI module is in command sequencer mode.
ErrorInvalidParameter If one of following conditions are met:
pstcHsSpi == NULL
pu8TxData == NULL
u8DeviceNumber > 3
u8TxSize == 0
u8RxSize > HS_SPI_MAX_FIFO_DEPTH
u8RxSize > 0 && pu8RxData == NULL
u8LegacyTxSize > 0 && pu8LegacyData == NULL
pstcHsSpiInternData == NULL (invalid or disabled HS-SPI unit (PDL_PERIPHERAL_ENABLE_HSSPIn))
Definition at line 1475 of file hsspi.c.
References HS_SPI_MAX_FIFO_DEPTH, HSSPI_DIRECT_MODE_RX_ONLY_QUAD_MODE, HSSPI_DIRECT_MODE_TX_ONLY_QUAD_MODE, HSSPI_DIRECT_MODE_TX_ONLY_SINGLE_MODE, HsSpiGetInternDataPtr(), PDL_WAIT_LOOP_HOOK(), and stc_hsspi_intern_data::pu8RXBuffer.
en_result_t HsSpi_SetExternalDeviceConfig (volatile FM_HSSPI_TypeDef * pstcHsSpi, uint8_t u8DeviceNumber, const stc_hsspi_ext_device_config_t * pstcConfig)
Configures the communication parameters of an external device.
The external device specific parameters (e.g. HS-SPI mode, LSB/MSB first, ...) can be configured In case of high speed SPI the slave u8DeviceNumber is also enabled for the memory map in command sequencer mode. (See HW-manual for more information)
Parameters:
[in] pstcHsSpi HS-SPI module instance (register start address of HS-SPI module).
[in] u8DeviceNumber Slave which is connected to corresponding signals SSEL0..3
[in] pstcConfig HS-SPI configuration parameters.
Return values:
Ok External device configuration success
ErrorInvalidParameter If one of following conditions are met:
pstcHsSpi == NULL
pstcConfig == NULL
pstcHsSpiInternData == NULL (invalid or disabled HS-SPI unit (PDL_PERIPHERAL_ENABLE_HSSPIn))
u8DeviceNumber > 3
Error If HsSpi disable/enable failed
Definition at line 703 of file hsspi.c.
References stc_hsspi_ext_device_config::bCompensatedClock, stc_hsspi_ext_device_config::bSafeSync, stc_hsspi_ext_device_config::bShiftLsbFirst, stc_hsspi_ext_device_config::bSlaveSelectPolarityHigh, stc_hsspi_intern_data::enClkMode, stc_hsspi_ext_device_config::enClockDelay, stc_hsspi_ext_device_config::enClockDivider, stc_hsspi_ext_device_config::enClockMode, stc_hsspi_ext_device_config::enEndianess, HsSpi_ModuleDisable(), HsSpi_ModuleEnable(), HsSpiBigEndian, HsSpiGetInternDataPtr(), HsSpiLittleEndian, stc_hsspi_ext_device_config::u8ReadDeselectTime, and stc_hsspi_ext_device_config::u8WriteDeselectTime.
en_result_t HsSpi_SetMode (volatile FM_HSSPI_TypeDef * pstcHsSpi, en_hsspi_mode_t enMode, en_hsspi_protocol_mode_t enProtocolMode, en_hsspi_protocol_direction_t enProtocolDirection)
Set mode of the HS-SPI unit.
Selects if HS-SPI unit shall be operated in Direct or Command Sequencer mode and which protocol mode (legacy, dual, quad) shall be used. Any transmission has to be completed before a change of HS-SPI mode is possible, otherwise any ongoing transmission will be interrupted.
Parameters:
[in] pstcHsSpi HS-SPI module instance (register start address of HS-SPI module).
[in] enMode Direct mode or command sequencer mode.
[in] enProtocolMode HS-SPI Mode (Legacy, Dual or Quad)
[in] enProtocolDirection HS-SPI protocol direction
Return values:
Ok New mode was successfully set.
ErrorInvalidParameter If following condition is met:
pstcHsSpi == NULL
pstcHsSpiInternData == NULL (invalid or disabled SPI unit (PDL_PERIPHERAL_ENABLE_HSSPIn))
Error If HsSpi disable/enable failed
Definition at line 559 of file hsspi.c.
References stc_hsspi_intern_data::enDirectModeProtocol, HsSpi_ModuleDisable(), HsSpi_ModuleEnable(), HsSpiGetInternDataPtr(), HsSpiModeDirect, HsSpiProtocolModeDual, HsSpiProtocolModeQuad, HsSpiProtocolModeSingle, HsSpiProtocolRx, HsSpiProtocolTx, and HsSpiProtocolTxRx.
en_result_t HsSpi_SetReadCommandSequence (volatile FM_HSSPI_TypeDef * pstcHsSpi, const stc_hsspi_command_sequencer_control_t * pstcCmdSequence)
Set read command sequence for command sequencer mode.
Every command sequence is either 8 commands long, or has to be finished with command HsSpiCmdEndOfList. To find out if a 8 commands long sequence is valid or not, the 9th command (which will not be transferred) must be a HsSpiCmdEndOfList command. The new sequence will be set after internally disabling the HS-SPI module. After update, the SPI module is enabled again.
Parameters:
[in] pstcHsSpi HS-SPI module instance (register start address of high speed SPI module).
[in] pstcCmdSequence Pointer to command sequence list (maximum 9 entries, last entry must be SpiCmdEndOfList).
Return values:
Ok Read command sequence successfully set.
ErrorInvalidMode HS-SPI module is in direct mode.
ErrorInvalidParameter If one of following conditions are met:
pstcCmdSequence == NULL
SpiCmdEndOfList command missing in pstcCmdSequence
pstcHsSpi == NULL
Error If HsSpi disable/enable failed
Definition at line 1151 of file hsspi.c.
References HsSpi_ModuleDisable(), HsSpi_ModuleEnable(), HsSpiCmdEndOfList, HsSpiCmdTransmitData, HsSpiCmdTransmitHighZStateByte, HsSpiCmdTransmitHighZStateNibble, HsSpiDualBitMode, HsSpiQuadBitMode, HsSpiSerialIf, and HsSpiSingleBitMode.
en_result_t HsSpi_SetWriteCommandSequence (volatile FM_HSSPI_TypeDef * pstcHsSpi, const stc_hsspi_command_sequencer_control_t * pstcCmdSequence)
Set write command sequence for command sequencer mode.
Every command sequence is either 8 commands long, or has to be finished with command HsSpiCmdEndOfList. To find out if a 8 commands long sequence is valid or not, the 9th command (which will not be transferred) must be a HsSpiCmdEndOfList command. The new sequence will be set after internally disabling the SPI module. After update, the SPI module is enabled again.
Parameters:
[in] pstcHsSpi HS-SPI module instance (register start address of HS-SPI module).
[in] pstcCmdSequence Pointer to command sequence list (maximum 9 entries, last entry must be SpiCmdEndOfList).
Return values:
Ok Write command sequence successfully set.
ErrorInvalidMode SPI module is in direct mode.
ErrorInvalidParameter If one of following conditions are met:
pstcHsSpi == NULL
pstcCmdSequence == NULL
SpiCmdEndOfList command missing in pstcCmdSequence
Error If HsSpi disable/enable failed
Definition at line 1305 of file hsspi.c.
References HsSpi_ModuleDisable(), HsSpi_ModuleEnable(), HsSpiCmdEndOfList, HsSpiCmdTransmitData, HsSpiCmdTransmitHighZStateByte, HsSpiCmdTransmitHighZStateNibble, HsSpiDualBitMode, HsSpiQuadBitMode, HsSpiSerialIf, and HsSpiSingleBitMode.
static stc_hsspi_intern_data_t* HsSpiGetInternDataPtr (volatile FM_HSSPI_TypeDef * pstcHsSpi) [static]
Return the internal data for a certain HS-SPI instance.
Parameters:
[in] pstcHsSpi Pointer to HS-SPI instance
Returns:
Pointer to internal data or NULL if instance is not enabled (or not known)
Definition at line 134 of file hsspi.c.
References HS_SPI_INSTANCE_COUNT, and stc_hsspi_instance_data::stcInternData.
Referenced by HsSpi_DeInit(), HsSpi_DirectModeTransferHalfDuplexList(), HsSpi_Init(), HsSpi_MultiModeTransfer(), HsSpi_SetExternalDeviceConfig(), and HsSpi_SetMode().
Variable Documentation
stc_hsspi_instance_data_t m_astcHsSpiInstanceDataLut[(uint8_t)(PDL_PERIPHERAL_ENABLE_HSSPI0==PDL_ON)]
Initial value:
{
  {
     & (*((volatile  FM_HSSPI_TypeDef  *) FM_HSSPI_BASE)) ,
     0u,
     {0u, 0u, 0u, 0u, 0u, HsSpiClkLowOutFallingInRising, HsSpiProtocolModeSingle, 0u}
  }
}
Look-up table for all enabled I2S instances and their internal data.
Look-up table for all enabled ADC instances and their internal data.
Definition at line 92 of file hsspi.c.
stc_hsspi_instance_data_t m_astcHsSpiInstanceDataLut[(uint8_t)(PDL_PERIPHERAL_ENABLE_HSSPI0==PDL_ON)]
Look-up table for all enabled ADC instances and their internal data.
Definition at line 92 of file hsspi.c.