PDL for FM Family: Main Flash (MFlash)
Main Flash (MFlash)
Defines
#define Flash_Read(addr) *(volatile uint16_t*)((uint32_t)(addr))
Read a half word data from Flash.
#define Flash_Write(addr, data) *(volatile uint16_t*)((uint32_t)(addr)) = (uint16_t)(data)
Wirte a half word data into Flash.
#define MFLASH_CODE1 0x0AA8
write command
#define MFLASH_CODE2 0x0554
#define MFLASH_CHK_DPOL_MASK (uint16_t)0x0080
main flash check bit mask
#define MFLASH_CHK_TOGG_MASK (uint16_t)0x0040
#define MFLASH_CHK_TLOV_MASK (uint16_t)0x0020
#define CR_DATA_ADDR (0x00100004)
CR address.
Typedefs
typedef enum en_mflash_state en_mflash_state_t
state feedback
typedef enum en_mflash_toggle en_mflash_toggle_t
check toggle state
typedef enum en_mflash_datapoll en_mflash_datapoll_t
check toggle state
typedef enum en_mflash_eccbitstat en_mflash_eccbitstat_t
check toggle state
Enumerations
enum en_mflash_state { MFLASH_RET_OK, MFLASH_RET_INVALID_PARA, MFLASH_RET_ABNORMAL, MFLASH_RET_ECCERROR }
state feedback
enum en_mflash_toggle { MFLASH_CHK_TOGG_NORMAL, MFLASH_CHK_TOGG_ABNORMAL }
check toggle state
enum en_mflash_datapoll { MFLASH_CHK_DPOL_NORMAL, MFLASH_CHK_DPOL_ABNORMAL }
check toggle state
enum en_mflash_eccbitstat { MFLASH_ECC_NORMAL, MFLASH_ECC_ABNORMAL }
check toggle state
Functions
static __ramfunc en_mflash_toggle_t MFlash_CheckToggle (uint16_t *pu16Addr)
automatic algorithm of flash memory execution
static __ramfunc void MFlash_ReadResetCmd (uint16_t *pu16ResetSecAddr)
Issue read/reset command.
__ramfunc en_result_t MFlash_ChipErase (boolean_t bCrRemain)
Flash chip erase.
__ramfunc en_result_t MFlash_SectorErase (uint16_t *pu16SecAddr)
Flash sector erase.
__ramfunc en_result_t MFlash_WriteData32Bit (uint32_t *pu32WriteAddr, uint32_t *pu32WriteData, uint32_t u32Size, boolean_t bVerifyAndEccCheck)
Flash word write with ECC.
__ramfunc en_result_t MFlash_WriteData16Bit (uint16_t *pu16WriteAddr, uint16_t *pu16WriteData, uint32_t u32Size)
Flash half word write with ECC.
__ramfunc en_result_t MFlash_WriteData16Bit_Fm0Type3CrSecureArea (uint16_t *pu16WriteAddr, uint16_t *pu16WriteData, uint32_t u32Size)
Flash half word write with ECC.
static void MFlash_DualReadResetCmd (uint16_t *pu16ResetSecAddr)
Issue read/reset command.
static en_mflash_toggle_t MFlash_DualCheckToggle (uint16_t *pu16Addr)
automatic algorithm of flash memory execution
en_result_t MFlash_DualSectorErase (uint16_t *pu16SecAddr)
Dual Flash sector erase.
en_result_t MFlash_SetDualMode (boolean_t bDualMode)
Set Dual Flash Mode of FM4 TYPE3 product.
en_result_t MFlash_SetRemapMode (boolean_t bRemapMode)
Set remap function of FM4 TYPE3 product.
en_result_t MFlash_DualWriteData32Bit (uint32_t *pu32WriteAddr, uint32_t *pu32WriteData, uint32_t u32Size, boolean_t bVerifyAndEccCheck)
Dual Flash word write with ECC.
en_result_t MFlash_DualWriteData16Bit (uint16_t *pu16WriteAddr, uint16_t *pu16WriteData, uint32_t u32Size)
Dual Flash half-word write.
Detailed Description
Provided functions of Main Flash operation:
MFlash_ChipErase()
MFlash_SectorErase()
MFlash_WriteData32Bit()
MFlash_WriteData16Bit()
MFlash_SetDualMode()
MFlash_SetRemapMode()
MFlash_DualSectorErase()
MFlash_DualWriteData16Bit()
MFlash_DualWriteData32Bit()
Before using the Main Flash operation APIs, please make sure the code is operated in RAM area. In the IAR environment, the key word "__ramfunc" makes sure that the code is implemented from RAM. In the Keil environment, user has to place the code to RAM area manually. 1) Right click main_flash.c 2) [Options for main_flash.c]->[code/const]->select a RAM area
MFlash_ChipErase() can erase whole chip space of Main Flash, whether CR data remains after chip erase depends on the parameter MFlash_ChipErase::bCrRemain. MFlash_SectorErase() can erase one selected sector. MFlash_WriteData32Bit() writes data into Flash area with word align, as ECC is equipped in the Flash module. Whether data verify and ECC check is done depends on the parameter MFlash_WriteData32Bit::bVerifyAndEccCheck. MFlash_WriteData16Bit() writes data into Flash area with half word align
For the TYPE3 of FM4 product, there are two mode: Main Flash mode and Dual Flash Mode, which can be set by MFlash_SetDualMode(). In Main Flash mode, MFlash_Xxx() is used to operate whole Flash, but these APIs should be located at RAM area as described above. In Dual Flash mode, Flash is divided into Main Flash area and Dual Flash area, these two independent area can access to each other independently. MFlash_DualXxx() is used to operate the Dual Flash mode, and place MFlash_DualXxx() in the Main Flash area. MFlash_Xxx() is used to operate the Main Flash area, and place MFlash_Xxx() in the Dual Flash area (In the IAR IDE, "__ramfunc" before each MFlash_Xxx() can be removed in this case)
Define Documentation
#define CR_DATA_ADDR (0x00100004)
CR address.
To Set CR address
Definition at line 157 of file mainflash.h.
Referenced by MFlash_ChipErase().
#define Flash_Read (addr) *(volatile uint16_t*)((uint32_t)(addr))
Read a half word data from Flash.
Parameters:
addr Pointer to read data address
Definition at line 76 of file mainflash.c.
Referenced by MFlash_CheckToggle(), MFlash_ChipErase(), MFlash_DualCheckToggle(), MFlash_DualReadResetCmd(), MFlash_DualWriteData16Bit(), MFlash_DualWriteData32Bit(), MFlash_ReadResetCmd(), MFlash_WriteData16Bit(), MFlash_WriteData16Bit_Fm0Type3CrSecureArea(), and MFlash_WriteData32Bit().
#define Flash_Write (addr, data) *(volatile uint16_t*)((uint32_t)(addr)) = (uint16_t)(data)
Wirte a half word data into Flash.
Parameters:
addr Pointer to read data address
data Write data
Definition at line 85 of file mainflash.c.
Referenced by MFlash_ChipErase(), MFlash_DualReadResetCmd(), MFlash_DualSectorErase(), MFlash_DualWriteData16Bit(), MFlash_DualWriteData32Bit(), MFlash_ReadResetCmd(), MFlash_SectorErase(), MFlash_WriteData16Bit(), MFlash_WriteData16Bit_Fm0Type3CrSecureArea(), and MFlash_WriteData32Bit().
#define MFLASH_CHK_DPOL_MASK (uint16_t)0x0080
main flash check bit mask
To Set flash check hardware sequence flag bit mask
Definition at line 148 of file mainflash.h.
#define MFLASH_CHK_TLOV_MASK (uint16_t)0x0020
Definition at line 150 of file mainflash.h.
Referenced by MFlash_CheckToggle(), and MFlash_DualCheckToggle().
#define MFLASH_CHK_TOGG_MASK (uint16_t)0x0040
Definition at line 149 of file mainflash.h.
Referenced by MFlash_CheckToggle(), and MFlash_DualCheckToggle().
#define MFLASH_CODE1 0x0AA8
write command
To Select write command sequence by MCU type
Definition at line 125 of file mainflash.h.
Referenced by MFlash_ChipErase(), MFlash_DualSectorErase(), MFlash_DualWriteData16Bit(), MFlash_DualWriteData32Bit(), MFlash_SectorErase(), MFlash_WriteData16Bit(), MFlash_WriteData16Bit_Fm0Type3CrSecureArea(), and MFlash_WriteData32Bit().
#define MFLASH_CODE2 0x0554
Definition at line 126 of file mainflash.h.
Referenced by MFlash_ChipErase(), MFlash_DualSectorErase(), MFlash_DualWriteData16Bit(), MFlash_DualWriteData32Bit(), MFlash_SectorErase(), MFlash_WriteData16Bit(), MFlash_WriteData16Bit_Fm0Type3CrSecureArea(), and MFlash_WriteData32Bit().
Typedef Documentation
typedef enum en_mflash_datapoll en_mflash_datapoll_t
check toggle state
To feedback the flash toggle state
typedef enum en_mflash_eccbitstat en_mflash_eccbitstat_t
check toggle state
To feedback the flash toggle state
typedef enum en_mflash_state en_mflash_state_t
state feedback
To feedback the flash operation state
typedef enum en_mflash_toggle en_mflash_toggle_t
check toggle state
To feedback the flash toggle state
Enumeration Type Documentation
enum en_mflash_datapoll
check toggle state
To feedback the flash toggle state
Enumerator:
MFLASH_CHK_DPOL_NORMAL
data poll normal
MFLASH_CHK_DPOL_ABNORMAL
data poll abnormal
Definition at line 188 of file mainflash.h.
enum en_mflash_eccbitstat
check toggle state
To feedback the flash toggle state
Enumerator:
MFLASH_ECC_NORMAL
data poll normal
MFLASH_ECC_ABNORMAL
data poll abnormal
Definition at line 199 of file mainflash.h.
enum en_mflash_state
state feedback
To feedback the flash operation state
Enumerator:
MFLASH_RET_OK
OK.
MFLASH_RET_INVALID_PARA
parameter error
MFLASH_RET_ABNORMAL
operation fail
MFLASH_RET_ECCERROR
flash ECC verify error
Definition at line 164 of file mainflash.h.
enum en_mflash_toggle
check toggle state
To feedback the flash toggle state
Enumerator:
MFLASH_CHK_TOGG_NORMAL
flash toggle normal
MFLASH_CHK_TOGG_ABNORMAL
flash toggle abnormal
Definition at line 177 of file mainflash.h.
Function Documentation
static __ramfunc en_mflash_toggle_t MFlash_CheckToggle (uint16_t * pu16Addr) [static]
automatic algorithm of flash memory execution
Parameters:
pu16Addr address of flash data
Returns:
Operation status
Return values:
MFLASH_RET_OK
MFLASH_RET_ABNORMAL
MFLASH_RET_INVALID_PARA
Definition at line 516 of file mainflash.c.
References Flash_Read, MFLASH_CHK_TLOV_MASK, MFLASH_CHK_TOGG_ABNORMAL, MFLASH_CHK_TOGG_MASK, and MFLASH_CHK_TOGG_NORMAL.
Referenced by MFlash_ChipErase(), MFlash_SectorErase(), MFlash_WriteData16Bit(), MFlash_WriteData16Bit_Fm0Type3CrSecureArea(), and MFlash_WriteData32Bit().
en_result_t MFlash_ChipErase (boolean_t bCrRemain)
Flash chip erase.
Parameters:
bCrRemain Protect CR data or not
TRUE Remain CR data after chip erase
FALSE CR data will be lost after chip erase
Returns:
Operation status
Return values:
Ok Chip erase successfully done.
ErrorInvalidParameter If one of following conditions are met:
automatic algorithm of flash memory execution abnormally
Definition at line 159 of file mainflash.c.
References CR_DATA_ADDR, Flash_Read, Flash_Write, MFlash_CheckToggle(), MFLASH_CHK_TOGG_ABNORMAL, MFLASH_CODE1, MFLASH_CODE2, and MFlash_ReadResetCmd().
static en_mflash_toggle_t MFlash_DualCheckToggle (uint16_t * pu16Addr) [static]
automatic algorithm of flash memory execution
Parameters:
pu16Addr address of flash data
Returns:
Operation status
Return values:
MFLASH_RET_OK
MFLASH_RET_ABNORMAL
MFLASH_RET_INVALID_PARA
Definition at line 588 of file mainflash.c.
References Flash_Read, MFLASH_CHK_TLOV_MASK, MFLASH_CHK_TOGG_ABNORMAL, MFLASH_CHK_TOGG_MASK, and MFLASH_CHK_TOGG_NORMAL.
Referenced by MFlash_DualSectorErase(), MFlash_DualWriteData16Bit(), and MFlash_DualWriteData32Bit().
static void MFlash_DualReadResetCmd (uint16_t * pu16ResetSecAddr) [static]
Issue read/reset command.
Parameters:
pu16ResetSecAddr address of sector
Returns:
None
Definition at line 563 of file mainflash.c.
References Flash_Read, and Flash_Write.
Referenced by MFlash_DualSectorErase(), MFlash_DualWriteData16Bit(), and MFlash_DualWriteData32Bit().
en_result_t MFlash_DualSectorErase (uint16_t * pu16SecAddr)
Dual Flash sector erase.
Parameters:
pu16SecAddr address of flash sector
Returns:
Operation status
Return values:
Ok sector erase successfully done.
ErrorInvalidParameter If one of following conditions are met:
automatic algorithm of flash memory execution abnormally
< set 16 bit read/write (CPU programming mode)
< set 32 bit read(CPU ROM mode)
Definition at line 637 of file mainflash.c.
References Flash_Write, MFLASH_CHK_TOGG_ABNORMAL, MFLASH_CODE1, MFLASH_CODE2, MFlash_DualCheckToggle(), and MFlash_DualReadResetCmd().
en_result_t MFlash_DualWriteData16Bit (uint16_t * pu16WriteAddr, uint16_t * pu16WriteData, uint32_t u32Size)
Dual Flash half-word write.
Parameters:
pu16WriteAddr address of flash data
pu16WriteData pointer to write data
u32Size data size, 1 indicates 1 16-bit data
Returns:
Operation status
Return values:
Ok Dual Flash written successfully done.
ErrorInvalidParameter If one of following conditions are met:
automatic algorithm of flash memory execution abnormally
ECC abnormally
< set 16 bit read/write (CPU programming mode)
< set 32 bit read(CPU ROM mode)
Definition at line 822 of file mainflash.c.
References Flash_Read, Flash_Write, MFLASH_CHK_TOGG_ABNORMAL, MFLASH_CODE1, MFLASH_CODE2, MFlash_DualCheckToggle(), and MFlash_DualReadResetCmd().
en_result_t MFlash_DualWriteData32Bit (uint32_t * pu32WriteAddr, uint32_t * pu32WriteData, uint32_t u32Size, boolean_t bVerifyAndEccCheck)
Dual Flash word write with ECC.
Parameters:
pu32WriteAddr address of flash data
pu32WriteData pointer to write data
u32Size data size, 1 indicates 1 32-bit data
bVerifyAndEccCheck Whether to verify and check ECC
Returns:
Operation status
Return values:
Ok Dual Flash written successfully done.
ErrorInvalidParameter If one of following conditions are met:
automatic algorithm of flash memory execution abnormally
ECC abnormally
< set 16 bit read/write (CPU programming mode)
< set 32 bit read(CPU ROM mode)
< clear ECC error bit
Definition at line 754 of file mainflash.c.
References Flash_Read, Flash_Write, MFLASH_CHK_TOGG_ABNORMAL, MFLASH_CODE1, MFLASH_CODE2, MFlash_DualCheckToggle(), MFlash_DualReadResetCmd(), MFLASH_ECC_ABNORMAL, and MFLASH_ECC_NORMAL.
static __ramfunc void MFlash_ReadResetCmd (uint16_t * pu16ResetSecAddr) [static]
Issue read/reset command.
Parameters:
pu16ResetSecAddr address of sector
Returns:
None
Definition at line 125 of file mainflash.c.
References Flash_Read, and Flash_Write.
Referenced by MFlash_ChipErase(), MFlash_SectorErase(), MFlash_WriteData16Bit(), MFlash_WriteData16Bit_Fm0Type3CrSecureArea(), and MFlash_WriteData32Bit().
en_result_t MFlash_SectorErase (uint16_t * pu16SecAddr)
Flash sector erase.
Parameters:
pu16SecAddr address of flash sector
Returns:
Operation status
Return values:
Ok sector erase successfully done.
ErrorInvalidParameter If one of following conditions are met:
automatic algorithm of flash memory execution abnormally
Definition at line 254 of file mainflash.c.
References Flash_Write, MFlash_CheckToggle(), MFLASH_CHK_TOGG_ABNORMAL, MFLASH_CODE1, MFLASH_CODE2, and MFlash_ReadResetCmd().
en_result_t MFlash_SetDualMode (boolean_t bDualMode)
Set Dual Flash Mode of FM4 TYPE3 product.
Parameters:
bDualMode
TRUE Dual Flash mode
FALSE Single mode or Main Flash mode
Returns:
Ok Mode is set
Definition at line 685 of file mainflash.c.
en_result_t MFlash_SetRemapMode (boolean_t bRemapMode)
Set remap function of FM4 TYPE3 product.
Parameters:
bRemapMode
TRUE Remap mode
FALSE Normal mode
Returns:
Ok Mode is set
Note:
This mode is only aviable for S6E2CCA (with 2048k+40k Flash)
Definition at line 718 of file mainflash.c.
en_result_t MFlash_WriteData16Bit (uint16_t * pu16WriteAddr, uint16_t * pu16WriteData, uint32_t u32Size)
Flash half word write with ECC.
Parameters:
pu16WriteAddr address of flash data
pu16WriteData pointer to write data
u32Size data size, 1 indicates 1 16-bit data
Returns:
Operation status
Return values:
MFLASH_RET_OK
MFLASH_RET_ABNORMAL
MFLASH_RET_INVALID_PARA
Definition at line 388 of file mainflash.c.
References Flash_Read, Flash_Write, MFlash_CheckToggle(), MFLASH_CHK_TOGG_ABNORMAL, MFLASH_CODE1, MFLASH_CODE2, and MFlash_ReadResetCmd().
en_result_t MFlash_WriteData16Bit_Fm0Type3CrSecureArea (uint16_t * pu16WriteAddr, uint16_t * pu16WriteData, uint32_t u32Size)
Flash half word write with ECC.
Parameters:
pu16WriteAddr address of flash data
pu16WriteData pointer to write data
u32Size data size, 1 indicates 1 16-bit data
Returns:
Operation status
Return values:
MFLASH_RET_OK
MFLASH_RET_ABNORMAL
MFLASH_RET_INVALID_PARA
Definition at line 453 of file mainflash.c.
References Flash_Read, Flash_Write, MFlash_CheckToggle(), MFLASH_CHK_TOGG_ABNORMAL, MFLASH_CODE1, MFLASH_CODE2, and MFlash_ReadResetCmd().
en_result_t MFlash_WriteData32Bit (uint32_t * pu32WriteAddr, uint32_t * pu32WriteData, uint32_t u32Size, boolean_t bVerifyAndEccCheck)
Flash word write with ECC.
Parameters:
pu32WriteAddr address of flash data
pu32WriteData pointer to write data
u32Size data size, 1 indicates 1 32-bit data
bVerifyAndEccCheck Whether to verify and check ECC
Returns:
Operation status
Return values:
Ok Flash written successfully done.
ErrorInvalidParameter If one of following conditions are met:
automatic algorithm of flash memory execution abnormally
ECC abnormally
Definition at line 313 of file mainflash.c.
References Flash_Read, Flash_Write, MFlash_CheckToggle(), MFLASH_CHK_TOGG_ABNORMAL, MFLASH_CODE1, MFLASH_CODE2, MFLASH_ECC_ABNORMAL, MFLASH_ECC_NORMAL, and MFlash_ReadResetCmd().