PDL for FM Family: IC Card Interface (ICC)
IC Card Interface (ICC)
Data Structures
struct stc_icc_irq_en
ICC interrupt enable structure.
struct stc_icc_irq_cb
ICC interrupt callback function.
struct stc_icc_fifo_config
ICC FIFO configuration.
struct stc_icc_config
ICC configuration structure.
struct stc_icc_instance_data
ICC instance data type.
Defines
#define stc_iccn_t FM_ICC_TypeDef
#define ICC0 (*((volatile stc_iccn_t *) FM_ICC0_BASE))
#define ICC1 (*((volatile stc_iccn_t *) FM_ICC1_BASE))
#define ICC_INSTANCE_COUNT
Typedefs
typedef enum en_icc_idletmrclk en_icc_idletmrclk_t
ICC Idle timer source.
typedef enum en_icc_data_dir en_icc_data_dir_t
ICC data direction.
typedef enum en_icc_tx_data en_icc_tx_data_t
ICC transmit data format.
typedef enum en_icc_rx_data en_icc_rx_data_t
ICC receive data format.
typedef enum en_icc_irq_sel en_icc_irq_sel_t
ICC interrupt types.
typedef struct stc_icc_irq_en stc_icc_irq_en_t
ICC interrupt enable structure.
typedef struct stc_icc_irq_cb stc_icc_irq_cb_t
ICC interrupt callback function.
typedef struct stc_icc_irq_cb stc_icc_intern_data_t
typedef enum en_icc_status en_icc_status_t
ICC status types.
typedef struct stc_icc_fifo_config stc_icc_fifo_config_t
ICC FIFO configuration.
typedef struct stc_icc_config stc_icc_config_t
ICC configuration structure.
typedef enum en_icc_instance_index en_icc_instance_index_t
Enumeration to define an index for each enabled Icc instance.
typedef struct
stc_icc_instance_data stc_icc_instance_data_t
ICC instance data type.
Enumerations
enum en_icc_idletmrclk { IccCardClk = 0u, IccEtuClk = 1u }
ICC Idle timer source.
enum en_icc_data_dir { IccDataLsbFirst = 0u, IccDataMsbFirst = 1u }
ICC data direction.
enum en_icc_tx_data { IccTx8Even2 = 0u, IccTx8Odd2 = 1u, IccTx8None2 = 2u }
ICC transmit data format.
enum en_icc_rx_data {
IccRx8Even1 = 0u, IccRx8Odd1 = 1u, IccRx8None2 = 2u, IccRx8None1 = 3u,
IccRx9None1 = 4u
}
ICC receive data format.
enum en_icc_irq_sel {
IccRxFullIrq = 0u, IccTxEmptyIrq = 1u, IccRxStartBitIrq = 2u, IccCardEventIrq = 3u,
IccIdleTimerIrq = 4u, IccReadFifoIrq = 5u, IccWriteFifoIrq = 6u, IccReadFifoOverrunIrq = 7u
}
ICC interrupt types.
enum en_icc_status {
IccTxEmpty = 0u, IccRxFull = 1u, IccRxAction = 2u, IccTxAction = 3u,
IccCardDetect = 4u, IccCardEvent = 5u, IccReceiveOverflow = 6u, IccIdleTimerRun = 7u,
IccReadFifoOverrun = 8u, IccReadFifoFull = 9u, IccWriteFifoEmpty = 10u, IccRxStartErr = 11u,
IccTxResend = 12u, IccRxResend = 13u
}
ICC status types.
enum en_icc_instance_index { IccInstanceIndexIcc0, IccInstanceIndexIcc1, IccInstanceIndexMax, IccInstanceIndexUnknown = 0xFFu }
Enumeration to define an index for each enabled Icc instance.
Functions
static stc_icc_intern_data_t * IccGetInternDataPtr (volatile FM_ICC_TypeDef *pstcIcc)
Return the internal data for a certain ICC instance.
static void IccInitIrq (volatile FM_ICC_TypeDef *pstcIcc)
Device dependent initialization of interrupts according CMSIS with level defined in pdl_user.h.
static void IccDeInitIrq (volatile FM_ICC_TypeDef *pstcIcc)
Device dependent de-initialization of interrupts according CMSIS.
void Icc_IrqHandler (volatile FM_ICC_TypeDef *pstcIcc, stc_icc_intern_data_t *pstcIccInternData)
ICC interrupt service routine.
en_result_t Icc_EnableIrq (volatile FM_ICC_TypeDef *pstcIcc, en_icc_irq_sel_t enIrqSel)
Enable ICC interrupts.
en_result_t Icc_DisableIrq (volatile FM_ICC_TypeDef *pstcIcc, en_icc_irq_sel_t enIrqSel)
Disable ICC interrupts.
uint16_t Icc_ReadIrqStatus (volatile FM_ICC_TypeDef *pstcIcc)
Read ICC IRQ Status.
en_result_t Icc_Init (volatile FM_ICC_TypeDef *pstcIcc, stc_icc_config_t *pstcConfig)
Initialization of an ICC module to activate as ICC.
en_result_t Icc_DeInit (volatile FM_ICC_TypeDef *pstcIcc, boolean_t bTouchNvic)
Deinitialisation of a ICC module activating as ICC.
en_result_t Icc_Enable (volatile FM_ICC_TypeDef *pstcIcc)
Enable ICC Function.
en_result_t Icc_Disable (volatile FM_ICC_TypeDef *pstcIcc)
Disable ICC Function.
en_result_t Icc_SetBaudRate (volatile FM_ICC_TypeDef *pstcIcc, uint16_t u16BaudRate)
Set the baudrate of ICC.
boolean_t Icc_GetStatus (volatile FM_ICC_TypeDef *pstcIcc, en_icc_status_t enStatus)
Get status of ICC according to status type.
boolean_t Icc_GetIrqStatus (volatile FM_ICC_TypeDef *pstcIcc, en_icc_irq_sel_t enIrqSel)
Get interrupt status of ICC according to status type.
en_result_t Icc_SendData (volatile FM_ICC_TypeDef *pstcIcc, uint16_t u16Data)
Write ICC data buffer.
en_result_t Icc_SendFifoData (volatile FM_ICC_TypeDef *pstcIcc, uint16_t u16Data)
Write ICC FIFO data buffer.
uint16_t Icc_ReceiveData (volatile FM_ICC_TypeDef *pstcIcc)
Read ICC data buffer.
uint16_t Icc_ReceiveFifoData (volatile FM_ICC_TypeDef *pstcIcc)
Read ICC FIFO data buffer.
en_result_t Icc_ClearWriteFifo (volatile FM_ICC_TypeDef *pstcIcc)
Clear ICC Write FIFO.
en_result_t Icc_ClearReadFifo (volatile FM_ICC_TypeDef *pstcIcc)
Clear ICC Read FIFO.
en_result_t Icc_SetWriteFifoLevel (volatile FM_ICC_TypeDef *pstcIcc, uint8_t u8Level)
Set ICC TX FIFO level.
en_result_t Icc_SetReadFifoLevel (volatile FM_ICC_TypeDef *pstcIcc, uint8_t u8Level)
Set ICC TX FIFO level.
uint8_t Icc_GetWriteFifoCurCnt (volatile FM_ICC_TypeDef *pstcIcc)
Get ICC Write FIFO current count.
uint8_t Icc_GetReadFifoCurCnt (volatile FM_ICC_TypeDef *pstcIcc)
Get ICC Read FIFO current count.
en_result_t Icc_SetVpenPinLevel (volatile FM_ICC_TypeDef *pstcIcc, boolean_t bLevel)
Set ICC VPEN pin level.
en_result_t Icc_SetVccPinLevel (volatile FM_ICC_TypeDef *pstcIcc, boolean_t bLevel)
Set ICC VCC pin level.
en_result_t Icc_SetRstPinLevel (volatile FM_ICC_TypeDef *pstcIcc, boolean_t bLevel)
Set ICC Reset pin level.
en_result_t Icc_SetClkPinLevel (volatile FM_ICC_TypeDef *pstcIcc, boolean_t bLevel)
Set ICC Clock pin level.
en_result_t Icc_SetDataPinLevel (volatile FM_ICC_TypeDef *pstcIcc, boolean_t bLevel)
Set ICC Data pin level.
en_result_t Icc_SetIdleTimerCnt (volatile FM_ICC_TypeDef *pstcIcc, uint16_t u16Cnt)
Set count value of ICC Idle timer.
en_result_t Icc_StartIdleTimer (volatile FM_ICC_TypeDef *pstcIcc)
Start Idle timer.
en_result_t Icc_StopIdleTimer (volatile FM_ICC_TypeDef *pstcIcc)
Stop Idle timer.
Variables
stc_icc_instance_data_t m_astcIccInstanceDataLut [(uint8_t)(PDL_PERIPHERAL_ENABLE_ICC0==PDL_ON)+(uint8_t)(PDL_PERIPHERAL_ENABLE_ICC1==PDL_ON)]
Look-up table for all enabled ICC instances and their internal data.
stc_icc_instance_data_t m_astcIccInstanceDataLut [(uint8_t)(PDL_PERIPHERAL_ENABLE_ICC0==PDL_ON)+(uint8_t)(PDL_PERIPHERAL_ENABLE_ICC1==PDL_ON)]
Look-up table for all enabled Icc instances and their internal data.
Detailed Description
Provided functions of ICC module:
Icc_Init()
Icc_DeInit()
Icc_Enable()
Icc_Disable()
Icc_EnableIrq()
Icc_DisableIrq()
Icc_SetBaudRate()
Icc_GetStatus()
Icc_GetIrqStatus()
Icc_SendData()
Icc_SendFifoData()
Icc_ReceiveData()
Icc_ReceiveFifoData()
Icc_ClearWriteFifo()
Icc_ClearReadFifo()
Icc_SetWriteFifoLevel()
Icc_SetReadFifoLevel()
Icc_GetWriteFifoCurCnt()
Icc_GetReadFifoCurCnt()
Icc_SetVpenPinLevel()
Icc_SetVccPinLevel()
Icc_SetRstPinLevel()
Icc_SetClkPinLevel()
Icc_SetDataPinLevel()
Icc_SetIdleTimerCnt()
Icc_StartIdleTimer()
Icc_StopIdleTimer()
Icc_Init() is used to initialize an ICC instance with parameter pstcConfig of type stc_icc_config_t.
Icc_DeInit() is used to reset all ICC related configuration register.
The interrupt can be configured in Icc_Init() first, after initialization, Icc_EnableIrq() enables ICC interrupt sources selected by parameter Icc_EnableIrq::enIrqSel. Icc_DisableIrq() disables the ICC interrupt sources selected by parameter Icc_EnableIrq::enIrqSel.
Icc_SetBaudRate() provides a possibility to change the ICC baudrate.
Icc_GetStatus() gets the status selected by structure type en_icc_status_t and Icc_GetIrqStatus() gets the IRQ status selected by the structure type en_icc_irq_sel_t.
Icc_SendData() writes a byte data into ICC transfer buffer Icc_SendFifoData() writes a byte data into ICC FIFO transfer buffer Icc_ReceiveData() reads a byte data from ICC receive buffer. Icc_ReceiveFifoData() reads a byte data from ICC FIFO receive buffer.
Icc_ClearWriteFifo() clear the write FIFO buffer of ICC.
Icc_ClearReadFifo() clear the read FIFO buffer of ICC.
Icc_SetWriteFifoLevel() sets the write FIFO level of ICC.
Icc_SetReadFifoLevel() sets the read FIFO level of ICC.
Icc_GetWriteFifoCurCnt() gets the current write FIFO count of ICC.
Icc_GetReadFifoCurCnt() gets the current read FIFO count of ICC.
Icc_SetVpenPinLevel() is used to set the level of VPEN pin.
Icc_SetVccPinLevel() is used to set the level of VPEN pin.
Icc_SetRstPinLevel() is used to set the level of Reset pin.
Icc_SetClkPinLevel() is used to set the level of Clock pin.
Icc_SetDataPinLevel() is used to set the level of Data pin.
Icc_StartIdleTimer() is used to start idle timer and Icc_StopIdleTimer() is used to stop idle timer.
Icc_SetIdleTimerCnt() is used to set the count of Idle Timer.
Define Documentation
#define ICC0 (*((volatile stc_iccn_t *) FM_ICC0_BASE))
Definition at line 159 of file icc.h.
Referenced by IccDeInitIrq(), and IccInitIrq().
#define ICC1 (*((volatile stc_iccn_t *) FM_ICC1_BASE))
Definition at line 160 of file icc.h.
Referenced by IccDeInitIrq(), and IccInitIrq().
#define ICC_INSTANCE_COUNT
Value:
(uint8_t)(PDL_PERIPHERAL_ENABLE_ICC0 == PDL_ON) + \
        (uint8_t)(PDL_PERIPHERAL_ENABLE_ICC1 == PDL_ON)
Definition at line 162 of file icc.h.
Referenced by IccGetInternDataPtr().
#define stc_iccn_t FM_ICC_TypeDef
Definition at line 157 of file icc.h.
Typedef Documentation
typedef enum en_icc_data_dir en_icc_data_dir_t
ICC data direction.
typedef enum en_icc_idletmrclk en_icc_idletmrclk_t
ICC Idle timer source.
typedef enum en_icc_instance_index en_icc_instance_index_t
Enumeration to define an index for each enabled Icc instance.
typedef enum en_icc_irq_sel en_icc_irq_sel_t
ICC interrupt types.
typedef enum en_icc_rx_data en_icc_rx_data_t
ICC receive data format.
typedef enum en_icc_status en_icc_status_t
ICC status types.
typedef enum en_icc_tx_data en_icc_tx_data_t
ICC transmit data format.
typedef struct stc_icc_config stc_icc_config_t
ICC configuration structure.
typedef struct stc_icc_fifo_config stc_icc_fifo_config_t
ICC FIFO configuration.
typedef struct stc_icc_instance_data stc_icc_instance_data_t
ICC instance data type.
typedef struct stc_icc_irq_cb stc_icc_intern_data_t
typedef struct stc_icc_irq_cb stc_icc_irq_cb_t
ICC interrupt callback function.
typedef struct stc_icc_irq_en stc_icc_irq_en_t
ICC interrupt enable structure.
Enumeration Type Documentation
enum en_icc_data_dir
ICC data direction.
Enumerator:
IccDataLsbFirst
LSB first.
IccDataMsbFirst
MSB first.
Definition at line 183 of file icc.h.
enum en_icc_idletmrclk
ICC Idle timer source.
Enumerator:
IccCardClk
Idle timer is clocked by card clock(ICx_CLK)
IccEtuClk
Idle timer is clocked by baud clock (ETU clock).
Definition at line 173 of file icc.h.
enum en_icc_instance_index
Enumeration to define an index for each enabled Icc instance.
Enumerator:
IccInstanceIndexIcc0
IccInstanceIndexIcc1
IccInstanceIndexMax
IccInstanceIndexUnknown
Definition at line 342 of file icc.h.
enum en_icc_irq_sel
ICC interrupt types.
Enumerator:
IccRxFullIrq
Receive buffer full interrupt.
IccTxEmptyIrq
Transmit buffer empty interrupt.
IccRxStartBitIrq
Receive start bit detected interrupt.
IccCardEventIrq
Card insert/pull out interrupt.
IccIdleTimerIrq
Idle timer interrupt.
IccReadFifoIrq
Receive FIFO interrupt.
IccWriteFifoIrq
Transfer FIFO interrupt.
IccReadFifoOverrunIrq
Receive FIFO overrun interrupt.
Definition at line 217 of file icc.h.
enum en_icc_rx_data
ICC receive data format.
Enumerator:
IccRx8Even1
8 bit with even parity and 2 stop bit
IccRx8Odd1
8 bit with odd parity and 2 stop bit
IccRx8None2
8 bit with none parity and 2 stop bit
IccRx8None1
8 bit with none parity and 1 stop bit
IccRx9None1
9 bit with none parity and 1 stop bit
Definition at line 204 of file icc.h.
enum en_icc_status
ICC status types.
Enumerator:
IccTxEmpty
Transmit buffer empty.
IccRxFull
Receive buffer full.
IccRxAction
Receive is in action.
IccTxAction
Transmit is in action.
IccCardDetect
Card insertion is detected.
IccCardEvent
Card event is detected.
IccReceiveOverflow
Receive buffer overflow.
IccIdleTimerRun
Idle timer running.
IccReadFifoOverrun
Read FIFO overflow.
IccReadFifoFull
Read FIFO full.
IccWriteFifoEmpty
Write FIFO empty.
IccRxStartErr
Receive start bit error.
IccTxResend
Trasmit detect resend.
IccRxResend
Receive detect resend.
Definition at line 269 of file icc.h.
enum en_icc_tx_data
ICC transmit data format.
Enumerator:
IccTx8Even2
8 bit with even parity and 2 stop bit
IccTx8Odd2
8 bit with odd parity and 2 stop bit
IccTx8None2
8 bit with none parity and 2 stop bit
Definition at line 193 of file icc.h.
Function Documentation
en_result_t Icc_ClearReadFifo (volatile FM_ICC_TypeDef * pstcIcc)
Clear ICC Read FIFO.
Parameters:
[in] pstcIcc Pointer to ICC instance
Return values:
Ok FIFO has been successfully reset
ErrorInvalidParameter If one of following conditions are met:
pstcIcc == NULL
Definition at line 1111 of file icc.c.
en_result_t Icc_ClearWriteFifo (volatile FM_ICC_TypeDef * pstcIcc)
Clear ICC Write FIFO.
Parameters:
[in] pstcIcc Pointer to ICC instance
Return values:
Ok FIFO has been successfully reset
ErrorInvalidParameter If one of following conditions are met:
pstcIcc == NULL
Definition at line 1088 of file icc.c.
en_result_t Icc_DeInit (volatile FM_ICC_TypeDef * pstcIcc, boolean_t bTouchNvic)
Deinitialisation of a ICC module activating as ICC.
All used icc register are reset to their default values.
Parameters:
[in] pstcIcc Pointer to ICC instance register area
[in] bTouchNvic Touch NVIC or not
Return values:
Ok Process successfully done.
ErrorInvalidParameter If one of following conditions are met:
pstcIcc == NULL
pstcIccInternData == NULL (invalid or disabled ICC unit (PDL_PERIPHERAL_ENABLE_ICC0))
Definition at line 748 of file icc.c.
References IccDeInitIrq(), IccGetInternDataPtr(), stc_icc_irq_cb::pfnCardEventIrqCb, stc_icc_irq_cb::pfnIdleTimerIrqCb, stc_icc_irq_cb::pfnReadFifoIrqCb, stc_icc_irq_cb::pfnReadFifoOverrunIrqCb, stc_icc_irq_cb::pfnRxFullIrqCb, stc_icc_irq_cb::pfnRxStartBitIrqCb, stc_icc_irq_cb::pfnTxEmptyIrqCb, and stc_icc_irq_cb::pfnWriteFifoIrqCb.
en_result_t Icc_Disable (volatile FM_ICC_TypeDef * pstcIcc)
Disable ICC Function.
Parameters:
[in] pstcIcc Pointer to ICC instance
Return values:
Ok ICC function is enabled successfully
ErrorInvalidParameter If one of following conditions are met:
pstcIcc == NULL
Definition at line 825 of file icc.c.
en_result_t Icc_DisableIrq (volatile FM_ICC_TypeDef * pstcIcc, en_icc_irq_sel_t enIrqSel)
Disable ICC interrupts.
Parameters:
[in] pstcIcc Pointer to ICC instance
[in] enIrqSel Interrupt selection
Return values:
Ok Interrupts has been disabled and callback fucntion pointers are set to NULL
ErrorInvalidParameter If one of following conditions are met:
pstcIcc == NULL
pstcInt == NULL
The NVIC IRQ is also disabled in this function if all interrupt sources are disable.
Definition at line 413 of file icc.c.
References IccCardEventIrq, IccIdleTimerIrq, IccReadFifoIrq, IccReadFifoOverrunIrq, IccRxFullIrq, IccRxStartBitIrq, IccTxEmptyIrq, and IccWriteFifoIrq.
en_result_t Icc_Enable (volatile FM_ICC_TypeDef * pstcIcc)
Enable ICC Function.
Parameters:
[in] pstcIcc Pointer to ICC instance
Return values:
Ok ICC function is enabled successfully
ErrorInvalidParameter If one of following conditions are met:
pstcIcc == NULL
Definition at line 802 of file icc.c.
en_result_t Icc_EnableIrq (volatile FM_ICC_TypeDef * pstcIcc, en_icc_irq_sel_t enIrqSel)
Enable ICC interrupts.
Parameters:
[in] pstcIcc Pointer to ICC instance
[in] enIrqSel Interrupt selection
Return values:
Ok Interrupts has been enabled and callback fucntions are set
ErrorInvalidParameter If one of following conditions are met:
pstcICC == NULL
pstcInt == NULL
pstcIntCb == NULL
Other invalid configuration
The NVIC IRQ is also enabled in this function.
Definition at line 355 of file icc.c.
References IccCardEventIrq, IccIdleTimerIrq, IccReadFifoIrq, IccReadFifoOverrunIrq, IccRxFullIrq, IccRxStartBitIrq, IccTxEmptyIrq, and IccWriteFifoIrq.
boolean_t Icc_GetIrqStatus (volatile FM_ICC_TypeDef * pstcIcc, en_icc_irq_sel_t enIrqSel)
Get interrupt status of ICC according to status type.
Parameters:
[in] pstcIcc Pointer to ICC instance
[in] enIrqSel ICC interrupt type
IccRxFullIrq RX buffer full interrupt status
IccTxEmptyIrq TX buffer empty interrupt status
IccRxStartBitIrq RX start bit detect interrupt status
IccCardEventIrq Card event interrupt status
IccIdleTimerIrq Idle timer interrupt status
IccReadFifoIrq Read FIFO interrupt status
IccWriteFifoIrq Write FIFO interrupt status
IccReadFifoOverrunIrq Read FIFO overrun interrupt status
Return values:
FALSE The interrupt status is not set
TRUE The interrupt status is set
Definition at line 965 of file icc.c.
References IccCardEventIrq, IccIdleTimerIrq, IccReadFifoIrq, IccReadFifoOverrunIrq, IccRxFullIrq, IccRxStartBitIrq, IccTxEmptyIrq, and IccWriteFifoIrq.
uint8_t Icc_GetReadFifoCurCnt (volatile FM_ICC_TypeDef * pstcIcc)
Get ICC Read FIFO current count.
Parameters:
[in] pstcIcc Pointer to ICC instance
Return values:
FIFO count
Definition at line 1211 of file icc.c.
boolean_t Icc_GetStatus (volatile FM_ICC_TypeDef * pstcIcc, en_icc_status_t enStatus)
Get status of ICC according to status type.
Parameters:
[in] pstcIcc Pointer to ICC instance
[in] enStatus ICC status type
IccTxEmpty Transmit buffer empty
IccRxFull Receive buffer full
IccRxAction Receive is in action
IccTxAction Transmit is in action
IccCardDetect Card insertion is detected
IccCardEvent Card event is detected
IccReceiveOverflow Receive buffer overflow
IccIdleTmrRun Idle timer running
IccRdFifoOverrun Read FIFO overflow
IccRdFifoFull Read FIFO full
IccWrFifoEmpty Write FIFO empty
IccTxResend Trasmit detect resend
IccRxResend Receive detect resend
Return values:
FALSE The event do not happen
TRUE The event happen
Definition at line 890 of file icc.c.
References IccCardDetect, IccCardEvent, IccIdleTimerRun, IccReadFifoFull, IccReadFifoOverrun, IccReceiveOverflow, IccRxAction, IccRxFull, IccRxResend, IccRxStartErr, IccTxAction, IccTxEmpty, IccTxResend, and IccWriteFifoEmpty.
uint8_t Icc_GetWriteFifoCurCnt (volatile FM_ICC_TypeDef * pstcIcc)
Get ICC Write FIFO current count.
Parameters:
[in] pstcIcc Pointer to ICC instance
Return values:
FIFO count
Definition at line 1184 of file icc.c.
en_result_t Icc_Init (volatile FM_ICC_TypeDef * pstcIcc, stc_icc_config_t * pstcConfig)
Initialization of an ICC module to activate as ICC.
Set registers to active ICC as ICC.
Parameters:
[in] pstcIcc Pointer to ICC instance register area
[in] pstcConfig ICC configuration
Return values:
Ok Process successfully done.
ErrorInvalidParameter If one of following conditions are met:
pstcICC == NULL
pstcConfig == NULL
pstcIccInternData == NULL (invalid or disabled ICC unit (PDL_PERIPHERAL_ENABLE_ICC0))
Definition at line 487 of file icc.c.
References stc_icc_irq_en::bCardEventIrq, stc_icc_config::bClkPinLevel, stc_icc_config::bClkPinMode, stc_icc_config::bClkPinOutputEn, stc_icc_config::bDataPinLevel, stc_icc_config::bDataPinMode, stc_icc_config::bDataPinOutputEn, stc_icc_config::bDataResend, stc_icc_irq_en::bIdleTimerIrq, stc_icc_config::bInvertData, stc_icc_irq_en::bReadFifoIrq, stc_icc_irq_en::bReadFifoOverrunIrq, stc_icc_config::bRstPinLevel, stc_icc_config::bRstPinOutputEn, stc_icc_irq_en::bRxFullIrq, stc_icc_irq_en::bRxStartBitIrq, stc_icc_config::bTouchNvic, stc_icc_irq_en::bTxEmptyIrq, stc_icc_config::bUseGuardTimer, stc_icc_config::bVccPinLevel, stc_icc_config::bVccPinOutputEn, stc_icc_config::bVpenPinLevel, stc_icc_config::bVpenPinOutputEn, stc_icc_irq_en::bWriteFifoIrq, stc_icc_config::enBitDirection, stc_icc_config::enIdleTimerSrcClk, stc_icc_config::enRxDataFormat, stc_icc_config::enTxDataFormat, IccCardClk, IccDataLsbFirst, IccDataMsbFirst, IccEtuClk, IccGetInternDataPtr(), IccInitIrq(), IccRx8Even1, IccRx8None1, IccRx8None2, IccRx8Odd1, IccRx9None1, IccTx8Even2, IccTx8None2, IccTx8Odd2, PDL_ZERO_STRUCT, stc_icc_irq_cb::pfnCardEventIrqCb, stc_icc_irq_cb::pfnIdleTimerIrqCb, stc_icc_irq_cb::pfnReadFifoIrqCb, stc_icc_irq_cb::pfnReadFifoOverrunIrqCb, stc_icc_irq_cb::pfnRxFullIrqCb, stc_icc_irq_cb::pfnRxStartBitIrqCb, stc_icc_irq_cb::pfnTxEmptyIrqCb, stc_icc_irq_cb::pfnWriteFifoIrqCb, stc_icc_config::pstcFifoConfig, stc_icc_config::pstcIrqCb, stc_icc_config::pstcIrqEn, stc_icc_fifo_config::RxFifoLevel, stc_icc_fifo_config::TxFifoLevel, stc_icc_config::u16BaudRate, stc_icc_config::u16ClkDiv, stc_icc_config::u16IdleTimerCnt, and stc_icc_config::u8GuardTime.
void Icc_IrqHandler (volatile FM_ICC_TypeDef * pstcIcc, stc_icc_intern_data_t * pstcIccInternData)
ICC interrupt service routine.
Parameters:
pstcIcc Pointer to ICC instance
pstcIccInternData Pointer to ICC internal data structure
This function is called on Interrupt set by the ICC.
Definition at line 261 of file icc.c.
References stc_icc_irq_cb::pfnCardEventIrqCb, stc_icc_irq_cb::pfnIdleTimerIrqCb, stc_icc_irq_cb::pfnReadFifoIrqCb, stc_icc_irq_cb::pfnReadFifoOverrunIrqCb, stc_icc_irq_cb::pfnRxFullIrqCb, stc_icc_irq_cb::pfnRxStartBitIrqCb, stc_icc_irq_cb::pfnTxEmptyIrqCb, and stc_icc_irq_cb::pfnWriteFifoIrqCb.
uint16_t Icc_ReadIrqStatus (volatile FM_ICC_TypeDef * pstcIcc)
Read ICC IRQ Status.
Parameters:
[in] pstcIcc Pointer to ICC instance
Return values:
Receive data
Definition at line 463 of file icc.c.
uint16_t Icc_ReceiveData (volatile FM_ICC_TypeDef * pstcIcc)
Read ICC data buffer.
Parameters:
[in] pstcIcc Pointer to ICC instance
Return values:
Receive data
Definition at line 1058 of file icc.c.
uint16_t Icc_ReceiveFifoData (volatile FM_ICC_TypeDef * pstcIcc)
Read ICC FIFO data buffer.
Parameters:
[in] pstcIcc Pointer to ICC instance
Return values:
Receive data
Definition at line 1072 of file icc.c.
en_result_t Icc_SendData (volatile FM_ICC_TypeDef * pstcIcc, uint16_t u16Data)
Write ICC data buffer.
Parameters:
[in] pstcIcc Pointer to ICC instance
[in] u16Data Send data
Return values:
Ok Data has been successfully sent
ErrorInvalidParameter If one of following conditions are met:
pstcIcc == NULL
Definition at line 1013 of file icc.c.
en_result_t Icc_SendFifoData (volatile FM_ICC_TypeDef * pstcIcc, uint16_t u16Data)
Write ICC FIFO data buffer.
Parameters:
[in] pstcIcc Pointer to ICC instance
[in] u16Data Send data
Return values:
Ok Data has been successfully sent
ErrorInvalidParameter If one of following conditions are met:
pstcIcc == NULL
Definition at line 1037 of file icc.c.
en_result_t Icc_SetBaudRate (volatile FM_ICC_TypeDef * pstcIcc, uint16_t u16BaudRate)
Set the baudrate of ICC.
Parameters:
[in] pstcIcc Pointer to ICC instance
[in] u16BaudRate Baudrate value [bps]
Return values:
Ok ICC baud rate has been successfully modified
ErrorInvalidParameter If one of following conditions are met:
pstcIcc == NULL
Note:
The ICC baud rate can be initialized in the Icc_Init() and be modified in the funciton.
Definition at line 853 of file icc.c.
en_result_t Icc_SetClkPinLevel (volatile FM_ICC_TypeDef * pstcIcc, boolean_t bLevel)
Set ICC Clock pin level.
Parameters:
[in] pstcIcc Pointer to ICC instance
[in] bLevel Pin level
Return values:
Ok Pin level has been successfully set
ErrorInvalidParameter If one of following conditions are met:
pstcIcc == NULL
Definition at line 1319 of file icc.c.
en_result_t Icc_SetDataPinLevel (volatile FM_ICC_TypeDef * pstcIcc, boolean_t bLevel)
Set ICC Data pin level.
Parameters:
[in] pstcIcc Pointer to ICC instance
[in] bLevel Pin level
Return values:
Ok Pin level has been successfully set
ErrorInvalidParameter If one of following conditions are met:
pstcIcc == NULL
Definition at line 1345 of file icc.c.
en_result_t Icc_SetIdleTimerCnt (volatile FM_ICC_TypeDef * pstcIcc, uint16_t u16Cnt)
Set count value of ICC Idle timer.
Parameters:
[in] pstcIcc Pointer to ICC instance
[in] u16Cnt Timer count
Return values:
Ok Configuration has been successfully set
ErrorInvalidParameter If one of following conditions are met:
pstcIcc == NULL
Definition at line 1372 of file icc.c.
en_result_t Icc_SetReadFifoLevel (volatile FM_ICC_TypeDef * pstcIcc, uint8_t u8Level)
Set ICC TX FIFO level.
Parameters:
[in] pstcIcc Pointer to ICC instance
[in] u8Level FIFO level
Return values:
Ok FIFO level has been successfully set
ErrorInvalidParameter If one of following conditions are met:
pstcIcc == NULL
Definition at line 1160 of file icc.c.
en_result_t Icc_SetRstPinLevel (volatile FM_ICC_TypeDef * pstcIcc, boolean_t bLevel)
Set ICC Reset pin level.
Parameters:
[in] pstcIcc Pointer to ICC instance
[in] bLevel Pin level
Return values:
Ok Pin level has been successfully set
ErrorInvalidParameter If one of following conditions are met:
pstcIcc == NULL
Definition at line 1293 of file icc.c.
en_result_t Icc_SetVccPinLevel (volatile FM_ICC_TypeDef * pstcIcc, boolean_t bLevel)
Set ICC VCC pin level.
Parameters:
[in] pstcIcc Pointer to ICC instance
[in] bLevel Pin level
Return values:
Ok Pin level has been successfully set
ErrorInvalidParameter If one of following conditions are met:
pstcIcc == NULL
Definition at line 1267 of file icc.c.
en_result_t Icc_SetVpenPinLevel (volatile FM_ICC_TypeDef * pstcIcc, boolean_t bLevel)
Set ICC VPEN pin level.
Parameters:
[in] pstcIcc Pointer to ICC instance
[in] bLevel Pin level
Return values:
Ok Pin level has been successfully set
ErrorInvalidParameter If one of following conditions are met:
pstcIcc == NULL
Definition at line 1241 of file icc.c.
en_result_t Icc_SetWriteFifoLevel (volatile FM_ICC_TypeDef * pstcIcc, uint8_t u8Level)
Set ICC TX FIFO level.
Parameters:
[in] pstcIcc Pointer to ICC instance
[in] u8Level FIFO level
Return values:
Ok FIFO level has been successfully set
ErrorInvalidParameter If one of following conditions are met:
pstcIcc == NULL
Definition at line 1135 of file icc.c.
en_result_t Icc_StartIdleTimer (volatile FM_ICC_TypeDef * pstcIcc)
Start Idle timer.
Parameters:
[in] pstcIcc Pointer to ICC instance
Return values:
Ok No error
ErrorInvalidParameter If one of following conditions are met:
pstcIcc == NULL
Definition at line 1397 of file icc.c.
en_result_t Icc_StopIdleTimer (volatile FM_ICC_TypeDef * pstcIcc)
Stop Idle timer.
Parameters:
[in] pstcIcc Pointer to ICC instance
Return values:
Ok No error
ErrorInvalidParameter If one of following conditions are met:
pstcIcc == NULL
Definition at line 1420 of file icc.c.
static void IccDeInitIrq (volatile FM_ICC_TypeDef * pstcIcc) [static]
Device dependent de-initialization of interrupts according CMSIS.
Parameters:
pstcIcc Pointer to ICC instance
Definition at line 168 of file icc.c.
References ICC0, ICC1, and PDL_DEFAULT_INTERRUPT_LEVEL.
Referenced by Icc_DeInit().
static stc_icc_intern_data_t * IccGetInternDataPtr (volatile FM_ICC_TypeDef * pstcIcc) [static]
Return the internal data for a certain ICC instance.
Parameters:
pstcIcc Pointer to ICC instance
Returns:
Pointer to internal data or NULL if instance is not enabled (or not known)
Definition at line 228 of file icc.c.
References ICC_INSTANCE_COUNT, and stc_icc_instance_data::stcInternData.
Referenced by Icc_DeInit(), and Icc_Init().
static void IccInitIrq (volatile FM_ICC_TypeDef * pstcIcc) [static]
Device dependent initialization of interrupts according CMSIS with level defined in pdl_user.h.
Parameters:
pstcIcc Pointer to ICC instance
Definition at line 116 of file icc.c.
References ICC0, ICC1, and PDL_IRQ_LEVEL_ICC1_FLASH.
Referenced by Icc_Init().
Variable Documentation
stc_icc_instance_data_t m_astcIccInstanceDataLut[(uint8_t)(PDL_PERIPHERAL_ENABLE_ICC0==PDL_ON)+(uint8_t)(PDL_PERIPHERAL_ENABLE_ICC1==PDL_ON)]
Initial value:
{
    {
        & (*((volatile  FM_ICC_TypeDef  *) FM_ICC0_BASE)) ,
        0u,
    },
    {
        & (*((volatile  FM_ICC_TypeDef  *) FM_ICC1_BASE)) ,
        0u,
    },
}
Look-up table for all enabled ICC instances and their internal data.
Look-up table for all enabled Icc instances and their internal data.
Definition at line 74 of file icc.c.
stc_icc_instance_data_t m_astcIccInstanceDataLut[(uint8_t)(PDL_PERIPHERAL_ENABLE_ICC0==PDL_ON)+(uint8_t)(PDL_PERIPHERAL_ENABLE_ICC1==PDL_ON)]
Look-up table for all enabled Icc instances and their internal data.
Definition at line 74 of file icc.c.