PDL for FM Family: LCD controller (LCD)
LCD controller (LCD)
Data Structures
struct stc_lcd_clk_config
Select lcd source clock and configure clock division ratio.
struct stc_lcd_vv_sel
VVx selection bit.
struct stc_lcd_seg_sel1
These bits control I/O port status and analog switches for SEG outputs.
struct stc_lcd_seg_sel2
These bits control I/O port status and analog switches for SEG outputs.
struct stc_lcd_com_sel
These bits control I/O port status and analog switches for COM outputs.
struct stc_lcd_booster
LCD booster function.
struct stc_lcd_config
Clock Supervisor configuration.
Defines
#define LCD_RAM_MAX_INDEX (39u)
Typedefs
typedef enum en_lcd_div_mode en_lcd_div_mode_t
Select divider resitors to create LCD drive power.
typedef enum en_lcd_disp_mode en_lcd_disp_mode_t
Divider resistor value selection.
typedef enum en_lcd_div_res_val en_lcd_div_res_val_t
Divider resistor value selection.
typedef enum en_lcd_8com_bias en_lcd_8com_bias_t
8 COM mode bias selection
typedef enum en_lcd_src_clk_sel en_lcd_src_clk_sel_t
Source clock selection.
typedef struct stc_lcd_clk_config stc_lcd_clk_config_t
Select lcd source clock and configure clock division ratio.
typedef struct stc_lcd_vv_sel stc_lcd_vv_sel_t
VVx selection bit.
typedef struct stc_lcd_seg_sel1 stc_lcd_seg_sel1_t
These bits control I/O port status and analog switches for SEG outputs.
typedef struct stc_lcd_seg_sel2 stc_lcd_seg_sel2_t
These bits control I/O port status and analog switches for SEG outputs.
typedef struct stc_lcd_com_sel stc_lcd_com_sel_t
These bits control I/O port status and analog switches for COM outputs.
typedef enum en_lcd_input_io_mode en_lcd_input_io_mode_t
controls I/O ports shared by COM and SEG.
typedef enum en_lcd_blink_interval en_lcd_blink_interval_t
Blink interval.
typedef enum
en_lcd_ram_bit_operation en_lcd_ram_bit_operation_t
Blink interval.
typedef enum en_lcd_blink_operation en_lcd_blink_operation_t
LCD blink function enumeration.
typedef enum en_lcd_blink_dot_t en_lcd_blink_dot_t
LCD blink SEG COM dot enumeration.
typedef struct stc_lcd_booster stc_lcd_booster_t
LCD booster function.
typedef struct stc_lcd_config stc_lcd_config_t
Clock Supervisor configuration.
Enumerations
enum en_lcd_div_mode { LcdcExtRes = 0u, LcdcIntRes = 1u }
Select divider resitors to create LCD drive power.
enum en_lcd_disp_mode {
LcdStop = 0u, Lcd_4Com_1Div2Duty = 1u, Lcd_4Com_1Div3Duty = 2u, Lcd_4Com_1Div4Duty = 3u,
Lcd_8Com_1Div8Duty = 4u
}
Divider resistor value selection.
enum en_lcd_div_res_val { LcdDivRes100K = 0u, LcdDivRes10K = 1u }
Divider resistor value selection.
enum en_lcd_8com_bias { Lcd1Div3Bias = 0u, Lcd1Div4Bias = 1u }
8 COM mode bias selection
enum en_lcd_src_clk_sel { LcdClkSelSubClk = 0u, LcdClkSelPclk = 1u }
Source clock selection.
enum en_lcd_input_io_mode { LcdInputIoCutoff = 0u, LcdInputIoConnect = 1u }
controls I/O ports shared by COM and SEG.
enum en_lcd_blink_interval { LcdBlinkIntHalfSecond = 0u, LcdBlinkIntOneSecond = 1u }
Blink interval.
enum en_lcd_ram_bit_operation { LcdBitClr = 0u, LcdBitSet = 1u }
Blink interval.
enum en_lcd_blink_operation { LcdBlinkOff = 0u, LcdBlinkOn = 1u }
LCD blink function enumeration.
enum en_lcd_blink_dot_t {
LCDC_BlinkDotOff = 0u, LCDC_Blik4COMS3C3, LCDC_Blik4COMS3C2, LCDC_Blik4COMS3C1,
LCDC_Blik4COMS3C0, LCDC_Blik4COMS2C3, LCDC_Blik4COMS2C2, LCDC_Blik4COMS2C1,
LCDC_Blik4COMS2C0, LCDC_Blik4COMS1C3, LCDC_Blik4COMS1C2, LCDC_Blik4COMS1C1,
LCDC_Blik4COMS1C0, LCDC_Blik4COMS0C3, LCDC_Blik4COMS0C2, LCDC_Blik4COMS0C1,
LCDC_Blik4COMS0C0, LCDC_Blik8COMS1C7, LCDC_Blik8COMS1C6, LCDC_Blik8COMS1C5,
LCDC_Blik8COMS1C4, LCDC_Blik8COMS1C3, LCDC_Blik8COMS1C2, LCDC_Blik8COMS1C1,
LCDC_Blik8COMS1C0, LCDC_Blik8COMS0C7, LCDC_Blik8COMS0C6, LCDC_Blik8COMS0C5,
LCDC_Blik8COMS0C4, LCDC_Blik8COMS0C3, LCDC_Blik8COMS0C2, LCDC_Blik8COMS0C1,
LCDC_Blik8COMS0C0
}
LCD blink SEG COM dot enumeration.
Functions
static void LcdInitNvic (void)
Device dependent initialization of interrupts according CMSIS with level defined in pdl.h.
static void LcdDeInitNvic (void)
Device dependent de-initialization of interrupts according CMSIS.
void Lcd_IrqHandler (void)
Irq of the LCD module.
en_result_t Lcd_Init (stc_lcd_config_t *pstcConfig)
Initialize the LCD module.
void Lcd_DeInit (void)
De-Initialize LCD.
en_result_t Lcd_ConfInputIoMode (en_lcd_input_io_mode_t enInputIoMode)
Configure LCD input IO mode.
void Lcd_SetDispMode (en_lcd_disp_mode_t enDispMode)
Config LCD display mode.
void Lcd_EnableBlankDisp (void)
Blank is displayed.
void Lcd_DisableBlankDisp (void)
Data stored in LCDRAM is displayed.
en_result_t Lcd_WriteRAMBits (uint8_t u8RAMIndex, uint8_t u8Bitsmap, boolean_t bBit)
Set bitsmap in the LCD RAM .
en_result_t Lcd_WriteRAMBit (uint8_t u8RAMIndex, uint8_t u8BitIndex, boolean_t bBit)
Set 1 bit in the LCD RAM .
en_result_t Lcd_WriteRAMByte (uint8_t u8RAMIndex, uint8_t u8DataByte)
write byte to LCD RAM .
en_result_t Lcd_ReadRAMByte (uint8_t u8RAMIndex, uint8_t *pu8DataByte)
Read byte from LCD RAM .
void Lcd_FillWholeRam (void)
LCD is display all.
void Lcd_ClrWholeRam (void)
Clear LCD all.
en_result_t Lcd_SetBinkInterval (en_lcd_blink_interval_t enBlinkInterval)
Select blink interval time.
en_result_t Lcd_SetBlinkDot (en_lcd_blink_dot_t enBlinkDot, en_lcd_blink_operation_t enBlinkOp)
Select blink dot.
void Lcd_EnableIrq (void)
Enable lcd interrupt.
void Lcd_DisableIrq (void)
Disable lcd interrupt.
void Lcd_ClrIrqFlag (void)
Clear lcd interrupt flag.
boolean_t Lcd_GetIrqFlag (void)
Get lcd interrupt flag.
Variables
static func_ptr_t m_pfnIrqCb = NULL
Detailed Description
Provided functions of LCD module:
Lcd_Init()
Lcd_DeInit()
Lcd_ConfInputIoMode()
Lcd_SetDispMode()
Lcd_EnableBlankDisp()
Lcd_DisableBlankDisp()
Lcd_WriteRAMBits()
Lcd_WriteRAMBit()
Lcd_WriteRAMByte()
Lcd_ReadRAMByte();
Lcd_FillWholeRam()
Lcd_ClrWholeRam()
Lcd_SetBinkInterval()
Lcd_SetBlinkDot()
Lcd_EnableIrq()
Lcd_DisableIrq()
Lcd_ClrIrqFlag()
Lcd_GetIrqFlag()
Lcd_Init() initializes an LCD instance according the configuration of the structure type stc_lcd_config_t.
Lcd_DeInit() de-initializes an LCD instance.
Lcd_ConfInputIoMode() is used to config LCD input IO mode selected by the structure type en_lcd_input_io_mode_t.
Lcd_SetDispMode() is used to config LCD display mode selected by the structure type en_lcd_disp_mode_t
Lcd_EnableBlankDisp() can be used to display blank.
Lcd_DisableBlankDisp() can be used to display data stored in LCDRAM.
Lcd_WriteRAMBits() sets multi-bits in a byte of LCD RAM.
Lcd_WriteRAMBit() sets LCDRAM 1 bit n a byte of LCD RAM.
Lcd_WriteRAMByte() writes byte of LCD RAM
Lcd_ReadRAMByte() reads byte from LCD RAM.
Lcd_FillWholeRam() fills whole LCD RAM to display all.
Lcd_ClrWholeRam() clears whole LCDRAM.
Lcd_SetBinkInterval() selects blink interval time.
Lcd_SetBlinkDot() selects blink dot.
Lcd_EnableIrq() enables lcd interrupt.
Lcd_DisableIrq() disables lcd interrupt.
Lcd_ClrIrqFlag() clears interrupt flag.
Lcd_GetIrqFlag() gets interrupt flag.
Define Documentation
#define LCD_RAM_MAX_INDEX (39u)
Definition at line 68 of file lcd.c.
Referenced by Lcd_ClrWholeRam(), Lcd_FillWholeRam(), Lcd_ReadRAMByte(), Lcd_WriteRAMBit(), Lcd_WriteRAMBits(), and Lcd_WriteRAMByte().
Typedef Documentation
typedef enum en_lcd_8com_bias en_lcd_8com_bias_t
8 COM mode bias selection
typedef enum en_lcd_blink_dot_t en_lcd_blink_dot_t
LCD blink SEG COM dot enumeration.
typedef enum en_lcd_blink_interval en_lcd_blink_interval_t
Blink interval.
typedef enum en_lcd_blink_operation en_lcd_blink_operation_t
LCD blink function enumeration.
typedef enum en_lcd_disp_mode en_lcd_disp_mode_t
Divider resistor value selection.
typedef enum en_lcd_div_mode en_lcd_div_mode_t
Select divider resitors to create LCD drive power.
typedef enum en_lcd_div_res_val en_lcd_div_res_val_t
Divider resistor value selection.
typedef enum en_lcd_input_io_mode en_lcd_input_io_mode_t
controls I/O ports shared by COM and SEG.
typedef enum en_lcd_ram_bit_operation en_lcd_ram_bit_operation_t
Blink interval.
typedef enum en_lcd_src_clk_sel en_lcd_src_clk_sel_t
Source clock selection.
typedef struct stc_lcd_booster stc_lcd_booster_t
LCD booster function.
typedef struct stc_lcd_clk_config stc_lcd_clk_config_t
Select lcd source clock and configure clock division ratio.
typedef struct stc_lcd_com_sel stc_lcd_com_sel_t
These bits control I/O port status and analog switches for COM outputs.
typedef struct stc_lcd_config stc_lcd_config_t
Clock Supervisor configuration.
The Clock Supervisor configuration settings
typedef struct stc_lcd_seg_sel1 stc_lcd_seg_sel1_t
These bits control I/O port status and analog switches for SEG outputs.
typedef struct stc_lcd_seg_sel2 stc_lcd_seg_sel2_t
These bits control I/O port status and analog switches for SEG outputs.
typedef struct stc_lcd_vv_sel stc_lcd_vv_sel_t
VVx selection bit.
Note:
As VV4 pin cannot be used as GPIO when LCD controller is selected (LCDCC1:VSEL="1"), be sure to write "1" to VE4 bit.
Enumeration Type Documentation
enum en_lcd_8com_bias
8 COM mode bias selection
Enumerator:
Lcd1Div3Bias
1/3 bias is selected in 8 COM mode.
Lcd1Div4Bias
1/4 bias is selected in 8 COM mode.
Definition at line 181 of file lcd.h.
enum en_lcd_blink_dot_t
LCD blink SEG COM dot enumeration.
Enumerator:
LCDC_BlinkDotOff
LCD blink on.
LCDC_Blik4COMS3C3
lcdc blink for SEG3-COM3
LCDC_Blik4COMS3C2
lcdc blink for SEG3-COM2
LCDC_Blik4COMS3C1
lcdc blink for SEG3-COM1
LCDC_Blik4COMS3C0
lcdc blink for SEG3-COM0
LCDC_Blik4COMS2C3
lcdc blink for SEG2-COM3
LCDC_Blik4COMS2C2
lcdc blink for SEG2-COM2
LCDC_Blik4COMS2C1
lcdc blink for SEG2-COM1
LCDC_Blik4COMS2C0
lcdc blink for SEG2-COM0
LCDC_Blik4COMS1C3
lcdc blink for SEG1-COM3
LCDC_Blik4COMS1C2
lcdc blink for SEG1-COM2
LCDC_Blik4COMS1C1
lcdc blink for SEG1-COM1
LCDC_Blik4COMS1C0
lcdc blink for SEG1-COM0
LCDC_Blik4COMS0C3
lcdc blink for SEG0-COM3
LCDC_Blik4COMS0C2
lcdc blink for SEG0-COM2
LCDC_Blik4COMS0C1
lcdc blink for SEG0-COM1
LCDC_Blik4COMS0C0
lcdc blink for SEG0-COM0
LCDC_Blik8COMS1C7
lcdc blink for SEG1-COM7
LCDC_Blik8COMS1C6
lcdc blink for SEG1-COM6
LCDC_Blik8COMS1C5
lcdc blink for SEG1-COM5
LCDC_Blik8COMS1C4
lcdc blink for SEG1-COM4
LCDC_Blik8COMS1C3
lcdc blink for SEG1-COM3
LCDC_Blik8COMS1C2
lcdc blink for SEG1-COM2
LCDC_Blik8COMS1C1
lcdc blink for SEG1-COM1
LCDC_Blik8COMS1C0
lcdc blink for SEG1-COM0
LCDC_Blik8COMS0C7
lcdc blink for SEG0-COM7
LCDC_Blik8COMS0C6
lcdc blink for SEG0-COM6
LCDC_Blik8COMS0C5
lcdc blink for SEG0-COM5
LCDC_Blik8COMS0C4
lcdc blink for SEG0-COM4
LCDC_Blik8COMS0C3
lcdc blink for SEG0-COM3
LCDC_Blik8COMS0C2
lcdc blink for SEG0-COM2
LCDC_Blik8COMS0C1
lcdc blink for SEG0-COM1
LCDC_Blik8COMS0C0
lcdc blink for SEG0-COM0
Definition at line 372 of file lcd.h.
enum en_lcd_blink_interval
Blink interval.
Enumerator:
LcdBlinkIntHalfSecond
If sub-clock is 32.768 [kHz], the interval becomes 0.5 [s].
LcdBlinkIntOneSecond
If sub-clock is 32.768 [kHz], the interval becomes 1.0 [s].
Definition at line 340 of file lcd.h.
enum en_lcd_blink_operation
LCD blink function enumeration.
Enumerator:
LcdBlinkOff
LCD blink on.
LcdBlinkOn
LCD blink off.
Definition at line 362 of file lcd.h.
enum en_lcd_disp_mode
Divider resistor value selection.
Enumerator:
LcdStop
LCD controller stops display operations.
Lcd_4Com_1Div2Duty
4 COM mode, 1/2 duty
Lcd_4Com_1Div3Duty
4 COM mode, 1/3 duty
Lcd_4Com_1Div4Duty
4 COM mode, 1/4 duty
Lcd_8Com_1Div8Duty
8 COM mode, 1/8 duty
Definition at line 158 of file lcd.h.
enum en_lcd_div_mode
Select divider resitors to create LCD drive power.
Enumerator:
LcdcExtRes
External divider resistors are used to create LCD drive power.
LcdcIntRes
Internal divider resistors are used to create LCD drive power.
Definition at line 148 of file lcd.h.
enum en_lcd_div_res_val
Divider resistor value selection.
Enumerator:
LcdDivRes100K
100 k resistors are selected.
LcdDivRes10K
100 k resistors are selected.
Definition at line 171 of file lcd.h.
enum en_lcd_input_io_mode
controls I/O ports shared by COM and SEG.
Enumerator:
LcdInputIoCutoff
Input from I/O port is cut off.
LcdInputIoConnect
Input from I/O port is not cut off.
Definition at line 329 of file lcd.h.
enum en_lcd_ram_bit_operation
Blink interval.
Enumerator:
LcdBitClr
Clear lcd ram bit.
LcdBitSet
Set lcd ram bit.
Definition at line 351 of file lcd.h.
enum en_lcd_src_clk_sel
Source clock selection.
Enumerator:
LcdClkSelSubClk
Sub-clock is selected for LCDC source clock.
LcdClkSelPclk
PCLK is selected for LCDC source clock.
Definition at line 191 of file lcd.h.
Function Documentation
void Lcd_ClrIrqFlag (void)
Clear lcd interrupt flag.
Definition at line 681 of file lcd.c.
void Lcd_ClrWholeRam (void)
Clear LCD all.
Definition at line 548 of file lcd.c.
References LCD_RAM_MAX_INDEX.
en_result_t Lcd_ConfInputIoMode (en_lcd_input_io_mode_t enInputIoMode)
Configure LCD input IO mode.
Parameters:
enInputIoMode
LcdInputIoCutoff: Input IO of LCD is cut-off
LcdInputIoConnect: Input IO of LCD is not cut-off
Return values:
Ok LCD input IO mode is set normally.
ErrorInvalidParameter If one of following condition matches:
enInputIoMode > LcdInputIoConnect
Definition at line 348 of file lcd.c.
References LcdInputIoConnect, and LcdInputIoCutoff.
void Lcd_DeInit (void)
De-Initialize LCD.
Definition at line 313 of file lcd.c.
References LcdDeInitNvic(), and m_pfnIrqCb.
void Lcd_DisableBlankDisp (void)
Data stored in LCDRAM is displayed.
Definition at line 414 of file lcd.c.
void Lcd_DisableIrq (void)
Disable lcd interrupt.
Definition at line 669 of file lcd.c.
void Lcd_EnableBlankDisp (void)
Blank is displayed.
Definition at line 402 of file lcd.c.
void Lcd_EnableIrq (void)
Enable lcd interrupt.
Definition at line 658 of file lcd.c.
void Lcd_FillWholeRam (void)
LCD is display all.
Definition at line 532 of file lcd.c.
References LCD_RAM_MAX_INDEX.
boolean_t Lcd_GetIrqFlag (void)
Get lcd interrupt flag.
Return values:
TRUE LCD interrupt flag is set
FALSE LCD interrupt flag is clear
Definition at line 694 of file lcd.c.
en_result_t Lcd_Init (stc_lcd_config_t * pstcConfig)
Initialize the LCD module.
Parameters:
pstcConfig,: LCD module configuration
Return values:
Ok Initializiation of LCD successfully done.
ErrorInvalidParameter If one of following condition matches:
pstcConfig == NULL
pstcConfig->enDispMode > Lcd_8Com_1Div8Duty
pstcConfig->enDivResVal > LcdDivRes10K
pstcConfig->en8ComBias > Lcd1Div4Bias
pstcConfig->enInputIoMode > LcdInputIoConnect
pstcConfig->stcClkConf.u32DivVal > 0x200000u
pstcConfig->stcClkConf.u32DivVal == 0x00u
pstcConfig->stcClkConf.enSrcClk > LcdClkSelPclk
Definition at line 158 of file lcd.c.
References stc_lcd_config::bEnBlankDisp, stc_lcd_config::bEnBooster, stc_lcd_config::bEnDispRevs, stc_lcd_config::bIrqEn, stc_lcd_config::bTimerMod, stc_lcd_config::bTouchNvic, stc_lcd_config::en8ComBias, stc_lcd_config::enDispMode, stc_lcd_config::enDivMode, stc_lcd_config::enDivResVal, stc_lcd_config::enInputIoMode, stc_lcd_clk_config::enSrcClk, Lcd1Div3Bias, Lcd1Div4Bias, Lcd_4Com_1Div2Duty, Lcd_4Com_1Div3Duty, Lcd_4Com_1Div4Duty, Lcd_8Com_1Div8Duty, LcdcIntRes, LcdClkSelPclk, LcdClkSelSubClk, LcdDeInitNvic(), LcdDivRes100K, LcdDivRes10K, LcdInitNvic(), LcdInputIoConnect, LcdInputIoCutoff, LcdStop, m_pfnIrqCb, PDL_ZERO_STRUCT, stc_lcd_config::pfnIrqCb, stc_lcd_config::stcBooster, stc_lcd_config::stcClkConf, stc_lcd_config::stcComSel, stc_lcd_config::stcSegSel1, stc_lcd_config::stcSegSel2, stc_lcd_config::stcVvSel, and stc_lcd_clk_config::u32DivVal.
void Lcd_IrqHandler (void)
Irq of the LCD module.
Definition at line 125 of file lcd.c.
References m_pfnIrqCb.
en_result_t Lcd_ReadRAMByte (uint8_t u8RAMIndex, uint8_t * pu8DataByte)
Read byte from LCD RAM .
Parameters:
u8RAMIndex LCD RAM index
pu8DataByte pointer of buffer
Return values:
Ok Byte in the LCD RAM is read normally.
ErrorInvalidParameter If one of following condition matches:
u8RAMIndex > LCD_RAM_MAX_INDEX
Definition at line 518 of file lcd.c.
References LCD_RAM_MAX_INDEX.
en_result_t Lcd_SetBinkInterval (en_lcd_blink_interval_t enBlinkInterval)
Select blink interval time.
Parameters:
enBlinkInterval
LCD_BLINK_HALF_SEC blink interval is 0.5s
LCD_BLINK_ONE_SEC blink interval is 1s
Return values:
Ok Blink interval time is set normally.
ErrorInvalidParameter If one of following condition matches:
enBlinkInterval > LcdBlinkIntOneSecond
Definition at line 572 of file lcd.c.
References LcdBlinkIntHalfSecond, and LcdBlinkIntOneSecond.
en_result_t Lcd_SetBlinkDot (en_lcd_blink_dot_t enBlinkDot, en_lcd_blink_operation_t enBlinkOp)
Select blink dot.
Parameters:
enBlinkDot blink dot
enBlinkOp blink operation
Return values:
Ok Blink dot is set normally.
ErrorInvalidParameter If one of following condition matches:
enBlinkDot > LCDC_Blik8COMS0C0
LcdBlinkOff != enBlinkOp && LcdBlinkOn != enBlinkOp
Definition at line 602 of file lcd.c.
References LcdBlinkOff, LcdBlinkOn, LCDC_Blik4COMS0C0, LCDC_Blik4COMS0C1, LCDC_Blik4COMS0C2, LCDC_Blik4COMS0C3, LCDC_Blik4COMS1C0, LCDC_Blik4COMS1C1, LCDC_Blik4COMS1C2, LCDC_Blik4COMS1C3, LCDC_Blik4COMS2C0, LCDC_Blik4COMS2C1, LCDC_Blik4COMS2C2, LCDC_Blik4COMS2C3, LCDC_Blik4COMS3C0, LCDC_Blik4COMS3C1, LCDC_Blik4COMS3C2, LCDC_Blik4COMS3C3, LCDC_Blik8COMS0C0, LCDC_Blik8COMS0C1, LCDC_Blik8COMS0C2, LCDC_Blik8COMS0C3, LCDC_Blik8COMS0C4, LCDC_Blik8COMS0C5, LCDC_Blik8COMS0C6, LCDC_Blik8COMS0C7, LCDC_Blik8COMS1C0, LCDC_Blik8COMS1C1, LCDC_Blik8COMS1C2, LCDC_Blik8COMS1C3, LCDC_Blik8COMS1C4, LCDC_Blik8COMS1C5, LCDC_Blik8COMS1C6, LCDC_Blik8COMS1C7, and LCDC_BlinkDotOff.
void Lcd_SetDispMode (en_lcd_disp_mode_t enDispMode)
Config LCD display mode.
Parameters:
enDispMode
Definition at line 372 of file lcd.c.
References Lcd_4Com_1Div2Duty, Lcd_4Com_1Div3Duty, Lcd_4Com_1Div4Duty, Lcd_8Com_1Div8Duty, and LcdStop.
en_result_t Lcd_WriteRAMBit (uint8_t u8RAMIndex, uint8_t u8BitIndex, boolean_t bBit)
Set 1 bit in the LCD RAM .
Parameters:
u8RAMIndex LCD RAM index
u8BitIndex Bit index in a RAM byte
bBit Bit value
Return values:
Ok 1 bit in the LCD RAM is set normally.
ErrorInvalidParameter If one of following condition matches:
u8RAMIndex > LCD_RAM_MAX_INDEX
Definition at line 466 of file lcd.c.
References LCD_RAM_MAX_INDEX.
en_result_t Lcd_WriteRAMBits (uint8_t u8RAMIndex, uint8_t u8Bitsmap, boolean_t bBit)
Set bitsmap in the LCD RAM .
Parameters:
u8RAMIndex LCD RAM index
u8Bitsmap Bit map in a RAM byte
bBit Bit value
Return values:
Ok bitsmap in the LCD RAM is set normally.
ErrorInvalidParameter If one of following condition matches:
u8RAMIndex > LCD_RAM_MAX_INDEX
Definition at line 435 of file lcd.c.
References LCD_RAM_MAX_INDEX.
en_result_t Lcd_WriteRAMByte (uint8_t u8RAMIndex, uint8_t u8DataByte)
write byte to LCD RAM .
Parameters:
u8RAMIndex LCD RAM index
u8DataByte data to be written
Return values:
Ok Byte in the LCD RAM is read normally.
ErrorInvalidParameter If one of following condition matches:
u8RAMIndex > LCD_RAM_MAX_INDEX
Definition at line 496 of file lcd.c.
References LCD_RAM_MAX_INDEX.
static void LcdDeInitNvic (void) [static]
Device dependent de-initialization of interrupts according CMSIS.
Definition at line 112 of file lcd.c.
References PDL_DEFAULT_INTERRUPT_LEVEL.
Referenced by Lcd_DeInit(), and Lcd_Init().
static void LcdInitNvic (void) [static]
Device dependent initialization of interrupts according CMSIS with level defined in pdl.h.
Definition at line 99 of file lcd.c.
Referenced by Lcd_Init().
Variable Documentation
func_ptr_t m_pfnIrqCb = NULL [static]
Definition at line 74 of file lcd.c.
Referenced by Lcd_DeInit(), Lcd_Init(), and Lcd_IrqHandler().