PDL for FM Family: Quadrature Position/Revolution Counter (QPRC)
Quadrature Position/Revolution Counter (QPRC)
Data Structures
struct stc_qprc_irq_en
Enumeration to define QPRC interrupt selection.
struct stc_qprc_irq_cb
Enumeration to define QPRC interrupt callback function.
struct stc_qprc_filter
Structure to configuration QPRC filter.
struct stc_qprc_config
Structure to configuration QPRC.
struct stc_qprc_instance_data
Structure of QPRC instance data.
Defines
#define stc_qprcn_t FM_QPRC_TypeDef
#define QPRC0 (*((volatile stc_qprcn_t *) FM_QPRC0_BASE))
#define QPRC1 (*((volatile stc_qprcn_t *) FM_QPRC1_BASE))
#define QPRC2 (*((volatile stc_qprcn_t *) FM_QPRC2_BASE))
#define QPRC3 (*((volatile stc_qprcn_t *) FM_QPRC3_BASE))
#define stc_qprc_nfn_t FM_QPRC_NF_TypeDef
#define QPRCNF0 (*((volatile stc_qprc_nfn_t *) FM_QPRC0_NF_BASE))
#define QPRCNF1 (*((volatile stc_qprc_nfn_t *) FM_QPRC1_NF_BASE))
#define QPRCNF2 (*((volatile stc_qprc_nfn_t *) FM_QPRC2_NF_BASE))
#define QPRCNF3 (*((volatile stc_qprc_nfn_t *) FM_QPRC3_NF_BASE))
#define QPRC_INSTANCE_COUNT
#define QPRC_PC_OVERFLOW_INT 0u
#define QPRC_PC_UNDERFLOW_INT 1u
#define QPRC_PC_ZERO_INDEX_INT 2u
Typedefs
typedef enum en_qprc_instance_index en_qprc_instance_index_t
Enumeration to define an index for each QPRC instance.
typedef enum en_qprc_pcmode en_qprc_pcmode_t
Enumeration to define position counter mode.
typedef enum en_qprc_rcmode en_qprc_rcmode_t
Enumeration to define revolution counter mode.
typedef enum en_qprc_zinedge en_qprc_zinedge_t
Enumeration to define ZIN valid edge.
typedef enum en_qprc_binedge en_qprc_binedge_t
Enumeration to define BIN valid edge.
typedef enum en_qprc_ainedge en_qprc_ainedge_t
Enumeration to define AIN valid edge.
typedef enum en_qprc_pcresetmask en_qprc_pcresetmask_t
Enumeration to define reset mask times of position counter.
typedef enum en_qprc_compmode en_qprc_compmode_t
Enumeration to define compare object of QPRCR register.
typedef enum en_qprc_irq_sel en_qprc_irq_sel_t
Enumeration to define QPRC interrupt type.
typedef struct stc_qprc_irq_en stc_qprc_irq_en_t
Enumeration to define QPRC interrupt selection.
typedef struct stc_qprc_irq_cb stc_qprc_irq_cb_t
Enumeration to define QPRC interrupt callback function.
typedef struct stc_qprc_irq_cb stc_qprc_intern_data_t
typedef enum en_qprc_filter_width en_qprc_filter_width_t
Enumeration to define QPRC filter width.
typedef struct stc_qprc_filter stc_qprc_filter_t
Structure to configuration QPRC filter.
typedef struct stc_qprc_config stc_qprc_config_t
Structure to configuration QPRC.
typedef struct
stc_qprc_instance_data stc_qprc_instance_data_t
Structure of QPRC instance data.
Enumerations
enum en_qprc_instance_index { QprcInstanceIndexQprc0 = 0u, QprcInstanceIndexQprc1, QprcInstanceIndexQprc2, QprcInstanceIndexQprc3 }
Enumeration to define an index for each QPRC instance.
enum en_qprc_pcmode { QprcPcMode0 = 0u, QprcPcMode1 = 1u, QprcPcMode2 = 2u, QprcPcMode3 = 3u }
Enumeration to define position counter mode.
enum en_qprc_rcmode { QprcRcMode0 = 0u, QprcRcMode1 = 1u, QprcRcMode2 = 2u, QprcRcMode3 = 3u }
Enumeration to define revolution counter mode.
enum en_qprc_zinedge {
QprcZinDisable = 0u, QprcZinFallingEdge = 1u, QprcZinRisingEdge = 2u, QprcZinBothEdges = 3u,
QprcZinLowLevel = 4u, QprcZinHighLevel = 5u
}
Enumeration to define ZIN valid edge.
enum en_qprc_binedge { QprcBinDisable = 0u, QprcBinFallingEdge = 1u, QprcBinRisingEdge = 2u, QprcBinBothEdges = 3u }
Enumeration to define BIN valid edge.
enum en_qprc_ainedge { QprcAinDisable = 0u, QprcAinFallingEdge = 1u, QprcAinRisingEdge = 2u, QprcAinBothEdges = 3u }
Enumeration to define AIN valid edge.
enum en_qprc_pcresetmask { QprcResetMaskDisable = 0u, QprcResetMask2Times = 1u, QprcResetMask4Times = 2u, QprcResetMask8Times = 3u }
Enumeration to define reset mask times of position counter.
enum en_qprc_compmode { QprcCompareWithPosition = 0u, QprcCompareWithRevolution = 1u }
Enumeration to define compare object of QPRCR register.
enum en_qprc_irq_sel {
QprcPcOfUfZeroIrq = 0u, QprcPcMatchIrq = 1u, QprcPcRcMatchIrq = 2u, QprcPcMatchRcMatchIrq = 3u,
QprcPcCountInvertIrq = 4u, QprcRcOutrangeIrq = 5u
}
Enumeration to define QPRC interrupt type.
enum en_qprc_filter_width {
QprcNoFilter = 0u, QprcFilterWidth4Pclk = 1u, QprcFilterWidth8Pclk = 2u, QprcFilterWidth16Pclk = 3u,
QprcFilterWidth32Pclk = 4u, QprcFilterWidth64Pclk = 5u, QprcFilterWidth128Pclk = 6u, QprcFilterWidth256Pclk = 7u
}
Enumeration to define QPRC filter width.
Functions
static volatile
FM_QPRC_NF_TypeDef * QprcGetNoisFilterPtr (volatile FM_QPRC_TypeDef *pstcQprc)
Get the noise filter for a certain QPRC instance.
static stc_qprc_intern_data_t * QprcGetInternDataPtr (volatile FM_QPRC_TypeDef *pstcQprc)
Get the internal data for a certain QPRC instance.
static void QprcInitNvic (volatile FM_QPRC_TypeDef *pstcQprc)
Set NVIC Interrupt depending on QPRC instance.
static void QprcDeInitNvic (volatile FM_QPRC_TypeDef *pstcQprc)
Clear NVIC Interrupt depending on QPRC instance.
void Qprc_IrqHandler (volatile FM_QPRC_TypeDef *pstcQprc, stc_qprc_intern_data_t *pstcQprcInternData)
QPRC instance interrupt service routine.
en_result_t Qprc_Init (volatile FM_QPRC_TypeDef *pstcQprc, stc_qprc_config_t *pstcConfig)
Initialize QPRC.
en_result_t Qprc_DeInit (volatile FM_QPRC_TypeDef *pstcQprc, boolean_t bTouchNvic)
De-Initialize QPRC.
en_result_t Qprc_StopPcCount (volatile FM_QPRC_TypeDef *pstcQprc)
Stop Position Counter.
en_result_t Qprc_RestartPcCount (volatile FM_QPRC_TypeDef *pstcQprc)
Restart Position Counter from stop status.
en_result_t Qprc_SetPcCount (volatile FM_QPRC_TypeDef *pstcQprc, uint16_t u16PcValue)
Set count value of Position counter.
uint16_t Qprc_GetPcCount (volatile FM_QPRC_TypeDef *pstcQprc)
Get count value of Position counter.
en_result_t Qprc_SetRcCount (volatile FM_QPRC_TypeDef *pstcQprc, uint16_t u16RcValue)
Set count value of Revolution Counter.
uint16_t Qprc_GetRcCount (volatile FM_QPRC_TypeDef *pstcQprc)
Get count value of Revolution Counter.
en_result_t Qprc_SetPcMaxValue (volatile FM_QPRC_TypeDef *pstcQprc, uint16_t u16PcMaxValue)
Set maximum count value of Position Counter.
uint16_t Qprc_GetPcMaxValue (volatile FM_QPRC_TypeDef *pstcQprc)
Get maximum count value of Position Counter.
en_result_t Qprc_SetPcCompareValue (volatile FM_QPRC_TypeDef *pstcQprc, uint16_t u16PcValue)
Set compare value of Position counter.
uint16_t Qprc_GetPcCompareValue (volatile FM_QPRC_TypeDef *pstcQprc)
Get compare value of Position counter.
en_result_t Qprc_SetPcRcCompareValue (volatile FM_QPRC_TypeDef *pstcQprc, uint16_t u16PcRcValue)
Set compare value of Position and Revolution Counter.
uint16_t Qprc_GetPcRcCompareValue (volatile FM_QPRC_TypeDef *pstcQprc)
Get compare value of Position and Revolution Counter.
en_result_t Qprc_ConfigPcMode (volatile FM_QPRC_TypeDef *pstcQprc, en_qprc_pcmode_t enMode)
Set Position Counter mode.
en_result_t Qprc_ConfigRcMode (volatile FM_QPRC_TypeDef *pstcQprc, en_qprc_rcmode_t enMode)
Set Revolution Counter mode.
en_result_t Qprc_EnableIrq (volatile FM_QPRC_TypeDef *pstcQprc, en_qprc_irq_sel_t enIrqSel)
Enable QPRC interrupt.
en_result_t Qprc_DisableIrq (volatile FM_QPRC_TypeDef *pstcQprc, en_qprc_irq_sel_t enIrqSel)
Disable QPRC interrupt.
en_irq_flag_t Qprc_GetIrqFlag (volatile FM_QPRC_TypeDef *pstcQprc, en_qprc_irq_sel_t enIrqSel)
Get interrupt flag of QPRC.
en_result_t Qprc_ClrIrqFlag (volatile FM_QPRC_TypeDef *pstcQprc, en_qprc_irq_sel_t enIrqSel)
Clear interrupt flag of QPRC.
en_stat_flag_t Qprc_GetPcOfUfDir (volatile FM_QPRC_TypeDef *pstcQprc)
Get last position counter flow direction.
en_stat_flag_t Qprc_GetPcDir (volatile FM_QPRC_TypeDef *pstcQprc)
Get last position counter direction.
Variables
stc_qprc_instance_data_t m_astcQprcInstanceDataLut [(PDL_PERIPHERAL_ENABLE_QPRC0==PDL_ON?1u:0u)+(PDL_PERIPHERAL_ENABLE_QPRC1==PDL_ON?1u:0u)+(PDL_PERIPHERAL_ENABLE_QPRC2==PDL_ON?1u:0u)+(PDL_PERIPHERAL_ENABLE_QPRC3==PDL_ON?1u:0u)]
Look-up table for all enabled ADC instances and their internal data.
stc_qprc_instance_data_t m_astcQprcInstanceDataLut [(PDL_PERIPHERAL_ENABLE_QPRC0==PDL_ON?1u:0u)+(PDL_PERIPHERAL_ENABLE_QPRC1==PDL_ON?1u:0u)+(PDL_PERIPHERAL_ENABLE_QPRC2==PDL_ON?1u:0u)+(PDL_PERIPHERAL_ENABLE_QPRC3==PDL_ON?1u:0u)]
Look-up table for all enabled MFS instances and their internal data.
Detailed Description
Provided functions of QPRC module:
Qprc_Init()
Qprc_StopPcCount()
Qprc_RestartPcCount()
Qprc_SetPcCount()
Qprc_GetPcCount()
Qprc_SetRcCount()
Qprc_GetRcCount()
Qprc_SetPcCompareValue()
Qprc_GetPcCompareValue()
Qprc_SetPcRcCompareValue()
Qprc_GetPcRcCompareValue()
Qprc_ConfigPcMode()
Qprc_ConfigRcMode()
Qprc_EnableIrq()
Qprc_DisableIrq()
Qprc_GetIrqFlag()
Qprc_ClrIrqFlag()
Qprc_GetPcOfUfDir()
Qprc_GetPcDir()
How to use Position Count (PC) and Revolution Counter (RC)?
Qprc_Init() must be used for configuration of a QPRC channel with a structure of the type stc_qprc_config_t.
The interrupts can be configured in Qprc_Init(), after initialization, a QPRC interrupt can be enabled or disabled by the function Qprc_EnableIrq() and Qprc_DisableIrq().
With Qprc_SetPcCompareValue() the PC compare value is set to the value given in the parameter Qprc_SetPcCompareValue::u16PcValue. And PC compare value is read by Qprc_GetPcCompareValue().
With Qprc_SetPcRcCompareValue() the PC and RC compare value is set to the value given in the parameter Qprc_SetPcRcCompareValue::u16PcRcValue. And PC and RC compare value is read by Qprc_GetPcRcCompareValue(). Whether PC and RC compare value compares to PC count and RC count depends on the setting in paramter of the Qprc_Init().
The initial PC count value can be set by Qprc_SetPcCount(). And current PC count can be read by Qprc_GetPcCount()
The initial RC count value can be set by Qprc_SetRcCount(). And current RC count can be read by Qprc_GetRcCount()
The maximum PC count value can be set by Qprc_SetPcMaxValue(). And the maximum PC count value can be read by Qprc_GetPcMaxValue(). If PC count exceeds this value, a PC overflow interrupt flag will be set.
After above setting, Qprc_ConfigPcMode() can start PC with following mode:
Up-down count mode(PC mode 1)
Phase different count mode (PC mode 2)
Directional count mode (PC mode 3)
Qprc_ConfigRcMode() can start RC with following mode:
ZIN trigger mode(RC mode 1)
PC underflow or overflow detection trigger mode (RC mode 2)
ZIN or PC underflow or overflow detection trigger mode(RC mode 3)
With interrupt mode, when the interrupt occurs, the interrupt flag will be cleared and run into user interrupt callback function.
With polling mode, user can use Qprc_GetIrqFlag() to check if the interrupt occurs, and clear the interrupt flag by Qprc_ClrIrqFlag().
Qprc_GetPcOfUfDir() can get the PC direction after a PC overflow or underflow occurs.
Qprc_GetPcDir() can get the current PC direction when PC is counting.
Qprc_StopPcCount() can stop PC when PC is counting. And Qprc_RestartPcCount() will restart PC when PC is in stop status.
When stopping the QPRC, disable PC by using Qprc_ConfigPcMode() to set PC to PC mode0 and disable RC by using Qprc_ConfigRcMode() to set RC to RC mode0. Use QPRC_DisableIrq() to disable QPRC interrupt.
Define Documentation
#define QPRC0 (*((volatile stc_qprcn_t *) FM_QPRC0_BASE))
Definition at line 153 of file qprc.h.
#define QPRC1 (*((volatile stc_qprcn_t *) FM_QPRC1_BASE))
Definition at line 154 of file qprc.h.
#define QPRC2 (*((volatile stc_qprcn_t *) FM_QPRC2_BASE))
Definition at line 155 of file qprc.h.
#define QPRC3 (*((volatile stc_qprcn_t *) FM_QPRC3_BASE))
Definition at line 156 of file qprc.h.
#define QPRC_INSTANCE_COUNT
Value:
(PDL_PERIPHERAL_ENABLE_QPRC0 == PDL_ON ? 1u : 0u) + \
                                (PDL_PERIPHERAL_ENABLE_QPRC1 == PDL_ON ? 1u : 0u) + \
                                (PDL_PERIPHERAL_ENABLE_QPRC2 == PDL_ON ? 1u : 0u) + \
                                (PDL_PERIPHERAL_ENABLE_QPRC3 == PDL_ON ? 1u : 0u)
Definition at line 167 of file qprc.h.
Referenced by QprcGetInternDataPtr(), and QprcGetNoisFilterPtr().
#define QPRC_PC_OVERFLOW_INT 0u
Definition at line 172 of file qprc.h.
Referenced by Qprc_IrqHandler().
#define QPRC_PC_UNDERFLOW_INT 1u
Definition at line 173 of file qprc.h.
Referenced by Qprc_IrqHandler().
#define QPRC_PC_ZERO_INDEX_INT 2u
Definition at line 174 of file qprc.h.
Referenced by Qprc_IrqHandler().
#define QPRCNF0 (*((volatile stc_qprc_nfn_t *) FM_QPRC0_NF_BASE))
Definition at line 161 of file qprc.h.
#define QPRCNF1 (*((volatile stc_qprc_nfn_t *) FM_QPRC1_NF_BASE))
Definition at line 162 of file qprc.h.
#define QPRCNF2 (*((volatile stc_qprc_nfn_t *) FM_QPRC2_NF_BASE))
Definition at line 163 of file qprc.h.
#define QPRCNF3 (*((volatile stc_qprc_nfn_t *) FM_QPRC3_NF_BASE))
Definition at line 164 of file qprc.h.
#define stc_qprc_nfn_t FM_QPRC_NF_TypeDef
Definition at line 159 of file qprc.h.
Referenced by Qprc_DeInit(), Qprc_Init(), and QprcGetNoisFilterPtr().
#define stc_qprcn_t FM_QPRC_TypeDef
Definition at line 151 of file qprc.h.
Typedef Documentation
typedef enum en_qprc_ainedge en_qprc_ainedge_t
Enumeration to define AIN valid edge.
typedef enum en_qprc_binedge en_qprc_binedge_t
Enumeration to define BIN valid edge.
typedef enum en_qprc_compmode en_qprc_compmode_t
Enumeration to define compare object of QPRCR register.
typedef enum en_qprc_filter_width en_qprc_filter_width_t
Enumeration to define QPRC filter width.
typedef enum en_qprc_instance_index en_qprc_instance_index_t
Enumeration to define an index for each QPRC instance.
typedef enum en_qprc_irq_sel en_qprc_irq_sel_t
Enumeration to define QPRC interrupt type.
typedef enum en_qprc_pcmode en_qprc_pcmode_t
Enumeration to define position counter mode.
typedef enum en_qprc_pcresetmask en_qprc_pcresetmask_t
Enumeration to define reset mask times of position counter.
typedef enum en_qprc_rcmode en_qprc_rcmode_t
Enumeration to define revolution counter mode.
typedef enum en_qprc_zinedge en_qprc_zinedge_t
Enumeration to define ZIN valid edge.
typedef struct stc_qprc_config stc_qprc_config_t
Structure to configuration QPRC.
typedef struct stc_qprc_filter stc_qprc_filter_t
Structure to configuration QPRC filter.
typedef struct stc_qprc_instance_data stc_qprc_instance_data_t
Structure of QPRC instance data.
typedef struct stc_qprc_irq_cb stc_qprc_intern_data_t
typedef struct stc_qprc_irq_cb stc_qprc_irq_cb_t
Enumeration to define QPRC interrupt callback function.
typedef struct stc_qprc_irq_en stc_qprc_irq_en_t
Enumeration to define QPRC interrupt selection.
Enumeration Type Documentation
enum en_qprc_ainedge
Enumeration to define AIN valid edge.
Enumerator:
QprcAinDisable
Disables edge detection.
QprcAinFallingEdge
AIN active at falling edge.
QprcAinRisingEdge
AIN active at rising edge.
QprcAinBothEdges
AIN active at falling or rising edge.
Definition at line 250 of file qprc.h.
enum en_qprc_binedge
Enumeration to define BIN valid edge.
Enumerator:
QprcBinDisable
Disables edge detection.
QprcBinFallingEdge
BIN active at falling edge.
QprcBinRisingEdge
BIN active at rising edge.
QprcBinBothEdges
BIN active at falling or rising edge.
Definition at line 238 of file qprc.h.
enum en_qprc_compmode
Enumeration to define compare object of QPRCR register.
Enumerator:
QprcCompareWithPosition
Compares the value of the QPRC Position and Revolution Counter Compare Register (QPRCR) with that of the position counter.
QprcCompareWithRevolution
Compares the value of the QPRC Position and Revolution Counter Compare Register (QPRCR) with that of the revolution counter.
Definition at line 274 of file qprc.h.
enum en_qprc_filter_width
Enumeration to define QPRC filter width.
Enumerator:
QprcNoFilter
No filter.
QprcFilterWidth4Pclk
QPRC filter width: 4 PCLK.
QprcFilterWidth8Pclk
QPRC filter width: 8 PCLK.
QprcFilterWidth16Pclk
QPRC filter width: 16 PCLK.
QprcFilterWidth32Pclk
QPRC filter width: 32 PCLK.
QprcFilterWidth64Pclk
QPRC filter width: 64 PCLK.
QprcFilterWidth128Pclk
QPRC filter width: 128 PCLK.
QprcFilterWidth256Pclk
QPRC filter width: 256 PCLK.
Definition at line 329 of file qprc.h.
enum en_qprc_instance_index
Enumeration to define an index for each QPRC instance.
Enumerator:
QprcInstanceIndexQprc0
Instance index of QPRC0.
QprcInstanceIndexQprc1
Instance index of QPRC1.
QprcInstanceIndexQprc2
Instance index of QPRC2.
QprcInstanceIndexQprc3
Instance index of QPRC2.
Definition at line 180 of file qprc.h.
enum en_qprc_irq_sel
Enumeration to define QPRC interrupt type.
Enumerator:
QprcPcOfUfZeroIrq
Overflow, underflow, zero match interrupt of position counter.
QprcPcMatchIrq
PC match interrupt of position counter.
QprcPcRcMatchIrq
PC and RC match interrupt.
QprcPcMatchRcMatchIrq
PC match and RC match interrupt.
QprcPcCountInvertIrq
PC invert interrupt.
QprcRcOutrangeIrq
RC outrange interrupt.
Definition at line 284 of file qprc.h.
enum en_qprc_pcmode
Enumeration to define position counter mode.
Enumerator:
QprcPcMode0
PC_Mode0: Disable position counter.
QprcPcMode1
PC_Mode1: Increments with AIN active edge and decrements with BIN active edge.
QprcPcMode2
PC_Mode2: Phase difference count mode: Counts up if AIN is leading BIN, down if BIN leading.
QprcPcMode3
PC_Mode3: Directional count mode: Counts up/down with BIN active edge and AIN level.
Definition at line 200 of file qprc.h.
enum en_qprc_pcresetmask
Enumeration to define reset mask times of position counter.
Enumerator:
QprcResetMaskDisable
No reset mask.
QprcResetMask2Times
The position counter reset or a revolution counter count-up or -down events are ignored until the position counter changes twice.
QprcResetMask4Times
The position counter reset or a revolution counter count-up or -down events are ignored until the position counter changes four times.
QprcResetMask8Times
The position counter reset or a revolution counter count-up or -down events are ignored until the position counter changes eight times.
Definition at line 262 of file qprc.h.
enum en_qprc_rcmode
Enumeration to define revolution counter mode.
Enumerator:
QprcRcMode0
RC_Mode0: Disable revolution counter.
QprcRcMode1
RC_Mode1: Up/down count of revolution counter with ZIN active edge.
QprcRcMode2
RC_Mode2: Up/down count of revolution counter on overflow or underflow in position count match.
QprcRcMode3
RC_Mode3: Up/down count of revolution counter on overflow or underflow in position count match and ZIN active edge.
Definition at line 212 of file qprc.h.
enum en_qprc_zinedge
Enumeration to define ZIN valid edge.
Enumerator:
QprcZinDisable
Disables edge and level detection.
QprcZinFallingEdge
ZIN active at falling edge.
QprcZinRisingEdge
ZIN active at rising edge.
QprcZinBothEdges
ZIN active at falling or rising edge.
QprcZinLowLevel
ZIN active at low level detected.
QprcZinHighLevel
ZIN active at high level detected.
Definition at line 224 of file qprc.h.
Function Documentation
en_result_t Qprc_ClrIrqFlag (volatile FM_QPRC_TypeDef * pstcQprc, en_qprc_irq_sel_t enIrqSel)
Clear interrupt flag of QPRC.
Parameters:
[in] pstcQprc Pointer to QPRC instance
[in] enIrqSel Interrupt type
Return values:
Ok Clear interrupt flag successfully
ErrorInvalidParameter If one of following conditions are met:
pstcQprc invalid
enIntType > QprcRcOutrangeInt
Other invalid configuration
Definition at line 1287 of file qprc.c.
References PdlClr, QprcPcCountInvertIrq, QprcPcMatchIrq, QprcPcMatchRcMatchIrq, QprcPcOfUfZeroIrq, QprcPcRcMatchIrq, and QprcRcOutrangeIrq.
en_result_t Qprc_ConfigPcMode (volatile FM_QPRC_TypeDef * pstcQprc, en_qprc_pcmode_t enMode)
Set Position Counter mode.
Parameters:
[in] pstcQprc Pointer to QPRC instance
[in] enMode Position Counter mode
Return values:
Ok Position Counter mode has been setup
ErrorInvalidParameter If one of following conditions are met:
pstcQprc == NULL
enMode > QprcPcMode3
Other invalid configuration
Definition at line 997 of file qprc.c.
References QprcPcMode0, QprcPcMode1, QprcPcMode2, and QprcPcMode3.
en_result_t Qprc_ConfigRcMode (volatile FM_QPRC_TypeDef * pstcQprc, en_qprc_rcmode_t enMode)
Set Revolution Counter mode.
Parameters:
[in] pstcQprc Pointer to QPRC instance
[in] enMode Revolution Counter mode
Return values:
Ok Revolution Counter mode has been setup
ErrorInvalidParameter If one of following confitions are met:
pstcQprc == NULL
enMode > QprcRcMode3
Other invalid configuration
Definition at line 1052 of file qprc.c.
References QprcRcMode0, QprcRcMode1, QprcRcMode2, and QprcRcMode3.
en_result_t Qprc_DeInit (volatile FM_QPRC_TypeDef * pstcQprc, boolean_t bTouchNvic)
De-Initialize QPRC.
This function clears an QPRC instance.
Parameters:
[in] pstcQprc Pointer to QPRC instance
[in] bTouchNvic Touch NVIC or not
Return values:
Ok QPRC instance cleared
ErrorInvalidParameter If one of following conditions are met:
pstcQprc == NULL
Definition at line 679 of file qprc.c.
References QprcDeInitNvic(), QprcGetNoisFilterPtr(), and stc_qprc_nfn_t.
en_result_t Qprc_DisableIrq (volatile FM_QPRC_TypeDef * pstcQprc, en_qprc_irq_sel_t enIrqSel)
Disable QPRC interrupt.
Parameters:
[in] pstcQprc Pointer to QPRC instance
[in] enIrqSel Interrupt type
Return values:
Ok PC match interrupt enable bit has been setup
ErrorInvalidParameter If one of following conditions are met:
pstcQprc invalid
Other invalid configuration
Definition at line 1162 of file qprc.c.
References QprcPcCountInvertIrq, QprcPcMatchIrq, QprcPcMatchRcMatchIrq, QprcPcOfUfZeroIrq, QprcPcRcMatchIrq, and QprcRcOutrangeIrq.
en_result_t Qprc_EnableIrq (volatile FM_QPRC_TypeDef * pstcQprc, en_qprc_irq_sel_t enIrqSel)
Enable QPRC interrupt.
Parameters:
[in] pstcQprc Pointer to QPRC instance
[in] enIrqSel Interrupt type
Return values:
Ok QPRC interrupts has been enabled
ErrorInvalidParameter If one of following conditions are met:
pstcQprc invalid
Other invalid configuration
Definition at line 1110 of file qprc.c.
References QprcPcCountInvertIrq, QprcPcMatchIrq, QprcPcMatchRcMatchIrq, QprcPcOfUfZeroIrq, QprcPcRcMatchIrq, and QprcRcOutrangeIrq.
en_irq_flag_t Qprc_GetIrqFlag (volatile FM_QPRC_TypeDef * pstcQprc, en_qprc_irq_sel_t enIrqSel)
Get interrupt flag of QPRC.
Parameters:
[in] pstcQprc Pointer to QPRC instance
[in] enIrqSel Interrupt type
Return values:
PdlClr Interrupt doesn't occur selected by enIntType
PdlSet Interrupt occurs selected by enIntType
Definition at line 1214 of file qprc.c.
References PdlClr, PdlSet, QprcPcCountInvertIrq, QprcPcMatchIrq, QprcPcMatchRcMatchIrq, QprcPcOfUfZeroIrq, QprcPcRcMatchIrq, and QprcRcOutrangeIrq.
uint16_t Qprc_GetPcCompareValue (volatile FM_QPRC_TypeDef * pstcQprc)
Get compare value of Position counter.
Parameters:
[in] pstcQprc Pointer to QPRC instance
Return values:
Count value
Definition at line 925 of file qprc.c.
uint16_t Qprc_GetPcCount (volatile FM_QPRC_TypeDef * pstcQprc)
Get count value of Position counter.
Parameters:
[in] pstcQprc Pointer to QPRC instance
Return values:
Count value
Note:
If pstcQprc = NULL, the return value will be 0xFFFF.
Definition at line 797 of file qprc.c.
en_stat_flag_t Qprc_GetPcDir (volatile FM_QPRC_TypeDef * pstcQprc)
Get last position counter direction.
Parameters:
[in] pstcQprc Pointer to QPRC instance
Return values:
PdlClr The position counter was incremented.
PdlSet The position counter was decremented.
Definition at line 1362 of file qprc.c.
References PdlClr, and PdlSet.
uint16_t Qprc_GetPcMaxValue (volatile FM_QPRC_TypeDef * pstcQprc)
Get maximum count value of Position Counter.
Parameters:
[in] pstcQprc Pointer to QPRC instance
Return values:
PcMaxValue
Note:
If pstcQprc = NULL, the return value will be 0xFFFF.
Definition at line 882 of file qprc.c.
en_stat_flag_t Qprc_GetPcOfUfDir (volatile FM_QPRC_TypeDef * pstcQprc)
Get last position counter flow direction.
Parameters:
[in] pstcQprc Pointer to QPRC instance
Return values:
PdlClr The position counter was incremented.
PdlSet The position counter was decremented.
Definition at line 1340 of file qprc.c.
References PdlClr, and PdlSet.
uint16_t Qprc_GetPcRcCompareValue (volatile FM_QPRC_TypeDef * pstcQprc)
Get compare value of Position and Revolution Counter.
Parameters:
[in] pstcQprc Pointer to QPRC instance
Return values:
Count value
If pstcQprc = NULL, the return will be 0xFFFF.
Definition at line 973 of file qprc.c.
uint16_t Qprc_GetRcCount (volatile FM_QPRC_TypeDef * pstcQprc)
Get count value of Revolution Counter.
Parameters:
[in] pstcQprc Pointer to QPRC instance
Return values:
Count value
Note:
If pstcQprc = NULL, the return value will be 0xFFFF.
Definition at line 840 of file qprc.c.
en_result_t Qprc_Init (volatile FM_QPRC_TypeDef * pstcQprc, stc_qprc_config_t * pstcConfig)
Initialize QPRC.
This function initializes an QPRC module and sets up the internal data structures
Parameters:
[in] pstcQprc Pointer to QPRC instance
[in] pstcConfig Pointer to QPRC module configuration
Return values:
Ok Internal data has been setup
ErrorInvalidParameter If one of following conditions are met:
pstcQprc == NULL
pstcConfig == NULL
Other invalid configuration
Definition at line 367 of file qprc.c.
References stc_qprc_config::b8KValue, stc_qprc_filter::bInputInvert, stc_qprc_filter::bInputMask, stc_qprc_config::bPhaseEdge, stc_qprc_irq_en::bQprcPcCountInvertIrq, stc_qprc_irq_en::bQprcPcMatchIrq, stc_qprc_irq_en::bQprcPcMatchRcMatchIrq, stc_qprc_irq_en::bQprcPcOfUfZeroIrq, stc_qprc_irq_en::bQprcPcRcMatchIrq, stc_qprc_irq_en::bQprcRcOutrangeIrq, stc_qprc_config::bSwapAinBin, stc_qprc_config::bTouchNvic, stc_qprc_config::enAinEdge, stc_qprc_config::enBinEdge, stc_qprc_config::enCompareMode, stc_qprc_config::enPcResetMask, stc_qprc_filter::enWidth, stc_qprc_config::enZinEdge, stc_qprc_irq_cb::pfnPcCountInvertIrqCb, stc_qprc_irq_cb::pfnPcMatchIrqCb, stc_qprc_irq_cb::pfnPcMatchRcMatchIrqCb, stc_qprc_irq_cb::pfnPcOfUfZeroIrqCb, stc_qprc_irq_cb::pfnPcRcMatchIrqCb, stc_qprc_irq_cb::pfnRcOutrangeIrqCb, stc_qprc_config::pstcIrqCb, stc_qprc_config::pstcIrqEn, QprcBinBothEdges, QprcBinDisable, QprcBinFallingEdge, QprcBinRisingEdge, QprcCompareWithPosition, QprcCompareWithRevolution, QprcFilterWidth128Pclk, QprcFilterWidth16Pclk, QprcFilterWidth256Pclk, QprcFilterWidth32Pclk, QprcFilterWidth4Pclk, QprcFilterWidth64Pclk, QprcFilterWidth8Pclk, QprcGetInternDataPtr(), QprcGetNoisFilterPtr(), QprcInitNvic(), QprcNoFilter, QprcResetMask2Times, QprcResetMask4Times, QprcResetMask8Times, QprcResetMaskDisable, QprcZinBothEdges, QprcZinDisable, QprcZinFallingEdge, QprcZinHighLevel, QprcZinLowLevel, QprcZinRisingEdge, stc_qprc_nfn_t, stc_qprc_config::stcAinFilter, stc_qprc_config::stcBinFilter, and stc_qprc_config::stcCinFilter.
void Qprc_IrqHandler (volatile FM_QPRC_TypeDef * pstcQprc, stc_qprc_intern_data_t * pstcQprcInternData)
QPRC instance interrupt service routine.
Parameters:
[in] pstcQprc Pointer to QPRC instance
[in] pstcQprcInternData Pointer to internal data
Definition at line 265 of file qprc.c.
References PdlClr, PdlSet, stc_qprc_irq_cb::pfnPcCountInvertIrqCb, stc_qprc_irq_cb::pfnPcMatchIrqCb, stc_qprc_irq_cb::pfnPcMatchRcMatchIrqCb, stc_qprc_irq_cb::pfnPcOfUfZeroIrqCb, stc_qprc_irq_cb::pfnPcRcMatchIrqCb, stc_qprc_irq_cb::pfnRcOutrangeIrqCb, QPRC_PC_OVERFLOW_INT, QPRC_PC_UNDERFLOW_INT, and QPRC_PC_ZERO_INDEX_INT.
en_result_t Qprc_RestartPcCount (volatile FM_QPRC_TypeDef * pstcQprc)
Restart Position Counter from stop status.
Parameters:
[in] pstcQprc Pointer to QPRC instance
Return values:
Ok Restart Position Counter successfully
ErrorInvalidParameter pstcQprc == NULL
Definition at line 753 of file qprc.c.
en_result_t Qprc_SetPcCompareValue (volatile FM_QPRC_TypeDef * pstcQprc, uint16_t u16PcValue)
Set compare value of Position counter.
Parameters:
[in] pstcQprc Pointer to QPRC instance
[in] u16PcValue Compare value
Return values:
Ok Compare value has been setup
ErrorInvalidParameter pstcQprc == NULL
Definition at line 903 of file qprc.c.
en_result_t Qprc_SetPcCount (volatile FM_QPRC_TypeDef * pstcQprc, uint16_t u16PcValue)
Set count value of Position counter.
Parameters:
[in] pstcQprc Pointer to QPRC instance
[in] u16PcValue Count value
Return values:
Ok Count value has been setup
ErrorInvalidParameter pstcQprc == NULL
Definition at line 775 of file qprc.c.
en_result_t Qprc_SetPcMaxValue (volatile FM_QPRC_TypeDef * pstcQprc, uint16_t u16PcMaxValue)
Set maximum count value of Position Counter.
Parameters:
[in] pstcQprc Pointer to QPRC instance
[in] u16PcMaxValue Maximum count value
Return values:
Ok Maximum count value has been setup
ErrorInvalidParameter pstcQprc == NULL
Definition at line 860 of file qprc.c.
en_result_t Qprc_SetPcRcCompareValue (volatile FM_QPRC_TypeDef * pstcQprc, uint16_t u16PcRcValue)
Set compare value of Position and Revolution Counter.
Parameters:
[in] pstcQprc Pointer to QPRC instance
[in] u16PcRcValue Compare value
Return values:
Ok Compare value has been setup
ErrorInvalidParameter pstcQprc == NULL
Note:
the object with which this value is compared depends on the compare mode setting in the Qprc_Init(), plesae refer to the structure type en_qprc_compmode_t.
Definition at line 950 of file qprc.c.
en_result_t Qprc_SetRcCount (volatile FM_QPRC_TypeDef * pstcQprc, uint16_t u16RcValue)
Set count value of Revolution Counter.
Parameters:
[in] pstcQprc Pointer to QPRC instance
[in] u16RcValue Count value
Return values:
Ok Count value has been setup
ErrorInvalidParameter pstcQprc == NULL
Definition at line 817 of file qprc.c.
en_result_t Qprc_StopPcCount (volatile FM_QPRC_TypeDef * pstcQprc)
Stop Position Counter.
Parameters:
[in] pstcQprc Pointer to QPRC instance
Return values:
Ok Stop Position Counter counting successfully
ErrorInvalidParameter pstcQprc == NULL
Definition at line 732 of file qprc.c.
static void QprcDeInitNvic (volatile FM_QPRC_TypeDef * pstcQprc) [static]
Clear NVIC Interrupt depending on QPRC instance.
Parameters:
[in] pstcQprc Pointer to QPRC instance
Definition at line 227 of file qprc.c.
References PDL_DEFAULT_INTERRUPT_LEVEL.
Referenced by Qprc_DeInit().
static stc_qprc_intern_data_t * QprcGetInternDataPtr (volatile FM_QPRC_TypeDef * pstcQprc) [static]
Get the internal data for a certain QPRC instance.
Parameters:
[in] pstcQprc Pointer to QPRC instance
Returns:
Pointer to internal data
Definition at line 163 of file qprc.c.
References QPRC_INSTANCE_COUNT, and stc_qprc_instance_data::stcInternData.
Referenced by Qprc_Init().
static volatile FM_QPRC_NF_TypeDef * QprcGetNoisFilterPtr (volatile FM_QPRC_TypeDef * pstcQprc) [static]
Get the noise filter for a certain QPRC instance.
Parameters:
[in] pstcQprc Pointer to QPRC instance
Returns:
Pointer to the noise filter
Definition at line 138 of file qprc.c.
References stc_qprc_instance_data::pstcInstanceNf, QPRC_INSTANCE_COUNT, and stc_qprc_nfn_t.
Referenced by Qprc_DeInit(), and Qprc_Init().
static void QprcInitNvic (volatile FM_QPRC_TypeDef * pstcQprc) [static]
Set NVIC Interrupt depending on QPRC instance.
Parameters:
pstcQprc Pointer to QPRC instance
Definition at line 189 of file qprc.c.
Referenced by Qprc_Init().
Variable Documentation
stc_qprc_instance_data_t m_astcQprcInstanceDataLut[(PDL_PERIPHERAL_ENABLE_QPRC0==PDL_ON?1u:0u)+(PDL_PERIPHERAL_ENABLE_QPRC1==PDL_ON?1u:0u)+(PDL_PERIPHERAL_ENABLE_QPRC2==PDL_ON?1u:0u)+(PDL_PERIPHERAL_ENABLE_QPRC3==PDL_ON?1u:0u)]
Look-up table for all enabled ADC instances and their internal data.
Look-up table for all enabled MFS instances and their internal data.
Definition at line 96 of file qprc.c.
stc_qprc_instance_data_t m_astcQprcInstanceDataLut[(PDL_PERIPHERAL_ENABLE_QPRC0==PDL_ON?1u:0u)+(PDL_PERIPHERAL_ENABLE_QPRC1==PDL_ON?1u:0u)+(PDL_PERIPHERAL_ENABLE_QPRC2==PDL_ON?1u:0u)+(PDL_PERIPHERAL_ENABLE_QPRC3==PDL_ON?1u:0u)]
Look-up table for all enabled MFS instances and their internal data.
Definition at line 96 of file qprc.c.