PDL for FM Family: Controller Area Network with Flexible Data-Rate (CANFD)
Controller Area Network with Flexible Data-Rate (CANFD)
Data Structures
struct stc_canfd_rx_buffer
struct stc_canfd_tx_buffer
struct stc_canfd_tx_event
CAN FD Tx event FIFO element.
struct stc_canfd_stdid_filter
struct stc_canfd_extid_filter
struct stc_canfd_rx_confirmation
struct stc_canfd_intern_data
CAN FD instance internal data, storing internal information for each enabled CAN FD instance.
struct stc_canfd_instance_data
CAN FD instance data type.
struct stc_canfd_msg_id
CAN message identifier.
struct stc_canfd_msg_data
CAN message data.
struct stc_canfd_msg
CAN message.
struct stc_canfd_interrupt_handling
CAN FD interrupt pointer structure.
struct stc_canfd_notification
CAN FD notification pointer structure.
struct stc_canfd_config
CAN FD configuration.
Defines
#define CANFD_INSTANCE_COUNT (uint32_t)(sizeof(m_astcCanfdInstanceDataLut) / sizeof(m_astcCanfdInstanceDataLut[0]))
Macro to return the number of enabled CAN FD instances.
#define CANFD_MSGRAM_OFFSET (0x00008000UL)
Controller dependent constants.
#define CANFD_MSGRAM_SIZEB (16384)
#define CANFD_MSGRAM_SIZEW (CANFD_MSGRAM_SIZEB >> 2)
#define CANFD_TX_NOT_REQUESTED (0x00U)
Tx buffer transmission requested marks.
#define CANFD_TX_REQUESTED (0x96U)
#define CANFD_IR_MASK_ERROR
Bit masks for IR register.
#define CANFD_IR_MASK_STATUS (0x03800000UL)
#define CANFD_IR_MASK_RXBUF (0x00080000UL)
#define CANFD_IR_MASK_RXFIFO0 (0x00000001UL)
#define CANFD_IR_MASK_RXFIFO1 (0x00000010UL)
#define CANFD_IR_MASK_RX (CANFD_IR_MASK_RXBUF | CANFD_IR_MASK_RXFIFO0 | CANFD_IR_MASK_RXFIFO1)
#define CANFD_IR_MASK_TX (0x00000200UL)
#define CANFD_RXBUF_INFOSIZE (2)
CAN FD Rx buffer and FIFO element.
#define CANFD_TXBUF_INFOSIZE (2)
CAN FD Tx buffer element.
#define CANFD_STDID_INFOSIZE (1)
CAN FD standard message ID filter element.
#define CANFD_EXTID_INFOSIZE (2)
CAN FD extended message ID filter element.
#define stc_canfdn_t FM_CANFD_TypeDef
#define CANFD0 (*((volatile stc_canfdn_t *)FM_CANFD0_BASE))
#define CANFD_MESSAGE_DATA_BUFFER_SIZE 64
Size of data bytes in a receive or transmit operation.
#define CANFD_MESSAGE_DATA_BUFFER_SIZEW (CANFD_MESSAGE_DATA_BUFFER_SIZE / 4)
Size of data word in a receive or transmit operation.
#define CANFD_MESSAGE_RXBUFFER_COUNT 64
Number of possible dedicated Rx buffer for receive.
#define CANFD_MESSAGE_RXFIFO_COUNT 32
Number of possible Rx FIFO for receive messages.
#define CANFD_MESSAGE_TXBUFFER_COUNT 32
Number of possible dedicated Tx buffer, Tx Queue and Tx FIFO for transmit messages.
#define CANFD_MSGIDX_MIN (0U)
The CAN FD driver uses definitions of the structure of registers on the CAN FD controller that were defined in the "REGISTER DEFINITION HEADER" for the target MCU.
#define CANFD_MSGIDX_MAX (63U)
#define CANFD_MSGIDX_FIFO0 (254U)
#define CANFD_MSGIDX_FIFO1 (255U)
#define CANFD_MAX_STDDLC (8)
#define CANFD_ERROR_STE (1UL << 31)
CAN FD error.
#define CANFD_ERROR_FOE (1UL << 30)
#define CANFD_ERROR_ACKE (1UL << 29)
#define CANFD_ERROR_BE (1UL << 28)
#define CANFD_ERROR_CRCE (1UL << 27)
#define CANFD_ERROR_WDI (1UL << 26)
#define CANFD_ERROR_ELO (1UL << 22)
#define CANFD_ERROR_BEU (1UL << 21)
#define CANFD_ERROR_BEC (1UL << 20)
#define CANFD_ERROR_TOO (1UL << 18)
#define CANFD_ERROR_MRAF (1UL << 17)
#define CANFD_ERROR_TEFL (1UL << 15)
#define CANFD_ERROR_RF1L (1UL << 7)
#define CANFD_ERROR_RF0L (1UL << 3)
Typedefs
typedef struct stc_canfd_rx_buffer stc_canfd_rx_buffer_t
typedef struct stc_canfd_tx_buffer stc_canfd_tx_buffer_t
typedef struct stc_canfd_tx_event stc_canfd_tx_event_t
CAN FD Tx event FIFO element.
typedef struct
stc_canfd_stdid_filter stc_canfd_stdid_filter_t
typedef struct
stc_canfd_extid_filter stc_canfd_extid_filter_t
typedef enum
en_canfd_confirmation_method en_canfd_confirmation_method_t
CAN FD internal data.
typedef struct
stc_canfd_rx_confirmation stc_canfd_rx_confirmation_t
typedef struct
stc_canfd_intern_data stc_canfd_intern_data_t
CAN FD instance internal data, storing internal information for each enabled CAN FD instance.
typedef struct
stc_canfd_instance_data stc_canfd_instance_data_t
CAN FD instance data type.
typedef enum en_canfd_rxfifo_number en_canfd_rxfifo_number_t
Rx FIFO ID.
typedef enum en_canfd_mode en_canfd_mode_t
CAN operation mode.
typedef enum en_canfd_clock en_canfd_clock_t
CAN FD operation clock frequency.
typedef struct stc_canfd_msg_id stc_canfd_msg_id_t
CAN message identifier.
typedef struct stc_canfd_msg_data stc_canfd_msg_data_t
CAN message data.
typedef enum en_canfd_status en_canfd_status_t
CAN FD module status.
typedef struct stc_canfd_msg stc_canfd_msg_t
CAN message.
typedef void(* canfd_tx_msg_func_ptr_t)(uint8_t u8MsgBuf)
Message transmission complete callback function (canfd_tx_msg_func_ptr_t).
typedef void(* canfd_rx_msg_func_ptr_t)(uint8_t u8MsgBuf, stc_canfd_msg_t *pstcRxMsg)
Message reception callback function (canfd_rx_msg_func_ptr_t).
typedef void(* canfd_status_chg_func_ptr_t)(en_canfd_status_t enCanfdStatus)
Status changed callback function (canfd_status_chg_func_ptr_t).
typedef void(* canfd_error_func_ptr_t)(uint32_t u32CanfdError)
Error callback function (canfd_error_func_ptr_t).
typedef struct
stc_canfd_interrupt_handling stc_canfd_interrupt_handling_t
CAN FD interrupt pointer structure.
typedef struct
stc_canfd_notification stc_canfd_notification_t
CAN FD notification pointer structure.
typedef struct stc_canfd_config stc_canfd_config_t
CAN FD configuration.
Enumerations
enum en_canfd_confirmation_method { CanfdConfirmPolling = 0, CanfdConfirmInterrupt = 1 }
CAN FD internal data.
enum en_canfd_rxfifo_number { CanfdRxFIFO0 = 0, CanfdRxFIFO1 = 1 }
Rx FIFO ID.
enum en_canfd_mode { CanfdModeClassic = 0, CanfdModeFDFixed = 1, CanfdModeFDFlex = 2 }
CAN operation mode.
enum en_canfd_clock { CanfdClock32MHz = 0, CanfdClock40MHz = 1 }
CAN FD operation clock frequency.
enum en_canfd_status { CanfdBusOff = 0, CanfdWarning = 1 }
CAN FD module status.
Functions
static stc_canfd_intern_data_t * CanfdGetInternDataPtr (volatile FM_CANFD_TypeDef *pstcCanfd)
Return the internal data for a certain CAN FD instance.
static void CanfdInitInterrupt (volatile FM_CANFD_TypeDef *pstcCanfd)
Set NVIC Interrupt depending on CAN FD instance.
static void CanfdDeInitInterrupt (volatile FM_CANFD_TypeDef *pstcCanfd)
Clear NVIC Interrupt depending on CAN FD instance.
static en_result_t CanfdCheckAndNotifyRxMsg (volatile FM_CANFD_TypeDef *pstcCanfd, en_canfd_confirmation_method_t enMethod, uint32_t *pu32Accepted)
Check and notify received messages.
static stc_canfd_stdid_filter_t * CanfdCalcStdIdFilterAddress (volatile FM_CANFD_TypeDef *pstcCanfd, uint8_t u8Index)
Calculate address of the element of specified standard ID filter.
static stc_canfd_extid_filter_t * CanfdCalcExtIdFilterAddress (volatile FM_CANFD_TypeDef *pstcCanfd, uint8_t u8Index)
Calculate address of the element of specified extended ID filter.
static stc_canfd_rx_buffer_t * CanfdCalcRxBufferAddress (volatile FM_CANFD_TypeDef *pstcCanfd, uint8_t u8Index)
Calculate address of the element of specified dedicated Rx Buffer.
static en_result_t CanfdGetRxFIFO (volatile FM_CANFD_TypeDef *pstcCanfd, en_canfd_rxfifo_number_t enNumber, stc_canfd_rx_buffer_t *pstcRxBuffer)
Get one received message from specified Rx FIFO.
static en_result_t CanfdConvRxBuffer (stc_canfd_rx_buffer_t *pstcRxBuffer, stc_canfd_msg_t *pstcRxMsg)
Convert MCAN Rx buffer to driver message.
static stc_canfd_tx_buffer_t * CanfdCalcTxBufferAddress (volatile FM_CANFD_TypeDef *pstcCanfd, uint8_t u8Index)
Calculate address of the element of specified Tx Buffer.
static en_result_t CanfdClearTxRequestMarker (volatile FM_CANFD_TypeDef *pstcCanfd)
Clear transmission request marker.
void CanfdIrqHandler (volatile FM_CANFD_TypeDef *pstcCanfd)
CAN FD (Status/Error/Rx/Tx) interrupt ISR.
en_result_t Canfd_Init (volatile FM_CANFD_TypeDef *pstcCanfd, const stc_canfd_config_t *pstcConfig)
Initializes the CAN FD module.
en_result_t Canfd_DeInit (volatile FM_CANFD_TypeDef *pstcCanfd)
Deinitializes the CAN FD module. Any pending transmission or receiption will be aborted and all CAN FD related registers are reset to their default values.
en_result_t Canfd_Start (volatile FM_CANFD_TypeDef *pstcCanfd)
Start communication. Start (enable) CAN communication.
en_result_t Canfd_Stop (volatile FM_CANFD_TypeDef *pstcCanfd)
Stop communication. Stop (disable) CAN communication. Any pending transmission or receiption will be aborted and all CAN FD statuses are reset (cleared).
en_result_t Canfd_Restart (volatile FM_CANFD_TypeDef *pstcCanfd)
Restart communication. Restart CAN communication. This funnction stops and starts communication. Any pending transmission or receiption will be aborted and all CAN FD statuses are reset (cleared) in the stop process.
en_result_t Canfd_TransmitMsg (volatile FM_CANFD_TypeDef *pstcCanfd, uint8_t u8MsgBuf, stc_canfd_msg_t *pstcMsg)
Configures a message buffer for transmission. Setting of new values is not possible if a transmission is pending.
en_result_t Canfd_ReceiveMsg (volatile FM_CANFD_TypeDef *pstcCanfd)
Get all received messages by polling. Check and notify all received messages by polling.
en_result_t Canfd_GetBusStatus (volatile FM_CANFD_TypeDef *pstcCanfd)
Get current bus status.
Variables
static stc_canfd_instance_data_t m_astcCanfdInstanceDataLut []
static const uint8_t u8BufSizeInWord []
static const uint8_t u8DlcInByte []
Detailed Description
Provided functions of CANFD module:
Canfd_Init() (Initialisation of CAN FD module)
Canfd_DeInit() (Reset of all CAN FD related register to default value)
Canfd_Start() (Start communication)
Canfd_Stop() (Stop communication)
Canfd_Restart() (Restart communication)
Canfd_TransmitMsg() (Request to send message)
Canfd_ReceiveMsg() (Receive message by polling)
Canfd_GetBusStatus() (Detect BusOff)
How to use the CAN FD module:
First, to initialize a CAN module, Canfd_Init() must be called. The callback functions are optional, but recommended, otherwise there is no report to the API in case of any reception, transmission, bus state and error event. Canfd_DeInit() has to be used if any of the settings from Canfd_Init() have to be changed (use Canfd_DeInit() and afterwards Canfd_Init()). Canfd_DeInit() is used to completely disable the CAN FD module. With Canfd_DeInit() all CAN FD related register values are reset to their default values. Also any pending or ongoing transmission or reception will be aborted. Each CAN FD module has dedicated message buffers for receiving and transmiting. The receiving buffer consists of dedicated Rx byffer, Rx FIFO0 and Rx FIFO1. In the same way, the transmission buffer consists of dedicated Tx buffer and Tx FIFO/QUEUE. Canfd_Start() is used to start communication via CAN FD, and Canfd_Stop() is used to stop communication. Canfd_Restart() is used to restart communication. Usually, it will be called to recovery from CAN FD error state. Canfd_ReceiveMsg() is used to receive CAN messages. Canfd_TransmitMsg() is used to transmit CAN messages. Canfd_GetBusStatus() is used to get the bus status. Received message, completion of message transmission, changing of bus status and occurring of errors are always notified by calling to corresponding callback functions. The application has to specify the callback function that needs to know, or the corresponding event is never notified.
Note:
The numbers of the message buffers used in this driver are shown as follows; dedicated Rx buffer : 1 element, indexed 0. Rx FIFO0 : 2 elements. Rx FIFO1 : not used. Tx buffer : 1 element, indexed 0. Tx FIFO/QUEUE : not used.
Define Documentation
#define CANFD0 (*((volatile stc_canfdn_t *)FM_CANFD0_BASE))
Definition at line 126 of file canfd.h.
#define CANFD_ERROR_ACKE (1UL << 29)
Definition at line 254 of file canfd.h.
#define CANFD_ERROR_BE (1UL << 28)
Definition at line 255 of file canfd.h.
#define CANFD_ERROR_BEC (1UL << 20)
Definition at line 260 of file canfd.h.
#define CANFD_ERROR_BEU (1UL << 21)
Definition at line 259 of file canfd.h.
#define CANFD_ERROR_CRCE (1UL << 27)
Definition at line 256 of file canfd.h.
#define CANFD_ERROR_ELO (1UL << 22)
Definition at line 258 of file canfd.h.
#define CANFD_ERROR_FOE (1UL << 30)
Definition at line 253 of file canfd.h.
#define CANFD_ERROR_MRAF (1UL << 17)
Definition at line 262 of file canfd.h.
#define CANFD_ERROR_RF0L (1UL << 3)
Definition at line 265 of file canfd.h.
#define CANFD_ERROR_RF1L (1UL << 7)
Definition at line 264 of file canfd.h.
#define CANFD_ERROR_STE (1UL << 31)
CAN FD error.
These error values are used to report any CAN FD related error to the API via the CAN FD error callback function. The parameter of this callback function is uint32_t type, and it includes all of detected error flags as shown below;
Definition at line 252 of file canfd.h.
#define CANFD_ERROR_TEFL (1UL << 15)
Definition at line 263 of file canfd.h.
#define CANFD_ERROR_TOO (1UL << 18)
Definition at line 261 of file canfd.h.
#define CANFD_ERROR_WDI (1UL << 26)
Definition at line 257 of file canfd.h.
#define CANFD_EXTID_INFOSIZE (2)
CAN FD extended message ID filter element.
This structure defines an extended ID filtering element placed on the message RAM.
Definition at line 226 of file canfd.c.
Referenced by CanfdCalcExtIdFilterAddress().
#define CANFD_INSTANCE_COUNT (uint32_t)(sizeof(m_astcCanfdInstanceDataLut) / sizeof(m_astcCanfdInstanceDataLut[0]))
Macro to return the number of enabled CAN FD instances.
Definition at line 70 of file canfd.c.
Referenced by CanfdGetInternDataPtr().
#define CANFD_IR_MASK_ERROR
Value:
(CANFD_ERROR_STE  | \
                                 CANFD_ERROR_FOE  | \
                                 CANFD_ERROR_ACKE | \
                                 CANFD_ERROR_BE   | \
                                 CANFD_ERROR_CRCE | \
                                 CANFD_ERROR_WDI  | \
                                 CANFD_ERROR_ELO  | \
                                 CANFD_ERROR_BEU  | \
                                 CANFD_ERROR_BEC  | \
                                 CANFD_ERROR_TOO  | \
                                 CANFD_ERROR_MRAF | \
                                 CANFD_ERROR_TEFL | \
                                 CANFD_ERROR_RF1L | \
                                 CANFD_ERROR_RF0L)
Bit masks for IR register.
Definition at line 85 of file canfd.c.
Referenced by Canfd_Start(), and CanfdIrqHandler().
#define CANFD_IR_MASK_RX (CANFD_IR_MASK_RXBUF | CANFD_IR_MASK_RXFIFO0 | CANFD_IR_MASK_RXFIFO1)
Definition at line 104 of file canfd.c.
Referenced by CanfdIrqHandler().
#define CANFD_IR_MASK_RXBUF (0x00080000UL)
Definition at line 100 of file canfd.c.
Referenced by Canfd_Start(), and CanfdCheckAndNotifyRxMsg().
#define CANFD_IR_MASK_RXFIFO0 (0x00000001UL)
Definition at line 101 of file canfd.c.
Referenced by Canfd_Start(), and CanfdCheckAndNotifyRxMsg().
#define CANFD_IR_MASK_RXFIFO1 (0x00000010UL)
Definition at line 102 of file canfd.c.
Referenced by Canfd_Start(), and CanfdCheckAndNotifyRxMsg().
#define CANFD_IR_MASK_STATUS (0x03800000UL)
Definition at line 99 of file canfd.c.
Referenced by Canfd_GetBusStatus(), Canfd_Start(), and CanfdIrqHandler().
#define CANFD_IR_MASK_TX (0x00000200UL)
Definition at line 105 of file canfd.c.
Referenced by Canfd_Start(), and CanfdIrqHandler().
#define CANFD_MAX_STDDLC (8)
Definition at line 169 of file canfd.h.
Referenced by Canfd_TransmitMsg(), and CanfdConvRxBuffer().
#define CANFD_MESSAGE_DATA_BUFFER_SIZE 64
Size of data bytes in a receive or transmit operation.
Definition at line 129 of file canfd.h.
#define CANFD_MESSAGE_DATA_BUFFER_SIZEW (CANFD_MESSAGE_DATA_BUFFER_SIZE / 4)
Size of data word in a receive or transmit operation.
Definition at line 131 of file canfd.h.
#define CANFD_MESSAGE_RXBUFFER_COUNT 64
Number of possible dedicated Rx buffer for receive.
Definition at line 134 of file canfd.h.
#define CANFD_MESSAGE_RXFIFO_COUNT 32
Number of possible Rx FIFO for receive messages.
Definition at line 137 of file canfd.h.
#define CANFD_MESSAGE_TXBUFFER_COUNT 32
Number of possible dedicated Tx buffer, Tx Queue and Tx FIFO for transmit messages.
Definition at line 140 of file canfd.h.
Referenced by Canfd_TransmitMsg(), CanfdClearTxRequestMarker(), and CanfdIrqHandler().
#define CANFD_MSGIDX_FIFO0 (254U)
Definition at line 166 of file canfd.h.
Referenced by CanfdCheckAndNotifyRxMsg().
#define CANFD_MSGIDX_FIFO1 (255U)
Definition at line 167 of file canfd.h.
Referenced by CanfdCheckAndNotifyRxMsg().
#define CANFD_MSGIDX_MAX (63U)
Definition at line 165 of file canfd.h.
#define CANFD_MSGIDX_MIN (0U)
The CAN FD driver uses definitions of the structure of registers on the CAN FD controller that were defined in the "REGISTER DEFINITION HEADER" for the target MCU.
CAN FD Unit configuration structures
CAN FD received message index.
These are used to specify CAN operation mode.
Definition at line 164 of file canfd.h.
#define CANFD_MSGRAM_OFFSET (0x00008000UL)
Controller dependent constants.
Message RAM
Definition at line 75 of file canfd.c.
Referenced by Canfd_Init(), CanfdCalcExtIdFilterAddress(), CanfdCalcRxBufferAddress(), CanfdCalcStdIdFilterAddress(), CanfdCalcTxBufferAddress(), and CanfdGetRxFIFO().
#define CANFD_MSGRAM_SIZEB (16384)
Definition at line 76 of file canfd.c.
#define CANFD_MSGRAM_SIZEW (CANFD_MSGRAM_SIZEB >> 2)
Definition at line 77 of file canfd.c.
Referenced by Canfd_Init().
#define CANFD_RXBUF_INFOSIZE (2)
CAN FD Rx buffer and FIFO element.
This structure defines a dedicated Rx buffer and Rx FIFO element placed on the message RAM.
Definition at line 122 of file canfd.c.
Referenced by CanfdCalcRxBufferAddress(), and CanfdGetRxFIFO().
#define CANFD_STDID_INFOSIZE (1)
CAN FD standard message ID filter element.
This structure defines a standard ID filtering element placed on the message RAM.
Definition at line 204 of file canfd.c.
Referenced by CanfdCalcStdIdFilterAddress().
#define CANFD_TX_NOT_REQUESTED (0x00U)
Tx buffer transmission requested marks.
Definition at line 80 of file canfd.c.
Referenced by CanfdClearTxRequestMarker(), and CanfdIrqHandler().
#define CANFD_TX_REQUESTED (0x96U)
Definition at line 81 of file canfd.c.
Referenced by Canfd_TransmitMsg(), and CanfdIrqHandler().
#define CANFD_TXBUF_INFOSIZE (2)
CAN FD Tx buffer element.
This structure defines a dedicated Tx buffer, queue and FIFO element placed on the message RAM.
Definition at line 151 of file canfd.c.
Referenced by CanfdCalcTxBufferAddress().
#define stc_canfdn_t FM_CANFD_TypeDef
Definition at line 125 of file canfd.h.
Typedef Documentation
typedef void(* canfd_error_func_ptr_t)(uint32_t u32CanfdError)
Error callback function (canfd_error_func_ptr_t).
Any error will be reported to the API
Definition at line 319 of file canfd.h.
typedef void(* canfd_rx_msg_func_ptr_t)(uint8_t u8MsgBuf, stc_canfd_msg_t *pstcRxMsg)
Message reception callback function (canfd_rx_msg_func_ptr_t).
Signals that CAN has received a new message.
Definition at line 300 of file canfd.h.
typedef void(* canfd_status_chg_func_ptr_t)(en_canfd_status_t enCanfdStatus)
Status changed callback function (canfd_status_chg_func_ptr_t).
Any status change will be reported to the API (see en_canfd_status_t for possible status change codes).
Definition at line 310 of file canfd.h.
typedef void(* canfd_tx_msg_func_ptr_t)(uint8_t u8MsgBuf)
Message transmission complete callback function (canfd_tx_msg_func_ptr_t).
Signals a successful completed transmission.
Definition at line 291 of file canfd.h.
typedef enum en_canfd_clock en_canfd_clock_t
CAN FD operation clock frequency.
These are used to determin clock frequency of CAN FD controller.
typedef enum en_canfd_confirmation_method en_canfd_confirmation_method_t
CAN FD internal data.
This structure defines an extended ID filtering element placed on the message RAM.
typedef enum en_canfd_mode en_canfd_mode_t
CAN operation mode.
These are used to specify CAN operation mode.
typedef enum en_canfd_rxfifo_number en_canfd_rxfifo_number_t
Rx FIFO ID.
typedef enum en_canfd_status en_canfd_status_t
CAN FD module status.
These state values represent the current CAN FD module state, and are used in the CAN FD status changed callback function (canfd_status_chg_func_ptr_t).
typedef struct stc_canfd_config stc_canfd_config_t
CAN FD configuration.
Is used to set the CAN operation mode and CAN FD clock frequency. Optionally reception, transmission, error and status notification callback functions can be set.
typedef struct stc_canfd_extid_filter stc_canfd_extid_filter_t
typedef struct stc_canfd_instance_data stc_canfd_instance_data_t
CAN FD instance data type.
typedef struct stc_canfd_intern_data stc_canfd_intern_data_t
CAN FD instance internal data, storing internal information for each enabled CAN FD instance.
typedef struct stc_canfd_interrupt_handling stc_canfd_interrupt_handling_t
CAN FD interrupt pointer structure.
Holds some pointers that point to callback functions for message reception and transmission.
typedef struct stc_canfd_msg_data stc_canfd_msg_data_t
CAN message data.
Data structure for transmit and receive operations, maximum value for parameter u8DataLengthCode is CANFD_MESSAGE_DATA_BUFFER_SIZE.
typedef struct stc_canfd_msg_id stc_canfd_msg_id_t
CAN message identifier.
This structure is used to set the CAN message identifier for transmit and receive operations.
typedef struct stc_canfd_msg stc_canfd_msg_t
CAN message.
This structure stores a CAN or CAN FD message, including the identifier, data and data length code (DLC). It also contains an overflow and new flag which indicates the message state for received messages.
typedef struct stc_canfd_notification stc_canfd_notification_t
CAN FD notification pointer structure.
Holds some pointers to callback functions for status and error notification
typedef struct stc_canfd_rx_buffer stc_canfd_rx_buffer_t
typedef struct stc_canfd_rx_confirmation stc_canfd_rx_confirmation_t
typedef struct stc_canfd_stdid_filter stc_canfd_stdid_filter_t
typedef struct stc_canfd_tx_buffer stc_canfd_tx_buffer_t
typedef struct stc_canfd_tx_event stc_canfd_tx_event_t
CAN FD Tx event FIFO element.
This structure defines a dedicated Tx event FIFO element placed on the message RAM.
Enumeration Type Documentation
enum en_canfd_clock
CAN FD operation clock frequency.
These are used to determin clock frequency of CAN FD controller.
Enumerator:
CanfdClock32MHz
CanfdClock40MHz
Definition at line 190 of file canfd.h.
enum en_canfd_confirmation_method
CAN FD internal data.
This structure defines an extended ID filtering element placed on the message RAM.
Enumerator:
CanfdConfirmPolling
CanfdConfirmInterrupt
Definition at line 250 of file canfd.c.
enum en_canfd_mode
CAN operation mode.
These are used to specify CAN operation mode.
Enumerator:
CanfdModeClassic
CanfdModeFDFixed
CanfdModeFDFlex
Definition at line 177 of file canfd.h.
enum en_canfd_rxfifo_number
Rx FIFO ID.
Enumerator:
CanfdRxFIFO0
CanfdRxFIFO1
Definition at line 290 of file canfd.c.
enum en_canfd_status
CAN FD module status.
These state values represent the current CAN FD module state, and are used in the CAN FD status changed callback function (canfd_status_chg_func_ptr_t).
Enumerator:
CanfdBusOff
CanfdWarning
Definition at line 236 of file canfd.h.
Function Documentation
en_result_t Canfd_DeInit (volatile FM_CANFD_TypeDef * pstcCanfd)
Deinitializes the CAN FD module. Any pending transmission or receiption will be aborted and all CAN FD related registers are reset to their default values.
Parameters:
[in] pstcCanfd Pointer to register area of a CAN FD unit.
Return values:
Ok CAN FD module has been successfully deinitialized.
ErrorInvalidParameter If one of the following conditions are met:
pstcCanfd == NULL
pstcCanfdInternData == NULL (invalid or disabled CAN FD unit (PDL_PERIPHERAL_ENABLE_CANFD))
Definition at line 892 of file canfd.c.
References CanfdClearTxRequestMarker(), CanfdDeInitInterrupt(), CanfdGetInternDataPtr(), PDL_OFF, PDL_ON, stc_canfd_notification::pfnCanfdErrorInterruptFunction, stc_canfd_interrupt_handling::pfnCanfdRxInterruptFunction, stc_canfd_notification::pfnCanfdStatusInterruptFunction, stc_canfd_interrupt_handling::pfnCanfdTxInterruptFunction, stc_canfd_intern_data::stcCanfdInterruptHandling, and stc_canfd_intern_data::stcCanfdNotificationCb.
en_result_t Canfd_GetBusStatus (volatile FM_CANFD_TypeDef * pstcCanfd)
Get current bus status.
Calculate the top of address of standard ID filter element that is corresponding to specified index.
Parameters:
[in] pstcCanfd Pointer to register area of a CAN FD unit.
Return values:
Ok Process succeeded.
ErrorInvalidParameter If one of the following conditions are met:
pstcCanfd == NULL
pstcCanfdInternData == NULL
Definition at line 1317 of file canfd.c.
References CANFD_IR_MASK_STATUS, CanfdBusOff, CanfdGetInternDataPtr(), CanfdWarning, PDL_ON, stc_canfd_notification::pfnCanfdStatusInterruptFunction, and stc_canfd_intern_data::stcCanfdNotificationCb.
Referenced by CanfdIrqHandler().
en_result_t Canfd_Init (volatile FM_CANFD_TypeDef * pstcCanfd, const stc_canfd_config_t * pstcConfig)
Initializes the CAN FD module.
This function initializes one specific CAN FD module with the parameters provided in the given config structure. After initialization the CAN FD module has Error, Status and Module-Interrupt enabled and is ready to use.
Canfd_Init() has to be called with the parameter pstcConfig of type stc_canfd_config_t the basic CAN settings the CAN operation mode, the CAN baudrate, and the error and status change callback function can be set.
All values in pstcConfig have to be in valid range (see can.h for allowed ranges of dedicated parameters). The error and status change callback functions can be NULL. In this case no information of error or status changes will be reported to the API.
To reset and disable the CAN FD module the function Canfd_DeInit() has to be used.
Parameters:
[in] pstcCanfd Pointer to register area of a CAN FD unit.
[in] pstcConfig CAN FD configuration parameters.
Return values:
Ok CAN FD module has been successfully initialized.
ErrorInvalidParameter If one of the following conditions are met:
pstcCanfd == NULL
pstcConfig == NULL
pstcCanfdInternData == NULL (invalid or disabled CAN FD unit (PDL_PERIPHERAL_ENABLE_CANFD))
pstcConfig->enCanfdMode parameter out of range
pstcConfig->enCanfdClock parameter out of range
Definition at line 576 of file canfd.c.
References CANFD_MSGRAM_OFFSET, CANFD_MSGRAM_SIZEW, CanfdCalcStdIdFilterAddress(), CanfdClearTxRequestMarker(), CanfdClock32MHz, CanfdClock40MHz, CanfdConfirmInterrupt, CanfdConfirmPolling, CanfdGetInternDataPtr(), CanfdInitInterrupt(), CanfdModeClassic, CanfdModeFDFixed, CanfdModeFDFlex, stc_canfd_rx_confirmation::enBusStatus, stc_canfd_config::enCanfdClock, stc_canfd_intern_data::enCanfdMode, stc_canfd_config::enCanfdMode, stc_canfd_rx_confirmation::enErrorStatus, stc_canfd_rx_confirmation::enRxBuffer, stc_canfd_rx_confirmation::enRxFIFO0, stc_canfd_rx_confirmation::enRxFIFO1, stc_canfd_rx_confirmation::enTxBuffer, PDL_OFF, PDL_ON, stc_canfd_notification::pfnCanfdErrorInterruptFunction, stc_canfd_interrupt_handling::pfnCanfdRxInterruptFunction, stc_canfd_notification::pfnCanfdStatusInterruptFunction, stc_canfd_interrupt_handling::pfnCanfdTxInterruptFunction, stc_canfd_config::pfnErrorCallback, stc_canfd_config::pfnReceiveMsgCallback, stc_canfd_config::pfnStatusCallback, stc_canfd_config::pfnTransmitMsgCallback, stc_canfd_stdid_filter::sfec, stc_canfd_stdid_filter::sfid1, stc_canfd_stdid_filter::sfid2, stc_canfd_stdid_filter::sft, stc_canfd_intern_data::stcCanfdInterruptHandling, stc_canfd_intern_data::stcCanfdNotificationCb, stc_canfd_intern_data::stcCanfdRxConfirmation, and stc_canfd_stdid_filter::w.
en_result_t Canfd_ReceiveMsg (volatile FM_CANFD_TypeDef * pstcCanfd)
Get all received messages by polling. Check and notify all received messages by polling.
Parameters:
[in] pstcCanfd Pointer to register area of a CAN FD unit.
Return values:
Ok Message buffer for reception has been succesfully set.
ErrorInvalidParameter If one of the following conditions are met:
pstcCanfd == NULL
pstcCanfdInternData == NULL (invalid or disabled CAN FD unit (PDL_PERIPHERAL_ENABLE_CANFD))
Definition at line 1284 of file canfd.c.
References CanfdCheckAndNotifyRxMsg(), and CanfdConfirmPolling.
en_result_t Canfd_Restart (volatile FM_CANFD_TypeDef * pstcCanfd)
Restart communication. Restart CAN communication. This funnction stops and starts communication. Any pending transmission or receiption will be aborted and all CAN FD statuses are reset (cleared) in the stop process.
Parameters:
[in] pstcCanfd Pointer to register area of a CAN FD unit.
Return values:
Ok CAN FD module has been successfully restarted.
ErrorInvalidParameter If one of the following conditions are met:
pstcCanfd == NULL (Canfd_Stop)
pstcCanfdInternData == NULL (Canfd_Start)
Definition at line 1146 of file canfd.c.
References Canfd_Start(), Canfd_Stop(), and CanfdClearTxRequestMarker().
en_result_t Canfd_Start (volatile FM_CANFD_TypeDef * pstcCanfd)
Start communication. Start (enable) CAN communication.
Parameters:
[in] pstcCanfd Pointer to register area of a CAN FD unit.
Return values:
Ok CAN FD module has been successfully started.
ErrorInvalidParameter If one of the following conditions are met:
pstcCanfd == NULL
pstcCanfdInternData == NULL
Definition at line 1009 of file canfd.c.
References CANFD_IR_MASK_ERROR, CANFD_IR_MASK_RXBUF, CANFD_IR_MASK_RXFIFO0, CANFD_IR_MASK_RXFIFO1, CANFD_IR_MASK_STATUS, CANFD_IR_MASK_TX, CanfdConfirmInterrupt, CanfdGetInternDataPtr(), CanfdModeClassic, CanfdModeFDFixed, CanfdModeFDFlex, stc_canfd_rx_confirmation::enBusStatus, stc_canfd_intern_data::enCanfdMode, stc_canfd_rx_confirmation::enErrorStatus, stc_canfd_rx_confirmation::enRxBuffer, stc_canfd_rx_confirmation::enRxFIFO0, stc_canfd_rx_confirmation::enRxFIFO1, stc_canfd_rx_confirmation::enTxBuffer, PDL_OFF, PDL_ON, and stc_canfd_intern_data::stcCanfdRxConfirmation.
Referenced by Canfd_Restart().
en_result_t Canfd_Stop (volatile FM_CANFD_TypeDef * pstcCanfd)
Stop communication. Stop (disable) CAN communication. Any pending transmission or receiption will be aborted and all CAN FD statuses are reset (cleared).
Parameters:
[in] pstcCanfd Pointer to register area of a CAN FD unit.
Return values:
Ok CAN FD module has been successfully stopped.
ErrorInvalidParameter If following condition is met:
pstcCanfd == NULL
Definition at line 1095 of file canfd.c.
References PDL_OFF, and PDL_ON.
Referenced by Canfd_Restart().
en_result_t Canfd_TransmitMsg (volatile FM_CANFD_TypeDef * pstcCanfd, uint8_t u8MsgBuf, stc_canfd_msg_t * pstcMsg)
Configures a message buffer for transmission. Setting of new values is not possible if a transmission is pending.
Parameters:
[in] pstcCanfd Pointer to register area of a CAN FD unit.
[in] u8MsgBuf Message buffer index (0 .. CANFD_MESSAGE_TXBUFFER_COUNT - 1)
[in] pstcMsg CAN message to be transmitted.
Return values:
Ok Transmission request has been successfully accepted.
ErrorInvalidParameter If one of the following conditions are met:
pstcCanfd == NULL
u8MsgBuf out of range
pstcMsg == NULL
pstcCanfdInternData == NULL (invalid or disabled CAN FD unit (PDL_PERIPHERAL_ENABLE_CANFD))
ErrorOperationInProgress If following condition is met:
A transmission is pending.
Definition at line 1190 of file canfd.c.
References stc_canfd_msg_data::au32Data, stc_canfd_msg_id::bExtended, CANFD_MAX_STDDLC, CANFD_MESSAGE_TXBUFFER_COUNT, CANFD_TX_REQUESTED, CanfdCalcTxBufferAddress(), CanfdGetInternDataPtr(), CanfdModeClassic, stc_canfd_tx_buffer::data, stc_canfd_tx_buffer::dlc, stc_canfd_tx_buffer::efc, stc_canfd_intern_data::enCanfdMode, stc_canfd_tx_buffer::id, stc_canfd_tx_buffer::mm, stc_canfd_tx_buffer::rtr, stc_canfd_msg::stcData, stc_canfd_msg::stcIdentifier, stc_canfd_msg_id::u32Identifier, stc_canfd_msg_data::u8DataLengthCode, u8DlcInByte, stc_canfd_intern_data::u8TxReqMarker, and stc_canfd_tx_buffer::xtd.
static stc_canfd_extid_filter_t * CanfdCalcExtIdFilterAddress (volatile FM_CANFD_TypeDef * pstcCanfd, uint8_t u8Index) [static]
Calculate address of the element of specified extended ID filter.
Calculate the top of address of exended ID filter element that is corresponding to specified index.
Parameters:
[in] pstcCanfd Pointer to register area of a CAN FD unit.
[in] u8Index Extended ID filter index.
Return values:
NULL Invalid parameter(s).
not NULL Address of specified filter element
Definition at line 1592 of file canfd.c.
References CANFD_EXTID_INFOSIZE, and CANFD_MSGRAM_OFFSET.
static stc_canfd_rx_buffer_t * CanfdCalcRxBufferAddress (volatile FM_CANFD_TypeDef * pstcCanfd, uint8_t u8Index) [static]
Calculate address of the element of specified dedicated Rx Buffer.
Calculate the top of address of dedicated Rx buffer element that is corresponding to specified index.
Parameters:
[in] pstcCanfd Pointer to register area of a CAN FD unit.
[in] u8Index Rx buffer index.
Return values:
NULL Invalid parameter(s).
not NULL Address of specified Rx buffer element
Definition at line 1627 of file canfd.c.
References CANFD_MSGRAM_OFFSET, CANFD_RXBUF_INFOSIZE, and u8BufSizeInWord.
Referenced by CanfdCheckAndNotifyRxMsg().
static stc_canfd_stdid_filter_t * CanfdCalcStdIdFilterAddress (volatile FM_CANFD_TypeDef * pstcCanfd, uint8_t u8Index) [static]
Calculate address of the element of specified standard ID filter.
Calculate the top of address of standard ID filter element that is corresponding to specified index.
Parameters:
[in] pstcCanfd Pointer to register area of a CAN FD unit.
[in] u8Index Standard ID filter index.
Return values:
NULL Invalid parameter(s).
not NULL Address of specified filter element
Definition at line 1557 of file canfd.c.
References CANFD_MSGRAM_OFFSET, and CANFD_STDID_INFOSIZE.
Referenced by Canfd_Init().
static stc_canfd_tx_buffer_t * CanfdCalcTxBufferAddress (volatile FM_CANFD_TypeDef * pstcCanfd, uint8_t u8Index) [static]
Calculate address of the element of specified Tx Buffer.
Calculate the top of address of Tx buffer element that is corresponding to specified index.
Parameters:
[in] pstcCanfd Pointer to register area of a CAN FD unit.
[in] u8Index Tx buffer index.
Return values:
NULL Invalid parameter(s).
not NULL Address of specified Tx buffer element
Definition at line 1849 of file canfd.c.
References CANFD_MSGRAM_OFFSET, CANFD_TXBUF_INFOSIZE, and u8BufSizeInWord.
Referenced by Canfd_TransmitMsg().
static en_result_t CanfdCheckAndNotifyRxMsg (volatile FM_CANFD_TypeDef * pstcCanfd, en_canfd_confirmation_method_t enMethod, uint32_t * pu32Accepted) [static]
Check and notify received messages.
Check and notify received messages via Rx buffer, FIFO0 and FIFO1. The target is the object that its confirmation method is same as the parameter 'enMethod'. Note that the value of the parameter 'pstcCanfd' is not checked.
Parameters:
[in] pstcCanfd Pointer to register area of a CAN FD unit.
[in] enMethod Confirmation method.
[in] pu32Accepted Address to store flags that were accepted in this function.
Return values:
Ok Process was done successfully.
ErrorInvalidParameter If one of the following conditions are met:
pstcCanfdInternData == NULL
pu32Accepted == NULL
Definition at line 1398 of file canfd.c.
References CANFD_IR_MASK_RXBUF, CANFD_IR_MASK_RXFIFO0, CANFD_IR_MASK_RXFIFO1, CANFD_MSGIDX_FIFO0, CANFD_MSGIDX_FIFO1, CanfdCalcRxBufferAddress(), CanfdConvRxBuffer(), CanfdGetInternDataPtr(), CanfdGetRxFIFO(), CanfdRxFIFO0, CanfdRxFIFO1, stc_canfd_rx_confirmation::enRxBuffer, stc_canfd_rx_confirmation::enRxFIFO0, stc_canfd_rx_confirmation::enRxFIFO1, stc_canfd_interrupt_handling::pfnCanfdRxInterruptFunction, stc_canfd_intern_data::stcCanfdInterruptHandling, and stc_canfd_intern_data::stcCanfdRxConfirmation.
Referenced by Canfd_ReceiveMsg(), and CanfdIrqHandler().
static en_result_t CanfdClearTxRequestMarker (volatile FM_CANFD_TypeDef * pstcCanfd) [static]
Clear transmission request marker.
Clear transmission request marker of all Tx buffers. Transmission request marker holds in the MM field of Tx buffer.
Parameters:
[in] pstcCanfd Pointer to register area of a CAN FD unit.
Return values:
Ok Done process successfully.
ErrorInvalidParameter If one of the following conditions are met:
pstcCanfd == NULL
pstcCanfdInternData == NULL
Definition at line 1889 of file canfd.c.
References CANFD_MESSAGE_TXBUFFER_COUNT, CANFD_TX_NOT_REQUESTED, CanfdGetInternDataPtr(), and stc_canfd_intern_data::u8TxReqMarker.
Referenced by Canfd_DeInit(), Canfd_Init(), and Canfd_Restart().
static en_result_t CanfdConvRxBuffer (stc_canfd_rx_buffer_t * pstcRxBuffer, stc_canfd_msg_t * pstcRxMsg) [static]
Convert MCAN Rx buffer to driver message.
Convert contents of MCAN Rx buffer on the message RAM to the driver defined message structure.
Parameters:
[in] pstcRxBuffer Pointer to Rx buffer/FIFO element
[in] pstcRxMsg Pointer to message structure
Return values:
Ok Done conversion successfully.
ErrorInvalidParameter If one of the following conditions are met:
pstcRxBuffer == NULL
pstcRxMsg == NULL
Note: This function premises that the byte order is 'little endian'.
Definition at line 1771 of file canfd.c.
References stc_canfd_msg_data::au32Data, stc_canfd_msg_data::au8Data, stc_canfd_msg::bCanfd, stc_canfd_msg_id::bExtended, CANFD_MAX_STDDLC, stc_canfd_rx_buffer::data, stc_canfd_rx_buffer::dlc, stc_canfd_rx_buffer::edl, stc_canfd_rx_buffer::id, stc_canfd_msg::stcData, stc_canfd_msg::stcIdentifier, stc_canfd_msg_id::u32Identifier, stc_canfd_msg_data::u8DataLengthCode, u8DlcInByte, and stc_canfd_rx_buffer::xtd.
Referenced by CanfdCheckAndNotifyRxMsg().
static void CanfdDeInitInterrupt (volatile FM_CANFD_TypeDef * pstcCanfd) [static]
Clear NVIC Interrupt depending on CAN FD instance.
Parameters:
pstcCanfd Pointer to CAN FD instance
Definition at line 422 of file canfd.c.
References PDL_DEFAULT_INTERRUPT_LEVEL.
Referenced by Canfd_DeInit().
static stc_canfd_intern_data_t * CanfdGetInternDataPtr (volatile FM_CANFD_TypeDef * pstcCanfd) [static]
Return the internal data for a certain CAN FD instance.
Parameters:
pstcCanfd Pointer to CAN FD instance
Returns:
Pointer to internal data or NULL if instance is not enabled (or not known)
Definition at line 378 of file canfd.c.
References CANFD_INSTANCE_COUNT, and stc_canfd_instance_data::stcInternData.
Referenced by Canfd_DeInit(), Canfd_GetBusStatus(), Canfd_Init(), Canfd_Start(), Canfd_TransmitMsg(), CanfdCheckAndNotifyRxMsg(), CanfdClearTxRequestMarker(), and CanfdIrqHandler().
static en_result_t CanfdGetRxFIFO (volatile FM_CANFD_TypeDef * pstcCanfd, en_canfd_rxfifo_number_t enNumber, stc_canfd_rx_buffer_t * pstcRxBuffer) [static]
Get one received message from specified Rx FIFO.
Get one received message from specified Rx FIFO. The 'GetIndex' is updated by this process if it was done successfully.
Parameters:
[in] pstcCanfd Pointer to register area of a CAN FD unit.
[in] enNumber Rx FIFO number (FIFO0/1).
[in] pstcRxBuffer Address of Rx (FIFO) buffer element.
Return values:
Ok Get Rx FIFO message succesfully.
ErrorInvalidParameter If one of the following conditions are met:
pstcCanfdInternData == NULL
enNumber out of range
pstcRxBuffer == NULL
Error FIFO is not available or has no message.
Definition at line 1670 of file canfd.c.
References CANFD_MSGRAM_OFFSET, CANFD_RXBUF_INFOSIZE, CanfdRxFIFO0, CanfdRxFIFO1, stc_canfd_rx_buffer::data, PDL_OFF, u8BufSizeInWord, and stc_canfd_rx_buffer::w.
Referenced by CanfdCheckAndNotifyRxMsg().
static void CanfdInitInterrupt (volatile FM_CANFD_TypeDef * pstcCanfd) [static]
Set NVIC Interrupt depending on CAN FD instance.
Parameters:
pstcCanfd Pointer to CAN FD instance
Definition at line 408 of file canfd.c.
Referenced by Canfd_Init().
void CanfdIrqHandler (volatile FM_CANFD_TypeDef * pstcCanfd)
CAN FD (Status/Error/Rx/Tx) interrupt ISR.
Check for any pending interrupt source and process until no more INTs are active.
Parameters:
[in] pstcCanfd Pointer to register area of a CAN unit.
Definition at line 443 of file canfd.c.
References Canfd_GetBusStatus(), CANFD_IR_MASK_ERROR, CANFD_IR_MASK_RX, CANFD_IR_MASK_STATUS, CANFD_IR_MASK_TX, CANFD_MESSAGE_TXBUFFER_COUNT, CANFD_TX_NOT_REQUESTED, CANFD_TX_REQUESTED, CanfdCheckAndNotifyRxMsg(), CanfdConfirmInterrupt, CanfdGetInternDataPtr(), stc_canfd_rx_confirmation::enBusStatus, stc_canfd_rx_confirmation::enErrorStatus, stc_canfd_rx_confirmation::enTxBuffer, stc_canfd_notification::pfnCanfdErrorInterruptFunction, stc_canfd_notification::pfnCanfdStatusInterruptFunction, stc_canfd_interrupt_handling::pfnCanfdTxInterruptFunction, stc_canfd_intern_data::stcCanfdInterruptHandling, stc_canfd_intern_data::stcCanfdNotificationCb, stc_canfd_intern_data::stcCanfdRxConfirmation, and stc_canfd_intern_data::u8TxReqMarker.
Variable Documentation
stc_canfd_instance_data_t m_astcCanfdInstanceDataLut[] [static]
Initial value:
{
    {
        & (*((volatile  FM_CANFD_TypeDef  *)FM_CANFD0_BASE))
    },
}
Definition at line 319 of file canfd.c.
const uint8_t u8BufSizeInWord[] [static]
Initial value:
 {
    2,
    3,
    4,
    5,
    6,
    8,
    12,
    16
}
Definition at line 330 of file canfd.c.
Referenced by CanfdCalcRxBufferAddress(), CanfdCalcTxBufferAddress(), and CanfdGetRxFIFO().
const uint8_t u8DlcInByte[] [static]
Initial value:
 {
     0,
     1,
     2,
     3,
     4,
     5,
     6,
     7,
     8,
    12,
    16,
    20,
    24,
    32,
    48,
    64,
}
Definition at line 342 of file canfd.c.
Referenced by Canfd_TransmitMsg(), and CanfdConvRxBuffer().