PDL for FM Family: Waveform Generator (WFG)
Waveform Generator (WFG)
Data Structures
struct stc_wfg_config
struct stc_mft_wfg_intern_data
struct stc_wfg_nzcl_config
struct stc_mft_wfg_instance_data
Defines
#define stc_mftn_wfg_t FM_MFT_WFG_TypeDef
#define MFT0_WFG (*((volatile stc_mftn_wfg_t *) FM_MFT0_WFG_BASE))
#define MFT1_WFG (*((volatile stc_mftn_wfg_t *) FM_MFT1_WFG_BASE))
#define MFT2_WFG (*((volatile stc_mftn_wfg_t *) FM_MFT2_WFG_BASE))
#define MFT_WFG_CH0 0u
#define MFT_WFG_CH1 1u
#define MFT_WFG_CH2 2u
#define MFT_WFG_CH3 3u
#define MFT_WFG_CH4 4u
#define MFT_WFG_CH5 5u
#define MFT_WFG_CH10 0u
#define MFT_WFG_CH32 1u
#define MFT_WFG_CH54 2u
#define MFT_WFG_MAXCH 3u
#define WFG_INSTANCE_COUNT
Typedefs
typedef enum en_wfg_instance_index en_wfg_instance_index_t
Enumeration to define an index for each WFG instance.
typedef enum en_mft_wfg_mode en_mft_wfg_mode_t
typedef enum en_gten_bits en_gten_bits_t
typedef enum en_psel_bits en_psel_bits_t
typedef enum en_pgen_bits en_pgen_bits_t
typedef enum en_dmod_bits en_dmod_bits_t
typedef enum en_wfg_timer_clock en_wfg_timer_clock_t
typedef struct stc_wfg_config stc_wfg_config_t
typedef struct
stc_mft_wfg_intern_data stc_mft_wfg_intern_data_t
typedef enum en_nzcl_filter_width en_nzcl_filter_width_t
typedef struct stc_wfg_nzcl_config stc_wfg_nzcl_config_t
typedef struct
stc_mft_wfg_instance_data stc_mft_wfg_instance_data_t
Enumerations
enum en_wfg_instance_index { WfgInstanceIndexWfg0 = 0u, WfgInstanceIndexWfg1, WfgInstanceIndexWfg2 }
Enumeration to define an index for each WFG instance.
enum en_mft_wfg_mode {
WfgThroughMode = 0u, WfgRtPpgMode = 1u, WfgTimerPpgMode = 2u, WfgRtDeadTimerMode = 4u,
WfgRtDeadTimerFilterMode = 5u, WfgPpgDeadTimerFilterMode = 6u, WfgPpgDeadTimerMode = 7u
}
enum en_gten_bits { GtenBits00B = 0u, GtenBits01B = 1u, GtenBits10B = 2u, GtenBits11B = 3u }
enum en_psel_bits { PselBits00B = 0u, PselBits01B = 1u, PselBits10B = 2u, PselBits11B = 3u }
enum en_pgen_bits { PgenBits00B = 0u, PgenBits01B = 1u, PgenBits10B = 2u, PgenBits11B = 3u }
enum en_dmod_bits { DmodBits00B = 0u, DmodBits01B = 1u, DmodBits10B = 2u, DmodBits11B = 3u }
enum en_wfg_timer_clock {
WfgPlckDiv1 = 0u, WfgPlckDiv2 = 1u, WfgPlckDiv4 = 2u, WfgPlckDiv8 = 3u,
WfgPlckDiv16 = 4u, WfgPlckDiv32 = 5u, WfgPlckDiv64 = 6u, WfgPlckDiv128 = 7u
}
enum en_nzcl_filter_width {
NzlcNoFilter, NzlcWidth4Cycle, NzlcWidth8Cycle, NzlcWidth16Cycle,
NzlcWidth32Cycle, NzlcWidth64Cycle, NzlcWidth128Cycle, NzlcWidth256Cycle
}
Functions
static stc_mft_wfg_intern_data_t * MftGetInternDataPtr (volatile FM_MFT_WFG_TypeDef *pstcWfg)
Return the internal data for a certain WFG instance.
void Mft_Wfg_IrqHandler (volatile FM_MFT_WFG_TypeDef *pstcWfg, stc_mft_wfg_intern_data_t *pstcMftWfgInternData)
WFG interrupt handler sub function.
static void MftWfgInitNvic (volatile FM_MFT_WFG_TypeDef *pstcWfg)
Device dependent initialization of interrupts according CMSIS with level defined in pdl.h.
static void MftWfgDeInitNvic (volatile FM_MFT_WFG_TypeDef *pstcWfg)
Device dependent de-initialization of interrupts according CMSIS.
en_result_t Mft_Wfg_Init (volatile FM_MFT_WFG_TypeDef *pstcWfg, uint8_t u8CoupleCh, stc_wfg_config_t *pstcConfig)
Initialize a couple WFG channels.
en_result_t Mft_Wfg_DeInit (volatile FM_MFT_WFG_TypeDef *pstcWfg, uint8_t u8CoupleCh, boolean_t bTouchNvic)
De-Initialize a couple WFG channels.
en_result_t Mft_Wfg_StartTimer (volatile FM_MFT_WFG_TypeDef *pstcWfg, uint8_t u8CoupleCh)
Start WFG timer.
en_result_t Mft_Wfg_StopTimer (volatile FM_MFT_WFG_TypeDef *pstcWfg, uint8_t u8CoupleCh)
Stop WFG timer.
en_irq_flag_t Mft_Wfg_GetTimerIrqFlag (volatile FM_MFT_WFG_TypeDef *pstcWfg, uint8_t u8CoupleCh)
get WFG timer interrupt flag
en_result_t Mft_Wfg_ClrTimerIrqFlag (volatile FM_MFT_WFG_TypeDef *pstcWfg, uint8_t u8CoupleCh)
clear WFG timer interrupt flag
en_result_t Mft_Wfg_WriteTimerCountCycle (volatile FM_MFT_WFG_TypeDef *pstcWfg, uint8_t u8CoupleCh, uint16_t u16CycleA, uint16_t u16CycleB)
write timer count cycle
en_result_t Mft_Wfg_SetFilterCountValue (volatile FM_MFT_WFG_TypeDef *pstcWfg, uint8_t u8CoupleCh, uint16_t u16Count)
set cycle of WFG timer
en_result_t Mft_Wfg_Nzcl_Init (volatile FM_MFT_WFG_TypeDef *pstcWfg, stc_wfg_nzcl_config_t *pstcNzclConfig, boolean_t bTouchNvic)
Initialize NZCL of waveform generator.
en_result_t Mft_Wfg_Nzcl_DeInit (volatile FM_MFT_WFG_TypeDef *pstcWfg, boolean_t bTouchNvic)
De-Initialize NZCL of waveform generator.
en_result_t Mft_Wfg_Nzcl_SwTiggerDtif (volatile FM_MFT_WFG_TypeDef *pstcWfg)
set software trigger DTIF
en_irq_flag_t Mft_Wfg_Nzcl_GetDigitalFilterIrqFlag (volatile FM_MFT_WFG_TypeDef *pstcWfg)
get Digital filter interrupt flag
en_result_t Mft_Wfg_Nzcl_ClrDigitalFilterIrqFlag (volatile FM_MFT_WFG_TypeDef *pstcWfg)
clear Digital filter interrupt flag
en_irq_flag_t Mft_Wfg_Nzcl_GetAnalogFilterIrqFlag (volatile FM_MFT_WFG_TypeDef *pstcWfg)
get Analog Filter interrupt flag
en_result_t Mft_Wfg_Nzcl_ClrAnalogFilterIrqFlag (volatile FM_MFT_WFG_TypeDef *pstcWfg)
clear Analog Filter interrupt flag
en_result_t Mft_Wfg_NzclClrAnalogFilterIrqFlag (volatile FM_MFT_WFG_TypeDef *pstcWfg)
Variables
stc_mft_wfg_instance_data_t m_astcMftWfgInstanceDataLut [(PDL_PERIPHERAL_ENABLE_MFT0_WFG==PDL_ON?1u:0u)+(PDL_PERIPHERAL_ENABLE_MFT1_WFG==PDL_ON?1u:0u)+(PDL_PERIPHERAL_ENABLE_MFT2_WFG==PDL_ON?1u:0u)]
Look-up table for all enabled WFG instances and their internal data.
stc_mft_wfg_instance_data_t m_astcMftWfgInstanceDataLut [(PDL_PERIPHERAL_ENABLE_MFT0_WFG==PDL_ON?1u:0u)+(PDL_PERIPHERAL_ENABLE_MFT1_WFG==PDL_ON?1u:0u)+(PDL_PERIPHERAL_ENABLE_MFT2_WFG==PDL_ON?1u:0u)]
Look-up table for all enabled WFG instances and their internal data.
Detailed Description
Provided functions of WFG module:
Mft_Wfg_Init()
Mft_Wfg_DeInit()
Mft_Wfg_StartTimer()
Mft_Wfg_StopTimer()
Mft_Wfg_WriteTimerCountCycle()
Mft_Wfg_GetTimerIrqFlag()
Mft_Wfg_ClrTimerIrqFlag()
Mft_Wfg_WriteTimerCountCycle()
Mft_Wfg_Nzcl_Init()
Mft_Wfg_Nzcl_DeInit()
Mft_Wfg_Nzcl_SwTiggerDtif()
Mft_Wfg_Nzcl_GetDigitalFilterIrqFlag()
Mft_Wfg_Nzcl_ClrDigitalFilterIrqFlag()
Mft_Wfg_Nzcl_GetAnalogFilterIrqFlag()
Mft_Wfg_Nzcl_ClrAnalogFilterIrqFlag()
The WFG can be configured to following mode:
Through mode
RT-PPG mode
Timer-PPG mode
RT-dead timer mode
PPG-dead timer mode
how to operate WFG with Through mode (one of usages)?
Before using WFG, the FRT used to connect with applying OCU must be initialed first and OCU must be initialed then.
For how to configure FRT, see the description in the mft_frt.h
For how to configure OCU, see the description in the mft_ocu.h
Configure the WFG structure of the type stc_wfg_config_t:
enMode = Through mode
enGtenBits = b'00
enPselBits = b'00
enPgenBits = b'00
enDmodBit = b'0
Call Mft_Wfg_Init() with the structure configued.
Enable OCU operation and RT signal will output to RTO pin directly. Changing the value of control bits will influence RTO output.
how to operate WFG with RT-PPG mode (one of usages)?
Before using WFG, the FRT used to connect with applying OCU must be initialized first and OCU must be initialed then, PPG should be initialized at the following.
For how to configure FRT, see the description in the mft_frt.h
For how to configure OCU, see the description in the mft_ocu.h
For how to configure PPG, see the description in the ppg.h
Configure the WFG structure of the type stc_wfg_config_t:
enMode = RT-PPG mode
enGtenBits = b'00
enPselBits = b'00 (input PPG ch.0 to WFG0)
enPgenBits = b'11
enDmodBit = b'0
Call Mft_Wfg_Init() with the structure configued.
Start PPG0 and enable OCU operation.
In this case RTO0 will outputs the logic AND signal of RT0 signal and PPG0, RTO1 will outputs the logic AND signal of RT1 signal and PPG0. Changing the value of control bits (GTEN, PSEL, PGEN, DMOF) will influence RTO output.
how to operate WFG with Timer-PPG mode (one of usages)?
Before using WFG, the FRT used to connect with applying OCU must be initialized first and OCU must be initialed then, PPG and WFG timer should be initialized at the following.
For how to configure FRT, see the description in the mft_frt.h
For how to configure OCU, see the description in the mft_ocu.h
For how to configure PPG, see the description in the ppg.h
For how to initialize WFG timer, see the description at the following.
Configure the WFG structure of the type stc_wfg_config_t:
enGtenBits = b'00
enPselBits = b'00 (input PPG ch.0 to WFG10)
enPgenBits = b'11
enDmodBit = b'0
Configure WFG to Timer-PPG mode with Mft_Wfg_ConfigMode()
Start PPG0, enable OCU operation and start WFG timer.
In this case RTO0 will outputs the logic AND signal of WFG timer flag 0 and PPG0, RTO1 will outputs the logic AND signal of WFG timer flag 1 and PPG0. Changing the value of control bits will influence RTO output.
how to operate WFG with RT-dead timer mode (one of usages)?
Before using WFG, the FRT used to connect with applying OCU must be initialized first and OCU must be initialed then, WFG timer should be initialized at the following.
For how to configure FRT, see the description in the mft_frt.h
For how to configure OCU, see the description in the mft_ocu.h
For how to initialize WFG timer, see the description at the following.
Configure WFG to RT-dead timer mode with Mft_Wfg_ConfigMode()
Configure the WFG structure of the type stc_wfg_config_t:
enMode = RT-dead timer mode
enClk = xxx
enGtenBits = b'00
enPselBits = b'00
enPgenBits = b'00
enDmodBit = b'0
Call Mft_Wfg_Init() with the structure configued.
Enable OCU operation and start WFG timer.
In this case, RT(1) will trigger the WFG timer to start, WFG will output the generated non-overlap signal. Changing the value of control bits will influence RTO output.
how to operate WFG with PPG-dead timer mode (one of usages)?
Before using WFG, WFG timer should be initialized at the following. For how to initialize WFG timer, see the description at the following.
Configure WFG to PPG-dead timer mode with Mft_Wfg_ConfigMode()
Configure the WFG structure of the type stc_wfg_config_t:
enMode = PPG-dead timer mode
enClk = xxx
enGtenBits = b'00
enPselBits = b'00 (input PPG0 to WFG10)
enPgenBits = b'00
enDmodBit = b'0
Call Mft_Wfg_Init() with the structure configued.
Start WFG timer.
In this case, PPG0 will trigger the WFG timer to start, WFG will output the generated non-overlap singal. Changing the value of control bits will influence RTO output.
How to use the NZCL (used for motor emergency shutdown) ?
Mft_Wfg_Nzcl_Init() must be used for configuration of the WFG NZCL with a structure of the type stc_wfg_nzcl_config_t.
Both analog noise filter and digital noise filter can be used to filter the signal input from DTTIX pin.
Mft_Wfg_Nzcl_SwTiggerDtif() is used to trigger the DTIF interrupt by software, regardless of DTTIX pin input status.
With interrupt mode, when the interrupt occurs, it will run into user interrupt callback function set with the Mft_Wfg_Nzcl_Init().
With polling mode, user can use Mft_Wfg_Nzcl_GetDigitalFilterIrqFlag() to check if the interrupt of digital noise filter occurs, and clear the interrupt flag by Mft_Wfg_Nzcl_ClrDigitalFilterIrqFlag(). user can use Mft_Wfg_Nzcl_GetAnalogFilterIrqFlag() to check if the interrupt of analog noise filter occurs, and clear the interrupt flag by Mft_Wfg_Nzcl_ClrAnalogFilterIrqFlag().
When stopping the WFG NZCL, use Mft_Wfg_Nzcl_DeInit() to disable WFG NZCL operation as well as WFG NZCL interrupt.
Define Documentation
#define MFT0_WFG (*((volatile stc_mftn_wfg_t *) FM_MFT0_WFG_BASE))
Definition at line 256 of file mft_wfg.h.
Referenced by Mft_Wfg_Nzcl_Init(), MftWfgDeInitNvic(), and MftWfgInitNvic().
#define MFT1_WFG (*((volatile stc_mftn_wfg_t *) FM_MFT1_WFG_BASE))
Definition at line 257 of file mft_wfg.h.
Referenced by Mft_Wfg_Nzcl_Init(), MftWfgDeInitNvic(), and MftWfgInitNvic().
#define MFT2_WFG (*((volatile stc_mftn_wfg_t *) FM_MFT2_WFG_BASE))
Definition at line 258 of file mft_wfg.h.
Referenced by Mft_Wfg_Nzcl_Init(), MftWfgDeInitNvic(), and MftWfgInitNvic().
#define MFT_WFG_CH0 0u
Definition at line 260 of file mft_wfg.h.
#define MFT_WFG_CH1 1u
Definition at line 261 of file mft_wfg.h.
#define MFT_WFG_CH10 0u
Definition at line 267 of file mft_wfg.h.
Referenced by Mft_Wfg_ClrTimerIrqFlag(), Mft_Wfg_DeInit(), Mft_Wfg_GetTimerIrqFlag(), Mft_Wfg_Init(), Mft_Wfg_StartTimer(), and Mft_Wfg_StopTimer().
#define MFT_WFG_CH2 2u
Definition at line 262 of file mft_wfg.h.
#define MFT_WFG_CH3 3u
Definition at line 263 of file mft_wfg.h.
#define MFT_WFG_CH32 1u
Definition at line 268 of file mft_wfg.h.
Referenced by Mft_Wfg_ClrTimerIrqFlag(), Mft_Wfg_DeInit(), Mft_Wfg_GetTimerIrqFlag(), Mft_Wfg_Init(), Mft_Wfg_StartTimer(), and Mft_Wfg_StopTimer().
#define MFT_WFG_CH4 4u
Definition at line 264 of file mft_wfg.h.
#define MFT_WFG_CH5 5u
Definition at line 265 of file mft_wfg.h.
#define MFT_WFG_CH54 2u
Definition at line 269 of file mft_wfg.h.
Referenced by Mft_Wfg_ClrTimerIrqFlag(), Mft_Wfg_DeInit(), Mft_Wfg_GetTimerIrqFlag(), Mft_Wfg_Init(), Mft_Wfg_StartTimer(), and Mft_Wfg_StopTimer().
#define MFT_WFG_MAXCH 3u
Definition at line 270 of file mft_wfg.h.
Referenced by Mft_Wfg_ClrTimerIrqFlag(), Mft_Wfg_Init(), Mft_Wfg_StartTimer(), Mft_Wfg_StopTimer(), and Mft_Wfg_WriteTimerCountCycle().
#define stc_mftn_wfg_t FM_MFT_WFG_TypeDef
Definition at line 254 of file mft_wfg.h.
Referenced by MftWfgDeInitNvic(), and MftWfgInitNvic().
#define WFG_INSTANCE_COUNT
Value:
(PDL_PERIPHERAL_ENABLE_MFT0_WFG == PDL_ON ? 1u : 0u) + \
                                 (PDL_PERIPHERAL_ENABLE_MFT1_WFG == PDL_ON ? 1u : 0u) + \
                                 (PDL_PERIPHERAL_ENABLE_MFT2_WFG == PDL_ON ? 1u : 0u)
Definition at line 272 of file mft_wfg.h.
Referenced by MftGetInternDataPtr().
Typedef Documentation
typedef enum en_dmod_bits en_dmod_bits_t
typedef enum en_gten_bits en_gten_bits_t
typedef enum en_mft_wfg_mode en_mft_wfg_mode_t
typedef enum en_nzcl_filter_width en_nzcl_filter_width_t
typedef enum en_pgen_bits en_pgen_bits_t
typedef enum en_psel_bits en_psel_bits_t
typedef enum en_wfg_instance_index en_wfg_instance_index_t
Enumeration to define an index for each WFG instance.
typedef enum en_wfg_timer_clock en_wfg_timer_clock_t
typedef struct stc_mft_wfg_instance_data stc_mft_wfg_instance_data_t
typedef struct stc_mft_wfg_intern_data stc_mft_wfg_intern_data_t
typedef struct stc_wfg_config stc_wfg_config_t
typedef struct stc_wfg_nzcl_config stc_wfg_nzcl_config_t
Enumeration Type Documentation
enum en_dmod_bits
Enumerator:
DmodBits00B
output RTO1 and RTO0 signals without changing the level
DmodBits01B
output both RTO1 and RTO0 signals reversed
DmodBits10B
Outputs the RTO(0) signal reversed, outputs the RTO(1) signal without changing the level.
DmodBits11B
Outputs the RTO(0) signal without changing the level, Outputs the RTO(1) signal reversed.
Definition at line 348 of file mft_wfg.h.
enum en_gten_bits
Enumerator:
GtenBits00B
GTEN == b'00.
GtenBits01B
GTEN == b'01.
GtenBits10B
GTEN == b'10.
GtenBits11B
GTEN == b'11.
Definition at line 312 of file mft_wfg.h.
enum en_mft_wfg_mode
Enumerator:
WfgThroughMode
through mode
WfgRtPpgMode
RT-PPG mode.
WfgTimerPpgMode
Timer-PPG mode.
WfgRtDeadTimerMode
RT-dead timer mode.
WfgRtDeadTimerFilterMode
RT-dead timer filter mode.
WfgPpgDeadTimerFilterMode
PPG-dead timer filter mode.
WfgPpgDeadTimerMode
PPG-dead timer mode.
Definition at line 297 of file mft_wfg.h.
enum en_nzcl_filter_width
Enumerator:
NzlcNoFilter
no noise-canceling
NzlcWidth4Cycle
4 PCLK cycles
NzlcWidth8Cycle
8 PCLK cycles
NzlcWidth16Cycle
16 PCLK cycles
NzlcWidth32Cycle
32 PCLK cycles
NzlcWidth64Cycle
64 PCLK cycles
NzlcWidth128Cycle
128 PCLK cycles
NzlcWidth256Cycle
256 PCLK cycles
Definition at line 415 of file mft_wfg.h.
enum en_pgen_bits
Enumerator:
PgenBits00B
PGEN == b'00.
PgenBits01B
PGEN == b'01.
PgenBits10B
PGEN == b'10.
PgenBits11B
PGEN == b'11.
Definition at line 336 of file mft_wfg.h.
enum en_psel_bits
Enumerator:
PselBits00B
PSEL == b'00.
PselBits01B
PSEL == b'01.
PselBits10B
PSEL == b'10.
PselBits11B
PSEL == b'11.
Definition at line 324 of file mft_wfg.h.
enum en_wfg_instance_index
Enumeration to define an index for each WFG instance.
Enumerator:
WfgInstanceIndexWfg0
Instance index of WFG0.
WfgInstanceIndexWfg1
Instance index of WFG1.
WfgInstanceIndexWfg2
Instance index of WFG2.
Definition at line 280 of file mft_wfg.h.
enum en_wfg_timer_clock
Enumerator:
WfgPlckDiv1
WFG timer clock prescaler: None.
WfgPlckDiv2
WFG timer clock prescaler: 1/2.
WfgPlckDiv4
WFG timer clock prescaler: 1/4.
WfgPlckDiv8
WFG timer clock prescaler: 1/8.
WfgPlckDiv16
WFG timer clock prescaler: 1/16.
WfgPlckDiv32
WFG timer clock prescaler: 1/32.
WfgPlckDiv64
WFG timer clock prescaler: 1/64.
WfgPlckDiv128
WFG timer clock prescaler: 1/128.
Definition at line 361 of file mft_wfg.h.
Function Documentation
en_result_t Mft_Wfg_ClrTimerIrqFlag (volatile FM_MFT_WFG_TypeDef * pstcWfg, uint8_t u8CoupleCh)
clear WFG timer interrupt flag
Parameters:
[in] pstcWfg Pointer to WFG instance
[in] u8CoupleCh channel of WFG couple
MFT_WFG_CH10 ~ MFT_WFG_CH54
Return values:
Ok WFG timer interrupt flag is clear
ErrorInvalidParameter If one of following conditions are met:
pstcMft == NULL
u8CoupleCh out of range
Definition at line 729 of file mft_wfg.c.
References MFT_WFG_CH10, MFT_WFG_CH32, MFT_WFG_CH54, and MFT_WFG_MAXCH.
Referenced by Mft_Wfg_IrqHandler().
en_result_t Mft_Wfg_DeInit (volatile FM_MFT_WFG_TypeDef * pstcWfg, uint8_t u8CoupleCh, boolean_t bTouchNvic)
De-Initialize a couple WFG channels.
Parameters:
[in] pstcWfg Pointer to WFG instance
[in] u8CoupleCh Couple channel of WFG couple
MFT_WFG_CH10 ~ MFT_WFG_CH54
[in] bTouchNvic Touch NVIC or not
Return values:
Ok WFG mode is configured
ErrorInvalidParameter If one of following conditions are met:
pstcWfg == NULL
u8CoupleCh out of range
Other invalid configuration
Definition at line 537 of file mft_wfg.c.
References MFT_WFG_CH10, MFT_WFG_CH32, MFT_WFG_CH54, MftGetInternDataPtr(), MftWfgDeInitNvic(), stc_mft_wfg_intern_data::pfnWfg10TimerIrqCallback, stc_mft_wfg_intern_data::pfnWfg32TimerIrqCallback, and stc_mft_wfg_intern_data::pfnWfg54TimerIrqCallback.
en_irq_flag_t Mft_Wfg_GetTimerIrqFlag (volatile FM_MFT_WFG_TypeDef * pstcWfg, uint8_t u8CoupleCh)
get WFG timer interrupt flag
Parameters:
[in] pstcWfg Pointer to WFG instance
[in] u8CoupleCh channel of WFG couple
MFT_WFG_CH10 ~ MFT_WFG_CH54
Return values:
PdlSet WFG Interrupt flag is set
PdlClr WFG Interrupt flag is clear
Definition at line 691 of file mft_wfg.c.
References MFT_WFG_CH10, MFT_WFG_CH32, MFT_WFG_CH54, PdlClr, and PdlSet.
Referenced by Mft_Wfg_IrqHandler().
en_result_t Mft_Wfg_Init (volatile FM_MFT_WFG_TypeDef * pstcWfg, uint8_t u8CoupleCh, stc_wfg_config_t * pstcConfig)
Initialize a couple WFG channels.
Parameters:
[in] pstcWfg Pointer to WFG instance
[in] u8CoupleCh channel of WFG couple
MFT_WFG_CH10 ~ MFT_WFG_CH54
[in] pstcConfig Pointer to WFG configuration
see the struct stc_wfg_config_t
Return values:
Ok WFG mode is configured
ErrorInvalidParameter If one of following conditions are met:
pstcMft == NULL
u8CoupleCh out of range
Other invalid configuration
Definition at line 312 of file mft_wfg.c.
References stc_wfg_config::bTouchNvic, stc_wfg_config::bWfgimerIrqMask, DmodBits00B, DmodBits01B, DmodBits10B, DmodBits11B, stc_wfg_config::enClk, stc_wfg_config::enDmodBits, stc_wfg_config::enGtenBits, stc_wfg_config::enMode, stc_wfg_config::enPgenBits, stc_wfg_config::enPselBits, GtenBits00B, GtenBits01B, GtenBits10B, GtenBits11B, MFT_WFG_CH10, MFT_WFG_CH32, MFT_WFG_CH54, MFT_WFG_MAXCH, MftGetInternDataPtr(), MftWfgInitNvic(), stc_mft_wfg_intern_data::pfnWfg10TimerIrqCallback, stc_mft_wfg_intern_data::pfnWfg32TimerIrqCallback, stc_mft_wfg_intern_data::pfnWfg54TimerIrqCallback, stc_wfg_config::pfnWfgTimerIrqCallback, PgenBits00B, PgenBits01B, PgenBits10B, PgenBits11B, PselBits00B, PselBits01B, PselBits10B, PselBits11B, WfgPlckDiv1, WfgPlckDiv128, WfgPlckDiv16, WfgPlckDiv2, WfgPlckDiv32, WfgPlckDiv4, WfgPlckDiv64, WfgPlckDiv8, WfgPpgDeadTimerFilterMode, WfgPpgDeadTimerMode, WfgRtDeadTimerFilterMode, WfgRtDeadTimerMode, WfgRtPpgMode, WfgThroughMode, and WfgTimerPpgMode.
void Mft_Wfg_IrqHandler (volatile FM_MFT_WFG_TypeDef * pstcWfg, stc_mft_wfg_intern_data_t * pstcMftWfgInternData)
WFG interrupt handler sub function.
Parameters:
[in] pstcWfg Pointer to WFG instance
[in] pstcMftWfgInternData structure of WFG callback function
structure of stc_mft_intern_data
Definition at line 149 of file mft_wfg.c.
References Mft_Wfg_ClrTimerIrqFlag(), Mft_Wfg_GetTimerIrqFlag(), Mft_Wfg_Nzcl_GetAnalogFilterIrqFlag(), Mft_Wfg_Nzcl_GetDigitalFilterIrqFlag(), PdlSet, stc_mft_wfg_intern_data::pfnDtifAnalogFilterIrqCallback, stc_mft_wfg_intern_data::pfnDtifDigtalFilterIrqCallback, and stc_mft_wfg_intern_data::pfnWfg10TimerIrqCallback.
en_result_t Mft_Wfg_Nzcl_ClrAnalogFilterIrqFlag (volatile FM_MFT_WFG_TypeDef * pstcWfg)
clear Analog Filter interrupt flag
Parameters:
[in] pstcWfg Pointer to WFG instance
Return values:
Ok Analog Filter interrupt flag is clear
ErrorInvalidParameter If one of following conditions are met:
pstcMft == NULL
u8CoupleCh out of range
Definition at line 1105 of file mft_wfg.c.
en_result_t Mft_Wfg_Nzcl_ClrDigitalFilterIrqFlag (volatile FM_MFT_WFG_TypeDef * pstcWfg)
clear Digital filter interrupt flag
Parameters:
[in] pstcWfg Pointer to WFG instance
Return values:
Ok Digital filter interrupt flag is clear
ErrorInvalidParameter If one of following conditions are met:
pstcMft == NULL
u8CoupleCh out of range
Definition at line 1058 of file mft_wfg.c.
en_result_t Mft_Wfg_Nzcl_DeInit (volatile FM_MFT_WFG_TypeDef * pstcWfg, boolean_t bTouchNvic)
De-Initialize NZCL of waveform generator.
Parameters:
[in] pstcWfg Pointer to WFG instance
[in] bTouchNvic Disable NVIC or not
TRUE Disable NVIC
FALSE Don't disable NVIC
Return values:
Ok NZCL is cleared
ErrorInvalidParameter If one of following conditions are met:
pstcMft == NULL
Definition at line 978 of file mft_wfg.c.
References MftWfgDeInitNvic().
en_irq_flag_t Mft_Wfg_Nzcl_GetAnalogFilterIrqFlag (volatile FM_MFT_WFG_TypeDef * pstcWfg)
get Analog Filter interrupt flag
Parameters:
[in] pstcWfg Pointer to WFG instance
Return values:
PdlClr Analog Filter interrupt flag is clear
PdlSet Analog Filter interrupt flag is set
Definition at line 1083 of file mft_wfg.c.
References PdlClr, and PdlSet.
Referenced by Mft_Wfg_IrqHandler().
en_irq_flag_t Mft_Wfg_Nzcl_GetDigitalFilterIrqFlag (volatile FM_MFT_WFG_TypeDef * pstcWfg)
get Digital filter interrupt flag
Parameters:
[in] pstcWfg Pointer to WFG instance
Return values:
PdlClr Digital Filter interrupt flag is clear
PdlSet Digital Filter interrupt flag is set
Definition at line 1035 of file mft_wfg.c.
References PdlClr, and PdlSet.
Referenced by Mft_Wfg_IrqHandler().
en_result_t Mft_Wfg_Nzcl_Init (volatile FM_MFT_WFG_TypeDef * pstcWfg, stc_wfg_nzcl_config_t * pstcNzclConfig, boolean_t bTouchNvic)
Initialize NZCL of waveform generator.
Parameters:
[in] pstcWfg Pointer to WFG instance
[in] pstcNzclConfig Configure of NZCL
[in] bTouchNvic Touch NVIC or not
Return values:
Ok NZCL is configured
ErrorInvalidParameter If one of following conditions are met:
pstcMft == NULL
Definition at line 863 of file mft_wfg.c.
References stc_wfg_nzcl_config::bDtifAnalogFilterIrqMask, stc_wfg_nzcl_config::bDtifDigitalFilterIrqMask, stc_wfg_nzcl_config::bEnAnalogFilter, stc_wfg_nzcl_config::bEnDigitalFilter, stc_wfg_nzcl_config::bHoldRto, stc_wfg_nzcl_config::bSwitchToGpio, stc_wfg_nzcl_config::enDigitalFilterWidth, MFT0_WFG, MFT1_WFG, MFT2_WFG, MftGetInternDataPtr(), MftWfgInitNvic(), NzlcNoFilter, NzlcWidth128Cycle, NzlcWidth16Cycle, NzlcWidth256Cycle, NzlcWidth32Cycle, NzlcWidth4Cycle, NzlcWidth64Cycle, NzlcWidth8Cycle, stc_mft_wfg_intern_data::pfnDtifAnalogFilterIrqCallback, stc_wfg_nzcl_config::pfnDtifAnalogFilterIrqCallback, stc_mft_wfg_intern_data::pfnDtifDigtalFilterIrqCallback, and stc_wfg_nzcl_config::pfnDtifDigtalFilterIrqCallback.
en_result_t Mft_Wfg_Nzcl_SwTiggerDtif (volatile FM_MFT_WFG_TypeDef * pstcWfg)
set software trigger DTIF
Parameters:
[in] pstcWfg Pointer to WFG instance
Return values:
Ok DTIF is triggered by software
ErrorInvalidParameter If one of following conditions are met:
pstcMft == NULL
u8CoupleCh out of range
Definition at line 1012 of file mft_wfg.c.
en_result_t Mft_Wfg_NzclClrAnalogFilterIrqFlag (volatile FM_MFT_WFG_TypeDef * pstcWfg)
en_result_t Mft_Wfg_SetFilterCountValue (volatile FM_MFT_WFG_TypeDef * pstcWfg, uint8_t u8CoupleCh, uint16_t u16Count)
set cycle of WFG timer
Parameters:
[in] pstcWfg Pointer to WFG instance
[in] u8CoupleCh channel of WFG couple
MFT_WFG_CH10 ~ MFT_WFG_CH54
[in] u16Count wfg pulse counter value
0~65535
Return values:
Ok cycle of WFG timer is set
ErrorInvalidParameter If one of following conditions are met:
pstcMft == NULL
u8CoupleCh out of range
Definition at line 837 of file mft_wfg.c.
en_result_t Mft_Wfg_StartTimer (volatile FM_MFT_WFG_TypeDef * pstcWfg, uint8_t u8CoupleCh)
Start WFG timer.
Parameters:
[in] pstcWfg Pointer to WFG instance
[in] u8CoupleCh channel of WFG couple
MFT_WFG_CH10 ~ MFT_WFG_CH54
Return values:
Ok Start timer successfully
ErrorInvalidParameter If one of following conditions are met:
pstcMft == NULL
u8CoupleCh out of range
Definition at line 610 of file mft_wfg.c.
References MFT_WFG_CH10, MFT_WFG_CH32, MFT_WFG_CH54, and MFT_WFG_MAXCH.
en_result_t Mft_Wfg_StopTimer (volatile FM_MFT_WFG_TypeDef * pstcWfg, uint8_t u8CoupleCh)
Stop WFG timer.
Parameters:
[in] pstcWfg Pointer to WFG instance
[in] u8CoupleCh channel of WFG couple
MFT_WFG_CH10 ~ MFT_WFG_CH54
Return values:
Ok Stop timer successfully
ErrorInvalidParameter If one of following conditions are met:
pstcMft == NULL
u8CoupleCh out of range
Definition at line 651 of file mft_wfg.c.
References MFT_WFG_CH10, MFT_WFG_CH32, MFT_WFG_CH54, and MFT_WFG_MAXCH.
en_result_t Mft_Wfg_WriteTimerCountCycle (volatile FM_MFT_WFG_TypeDef * pstcWfg, uint8_t u8CoupleCh, uint16_t u16CycleA, uint16_t u16CycleB)
write timer count cycle
Parameters:
[in] pstcWfg Pointer to WFG instance
[in] u8CoupleCh channel of WFG couple
MFT_WFG_CH10 ~ MFT_WFG_CH54
[in] u16CycleA WFTA value
0~65535
[in] u16CycleB WFTB value
0~65535
Return values:
Ok Timer count cycle is written
ErrorInvalidParameter If one of following conditions are met:
pstcMft == NULL
u8CoupleCh out of range
u16CycleA != u16CycleB (FM3 products)
Definition at line 778 of file mft_wfg.c.
References MFT_WFG_MAXCH.
static stc_mft_wfg_intern_data_t* MftGetInternDataPtr (volatile FM_MFT_WFG_TypeDef * pstcWfg) [static]
Return the internal data for a certain WFG instance.
Parameters:
pstcWfg Pointer to WFG instance
Returns:
Pointer to internal data or NULL if instance is not enabled (or not known)
Definition at line 121 of file mft_wfg.c.
References stc_mft_wfg_instance_data::stcInternData, and WFG_INSTANCE_COUNT.
Referenced by Mft_Wfg_DeInit(), Mft_Wfg_Init(), and Mft_Wfg_Nzcl_Init().
static void MftWfgDeInitNvic (volatile FM_MFT_WFG_TypeDef * pstcWfg) [static]
Device dependent de-initialization of interrupts according CMSIS.
Parameters:
[in] pstcWfg Pointer to WFG instance
Return values:
Ok Successful initialization
Definition at line 256 of file mft_wfg.c.
References MFT0_WFG, MFT1_WFG, MFT2_WFG, PDL_DEFAULT_INTERRUPT_LEVEL, and stc_mftn_wfg_t.
Referenced by Mft_Wfg_DeInit(), and Mft_Wfg_Nzcl_DeInit().
static void MftWfgInitNvic (volatile FM_MFT_WFG_TypeDef * pstcWfg) [static]
Device dependent initialization of interrupts according CMSIS with level defined in pdl.h.
Parameters:
[in] pstcWfg Pointer to WFG instance
Return values:
Ok Successful initialization
Definition at line 211 of file mft_wfg.c.
References MFT0_WFG, MFT1_WFG, MFT2_WFG, and stc_mftn_wfg_t.
Referenced by Mft_Wfg_Init(), and Mft_Wfg_Nzcl_Init().
Variable Documentation
stc_mft_wfg_instance_data_t m_astcMftWfgInstanceDataLut[(PDL_PERIPHERAL_ENABLE_MFT0_WFG==PDL_ON?1u:0u)+(PDL_PERIPHERAL_ENABLE_MFT1_WFG==PDL_ON?1u:0u)+(PDL_PERIPHERAL_ENABLE_MFT2_WFG==PDL_ON?1u:0u)]
Initial value:
{
    {
        & (*((volatile  FM_MFT_WFG_TypeDef  *) FM_MFT0_WFG_BASE)) ,
        0u
    },
    {
        & (*((volatile  FM_MFT_WFG_TypeDef  *) FM_MFT1_WFG_BASE)) ,
        0u
    },
    {
        & (*((volatile  FM_MFT_WFG_TypeDef  *) FM_MFT2_WFG_BASE)) ,
        0u
    },
}
Look-up table for all enabled WFG instances and their internal data.
Definition at line 74 of file mft_wfg.c.
stc_mft_wfg_instance_data_t m_astcMftWfgInstanceDataLut[(PDL_PERIPHERAL_ENABLE_MFT0_WFG==PDL_ON?1u:0u)+(PDL_PERIPHERAL_ENABLE_MFT1_WFG==PDL_ON?1u:0u)+(PDL_PERIPHERAL_ENABLE_MFT2_WFG==PDL_ON?1u:0u)]
Look-up table for all enabled WFG instances and their internal data.
Definition at line 74 of file mft_wfg.c.