PDL for FM Family: HDMI-CEC/Remote Control Reception/Transmission (RC)
HDMI-CEC/Remote Control Reception/Transmission (RC)
Data Structures
struct stc_rc_rx_addr
Remoter Control Receiver address structure.
struct stc_rc_rx_sircs_irq_en
Remoter Control Receiver SIRCS mode interrupt enable structure.
struct stc_rc_rx_sircs_irq_cb
Remoter Control Receiver SIRCS mode interrupt callback function.
struct stc_rc_rx_nec_irq_en
Remoter Control Receiver NEC mode interrupt enable structure.
struct stc_rc_rx_nec_irq_cb
Remoter Control Receiver NEC mode interrupt callback functions.
struct stc_rc_rx_cec_irq_en
Remoter Control Receiver CEC mode interrupt enable structure.
struct stc_rc_rx_cec_irq_cb
Remoter Control Receiver CEC mode interrupt callback functions.
struct stc_rc_tx_cec_irq_en
Remoter Control Transmission interrupt enable structure.
struct stc_rc_tx_irq_cb
Remoter Control Transmission interrupt callback function.
struct stc_rc_intern_data
Intern data structure.
struct stc_rc_rx_sircs_config
Remoter Control Receiver SIRCS mode configuration.
struct stc_rc_rx_nec_config
Remoter Control Receiver NEC mode configuration.
struct stc_rc_rx_cec_config
Remoter Control Receiver CEC mode configuration.
struct rc_rx_sircs_data
Remoter Control Receiver SIRCS data format.
struct rc_rx_nec_data
Remoter Control Receiver NEC data format.
struct stc_rc_tx_cec_config
Remoter Control Receiver CEC mode configuration.
struct stc_rc_instance_data
RC instance data type.
Defines
#define stc_rcn_t FM_HDMICEC_TypeDef
#define RC0 (*((volatile stc_rcn_t *) FM_HDMICEC0_BASE))
#define RC1 (*((volatile stc_rcn_t *) FM_HDMICEC1_BASE))
#define RC_INSTANCE_COUNT
Typedefs
typedef enum en_rc_mode en_rc_mode_t
RC mode setting.
typedef enum en_rc_src_clk en_rc_src_clk_t
RC CLK.
typedef enum en_rc_threshold_type en_rc_threshold_type_t
RC threshold type.
typedef enum en_rc_overflow en_rc_overflow_t
RC overflow type.
typedef struct stc_rc_rx_addr stc_rc_rx_addr_t
Remoter Control Receiver address structure.
typedef struct
stc_rc_rx_sircs_irq_en stc_rc_rx_sircs_irq_en_t
Remoter Control Receiver SIRCS mode interrupt enable structure.
typedef enum en_rc_rx_sircs_irq_sel en_rc_rx_sircs_irq_sel_t
Remoter Control Receiver SIRCS mode interrupt selection enumeration.
typedef struct
stc_rc_rx_sircs_irq_cb stc_rc_rx_sircs_irq_cb_t
Remoter Control Receiver SIRCS mode interrupt callback function.
typedef struct stc_rc_rx_nec_irq_en stc_rc_rx_nec_irq_en_t
Remoter Control Receiver NEC mode interrupt enable structure.
typedef enum en_rc_rx_nec_irq_sel en_rc_rx_nec_irq_sel_t
Remoter Control Receiver NEC mode interrupt selection enumeration.
typedef struct stc_rc_rx_nec_irq_cb stc_rc_rx_nec_irq_cb_t
Remoter Control Receiver NEC mode interrupt callback functions.
typedef struct stc_rc_rx_cec_irq_en stc_rc_rx_cec_irq_en_t
Remoter Control Receiver CEC mode interrupt enable structure.
typedef enum en_rc_rx_cec_irq_sel en_rc_rx_cec_irq_sel_t
Remoter Control Receiver CEC mode interrupt selection enumeration.
typedef struct stc_rc_rx_cec_irq_cb stc_rc_rx_cec_irq_cb_t
Remoter Control Receiver CEC mode interrupt callback functions.
typedef enum en_rc_txdata_type en_rc_txdata_type_t
Remoter Control Transmission data type.
typedef enum en_rc_tx_cec_irq_sel en_rc_tx_cec_irq_sel_t
Remoter Control Transmission interrupt selection.
typedef struct stc_rc_tx_cec_irq_en stc_rc_tx_cec_irq_en_t
Remoter Control Transmission interrupt enable structure.
typedef struct stc_rc_tx_irq_cb stc_rc_tx_cec_irq_cb_t
Remoter Control Transmission interrupt callback function.
typedef struct stc_rc_intern_data stc_rc_intern_data_t
Intern data structure.
typedef struct
stc_rc_rx_sircs_config stc_rc_rx_sircs_config_t
Remoter Control Receiver SIRCS mode configuration.
typedef struct stc_rc_rx_nec_config stc_rc_rx_nec_config_t
Remoter Control Receiver NEC mode configuration.
typedef struct stc_rc_rx_cec_config stc_rc_rx_cec_config_t
Remoter Control Receiver CEC mode configuration.
typedef struct rc_rx_sircs_data rc_rx_sircs_data_t
Remoter Control Receiver SIRCS data format.
typedef struct rc_rx_nec_data rc_rx_nec_data_t
Remoter Control Receiver NEC data format.
typedef struct stc_rc_tx_cec_config stc_rc_tx_cec_config_t
Remoter Control Receiver CEC mode configuration.
typedef enum en_rc_instance_index en_rc_instance_index_t
Enumeration to define an index for each enabled RC instance.
typedef struct stc_rc_instance_data stc_rc_instance_data_t
RC instance data type.
Enumerations
enum en_rc_mode { RcSircsMode = 0u, RcSettingProh = 1u, RcNecMode = 2u, RcCecMode = 3u }
RC mode setting.
enum en_rc_src_clk { RcPeripheralClk = 0u, RcSubClk = 1u }
RC CLK.
enum en_rc_threshold_type { RcThresholdType0 = 0u, RcThresholdType1 = 1u }
RC threshold type.
enum en_rc_overflow { RcOverflow128Cycle = 0u, RcOverflow256Cycle = 1u }
RC overflow type.
enum en_rc_rx_sircs_irq_sel { RcRxSircsStartIrq = 0u, RcRxSircsAckIrq = 1u, RcRxSircsCntOvfIrq = 2u }
Remoter Control Receiver SIRCS mode interrupt selection enumeration.
enum en_rc_rx_nec_irq_sel { RcRxNecStartIrq = 0u, RcRxNecAckIrq = 1u, RcRxNecCntOvfIrq = 2u, RcRxNecRepeatCodeIrq = 3u }
Remoter Control Receiver NEC mode interrupt selection enumeration.
enum en_rc_rx_cec_irq_sel {
RcRxCecStartIrq = 0u, RcRxCecAckIrq = 1u, RcRxCecCntOvfIrq = 2u, RcRxCecMinDataIrq = 3u,
RcRxCecMaxDataIrq = 4u
}
Remoter Control Receiver CEC mode interrupt selection enumeration.
enum en_rc_txdata_type { RcTxCecHeader = 0u, RcTxCecData = 1u, RcTxCecPolling = 2u, RcTxCecFinal = 3u }
Remoter Control Transmission data type.
enum en_rc_tx_cec_irq_sel { RcTxCecBusErrorIrq = 0u, RcTxCecTransStausIrq = 1u }
Remoter Control Transmission interrupt selection.
enum en_rc_instance_index { RcInstanceIndexRc0, RcInstanceIndexRc1, RcInstanceIndexMax }
Enumeration to define an index for each enabled RC instance.
Functions
static void RcInitNvic (void)
Initialize NVIC of Remote Control.
static void RcDeInitNvic (void)
De-Initialize NVIC of Remote Control.
void RcIrqHandler (volatile FM_HDMICEC_TypeDef *pstcRc, stc_rc_intern_data_t *pstcRcInternData)
RC instance interrupt service routine.
static stc_rc_intern_data_t * RcGetInternDataPtr (volatile FM_HDMICEC_TypeDef *pstcRc)
Return the internal data for a certain RC instance.
en_result_t Rc_Rx_Sircs_Init (volatile FM_HDMICEC_TypeDef *pstcRc, stc_rc_rx_sircs_config_t *pstcRcSircsConfig)
Initialize SIRCS mode of Remote Control Reception.
en_result_t Rc_Rx_Sircs_DeInit (volatile FM_HDMICEC_TypeDef *pstcRc, boolean_t bTouchNvic)
De-Initialize SIRCS mode of Remote Control Reception.
en_result_t Rc_Rx_Sircs_EnableRx (volatile FM_HDMICEC_TypeDef *pstcRc)
Enable SIRCS mode reception of Remote Control Reception.
en_result_t Rc_Rx_Sircs_DisableRx (volatile FM_HDMICEC_TypeDef *pstcRc)
Disable SIRCS mode reception of Remote Control Reception.
en_result_t Rc_Rx_Sircs_EnableIrq (volatile FM_HDMICEC_TypeDef *pstcRc, en_rc_rx_sircs_irq_sel_t enIrqSel)
Enable interrupt of Remote Control Reception with SIRCS mode.
en_result_t Rc_Rx_Sircs_DisableIrq (volatile FM_HDMICEC_TypeDef *pstcRc, en_rc_rx_sircs_irq_sel_t enIrqSel)
Disable interrupt of Remote Control Reception with SIRCS mode.
boolean_t Rc_Rx_Sircs_GetIrqFlag (volatile FM_HDMICEC_TypeDef *pstcRc, en_rc_rx_sircs_irq_sel_t enIrqSel)
Get interrupt flag of Remote Control Reception with SIRCS mode.
en_result_t Rc_Rx_Sircs_ClrIrqFlag (volatile FM_HDMICEC_TypeDef *pstcRc, en_rc_rx_sircs_irq_sel_t enIrqSel)
Clear interrupt flag of Remote Control Reception with SIRCS mode.
en_result_t Rc_Rx_Sircs_ReadData (volatile FM_HDMICEC_TypeDef *pstcRc, rc_rx_sircs_data_t *pstcData)
Get data of Remote Control Reception with SIRCS mode.
en_result_t Rc_Rx_Nec_Init (volatile FM_HDMICEC_TypeDef *pstcRc, stc_rc_rx_nec_config_t *pstcRcNecConfig)
Initialize NEC mode of Remote Control Reception.
en_result_t Rc_Rx_Nec_DeInit (volatile FM_HDMICEC_TypeDef *pstcRc, boolean_t bTouchNvic)
De-Initialize NEC mode of Remote Control Reception.
en_result_t Rc_Rx_Nec_EnableRx (volatile FM_HDMICEC_TypeDef *pstcRc)
Enable NEC mode reception of Remote Control Reception.
en_result_t Rc_Rx_Nec_DisableRx (volatile FM_HDMICEC_TypeDef *pstcRc)
Disable NEC mode reception of Remote Control Reception.
en_result_t Rc_Rx_Nec_EnableIrq (volatile FM_HDMICEC_TypeDef *pstcRc, en_rc_rx_nec_irq_sel_t enIrqSel)
Enable interrupt of Remote Control Reception with NEC mode.
en_result_t Rc_Rx_Nec_DisableIrq (volatile FM_HDMICEC_TypeDef *pstcRc, en_rc_rx_nec_irq_sel_t enIrqSel)
Disable interrupt of Remote Control Reception with NEC mode.
boolean_t Rc_Rx_Nec_GetIrqFlag (volatile FM_HDMICEC_TypeDef *pstcRc, en_rc_rx_nec_irq_sel_t enIrqSel)
Get interrupt flag of Remote Control Reception with NEC mode.
en_result_t Rc_Rx_Nec_ClrIrqFlag (volatile FM_HDMICEC_TypeDef *pstcRc, en_rc_rx_nec_irq_sel_t enIrqSel)
Clear interrupt flag of Remote Control Reception with NEC mode.
en_result_t Rc_Rx_Nec_ReadData (volatile FM_HDMICEC_TypeDef *pstcRc, rc_rx_nec_data_t *pstcData)
Get data of Remote Control Reception with NEC mode.
en_result_t Rc_Rx_Cec_Init (volatile FM_HDMICEC_TypeDef *pstcRc, stc_rc_rx_cec_config_t *pstcRcCecConfig)
Initialize CEC mode of Remote Control Reception.
en_result_t Rc_Rx_Cec_DeInit (volatile FM_HDMICEC_TypeDef *pstcRc, boolean_t bTouchNvic)
De-Initialize CEC mode of Remote Control Reception.
en_result_t Rc_Rx_Cec_EnableRx (volatile FM_HDMICEC_TypeDef *pstcRc)
Enable CEC mode reception of Remote Control Reception.
en_result_t Rc_Rx_Cec_DisableRx (volatile FM_HDMICEC_TypeDef *pstcRc)
Disable CEC mode reception of Remote Control Reception.
en_result_t Rc_Rx_Cec_EnableIrq (volatile FM_HDMICEC_TypeDef *pstcRc, en_rc_rx_cec_irq_sel_t enIrqSel)
Enable interrupt of Remote Control Reception with CEC mode.
en_result_t Rc_Rx_Cec_DisableIrq (volatile FM_HDMICEC_TypeDef *pstcRc, en_rc_rx_cec_irq_sel_t enIrqSel)
Disable interrupt of Remote Control Reception with CEC mode.
boolean_t Rc_Rx_Cec_GetIrqFlag (volatile FM_HDMICEC_TypeDef *pstcRc, en_rc_rx_cec_irq_sel_t enIrqSel)
Get interrupt flag of Remote Control Reception with CEC mode.
en_result_t Rc_Rx_Cec_ClrIrqFlag (volatile FM_HDMICEC_TypeDef *pstcRc, en_rc_rx_cec_irq_sel_t enIrqSel)
Clear interrupt flag of Remote Control Reception with CEC mode.
uint8_t Rc_Rx_Cec_ReadData (volatile FM_HDMICEC_TypeDef *pstcRc)
Get data of Remote Control Reception with CEC mode.
boolean_t Rc_Rx_Cec_GetEomState (volatile FM_HDMICEC_TypeDef *pstcRc)
Get EOM state of Remote Control Reception with CEC mode.
en_result_t Rc_Rx_Cec_ClrEomState (volatile FM_HDMICEC_TypeDef *pstcRc)
clear EOM state of Remote Control Reception with CEC mode
en_result_t Rc_Tx_Cec_Init (volatile FM_HDMICEC_TypeDef *pstcRc, stc_rc_tx_cec_config_t *pstcRcTxConfig)
Initialize CEC mode of Remote Control transmission.
en_result_t Rc_Tx_Cec_DeInit (volatile FM_HDMICEC_TypeDef *pstcRc, boolean_t bTouchNvic)
De-Initialize CEC mode of Remote Control transmission.
en_result_t Rc_Tx_Cec_EnableTx (volatile FM_HDMICEC_TypeDef *pstcRc)
Enable CEC mode transfer of Remote Control transmision.
en_result_t Rc_Tx_Cec_DisableTx (volatile FM_HDMICEC_TypeDef *pstcRc)
Disable CEC mode transfer of Remote Control transmision.
en_result_t Rc_Tx_Cec_EnableIrq (volatile FM_HDMICEC_TypeDef *pstcRc, en_rc_tx_cec_irq_sel_t enIrqSel)
Enable CEC mode interrupt of Remote Control transmision.
en_result_t Rc_Tx_Cec_DisableIrq (volatile FM_HDMICEC_TypeDef *pstcRc, en_rc_tx_cec_irq_sel_t enIrqSel)
Disable CEC mode interrupt of Remote Control transmision.
boolean_t Rc_Tx_Cec_GetIrqFlag (volatile FM_HDMICEC_TypeDef *pstcRc, en_rc_tx_cec_irq_sel_t enIrqSel)
Get interrupt flag of Remote Control transmission with CEC mode.
en_result_t Rc_Tx_Cec_ClrIrqFlag (volatile FM_HDMICEC_TypeDef *pstcRc, en_rc_tx_cec_irq_sel_t enIrqSel)
Clear interrupt flag of Remote Control Transmission with CEC mode.
boolean_t Rc_Tx_GetAckCycleValue (volatile FM_HDMICEC_TypeDef *pstcRc)
Get ACK cycle value of Remote Control transmission with CEC mode.
en_result_t Rc_Tx_Cec_WriteData (volatile FM_HDMICEC_TypeDef *pstcRc, uint8_t u8Data, en_rc_txdata_type_t enType)
Write data into data specified with data type for CEC TX mode.
en_result_t Rc_Tx_Cec_SendDataPolling (volatile FM_HDMICEC_TypeDef *pstcRc, uint8_t u8Header, uint8_t *pu8Data, uint32_t u32Size)
Write CEC data package with polling mode for CEC TX mode.
Variables
stc_rc_instance_data_t m_astcRcInstanceDataLut [(uint8_t)(PDL_PERIPHERAL_ENABLE_RC0==PDL_ON)+(uint8_t)(PDL_PERIPHERAL_ENABLE_RC1==PDL_ON)]
Look-up table for all enabled RC instances and their internal data.
stc_rc_instance_data_t m_astcRcInstanceDataLut [(uint8_t)(PDL_PERIPHERAL_ENABLE_RC0==PDL_ON)+(uint8_t)(PDL_PERIPHERAL_ENABLE_RC1==PDL_ON)]
Look-up table for all enabled RC instances and their internal data.
Detailed Description
Provided functions of RC module:
Rc_Rx_Sircs_Init()
Rc_Rx_Sircs_DeInit()
Rc_Rx_Sircs_EnableRx()
Rc_Rx_Sircs_DisableRx()
Rc_Rx_Sircs_EnableIrq()
Rc_Rx_Sircs_DisableIrq()
Rc_Rx_Sircs_GetIrqFlag()
Rc_Rx_Sircs_ClrIrqFlag()
Rc_Rx_Sircs_ReadData()
Rc_Rx_Nec_Init()
Rc_Rx_Nec_DeInit()
Rc_Rx_Nec_EnableRx()
Rc_Rx_Nec_DisableRx()
Rc_Rx_Nec_GetIrqFlag()
Rc_Rx_Nec_ClrIrqFlag()
Rc_Rx_Nec_EnableIrq()
Rc_Rx_Nec_DisableIrq()
Rc_Rx_Nec_ReadData()
Rc_Rx_Cec_Init()
Rc_Rx_Cec_DeInit()
Rc_Rx_Cec_EnableRx()
Rc_Rx_Cec_DisableRx()
Rc_Rx_Cec_GetIrqFlag()
Rc_Rx_Cec_ClrIrqFlag()
Rc_Rx_Cec_EnableIrq()
Rc_Rx_Cec_DisableIrq()
Rc_Rx_Cec_ReadData()
Rc_Tx_Cec_Init()
Rc_Tx_Cec_DeInit()
Rc_Tx_Cec_EnableTx()
Rc_Tx_Cec_DisableTx()
Rc_Tx_Cec_GetIrqFlag()
Rc_Tx_Cec_ClrIrqFlag()
Rc_Tx_GetAckCycleValue()
Rc_Tx_Cec_EnableIrq()
Rc_Tx_Cec_DisableIrq()
Rc_Tx_Cec_WriteData()
Rc_Tx_Cec_SendDataPolling()
Remote Control Reception supports three modes:
SIRCS mode
NEC mode
HDMI-CEC mode
Remote Control transmission only supports HDMI-CEC mode.
SIRCS mode of Remote Control Reception:
Rc_Rx_Sircs_Init() configures the Remote Control to SIRCS mode and Rc_Rx_Sircs_DeInit() reset the Remote Control.
Rc_Rx_Sircs_EnableRx() enables reception of SIRCS mode in Remote Control Reception. Rc_Rx_Sircs_DisableRx() disables reception of SIRCS mode.
Rc_Rx_Sircs_GetIrqFlag() gets the interrupt flag of SIRCS mode. And Rc_Rx_Sircs_ClrIrqFlag() clears the interrupt flag of SIRCS mode.
Interrupts can be configured in Rc_Rx_Sircs_Init() first, after initialization, Rc_Rx_Sircs_EnableIrq() enables interrupt of SIRCS mode and Rc_Rx_Sircs_DisableIrq() disables interrupt of SIRCS mode.
Rc_Rx_Sircs_ReadData() reads the data received in SIRCS mode.
NEC mode of Remote Control Reception:
Rc_Rx_Nec_Init() configures the Remote Control to NEC mode and Rc_Rx_Nec_DeInit() reset the Remote Control.
Rc_Rx_Nec_EnableRx() enables reception of NEC mode in Remote Control Reception. Rc_Rx_Nec_DisableRx() disables reception of NEC mode.
Rc_Rx_Nec_GetIrqFlag() gets the interrupt flag of NEC mode. And Rc_Rx_Nec_ClrIrqFlag() clears the interrupt flag of NEC mode.
Rc_Rx_Nec_ReadData() reads the data received in NEC mode.
Interrupts can be configured in Rc_Rx_Nec_Init() first, after initialization, Rc_Rx_Nec_EnableIrq() enables interrupt of NEC mode and Rc_Rx_Nec_DisableIrq() disables interrupt of NEC mode.
CEC mode of Remote Control Reception:
Rc_Rx_Cec_Init() configures the Remote Control to CEC mode and Rc_Rx_Cec_DeInit() reset the Remote Control.
Rc_Rx_Cec_EnableRx() enables reception of CEC mode in Remote Control Reception. Rc_Rx_Cec_DisableRx() disables reception of CEC mode.
Rc_Rx_Cec_GetIrqFlag() gets the interrupt flag of CEC mode. And Rc_Rx_Cec_ClrIrqFlag() clears the interrupt flag of CEC mode.
Interrupts can be configured in Rc_Rx_Cec_Init() first, after initialization, Rc_Rx_Cec_EnableIrq() enables interrupt of CEC RX mode and Rc_Rx_Cec_DisableIrq() disables interrupt of CEC RX mode.
Rc_Rx_Cec_ReadData() reads the data received in CEC mode.
CEC mode of Remote Control Transmission:
Rc_Tx_Cec_Init() configures the Remote Control Transmission to CEC mode and Rc_Tx_Cec_DeInit() reset the Remote Control Transmission.
Rc_Tx_Cec_EnableTx() enables trasmission of CEC mode in Remote Control trasmission. Rc_Rx_Cec_DisableTx() disables trasmission of CEC mode.
Rc_Rx_Cec_GetIrqFlag() gets the interrupt flag of CEC mode. And Rc_Rx_Cec_ClrIrqFlag() clears the interrupt flag of CEC mode.
Interrupts can be configured in Rc_Tx_Cec_Init() first, after initialization, Rc_Rx_Cec_EnableIrq() enables interrupt of CEC TX mode and Rc_Rx_Cec_DisableIrq() disables interrupt of CEC TX mode.
Rc_Tx_GetAckCycleValue() gets the ACK cycle value in CEC TX mode.
Rc_Tx_Cec_WriteData() writes data specified with parameter to data buffer CEC TX mode.
Rc_Tx_Cec_SendDataPolling() is a high level API, which can write a data frame with CEC format using polling mode.
Define Documentation
#define RC0 (*((volatile stc_rcn_t *) FM_HDMICEC0_BASE))
Definition at line 200 of file rc.h.
#define RC1 (*((volatile stc_rcn_t *) FM_HDMICEC1_BASE))
Definition at line 201 of file rc.h.
#define RC_INSTANCE_COUNT
Value:
(uint8_t)(PDL_PERIPHERAL_ENABLE_RC0 == PDL_ON) + \
        (uint8_t)(PDL_PERIPHERAL_ENABLE_RC1 == PDL_ON)
Definition at line 203 of file rc.h.
Referenced by RcGetInternDataPtr().
#define stc_rcn_t FM_HDMICEC_TypeDef
Definition at line 199 of file rc.h.
Typedef Documentation
typedef enum en_rc_instance_index en_rc_instance_index_t
Enumeration to define an index for each enabled RC instance.
typedef enum en_rc_mode en_rc_mode_t
RC mode setting.
typedef enum en_rc_overflow en_rc_overflow_t
RC overflow type.
typedef enum en_rc_rx_cec_irq_sel en_rc_rx_cec_irq_sel_t
Remoter Control Receiver CEC mode interrupt selection enumeration.
typedef enum en_rc_rx_nec_irq_sel en_rc_rx_nec_irq_sel_t
Remoter Control Receiver NEC mode interrupt selection enumeration.
typedef enum en_rc_rx_sircs_irq_sel en_rc_rx_sircs_irq_sel_t
Remoter Control Receiver SIRCS mode interrupt selection enumeration.
typedef enum en_rc_src_clk en_rc_src_clk_t
RC CLK.
typedef enum en_rc_threshold_type en_rc_threshold_type_t
RC threshold type.
typedef enum en_rc_tx_cec_irq_sel en_rc_tx_cec_irq_sel_t
Remoter Control Transmission interrupt selection.
typedef enum en_rc_txdata_type en_rc_txdata_type_t
Remoter Control Transmission data type.
typedef struct rc_rx_nec_data rc_rx_nec_data_t
Remoter Control Receiver NEC data format.
typedef struct rc_rx_sircs_data rc_rx_sircs_data_t
Remoter Control Receiver SIRCS data format.
typedef struct stc_rc_instance_data stc_rc_instance_data_t
RC instance data type.
typedef struct stc_rc_intern_data stc_rc_intern_data_t
Intern data structure.
typedef struct stc_rc_rx_addr stc_rc_rx_addr_t
Remoter Control Receiver address structure.
typedef struct stc_rc_rx_cec_config stc_rc_rx_cec_config_t
Remoter Control Receiver CEC mode configuration.
typedef struct stc_rc_rx_cec_irq_cb stc_rc_rx_cec_irq_cb_t
Remoter Control Receiver CEC mode interrupt callback functions.
typedef struct stc_rc_rx_cec_irq_en stc_rc_rx_cec_irq_en_t
Remoter Control Receiver CEC mode interrupt enable structure.
typedef struct stc_rc_rx_nec_config stc_rc_rx_nec_config_t
Remoter Control Receiver NEC mode configuration.
typedef struct stc_rc_rx_nec_irq_cb stc_rc_rx_nec_irq_cb_t
Remoter Control Receiver NEC mode interrupt callback functions.
typedef struct stc_rc_rx_nec_irq_en stc_rc_rx_nec_irq_en_t
Remoter Control Receiver NEC mode interrupt enable structure.
typedef struct stc_rc_rx_sircs_config stc_rc_rx_sircs_config_t
Remoter Control Receiver SIRCS mode configuration.
typedef struct stc_rc_rx_sircs_irq_cb stc_rc_rx_sircs_irq_cb_t
Remoter Control Receiver SIRCS mode interrupt callback function.
typedef struct stc_rc_rx_sircs_irq_en stc_rc_rx_sircs_irq_en_t
Remoter Control Receiver SIRCS mode interrupt enable structure.
typedef struct stc_rc_tx_cec_config stc_rc_tx_cec_config_t
Remoter Control Receiver CEC mode configuration.
typedef struct stc_rc_tx_irq_cb stc_rc_tx_cec_irq_cb_t
Remoter Control Transmission interrupt callback function.
typedef struct stc_rc_tx_cec_irq_en stc_rc_tx_cec_irq_en_t
Remoter Control Transmission interrupt enable structure.
Enumeration Type Documentation
enum en_rc_instance_index
Enumeration to define an index for each enabled RC instance.
Enumerator:
RcInstanceIndexRc0
RcInstanceIndexRc1
RcInstanceIndexMax
Definition at line 555 of file rc.h.
enum en_rc_mode
RC mode setting.
Enumerator:
RcSircsMode
SIRCS mode.
RcSettingProh
Setting Prohibited.
RcNecMode
NEC/Association for electric home appliance mode.
RcCecMode
HDIM-CEC mode.
Definition at line 214 of file rc.h.
enum en_rc_overflow
RC overflow type.
Enumerator:
RcOverflow128Cycle
An overflow will occur after the counter counted 128 clocks.
RcOverflow256Cycle
An overflow will occur after the counter counted 256 clocks.
Definition at line 246 of file rc.h.
enum en_rc_rx_cec_irq_sel
Remoter Control Receiver CEC mode interrupt selection enumeration.
Enumerator:
RcRxCecStartIrq
CEC mode start bit detection interrupt.
RcRxCecAckIrq
CEC mode ACK detection interrupt.
RcRxCecCntOvfIrq
CEC mode counter overflow interrupt.
RcRxCecMinDataIrq
CEC mode Minimum data bit width violation detection.
RcRxCecMaxDataIrq
CEC mode Maximum data bit width violation detection.
Definition at line 354 of file rc.h.
enum en_rc_rx_nec_irq_sel
Remoter Control Receiver NEC mode interrupt selection enumeration.
Enumerator:
RcRxNecStartIrq
NEC mode start bit detection interrupt.
RcRxNecAckIrq
NEC mode ACK detection interrupt.
RcRxNecCntOvfIrq
NEC mode counter overflow interrupt.
RcRxNecRepeatCodeIrq
NEC mode repeat code interrupt.
Definition at line 314 of file rc.h.
enum en_rc_rx_sircs_irq_sel
Remoter Control Receiver SIRCS mode interrupt selection enumeration.
Enumerator:
RcRxSircsStartIrq
SIRCS mode start bit detection interrupt.
RcRxSircsAckIrq
SIRCS mode ACK detection interrupt.
RcRxSircsCntOvfIrq
SIRCS mode RX counter overflow interrupt.
Definition at line 278 of file rc.h.
enum en_rc_src_clk
RC CLK.
Enumerator:
RcPeripheralClk
Use peripheral clock as Remoter Control clock.
RcSubClk
Use sub clock as Remoter Control clock.
Definition at line 226 of file rc.h.
enum en_rc_threshold_type
RC threshold type.
Enumerator:
RcThresholdType0
RC threshold type 0.
RcThresholdType1
RC threshold type 1.
Definition at line 236 of file rc.h.
enum en_rc_tx_cec_irq_sel
Remoter Control Transmission interrupt selection.
Enumerator:
RcTxCecBusErrorIrq
Remoter Control CEC TX bus error interrupt.
RcTxCecTransStausIrq
Remoter Control CEC TX transfer status interrupt.
Definition at line 394 of file rc.h.
enum en_rc_txdata_type
Remoter Control Transmission data type.
Enumerator:
RcTxCecHeader
Header block transmission.
RcTxCecData
Data block.
RcTxCecPolling
Header block transmission.
RcTxCecFinal
Final data block.
Definition at line 382 of file rc.h.
Function Documentation
en_result_t Rc_Rx_Cec_ClrEomState (volatile FM_HDMICEC_TypeDef * pstcRc)
clear EOM state of Remote Control Reception with CEC mode
This function reads the data from data buffer in CEC mode
Parameters:
[in] pstcRc RC instance
Return values:
True that's end of data
Flase that isn't end of data
Definition at line 1713 of file rc.c.
en_result_t Rc_Rx_Cec_ClrIrqFlag (volatile FM_HDMICEC_TypeDef * pstcRc, en_rc_rx_cec_irq_sel_t enIrqSel)
Clear interrupt flag of Remote Control Reception with CEC mode.
This function clears the interrupt flag status of CEC mode
Parameters:
[in] pstcRc RC instance
[in] enIrqSel RC Reception CEC mode interrupt types
Return values:
Ok The interrupt flag selected is clear normally
ErrorInvalidParameter If one of following cases matchs:
NULL == pstcRc
Other invalid configuration
Definition at line 1627 of file rc.c.
References RcRxCecAckIrq, RcRxCecCntOvfIrq, RcRxCecMaxDataIrq, RcRxCecMinDataIrq, and RcRxCecStartIrq.
en_result_t Rc_Rx_Cec_DeInit (volatile FM_HDMICEC_TypeDef * pstcRc, boolean_t bTouchNvic)
De-Initialize CEC mode of Remote Control Reception.
This function deinitializes an Remote Control Reception with CEC mode
Parameters:
[in] pstcRc RC instance
[in] bTouchNvic Touch NVIC or not
Return values:
Ok RC instance with CEC mode de-initialized
ErrorInvalidParameter pstcRc == NULL
Definition at line 1368 of file rc.c.
References stc_rc_intern_data::pfnRcRxAckIrqCb, stc_rc_intern_data::pfnRcRxCntOvfIrqCb, stc_rc_intern_data::pfnRcRxMaxDataIrqCb, stc_rc_intern_data::pfnRcRxMinDataIrqCb, stc_rc_intern_data::pfnRcRxStartIrqCb, RcDeInitNvic(), and RcGetInternDataPtr().
en_result_t Rc_Rx_Cec_DisableIrq (volatile FM_HDMICEC_TypeDef * pstcRc, en_rc_rx_cec_irq_sel_t enIrqSel)
Disable interrupt of Remote Control Reception with CEC mode.
This function disable the interrupt selected of Remote Control Reception CEC mode
Parameters:
[in] pstcRc RC instance
[in] enIrqSel RC Reception CEC mode interrupt types
Return values:
Ok Interrupt disabled normally
ErrorInvalidParameter If one of following cases matchs:
pstcRc == NULL
Other invalid configuration
Definition at line 1539 of file rc.c.
References RcRxCecAckIrq, RcRxCecCntOvfIrq, RcRxCecMaxDataIrq, RcRxCecMinDataIrq, and RcRxCecStartIrq.
en_result_t Rc_Rx_Cec_DisableRx (volatile FM_HDMICEC_TypeDef * pstcRc)
Disable CEC mode reception of Remote Control Reception.
This function disables reception funciton of CEC mode
Parameters:
[in] pstcRc RC instance
Return values:
Ok CEC mode reception disabled normally
ErrorInvalidParameter pstcRc == NULL
Definition at line 1461 of file rc.c.
en_result_t Rc_Rx_Cec_EnableIrq (volatile FM_HDMICEC_TypeDef * pstcRc, en_rc_rx_cec_irq_sel_t enIrqSel)
Enable interrupt of Remote Control Reception with CEC mode.
This function enable the interrupt selected of Remote Control Reception CEC mode
Parameters:
[in] pstcRc RC instance
[in] enIrqSel RC Reception CEC mode interrupt types
Return values:
Ok Interrupt enabled normally
ErrorInvalidParameter If one of following cases matchs:
pstcRc == NULL
Other invalid configuration
Definition at line 1491 of file rc.c.
References RcRxCecAckIrq, RcRxCecCntOvfIrq, RcRxCecMaxDataIrq, RcRxCecMinDataIrq, and RcRxCecStartIrq.
en_result_t Rc_Rx_Cec_EnableRx (volatile FM_HDMICEC_TypeDef * pstcRc)
Enable CEC mode reception of Remote Control Reception.
This function enables reception funciton of CEC mode
Parameters:
[in] pstcRc RC instance
Return values:
Ok CEC mode reception enabled normally
ErrorInvalidParameter pstcRc == NULL
Definition at line 1437 of file rc.c.
boolean_t Rc_Rx_Cec_GetEomState (volatile FM_HDMICEC_TypeDef * pstcRc)
Get EOM state of Remote Control Reception with CEC mode.
This function reads the data from data buffer in CEC mode
Parameters:
[in] pstcRc RC instance
Return values:
True that's end of data
Flase that isn't end of data
Definition at line 1692 of file rc.c.
boolean_t Rc_Rx_Cec_GetIrqFlag (volatile FM_HDMICEC_TypeDef * pstcRc, en_rc_rx_cec_irq_sel_t enIrqSel)
Get interrupt flag of Remote Control Reception with CEC mode.
This function gets the interrupt flag status of CEC mode
Parameters:
[in] pstcRc RC instance
[in] enIrqSel RC Reception CEC mode interrupt types
Return values:
TRUE The interrupt flag selected is set
ErrorInvalidParameter The interrupt flag selected is clear
Definition at line 1586 of file rc.c.
References RcRxCecAckIrq, RcRxCecCntOvfIrq, RcRxCecMaxDataIrq, RcRxCecMinDataIrq, and RcRxCecStartIrq.
en_result_t Rc_Rx_Cec_Init (volatile FM_HDMICEC_TypeDef * pstcRc, stc_rc_rx_cec_config_t * pstcRcCecConfig)
Initialize CEC mode of Remote Control Reception.
This function initializes CEC mode of an Remote Control Reception
Parameters:
[in] pstcRc RC instance
[in] pstcRcCecConfig Pointer to CEC mode configuration
Return values:
Ok CEC mode initialized normally
ErrorInvalidParameter If one of following cases matchs:
pstcRc == NULL
pstcRcCecConfig == NULL
Other invalid configuration
Definition at line 1214 of file rc.c.
References stc_rc_rx_cec_config::bAddrCmpEn, stc_rc_rx_cec_config::bBusErrorPulseOutput, stc_rc_rx_cec_irq_en::bRcRxCecAckIrq, stc_rc_rx_cec_irq_en::bRcRxCecCntOvfIrq, stc_rc_rx_cec_irq_en::bRcRxCecMaxDataIrq, stc_rc_rx_cec_irq_en::bRcRxCecMinDataIrq, stc_rc_rx_cec_irq_en::bRcRxCecStartIrq, stc_rc_rx_cec_config::bTouchNvic, stc_rc_rx_cec_config::enOverflowCycle, stc_rc_rx_cec_config::enSrcClk, stc_rc_rx_cec_config::enThresholdType, stc_rc_intern_data::pfnRcRxAckIrqCb, stc_rc_rx_cec_irq_cb::pfnRcRxCecAckIrqCb, stc_rc_rx_cec_irq_cb::pfnRcRxCecCntOvfIrqCb, stc_rc_rx_cec_irq_cb::pfnRcRxCecMaxDataIrqCb, stc_rc_rx_cec_irq_cb::pfnRcRxCecMinDataIrqCb, stc_rc_rx_cec_irq_cb::pfnRcRxCecStartIrqCb, stc_rc_intern_data::pfnRcRxCntOvfIrqCb, stc_rc_intern_data::pfnRcRxMaxDataIrqCb, stc_rc_intern_data::pfnRcRxMinDataIrqCb, stc_rc_intern_data::pfnRcRxStartIrqCb, stc_rc_rx_cec_config::pstcIrqCb, stc_rc_rx_cec_config::pstcIrqEn, RcCecMode, RcGetInternDataPtr(), RcInitNvic(), RcOverflow128Cycle, RcOverflow256Cycle, RcPeripheralClk, RcSubClk, RcThresholdType0, RcThresholdType1, stc_rc_rx_cec_config::stcAddr, stc_rc_rx_cec_config::u16DivVal, stc_rc_rx_addr::u8Addr1, stc_rc_rx_addr::u8Addr2, stc_rc_rx_cec_config::u8MaxDataWidth, stc_rc_rx_cec_config::u8MinDataWidth, stc_rc_rx_cec_config::u8MinPulseWidth, stc_rc_rx_cec_config::u8StartBitWidth, and stc_rc_rx_cec_config::u8ThresholdWidth.
uint8_t Rc_Rx_Cec_ReadData (volatile FM_HDMICEC_TypeDef * pstcRc)
Get data of Remote Control Reception with CEC mode.
This function reads the data from data buffer in CEC mode
Parameters:
[in] pstcRc RC instance
Return values:
CEC data CEC data
Definition at line 1670 of file rc.c.
en_result_t Rc_Rx_Nec_ClrIrqFlag (volatile FM_HDMICEC_TypeDef * pstcRc, en_rc_rx_nec_irq_sel_t enIrqSel)
Clear interrupt flag of Remote Control Reception with NEC mode.
This function clears the interrupt flag status of NEC mode
Parameters:
[in] pstcRc RC instance
[in] enIrqSel RC Reception SIRCS mode interrupt types
Return values:
Ok The interrupt flag selected is clear normally
ErrorInvalidParameter If one of following cases matchs:
NULL == pstcRc
Other invalid configuration
Definition at line 1137 of file rc.c.
References RcRxNecAckIrq, RcRxNecCntOvfIrq, RcRxNecRepeatCodeIrq, and RcRxNecStartIrq.
en_result_t Rc_Rx_Nec_DeInit (volatile FM_HDMICEC_TypeDef * pstcRc, boolean_t bTouchNvic)
De-Initialize NEC mode of Remote Control Reception.
This function deinitializes an Remote Control Reception with NEC mode
Parameters:
[in] pstcRc RC instance
[in] bTouchNvic Touch NVIC or not
Return values:
Ok RC instance with NEC mode de-initialized
ErrorInvalidParameter pstcRc == NULL
Definition at line 888 of file rc.c.
References stc_rc_intern_data::pfnRcRxAckIrqCb, stc_rc_intern_data::pfnRcRxCntOvfIrqCb, stc_rc_intern_data::pfnRcRxRepeatCodeIrqCb, stc_rc_intern_data::pfnRcRxStartIrqCb, RcDeInitNvic(), and RcGetInternDataPtr().
en_result_t Rc_Rx_Nec_DisableIrq (volatile FM_HDMICEC_TypeDef * pstcRc, en_rc_rx_nec_irq_sel_t enIrqSel)
Disable interrupt of Remote Control Reception with NEC mode.
This function disable the interrupt selected of Remote Control Reception NEC mode
Parameters:
[in] pstcRc RC instance
[in] enIrqSel RC Reception NEC mode interrupt types
Return values:
Ok Interrupt disabled normally
ErrorInvalidParameter If one of following cases matchs:
pstcRc == NULL
Other invalid configuration
Definition at line 1055 of file rc.c.
References RcRxNecAckIrq, RcRxNecCntOvfIrq, RcRxNecRepeatCodeIrq, and RcRxNecStartIrq.
en_result_t Rc_Rx_Nec_DisableRx (volatile FM_HDMICEC_TypeDef * pstcRc)
Disable NEC mode reception of Remote Control Reception.
This function disables reception funciton of NEC mode
Parameters:
[in] pstcRc RC instance
Return values:
Ok NEC mode reception disabled normally
ErrorInvalidParameter pstcRc == NULL
Definition at line 980 of file rc.c.
en_result_t Rc_Rx_Nec_EnableIrq (volatile FM_HDMICEC_TypeDef * pstcRc, en_rc_rx_nec_irq_sel_t enIrqSel)
Enable interrupt of Remote Control Reception with NEC mode.
This function enable the interrupt selected of Remote Control Reception NEC mode
Parameters:
[in] pstcRc RC instance
[in] enIrqSel RC Reception NEC mode interrupt types
Return values:
Ok Interrupt enabled normally
ErrorInvalidParameter If one of following cases matchs:
pstcRc == NULL
Other invalid configuration
Definition at line 1010 of file rc.c.
References RcRxNecAckIrq, RcRxNecCntOvfIrq, RcRxNecRepeatCodeIrq, and RcRxNecStartIrq.
en_result_t Rc_Rx_Nec_EnableRx (volatile FM_HDMICEC_TypeDef * pstcRc)
Enable NEC mode reception of Remote Control Reception.
This function enables reception funciton of NEC mode
Parameters:
[in] pstcRc RC instance
Return values:
Ok NEC mode reception enabled normally
ErrorInvalidParameter pstcRc == NULL
Definition at line 956 of file rc.c.
boolean_t Rc_Rx_Nec_GetIrqFlag (volatile FM_HDMICEC_TypeDef * pstcRc, en_rc_rx_nec_irq_sel_t enIrqSel)
Get interrupt flag of Remote Control Reception with NEC mode.
This function gets the interrupt flag status of NEC mode
Parameters:
[in] pstcRc RC instance
[in] enIrqSel RC Reception NEC mode interrupt types
Return values:
TRUE The interrupt flag selected is set
ErrorInvalidParameter The interrupt flag selected is clear
Definition at line 1099 of file rc.c.
References RcRxNecAckIrq, RcRxNecCntOvfIrq, RcRxNecRepeatCodeIrq, and RcRxNecStartIrq.
en_result_t Rc_Rx_Nec_Init (volatile FM_HDMICEC_TypeDef * pstcRc, stc_rc_rx_nec_config_t * pstcRcNecConfig)
Initialize NEC mode of Remote Control Reception.
This function initializes NEC mode of an Remote Control Reception
Parameters:
[in] pstcRc RC instance
[in] pstcRcNecConfig Pointer to NEC mode configuration
Return values:
Ok NEC mode initialized normally
ErrorInvalidParameter If one of following cases matchs:
pstcRc == NULL
pstcRcNecConfig == NULL
Other invalid configuration
Definition at line 755 of file rc.c.
References stc_rc_rx_nec_config::bAddrCmpEn, stc_rc_rx_nec_irq_en::bRcRxNecAckIrq, stc_rc_rx_nec_irq_en::bRcRxNecCntOvfIrq, stc_rc_rx_nec_irq_en::bRcRxNecRepeatCodeIrq, stc_rc_rx_nec_irq_en::bRcRxNecStartIrq, stc_rc_rx_nec_config::bTouchNvic, stc_rc_rx_nec_config::enOverflowCycle, stc_rc_rx_nec_config::enSrcClk, stc_rc_rx_nec_config::enThresholdType, stc_rc_intern_data::pfnRcRxAckIrqCb, stc_rc_intern_data::pfnRcRxCntOvfIrqCb, stc_rc_rx_nec_irq_cb::pfnRcRxNecAckIrqCb, stc_rc_rx_nec_irq_cb::pfnRcRxNecCntOvfIrqCb, stc_rc_rx_nec_irq_cb::pfnRcRxNecRepeatCodeIrqCb, stc_rc_rx_nec_irq_cb::pfnRcRxNecStartIrqCb, stc_rc_intern_data::pfnRcRxRepeatCodeIrqCb, stc_rc_intern_data::pfnRcRxStartIrqCb, stc_rc_rx_nec_config::pstcIrqCb, stc_rc_rx_nec_config::pstcIrqEn, RcGetInternDataPtr(), RcInitNvic(), RcNecMode, RcOverflow128Cycle, RcOverflow256Cycle, RcPeripheralClk, RcSubClk, RcThresholdType0, RcThresholdType1, stc_rc_rx_nec_config::stcAddr, stc_rc_rx_nec_config::u16DivVal, stc_rc_rx_addr::u8Addr1, stc_rc_rx_addr::u8Addr2, stc_rc_rx_nec_config::u8MinPulseWidth, stc_rc_rx_nec_config::u8StartBitWidth, and stc_rc_rx_nec_config::u8ThresholdWidth.
en_result_t Rc_Rx_Nec_ReadData (volatile FM_HDMICEC_TypeDef * pstcRc, rc_rx_nec_data_t * pstcData)
Get data of Remote Control Reception with NEC mode.
This function reads the data from data buffer in NEC mode
Parameters:
[in] pstcRc RC instance
[in] pstcData Poitner to NEC mode data structure
Return values:
Ok Data is read normally
ErrorInvalidParameter NULL == pstcRc
Definition at line 1179 of file rc.c.
References rc_rx_nec_data::u16CustomCode, rc_rx_nec_data::u8Data0, and rc_rx_nec_data::u8Data1.
en_result_t Rc_Rx_Sircs_ClrIrqFlag (volatile FM_HDMICEC_TypeDef * pstcRc, en_rc_rx_sircs_irq_sel_t enIrqSel)
Clear interrupt flag of Remote Control Reception with SIRCS mode.
This function clears the interrupt flag status of SIRCS mode
Parameters:
[in] pstcRc RC instance
[in] enIrqSel RC Reception SIRCS mode interrupt types
Return values:
Ok The interrupt flag selected is clear normally
ErrorInvalidParameter If one of following cases matchs:
NULL == pstcRc
Other invalid configuration
Definition at line 682 of file rc.c.
References RcRxSircsAckIrq, RcRxSircsCntOvfIrq, and RcRxSircsStartIrq.
en_result_t Rc_Rx_Sircs_DeInit (volatile FM_HDMICEC_TypeDef * pstcRc, boolean_t bTouchNvic)
De-Initialize SIRCS mode of Remote Control Reception.
This function deinitializes an SRemote Control Reception with IRCS mode
Parameters:
[in] pstcRc RC instance
[in] bTouchNvic Touch NVIC or not
Return values:
Ok RC instance fully disabled and reset
ErrorInvalidParameter pstcRc == NULL
Definition at line 449 of file rc.c.
References stc_rc_intern_data::pfnRcRxAckIrqCb, stc_rc_intern_data::pfnRcRxCntOvfIrqCb, stc_rc_intern_data::pfnRcRxStartIrqCb, RcDeInitNvic(), and RcGetInternDataPtr().
en_result_t Rc_Rx_Sircs_DisableIrq (volatile FM_HDMICEC_TypeDef * pstcRc, en_rc_rx_sircs_irq_sel_t enIrqSel)
Disable interrupt of Remote Control Reception with SIRCS mode.
This function disable the interrupt selected of Remote Control Reception SIRCS mode
Parameters:
[in] pstcRc RC instance
[in] enIrqSel RC Reception SIRCS mode interrupt types
Return values:
Ok Interrupt disabled normally
ErrorInvalidParameter If one of following cases matchs:
pstcRc == NULL
Other invalid configuration
Definition at line 606 of file rc.c.
References RcRxSircsAckIrq, RcRxSircsCntOvfIrq, and RcRxSircsStartIrq.
en_result_t Rc_Rx_Sircs_DisableRx (volatile FM_HDMICEC_TypeDef * pstcRc)
Disable SIRCS mode reception of Remote Control Reception.
This function disables reception funciton of SIRCS mode
Parameters:
[in] pstcRc RC instance
Return values:
Ok SIRCS mode reception disabled normally
ErrorInvalidParameter pstcRc == NULL
Definition at line 534 of file rc.c.
en_result_t Rc_Rx_Sircs_EnableIrq (volatile FM_HDMICEC_TypeDef * pstcRc, en_rc_rx_sircs_irq_sel_t enIrqSel)
Enable interrupt of Remote Control Reception with SIRCS mode.
This function enable the interrupt selected of Remote Control Reception SIRCS mode
Parameters:
[in] pstcRc RC instance
[in] enIrqSel RC Reception SIRCS mode interrupt types
Return values:
Ok Interrupt enabled normally
ErrorInvalidParameter If one of following cases matchs:
pstcRc == NULL
Other invalid configuration
Definition at line 564 of file rc.c.
References RcRxSircsAckIrq, RcRxSircsCntOvfIrq, and RcRxSircsStartIrq.
en_result_t Rc_Rx_Sircs_EnableRx (volatile FM_HDMICEC_TypeDef * pstcRc)
Enable SIRCS mode reception of Remote Control Reception.
This function enables reception funciton of SIRCS mode
Parameters:
[in] pstcRc RC instance
Return values:
Ok SIRCS mode reception enabled normally
ErrorInvalidParameter pstcRc == NULL
Definition at line 510 of file rc.c.
boolean_t Rc_Rx_Sircs_GetIrqFlag (volatile FM_HDMICEC_TypeDef * pstcRc, en_rc_rx_sircs_irq_sel_t enIrqSel)
Get interrupt flag of Remote Control Reception with SIRCS mode.
This function gets the interrupt flag status of SIRCS mode
Parameters:
[in] pstcRc RC instance
[in] enIrqSel RC Reception SIRCS mode interrupt types
Return values:
TRUE The interrupt flag selected is set
ErrorInvalidParameter The interrupt flag selected is clear
Definition at line 647 of file rc.c.
References RcRxSircsAckIrq, RcRxSircsCntOvfIrq, and RcRxSircsStartIrq.
en_result_t Rc_Rx_Sircs_Init (volatile FM_HDMICEC_TypeDef * pstcRc, stc_rc_rx_sircs_config_t * pstcRcSircsConfig)
Initialize SIRCS mode of Remote Control Reception.
This function initializes SIRCS mode of an Remote Control Reception
Parameters:
[in] pstcRc RC instance
[in] pstcRcSircsConfig Pointer to SIRCS mode configuration
Return values:
Ok SIRCS mode initialized normally
ErrorInvalidParameter pstcRc == NULL pstcRcSircsConfig == NULL Other invalid configuration
Definition at line 321 of file rc.c.
References stc_rc_rx_sircs_config::bAddrCmpEn, stc_rc_rx_sircs_irq_en::bRcRxSircsAckIrq, stc_rc_rx_sircs_irq_en::bRcRxSircsCntOvfIrq, stc_rc_rx_sircs_irq_en::bRcRxSircsStartIrq, stc_rc_rx_sircs_config::bTouchNvic, stc_rc_rx_sircs_config::enOverflowCycle, stc_rc_rx_sircs_config::enSrcClk, stc_rc_rx_sircs_config::enThresholdType, stc_rc_intern_data::pfnRcRxAckIrqCb, stc_rc_intern_data::pfnRcRxCntOvfIrqCb, stc_rc_rx_sircs_irq_cb::pfnRcRxSircsAckIrqCb, stc_rc_rx_sircs_irq_cb::pfnRcRxSircsCntOvfIrqCb, stc_rc_rx_sircs_irq_cb::pfnRcRxSircsStartIrqCb, stc_rc_intern_data::pfnRcRxStartIrqCb, stc_rc_rx_sircs_config::pstcIrqCb, stc_rc_rx_sircs_config::pstcIrqEn, RcGetInternDataPtr(), RcInitNvic(), RcOverflow128Cycle, RcOverflow256Cycle, RcPeripheralClk, RcSircsMode, RcSubClk, RcThresholdType0, RcThresholdType1, stc_rc_rx_sircs_config::stcAddr, stc_rc_rx_sircs_config::u16DivVal, stc_rc_rx_addr::u8Addr1, stc_rc_rx_addr::u8Addr2, stc_rc_rx_sircs_config::u8MinPulseWidth, stc_rc_rx_sircs_config::u8StartBitWidth, and stc_rc_rx_sircs_config::u8ThresholdWidth.
en_result_t Rc_Rx_Sircs_ReadData (volatile FM_HDMICEC_TypeDef * pstcRc, rc_rx_sircs_data_t * pstcData)
Get data of Remote Control Reception with SIRCS mode.
This function reads the data from data buffer in SIRCS mode
Parameters:
[in] pstcRc RC instance
[in] pstcData Poitner to SIRCS mode data structure
Return values:
Ok Data is read normally
ErrorInvalidParameter NULL == pstcRc
Definition at line 721 of file rc.c.
References rc_rx_sircs_data::u8Command, rc_rx_sircs_data::u8Data0, rc_rx_sircs_data::u8Data1, and rc_rx_sircs_data::u8DeviceAddress.
en_result_t Rc_Tx_Cec_ClrIrqFlag (volatile FM_HDMICEC_TypeDef * pstcRc, en_rc_tx_cec_irq_sel_t enIrqSel)
Clear interrupt flag of Remote Control Transmission with CEC mode.
This function clears the interrupt flag status of CEC mode
Parameters:
[in] pstcRc RC instance
[in] enIrqSel RC Reception CEC mode interrupt types
Return values:
Ok The interrupt flag selected is clear normally
ErrorInvalidParameter If one of following cases matchs:
NULL == pstcRc
Other invalid configuration
Definition at line 2042 of file rc.c.
References RcTxCecBusErrorIrq, and RcTxCecTransStausIrq.
en_result_t Rc_Tx_Cec_DeInit (volatile FM_HDMICEC_TypeDef * pstcRc, boolean_t bTouchNvic)
De-Initialize CEC mode of Remote Control transmission.
This function deinitializes an Remote Control transmission with CEC mode
Parameters:
[in] pstcRc RC instance
[in] bTouchNvic Touch NVIC or not
Return values:
Ok RC instance with CEC mode de-initialized
ErrorInvalidParameter pstcRc == NULL
Definition at line 1831 of file rc.c.
References stc_rc_intern_data::pfnRcTxIrqBusErrorCb, stc_rc_intern_data::pfnRcTxIrqStatusCb, RcDeInitNvic(), and RcGetInternDataPtr().
en_result_t Rc_Tx_Cec_DisableIrq (volatile FM_HDMICEC_TypeDef * pstcRc, en_rc_tx_cec_irq_sel_t enIrqSel)
Disable CEC mode interrupt of Remote Control transmision.
This function disables transfer interrupt of CEC mode
Parameters:
[in] pstcRc RC instance
[in] enIrqSel Interrupt type
Return values:
Ok CEC mode transmision interrupt disabled normally
ErrorInvalidParameter pstcRc == NULL
Definition at line 1971 of file rc.c.
References RcTxCecBusErrorIrq, and RcTxCecTransStausIrq.
en_result_t Rc_Tx_Cec_DisableTx (volatile FM_HDMICEC_TypeDef * pstcRc)
Disable CEC mode transfer of Remote Control transmision.
This function disables transfer funciton of CEC mode
Parameters:
[in] pstcRc RC instance
Return values:
Ok CEC mode transmision disabled normally
ErrorInvalidParameter pstcRc == NULL
Definition at line 1908 of file rc.c.
en_result_t Rc_Tx_Cec_EnableIrq (volatile FM_HDMICEC_TypeDef * pstcRc, en_rc_tx_cec_irq_sel_t enIrqSel)
Enable CEC mode interrupt of Remote Control transmision.
This function enables transfer interrupt of CEC mode
Parameters:
[in] pstcRc RC instance
[in] enIrqSel Interrupt type
Return values:
Ok CEC mode transmision interrupt enabled normally
ErrorInvalidParameter pstcRc == NULL
Definition at line 1935 of file rc.c.
References RcTxCecBusErrorIrq, and RcTxCecTransStausIrq.
en_result_t Rc_Tx_Cec_EnableTx (volatile FM_HDMICEC_TypeDef * pstcRc)
Enable CEC mode transfer of Remote Control transmision.
This function enables transfer funciton of CEC mode
Parameters:
[in] pstcRc RC instance
Return values:
Ok CEC mode transmision enabled normally
ErrorInvalidParameter pstcRc == NULL
Definition at line 1884 of file rc.c.
boolean_t Rc_Tx_Cec_GetIrqFlag (volatile FM_HDMICEC_TypeDef * pstcRc, en_rc_tx_cec_irq_sel_t enIrqSel)
Get interrupt flag of Remote Control transmission with CEC mode.
This function gets the interrupt flag status of CEC mode
Parameters:
[in] pstcRc RC instance
[in] enIrqSel RC Reception CEC mode interrupt types
Return values:
TRUE The interrupt flag selected is set
ErrorInvalidParameter The interrupt flag selected is clear
Definition at line 2008 of file rc.c.
References RcTxCecBusErrorIrq, and RcTxCecTransStausIrq.
en_result_t Rc_Tx_Cec_Init (volatile FM_HDMICEC_TypeDef * pstcRc, stc_rc_tx_cec_config_t * pstcRcTxConfig)
Initialize CEC mode of Remote Control transmission.
This function initializes CEC mode of an Remote Control transmission
Parameters:
[in] pstcRc RC instance
[in] pstcRcTxConfig Pointer to TX CEC mode configuration
Return values:
Ok CEC mode initialized normally
ErrorInvalidParameter If one of following cases matchs:
pstcRc == NULL
pstcRcTxConfig == NULL
Other invalid configuration
Definition at line 1740 of file rc.c.
References stc_rc_tx_cec_irq_en::bRcTxCecBusErrorIrq, stc_rc_tx_cec_irq_en::bRcTxCecStatusIrq, stc_rc_tx_cec_config::bTouchNvic, stc_rc_tx_cec_config::enSrcClk, stc_rc_tx_irq_cb::pfnRcTxIrqBusErrorCb, stc_rc_intern_data::pfnRcTxIrqBusErrorCb, stc_rc_intern_data::pfnRcTxIrqStatusCb, stc_rc_tx_irq_cb::pfnRcTxIrqTxStatusCb, stc_rc_tx_cec_config::pstcIrqCb, stc_rc_tx_cec_config::pstcIrqEn, RcGetInternDataPtr(), RcInitNvic(), RcPeripheralClk, RcSubClk, stc_rc_tx_cec_config::u16DivVal, and stc_rc_tx_cec_config::u8FreeCycle.
en_result_t Rc_Tx_Cec_SendDataPolling (volatile FM_HDMICEC_TypeDef * pstcRc, uint8_t u8Header, uint8_t * pu8Data, uint32_t u32Size)
Write CEC data package with polling mode for CEC TX mode.
This function writes a CEC data frame with polling mode
Parameters:
[in] pstcRc RC instance
[in] u8Header Data header
[in] pu8Data Pointer to data to be written
[in] u32Size Data size
Return values:
Ok Data is written
ErrorInvalidParameter pstcRc == NULL or other invalid configuration
Definition at line 2146 of file rc.c.
en_result_t Rc_Tx_Cec_WriteData (volatile FM_HDMICEC_TypeDef * pstcRc, uint8_t u8Data, en_rc_txdata_type_t enType)
Write data into data specified with data type for CEC TX mode.
This function writes the data buffer with data specified
Parameters:
[in] pstcRc RC instance
[in] u8Data Data to be written
[in] enType Remote Control TX data type
Return values:
Ok Data is written
ErrorInvalidParameter pstcRc == NULL or other invalid configuration
Definition at line 2095 of file rc.c.
References RcTxCecData, RcTxCecFinal, RcTxCecHeader, and RcTxCecPolling.
boolean_t Rc_Tx_GetAckCycleValue (volatile FM_HDMICEC_TypeDef * pstcRc)
Get ACK cycle value of Remote Control transmission with CEC mode.
This function gets the ACK cycle value of CEC mode
Parameters:
[in] pstcRc RC instance
Return values:
TRUE ACK cycle value is set
ErrorInvalidParameter ACK cycle value is clear
Definition at line 2077 of file rc.c.
static void RcDeInitNvic (void) [static]
De-Initialize NVIC of Remote Control.
Definition at line 146 of file rc.c.
References PDL_IRQ_LEVEL_CEC.
Referenced by Rc_Rx_Cec_DeInit(), Rc_Rx_Nec_DeInit(), Rc_Rx_Sircs_DeInit(), and Rc_Tx_Cec_DeInit().
static stc_rc_intern_data_t* RcGetInternDataPtr (volatile FM_HDMICEC_TypeDef * pstcRc) [static]
Return the internal data for a certain RC instance.
Parameters:
pstcRc Pointer to RC instance
Returns:
Pointer to internal data or NULL if instance is not enabled (or not known)
Definition at line 287 of file rc.c.
References RC_INSTANCE_COUNT, and stc_rc_instance_data::stcInternData.
Referenced by Rc_Rx_Cec_DeInit(), Rc_Rx_Cec_Init(), Rc_Rx_Nec_DeInit(), Rc_Rx_Nec_Init(), Rc_Rx_Sircs_DeInit(), Rc_Rx_Sircs_Init(), Rc_Tx_Cec_DeInit(), and Rc_Tx_Cec_Init().
static void RcInitNvic (void) [static]
Initialize NVIC of Remote Control.
Definition at line 107 of file rc.c.
References PDL_IRQ_LEVEL_CEC.
Referenced by Rc_Rx_Cec_Init(), Rc_Rx_Nec_Init(), Rc_Rx_Sircs_Init(), and Rc_Tx_Cec_Init().
void RcIrqHandler (volatile FM_HDMICEC_TypeDef * pstcRc, stc_rc_intern_data_t * pstcRcInternData)
RC instance interrupt service routine.
RC instance interrupt service routine, clear interrupt cause and implement interrupt callback function.
Parameters:
pstcRc Pointer to RC instance
pstcRcInternData Pointer to RC intern data
Definition at line 191 of file rc.c.
References stc_rc_intern_data::pfnRcRxAckIrqCb, stc_rc_intern_data::pfnRcRxCntOvfIrqCb, stc_rc_intern_data::pfnRcRxEomCb, stc_rc_intern_data::pfnRcRxMaxDataIrqCb, stc_rc_intern_data::pfnRcRxMinDataIrqCb, stc_rc_intern_data::pfnRcRxRepeatCodeIrqCb, stc_rc_intern_data::pfnRcRxStartIrqCb, stc_rc_intern_data::pfnRcTxIrqBusErrorCb, and stc_rc_intern_data::pfnRcTxIrqStatusCb.
Variable Documentation
stc_rc_instance_data_t m_astcRcInstanceDataLut[(uint8_t)(PDL_PERIPHERAL_ENABLE_RC0==PDL_ON)+(uint8_t)(PDL_PERIPHERAL_ENABLE_RC1==PDL_ON)]
Initial value:
{
    {
        & (*((volatile  FM_HDMICEC_TypeDef  *) FM_HDMICEC0_BASE)) ,
        0u
    },
    {
        & (*((volatile  FM_HDMICEC_TypeDef  *) FM_HDMICEC1_BASE)) ,
        0u
    },
}
Look-up table for all enabled RC instances and their internal data.
Definition at line 73 of file rc.c.
stc_rc_instance_data_t m_astcRcInstanceDataLut[(uint8_t)(PDL_PERIPHERAL_ENABLE_RC0==PDL_ON)+(uint8_t)(PDL_PERIPHERAL_ENABLE_RC1==PDL_ON)]
Look-up table for all enabled RC instances and their internal data.
Definition at line 73 of file rc.c.