PDL for FM Family: Low Power Modes Functions (LPM)
Low Power Modes Functions (LPM)
Data Structures
struct stc_ret_cause
Deep standby mode return cause.
struct stc_backupreg
backup register index
Defines
#define CM_CORE_CSR *((volatile unsigned int*)(0xE000ED10UL))
#define LPCM_BACKUP_REG_BASE ((volatile uint8_t*)0x40035900)
#define PDL_BACK_UP_REGISTERS (32u)
#define WIFSR_WRTCI (1ul<<0u)
#define WIFSR_WLVDI (1ul<<1u)
#define WIFSR_WUI0 (1ul<<2u)
#define WIFSR_WUI1 (1ul<<3u)
#define WIFSR_WUI2 (1ul<<4u)
#define WIFSR_WUI3 (1ul<<5u)
#define WIFSR_WUI4 (1ul<<6u)
#define WIFSR_WUI5 (1ul<<7u)
#define WIFSR_WCEC0I (1ul<<8u)
#define WIFSR_WCEC1I (1ul<<9u)
#define WIFSR_WUI6 (1ul<<10u)
#define WIFSR_WUI7 (1ul<<11u)
#define WIFSR_WUI8 (1ul<<12u)
#define WIFSR_WUI9 (1ul<<13u)
#define WIFSR_WUI10 (1ul<<14u)
#define WIFSR_WUI11 (1ul<<15u)
#define WRFSR_WINITX (1ul<<0u)
#define WRFSR_WLVDH (1ul<<1u)
Typedefs
typedef enum en_lpm_mode en_lpm_mode_t
define standby mode type
typedef struct stc_ret_cause stc_dstb_ret_cause_t
Deep standby mode return cause.
typedef enum en_ret_cause_flag en_dstb_ret_cause_t
define deep standby mode return cause flag
typedef enum en_dstb_wkup_pin en_dstb_wkup_pin_t
define wkup pin index
typedef enum en_wkup_valid_level en_wkup_valid_level_t
Valid level of wakeup pin.
typedef enum
en_lpm_internal_voltage en_lpm_internal_voltage_t
Internal voltage selection in deep standby mode.
typedef enum en_lpm_main_osc en_lpm_main_osc_t
Main oscillator selection types.
typedef enum en_dstb_bakup_reg en_dstb_bakup_reg_t
backup register index
typedef struct stc_backupreg stc_backupreg_t
backup register index
Enumerations
enum en_lpm_mode {
StbSleepMode = 0u, StbTimerMode = 1u, StbStopMode = 2u, StbRtcMode = 3u,
DeepStbRtcMode = 4u, DeepStbStopMode = 5u
}
define standby mode type
enum en_ret_cause_flag {
DeepStbNoFlag = 0u, DeepStbInitx = 1u, DeepStbLvdReset = 2u, DeepStbRtcInt = 3u,
DeepStbLvdInt = 4u, DeepStbWkupPin0 = 5u, DeepStbWkupPin1 = 6u, DeepStbWkupPin2 = 7u,
DeepStbWkupPin3 = 8u, DeepStbWkupPin4 = 9u, DeepStbWkupPin5 = 10u, DeepStbCec0 = 11u,
DeepStbCec1 = 12u, DeepStbWkupPin6 = 13u, DeepStbWkupPin7 = 14u, DeepStbWkupPin8 = 15u,
DeepStbWkupPin9 = 16u, DeepStbWkupPin10 = 17u, DeepStbWkupPin11 = 18u
}
define deep standby mode return cause flag
enum en_dstb_wkup_pin {
WkupPin1 = 0u, WkupPin2 = 1u, WkupPin3 = 2u, WkupPin4 = 3u,
WkupPin5 = 4u, WkupPin6 = 5u, WkupPin7 = 6u, WkupPin8 = 7u,
WkupPin9 = 8u, WkupPin10 = 9u, WkupPin11 = 10u, WkupPinMax
}
define wkup pin index
enum en_wkup_valid_level { WkupLowLevelValid = 0u, WkupHighLevelValid = 1u }
Valid level of wakeup pin.
enum en_lpm_internal_voltage { LpmInternalVoltage120 = 0u, LpmInternalVoltage105 = 1u, LpmInternalVoltage110 = 2u }
Internal voltage selection in deep standby mode.
enum en_lpm_main_osc { LpmMainOsc4M = 0u, LpmMainOsc4M8M = 1u, LpmMainOsc4M8M16M = 2u, LpmMainOsc48M = 3u }
Main oscillator selection types.
enum en_dstb_bakup_reg {
BackupReg1 = 1u, BackupReg2 = 2u, BackupReg3 = 3u, BackupReg4 = 4u,
BackupReg5 = 5u, BackupReg6 = 6u, BackupReg7 = 7u, BackupReg8 = 8u,
BackupReg9 = 9u, BackupReg10 = 10u, BackupReg11 = 11u, BackupReg12 = 12u,
BackupReg13 = 13u, BackupReg14 = 14u, BackupReg15 = 15u, BackupReg16 = 16u
}
backup register index
Functions
static en_result_t ReadBackupRegisters (stc_backupreg_t *stcBackUpReg)
Read Backup Registers.
static en_result_t WriteBackupRegisters (stc_backupreg_t *stcBackUpReg)
Write Backup Registers.
static uint16_t WRFSRDummyRead (void)
WRFSR dummy read.
static uint16_t WIFSRDummyRead (void)
WRFSR dummy read.
void Lpm_GoToStandByMode (en_lpm_mode_t enMode, boolean_t bIoRemain)
go to standby mode
en_result_t Lpm_ConfigDeepStbRetCause (stc_dstb_ret_cause_t *pstcCause)
Configure return cause from deep standby mode.
en_dstb_ret_cause_t Lpm_ReadDeepStbRetCause (void)
Read deep standby mode return cause flag.
en_result_t Lpm_SetWkupPinLevel (en_dstb_wkup_pin_t enPinIndex, en_wkup_valid_level_t enLevel)
Set the valid level of wkup pin.
en_result_t Lpm_ConfigInternalVoltage (en_lpm_internal_voltage_t enVoltage)
Configure the internal voltage in deep standby mode.
en_result_t Lpm_SelMainOscTypes (en_lpm_main_osc_t enMainOsc)
Configure main oscillator types in deep standby mode.
en_result_t Lpm_ConfigFlashPower (boolean_t bPowerOn)
Configure Flash power in deep standby mode.
en_result_t Lpm_ConfigSubClk (boolean_t bSupplyCec, boolean_t bSupplyRtc)
Configue the sub clock supply.
en_result_t Lpm_ConfigDeepStbRAMRetention (boolean_t bRamRetain)
Configure deep standby mode RAM retention.
en_result_t Lpm_WriteBackupReg (en_dstb_bakup_reg_t enRegIndex, uint8_t u8Data)
Write the backup register.
uint8_t Lpm_ReadBackupReg (en_dstb_bakup_reg_t enRegIndex)
Read the backup register.
en_result_t Lpm_Readu8DataBackupRegister (uint8_t u8AddressOffset, uint8_t *u8Data)
Read Backup Register (Byte)
en_result_t Lpm_Writeu8DataBackupRegister (uint8_t u8AddressOffset, uint8_t u8Data)
Write Backup Registers (Byte)
en_result_t Lpm_Readu16DataBackupRegister (uint8_t u8AddressOffset, uint16_t *u16Data)
Read Backup Register (16-Bit)
en_result_t Lpm_Writeu16DataBackupRegister (uint8_t u8AddressOffset, uint16_t u16Data)
Write Backup Registers (16-Bit)
en_result_t Lpm_Readu32DataBackupRegister (uint8_t u8AddressOffset, uint32_t *u32Data)
Read Backup Register (32-Bit)
en_result_t Lpm_Writeu32DataBackupRegister (uint8_t u8AddressOffset, uint32_t u32Data)
Write Backup Registers (32-Bit)
en_result_t Lpm_ReadBackupRegisters (stc_backupreg_t *stcBackUpReg)
en_result_t Lpm_WriteBackupRegisters (stc_backupreg_t *stcBackUpReg)
Detailed Description
Provided functions of LPM module:
Lpm_GoToStandByMode()
Lpm_ConfigDeepStbRetCause()
Lpm_ReadDeepStbRetCause()
Lpm_SetWkupPinLevel()
Lpm_ConfigSubClk()
Lpm_ConfigDeepStbRAMRetention()
Lpm_WriteBackupReg()
Lpm_ReadBackupReg()
Lpm_GoToStandByMode() enters the low power consumption selected by the parameter Lpm_GoToStandByMode::enMode. Since MCU enters into low power consumption mode after calling this funciton, this function will not return until MCU is waken up. There are also different between waken up from Standby mode and deep standby mode. When MCU is waken up from standby mode, the program of MCU will run after this function, but when MCU is waken up from deep standby mode, the program of MCU will run from the reset vector.
Lpm_ConfigDeepStbRetCause() configures the return causes of deep standby mode and Lpm_ReadDeepStbRetCause() reads the return causes after MCU is waken up. Note that Wakeup from WKUP0 pin is always enabled.
Lpm_SetWkupPinLevel() is used to set the WKUP pin active level.
Lpm_ConfigSubClk() configures whether to supply Sub clock to RTC and CEC in deep standby mode. Not all FM product has this function. Please confirm it in the hardware manual.
Lpm_ConfigDeepStbRAMRetention() configures whether to retain RAM content after entering deep standby mode. Not all FM product has this function. Plesae comfirm it in the hardware manual.
Lpm_WriteBackupRegisters() writes all backup registers, which can retain in the deep standby mode. and Lpm_ReadBackupRegisters() reads all backup regisers after waken up from deep standby mode.
Lpm_Writeu8DataBackupRegister() writes a backup regiser with 8-bit alignment, which can retain in the deep standby mode, and Lpm_Readu8DataBackupRegister() reads a backup regiser with 8-bit alignment after waken up from deep standby mode.
Lpm_Writeu16DataBackupRegister() writes a backup regiser with 16-bit alignment, which can retain in the deep standby mode, and Lpm_Readu16DataBackupRegister() reads a backup regiser with 16-bit alignment after waken up from deep standby mode.
Lpm_Writeu32DataBackupRegister() writes a backup regiser with 32-bit alignment, which can retain in the deep standby mode, and Lpm_Readu32DataBackupRegister() reads a backup regiser with 32-bit alignment after waken up from deep standby mode.
Up to 32 byte backup registers can be for FM product, see product data sheet for details.
Note:
The deep standby mode may not be available for some of FM product. Please refer to the hardware manual for the function availability.
Define Documentation
#define CM_CORE_CSR *((volatile unsigned int*)(0xE000ED10UL))
Definition at line 89 of file lpm.c.
Referenced by Lpm_GoToStandByMode().
#define LPCM_BACKUP_REG_BASE ((volatile uint8_t*)0x40035900)
Definition at line 92 of file lpm.c.
Referenced by Lpm_ReadBackupReg(), and Lpm_WriteBackupReg().
#define PDL_BACK_UP_REGISTERS (32u)
Definition at line 138 of file lpm.h.
Referenced by Lpm_Readu16DataBackupRegister(), Lpm_Readu32DataBackupRegister(), Lpm_Readu8DataBackupRegister(), Lpm_Writeu16DataBackupRegister(), Lpm_Writeu32DataBackupRegister(), Lpm_Writeu8DataBackupRegister(), ReadBackupRegisters(), and WriteBackupRegisters().
#define WIFSR_WCEC0I (1ul<<8u)
Definition at line 151 of file lpm.h.
Referenced by Lpm_ReadDeepStbRetCause().
#define WIFSR_WCEC1I (1ul<<9u)
Definition at line 152 of file lpm.h.
Referenced by Lpm_ReadDeepStbRetCause().
#define WIFSR_WLVDI (1ul<<1u)
Definition at line 144 of file lpm.h.
Referenced by Lpm_ReadDeepStbRetCause().
#define WIFSR_WRTCI (1ul<<0u)
Definition at line 143 of file lpm.h.
Referenced by Lpm_ReadDeepStbRetCause().
#define WIFSR_WUI0 (1ul<<2u)
Definition at line 145 of file lpm.h.
Referenced by Lpm_ReadDeepStbRetCause().
#define WIFSR_WUI1 (1ul<<3u)
Definition at line 146 of file lpm.h.
Referenced by Lpm_ReadDeepStbRetCause().
#define WIFSR_WUI10 (1ul<<14u)
Definition at line 157 of file lpm.h.
Referenced by Lpm_ReadDeepStbRetCause().
#define WIFSR_WUI11 (1ul<<15u)
Definition at line 158 of file lpm.h.
Referenced by Lpm_ReadDeepStbRetCause().
#define WIFSR_WUI2 (1ul<<4u)
Definition at line 147 of file lpm.h.
Referenced by Lpm_ReadDeepStbRetCause().
#define WIFSR_WUI3 (1ul<<5u)
Definition at line 148 of file lpm.h.
Referenced by Lpm_ReadDeepStbRetCause().
#define WIFSR_WUI4 (1ul<<6u)
Definition at line 149 of file lpm.h.
Referenced by Lpm_ReadDeepStbRetCause().
#define WIFSR_WUI5 (1ul<<7u)
Definition at line 150 of file lpm.h.
Referenced by Lpm_ReadDeepStbRetCause().
#define WIFSR_WUI6 (1ul<<10u)
Definition at line 153 of file lpm.h.
Referenced by Lpm_ReadDeepStbRetCause().
#define WIFSR_WUI7 (1ul<<11u)
Definition at line 154 of file lpm.h.
Referenced by Lpm_ReadDeepStbRetCause().
#define WIFSR_WUI8 (1ul<<12u)
Definition at line 155 of file lpm.h.
Referenced by Lpm_ReadDeepStbRetCause().
#define WIFSR_WUI9 (1ul<<13u)
Definition at line 156 of file lpm.h.
Referenced by Lpm_ReadDeepStbRetCause().
#define WRFSR_WINITX (1ul<<0u)
Definition at line 160 of file lpm.h.
Referenced by Lpm_ReadDeepStbRetCause().
#define WRFSR_WLVDH (1ul<<1u)
Definition at line 161 of file lpm.h.
Typedef Documentation
typedef enum en_dstb_bakup_reg en_dstb_bakup_reg_t
backup register index
typedef enum en_ret_cause_flag en_dstb_ret_cause_t
define deep standby mode return cause flag
typedef enum en_dstb_wkup_pin en_dstb_wkup_pin_t
define wkup pin index
typedef enum en_lpm_internal_voltage en_lpm_internal_voltage_t
Internal voltage selection in deep standby mode.
typedef enum en_lpm_main_osc en_lpm_main_osc_t
Main oscillator selection types.
typedef enum en_lpm_mode en_lpm_mode_t
define standby mode type
typedef enum en_wkup_valid_level en_wkup_valid_level_t
Valid level of wakeup pin.
typedef struct stc_backupreg stc_backupreg_t
backup register index
typedef struct stc_ret_cause stc_dstb_ret_cause_t
Deep standby mode return cause.
Enumeration Type Documentation
enum en_dstb_bakup_reg
backup register index
Enumerator:
BackupReg1
index of backup register 1
BackupReg2
index of backup register 2
BackupReg3
index of backup register 3
BackupReg4
index of backup register 4
BackupReg5
index of backup register 5
BackupReg6
index of backup register 6
BackupReg7
index of backup register 7
BackupReg8
index of backup register 8
BackupReg9
index of backup register 9
BackupReg10
index of backup register 10
BackupReg11
index of backup register 11
BackupReg12
index of backup register 12
BackupReg13
index of backup register 13
BackupReg14
index of backup register 14
BackupReg15
index of backup register 15
BackupReg16
index of backup register 16
Definition at line 294 of file lpm.h.
enum en_dstb_wkup_pin
define wkup pin index
Enumerator:
WkupPin1
index of wkup pin 1
WkupPin2
index of wkup pin 2
WkupPin3
index of wkup pin 3
WkupPin4
index of wkup pin 4
WkupPin5
index of wkup pin 5
WkupPin6
index of wkup pin 6
WkupPin7
index of wkup pin 7
WkupPin8
index of wkup pin 8
WkupPin9
index of wkup pin 9
WkupPin10
index of wkup pin 10
WkupPin11
index of wkup pin 11
WkupPinMax
Definition at line 236 of file lpm.h.
enum en_lpm_internal_voltage
Internal voltage selection in deep standby mode.
Enumerator:
LpmInternalVoltage120
Internal voltage is 1.20v in deepstandby mode.
LpmInternalVoltage105
Internal voltage is 1.05v in deepstandby mode.
LpmInternalVoltage110
Internal voltage is 1.10v in deepstandby mode.
Definition at line 269 of file lpm.h.
enum en_lpm_main_osc
Main oscillator selection types.
Enumerator:
LpmMainOsc4M
Support 4MHz main oscillator in deep standby mode, has the lowest power consumption.
LpmMainOsc4M8M
Support 4MHz and 8MHz main oscillator in deep standby mode, has the middle power consumption.
LpmMainOsc4M8M16M
Support 4MHz, 8MHz, and 16MHz main oscillator in deep standby mode, has higher power consumption.
LpmMainOsc48M
Support 48MHz main oscillator in deep standby mode, has the highest power consumption.
Definition at line 281 of file lpm.h.
enum en_lpm_mode
define standby mode type
Enumerator:
StbSleepMode
standby sleep mode
StbTimerMode
standby timer mode
StbStopMode
standby stop mode
StbRtcMode
standby RTC mode
DeepStbRtcMode
deep standby RTC mode
DeepStbStopMode
deep standby stop mode
Definition at line 167 of file lpm.h.
enum en_ret_cause_flag
define deep standby mode return cause flag
Enumerator:
DeepStbNoFlag
No flag set.
DeepStbInitx
return from INITX input reset
DeepStbLvdReset
return from LVD reset
DeepStbRtcInt
return from RTC interrupt
DeepStbLvdInt
return from LVD interrupt
DeepStbWkupPin0
return from Wkup pin1 detection
DeepStbWkupPin1
return from Wkup pin1 detection
DeepStbWkupPin2
return from Wkup pin2 detection
DeepStbWkupPin3
return from Wkup pin3 detection
DeepStbWkupPin4
return from Wkup pin4 detection
DeepStbWkupPin5
return from Wkup pin5 detection
DeepStbCec0
return from Wkup CEC1 reception interrupt
DeepStbCec1
return from Wkup CEC2 reception interrupt
DeepStbWkupPin6
return from Wkup pin6 detection
DeepStbWkupPin7
return from Wkup pin7 detection
DeepStbWkupPin8
return from Wkup pin8 detection
DeepStbWkupPin9
return from Wkup pin9 detection
DeepStbWkupPin10
return from Wkup pin10 detection
DeepStbWkupPin11
return from Wkup pin11 detection
Definition at line 207 of file lpm.h.
enum en_wkup_valid_level
Valid level of wakeup pin.
Enumerator:
WkupLowLevelValid
Set low level as valid level.
WkupHighLevelValid
Set high level as valid level.
Definition at line 258 of file lpm.h.
Function Documentation
en_result_t Lpm_ConfigDeepStbRAMRetention (boolean_t bRamRetain)
Configure deep standby mode RAM retention.
Parameters:
bRamRetain Whether to retain data in the RAM
Return values:
Ok Deep standby mode RAM retention set
Note:
Not all FM0+ product has this function, please check it in the product manual.
Definition at line 635 of file lpm.c.
en_result_t Lpm_ConfigDeepStbRetCause (stc_dstb_ret_cause_t * pstcCause)
Configure return cause from deep standby mode.
Parameters:
pstcCause Pointer to structure of return cause types
Return values:
Ok Deep standby mode is configured normally
Note:
Wakeup from WKUP0 pin is always enabled
Definition at line 313 of file lpm.c.
References stc_ret_cause::bCec0En, stc_ret_cause::bCec1En, stc_ret_cause::bLvdEn, stc_ret_cause::bRtcEn, stc_ret_cause::bWakeup10En, stc_ret_cause::bWakeup11En, stc_ret_cause::bWakeup1En, stc_ret_cause::bWakeup2En, stc_ret_cause::bWakeup3En, stc_ret_cause::bWakeup4En, stc_ret_cause::bWakeup5En, stc_ret_cause::bWakeup6En, stc_ret_cause::bWakeup7En, stc_ret_cause::bWakeup8En, and stc_ret_cause::bWakeup9En.
en_result_t Lpm_ConfigFlashPower (boolean_t bPowerOn)
Configure Flash power in deep standby mode.
Parameters:
bPowerOn Flash power on or not
TRUE Flash power on
FALSE Flash power off
Return values:
Ok Main oscillator types is set normally
ErrorInvalidParameter Invalid value of enMainOsc
Note:
This setting is active during stop/RTC/Sub Timer mode
Definition at line 579 of file lpm.c.
en_result_t Lpm_ConfigInternalVoltage (en_lpm_internal_voltage_t enVoltage)
Configure the internal voltage in deep standby mode.
Parameters:
enVoltage Internal voltage
LpmInternalVoltage120 Internal voltage is 1.20v
LpmInternalVoltage110 Internal voltage is 1.10v
LpmInternalVoltage105 Internal voltage is 1.05v
Return values:
Ok Internal volatge is set normally
ErrorInvalidParameter Invalid value of enVoltage
Note:
This setting is active during deep standby only.
Definition at line 504 of file lpm.c.
References LpmInternalVoltage105, LpmInternalVoltage110, and LpmInternalVoltage120.
en_result_t Lpm_ConfigSubClk (boolean_t bSupplyCec, boolean_t bSupplyRtc)
Configue the sub clock supply.
Parameters:
bSupplyCec Whether to supply sub clock to CEC
bSupplyRtc Whether to supply sub clock to RTC
Return values:
Ok The sub clock supply is configured normally
Note:
Not all FM product has this function, please check it in the product manual.
Definition at line 600 of file lpm.c.
void Lpm_GoToStandByMode (en_lpm_mode_t enMode, boolean_t bIoRemain)
go to standby mode
Parameters:
enMode the type of standby mode. This parameter can be one of the following values:
StbSleepMode Sleep mode
StbTimerMode Timer mode
StbStopMode Stop mode
StbRtcMode RTC mode
DeepStbRtcMode deep standby RTC mode
DeepStbStopMode deep standby stop mode
bIoRemain Set io status when enter standby mode. This parameter can be one of the following values:
FALSE Set IO to Hi-z
TRUE Remain IO status
Definition at line 223 of file lpm.c.
References CM_CORE_CSR, DeepStbRtcMode, DeepStbStopMode, StbRtcMode, StbSleepMode, StbStopMode, StbTimerMode, WIFSRDummyRead(), and WRFSRDummyRead().
uint8_t Lpm_ReadBackupReg (en_dstb_bakup_reg_t enRegIndex)
Read the backup register.
Parameters:
enRegIndex Backup register index
BackupReg1 Back up register 1 index
BackupReg2 Back up register 2 index
BackupReg3 Back up register 3 index
BackupReg4 Back up register 4 index
BackupReg5 Back up register 5 index
BackupReg6 Back up register 6 index
BackupReg7 Back up register 7 index
BackupReg8 Back up register 8 index
BackupReg9 Back up register 9 index
BackupReg10 Back up register 10 index
BackupReg11 Back up register 11 index
BackupReg12 Back up register 12 index
BackupReg13 Back up register 13 index
BackupReg14 Back up register 14 index
BackupReg15 Back up register 15 index
BackupReg16 Back up register 16 index
Returns:
Backup register data
Definition at line 711 of file lpm.c.
References LPCM_BACKUP_REG_BASE.
en_result_t Lpm_ReadBackupRegisters (stc_backupreg_t * stcBackUpReg)
en_dstb_ret_cause_t Lpm_ReadDeepStbRetCause (void)
Read deep standby mode return cause flag.
Return values:
DeepStbNoFlag No flag set
DeepStbInitx Wakeup from deep standby mode by INITX reset
DeepStbLvdReset Wakeup from deep standby mode by LVD reset
DeepStbRtcInt Wakeup from deep standby mode by RTC interrupt
DeepStbLvdInt Wakeup from deep standby mode by LVD interrupt
DeepStbWkupPin0 Wakeup from deep standby mode by WKUP0
DeepStbWkupPin1 Wakeup from deep standby mode by WKUP1
DeepStbWkupPin2 Wakeup from deep standby mode by WKUP2
DeepStbWkupPin3 Wakeup from deep standby mode by WKUP3
DeepStbWkupPin4 Wakeup from deep standby mode by WKUP4
DeepStbWkupPin5 Wakeup from deep standby mode by WKUP5
DeepStbCec0 Wakeup from deep standby mode by CEC0 interrupt
DeepStbCec1 Wakeup from deep standby mode by CEC1 interrupt
DeepStbWkupPin6 Wakeup from deep standby mode by WKUP6
DeepStbWkupPin7 Wakeup from deep standby mode by WKUP7
DeepStbWkupPin8 Wakeup from deep standby mode by WKUP8
DeepStbWkupPin9 Wakeup from deep standby mode by WKUP9
DeepStbWkupPin10 Wakeup from deep standby mode by WKUP10
DeepStbWkupPin11 Wakeup from deep standby mode by WKUP11
Definition at line 364 of file lpm.c.
References DeepStbCec0, DeepStbCec1, DeepStbInitx, DeepStbLvdInt, DeepStbLvdReset, DeepStbNoFlag, DeepStbRtcInt, DeepStbWkupPin0, DeepStbWkupPin1, DeepStbWkupPin10, DeepStbWkupPin11, DeepStbWkupPin2, DeepStbWkupPin3, DeepStbWkupPin4, DeepStbWkupPin5, DeepStbWkupPin6, DeepStbWkupPin7, DeepStbWkupPin8, DeepStbWkupPin9, WIFSR_WCEC0I, WIFSR_WCEC1I, WIFSR_WLVDI, WIFSR_WRTCI, WIFSR_WUI0, WIFSR_WUI1, WIFSR_WUI10, WIFSR_WUI11, WIFSR_WUI2, WIFSR_WUI3, WIFSR_WUI4, WIFSR_WUI5, WIFSR_WUI6, WIFSR_WUI7, WIFSR_WUI8, WIFSR_WUI9, and WRFSR_WINITX.
en_result_t Lpm_Readu16DataBackupRegister (uint8_t u8AddressOffset, uint16_t * u16Data)
Read Backup Register (16-Bit)
Parameters:
[in] u8AddressOffset Byte address offset to Back-up register
[out] u16Data Pointer to 16-Bit data to be read
Return values:
Ok Successfully written
ErrorInvalidParameter Address offset out of range (highest priority)
ErrorAddressAlignment Address not aligned to 16-bit
Definition at line 779 of file lpm.c.
References PDL_BACK_UP_REGISTERS, ReadBackupRegisters(), and stc_backupreg::u8BREG00.
en_result_t Lpm_Readu32DataBackupRegister (uint8_t u8AddressOffset, uint32_t * u32Data)
Read Backup Register (32-Bit)
Parameters:
[in] u8AddressOffset Byte address offset to Back-up register
[out] u32Data Pointer to 32-Bit data to be read
Return values:
Ok Successfully written
ErrorInvalidParameter Address offset out of range (highest priority)
ErrorAddressAlignment Address not aligned to 32-bit
Definition at line 843 of file lpm.c.
References PDL_BACK_UP_REGISTERS, ReadBackupRegisters(), and stc_backupreg::u8BREG00.
en_result_t Lpm_Readu8DataBackupRegister (uint8_t u8AddressOffset, uint8_t * u8Data)
Read Backup Register (Byte)
Parameters:
[in] u8AddressOffset Byte address offset to Back-up register
[out] u8Data Pointer to Byte data to be read
Return values:
Ok Successfully written
ErrorInvalidParameter Address offset out of range
Definition at line 726 of file lpm.c.
References PDL_BACK_UP_REGISTERS, ReadBackupRegisters(), and stc_backupreg::u8BREG00.
en_result_t Lpm_SelMainOscTypes (en_lpm_main_osc_t enMainOsc)
Configure main oscillator types in deep standby mode.
Parameters:
enMainOsc Main oscillator types
LpmMainOsc4M Support 4MHz main osc
LpmMainOsc4M8M Support 4MHz,8MHz main osc
LpmMainOsc4M8M16M Support 4MHz,8MHz,16MHz main osc
LpmMainOsc48M Support 48MHz main osc
Return values:
Ok Main oscillator types is set normally
ErrorInvalidParameter Invalid value of enMainOsc
Note:
This setting is active during deep standby only.
Definition at line 542 of file lpm.c.
References LpmMainOsc48M, LpmMainOsc4M, LpmMainOsc4M8M, and LpmMainOsc4M8M16M.
en_result_t Lpm_SetWkupPinLevel (en_dstb_wkup_pin_t enPinIndex, en_wkup_valid_level_t enLevel)
Set the valid level of wkup pin.
Parameters:
enPinIndex Pin index
WkupPin1 WKUP1 pin index
WkupPin2 WKUP2 pin index
WkupPin3 WKUP3 pin index
WkupPin4 WKUP4 pin index
WkupPin5 WKUP5 pin index
WkupPin6 WKUP6 pin index
WkupPin7 WKUP7 pin index
WkupPin8 WKUP8 pin index
WkupPin9 WKUP9 pin index
WkupPin10 WKUP10 pin index
WkupPin11 WKUP11 pin index
enLevel Wakeup pin valid value
WkupLowLevelValid Set low as active level for WKUPx
WkupHighLevelValid Set high as active level for WKUPx
Return values:
Ok The valid level of wkup pin is set normally
ErrorInvalidParameter Invalid value of enPinIndex
Definition at line 475 of file lpm.c.
References WkupPinMax.
en_result_t Lpm_WriteBackupReg (en_dstb_bakup_reg_t enRegIndex, uint8_t u8Data)
Write the backup register.
Parameters:
enRegIndex register index
BackupReg1 Back up register 1 index
BackupReg2 Back up register 2 index
BackupReg3 Back up register 3 index
BackupReg4 Back up register 4 index
BackupReg5 Back up register 5 index
BackupReg6 Back up register 6 index
BackupReg7 Back up register 7 index
BackupReg8 Back up register 8 index
BackupReg9 Back up register 9 index
BackupReg10 Back up register 10 index
BackupReg11 Back up register 11 index
BackupReg12 Back up register 12 index
BackupReg13 Back up register 13 index
BackupReg14 Back up register 14 index
BackupReg15 Back up register 15 index
BackupReg16 Back up register 16 index
u8Data the data written into backup register
Return values:
Ok The backup register written normally
ErrorInvalidParameter enRegIndex > BackupReg15
Definition at line 675 of file lpm.c.
References BackupReg15, and LPCM_BACKUP_REG_BASE.
en_result_t Lpm_WriteBackupRegisters (stc_backupreg_t * stcBackUpReg)
en_result_t Lpm_Writeu16DataBackupRegister (uint8_t u8AddressOffset, uint16_t u16Data)
Write Backup Registers (16-Bit)
Parameters:
[in] u8AddressOffset Byte address offset to Back-up register
[in] u16Data 16-Bit data to be written
Return values:
Ok Successfully written
ErrorInvalidParameter Address offset out of range (highest priority)
ErrorAddressAlignment Address not aligned to 16-bit
Definition at line 811 of file lpm.c.
References PDL_BACK_UP_REGISTERS, ReadBackupRegisters(), stc_backupreg::u8BREG00, and WriteBackupRegisters().
en_result_t Lpm_Writeu32DataBackupRegister (uint8_t u8AddressOffset, uint32_t u32Data)
Write Backup Registers (32-Bit)
Parameters:
[in] u8AddressOffset Byte address offset to Back-up register
[in] u32Data Pointer to 32-Bit data
Return values:
Ok Successfully written
ErrorInvalidParameter Address offset out of range (highest priority)
ErrorAddressAlignment Address not aligned to 32-bit
Definition at line 875 of file lpm.c.
References PDL_BACK_UP_REGISTERS, ReadBackupRegisters(), stc_backupreg::u8BREG00, and WriteBackupRegisters().
en_result_t Lpm_Writeu8DataBackupRegister (uint8_t u8AddressOffset, uint8_t u8Data)
Write Backup Registers (Byte)
Parameters:
[in] u8AddressOffset Byte address offset to Back-up register
[in] u8Data Byte data to be written
Return values:
Ok Successfully written
ErrorInvalidParameter Address offset out of range
Definition at line 752 of file lpm.c.
References PDL_BACK_UP_REGISTERS, ReadBackupRegisters(), stc_backupreg::u8BREG00, and WriteBackupRegisters().
static en_result_t ReadBackupRegisters (stc_backupreg_t * stcBackUpReg) [static]
Read Backup Registers.
Parameters:
[out] stcBackUpReg double pointer to user backup register structure
Return values:
Ok Successfully read
Definition at line 119 of file lpm.c.
References PDL_BACK_UP_REGISTERS, and stc_backupreg::u8BREG00.
Referenced by Lpm_Readu16DataBackupRegister(), Lpm_Readu32DataBackupRegister(), Lpm_Readu8DataBackupRegister(), Lpm_Writeu16DataBackupRegister(), Lpm_Writeu32DataBackupRegister(), and Lpm_Writeu8DataBackupRegister().
static uint16_t WIFSRDummyRead (void) [static]
WRFSR dummy read.
Definition at line 197 of file lpm.c.
Referenced by Lpm_GoToStandByMode().
static uint16_t WRFSRDummyRead (void) [static]
WRFSR dummy read.
Definition at line 186 of file lpm.c.
Referenced by Lpm_GoToStandByMode().
static en_result_t WriteBackupRegisters (stc_backupreg_t * stcBackUpReg) [static]
Write Backup Registers.
Parameters:
[out] stcBackUpReg structure of backup registers
Return values:
Ok Successfully written
Definition at line 154 of file lpm.c.
References PDL_BACK_UP_REGISTERS, and stc_backupreg::u8BREG00.
Referenced by Lpm_Writeu16DataBackupRegister(), Lpm_Writeu32DataBackupRegister(), and Lpm_Writeu8DataBackupRegister().