PDL for FM Family: Programmable CRC Controller (PCRC)
Programmable CRC Controller (PCRC)
Data Structures
struct stc_pcrc_config
Programmable Crc configuration.
Typedefs
typedef enum en_crc_data_format en_crc_data_format_t
Programmable Crc data format.
typedef enum en_crc_input_data_size en_crc_input_data_size_t
Programmable Crc input data size.
typedef struct stc_pcrc_config stc_pcrc_config_t
Programmable Crc configuration.
Enumerations
enum en_crc_data_format { MsbFirstBigEndian = 0u, MsbFirstLittleEndian = 1u, LsbFirstBigEndian = 2u, LsbFirstLittleEndian = 3u }
Programmable Crc data format.
enum en_crc_input_data_size { InputData8Bit = 0u, InputData16Bit = 1u, InputData24Bit = 2u, InputData32Bit = 3u }
Programmable Crc input data size.
Functions
static void PcrcInitNvic (void)
Device dependent initialization of interrupts according CMSIS with level defined in pdl_user.h.
static void PcrcDeInitNvic (void)
Device dependent de-initialization of interrupts according CMSIS.
void PcrcIrqHandler (void)
ISR of the PCRC module.
en_result_t Pcrc_Init (stc_pcrc_config_t *pstcConfig)
Initialisation of a Programmable CRC module.
void Pcrc_DeInit (void)
Re-Initialisation of a Programmable CRC module.
void Pcrc_SetInitialValue (uint32_t u32InitialValue)
Set CRC computing initial value.
void Pcrc_SetFinalXorValue (uint32_t u32FinalXorValue)
Set CRC computing result XOR value.
void Pcrc_SetOutputDataFormat (en_crc_data_format_t enOutputDataFormat)
Set CRC output data Format.
void Pcrc_SetInputDataFormat (en_crc_data_format_t enInputDataFormat)
Set CRC input data Format.
void Pcrc_SetInputDataSize (en_crc_input_data_size_t enInputDataSize)
Set CRC input data size.
void Pcrc_SetCfgTest (uint8_t u8CfgTest)
Set TEST field of CRC Computing Configuration Register.
uint8_t Pcrc_GetIntRequestFlag (void)
Get CRC interrupt request flag.
void Pcrc_EnableIntRequest (void)
Enable CRC interrupt request.
void Pcrc_DisableIntRequest (void)
Disable CRC interrupt request.
void Pcrc_EnableDmaTx (void)
Allows the transfer request of input data for DMA.
void Pcrc_DisableDmaTx (void)
Disable the transfer request of input data for DMA.
uint8_t Pcrc_GetLockStatus (void)
Get CRC computing unit state.
void Pcrc_ClrIntRequest (void)
Clear RGCRC Interrupt request.
void Pcrc_WriteData (uint32_t u32WriteData)
Write computing input data.
uint32_t Pcrc_ReadResult (void)
Get computing output data.
Variables
static func_ptr_t m_pfnPcrcIrqCb = NULL
Detailed Description
Provided functions of PCRC module:
Pcrc_Init()
Pcrc_DeInit()
Pcrc_SetInitialValue()
Pcrc_SetFinalXorValue()
Pcrc_SetOutputDataFormat()
Pcrc_SetInputDataFormat()
Pcrc_SetInputDataSize()
Pcrc_SetCfgTest()
Pcrc_GetIntRequestFlag()
Pcrc_EnableIntRequest()
Pcrc_DisableIntRequest()
Pcrc_EnableDmaTx()
Pcrc_DisableDmaTx()
Pcrc_GetLockStatus()
Pcrc_ClrIntRequest()
Pcrc_WriteData()
Pcrc_ReadResult()
Pcrc_Init() initializes a Programmable CRC module according the configuration of the structure type stc_pcrc_config_t.
Pcrc_DeInit() Re-Initialisation of a Programmable CRC module.
Pcrc_SetInitialValue() is used to set CRC computing initial value.
Pcrc_SetFinalXorValue() is used to set CRC computing result XOR value.
Pcrc_SetOutputDataFormat() sets CRC computing output data format selected by the structure type en_crc_data_format_t.
Pcrc_SetInputDataFormat() sets CRC computing input data format selected by the structure type en_crc_data_format_t.
Pcrc_SetInputDataSize() sets CRC computing input data size selected by the structure type en_crc_input_data_size_t.
Pcrc_SetCfgTest() Sets TEST field of CRC Computing Configuration Register to access it
Pcrc_GetIntRequestFlag() gets CRC interrupt request flag.
Pcrc_EnableIntRequest() enable CRC interrupt request.
Pcrc_DisableIntRequest() disable CRC interrupt request.
Pcrc_EnableDmaTx() enables the transfer request of input data for DMA.
Pcrc_DisableDmaTx() disables the transfer request of input data for DMA.
Pcrc_GetLockStatus() gets CRC computing unit state.
Pcrc_ClrIntRequest() clear CRC interrupt request.
Pcrc_WriteData() writes CRC computing input data..
Pcrc_ReadResult() reads CRC computing output data.
Typedef Documentation
typedef enum en_crc_data_format en_crc_data_format_t
Programmable Crc data format.
typedef enum en_crc_input_data_size en_crc_input_data_size_t
Programmable Crc input data size.
typedef struct stc_pcrc_config stc_pcrc_config_t
Programmable Crc configuration.
Enumeration Type Documentation
enum en_crc_data_format
Programmable Crc data format.
Enumerator:
MsbFirstBigEndian
MSB-first / Big endian is selected for output format conversion.
MsbFirstLittleEndian
MSB-first / Little endian is selected for output format conversion.
LsbFirstBigEndian
LSB-first / Big endian is selected for output format conversion.
LsbFirstLittleEndian
LSB-first / Little endian is selected for output format conversion.
Definition at line 147 of file pcrc.h.
enum en_crc_input_data_size
Programmable Crc input data size.
Enumerator:
InputData8Bit
8-bit input data size is selected.
InputData16Bit
16-bit input data size is selected.
InputData24Bit
24-bit input data size is selected.
InputData32Bit
32-bit input data size is selected.
Definition at line 159 of file pcrc.h.
Function Documentation
void Pcrc_ClrIntRequest (void)
Clear RGCRC Interrupt request.
Definition at line 393 of file pcrc.c.
void Pcrc_DeInit (void)
Re-Initialisation of a Programmable CRC module.
Definition at line 219 of file pcrc.c.
References PcrcDeInitNvic().
void Pcrc_DisableDmaTx (void)
Disable the transfer request of input data for DMA.
Definition at line 369 of file pcrc.c.
void Pcrc_DisableIntRequest (void)
Disable CRC interrupt request.
Definition at line 347 of file pcrc.c.
void Pcrc_EnableDmaTx (void)
Allows the transfer request of input data for DMA.
Definition at line 358 of file pcrc.c.
void Pcrc_EnableIntRequest (void)
Enable CRC interrupt request.
Definition at line 336 of file pcrc.c.
uint8_t Pcrc_GetIntRequestFlag (void)
Get CRC interrupt request flag.
Return values:
PRGCRC Interrupt request flag
Definition at line 327 of file pcrc.c.
uint8_t Pcrc_GetLockStatus (void)
Get CRC computing unit state.
Return values:
1 : Indicates the CRC computing unit is in busy state
0 : Indicates the CRC computing unit is in idle state.
Definition at line 384 of file pcrc.c.
en_result_t Pcrc_Init (stc_pcrc_config_t * pstcConfig)
Initialisation of a Programmable CRC module.
Parameters:
pstcConfig CRC module configuration
Return values:
Ok Initializiation of Programmable CRC module successfully done.
ErrorInvalidParameter If one of following cases match:
pstcConfig == NULL,
parameter out of range
Definition at line 170 of file pcrc.c.
References stc_pcrc_config::bIrqEn, stc_pcrc_config::bTouchNvic, stc_pcrc_config::bUseDstc, stc_pcrc_config::enInputDataSize, stc_pcrc_config::enInputFormat, stc_pcrc_config::enOutputFormat, InputData32Bit, LsbFirstLittleEndian, m_pfnPcrcIrqCb, PcrcInitNvic(), PDL_ZERO_STRUCT, stc_pcrc_config::pfnIrqCb, stc_pcrc_config::u32CrcInitValue, stc_pcrc_config::u32FinalXorValue, and stc_pcrc_config::u32GeneratorPolynomial.
uint32_t Pcrc_ReadResult (void)
Get computing output data.
Return values:
output data value
Definition at line 422 of file pcrc.c.
void Pcrc_SetCfgTest (uint8_t u8CfgTest)
Set TEST field of CRC Computing Configuration Register.
Parameters:
u8CfgTest,: TEST field value. The correct operation is not achieved if perform writing values other than "100000" to the TEST[5:0] register
Definition at line 313 of file pcrc.c.
void Pcrc_SetFinalXorValue (uint32_t u32FinalXorValue)
Set CRC computing result XOR value.
Parameters:
u32FinalXorValue,: result XOR value
Definition at line 255 of file pcrc.c.
void Pcrc_SetInitialValue (uint32_t u32InitialValue)
Set CRC computing initial value.
Parameters:
u32InitialValue,: CRC initial value
Definition at line 241 of file pcrc.c.
void Pcrc_SetInputDataFormat (en_crc_data_format_t enInputDataFormat)
Set CRC input data Format.
Parameters:
enInputDataFormat,: CRC input data Format
Definition at line 283 of file pcrc.c.
void Pcrc_SetInputDataSize (en_crc_input_data_size_t enInputDataSize)
Set CRC input data size.
Parameters:
enInputDataSize,: CRC input data size
Definition at line 297 of file pcrc.c.
void Pcrc_SetOutputDataFormat (en_crc_data_format_t enOutputDataFormat)
Set CRC output data Format.
Parameters:
enOutputDataFormat,: CRC output data Format
Definition at line 269 of file pcrc.c.
void Pcrc_WriteData (uint32_t u32WriteData)
Write computing input data.
Parameters:
u32WriteData,: input data value
Definition at line 408 of file pcrc.c.
static void PcrcDeInitNvic (void) [static]
Device dependent de-initialization of interrupts according CMSIS.
Definition at line 129 of file pcrc.c.
References PDL_DEFAULT_INTERRUPT_LEVEL.
Referenced by Pcrc_DeInit().
static void PcrcInitNvic (void) [static]
Device dependent initialization of interrupts according CMSIS with level defined in pdl_user.h.
Device dependent initialization of interrupts according CMSIS with level defined in pdl.h.
Definition at line 115 of file pcrc.c.
Referenced by Pcrc_Init().
void PcrcIrqHandler (void)
ISR of the PCRC module.
Definition at line 143 of file pcrc.c.
References m_pfnPcrcIrqCb.
Variable Documentation
func_ptr_t m_pfnPcrcIrqCb = NULL [static]
Definition at line 101 of file pcrc.c.
Referenced by Pcrc_Init(), and PcrcIrqHandler().