PDL for FM Family: Controller Area Network (CAN)
Controller Area Network (CAN)
Data Structures
struct stc_can_bitrate
CAN bitrate.
struct stc_can_msg_id
CAN message identifier.
struct stc_can_msg_data
CAN message data.
struct stc_can_msg
CAN message.
struct stc_can_interrupt_handling
CAN interrupt pointer structure.
struct stc_can_notification
CAN notification pointer structure.
struct stc_can_config
CAN configuration.
struct stc_can_intern_data
CAN instance internal data, storing internal information for each enabled CAN instance.
struct stc_can_instance_data
CAN instance data type.
Defines
#define CAN_INSTANCE_COUNT (uint32_t)(sizeof(m_astcCanInstanceDataLut) / sizeof(m_astcCanInstanceDataLut[0]))
Macro to return the number of enabled CAN instances.
#define CAN_STATUS_INTERRUPT (1 << 15)
Status interrupt detected.
#define CAN_NO_LEC_CHANGE 7
#define CAN_MSG_DIR_RX 0
WRRD bit indicating read direction.
#define CAN_MSG_DIR_TX 1
WRRD bit indicating write direction.
#define CAN_MSG_ID_EXTENDED 1
Extended msg id is used.
#define stc_cann_t FM_CAN_TypeDef
#define CAN0 (*((volatile stc_cann_t *) FM_CAN0_BASE))
#define CAN1 (*((volatile stc_cann_t *) FM_CAN1_BASE))
#define CAN_MESSAGE_DATA_BUFFER_SIZE 8u
Size of data bytes in a receive or transmit operation (usually 8)
#define CAN_MESSAGE_BUFFER_COUNT 32u
Number of possible message buffer for receive and transmit messages (usually 32)
#define CAN_BITRATE_TSEG1_MIN 2u
Lower limit for TSEG1 in structure stc_can_bitrate_t.
#define CAN_BITRATE_TSEG1_MAX 16u
Upper limit for TSEG1 in structure stc_can_bitrate_t.
#define CAN_BITRATE_TSEG2_MIN 1u
Lower limit for TSEG2 in structure stc_can_bitrate_t.
#define CAN_BITRATE_TSEG2_MAX 8u
Upper limit for TSEG2 in structure stc_can_bitrate_t.
#define CAN_BITRATE_SYNC_JUMP_WIDTH_MIN 1u
Lower limit for Sync Jump Width in structure stc_can_bitrate_t.
#define CAN_BITRATE_SYNC_JUMP_WIDTH_MAX 4u
Upper limit for Sync Jump Width in structure stc_can_bitrate_t.
#define CAN_BITRATE_PRESCALER_MIN 1u
Lower limit for Prescaler in structure stc_can_bitrate_t.
#define CAN_BITRATE_PRESCALER_MAX 64u
Upper limit for Prescaler in structure stc_can_bitrate_t.
#define CAN_MAX_CLK 40000000u
Maximum CAN clock frequency (after prescaler)
Typedefs
typedef enum en_can_prescaler en_can_prescaler_t
CAN Unit configuration structures.
typedef struct stc_can_bitrate stc_can_bitrate_t
CAN bitrate.
typedef struct stc_can_msg_id stc_can_msg_id_t
CAN message identifier.
typedef struct stc_can_msg_data stc_can_msg_data_t
CAN message data.
typedef enum en_can_tx_mode en_can_tx_mode_t
CAN transmit mode.
typedef enum en_can_status en_can_status_t
CAN status.
typedef enum en_can_error en_can_error_t
CAN error.
typedef struct stc_can_msg stc_can_msg_t
CAN message.
typedef void(* can_tx_msg_func_ptr_t)(uint8_t u8MsgBuf)
Message transmission complete callback function (can_tx_msg_func_ptr_t).
typedef void(* can_rx_msg_func_ptr_t)(uint8_t u8MsgBuf, stc_can_msg_t *pstcRxMsg)
Message reception callback function (can_rx_msg_func_ptr_t).
typedef void(* can_status_chg_func_ptr_t)(en_can_status_t enCanStatus)
Status changed callback function (can_status_chg_func_ptr_t).
typedef void(* can_error_func_ptr_t)(en_can_error_t enCanError)
Error callback function (can_error_func_ptr_t).
typedef struct
stc_can_interrupt_handling stc_can_interrupt_handling_t
CAN interrupt pointer structure.
typedef struct stc_can_notification stc_can_notification_t
CAN notification pointer structure.
typedef struct stc_can_config stc_can_config_t
CAN configuration.
typedef enum en_can_instance_index en_can_instance_index_t
Enumeration to define an index for each enabled CAN instance.
typedef struct stc_can_intern_data stc_can_intern_data_t
CAN instance internal data, storing internal information for each enabled CAN instance.
typedef struct
stc_can_instance_data stc_can_instance_data_t
CAN instance data type.
Enumerations
enum en_can_prescaler {
CanPreDiv11 = 0u, CanPreDiv12 = 1u, CanPreDiv14 = 2u, CanPreDiv18 = 3u,
CanPreDiv23 = 4u, CanPreDiv13 = 5u, CanPreDiv16 = 6u, CanPreDiv112 = 7u,
CanPreDiv15 = 8u, CanPreDiv110 = 9u
}
CAN Unit configuration structures.
enum en_can_tx_mode { CanImmediateTransmit = 0u, CanRemoteTransmit = 1u }
CAN transmit mode.
enum en_can_status {
CanNoError = 0u, CanStuffError = 1u, CanFormError = 2u, CanAckError = 3u,
CanBit1Error = 4u, CanBit0Error = 5u, CanCRCError = 6u
}
CAN status.
enum en_can_error { CanBusOff = 0u, CanWarning = 1u }
CAN error.
enum en_can_instance_index { CanInstanceIndexCan0, CanInstanceIndexCan1, CanInstanceIndexMax }
Enumeration to define an index for each enabled CAN instance.
Functions
static stc_can_intern_data_t * CanGetInternDataPtr (volatile FM_CAN_TypeDef *pstcCan)
Return the internal data for a certain CAN instance.
static void Can_InitInterrupt (volatile FM_CAN_TypeDef *pstcCan)
Set NVIC Interrupt depending on CAN instance.
static void Can_DeInitInterrupt (volatile FM_CAN_TypeDef *pstcCan)
Clear NVIC Interrupt depending on CAN instance.
void CanIrqHandler (volatile FM_CAN_TypeDef *pstcCan, stc_can_intern_data_t *pstcCanInternData)
CAN (Status/Error/Rx/Tx) interrupt ISR.
en_result_t Can_Init (volatile FM_CAN_TypeDef *pstcCan, const stc_can_config_t *pstcConfig)
Initializes the CAN module.
en_result_t Can_DeInit (volatile FM_CAN_TypeDef *pstcCan)
Deinitializes the CAN module. Any pending transmission or receiption will be aborted and all CAN related registers are reset to their default values.
static en_result_t CanIsMbUpdatePossible (volatile FM_CAN_TypeDef *pstcCan, uint8_t u8MsgBuf)
Check if the given Message Buffer can be updated.
en_result_t Can_SetTransmitMsgBuffer (volatile FM_CAN_TypeDef *pstcCan, uint8_t u8MsgBuf, const stc_can_msg_id_t *pstcMsgId, can_tx_msg_func_ptr_t pfnCallback)
Configures a message buffer for transmission. Setting of new values is not possible if a transmission is pending, except remote transmission mode. The callback function pfnCallback can be NULL, but there will be no notification of a successful transmission. This function has to be called at least once before function Can_UpdateAndTransmitMsgBuffer() can be used with the same message buffer index.
en_result_t Can_UpdateAndTransmitMsgBuffer (volatile FM_CAN_TypeDef *pstcCan, uint8_t u8MsgBuf, const stc_can_msg_data_t *pstcMsgData, en_can_tx_mode_t enTxMode)
Updates the message data of a message buffer and/or start transmission. Transmits the message immediately (immediate transmission mode) or on reception of a matching remote frame (remote transmission mode). Function Can_SetTransmitMsgBuffer() must be called before setup the identifier and enable this message buffer.
en_result_t Can_UpdateAndTransmitFifoMsgBuffer (volatile FM_CAN_TypeDef *pstcCan, uint8_t u8MsgBuf, const stc_can_msg_data_t *pstcMsgData, en_can_tx_mode_t enTxMode)
Updates the message data of a message buffer and/or start with EOB = 0 (Msg Buffer as FIFO) transmission. The function calls Can_UpdateAndTransmitMsgBuffer()
en_result_t Can_SetReceiveMsgBuffer (volatile FM_CAN_TypeDef *pstcCan, uint8_t u8MsgBuf, stc_can_msg_t *pstcMsgBuffer, uint32_t u32MsgIdMask, can_rx_msg_func_ptr_t pfnCallback)
Configure a message buffer for reception. Configure and enable a message buffer for reception. The acceptance filter is set by pstcMsgBuffer->stcIdentifier and u32MsgIdMask. Each '0' bit in u32MsgIdMask masks the corresponding bit of the received message ID before comparing it to the configured identifier (set by pstcMsgBuffer->stcIdentifier). This allows receiving messages with different identifier. Setting all bits of u32MsgIdMask to '1' will only accept messages that match the configured identifier. If extended identifier is used, the u32MsgIdMask will also be interpreted as extended mask identifier. If 11 bit identifier is used, than u32MsgIdMask will be used as 11 bit mask identifier. The application must provide a message buffer object (pstcMsgBuffer) to be filled with received data. After reception of a message that passed the acceptance filter, the message's identifier, data and data length is copied into the provided message buffer and its bNew flag is set to TRUE. The message buffer has to be kept valid until this message buffer is reset (Can_ResetMsgBuffer()).
en_result_t Can_SetReceiveFifoMsgBuffer (volatile FM_CAN_TypeDef *pstcCan, uint8_t u8MsgBuf, stc_can_msg_t *pstcMsgBuffer, uint32_t u32MsgIdMask, can_rx_msg_func_ptr_t pfnCallback)
Configure a message buffer for reception with EOB = 0 (FIFO mode). This function calls Can_SetReceiveMsgBuffer()
en_result_t Can_ResetMsgBuffer (volatile FM_CAN_TypeDef *pstcCan, uint8_t u8MsgBuf)
Stop any message buffer operation i.e. disable it.
Variables
stc_can_instance_data_t m_astcCanInstanceDataLut []
Look-up table for all enabled CAN instances and their internal data.
stc_can_instance_data_t m_astcCanInstanceDataLut []
Look-up table for all enabled CAN instances and their internal data.
Detailed Description
Provided functions of CAN module:
Can_Init() (Initialisation of CAN module)
Can_DeInit() (Reset of all CAN related register to default value)
Can_SetTransmitMsgBuffer() (Used to initiate and configure a message buffer for a CAN message trasnmission)
Can_UpdateAndTransmitMsgBuffer() (Used to update the data in a message buffer and to transmit a message)
Can_SetReceiveMsgBuffer() (Used to initiate and setup a message buffer for reveiving data)
How to use the CAN module:
First, to initialize a CAN module, Can_Init() must be called. The callback functions are optional, but recommended, otherwise there is no report to the API in case of any error. Can_DeInit() has to be used if any of the settings from Can_Init() have to be changed (use Can_DeInit() and afterwards Can_Init()). Can_DeInit() is used to completely disable the CAN module. With Can_DeInit() all CAN related register values are reset to their default values. Also any pending or ongoing transmission or reception will be aborted. Each CAN module has CAN_MESSAGE_BUFFER_COUNT number of message buffers which can be used either for reception or transmission of CAN messages. Each message buffer for transmission has to be set up first by calling Can_SetTransmitMsgBuffer(). For receiving CAN messages the function Can_SetReceiveMsgBuffer() has to be used. It is possible to set a callback function which will be notified whenever a message has been received.
Note:
The numbers of the message buffers used in this driver are indexed from 0 to 31 although the 'physical addresses' of these buffers are indexed from 1 to 32!
Define Documentation
#define CAN0 (*((volatile stc_cann_t *) FM_CAN0_BASE))
Definition at line 110 of file can.h.
Referenced by Can_DeInitInterrupt(), and Can_InitInterrupt().
#define CAN1 (*((volatile stc_cann_t *) FM_CAN1_BASE))
Definition at line 111 of file can.h.
Referenced by Can_DeInitInterrupt(), and Can_InitInterrupt().
#define CAN_BITRATE_PRESCALER_MAX 64u
Upper limit for Prescaler in structure stc_can_bitrate_t.
Definition at line 138 of file can.h.
Referenced by Can_Init().
#define CAN_BITRATE_PRESCALER_MIN 1u
Lower limit for Prescaler in structure stc_can_bitrate_t.
Definition at line 136 of file can.h.
Referenced by Can_Init().
#define CAN_BITRATE_SYNC_JUMP_WIDTH_MAX 4u
Upper limit for Sync Jump Width in structure stc_can_bitrate_t.
Definition at line 133 of file can.h.
Referenced by Can_Init().
#define CAN_BITRATE_SYNC_JUMP_WIDTH_MIN 1u
Lower limit for Sync Jump Width in structure stc_can_bitrate_t.
Definition at line 131 of file can.h.
Referenced by Can_Init().
#define CAN_BITRATE_TSEG1_MAX 16u
Upper limit for TSEG1 in structure stc_can_bitrate_t.
Definition at line 122 of file can.h.
Referenced by Can_Init().
#define CAN_BITRATE_TSEG1_MIN 2u
Lower limit for TSEG1 in structure stc_can_bitrate_t.
Definition at line 120 of file can.h.
Referenced by Can_Init().
#define CAN_BITRATE_TSEG2_MAX 8u
Upper limit for TSEG2 in structure stc_can_bitrate_t.
Definition at line 127 of file can.h.
Referenced by Can_Init().
#define CAN_BITRATE_TSEG2_MIN 1u
Lower limit for TSEG2 in structure stc_can_bitrate_t.
Definition at line 125 of file can.h.
Referenced by Can_Init().
#define CAN_INSTANCE_COUNT (uint32_t)(sizeof(m_astcCanInstanceDataLut) / sizeof(m_astcCanInstanceDataLut[0]))
Macro to return the number of enabled CAN instances.
Definition at line 71 of file can.c.
Referenced by CanGetInternDataPtr().
#define CAN_MAX_CLK 40000000u
Maximum CAN clock frequency (after prescaler)
Definition at line 142 of file can.h.
Referenced by Can_Init().
#define CAN_MESSAGE_BUFFER_COUNT 32u
Number of possible message buffer for receive and transmit messages (usually 32)
Definition at line 117 of file can.h.
Referenced by Can_DeInit(), Can_Init(), Can_ResetMsgBuffer(), Can_SetReceiveMsgBuffer(), Can_SetTransmitMsgBuffer(), and Can_UpdateAndTransmitMsgBuffer().
#define CAN_MESSAGE_DATA_BUFFER_SIZE 8u
Size of data bytes in a receive or transmit operation (usually 8)
Definition at line 114 of file can.h.
#define CAN_MSG_DIR_RX 0
WRRD bit indicating read direction.
Definition at line 80 of file can.c.
Referenced by Can_SetReceiveMsgBuffer(), Can_UpdateAndTransmitMsgBuffer(), and CanIrqHandler().
#define CAN_MSG_DIR_TX 1
WRRD bit indicating write direction.
Definition at line 81 of file can.c.
Referenced by Can_Init(), Can_SetReceiveMsgBuffer(), Can_SetTransmitMsgBuffer(), and Can_UpdateAndTransmitMsgBuffer().
#define CAN_MSG_ID_EXTENDED 1
Extended msg id is used.
Definition at line 82 of file can.c.
Referenced by Can_SetReceiveMsgBuffer(), Can_SetTransmitMsgBuffer(), and CanIrqHandler().
#define CAN_NO_LEC_CHANGE 7
LEC (Last Error Code) special value indicating that no changes happened after the CPU has written this special value to LEC
Definition at line 78 of file can.c.
Referenced by CanIrqHandler().
#define CAN_STATUS_INTERRUPT (1 << 15)
Status interrupt detected.
Definition at line 74 of file can.c.
Referenced by CanIrqHandler().
#define stc_cann_t FM_CAN_TypeDef
Definition at line 109 of file can.h.
Referenced by Can_DeInitInterrupt(), and Can_InitInterrupt().
Typedef Documentation
typedef void(* can_error_func_ptr_t)(en_can_error_t enCanError)
Error callback function (can_error_func_ptr_t).
Any error will be reported to the API (see en_can_error_t for possible error codes).
Definition at line 319 of file can.h.
typedef void(* can_rx_msg_func_ptr_t)(uint8_t u8MsgBuf, stc_can_msg_t *pstcRxMsg)
Message reception callback function (can_rx_msg_func_ptr_t).
Signals that CAN has received a new message.
Definition at line 299 of file can.h.
typedef void(* can_status_chg_func_ptr_t)(en_can_status_t enCanStatus)
Status changed callback function (can_status_chg_func_ptr_t).
Any status change will be reported to the API (see en_can_status_t for possible status change codes).
Definition at line 309 of file can.h.
typedef void(* can_tx_msg_func_ptr_t)(uint8_t u8MsgBuf)
Message transmission complete callback function (can_tx_msg_func_ptr_t).
Signals a successful completed transmission.
Definition at line 290 of file can.h.
typedef enum en_can_error en_can_error_t
CAN error.
These error values are used to report any CAN related error to the API via the CAN error callback function (can_error_func_ptr_t).
typedef enum en_can_instance_index en_can_instance_index_t
Enumeration to define an index for each enabled CAN instance.
typedef enum en_can_prescaler en_can_prescaler_t
CAN Unit configuration structures.
CAN Prescaler
typedef enum en_can_status en_can_status_t
CAN status.
These state values represent the current CAN state, and are used in the CAN status changed callback function (can_status_chg_func_ptr_t).
typedef enum en_can_tx_mode en_can_tx_mode_t
CAN transmit mode.
To select how transmit data should be processed.
typedef struct stc_can_bitrate stc_can_bitrate_t
CAN bitrate.
This structure is used to set the bitrate register. All values are decremented by 1 before writing to the CANn_BTR register (see HW manual for more details).
typedef struct stc_can_config stc_can_config_t
CAN configuration.
Is used to set the CAN bitrate and allows deactivating of automatic retransmission in case of a transmission error. Optionally error and status changed notification can be set.
typedef struct stc_can_instance_data stc_can_instance_data_t
CAN instance data type.
typedef struct stc_can_intern_data stc_can_intern_data_t
CAN instance internal data, storing internal information for each enabled CAN instance.
typedef struct stc_can_interrupt_handling stc_can_interrupt_handling_t
CAN interrupt pointer structure.
Holds some pointers to callback functions and buffer
typedef struct stc_can_msg_data stc_can_msg_data_t
CAN message data.
Data structure for transmit and receive operations, maximum value for parameter u8DataLengthCode is CAN_MESSAGE_DATA_BUFFER_SIZE.
typedef struct stc_can_msg_id stc_can_msg_id_t
CAN message identifier.
This structure is used to set the CAN message identifier for transmit and receive operations. The identifiction is needed when setting the CAN arbitration register. On the one side this structure is used in the Can_SetTransmitMsgBuffer() function, on the other side same structure is used in the structure stc_can_msg_t which is used for receive data in Can_SetReceiveMsgBuffer(...) function.
typedef struct stc_can_msg stc_can_msg_t
CAN message.
This structure stores a CAN message, including the identifier, data and data length code (DLC). It also contains an overflow and new flag which indicates the message state for received messages.
typedef struct stc_can_notification stc_can_notification_t
CAN notification pointer structure.
Holds some pointers to callback functions for status and error notification
Enumeration Type Documentation
enum en_can_error
CAN error.
These error values are used to report any CAN related error to the API via the CAN error callback function (can_error_func_ptr_t).
Enumerator:
CanBusOff
The CAN module is in busoff state.
CanWarning
At least one error counter has reached error warning limit of 96.
Definition at line 262 of file can.h.
enum en_can_instance_index
Enumeration to define an index for each enabled CAN instance.
Enumerator:
CanInstanceIndexCan0
CanInstanceIndexCan1
CanInstanceIndexMax
Definition at line 364 of file can.h.
enum en_can_prescaler
CAN Unit configuration structures.
CAN Prescaler
Enumerator:
CanPreDiv11
CAN prescaler clock: no division.
CanPreDiv12
CAN prescaler clock: 1/2.
CanPreDiv14
CAN prescaler clock: 1/4.
CanPreDiv18
CAN prescaler clock: 1/8.
CanPreDiv23
CAN prescaler clock: 2/3.
CanPreDiv13
CAN prescaler clock: 1/3.
CanPreDiv16
CAN prescaler clock: 1/6.
CanPreDiv112
CAN prescaler clock: 1/12.
CanPreDiv15
CAN prescaler clock: 1/5.
CanPreDiv110
CAN prescaler clock: 1/10.
Definition at line 159 of file can.h.
enum en_can_status
CAN status.
These state values represent the current CAN state, and are used in the CAN status changed callback function (can_status_chg_func_ptr_t).
Enumerator:
CanNoError
No error pending.
CanStuffError
More than 5 equal bits in a sequence have occurred in a part of a received message.
CanFormError
A fixed format part of a received frame has the wrong format.
CanAckError
The message this CAN Core transmitted was not acknowledged by another node.
CanBit1Error
While trying to send a recessive bit (1) a dominant level (0) was sampled.
CanBit0Error
While trying to send a dominant bit (0) a recessive level (1) was sampled.
CanCRCError
The CRC checksum was incorrect.
Definition at line 243 of file can.h.
enum en_can_tx_mode
CAN transmit mode.
To select how transmit data should be processed.
Enumerator:
CanImmediateTransmit
Transmit message immediately.
CanRemoteTransmit
Transmit message on reception of remote frame.
Definition at line 229 of file can.h.
Function Documentation
en_result_t Can_DeInit (volatile FM_CAN_TypeDef * pstcCan)
Deinitializes the CAN module. Any pending transmission or receiption will be aborted and all CAN related registers are reset to their default values.
Parameters:
[in] pstcCan Pointer to register area of a CAN unit.
Return values:
Ok CAN module has been successfully deinitialized
ErrorInvalidParameter If one of the following conditions are met:
pstcCan == NULL
pstcCanInternData == NULL (invalid or disabled CAN unit (PDL_PERIPHERAL_ENABLE_CAN))
Definition at line 661 of file can.c.
References Can_DeInitInterrupt(), CAN_MESSAGE_BUFFER_COUNT, CanGetInternDataPtr(), stc_can_notification::pfnCanErrorInterruptFunction, stc_can_interrupt_handling::pfnCanRxInterruptFunction, stc_can_notification::pfnCanStatusInterruptFunction, stc_can_interrupt_handling::pfnCanTxInterruptFunction, stc_can_interrupt_handling::pstcMsgBuffer, stc_can_intern_data::stcCanInterruptHandling, and stc_can_intern_data::stcCanNotificationCb.
static void Can_DeInitInterrupt (volatile FM_CAN_TypeDef * pstcCan) [static]
Clear NVIC Interrupt depending on CAN instance.
Parameters:
pstcCan Pointer to CAN instance
Definition at line 195 of file can.c.
References CAN0, CAN1, PDL_DEFAULT_INTERRUPT_LEVEL, and stc_cann_t.
Referenced by Can_DeInit().
en_result_t Can_Init (volatile FM_CAN_TypeDef * pstcCan, const stc_can_config_t * pstcConfig)
Initializes the CAN module.
This function initializes one specific CAN module with the parameters provided in the given config structure. After initialization the CAN module has Error, Status and Module-Interrupt enabled and is ready to use.
Can_Init() has to be called with the parameter pstcConfig of type stc_can_config_t the basic CAN settings automatic retransmission, the CAN baudrate, and the error and status change callback function can be set.
All values in pstcConfig have to be in valid range (see can.h for allowed ranges of dedicated parameters). The error and status change callback functions can be NULL. In this case no information of error or status changes will be reported to the API.
To reset and disable the CAN module the function Can_DeInit() has to be used.
The resulting CAN presecaler value is checked, if it is within CAN_MAX_CLK (normally 16 MHz).
Parameters:
[in] pstcCan Pointer to register area of a CAN unit.
[in] pstcConfig CAN configuration parameters.
Return values:
Ok CAN module has been successfully initialized.
ErrorInvalidParameter If one of the following conditions are met:
pstcCan == NULL
pstcConfig == NULL
pstcCanInternData == NULL (invalid or disabled CAN unit (PDL_PERIPHERAL_ENABLE_CAN))
pstcConfig->stcBitrate.u8TimeSegment1 out of range
pstcConfig->stcBitrate.u8TimeSegment2 out of range
pstcConfig->stcBitrate.u8SyncJumpWidth out of range
pstcConfig->stcBitrate.u16Prescaler out of range
pstcConfig->stcBitrate.enCanPrescaler wrong enumerator
pstcConfig->stcBitrate.enCanPrescaler CAN_MAX_CLK violated
Definition at line 454 of file can.c.
References stc_can_config::bDisableAutomaticRetransmission, stc_can_config::bTouchPrescaler, CAN_BITRATE_PRESCALER_MAX, CAN_BITRATE_PRESCALER_MIN, CAN_BITRATE_SYNC_JUMP_WIDTH_MAX, CAN_BITRATE_SYNC_JUMP_WIDTH_MIN, CAN_BITRATE_TSEG1_MAX, CAN_BITRATE_TSEG1_MIN, CAN_BITRATE_TSEG2_MAX, CAN_BITRATE_TSEG2_MIN, Can_InitInterrupt(), CAN_MAX_CLK, CAN_MESSAGE_BUFFER_COUNT, CAN_MSG_DIR_TX, CanGetInternDataPtr(), CanPreDiv11, CanPreDiv110, CanPreDiv112, CanPreDiv12, CanPreDiv13, CanPreDiv14, CanPreDiv15, CanPreDiv16, CanPreDiv18, CanPreDiv23, stc_can_bitrate::enCanPrescaler, PDL_ZERO_STRUCT, stc_can_notification::pfnCanErrorInterruptFunction, stc_can_notification::pfnCanStatusInterruptFunction, stc_can_config::pfnErrorCallback, stc_can_config::pfnStatusCallback, stc_can_config::stcBitrate, stc_can_intern_data::stcCanNotificationCb, stc_can_bitrate::u16Prescaler, stc_can_bitrate::u8SyncJumpWidth, stc_can_bitrate::u8TimeSegment1, and stc_can_bitrate::u8TimeSegment2.
static void Can_InitInterrupt (volatile FM_CAN_TypeDef * pstcCan) [static]
Set NVIC Interrupt depending on CAN instance.
Parameters:
pstcCan Pointer to CAN instance
Definition at line 156 of file can.c.
References CAN0, CAN1, and stc_cann_t.
Referenced by Can_Init().
en_result_t Can_ResetMsgBuffer (volatile FM_CAN_TypeDef * pstcCan, uint8_t u8MsgBuf)
Stop any message buffer operation i.e. disable it.
stop pending transmission (reset TXRQST and NEWDAT flag):
stop reception operation (reset MSGVAL flag)
reset RXIE and TXIE
clear pointers to external buffers and callback functions
Parameters:
[in] pstcCan Pointer to register area of a CAN unit.
[in] u8MsgBuf Message buffer index (0 .. CAN_MESSAGE_BUFFER_COUNT - 1)
Return values:
Ok Message buffer operations have been stoped
ErrorInvalidParameter If one of the following conditions are met:
pstcCan == NULL
pstcCanInternData == NULL (invalid or disabled CAN unit (PDL_PERIPHERAL_ENABLE_CAN))
u8MsgBuf out of range
Definition at line 1375 of file can.c.
References CAN_MESSAGE_BUFFER_COUNT, CanGetInternDataPtr(), stc_can_interrupt_handling::pfnCanRxInterruptFunction, stc_can_interrupt_handling::pfnCanTxInterruptFunction, stc_can_interrupt_handling::pstcMsgBuffer, and stc_can_intern_data::stcCanInterruptHandling.
en_result_t Can_SetReceiveFifoMsgBuffer (volatile FM_CAN_TypeDef * pstcCan, uint8_t u8MsgBuf, stc_can_msg_t * pstcMsgBuffer, uint32_t u32MsgIdMask, can_rx_msg_func_ptr_t pfnCallback)
Configure a message buffer for reception with EOB = 0 (FIFO mode). This function calls Can_SetReceiveMsgBuffer()
Parameters:
[in] pstcCan Pointer to register area of a CAN unit.
[in] u8MsgBuf Message buffer index (0 .. CAN_MESSAGE_BUFFER_COUNT - 1)
[in,out] pstcMsgBuffer CAN message object which defines identifier for acceptance filter.
[in] u32MsgIdMask Mask for identifier acceptance filter and later receives the received message (all '1' disables masking).
[in] pfnCallback Callback function which is called when new CAN message was received and accepted by this message buffer.
Return values:
Ok Message buffer for reception has been succesfully set.
ErrorInvalidParameter If one of the following conditions are met:
pstcCan == NULL
pstcCanInternData == NULL (invalid or disabled CAN unit (PDL_PERIPHERAL_ENABLE_CAN))
pstcMsgBuffer == NULL
u8MsgBuf out of range
Definition at line 1318 of file can.c.
References stc_can_intern_data::bEobZero, Can_SetReceiveMsgBuffer(), and CanGetInternDataPtr().
en_result_t Can_SetReceiveMsgBuffer (volatile FM_CAN_TypeDef * pstcCan, uint8_t u8MsgBuf, stc_can_msg_t * pstcMsgBuffer, uint32_t u32MsgIdMask, can_rx_msg_func_ptr_t pfnCallback)
Configure a message buffer for reception. Configure and enable a message buffer for reception. The acceptance filter is set by pstcMsgBuffer->stcIdentifier and u32MsgIdMask. Each '0' bit in u32MsgIdMask masks the corresponding bit of the received message ID before comparing it to the configured identifier (set by pstcMsgBuffer->stcIdentifier). This allows receiving messages with different identifier. Setting all bits of u32MsgIdMask to '1' will only accept messages that match the configured identifier. If extended identifier is used, the u32MsgIdMask will also be interpreted as extended mask identifier. If 11 bit identifier is used, than u32MsgIdMask will be used as 11 bit mask identifier. The application must provide a message buffer object (pstcMsgBuffer) to be filled with received data. After reception of a message that passed the acceptance filter, the message's identifier, data and data length is copied into the provided message buffer and its bNew flag is set to TRUE. The message buffer has to be kept valid until this message buffer is reset (Can_ResetMsgBuffer()).
A mask identifier has to be set when calling Can_SetReceiveMsgBuffer(), the length for the mask identifier will be the same like the one used in pstcMsgBuffer (11-bit or 29-bit identifier mask). The extended identification mask bit and the direction mask bit are always set to 1.
The API has to check the bNew flag of parameter pstcMsgBuffer to get information about if a message has already been received or not. If a new message has been received while bNew flag is set (the last received message was not read out by API so far) than the bOverflow flag will be set. So, if callback function is not used, the API has to reset the bNew flag when the received message is read out (also the bOverflow flag has to be reset) and furthermore.
Parameters:
[in] pstcCan Pointer to register area of a CAN unit.
[in] u8MsgBuf Message buffer index (0 .. CAN_MESSAGE_BUFFER_COUNT - 1)
[in,out] pstcMsgBuffer CAN message object which defines identifier for acceptance filter.
[in] u32MsgIdMask Mask for identifier acceptance filter and later receives the received message (all '1' disables masking).
[in] pfnCallback Callback function which is called when new CAN message was received and accepted by this message buffer.
Return values:
Ok Message buffer for reception has been succesfully set.
ErrorInvalidParameter If one of the following conditions are met:
pstcCan == NULL
pstcCanInternData == NULL (invalid or disabled CAN unit (PDL_PERIPHERAL_ENABLE_CAN))
pstcMsgBuffer == NULL
u8MsgBuf out of range
Definition at line 1198 of file can.c.
References stc_can_intern_data::bEobZero, stc_can_msg_id::bExtended, stc_can_msg::bNew, stc_can_msg::bOverflow, CAN_MESSAGE_BUFFER_COUNT, CAN_MSG_DIR_RX, CAN_MSG_DIR_TX, CAN_MSG_ID_EXTENDED, CanGetInternDataPtr(), PDL_ZERO_STRUCT, stc_can_interrupt_handling::pfnCanRxInterruptFunction, stc_can_interrupt_handling::pstcMsgBuffer, stc_can_intern_data::stcCanInterruptHandling, stc_can_msg::stcIdentifier, and stc_can_msg_id::u32Identifier.
Referenced by Can_SetReceiveFifoMsgBuffer().
en_result_t Can_SetTransmitMsgBuffer (volatile FM_CAN_TypeDef * pstcCan, uint8_t u8MsgBuf, const stc_can_msg_id_t * pstcMsgId, can_tx_msg_func_ptr_t pfnCallback)
Configures a message buffer for transmission. Setting of new values is not possible if a transmission is pending, except remote transmission mode. The callback function pfnCallback can be NULL, but there will be no notification of a successful transmission. This function has to be called at least once before function Can_UpdateAndTransmitMsgBuffer() can be used with the same message buffer index.
With the parameter stc_can_msg_id_t::pstcMsgId of type stc_can_msg_id_t the API can set the identifier (11 bit or 29 bit length) of the CAN transmit message. It is possible to set a callback function to get notified when a transmission is successfully finished. Can_SetTransmitMsgBuffer() must be called before calling Can_UpdateAndTransmitMsgBuffer(). Update or setting of new values of function Can_SetTransmitMsgBuffer() or Can_UpdateAndTransmitMsgBuffer() is not possible if a transmission is pending or ongoing, except remote transmission mode is used.
Parameters:
[in] pstcCan Pointer to register area of a CAN unit.
[in] u8MsgBuf Message buffer index (0 .. CAN_MESSAGE_BUFFER_COUNT - 1)
[in] pstcMsgId CAN message identifier.
[in] pfnCallback Callback function to be called after successful transmission, can be NULL.
Return values:
Ok Message buffer has been successfully initialized.
ErrorInvalidParameter If one of the following conditions are met:
pstcCan == NULL
pstcCanInternData == NULL (invalid or disabled CAN unit (PDL_PERIPHERAL_ENABLE_CAN))
pstcMsgId == NULL
u8MsgBuf out of range
ErrorOperationInProgress If following condition is met:
A transmission is pending (either wait or call Can_ResetMsgBuffer()).
Definition at line 843 of file can.c.
References stc_can_msg_id::bExtended, CAN_MESSAGE_BUFFER_COUNT, CAN_MSG_DIR_TX, CAN_MSG_ID_EXTENDED, CanGetInternDataPtr(), CanIsMbUpdatePossible(), stc_can_interrupt_handling::pfnCanTxInterruptFunction, stc_can_intern_data::stcCanInterruptHandling, and stc_can_msg_id::u32Identifier.
en_result_t Can_UpdateAndTransmitFifoMsgBuffer (volatile FM_CAN_TypeDef * pstcCan, uint8_t u8MsgBuf, const stc_can_msg_data_t * pstcMsgData, en_can_tx_mode_t enTxMode)
Updates the message data of a message buffer and/or start with EOB = 0 (Msg Buffer as FIFO) transmission. The function calls Can_UpdateAndTransmitMsgBuffer()
Parameters:
[in] pstcCan Pointer to register area of a CAN unit.
[in] u8MsgBuf Message buffer index (0 .. CAN_MESSAGE_BUFFER_COUNT - 1)
[in] pstcMsgData CAN message data
[in] enTxMode Transmission mode (immediately or remote)
Return values:
Ok Message buffer has been successfully updated.
ErrorInvalidParameter If one of the following conditions are met:
pstcCan == NULL
pstcCanInternData == NULL (invalid or disabled CAN unit (PDL_PERIPHERAL_ENABLE_CAN))
pstcMsgData == NULL
u8MsgBuf out of range
ErrorUninitialized If Can_SetTransmitMsgBuffer() was not called before.
ErrorOperationInProgress If a transmission is pending (either wait or call Can_ResetMsgBuffer()).
Definition at line 1115 of file can.c.
References stc_can_intern_data::bEobZero, Can_UpdateAndTransmitMsgBuffer(), and CanGetInternDataPtr().
en_result_t Can_UpdateAndTransmitMsgBuffer (volatile FM_CAN_TypeDef * pstcCan, uint8_t u8MsgBuf, const stc_can_msg_data_t * pstcMsgData, en_can_tx_mode_t enTxMode)
Updates the message data of a message buffer and/or start transmission. Transmits the message immediately (immediate transmission mode) or on reception of a matching remote frame (remote transmission mode). Function Can_SetTransmitMsgBuffer() must be called before setup the identifier and enable this message buffer.
Parameters:
[in] pstcCan Pointer to register area of a CAN unit.
[in] u8MsgBuf Message buffer index (0 .. CAN_MESSAGE_BUFFER_COUNT - 1)
[in] pstcMsgData CAN message data
[in] enTxMode Transmission mode (immediately or remote)
Return values:
Ok Message buffer has been successfully updated.
ErrorInvalidParameter If one of the following conditions are met:
pstcCan == NULL
pstcCanInternData == NULL (invalid or disabled CAN unit (PDl_PERIPHERAL_ENABLE_CAN))
pstcMsgData == NULL
u8MsgBuf out of range
ErrorUninitialized If Can_SetTransmitMsgBuffer() was not called before.
ErrorOperationInProgress If a transmission is pending (either wait or call Can_ResetMsgBuffer()).
Definition at line 946 of file can.c.
References stc_can_msg_data::au8Data, stc_can_intern_data::bEobZero, CAN_MESSAGE_BUFFER_COUNT, CAN_MSG_DIR_RX, CAN_MSG_DIR_TX, CanGetInternDataPtr(), CanImmediateTransmit, CanIsMbUpdatePossible(), and stc_can_msg_data::u8DataLengthCode.
Referenced by Can_UpdateAndTransmitFifoMsgBuffer().
static stc_can_intern_data_t* CanGetInternDataPtr (volatile FM_CAN_TypeDef * pstcCan) [static]
Return the internal data for a certain CAN instance.
Parameters:
pstcCan Pointer to CAN instance
Returns:
Pointer to internal data or NULL if instance is not enabled (or not known)
Definition at line 134 of file can.c.
References CAN_INSTANCE_COUNT, and stc_can_instance_data::stcInternData.
Referenced by Can_DeInit(), Can_Init(), Can_ResetMsgBuffer(), Can_SetReceiveFifoMsgBuffer(), Can_SetReceiveMsgBuffer(), Can_SetTransmitMsgBuffer(), Can_UpdateAndTransmitFifoMsgBuffer(), and Can_UpdateAndTransmitMsgBuffer().
void CanIrqHandler (volatile FM_CAN_TypeDef * pstcCan, stc_can_intern_data_t * pstcCanInternData)
CAN (Status/Error/Rx/Tx) interrupt ISR.
Check for any pending interrupt source and process until no more INTs are active.
Parameters:
[in] pstcCan Pointer to register area of a CAN unit.
[in] pstcCanInternData Pointer to internal data.
Description of flow:
write new data any time into user buffer
check bNew, if TRUE (user buffer not released yet) > set bOverflow
set bNew
call callback function
the MSGLST flag of the HW message buffer should be OR-mirrored into bOverflow, too
Definition at line 251 of file can.c.
References stc_can_msg_data::au8Data, stc_can_msg_id::bExtended, stc_can_msg::bNew, stc_can_msg::bOverflow, CAN_MSG_DIR_RX, CAN_MSG_ID_EXTENDED, CAN_NO_LEC_CHANGE, CAN_STATUS_INTERRUPT, CanBusOff, CanWarning, stc_can_notification::pfnCanErrorInterruptFunction, stc_can_interrupt_handling::pfnCanRxInterruptFunction, stc_can_notification::pfnCanStatusInterruptFunction, stc_can_interrupt_handling::pfnCanTxInterruptFunction, stc_can_interrupt_handling::pstcMsgBuffer, stc_can_intern_data::stcCanInterruptHandling, stc_can_intern_data::stcCanNotificationCb, stc_can_msg::stcData, stc_can_msg::stcIdentifier, stc_can_msg_id::u32Identifier, and stc_can_msg_data::u8DataLengthCode.
static en_result_t CanIsMbUpdatePossible (volatile FM_CAN_TypeDef * pstcCan, uint8_t u8MsgBuf) [static]
Check if the given Message Buffer can be updated.
Updating is not possible if a transmission is pending, except we are in remote transmission mode.
Parameters:
[in] pstcCan Pointer to register area of a CAN unit.
[in] u8MsgBuf Message buffer index (0 .. CAN_MESSAGE_BUFFER_COUNT - 1)
Return values:
Ok Message buffer can be updated
ErrorOperationInProgress A transmission is pending
Definition at line 765 of file can.c.
Referenced by Can_SetTransmitMsgBuffer(), and Can_UpdateAndTransmitMsgBuffer().
Variable Documentation
stc_can_instance_data_t m_astcCanInstanceDataLut[]
Initial value:
{
    {
      & (*((volatile  FM_CAN_TypeDef  *) FM_CAN0_BASE)) ,
      0u
    },
    {
      & (*((volatile  FM_CAN_TypeDef  *) FM_CAN1_BASE)) ,
      0u
    },
}
Look-up table for all enabled CAN instances and their internal data.
Definition at line 89 of file can.c.
stc_can_instance_data_t m_astcCanInstanceDataLut[]
Look-up table for all enabled CAN instances and their internal data.
Definition at line 89 of file can.c.