PDL for FM Family: 12-Bit Analog Digital Converter (ADC)
12-Bit Analog Digital Converter (ADC)
Data Structures
struct stc_ad_channel_list
ADC Channel list with same sort order as the ER32 registers.
struct stc_adc_scan
Scan Conversion configuration.
struct stc_adc_prio
Priority Conversion configuration.
struct stc_adc_comapre
Comparison configuration.
struct stc_adc_range_compare
Range comparison configuration.
struct stc_adc_irq_sel
ADC interrupt selection.
struct stc_adc_irq_cb
ADC interrupt callback function & internal data structure.
struct stc_adc_config
ADC configuration.
struct stc_adc_instance_data
ADC instance data type.
Defines
#define stc_adcn_t FM_ADC_TypeDef
#define ADC0 (*((volatile stc_adcn_t *) FM_ADC0_BASE))
#define ADC1 (*((volatile stc_adcn_t *) FM_ADC1_BASE))
#define ADC2 (*((volatile stc_adcn_t *) FM_ADC2_BASE))
#define PDL_ADC_READY_WAIT_COUNT 1000000u
Time-out counter value for ADC ready bit polling.
#define ADC_INSTANCE_COUNT
#define ADC0_SCAN_FIFO_ADDR (uint32_t)(&FM_ADC0->SCFD)
#define ADC1_SCAN_FIFO_ADDR (uint32_t)(&FM_ADC1->SCFD)
#define ADC2_SCAN_FIFO_ADDR (uint32_t)(&FM_ADC2->SCFD)
#define PDL_ADC_A 0u
#define PDL_ADC_B 1u
#define PDL_ADC_TYPE PDL_ADC_A
Typedefs
typedef void(* func_ptr_adc_parg32_t)(volatile uint32_t *pu32Argument)
typedef enum en_adc_scan_mode en_adc_scan_mode_t
Scan Conversion Mode.
typedef enum en_adc_sample_time_n en_adc_sample_time_n_t
Priority Conversion Stage Count.
typedef enum en_adc_timer_select en_adc_timer_select_t
ADC scan/priority conversion timer trigger selection.
typedef struct stc_ad_channel_list stc_ad_channel_list_t
ADC Channel list with same sort order as the ER32 registers.
typedef struct stc_adc_scan stc_adc_scan_t
Scan Conversion configuration.
typedef struct stc_adc_prio stc_adc_prio_t
Priority Conversion configuration.
typedef struct stc_adc_comapre stc_adc_comapre_t
Comparison configuration.
typedef struct
stc_adc_range_compare stc_adc_range_compare_t
Range comparison configuration.
typedef struct stc_adc_irq_sel stc_adc_irq_sel_t
ADC interrupt selection.
typedef struct stc_adc_irq_sel stc_adc_irq_en_t
typedef struct stc_adc_irq_cb stc_adc_irq_cb_t
ADC interrupt callback function & internal data structure.
typedef struct stc_adc_irq_cb stc_adc_intern_data_t
typedef struct stc_adc_config stc_adc_config_t
ADC configuration.
typedef enum en_adc_fifo_data_valid en_adc_fifo_data_valid_t
FIFO valid data result (Scan, Priority Conversion)
typedef enum
en_adc_fifo_start_cause en_adc_fifo_start_cause_t
FIFO data start cause.
typedef enum en_adc_status en_adc_status_t
ADC status list.
typedef enum en_adc_irq en_adc_irq_t
ADC interrupt type.
typedef enum en_adc_instance_index en_adc_instance_index_t
Enumeration to define an index for each enabled ADC instance.
typedef struct
stc_adc_instance_data stc_adc_instance_data_t
ADC instance data type.
Enumerations
enum en_adc_scan_mode { ScanSingleConversion = 0u, ScanRepeatConversion = 1u }
Scan Conversion Mode.
enum en_adc_sample_time_n {
Value1 = 0u, Value4 = 1u, Value8 = 2u, Value16 = 3u,
Value32 = 4u, Value64 = 5u, Value128 = 6u, Value256 = 7u
}
Priority Conversion Stage Count.
enum en_adc_timer_select {
AdcNoTimer = 0u, AdcMft = 1u, AdcBt0 = 2u, AdcBt1 = 3u,
AdcBt2 = 4u, AdcBt3 = 5u, AdcBt4 = 6u, AdcBt5 = 7u,
AdcBt6 = 8u, AdcBt7 = 9u
}
ADC scan/priority conversion timer trigger selection.
enum en_adc_fifo_data_valid { AdcFifoDataInvalid = 0u, AdcFifoDataValid = 1u }
FIFO valid data result (Scan, Priority Conversion)
enum en_adc_fifo_start_cause { AdcFifoSoftwareStart = 0u, AdcFifoTimerStart = 1u, AdcFifoExternalTrigger = 2u, AdcFifoErrorStart = 3u }
FIFO data start cause.
enum en_adc_status {
ScanFifoEmptyStatus = 0u, ScanFifoFullStatus = 1u, PrioFifoEmptyStatus = 2u, PrioFifoFullStatus = 3u,
Prio2PendingStatus = 4u, PrioStatus = 5u, ScanStatus = 6u, RangeThresholdExcessFlag = 7u
}
ADC status list.
enum en_adc_irq {
AdcScanIrq = 0u, AdcPrioIrq = 1u, AdcScanFifoOverrunIrq = 2u, AdcPrioFifoOverrunIrq = 3u,
AdcComparisonIrq = 4u, AdcRangeComparisonIrq = 5u
}
ADC interrupt type.
enum en_adc_instance_index { AdcInstanceIndexAdc0, AdcInstanceIndexAdc1, AdcInstanceIndexAdc2, AdcInstanceIndexMax }
Enumeration to define an index for each enabled ADC instance.
Functions
static void Adc_InitNvic (volatile FM_ADC_TypeDef *pstcAdc)
Set NVIC Interrupt depending on ADC instance.
static void Adc_DeInitNvic (volatile FM_ADC_TypeDef *pstcAdc)
Clear NVIC Interrupt depending on ADC instance.
static stc_adc_intern_data_t * AdcGetInternDataPtr (volatile FM_ADC_TypeDef *pstcAdc)
Return the internal data for a certain ADC instance.
void AdcIrqHandler (volatile FM_ADC_TypeDef *pstcAdc, stc_adc_intern_data_t *pstcAdcInternData)
ADC instance interrupt service routine.
en_result_t Adc_Init (volatile FM_ADC_TypeDef *pstcAdc, stc_adc_config_t *pstcConfig)
Initialize ADC.
en_result_t Adc_DeInit (volatile FM_ADC_TypeDef *pstcAdc, boolean_t bTouchNvic)
De-Initialize ADC.
en_result_t Adc_EnableIrq (volatile FM_ADC_TypeDef *pstcAdc, stc_adc_irq_sel_t *pstcIrqSel)
Enable ADC interrupt.
en_result_t Adc_DisableIrq (volatile FM_ADC_TypeDef *pstcAdc, stc_adc_irq_sel_t *pstcIrqSel)
Disable ADC interrupt.
boolean_t Adc_GetIrqFlag (volatile FM_ADC_TypeDef *pstcAdc, en_adc_irq_t enIrq)
Get ADC interrupt flag.
en_result_t Adc_ClrIrqFlag (volatile FM_ADC_TypeDef *pstcAdc, en_adc_irq_t enIrq)
Clear ADC interrupt flag.
en_result_t Adc_Enable (volatile FM_ADC_TypeDef *pstcAdc)
Enable ADC.
en_result_t Adc_Ready (volatile FM_ADC_TypeDef *pstcAdc)
Check ADC Readiness.
en_result_t Adc_EnableWaitReady (volatile FM_ADC_TypeDef *pstcAdc)
Enable ADC and wait for Readiness.
en_result_t Adc_Disable (volatile FM_ADC_TypeDef *pstcAdc)
Disable ADC.
en_result_t Adc_SwTriggerScan (volatile FM_ADC_TypeDef *pstcAdc)
ADC Scan Software Start Trigger.
en_result_t Adc_StopScanRepeat (volatile FM_ADC_TypeDef *pstcAdc)
Stop Scan conversion with repeat mode.
en_result_t Adc_StartScanRepeat (volatile FM_ADC_TypeDef *pstcAdc)
Start Scan conversion with repeat mode.
en_result_t Adc_SwTriggerPrio (volatile FM_ADC_TypeDef *pstcAdc)
ADC Priority Software Start Trigger.
en_result_t Adc_ForceStop (volatile FM_ADC_TypeDef *pstcAdc)
ADC Software Stop.
boolean_t Adc_GetStatus (volatile FM_ADC_TypeDef *pstcAdc, en_adc_status_t enStatus)
Get ADC conversion status.
uint32_t Adc_ReadScanFifo (volatile FM_ADC_TypeDef *pstcAdc)
Reads out Scan Conversion FIFO.
en_result_t Adc_ClrScanFifo (volatile FM_ADC_TypeDef *pstcAdc)
Clear scan FIFO.
uint8_t Adc_GetScanChannel (volatile FM_ADC_TypeDef *pstcAdc, uint32_t u32FifoData)
Get Channel Number from FIFO data.
en_adc_fifo_data_valid_t Adc_GetScanDataValid (volatile FM_ADC_TypeDef *pstcAdc, uint32_t u32FifoData)
Get Valid Data Flag from FIFO data.
en_adc_fifo_start_cause_t Adc_GetScanDataCause (volatile FM_ADC_TypeDef *pstcAdc, uint32_t u32FifoData)
Get Scan Conversion Start Cause from FIFO data.
uint16_t Adc_GetScanData (volatile FM_ADC_TypeDef *pstcAdc, uint32_t u32FifoData)
Get Scan Conversion FIFO data.
uint32_t Adc_ReadPrioFifo (volatile FM_ADC_TypeDef *pstcAdc)
Reads out Priority Conversion FIFO.
en_result_t Adc_ClrPrioFifo (volatile FM_ADC_TypeDef *pstcAdc)
Clear priority FIFO.
uint8_t Adc_GetPrioChannel (volatile FM_ADC_TypeDef *pstcAdc, uint32_t u32FifoData)
Get Channel Number from Priority FIFO data.
en_adc_fifo_data_valid_t Adc_GetPrioDataValid (volatile FM_ADC_TypeDef *pstcAdc, uint32_t u32FifoData)
Get Valid Data Flag from Priority FIFO data.
en_adc_fifo_start_cause_t Adc_GetPrioDataCause (volatile FM_ADC_TypeDef *pstcAdc, uint32_t u32FifoData)
Get Priority Conversion Start Cause from FIFO data.
uint16_t Adc_GetPrioData (volatile FM_ADC_TypeDef *pstcAdc, uint32_t u32FifoData)
Get Priority Conversion FIFO data.
Variables
stc_adc_instance_data_t m_astcAdcInstanceDataLut [(uint8_t)(PDL_PERIPHERAL_ENABLE_ADC0==PDL_ON)+(uint8_t)(PDL_PERIPHERAL_ENABLE_ADC1==PDL_ON)+(uint8_t)(PDL_PERIPHERAL_ENABLE_ADC2==PDL_ON)]
Look-up table for all enabled ADC instances and their internal data.
stc_adc_instance_data_t m_astcAdcInstanceDataLut [(uint8_t)(PDL_PERIPHERAL_ENABLE_ADC0==PDL_ON)+(uint8_t)(PDL_PERIPHERAL_ENABLE_ADC1==PDL_ON)+(uint8_t)(PDL_PERIPHERAL_ENABLE_ADC2==PDL_ON)]
Look-up table for all enabled ADC instances and their internal data.
Detailed Description
Provided functions of ADC module:
Adc_Init()
Adc_DeInit()
Adc_Enable()
Adc_Ready()
Adc_EnableWaitReady()
Adc_Disable()
Adc_SwTriggerScan()
Adc_StopScanRepeat()
Adc_SwTriggerPrio()
Adc_ForceStop()
Adc_EnableIrq()
Adc_DisableIrq()
Adc_GetIrqFlag()
Adc_ClrIrqFlag()
Adc_GetStatus()
Adc_ReadScanFifo()
Adc_ClrScanFifo()
Adc_GetScanChannel()
Adc_GetScanDataValid()
Adc_GetScanDataCause()
Adc_ReadPrioFifo()
Adc_ClrPrioFifo()
Adc_GetPrioChannel()
Adc_GetPrioDataValid()
Adc_GetPrioDataCause()
Adc_Init() initializes an ADC instance according the configuration of the structure type stc_adc_config_t. Adc_DeInit() de-initializes an ADC instance.
For using the ADC instnace Adc_Enable() can be used first to enable ADC operation.
The interrupt can be configured in Adc_Init() first, after initialization, Adc_EnableIrq() is used to enable ADC interrupt selected by the structure type stc_adc_irq_sel_t. Adc_DisableIrq() is used to disable ADC interrupt also selected by the structure type stc_adc_irq_sel_t.
Adc_SwTriggerScan() and Adc_SwTriggerPrio() can be used for software trigger start for scan and priority conversion.
Adc_StopScanRepeat() stops ADC scan conversion with repeat mode.
Adc_ForceStop() stops both ADC scan and priority conversion forcely.
Adc_GetIrqFlag() can get the interrupt flag in the interrupt-polling mode and Adc_ClrIrqFlag() can clear the interrupt flag. The interrupt type can be selected by the enumeration type en_adc_irq_t.
Adc_GetStatus() return the status of ADC selected by the structure type en_adc_status_t.
Adc_ClrScanFifo() and Adc_ClrPrioFifo() clear the FIFOs.
Adc_ReadScanFifo() and Adc_ReadPrioFifo() read out the FIFOs.
Adc_GetScanChannel() and Adc_GetPrioChannel() extracts channel information from the FIFO data.
Adc_GetScanDataValid() and Adc_GetPrioDataValid() extracts data valid information from the FIFO data.
Adc_GetScanDataCause() and Adc_GetPrioDataCause() extracts trigger cause information from the FIFO data.
Note:
The callback arguments for the scan and priority result point to the according FIFO registers of the recent instance. The application must take care of emptying these FIFOs. Either the FIFO depth of the configuration can be used for counting or the function Adc_GetStatus() can be used to check if the FIFO is empty or not.
Define Documentation
#define ADC0 (*((volatile stc_adcn_t *) FM_ADC0_BASE))
Definition at line 151 of file adc.h.
Referenced by Adc_DeInitNvic(), and Adc_InitNvic().
#define ADC0_SCAN_FIFO_ADDR (uint32_t)(&FM_ADC0->SCFD)
Definition at line 162 of file adc.h.
#define ADC1 (*((volatile stc_adcn_t *) FM_ADC1_BASE))
Definition at line 152 of file adc.h.
Referenced by Adc_DeInitNvic(), and Adc_InitNvic().
#define ADC1_SCAN_FIFO_ADDR (uint32_t)(&FM_ADC1->SCFD)
Definition at line 163 of file adc.h.
#define ADC2 (*((volatile stc_adcn_t *) FM_ADC2_BASE))
Definition at line 153 of file adc.h.
Referenced by Adc_DeInitNvic(), and Adc_InitNvic().
#define ADC2_SCAN_FIFO_ADDR (uint32_t)(&FM_ADC2->SCFD)
Definition at line 164 of file adc.h.
#define ADC_INSTANCE_COUNT
Value:
(uint8_t)(PDL_PERIPHERAL_ENABLE_ADC0 == PDL_ON) + \
        (uint8_t)(PDL_PERIPHERAL_ENABLE_ADC1 == PDL_ON) + \
        (uint8_t)(PDL_PERIPHERAL_ENABLE_ADC2 == PDL_ON)
Definition at line 157 of file adc.h.
Referenced by AdcGetInternDataPtr().
#define PDL_ADC_A 0u
Definition at line 167 of file adc.h.
#define PDL_ADC_B 1u
Definition at line 168 of file adc.h.
#define PDL_ADC_READY_WAIT_COUNT 1000000u
Time-out counter value for ADC ready bit polling.
Definition at line 155 of file adc.h.
Referenced by Adc_EnableWaitReady().
#define PDL_ADC_TYPE PDL_ADC_A
Definition at line 174 of file adc.h.
#define stc_adcn_t FM_ADC_TypeDef
Definition at line 150 of file adc.h.
Referenced by Adc_DeInitNvic(), and Adc_InitNvic().
Typedef Documentation
typedef enum en_adc_fifo_data_valid en_adc_fifo_data_valid_t
FIFO valid data result (Scan, Priority Conversion)
typedef enum en_adc_fifo_start_cause en_adc_fifo_start_cause_t
FIFO data start cause.
typedef enum en_adc_instance_index en_adc_instance_index_t
Enumeration to define an index for each enabled ADC instance.
typedef enum en_adc_irq en_adc_irq_t
ADC interrupt type.
typedef enum en_adc_sample_time_n en_adc_sample_time_n_t
Priority Conversion Stage Count.
typedef enum en_adc_scan_mode en_adc_scan_mode_t
Scan Conversion Mode.
typedef enum en_adc_status en_adc_status_t
ADC status list.
typedef enum en_adc_timer_select en_adc_timer_select_t
ADC scan/priority conversion timer trigger selection.
Note:
Do not change the numbering.
typedef void(* func_ptr_adc_parg32_t)(volatile uint32_t *pu32Argument)
Definition at line 182 of file adc.h.
typedef struct stc_ad_channel_list stc_ad_channel_list_t
ADC Channel list with same sort order as the ER32 registers.
typedef struct stc_adc_comapre stc_adc_comapre_t
Comparison configuration.
typedef struct stc_adc_config stc_adc_config_t
ADC configuration.
typedef struct stc_adc_instance_data stc_adc_instance_data_t
ADC instance data type.
typedef struct stc_adc_irq_cb stc_adc_intern_data_t
typedef struct stc_adc_irq_cb stc_adc_irq_cb_t
ADC interrupt callback function & internal data structure.
typedef struct stc_adc_irq_sel stc_adc_irq_en_t
typedef struct stc_adc_irq_sel stc_adc_irq_sel_t
ADC interrupt selection.
typedef struct stc_adc_prio stc_adc_prio_t
Priority Conversion configuration.
typedef struct stc_adc_range_compare stc_adc_range_compare_t
Range comparison configuration.
typedef struct stc_adc_scan stc_adc_scan_t
Scan Conversion configuration.
Enumeration Type Documentation
enum en_adc_fifo_data_valid
FIFO valid data result (Scan, Priority Conversion)
Enumerator:
AdcFifoDataInvalid
FIFO data invalid.
AdcFifoDataValid
FIFO data valid.
Definition at line 426 of file adc.h.
enum en_adc_fifo_start_cause
FIFO data start cause.
Enumerator:
AdcFifoSoftwareStart
FIFO data software start cause (Scan & Prio2 Conversion)
AdcFifoTimerStart
FIFO data timer start cause (Scan & Prio2 Conversion)
AdcFifoExternalTrigger
FIFO data external trigger cause (Prio1 Conversion)
AdcFifoErrorStart
FIFO data caused by unknown factor (Scan & Prio2 Conversion)
Definition at line 436 of file adc.h.
enum en_adc_instance_index
Enumeration to define an index for each enabled ADC instance.
Enumerator:
AdcInstanceIndexAdc0
AdcInstanceIndexAdc1
AdcInstanceIndexAdc2
AdcInstanceIndexMax
Definition at line 480 of file adc.h.
enum en_adc_irq
ADC interrupt type.
Enumerator:
AdcScanIrq
Scan conversion interrupt request.
AdcPrioIrq
Priority conversion interrupt request.
AdcScanFifoOverrunIrq
Scan FIFO overrun interrupt request.
AdcPrioFifoOverrunIrq
Priority FIFO overrun interrupt request.
AdcComparisonIrq
ADC comparison interrupt request.
AdcRangeComparisonIrq
ADC range comparison interrupt request.
Definition at line 467 of file adc.h.
enum en_adc_sample_time_n
Priority Conversion Stage Count.
Enumerator:
Value1
Set value * 1.
Value4
Set value * 4.
Value8
Set value * 8.
Value16
Set value * 16.
Value32
Set value * 32.
Value64
Set value * 64.
Value128
Set value * 128.
Value256
Set value * 256.
Definition at line 198 of file adc.h.
enum en_adc_scan_mode
Scan Conversion Mode.
Enumerator:
ScanSingleConversion
Single mode of scan conversion.
ScanRepeatConversion
Repeat mode of scan conversion.
Definition at line 188 of file adc.h.
enum en_adc_status
ADC status list.
Enumerator:
ScanFifoEmptyStatus
Scan FIFO empty status.
ScanFifoFullStatus
Scan FIFO full status.
PrioFifoEmptyStatus
Priority FIFO empty status.
PrioFifoFullStatus
Priority FIFO full status.
Prio2PendingStatus
Priority conversion (level 2) pending status.
PrioStatus
Priority conversion status.
ScanStatus
Scan conversion status.
RangeThresholdExcessFlag
Range comparison threshold exceed status.
Definition at line 448 of file adc.h.
enum en_adc_timer_select
ADC scan/priority conversion timer trigger selection.
Note:
Do not change the numbering.
Enumerator:
AdcNoTimer
No selected trigger.
AdcMft
Trigger by Multifunction Timer.
AdcBt0
Trigger with Base Timer 0.
AdcBt1
Trigger with Base Timer 1.
AdcBt2
Trigger with Base Timer 2.
AdcBt3
Trigger with Base Timer 3.
AdcBt4
Trigger with Base Timer 4.
AdcBt5
Trigger with Base Timer 5.
AdcBt6
Trigger with Base Timer 6.
AdcBt7
Trigger with Base Timer 7.
Definition at line 236 of file adc.h.
Function Documentation
en_result_t Adc_ClrIrqFlag (volatile FM_ADC_TypeDef * pstcAdc, en_adc_irq_t enIrq)
Clear ADC interrupt flag.
This function clears the ADC interrupt which is selected.
Parameters:
[in] pstcAdc ADC instance
[in] enIrq Interrupt type
AdcScanIrq Scan conversion interrupt flag
AdcPrioIrq Priority scan conversion interrupt flag
AdcScanFifoOverrunIrq Scan FIFO overrun interrupt flag
AdcPrioFifoOverrunIrq Priority FIFO overrun interrupt flag
AdcComparisonIrq Comparison interrupt flag
AdcRangeComparisonIrq Range comparison interrupt flag
Return values:
Ok Disable interrupt normally
ErrorInvalidParameter pstcAdc == NULL Other invalid configuration
Definition at line 988 of file adc.c.
References AdcComparisonIrq, AdcPrioFifoOverrunIrq, AdcPrioIrq, AdcRangeComparisonIrq, AdcScanFifoOverrunIrq, and AdcScanIrq.
en_result_t Adc_ClrPrioFifo (volatile FM_ADC_TypeDef * pstcAdc)
Clear priority FIFO.
This function clears the FIFO for priority conversion
Parameters:
[in] pstcAdc ADC instance
Return values:
Ok Priority FIFO cleared
ErrorInvalidParameter pstcAdc == NULL
Definition at line 1523 of file adc.c.
en_result_t Adc_ClrScanFifo (volatile FM_ADC_TypeDef * pstcAdc)
Clear scan FIFO.
This function clears the FIFO for scan conversion
Parameters:
[in] pstcAdc ADC instance
Return values:
Ok Scan FIFO cleared
ErrorInvalidParameter pstcAdc == NULL
Definition at line 1371 of file adc.c.
en_result_t Adc_DeInit (volatile FM_ADC_TypeDef * pstcAdc, boolean_t bTouchNvic)
De-Initialize ADC.
This function deinitializes an ADC module
Parameters:
[in] pstcAdc ADC instance
[in] bTouchNvic Touch NVIC or not
Return values:
Ok ADC instance fully disabled and reset
ErrorInvalidParameter If one of following case matches:
pstcAdc == NULL
pstcAdcInternData == NULL
Definition at line 727 of file adc.c.
References Adc_DeInitNvic(), AdcGetInternDataPtr(), stc_adc_irq_cb::pfnComparisonIrqCb, stc_adc_irq_cb::pfnPrioErrIrqCb, stc_adc_irq_cb::pfnPrioIrqCb, stc_adc_irq_cb::pfnRangeComparisonIrqCb, stc_adc_irq_cb::pfnScanErrIrqCb, and stc_adc_irq_cb::pfnScanIrqCb.
static void Adc_DeInitNvic (volatile FM_ADC_TypeDef * pstcAdc) [static]
Clear NVIC Interrupt depending on ADC instance.
Parameters:
pstcAdc Pointer to ADC instance
Definition at line 266 of file adc.c.
References ADC0, ADC1, ADC2, PDL_DEFAULT_INTERRUPT_LEVEL, and stc_adcn_t.
Referenced by Adc_DeInit().
en_result_t Adc_Disable (volatile FM_ADC_TypeDef * pstcAdc)
Disable ADC.
This function disables an ADC operation
Parameters:
[in] pstcAdc ADC instance
Return values:
Ok ADC instance disabled
ErrorTimeout ADC instance not ready
ErrorInvalidParameter pstcAdc == NULL
Definition at line 1129 of file adc.c.
en_result_t Adc_DisableIrq (volatile FM_ADC_TypeDef * pstcAdc, stc_adc_irq_sel_t * pstcIrqSel)
Disable ADC interrupt.
This function disable the ADC interrupts which are selected.
Parameters:
[in] pstcAdc ADC instance
[in] pstcIrqSel ADC interrupt selection
Return values:
Ok Disable interrupt normally
ErrorInvalidParameter If one of following cases matches:
pstcAdc == NULL
pstcIrqSel == NULL
Definition at line 870 of file adc.c.
References stc_adc_irq_sel::bComparisonIrq, stc_adc_irq_sel::bFifoOverrunIrq, stc_adc_irq_sel::bPrioIrq, stc_adc_irq_sel::bRangeComparisonIrq, and stc_adc_irq_sel::bScanIrq.
en_result_t Adc_Enable (volatile FM_ADC_TypeDef * pstcAdc)
Enable ADC.
This function enables an ADC instance (Does not wait for readiness)
Parameters:
[in] pstcAdc ADC instance
Return values:
Ok ADC enable bit set (does not indicate readiness!)
ErrorInvalidParameter pstcAdc == NULL
Definition at line 1036 of file adc.c.
en_result_t Adc_EnableIrq (volatile FM_ADC_TypeDef * pstcAdc, stc_adc_irq_sel_t * pstcIrqSel)
Enable ADC interrupt.
This function enable the ADC interrupts which are selected.
Parameters:
[in] pstcAdc ADC instance
[in] pstcIrqSel ADC interrupt selection
Return values:
Ok Enable interrupt normally
ErrorInvalidParameter If one of following cases matches:
pstcAdc == NULL
pstcIrqSel == NULL
Other invalid configuration
Definition at line 819 of file adc.c.
References stc_adc_irq_sel::bComparisonIrq, stc_adc_irq_sel::bFifoOverrunIrq, stc_adc_irq_sel::bPrioIrq, stc_adc_irq_sel::bRangeComparisonIrq, and stc_adc_irq_sel::bScanIrq.
en_result_t Adc_EnableWaitReady (volatile FM_ADC_TypeDef * pstcAdc)
Enable ADC and wait for Readiness.
This function enables an ADC instance and waits for readiness
Parameters:
[in] pstcAdc ADC instance
Return values:
Ok ADC instance enabled and ready
ErrorTimeout ADC instance not ready
ErrorInvalidParameter pstcAdc == NULL
Definition at line 1090 of file adc.c.
References PDL_ADC_READY_WAIT_COUNT.
en_result_t Adc_ForceStop (volatile FM_ADC_TypeDef * pstcAdc)
ADC Software Stop.
This function requests a stop of the ADC
Parameters:
[in] pstcAdc ADC instance
Return values:
Ok ADC instance stop request
ErrorInvalidParameter pstcAdc == NULL
Definition at line 1250 of file adc.c.
boolean_t Adc_GetIrqFlag (volatile FM_ADC_TypeDef * pstcAdc, en_adc_irq_t enIrq)
Get ADC interrupt flag.
This function gets the ADC interrupt flag which is selected.
Parameters:
[in] pstcAdc ADC instance
[in] enIrq ADC interrupt type
AdcScanIrq Scan conversion interrupt flag
AdcPrioIrq Priority scan conversion interrupt flag
AdcScanFifoOverrunIrq Scan FIFO overrun interrupt flag
AdcPrioFifoOverrunIrq Priority FIFO overrun interrupt flag
AdcComparisonIrq Comparison interrupt flag
AdcRangeComparisonIrq Range comparison interrupt flag
Return values:
TRUE The data count in scan FIFO match scan FIFO stage [AdcScanInt] The data count in priority FIFO match priority FIFO stage [AdcPrioInt] Scan FIFO overruns [AdcScanFifoOverrunInt] Priority FIFO overruns [AdcPrioFifoOverrunInt] The comparison result match the condition set in the Adc_Init() [AdcComparisonInt] The range comparison result match the condition set in the Adc_Init() [AdcRangeComparisonInt]
FALSE The data count in scan FIFO don't match scan FIFO stage [AdcScanInt] The data count in priority FIFO don't match priority FIFO stage [AdcPrioInt] Scan FIFO don't overrun [AdcScanFifoOverrunInt] Priority FIFO don't overrun [AdcPrioFifoOverrunInt] The comparison result don't match the condition set in the Adc_Init() [AdcComparisonInt] The range comparison result don't match the condition set in the Adc_Init() [AdcRangeComparisonInt]
Definition at line 937 of file adc.c.
References AdcComparisonIrq, AdcPrioFifoOverrunIrq, AdcPrioIrq, AdcRangeComparisonIrq, AdcScanFifoOverrunIrq, and AdcScanIrq.
uint8_t Adc_GetPrioChannel (volatile FM_ADC_TypeDef * pstcAdc, uint32_t u32FifoData)
Get Channel Number from Priority FIFO data.
This function returns the Channel data from input data from Priority Conversion FIFO
Precondition:
Adc_ReadPrioFifo() must be called before
Parameters:
[in] pstcAdc ADC instance
[in] u32FifoData Priority FIFO data
Returns:
Recent Priority Conversion Channel value.
Definition at line 1550 of file adc.c.
uint16_t Adc_GetPrioData (volatile FM_ADC_TypeDef * pstcAdc, uint32_t u32FifoData)
Get Priority Conversion FIFO data.
This function returns the Priority Conversion FIFO Data
Precondition:
Adc_ReadPrioFifo() must be called before
Parameters:
[in] pstcAdc ADC instance
[in] u32FifoData FIFO data
Return values:
FIFO data value
Definition at line 1631 of file adc.c.
en_adc_fifo_start_cause_t Adc_GetPrioDataCause (volatile FM_ADC_TypeDef * pstcAdc, uint32_t u32FifoData)
Get Priority Conversion Start Cause from FIFO data.
This function returns the Priority Conversion Start Cause from FIFO Data
Precondition:
Adc_ReadPrioFifo() must be called before
Parameters:
[in] pstcAdc ADC instance
[in] u32FifoData Priority FIFO data
Return values:
AdcFifoSoftwareStart Recent FIFO data cuased by Software Start
AdcFifoTimerStart Recent FIFO data causde by Timer Start
AdcFifoExternalTrigger Recent FIFO data causde by External Trigger
AdcFifoErrorStart Recent FIFO data causde by unknown factor
Definition at line 1597 of file adc.c.
References AdcFifoErrorStart, AdcFifoExternalTrigger, AdcFifoSoftwareStart, and AdcFifoTimerStart.
en_adc_fifo_data_valid_t Adc_GetPrioDataValid (volatile FM_ADC_TypeDef * pstcAdc, uint32_t u32FifoData)
Get Valid Data Flag from Priority FIFO data.
This function returns the Channel data from input data from FIFO
Precondition:
Adc_ReadPrioFifo() must be called before
Parameters:
[in] pstcAdc ADC instance
[in] u32FifoData Priority FIFO data
Return values:
AdcFifoDataValid Recent FIFO data valid
AdcFifoDataInvalid Recent FIFO data invalid
Definition at line 1570 of file adc.c.
References AdcFifoDataInvalid, and AdcFifoDataValid.
uint8_t Adc_GetScanChannel (volatile FM_ADC_TypeDef * pstcAdc, uint32_t u32FifoData)
Get Channel Number from FIFO data.
This function returns the Channel data from input data from Scan Conversion FIFO
Precondition:
Adc_ReadScanFifo() must be called before
Parameters:
[in] pstcAdc ADC instance
[in] u32FifoData FIFO data
Returns:
Recent Scan Conversion Channel value.
Definition at line 1398 of file adc.c.
uint16_t Adc_GetScanData (volatile FM_ADC_TypeDef * pstcAdc, uint32_t u32FifoData)
Get Scan Conversion FIFO data.
This function returns the Scan Conversion FIFO Data
Precondition:
Adc_ReadScanFifo() must be called before
Parameters:
[in] pstcAdc ADC instance
[in] u32FifoData FIFO data
Return values:
FIFO data value
Definition at line 1473 of file adc.c.
en_adc_fifo_start_cause_t Adc_GetScanDataCause (volatile FM_ADC_TypeDef * pstcAdc, uint32_t u32FifoData)
Get Scan Conversion Start Cause from FIFO data.
This function returns the Scan Conversion Start Cause from FIFO Data
Precondition:
Adc_ReadScanFifo() must be called before
Parameters:
[in] pstcAdc ADC instance
[in] u32FifoData FIFO data
Return values:
AdcFifoSoftwareStart Recent FIFO data cuased by Software Start
AdcFifoTimerStart Recent FIFO data caused by Timer Start
AdcFifoErrorStart Recent FIFO data caused by unknown factor
Definition at line 1444 of file adc.c.
References AdcFifoErrorStart, AdcFifoSoftwareStart, and AdcFifoTimerStart.
en_adc_fifo_data_valid_t Adc_GetScanDataValid (volatile FM_ADC_TypeDef * pstcAdc, uint32_t u32FifoData)
Get Valid Data Flag from FIFO data.
This function returns the Channel data from input data from FIFO
Precondition:
Adc_ReadScanFifo() must be called before
Parameters:
[in] pstcAdc ADC instance
[in] u32FifoData FIFO data
Return values:
AdcFifoDataValid Recent FIFO data valid
AdcFifoDataInvalid Recent FIFO data invalid
Definition at line 1418 of file adc.c.
References AdcFifoDataInvalid, and AdcFifoDataValid.
boolean_t Adc_GetStatus (volatile FM_ADC_TypeDef * pstcAdc, en_adc_status_t enStatus)
Get ADC conversion status.
This function gets the status when ADC is in conversion
Parameters:
[in] pstcAdc ADC instance
[in] enStatus ADC status type
ScanFifoEmptyStatus Scan FIFO empty status
ScanFifoFullStatus Scan FIFO full status
PrioFifoEmptyStatus Priority FIFO empty status
PrioFifoFullStatus Priority FIFO full status
Prio2PendingStatus Priority conversion (level 2) pending status
PrioStatus Priority conversion status
ScanStatus Scan conversion status
RangeThresholdExcessFlag Range comparison threshold exceed status
Return values:
TRUE The Scan FIFO is empty [ScanFifoEmptyStatus] The Scan FIFO is full [ScanFifoFullStatus] Priority FIFO is empty [PrioFifoEmptyStatus] Priority FIFO is full [PrioFifoFullStatus] Priority level 2 conversion is pending [Prio2PendingStatus] Priority conversion is in progress [PrioStatus] Scan conversion is in progress [ScanStatus] The sample data beyond the upper limit threshold [RangeThresholdExcessFlag]
FALSE The Scan FIFO isn't empty [ScanFifoEmptyStatus] The Scan FIFO isn't full [ScanFifoFullStatus] Priority FIFO isn't empty [PrioFifoEmptyStatus] Priority FIFO isn't full [PrioFifoFullStatus] Priority level 2 conversion isn't pending [Prio2PendingStatus] Priority conversion isn't in progress [PrioStatus] The sample data below the lower limit threshold [RangeThresholdExcessFlag]
Definition at line 1296 of file adc.c.
References Prio2PendingStatus, PrioFifoEmptyStatus, PrioFifoFullStatus, PrioStatus, RangeThresholdExcessFlag, ScanFifoEmptyStatus, ScanFifoFullStatus, and ScanStatus.
en_result_t Adc_Init (volatile FM_ADC_TypeDef * pstcAdc, stc_adc_config_t * pstcConfig)
Initialize ADC.
This function initializes an ADC module
Parameters:
[in] pstcAdc ADC instance
[in] pstcConfig ADC module configuration
Return values:
Ok ADC initialized normally
ErrorInvalidParameter if one of following case matches:
pstcAdc == NULL
pstcConfig == NULL
Other invalid configuration
Definition at line 347 of file adc.c.
References Adc_InitNvic(), AdcGetInternDataPtr(), stc_adc_comapre::bCompareAllChannels, stc_adc_irq_sel::bComparisonIrq, stc_adc_comapre::bCompIrqEqualGreater, stc_adc_irq_sel::bFifoOverrunIrq, stc_adc_config::bLsbAlignment, stc_adc_prio::bPrioExtTrigStartEnable, stc_adc_irq_sel::bPrioIrq, stc_adc_prio::bPrioTimerStartEnable, stc_adc_range_compare::bRangeCompareAllChannels, stc_adc_irq_sel::bRangeComparisonIrq, stc_adc_irq_sel::bScanIrq, stc_adc_scan::bScanTimerStartEnable, stc_adc_config::bTouchNvic, stc_adc_range_compare::bWithinRange, stc_adc_prio::enPrioTimerTrigger, stc_adc_config::enSamplingTimeN0, stc_adc_config::enSamplingTimeN1, stc_adc_scan::enScanMode, stc_adc_scan::enScanTimerTrigger, PDL_ZERO_STRUCT, stc_adc_irq_cb::pfnComparisonIrqCb, stc_adc_irq_cb::pfnPrioErrIrqCb, stc_adc_irq_cb::pfnPrioIrqCb, stc_adc_irq_cb::pfnRangeComparisonIrqCb, stc_adc_irq_cb::pfnScanErrIrqCb, stc_adc_irq_cb::pfnScanIrqCb, stc_adc_config::pstcComparisonInit, stc_adc_config::pstcIrqCb, stc_adc_config::pstcIrqEn, stc_adc_config::pstcPrioInit, stc_adc_config::pstcRangeComparisonInit, stc_adc_config::pstcScanInit, ScanRepeatConversion, ScanSingleConversion, stc_adc_comapre::u16CompareValue, stc_adc_range_compare::u16LowerLimitRangeValue, stc_adc_range_compare::u16UpperLimitRangeValue, stc_ad_channel_list::u32AD_CHn, stc_adc_config::u32SamplingTimeSelect, stc_adc_scan::u32ScanCannelSelect, stc_adc_comapre::u8CompareChannel, stc_adc_config::u8ComparingClockDiv, stc_adc_prio::u8PrioFifoDepth, stc_adc_prio::u8PrioLevel1AnalogChSel, stc_adc_prio::u8PrioLevel2AnalogChSel, stc_adc_range_compare::u8RangeComapreChannel, stc_adc_range_compare::u8RangeCountValue, stc_adc_config::u8SamplingTime0, stc_adc_config::u8SamplingTime1, stc_adc_scan::u8ScanFifoDepth, Value1, Value128, Value16, Value256, Value32, Value4, Value64, and Value8.
static void Adc_InitNvic (volatile FM_ADC_TypeDef * pstcAdc) [static]
Set NVIC Interrupt depending on ADC instance.
Parameters:
pstcAdc Pointer to ADC instance
Definition at line 225 of file adc.c.
References ADC0, ADC1, ADC2, PDL_IRQ_LEVEL_ADC0, and stc_adcn_t.
Referenced by Adc_Init().
uint32_t Adc_ReadPrioFifo (volatile FM_ADC_TypeDef * pstcAdc)
Reads out Priority Conversion FIFO.
This function reads out the Priority Conversion FIFO.
Precondition:
Adc_PrioFifioStatus() should be called before
Parameters:
[in] pstcAdc ADC instance
Returns:
Recent Priority Conversion FIFO value including INVL, RS2, RS1, RS0, and Channel data as is. If pstcAdc == NULL 0xFFFFFFFF is returned.
Definition at line 1501 of file adc.c.
uint32_t Adc_ReadScanFifo (volatile FM_ADC_TypeDef * pstcAdc)
Reads out Scan Conversion FIFO.
This function reads out the Scan Conversion FIFO.
Precondition:
Adc_ScanFifioStatus() should be called before
Parameters:
[in] pstcAdc ADC instance
Returns:
Recent Scan Conversion FIFO value including INVL, RS1, RS0, and Channel data as is. If pstcAdc == NULL 0xFFFFFFFF is returned.
Definition at line 1348 of file adc.c.
en_result_t Adc_Ready (volatile FM_ADC_TypeDef * pstcAdc)
Check ADC Readiness.
This function checks for ADC instance readiness
Parameters:
[in] pstcAdc ADC instance
Return values:
Ok ADC instance ready
ErrorNotReady ADC instance not ready
ErrorInvalidParameter pstcAdc == NULL
Definition at line 1062 of file adc.c.
en_result_t Adc_StartScanRepeat (volatile FM_ADC_TypeDef * pstcAdc)
Start Scan conversion with repeat mode.
This function starts an AD Scan Conversion with repeat mode
Parameters:
[in] pstcAdc ADC instance
Return values:
Ok ADC scan conversion started
ErrorInvalidParameter pstcAdc == NULL
Definition at line 1202 of file adc.c.
en_result_t Adc_StopScanRepeat (volatile FM_ADC_TypeDef * pstcAdc)
Stop Scan conversion with repeat mode.
This function stops an AD Scan Conversion with repeat mode
Parameters:
[in] pstcAdc ADC instance
Return values:
Ok ADC scan conversion stopped
ErrorInvalidParameter pstcAdc == NULL
Definition at line 1178 of file adc.c.
en_result_t Adc_SwTriggerPrio (volatile FM_ADC_TypeDef * pstcAdc)
ADC Priority Software Start Trigger.
This function starts an AD Priority Conversion by Software trigger
Parameters:
[in] pstcAdc ADC instance
Return values:
Ok ADC instance triggered (or re-triggered)
ErrorInvalidParameter pstcAdc == NULL
Definition at line 1226 of file adc.c.
en_result_t Adc_SwTriggerScan (volatile FM_ADC_TypeDef * pstcAdc)
ADC Scan Software Start Trigger.
This function starts an AD Scan Conversion by Software trigger
Parameters:
[in] pstcAdc ADC instance
Return values:
Ok ADC instance triggered (or re-triggered)
ErrorInvalidParameter pstcAdc == NULL
Definition at line 1154 of file adc.c.
static stc_adc_intern_data_t * AdcGetInternDataPtr (volatile FM_ADC_TypeDef * pstcAdc) [static]
Return the internal data for a certain ADC instance.
Parameters:
pstcAdc Pointer to ADC instance
Returns:
Pointer to internal data or NULL if instance is not enabled (or not known)
Definition at line 312 of file adc.c.
References ADC_INSTANCE_COUNT, and stc_adc_instance_data::stcInternData.
Referenced by Adc_DeInit(), and Adc_Init().
void AdcIrqHandler (volatile FM_ADC_TypeDef * pstcAdc, stc_adc_intern_data_t * pstcAdcInternData)
ADC instance interrupt service routine.
ADC instance interrupt service routine, clear interrupt cause and implement interrupt callback function.
Parameters:
pstcAdc Pointer to ADC instance
pstcAdcInternData Pointer to ADC intern data
Definition at line 148 of file adc.c.
References stc_adc_irq_cb::pfnComparisonIrqCb, stc_adc_irq_cb::pfnPrioErrIrqCb, stc_adc_irq_cb::pfnPrioIrqCb, stc_adc_irq_cb::pfnRangeComparisonIrqCb, stc_adc_irq_cb::pfnScanErrIrqCb, and stc_adc_irq_cb::pfnScanIrqCb.
Variable Documentation
stc_adc_instance_data_t m_astcAdcInstanceDataLut[(uint8_t)(PDL_PERIPHERAL_ENABLE_ADC0==PDL_ON)+(uint8_t)(PDL_PERIPHERAL_ENABLE_ADC1==PDL_ON)+(uint8_t)(PDL_PERIPHERAL_ENABLE_ADC2==PDL_ON)]
Look-up table for all enabled ADC instances and their internal data.
Definition at line 74 of file adc.c.
stc_adc_instance_data_t m_astcAdcInstanceDataLut[(uint8_t)(PDL_PERIPHERAL_ENABLE_ADC0==PDL_ON)+(uint8_t)(PDL_PERIPHERAL_ENABLE_ADC1==PDL_ON)+(uint8_t)(PDL_PERIPHERAL_ENABLE_ADC2==PDL_ON)]
Look-up table for all enabled ADC instances and their internal data.
Definition at line 74 of file adc.c.