PDL for FM Family: Inter IC Sound (I2S)
Inter IC Sound (I2S)
This section describes the interface for the I2S Unit (I2S)
Data Structures
struct stc_i2s_clk_config
I2S clock configuration.
struct stc_i2s_subframe_config
I2S sub frame configuration.
struct stc_i2s_irq_en
I2S interrupt enable structure.
struct stc_i2s_irq_cb
I2S interrupt callback function structure.
struct stc_i2s_config
I2S configuration.
struct stc_i2s_instance_data
I2S instance data type.
Typedefs
typedef void(* i2s_func_ptr_t)(void)
typedef void(* i2s_error_func_ptr)(uint32_t)
typedef enum en_i2s_pll_wait_time en_i2s_pll_wait_time_t
I2S PLL clock stabilization wait times (for 12.2 MHz input clock)
typedef enum en_i2s0_clk_in en_i2s0_clk_in_t
I2S ch.0 clock selection.
typedef enum en_i2s1_clk_in en_i2s1_clk_in_t
I2S ch.1 clock selection.
typedef struct stc_i2s_clk_config stc_i2s_clk_config_t
I2S clock configuration.
typedef enum en_i2s_start_condition en_i2s_start_condition_t
I2S start condition type (read, write)
typedef enum en_i2s_packet_timer en_i2s_packet_timer_t
I2S packet receive completion timer.
typedef struct
stc_i2s_subframe_config stc_i2s_subframe_config_t
I2S sub frame configuration.
typedef struct stc_i2s_irq_en stc_i2s_irq_en_t
I2S interrupt enable structure.
typedef enum en_i2s_irq_sel en_i2s_irq_sel_t
I2S interrupt enable structure.
typedef enum en_i2s_status en_i2s_status_t
I2S status enumeration.
typedef struct stc_i2s_irq_cb stc_i2s_irq_cb_t
I2S interrupt callback function structure.
typedef struct stc_i2s_irq_cb stc_i2s_intern_data_t
typedef struct stc_i2s_config stc_i2s_config_t
I2S configuration.
typedef enum en_i2s_instance_index en_i2s_instance_index_t
Enumeration to define an index for each enabled I2S instance.
typedef struct
stc_i2s_instance_data stc_i2s_instance_data_t
I2S instance data type.
Enumerations
enum en_i2s_pll_wait_time {
I2sPllWait26us = 0u, I2sPllWait53us = 1u, I2sPllWait106us = 2u, I2sPllWait213us = 3u,
I2sPllWait426us = 4u, I2sPllWait853us = 5u, I2sPllWait1ms70 = 6u, I2sPllWait3ms41 = 7u
}
I2S PLL clock stabilization wait times (for 12.2 MHz input clock)
enum en_i2s0_clk_in { I2s0UsePllClk = 0u, I2s0UseI2sMclki = 1u }
I2S ch.0 clock selection.
enum en_i2s1_clk_in { I2s1UsePllClk = 0u, I2s1UseI2sMclki = 1u, I2s1UseI2sMclki1 = 2u }
I2S ch.1 clock selection.
enum en_i2s_start_condition { I2sRead = 0u, I2sWrite = 1u }
I2S start condition type (read, write)
enum en_i2s_packet_timer { NoOperation = 0u, Hclk54000Cycles = 1u, Hclk108000Cycles = 2u, Hclk216000Cycles = 3u }
I2S packet receive completion timer.
enum en_i2s_irq_sel {
I2sTxFifoUnderflow0Irq = 0u, I2sTxFifoUnderflow1Irq = 1u, I2sTxBlockSizeErrIrq = 2u, I2sFrameErrIrq = 3u,
I2sTxFifoOverflowIrq = 4u, I2sTxFifoIrq = 5u, I2sRxBlockSizeErrIrq = 6u, I2sRxFifoUnderflowIrq = 7u,
I2sRxFifoOverflowIrq = 8u, I2sRxFifoIdleDetectIrq = 9u, I2sRxFifoIrq = 10u
}
I2S interrupt enable structure.
enum en_i2s_status {
I2sDmaTxChBlockSizeErr = 0u, I2sDmaRxChBlockSizeErr = 1u, I2sFrameErr = 2u, I2sTxFifoUnderflow1 = 3u,
I2sTxFifoUnderflow0 = 4u, I2sTxFifoOverflow = 5u, I2sRxFifoUnderflow = 6u, I2sRxFifoOverflow = 7u,
I2sRxFifoFifoIdle = 8u, I2sBusy = 9u, I2sTxFifoMatchThreshold = 10u, I2sRxFifoMatchThreshold = 11u
}
I2S status enumeration.
enum en_i2s_instance_index { I2sInstanceIndexI2s0, I2sInstanceIndexI2s1, I2sInstanceIndexMax }
Enumeration to define an index for each enabled I2S instance.
Functions
static stc_i2s_intern_data_t * I2sGetInternDataPtr (volatile FM_I2S_TypeDef *pstcI2s)
Return the internal data for a certain I2S instance.
void I2sIrqHandler (volatile FM_I2S_TypeDef *pstcI2s, stc_i2s_intern_data_t *pstcI2sInternData)
I2S instance interrupt service routine.
en_result_t I2s_EnableIrq (volatile FM_I2S_TypeDef *pstcI2s, en_i2s_irq_sel_t enIrqSel)
Enable I2S interrupts.
en_result_t I2s_DisableIrq (volatile FM_I2S_TypeDef *pstcI2s, en_i2s_irq_sel_t enIrqSel)
Disable I2S interrupts.
static void I2sInitNvic (volatile FM_I2S_TypeDef *pstcI2s)
Set NVIC Interrupt depending on I2S instance.
static void I2sDeInitNvic (volatile FM_I2S_TypeDef *pstcI2s)
Clear NVIC Interrupt depending on I2S instance.
en_result_t I2s_InitClk (stc_i2s_clk_config_t *pstcConfig)
This function initialises the I2S PLL clock according to the given parameters.
en_result_t I2s_DeInitClk (void)
This function de-initialises the I2S PLL clock and reset its registers.
en_result_t I2s_EnablePll (boolean_t bWaitPolling)
This function enables I2S PLL.
en_result_t I2s_DisablePll (void)
This function disables I2S PLL.
en_result_t I2s_CheckPllReady (void)
This function checks, if the PLL has stabilized.
void I2s_StartClk (volatile FM_I2S_TypeDef *pstcI2s)
This function starts the I2S clock.
void I2s_StopClk (volatile FM_I2S_TypeDef *pstcI2s)
This function stops the I2S clock.
en_result_t I2s_Init (volatile FM_I2S_TypeDef *pstcI2s, stc_i2s_config_t *pstcConfig)
en_result_t I2s_DeInit (volatile FM_I2S_TypeDef *pstcI2s, boolean_t bTouchNvic)
Deinitializes the I2S module.
en_result_t I2s_Start (volatile FM_I2S_TypeDef *pstcI2s)
Start I2S.
en_result_t I2s_Stop (volatile FM_I2S_TypeDef *pstcI2s)
Stop I2S.
en_result_t I2s_Reset (volatile FM_I2S_TypeDef *pstcI2s)
Reset I2S.
en_result_t I2s_EnableTx (volatile FM_I2S_TypeDef *pstcI2s)
Enable I2S TX.
en_result_t I2s_DisableTx (volatile FM_I2S_TypeDef *pstcI2s)
Disable I2S TX.
en_result_t I2s_EnableRx (volatile FM_I2S_TypeDef *pstcI2s)
Enable I2S RX.
en_result_t I2s_DisableRx (volatile FM_I2S_TypeDef *pstcI2s)
Disable I2S RX.
boolean_t I2s_GetStatus (volatile FM_I2S_TypeDef *pstcI2s, en_i2s_status_t enStatus)
Get status of I2S according to status type.
en_result_t I2s_ClrStatus (volatile FM_I2S_TypeDef *pstcI2s, en_i2s_status_t enStatus)
Clear status of I2S according to status type.
en_result_t I2s_WriteTxFifo (volatile FM_I2S_TypeDef *pstcI2s, uint32_t u32Data)
Write I2S TX FIFO.
uint32_t I2s_ReadRxFifo (volatile FM_I2S_TypeDef *pstcI2s)
Read I2S RX FIFO.
uint8_t I2s_GetTxFifoNumber (volatile FM_I2S_TypeDef *pstcI2s)
Read I2S TX FIFO number.
uint8_t I2s_GetRxFifoNumber (volatile FM_I2S_TypeDef *pstcI2s)
Read I2S RX FIFO number.
Variables
stc_i2s_instance_data_t m_astcI2sInstanceDataLut [I2sInstanceIndexMax]
Look-up table for all enabled I2S instances and their internal data.
stc_i2s_instance_data_t m_astcI2sInstanceDataLut [(uint8_t)(PDL_PERIPHERAL_ENABLE_I2S0==PDL_ON)+(uint8_t)(PDL_PERIPHERAL_ENABLE_I2S1==PDL_ON)]
Look-up table for all enabled I2S instances and their internal data.
Detailed Description
This section describes the interface for the I2S Unit (I2S)
Provided functions of I2S module:
I2s_InitClk()
I2s_DeInitClk()
I2s_EnablePll()
I2s_DisablePll()
I2s_CheckPllReady()
I2s_StartClk()
I2s_StopClk()
I2s_Init()
I2s_DeInit()
I2s_Start()
I2s_Stop()
I2s_GetStatus()
I2s_ClrStatus()
I2s_WriteTxFifo()
I2s_ReadRxFifo()
I2s_GetTxFifoNumber()
I2s_GetRxFifoNumber()
I2s_InitClk() initializes I2S clock setting. I2s_DeInitClk() resets the I2S clock setting.
I2s_EnablePll() enables I2S PLL, I2s_DisablePll() disables I2S PLL. I2s_CheckPllReady() checks if the PLL is stable.
I2s_StartClk() starts clock output to I2S macro, I2s_StopClk() stops clock output to I2S macro.
I2s_Init() initializes an I2S instance according its configuration. I2s_DeInit() de-initializes an I2S instance and resets the hardware to initial values.
I2s_Start() starts I2S operation and I2s_Stop() stops the operation.
I2s_GetStatus() gets the I2s status according to the status type. I2s_ClrStatus() clears the I2s status according to the status type.
I2s_WriteTxFifo() writes the I2S TX FIFO by word and I2s_ReadRxFifo() reads the I2S RX FIFO by word.
I2s_GetTxFifoNumber() gets the number of TX FIFO data count and I2s_GetRxFifoNumber() gets the number of RX FIFO data count.
Typedef Documentation
typedef enum en_i2s0_clk_in en_i2s0_clk_in_t
I2S ch.0 clock selection.
typedef enum en_i2s1_clk_in en_i2s1_clk_in_t
I2S ch.1 clock selection.
typedef enum en_i2s_instance_index en_i2s_instance_index_t
Enumeration to define an index for each enabled I2S instance.
typedef enum en_i2s_irq_sel en_i2s_irq_sel_t
I2S interrupt enable structure.
typedef enum en_i2s_packet_timer en_i2s_packet_timer_t
I2S packet receive completion timer.
typedef enum en_i2s_pll_wait_time en_i2s_pll_wait_time_t
I2S PLL clock stabilization wait times (for 12.2 MHz input clock)
typedef enum en_i2s_start_condition en_i2s_start_condition_t
I2S start condition type (read, write)
typedef enum en_i2s_status en_i2s_status_t
I2S status enumeration.
typedef void(* i2s_error_func_ptr)(uint32_t)
Definition at line 140 of file i2s.h.
typedef void(* i2s_func_ptr_t)(void)
Definition at line 139 of file i2s.h.
typedef struct stc_i2s_clk_config stc_i2s_clk_config_t
I2S clock configuration.
Note:
I2S ch.0 PLL clock output = (Fin * N * M / K) I2S ch.1 PLL clock output = (Fin * N * M1 / K) I2S ch.0 PLL clock = I2S ch.0 PLL clock output / M I2S ch.1 PLL clock = I2S ch.1 PLL clock output / M1 I2S PLL clock output must be in a certain range, check it in the product datasheet.
typedef struct stc_i2s_config stc_i2s_config_t
I2S configuration.
typedef struct stc_i2s_instance_data stc_i2s_instance_data_t
I2S instance data type.
typedef struct stc_i2s_irq_cb stc_i2s_intern_data_t
typedef struct stc_i2s_irq_cb stc_i2s_irq_cb_t
I2S interrupt callback function structure.
typedef struct stc_i2s_irq_en stc_i2s_irq_en_t
I2S interrupt enable structure.
typedef struct stc_i2s_subframe_config stc_i2s_subframe_config_t
I2S sub frame configuration.
Enumeration Type Documentation
enum en_i2s0_clk_in
I2S ch.0 clock selection.
Enumerator:
I2s0UsePllClk
Use PLL clock for I2S clock.
I2s0UseI2sMclki
Use MCLKI input for I2S clock.
Definition at line 162 of file i2s.h.
enum en_i2s1_clk_in
I2S ch.1 clock selection.
Enumerator:
I2s1UsePllClk
Use PLL clock for I2S clock.
I2s1UseI2sMclki
Use MCLKI input for I2S clock.
I2s1UseI2sMclki1
Use MCLKI1 input for I2S clock.
Definition at line 173 of file i2s.h.
enum en_i2s_instance_index
Enumeration to define an index for each enabled I2S instance.
Enumerator:
I2sInstanceIndexI2s0
I2sInstanceIndexI2s1
I2sInstanceIndexMax
Definition at line 358 of file i2s.h.
enum en_i2s_irq_sel
I2S interrupt enable structure.
Enumerator:
I2sTxFifoUnderflow0Irq
TX-FIFO underflow 0 interrupt.
I2sTxFifoUnderflow1Irq
TX-FIFO underflow 1 interrupt.
I2sTxBlockSizeErrIrq
TX block size error interrupt.
I2sFrameErrIrq
Frame error interrupt.
I2sTxFifoOverflowIrq
TX-FIFO overflow interrupt.
I2sTxFifoIrq
TX FIFO interrupt.
I2sRxBlockSizeErrIrq
RX block size error interrupt.
I2sRxFifoUnderflowIrq
RX-FIFO underflow interrupt.
I2sRxFifoOverflowIrq
RX-FIFO overflow interrupt.
I2sRxFifoIdleDetectIrq
RX FIFO idle detection interrupt.
I2sRxFifoIrq
RX FIFO interrupt.
Definition at line 260 of file i2s.h.
enum en_i2s_packet_timer
I2S packet receive completion timer.
Enumerator:
NoOperation
No operation.
Hclk54000Cycles
Timeout cycle: 54000.
Hclk108000Cycles
Timeout cycle: 108000.
Hclk216000Cycles
Timeout cycle: 216000.
Definition at line 217 of file i2s.h.
enum en_i2s_pll_wait_time
I2S PLL clock stabilization wait times (for 12.2 MHz input clock)
Enumerator:
I2sPllWait26us
26 us
I2sPllWait53us
53 us
I2sPllWait106us
106 us
I2sPllWait213us
213 us
I2sPllWait426us
426 us
I2sPllWait853us
853 us
I2sPllWait1ms70
1.70 ms
I2sPllWait3ms41
3.41 ms
Definition at line 146 of file i2s.h.
enum en_i2s_start_condition
I2S start condition type (read, write)
Enumerator:
I2sRead
I2S read.
I2sWrite
I2S write.
Definition at line 207 of file i2s.h.
enum en_i2s_status
I2S status enumeration.
Enumerator:
I2sDmaTxChBlockSizeErr
DMA transmit channel block size error.
I2sDmaRxChBlockSizeErr
DMA receive channel block size error.
I2sFrameErr
Frame error.
I2sTxFifoUnderflow1
TX FIFO underflow interrupt flag 1.
I2sTxFifoUnderflow0
TX FIFO underflow interrupt flag 0.
I2sTxFifoOverflow
TX FIFO overflow interrupt flag.
I2sRxFifoUnderflow
RX FIFO underflow interrupt flag.
I2sRxFifoOverflow
RX FIFO overflow interrupt flag.
I2sRxFifoFifoIdle
RX FIFO idle interrupt flag.
I2sBusy
I2S transmit busy status.
I2sTxFifoMatchThreshold
TX FIFO interrupt flag.
I2sRxFifoMatchThreshold
RX FIFO interrupt flag.
Definition at line 280 of file i2s.h.
Function Documentation
en_result_t I2s_CheckPllReady (void)
This function checks, if the PLL has stabilized.
Precondition:
I2s_InitClk() has to be called before.
Note:
This function can be used for polling, if the PLL has stabilized and in I2s_InitClk() the waiting was disabled
Returns:
- Ok PLL is stabilized
ErrorNotReady PLL is not stabilized
Definition at line 643 of file i2s.c.
en_result_t I2s_ClrStatus (volatile FM_I2S_TypeDef * pstcI2s, en_i2s_status_t enStatus)
Clear status of I2S according to status type.
Parameters:
[in] pstcI2s Pointer to I2S instance
[in] enStatus I2S status type
I2sDmaTxChBlockSizeErr DMA transmit channel block size error
I2sDmaRxChBlockSizeErr DMA receive channel block size error
I2sFrameErr Frame error
I2sTxFifoUnderflow1 TX FIFO underflow interrupt flag 1
I2sTxFifoUnderflow0 TX FIFO underflow interrupt flag 0
I2sTxFifoOverflow TX FIFO overflow interrupt flag
I2sRxFifoUnderflow RX FIFO underflow interrupt flag
I2sRxFifoOverflow RX FIFO overflow interrupt flag
I2sRxFifoFifoIdle RX FIFO idle interrupt flag
I2sBusy I2S transmit busy status
I2sTxFifoMatchThreshold TX FIFO interrupt flag
I2sRxFifoMatchThreshold RX FIFO interrupt flag
Return values:
Ok The status is cleared
ErrorInvalidParameter pstcI2s == NULL or invalid value of enStatus
Note:
The following status is cleared by hardware automatically:
I2sDmaTxChBlockSizeErr
I2sDmaRxChBlockSizeErr
I2sBusy
I2sTxFifoMatchThreshold
I2sRxFifoMatchThreshold
Definition at line 1147 of file i2s.c.
References I2sBusy, I2sDmaRxChBlockSizeErr, I2sDmaTxChBlockSizeErr, I2sFrameErr, I2sRxFifoFifoIdle, I2sRxFifoMatchThreshold, I2sRxFifoOverflow, I2sRxFifoUnderflow, I2sTxFifoMatchThreshold, I2sTxFifoOverflow, I2sTxFifoUnderflow0, and I2sTxFifoUnderflow1.
en_result_t I2s_DeInit (volatile FM_I2S_TypeDef * pstcI2s, boolean_t bTouchNvic)
Deinitializes the I2S module.
Any pending transmission or reception will be aborted and all I2S related registers are reset to their default values.
Parameters:
[in] pstcI2s Pointer to I2S instance
[in] bTouchNvic TRUE = De-Init NVIC
Return values:
Ok I2S module has been successfully deinitialized
ErrorInvalidParameter If one of the following conditions are met:
FM4_I2S0 == NULL
FM4_I2S0InternData == NULL (invalid or disabled I2S unit
Definition at line 868 of file i2s.c.
References I2sDeInitNvic(), I2sGetInternDataPtr(), stc_i2s_irq_cb::pfnFrameErrIrqCb, stc_i2s_irq_cb::pfnRxBlockSizeErrIrqCb, stc_i2s_irq_cb::pfnRxFifoIdleDetectIrqCb, stc_i2s_irq_cb::pfnRxFifoIrqCb, stc_i2s_irq_cb::pfnRxFifoOverflowIrqCb, stc_i2s_irq_cb::pfnRxFifoUnderflowIrqCb, stc_i2s_irq_cb::pfnTxBlockSizeErrIrqCb, stc_i2s_irq_cb::pfnTxFifoIrqCb, stc_i2s_irq_cb::pfnTxFifoOverflowIrqCb, stc_i2s_irq_cb::pfnTxFifoUnderflow0IrqCb, and stc_i2s_irq_cb::pfnTxFifoUnderflow1IrqCb.
en_result_t I2s_DeInitClk (void)
This function de-initialises the I2S PLL clock and reset its registers.
Returns:
Ok on successful clock de-init
Definition at line 553 of file i2s.c.
en_result_t I2s_DisableIrq (volatile FM_I2S_TypeDef * pstcI2s, en_i2s_irq_sel_t enIrqSel)
Disable I2S interrupts.
Parameters:
[in] pstcI2s Pointer to I2S instance
[in] enIrqSel I2S interrupt selection
I2sTxFifoUnderflow0Irq TX FIFO underflow interrupt 0
I2sTxFifoUnderflow1Irq TX FIFO underflow interrupt 1
I2sTxBlockSizeErrIrq DMA TX channel block error interrupt
I2sFrameErrIrq Frame error interrupt
I2sTxFifoOverflowIrq TX FIFO overflow interrupt
I2sTxFifoIrq TX FIFO interrupt
I2sRxBlockSizeErrIrq DMA RX channel block error interrupt
I2sRxFifoIdleDetectIrq RX FIFO idle interrupt
I2sRxFifoUnderflowIrq RX FIFO underflow interrupt
I2sRxFifoOverflowIrq RX FIFO overflow interrupt
I2sRxFifoIrq RX FIFO interrupt
Return values:
Ok Interrupts has been disabled
ErrorInvalidParameter If one of following conditions are met:
pstcI2s == NULL
Definition at line 354 of file i2s.c.
References I2sFrameErrIrq, I2sGetInternDataPtr(), I2sRxBlockSizeErrIrq, I2sRxFifoIdleDetectIrq, I2sRxFifoIrq, I2sRxFifoOverflowIrq, I2sRxFifoUnderflowIrq, I2sTxBlockSizeErrIrq, I2sTxFifoIrq, I2sTxFifoOverflowIrq, I2sTxFifoUnderflow0Irq, and I2sTxFifoUnderflow1Irq.
en_result_t I2s_DisablePll (void)
This function disables I2S PLL.
Returns:
- Ok I2S PLL is disable
Definition at line 623 of file i2s.c.
en_result_t I2s_DisableRx (volatile FM_I2S_TypeDef * pstcI2s)
Disable I2S RX.
Return values:
Ok I2S module has been stopped
Definition at line 1011 of file i2s.c.
en_result_t I2s_DisableTx (volatile FM_I2S_TypeDef * pstcI2s)
Disable I2S TX.
Return values:
Ok I2S module has been stopped
Definition at line 981 of file i2s.c.
en_result_t I2s_EnableIrq (volatile FM_I2S_TypeDef * pstcI2s, en_i2s_irq_sel_t enIrqSel)
Enable I2S interrupts.
Parameters:
[in] pstcI2s Pointer to I2S instance
[in] enIrqSel I2S interrupt selection
I2sTxFifoUnderflow0Irq TX FIFO underflow interrupt 0
I2sTxFifoUnderflow1Irq TX FIFO underflow interrupt 1
I2sTxBlockSizeErrIrq DMA TX channel block error interrupt
I2sFrameErrIrq Frame error interrupt
I2sTxFifoOverflowIrq TX FIFO overflow interrupt
I2sTxFifoIrq TX FIFO interrupt
I2sRxBlockSizeErrIrq DMA RX channel block error interrupt
I2sRxFifoIdleDetectIrq RX FIFO idle interrupt
I2sRxFifoUnderflowIrq RX FIFO underflow interrupt
I2sRxFifoOverflowIrq RX FIFO overflow interrupt
I2sRxFifoIrq RX FIFO interrupt
Return values:
Ok Interrupts has been enabled
ErrorInvalidParameter If one of following conditions are met:
pstcI2s == NULL
Definition at line 276 of file i2s.c.
References I2sFrameErrIrq, I2sGetInternDataPtr(), I2sRxBlockSizeErrIrq, I2sRxFifoIdleDetectIrq, I2sRxFifoIrq, I2sRxFifoOverflowIrq, I2sRxFifoUnderflowIrq, I2sTxBlockSizeErrIrq, I2sTxFifoIrq, I2sTxFifoOverflowIrq, I2sTxFifoUnderflow0Irq, and I2sTxFifoUnderflow1Irq.
en_result_t I2s_EnablePll (boolean_t bWaitPolling)
This function enables I2S PLL.
Note:
This function can be used for polling if the input parameter is true and returns directly after enable PLL.
Returns:
- Ok I2S PLL is enabled
ErrorTimeout I2S PLL is timeout
Definition at line 587 of file i2s.c.
en_result_t I2s_EnableRx (volatile FM_I2S_TypeDef * pstcI2s)
Enable I2S RX.
Return values:
Ok I2S module has been stopped
Definition at line 996 of file i2s.c.
en_result_t I2s_EnableTx (volatile FM_I2S_TypeDef * pstcI2s)
Enable I2S TX.
Return values:
Ok I2S module has been stopped
Definition at line 966 of file i2s.c.
uint8_t I2s_GetRxFifoNumber (volatile FM_I2S_TypeDef * pstcI2s)
Read I2S RX FIFO number.
Parameters:
pstcI2s Pointer to I2S instance
Return values:
The receive data in FIFO
Note:
It is number of word
Definition at line 1259 of file i2s.c.
boolean_t I2s_GetStatus (volatile FM_I2S_TypeDef * pstcI2s, en_i2s_status_t enStatus)
Get status of I2S according to status type.
Parameters:
[in] pstcI2s Pointer to I2S instance
[in] enStatus I2S status type
I2sDmaTxChBlockSizeErr DMA transmit channel block size error
I2sDmaRxChBlockSizeErr DMA receive channel block size error
I2sFrameErr Frame error
I2sTxFifoUnderflow1 TX FIFO underflow interrupt flag 1
I2sTxFifoUnderflow0 TX FIFO underflow interrupt flag 0
I2sTxFifoOverflow TX FIFO overflow interrupt flag
I2sRxFifoUnderflow RX FIFO underflow interrupt flag
I2sRxFifoOverflow RX FIFO overflow interrupt flag
I2sRxFifoFifoIdle RX FIFO idle interrupt flag
I2sBusy I2S transmit busy status
I2sTxFifoMatchThreshold TX FIFO interrupt flag
I2sRxFifoMatchThreshold RX FIFO interrupt flag
Return values:
FALSE If one of following conditions are met:
Block size of the DMA transmit channel is set to a value smaller than the transmit FIFO threshold value [enStatus = I2sDmaTxChBlockSizeErr]
Block size of the DMA receive channel is set to a value larger than the receive FIFO threshold value [enStatus = I2sDmaRxChBlockSizeErr]
Frame sync signal is received at the frame rate that was set. [enStatus = I2sFrameErr]
Transmit FIFO don't underflow at the frame start [enStatus = I2sTxFifoUnderflow1]
Transmit FIFO don't underflow during frame transmission [enStatus = I2sTxFifoUnderflow0]
Transmit FIFO don't overflow [enStatus = I2sTxFifoOverflow]
Receive FIFO don't underflow [enStatus = I2sRxFifoUnderflow]
Receive FIFO don't overflow [enStatus = I2sRxFifoOverflow]
Receive FIFO is empty when the timer reaches the time that was set [enStatus = I2sRxFifoFifoIdle]
Serial transmit control unit is not busy. [enStatus =I2sBusy]
Transmit FIFO empty slot is less than the TX FIFO threshold value [enStatus = I2sTxFifoMatchThreshold]
Receive FIFO data count is less than the RX FIFO threshold value [enStatus = I2sRxFifoMatchThreshold]
TRUE If one of following conditions are met:
Block size of the DMA transmit channel is set to a value larger than the transmit FIFO threshold value [enStatus = I2sDmaTxChBlockSizeErr]
Block size of the DMA receive channel is set to a value larger than the receive FIFO threshold value [enStatus = I2sDmaRxChBlockSizeErr]
Frame sync signal cannot be received at the frame rate that was set. [enStatus = I2sFrameErr]
Transmit FIFO underflows at the frame start [enStatus = I2sTxFifoUnderflow1]
Transmit FIFO underflows during frame transmission [enStatus = I2sTxFifoUnderflow0]
Transmit FIFO overflows [enStatus = I2sTxFifoOverflow]
Receive FIFO underflows [enStatus = I2sRxFifoUnderflow]
Receive FIFO overflows [enStatus = I2sRxFifoOverflow]
Receive FIFO is not empty when the timer reaches the time that was set [enStatus = I2sRxFifoFifoIdle]
Serial transmit control unit is busy. [enStatus =I2sBusy]
Transmit FIFO empty slot meets or exceeds the TX FIFO threshold value [enStatus = I2sTxFifoMatchThreshold]
Receive FIFO data count meets or exceeds the RX FIFO threshold value [enStatus = I2sRxFifoMatchThreshold]
Definition at line 1067 of file i2s.c.
References I2sBusy, I2sDmaRxChBlockSizeErr, I2sDmaTxChBlockSizeErr, I2sFrameErr, I2sRxFifoFifoIdle, I2sRxFifoMatchThreshold, I2sRxFifoOverflow, I2sRxFifoUnderflow, I2sTxFifoMatchThreshold, I2sTxFifoOverflow, I2sTxFifoUnderflow0, and I2sTxFifoUnderflow1.
uint8_t I2s_GetTxFifoNumber (volatile FM_I2S_TypeDef * pstcI2s)
Read I2S TX FIFO number.
Parameters:
pstcI2s Pointer to I2S instance
Return values:
The transmit data in FIFO
Note:
It is number of word
Definition at line 1244 of file i2s.c.
en_result_t I2s_Init (volatile FM_I2S_TypeDef * pstcI2s, stc_i2s_config_t * pstcConfig)
This function initialises one specific I2S module with the parameters provided in the given configuration structure. After successful initialization the I2S module is ready to use.
I2S_Init() has to be called with the parameter pstcConfig of type stc_i2s_config_t, the basic I2S settings automatic retransmission, the I2s baudrate, and the error and status callback function can be set.
All values in pstcConfig have to be in valid range (see i2s.h for allowed ranges of dedicated parameters). The error and status change callback functions can be NULL. In this case no information of error or status changes will be reported to the user application.
To reset and disable the I2S module the function I2s_DeInit() has to be used.
Parameters:
[in] pstcI2s Pointer to I2S instance
[in] pstcConfig Pointer to I2S configuration parameters
Returns:
- Ok on successful init
ErrorInvalidParameter if bit rate is 0 or pointers are NULL
Definition at line 708 of file i2s.c.
References stc_i2s_config::bBclkDivByMclk, stc_i2s_config::bBitExtensionHigh, stc_i2s_config::bClockpolarity, stc_i2s_config::bFifoTwoWords, stc_i2s_irq_en::bFrameErrIrq, stc_i2s_config::bFreeRunMode, stc_i2s_config::bLsbFirst, stc_i2s_config::bMaskBit, stc_i2s_config::bMasterMode, stc_i2s_irq_en::bRxBlockSizeErrIrq, stc_i2s_config::bRxDmaEnable, stc_i2s_config::bRxEnable, stc_i2s_irq_en::bRxFifoIdleDetectIrq, stc_i2s_irq_en::bRxFifoIrq, stc_i2s_irq_en::bRxFifoOverflowIrq, stc_i2s_irq_en::bRxFifoUnderflowIrq, stc_i2s_config::bSampleAtEnd, stc_i2s_config::bSubFrame01, stc_i2s_config::bTouchNvic, stc_i2s_irq_en::bTxBlockSizeErrIrq, stc_i2s_config::bTxDmaEnable, stc_i2s_config::bTxEnable, stc_i2s_irq_en::bTxFifoIrq, stc_i2s_irq_en::bTxFifoOverflowIrq, stc_i2s_irq_en::bTxFifoUnderflow0Irq, stc_i2s_irq_en::bTxFifoUnderflow1Irq, stc_i2s_config::bWordSelectLength, stc_i2s_config::bWordSelectPolarity, stc_i2s_config::bWordSelectSamePhase, stc_i2s_config::enPacketReceiveCompletionTimer, Hclk108000Cycles, Hclk216000Cycles, Hclk54000Cycles, I2sGetInternDataPtr(), I2sInitNvic(), NoOperation, stc_i2s_irq_cb::pfnFrameErrIrqCb, stc_i2s_irq_cb::pfnRxBlockSizeErrIrqCb, stc_i2s_irq_cb::pfnRxFifoIdleDetectIrqCb, stc_i2s_irq_cb::pfnRxFifoIrqCb, stc_i2s_irq_cb::pfnRxFifoOverflowIrqCb, stc_i2s_irq_cb::pfnRxFifoUnderflowIrqCb, stc_i2s_irq_cb::pfnTxBlockSizeErrIrqCb, stc_i2s_irq_cb::pfnTxFifoIrqCb, stc_i2s_irq_cb::pfnTxFifoOverflowIrqCb, stc_i2s_irq_cb::pfnTxFifoUnderflow0IrqCb, stc_i2s_irq_cb::pfnTxFifoUnderflow1IrqCb, stc_i2s_config::pstcIrqCb, stc_i2s_config::pstcIrqEn, stc_i2s_config::stcSubframe0, stc_i2s_config::stcSubframe1, stc_i2s_config::u16OverheadBits, stc_i2s_config::u32S0ch, stc_i2s_config::u32S1ch, stc_i2s_config::u8ClockDiv, stc_i2s_config::u8RxFifoThreshold, stc_i2s_subframe_config::u8Snchl, stc_i2s_subframe_config::u8Snchn, stc_i2s_subframe_config::u8Snwdl, and stc_i2s_config::u8TxFifoThreshold.
en_result_t I2s_InitClk (stc_i2s_clk_config_t * pstcConfig)
This function initialises the I2S PLL clock according to the given parameters.
Attention:
The clock parameters are only valid for 19.2 MHz main clock
To reset and disable the I2S clock module the function I2s_DeInitClk() has to be used.
Parameters:
[in] pstcConfig Pointer to I2S clock configuration parameters
Returns:
- Ok on successful clock init
ErrorInvalidParameter wrong enumerator used
ErrorTimeout Clock off or PLL wait too long
Definition at line 454 of file i2s.c.
References stc_i2s_clk_config::enI2s0ClkIn, stc_i2s_clk_config::enI2s1ClkIn, stc_i2s_clk_config::enI2sPllWaitTime, I2s0UseI2sMclki, I2s0UsePllClk, I2s1UseI2sMclki, I2s1UseI2sMclki1, I2s1UsePllClk, I2sPllWait106us, I2sPllWait1ms70, I2sPllWait213us, I2sPllWait26us, I2sPllWait3ms41, I2sPllWait426us, I2sPllWait53us, I2sPllWait853us, stc_i2s_clk_config::u8Pllk, stc_i2s_clk_config::u8Pllm, and stc_i2s_clk_config::u8Plln.
uint32_t I2s_ReadRxFifo (volatile FM_I2S_TypeDef * pstcI2s)
Read I2S RX FIFO.
Parameters:
pstcI2s Pointer to I2S instance
Return values:
The receive data in FIFO
Note:
The FIFO is always read by word
Definition at line 1229 of file i2s.c.
en_result_t I2s_Reset (volatile FM_I2S_TypeDef * pstcI2s)
Reset I2S.
Return values:
Ok I2S module has been stopped
Definition at line 953 of file i2s.c.
en_result_t I2s_Start (volatile FM_I2S_TypeDef * pstcI2s)
Start I2S.
Return values:
Ok I2S module has been started
Definition at line 927 of file i2s.c.
void I2s_StartClk (volatile FM_I2S_TypeDef * pstcI2s)
This function starts the I2S clock.
Definition at line 657 of file i2s.c.
References I2S0, and I2S1.
en_result_t I2s_Stop (volatile FM_I2S_TypeDef * pstcI2s)
Stop I2S.
Return values:
Ok I2S module has been stopped
Definition at line 940 of file i2s.c.
void I2s_StopClk (volatile FM_I2S_TypeDef * pstcI2s)
This function stops the I2S clock.
Definition at line 673 of file i2s.c.
References I2S0, and I2S1.
en_result_t I2s_WriteTxFifo (volatile FM_I2S_TypeDef * pstcI2s, uint32_t u32Data)
Write I2S TX FIFO.
Parameters:
pstcI2s Pointer to I2S instance
u32Data Data to be written
Return values:
Ok Data has been written
ErrorInvalidParameter pstcI2s == NULL
Note:
The FIFO is always written by word
Definition at line 1207 of file i2s.c.
static void I2sDeInitNvic (volatile FM_I2S_TypeDef * pstcI2s) [static]
Clear NVIC Interrupt depending on I2S instance.
Parameters:
pstcI2s Pointer to I2S instance
Definition at line 430 of file i2s.c.
References PDL_DEFAULT_INTERRUPT_LEVEL.
Referenced by I2s_DeInit().
static stc_i2s_intern_data_t* I2sGetInternDataPtr (volatile FM_I2S_TypeDef * pstcI2s) [static]
Return the internal data for a certain I2S instance.
Parameters:
pstcI2s Pointer to I2S instance
Returns:
Pointer to internal data or NULL if instance is not enabled (or not known)
Definition at line 113 of file i2s.c.
References I2S_INSTANCE_COUNT, and stc_i2s_instance_data::stcInternData.
Referenced by I2s_DeInit(), I2s_DisableIrq(), I2s_EnableIrq(), and I2s_Init().
static void I2sInitNvic (volatile FM_I2S_TypeDef * pstcI2s) [static]
Set NVIC Interrupt depending on I2S instance.
Parameters:
pstcI2s Pointer to I2S instance
Definition at line 416 of file i2s.c.
Referenced by I2s_Init().
void I2sIrqHandler (volatile FM_I2S_TypeDef * pstcI2s, stc_i2s_intern_data_t * pstcI2sInternData)
I2S instance interrupt service routine.
I2S instance interrupt service routine, clear interrupt cause and
Parameters:
pstcI2s Pointer to I2S instance
pstcI2sInternData Pointer to I2S intern data
Definition at line 140 of file i2s.c.
References stc_i2s_irq_cb::pfnFrameErrIrqCb, stc_i2s_irq_cb::pfnRxBlockSizeErrIrqCb, stc_i2s_irq_cb::pfnRxFifoIdleDetectIrqCb, stc_i2s_irq_cb::pfnRxFifoIrqCb, stc_i2s_irq_cb::pfnRxFifoOverflowIrqCb, stc_i2s_irq_cb::pfnRxFifoUnderflowIrqCb, stc_i2s_irq_cb::pfnTxBlockSizeErrIrqCb, stc_i2s_irq_cb::pfnTxFifoIrqCb, stc_i2s_irq_cb::pfnTxFifoOverflowIrqCb, stc_i2s_irq_cb::pfnTxFifoUnderflow0IrqCb, and stc_i2s_irq_cb::pfnTxFifoUnderflow1IrqCb.
Variable Documentation
stc_i2s_instance_data_t m_astcI2sInstanceDataLut[I2sInstanceIndexMax]
Initial value:
{
    {
        & (*(volatile  FM_I2S_TypeDef  *) FM_I2S0_BASE) ,
        0u
    },
    {
        & (*(volatile  FM_I2S_TypeDef  *) FM_I2S1_BASE) ,
        0u
    }
}
Look-up table for all enabled I2S instances and their internal data.
Definition at line 72 of file i2s.c.
stc_i2s_instance_data_t m_astcI2sInstanceDataLut[(uint8_t)(PDL_PERIPHERAL_ENABLE_I2S0==PDL_ON)+(uint8_t)(PDL_PERIPHERAL_ENABLE_I2S1==PDL_ON)]
Look-up table for all enabled I2S instances and their internal data.
Definition at line 72 of file i2s.c.