PDL for FM Family: Work Flash (WFlash)
Work Flash (WFlash)
Defines
#define Flash_Read(addr) *(volatile uint16_t*)((uint32_t)(addr))
Read a half word data from Flash.
#define Flash_Write(addr, data) *(volatile uint16_t*)((uint32_t)(addr)) = (uint16_t)(data)
Wirte a half word data into Flash.
#define WFLASH_CODE1 0x0AA8u
#define WFLASH_CODE2 0x0554u
#define WFLASH_RET_OK 0u
#define WFLASH_RET_INVALID_PARA 1u
#define WFLASH_RET_ABNORMAL 2u
#define WFLASH_CHK_TOGG_NORMAL 0u
#define WFLASH_CHK_TOGG_ABNORMAL 1u
#define WFLASH_CHK_DPOL_NORMAL 0u
#define WFLASH_CHK_DPOL_ABNORMAL 1u
#define WFLASH_CHK_DPOL_MASK (uint16_t)0x0080u
#define WFLASH_CHK_TOGG_MASK (uint16_t)0x0040u
#define WFLASH_CHK_TLOV_MASK (uint16_t)0x0020u
#define WFLASH_BASE_ADDR (0x200C0000u)
Functions
static uint8_t WFlash_CheckToggle (uint16_t *pu16Addr)
automatic algorithm of flash memory execution
static void WFlash_ReadResetCmd (uint16_t *pu16ResetSecAddr)
Issue read/reset command.
en_result_t WFlash_ChipErase (void)
Flash chip erase.
en_result_t WFlash_SectorErase (uint16_t *pu16SecAddr)
Flash sector erase.
en_result_t WFlash_WriteData32Bit (uint32_t *pu32WriteAddr, uint32_t *pu32WriteData, uint32_t u32Size)
Flash word write with ECC.
en_result_t WFlash_WriteData16Bit (uint16_t *pu16WriteAddr, uint16_t *pu16WriteData, uint32_t u32Size)
Flash half-word write with ECC.
Detailed Description
Provided functions of Work Flash operation:
WFlash_ChipErase()
WFlash_SectorErase()
WFlash_WriteData32Bit()
WFlash_WriteData16Bit()
What is Work Flash?
Work Flash have independent area, which is sperated from Main Flash, thus the Flash operation API can be called derectly from Main Flash.
How to use Work Flash module?
WFlash_ChipErase() can erase whole chip space of Work Flash. WFlash_SectorErase() can erase one selected sector. WFlash_WriteData32Bit() writes data into Flash area with word align. WFlash_WriteData16Bit() writes data into Flash area with half-word align.
Define Documentation
#define Flash_Read (addr) *(volatile uint16_t*)((uint32_t)(addr))
Read a half word data from Flash.
Parameters:
addr Pointer to read data address
Definition at line 71 of file workflash.c.
Referenced by WFlash_CheckToggle(), WFlash_ReadResetCmd(), WFlash_WriteData16Bit(), and WFlash_WriteData32Bit().
#define Flash_Write (addr, data) *(volatile uint16_t*)((uint32_t)(addr)) = (uint16_t)(data)
Wirte a half word data into Flash.
Parameters:
addr Pointer to read data address
data Write data
Definition at line 80 of file workflash.c.
Referenced by WFlash_ChipErase(), WFlash_ReadResetCmd(), WFlash_SectorErase(), WFlash_WriteData16Bit(), and WFlash_WriteData32Bit().
#define WFLASH_BASE_ADDR (0x200C0000u)
Definition at line 105 of file workflash.h.
Referenced by WFlash_ChipErase(), WFlash_SectorErase(), WFlash_WriteData16Bit(), and WFlash_WriteData32Bit().
#define WFLASH_CHK_DPOL_ABNORMAL 1u
Definition at line 99 of file workflash.h.
#define WFLASH_CHK_DPOL_MASK (uint16_t)0x0080u
Definition at line 101 of file workflash.h.
#define WFLASH_CHK_DPOL_NORMAL 0u
Definition at line 98 of file workflash.h.
#define WFLASH_CHK_TLOV_MASK (uint16_t)0x0020u
Definition at line 103 of file workflash.h.
Referenced by WFlash_CheckToggle().
#define WFLASH_CHK_TOGG_ABNORMAL 1u
Definition at line 96 of file workflash.h.
Referenced by WFlash_CheckToggle(), WFlash_ChipErase(), WFlash_SectorErase(), WFlash_WriteData16Bit(), and WFlash_WriteData32Bit().
#define WFLASH_CHK_TOGG_MASK (uint16_t)0x0040u
Definition at line 102 of file workflash.h.
Referenced by WFlash_CheckToggle().
#define WFLASH_CHK_TOGG_NORMAL 0u
Definition at line 95 of file workflash.h.
Referenced by WFlash_CheckToggle().
#define WFLASH_CODE1 0x0AA8u
Definition at line 88 of file workflash.h.
Referenced by WFlash_ChipErase(), WFlash_SectorErase(), WFlash_WriteData16Bit(), and WFlash_WriteData32Bit().
#define WFLASH_CODE2 0x0554u
Definition at line 89 of file workflash.h.
Referenced by WFlash_ChipErase(), WFlash_SectorErase(), WFlash_WriteData16Bit(), and WFlash_WriteData32Bit().
#define WFLASH_RET_ABNORMAL 2u
Definition at line 93 of file workflash.h.
#define WFLASH_RET_INVALID_PARA 1u
Definition at line 92 of file workflash.h.
#define WFLASH_RET_OK 0u
Definition at line 91 of file workflash.h.
Function Documentation
static uint8_t WFlash_CheckToggle (uint16_t * pu16Addr) [static]
automatic algorithm of flash memory execution
Parameters:
pu16Addr address of flash data
Returns:
Operation status
Return values:
MFLASH_RET_OK
MFLASH_RET_ABNORMAL
MFLASH_RET_INVALID_PARA
Definition at line 345 of file workflash.c.
References Flash_Read, WFLASH_CHK_TLOV_MASK, WFLASH_CHK_TOGG_ABNORMAL, WFLASH_CHK_TOGG_MASK, and WFLASH_CHK_TOGG_NORMAL.
Referenced by WFlash_ChipErase(), WFlash_SectorErase(), WFlash_WriteData16Bit(), and WFlash_WriteData32Bit().
en_result_t WFlash_ChipErase (void)
Flash chip erase.
Returns:
Operation status
Return values:
Ok Chip erase successfully done.
ErrorInvalidParameter If one of following conditions are met:
automatic algorithm of flash memory execution abnormally
Definition at line 121 of file workflash.c.
References Flash_Write, WFLASH_BASE_ADDR, WFlash_CheckToggle(), WFLASH_CHK_TOGG_ABNORMAL, WFLASH_CODE1, WFLASH_CODE2, and WFlash_ReadResetCmd().
static void WFlash_ReadResetCmd (uint16_t * pu16ResetSecAddr) [static]
Issue read/reset command.
Parameters:
pu16ResetSecAddr address of reset sector
Returns:
None
Definition at line 98 of file workflash.c.
References Flash_Read, and Flash_Write.
Referenced by WFlash_ChipErase(), WFlash_SectorErase(), WFlash_WriteData16Bit(), and WFlash_WriteData32Bit().
en_result_t WFlash_SectorErase (uint16_t * pu16SecAddr)
Flash sector erase.
Parameters:
pu16SecAddr address of flash sector
Returns:
Operation status
Return values:
Ok Chip erase successfully done.
ErrorInvalidParameter If one of following conditions are met:
automatic algorithm of flash memory execution abnormally
Definition at line 169 of file workflash.c.
References Flash_Write, WFLASH_BASE_ADDR, WFlash_CheckToggle(), WFLASH_CHK_TOGG_ABNORMAL, WFLASH_CODE1, WFLASH_CODE2, and WFlash_ReadResetCmd().
en_result_t WFlash_WriteData16Bit (uint16_t * pu16WriteAddr, uint16_t * pu16WriteData, uint32_t u32Size)
Flash half-word write with ECC.
Parameters:
pu16WriteAddr address of flash data
pu16WriteData pointer to write data
u32Size data size, 1 indicates 1 16-bit data, always set it to even
Returns:
Operation status
Return values:
Ok Chip erase successfully done.
ErrorInvalidParameter If one of following conditions are met:
automatic algorithm of flash memory execution abnormally
Definition at line 285 of file workflash.c.
References Flash_Read, Flash_Write, WFLASH_BASE_ADDR, WFlash_CheckToggle(), WFLASH_CHK_TOGG_ABNORMAL, WFLASH_CODE1, WFLASH_CODE2, and WFlash_ReadResetCmd().
en_result_t WFlash_WriteData32Bit (uint32_t * pu32WriteAddr, uint32_t * pu32WriteData, uint32_t u32Size)
Flash word write with ECC.
Parameters:
pu32WriteAddr address of flash data
pu32WriteData pointer to write data
u32Size data size, 1 indicates 1 16-bit data, always set it to even
Returns:
Operation status
Return values:
Ok Chip erase successfully done.
ErrorInvalidParameter If one of following conditions are met:
automatic algorithm of flash memory execution abnormally
Definition at line 221 of file workflash.c.
References Flash_Read, Flash_Write, WFLASH_BASE_ADDR, WFlash_CheckToggle(), WFLASH_CHK_TOGG_ABNORMAL, WFLASH_CODE1, WFLASH_CODE2, and WFlash_ReadResetCmd().