PDL for FM Family: Dual Flash (DFlash)
Dual Flash (DFlash)
Defines
#define Flash_Read(addr) *(volatile uint8_t*)((uint32_t)(addr))
Read a half word data from Flash.
#define Flash_Write(addr, data) *(volatile uint8_t*)((uint32_t)(addr)) = (uint8_t)(data)
Wirte a half word data into Flash.
#define FLASH_LOW_BANK1_START_ADDR (uint8_t*)(0x00000000ul)
#define FLASH_LOW_BANK1_END_ADDR (uint8_t*)(0x00003FFFul)
#define FLASH_LOW_BANK2_START_ADDR (uint8_t*)(0x00200000ul)
#define FLASH_LOW_BANK2_END_ADDR (uint8_t*)(0x00208000ul)
#define FLASH_HIGH_BANK_START_ADDR (uint8_t*)(0x00004000ul)
#define FLASH_HIGH_BANK_END_ADDR (uint8_t*)(0x00080000ul)
#define DFLASH_RET_OK 0u
#define DFLASH_RET_INVALID_PARA 1u
#define DFLASH_RET_ABNORMAL 2u
#define DFLASH_CHK_TOGG_NORMAL 0u
#define DFLASH_CHK_TOGG_ABNORMAL 1u
#define DFLASH_CHK_DPOL_NORMAL 0u
#define DFLASH_CHK_DPOL_ABNORMAL 1u
#define DFLASH_CHK_DPOL_MASK (uint8_t)0x80u
#define DFLASH_CHK_TOGG_MASK (uint8_t)0x40u
#define DFLASH_CHK_TLOV_MASK (uint8_t)0x20u
Functions
static uint8_t DFlash_CheckToggle (uint8_t *pAddr)
automatic algorithm of flash memory execution
static uint8_t DFlash_ReadResetCmd (uint8_t *pResetSecAddr)
Issue read/reset command.
en_result_t DFlash_ChipErase (void)
Flash chip erase.
en_result_t DFlash_SectorErase (uint16_t *pu16SecAddr)
Flash sector erase.
en_result_t DFlash_WriteData32Bit (uint32_t *pu32Addr, uint32_t *pu32Data, uint32_t u32Size)
Flash word write.
en_result_t DFlash_WriteData16Bit (uint16_t *pu16Addr, uint16_t *pu16Data, uint32_t u32Size)
Flash half word write.
en_result_t DFlash_WriteData8Bit (uint8_t *pu8Addr, uint8_t *pu8Data, uint32_t u32Size)
Flash byte write.
Detailed Description
Provided functions of Dual Flash operation:
DFlash_ChipErase()
DFlash_SectorErase()
DFlash_WriteData32Bit()
DFlash_WriteData16Bit()
DFlash_WriteData8Bit()
Dual Flash has two independent banks, which can be erase and written by each other. Before using Daul Flash driver, make sure the Flash operation code is in different bank of the bank to be erase and written.
In IAR environment, Flash code is located at 0x8000 by following way:
1) First adding following line in the ICF file
place at address mem:0x00008000 { section .flashcode };
2) Then adding the following line at each Flash operation API:
#pragma location=".flashcode"
In Keil environment, Flash code can be re-located by following way:
Define a ROM area in the "target"
Right click dual_flash.c
[Options for dual_flash.c]->[code/const]->select the ROM area defined.
DFlash_ChipErase() can erase whole chip space of dual Flash.
DFlash_SectorErase() can erase one selected sector.
DFlash_WriteData32Bit() writes data into Flash area with word align
DFlash_WriteData16Bit() writes data into Flash area with half word align
DFlash_WriteData8Bit() writes data into Flash area with byte align
Define Documentation
#define DFLASH_CHK_DPOL_ABNORMAL 1u
Definition at line 125 of file dualflash.h.
#define DFLASH_CHK_DPOL_MASK (uint8_t)0x80u
Definition at line 127 of file dualflash.h.
#define DFLASH_CHK_DPOL_NORMAL 0u
Definition at line 124 of file dualflash.h.
#define DFLASH_CHK_TLOV_MASK (uint8_t)0x20u
Definition at line 129 of file dualflash.h.
Referenced by DFlash_CheckToggle().
#define DFLASH_CHK_TOGG_ABNORMAL 1u
Definition at line 122 of file dualflash.h.
Referenced by DFlash_CheckToggle(), DFlash_ChipErase(), DFlash_SectorErase(), DFlash_WriteData16Bit(), DFlash_WriteData32Bit(), and DFlash_WriteData8Bit().
#define DFLASH_CHK_TOGG_MASK (uint8_t)0x40u
Definition at line 128 of file dualflash.h.
Referenced by DFlash_CheckToggle().
#define DFLASH_CHK_TOGG_NORMAL 0u
Definition at line 121 of file dualflash.h.
Referenced by DFlash_CheckToggle().
#define DFLASH_RET_ABNORMAL 2u
Definition at line 119 of file dualflash.h.
#define DFLASH_RET_INVALID_PARA 1u
Definition at line 118 of file dualflash.h.
#define DFLASH_RET_OK 0u
Definition at line 117 of file dualflash.h.
#define FLASH_HIGH_BANK_END_ADDR (uint8_t*)(0x00080000ul)
Definition at line 115 of file dualflash.h.
#define FLASH_HIGH_BANK_START_ADDR (uint8_t*)(0x00004000ul)
Definition at line 114 of file dualflash.h.
#define FLASH_LOW_BANK1_END_ADDR (uint8_t*)(0x00003FFFul)
Definition at line 111 of file dualflash.h.
#define FLASH_LOW_BANK1_START_ADDR (uint8_t*)(0x00000000ul)
Definition at line 110 of file dualflash.h.
#define FLASH_LOW_BANK2_END_ADDR (uint8_t*)(0x00208000ul)
Definition at line 113 of file dualflash.h.
#define FLASH_LOW_BANK2_START_ADDR (uint8_t*)(0x00200000ul)
Definition at line 112 of file dualflash.h.
#define Flash_Read (addr) *(volatile uint8_t*)((uint32_t)(addr))
Read a half word data from Flash.
Parameters:
addr Pointer to read data address
Definition at line 74 of file dualflash.c.
Referenced by DFlash_CheckToggle(), DFlash_ReadResetCmd(), DFlash_WriteData16Bit(), DFlash_WriteData32Bit(), and DFlash_WriteData8Bit().
#define Flash_Write (addr, data) *(volatile uint8_t*)((uint32_t)(addr)) = (uint8_t)(data)
Wirte a half word data into Flash.
Parameters:
addr Pointer to read data address
data Write data
Definition at line 83 of file dualflash.c.
Referenced by DFlash_ChipErase(), DFlash_ReadResetCmd(), DFlash_SectorErase(), DFlash_WriteData16Bit(), DFlash_WriteData32Bit(), and DFlash_WriteData8Bit().
Function Documentation
static uint8_t DFlash_CheckToggle (uint8_t * pAddr) [static]
automatic algorithm of flash memory execution
Parameters:
pAddr address of flash data
Returns:
Operation status
Return values:
DFLASH_RET_OK
DFLASH_RET_ABNORMAL
DFLASH_RET_INVALID_PARA
Definition at line 375 of file dualflash.c.
References DFLASH_CHK_TLOV_MASK, DFLASH_CHK_TOGG_ABNORMAL, DFLASH_CHK_TOGG_MASK, DFLASH_CHK_TOGG_NORMAL, and Flash_Read.
Referenced by DFlash_ChipErase(), DFlash_SectorErase(), DFlash_WriteData16Bit(), DFlash_WriteData32Bit(), and DFlash_WriteData8Bit().
en_result_t DFlash_ChipErase (void)
Flash chip erase.
Return values:
Ok Chip erase successfully done.
ErrorInvalidParameter If one of following conditions are met:
automatic algorithm of flash memory execution abnormally
Definition at line 143 of file dualflash.c.
References DFlash_CheckToggle(), DFLASH_CHK_TOGG_ABNORMAL, DFlash_ReadResetCmd(), and Flash_Write.
static uint8_t DFlash_ReadResetCmd (uint8_t * pResetSecAddr) [static]
Issue read/reset command.
Parameters:
pResetSecAddr address of reset sector
Return values:
Dummy data
Definition at line 121 of file dualflash.c.
References Flash_Read, and Flash_Write.
Referenced by DFlash_ChipErase(), DFlash_SectorErase(), DFlash_WriteData16Bit(), DFlash_WriteData32Bit(), and DFlash_WriteData8Bit().
en_result_t DFlash_SectorErase (uint16_t * pu16SecAddr)
Flash sector erase.
Parameters:
pu16SecAddr address of flash sector
Returns:
Operation status
Return values:
Ok sector erase successfully done.
ErrorInvalidParameter If one of following conditions are met:
automatic algorithm of flash memory execution abnormally
Definition at line 184 of file dualflash.c.
References DFlash_CheckToggle(), DFLASH_CHK_TOGG_ABNORMAL, DFlash_ReadResetCmd(), and Flash_Write.
en_result_t DFlash_WriteData16Bit (uint16_t * pu16Addr, uint16_t * pu16Data, uint32_t u32Size)
Flash half word write.
Parameters:
pu16Addr address of flash data
pu16Data pointer to write data
u32Size data size, 1 indicates 1 16-bit data
Returns:
Operation status
Return values:
Ok sector erase successfully done.
ErrorInvalidParameter If one of following conditions are met:
automatic algorithm of flash memory execution abnormally
Definition at line 277 of file dualflash.c.
References DFlash_CheckToggle(), DFLASH_CHK_TOGG_ABNORMAL, DFlash_ReadResetCmd(), Flash_Read, and Flash_Write.
en_result_t DFlash_WriteData32Bit (uint32_t * pu32Addr, uint32_t * pu32Data, uint32_t u32Size)
Flash word write.
Parameters:
pu32Addr address of flash data
pu32Data pointer to write data
u32Size data size, 1 indicates 1 32-bit data
Returns:
Operation status
Return values:
Ok sector erase successfully done.
ErrorInvalidParameter If one of following conditions are met:
automatic algorithm of flash memory execution abnormally
Definition at line 225 of file dualflash.c.
References DFlash_CheckToggle(), DFLASH_CHK_TOGG_ABNORMAL, DFlash_ReadResetCmd(), Flash_Read, and Flash_Write.
en_result_t DFlash_WriteData8Bit (uint8_t * pu8Addr, uint8_t * pu8Data, uint32_t u32Size)
Flash byte write.
Parameters:
pu8Addr address of flash data
pu8Data pointer to write data
u32Size data size, 1 indicates 1 8-bit data
Returns:
Operation status
Return values:
Ok sector erase successfully done.
ErrorInvalidParameter If one of following conditions are met:
automatic algorithm of flash memory execution abnormally
Definition at line 329 of file dualflash.c.
References DFlash_CheckToggle(), DFLASH_CHK_TOGG_ABNORMAL, DFlash_ReadResetCmd(), Flash_Read, and Flash_Write.