PDL for FM Family: Common Functions
Common Functions
Functions
void pdl_memclr (uint8_t *pu8Address, uint32_t u32Count)
Memory clear function for PDL_ZERO_STRUCT()
void PDL_WAIT_LOOP_HOOK (void)
Hook function, which is called in polling loops.
Function Documentation
void pdl_memclr (uint8_t * pu8Address, uint32_t u32Count)
Memory clear function for PDL_ZERO_STRUCT()
Definition at line 90 of file pdl.c.
void PDL_WAIT_LOOP_HOOK (void)
Hook function, which is called in polling loops.
This hook is part of wait loops.
Definition at line 102 of file pdl.c.
Referenced by HsSpi_DirectModeTransferHalfDuplexList(), HsSpi_ModuleDisable(), HsSpi_ModuleEnable(), and HsSpi_MultiModeTransfer().