PDL for FM Family: I2C Slave (I2CS))
I2C Slave (I2CS))
Data Structures
struct stc_i2cs_irq_en
I2CS interrupt enable structure.
struct stc_i2cs_irq_cb
I2CS interrupt callback function.
struct stc_i2cs_config
I2CS configuration structure.
struct stc_i2cs_intern_data
I2CS module internal data, storing internal information for each enabled I2CS instance.
struct stc_i2cs_instance_data
I2CS instance data type.
Defines
#define stc_i2csn_t FM_I2CS_TypeDef
#define I2CS0 (*((volatile stc_i2csn_t *) FM_I2CS0_BASE))
#define I2CS_INSTANCE_COUNT (uint8_t)(PDL_PERIPHERAL_ENABLE_I2CS0 == PDL_ON)
#define I2CS0_DATA_REG_ADDR (uint32_t)(&FM_I2CS0->TDR)
#define I2CS_IRQ_COND_RESTART_DETECTION 0u
#define I2CS_IRQ_COND_STOP_DETECTION 1u
Typedefs
typedef enum en_i2cs_ack en_i2cs_ack_t
I2CS ACK types.
typedef enum en_i2cs_irq_sel en_i2cs_irq_sel_t
I2CS interrupt selection.
typedef struct stc_i2cs_irq_en stc_i2cs_irq_en_t
I2CS interrupt enable structure.
typedef struct stc_i2cs_irq_cb stc_i2cs_irq_cb_t
I2CS interrupt callback function.
typedef enum en_i2cs_status en_i2cs_status_t
I2CS status types.
typedef enum en_i2cs_data_dir en_i2cs_data_dir_t
I2CS data direction.
typedef struct stc_i2cs_config stc_i2cs_config_t
I2CS configuration structure.
typedef enum en_i2cs_instance_index en_i2cs_instance_index_t
Enumeration to define an index for each enabled I2CS instance.
typedef struct stc_i2cs_intern_data stc_i2cs_intern_data_t
I2CS module internal data, storing internal information for each enabled I2CS instance.
typedef struct
stc_i2cs_instance_data stc_i2cs_instance_data_t
I2CS instance data type.
Enumerations
enum en_i2cs_ack { I2csAck = 0u, I2csNAck = 1u }
I2CS ACK types.
enum en_i2cs_irq_sel { I2csTxIrq = 0u, I2csRxIrq = 1u, I2csCondIrq = 2u, I2csStatusIrq = 3u }
I2CS interrupt selection.
enum en_i2cs_status {
I2csStatus = 0u, I2csRxFull = 1u, I2csTxEmpty = 2u, I2csFirstByteDetect = 3u,
I2csReservedByteDetect = 4u, I2csActive = 5u, I2csRestartDetect = 6u, I2csStopDetect = 7u,
I2csBusBusy = 8u
}
I2CS status types.
enum en_i2cs_data_dir { I2csDataRx = 0u, I2csDataTx = 1u }
I2CS data direction.
enum en_i2cs_instance_index { I2csInstanceIndexI2cs0, I2csInstanceIndexMax, I2csInstanceIndexUnknown = 0xFFu }
Enumeration to define an index for each enabled I2CS instance.
Functions
void I2csIrqHandlerTx (volatile FM_I2CS_TypeDef *pstcI2cs, stc_i2cs_intern_data_t *pstcInternData)
I2CS transfer interrupt service routine.
void I2csIrqHandlerRx (volatile FM_I2CS_TypeDef *pstcI2cs, stc_i2cs_intern_data_t *pstcInternData)
I2CS receive interrupt service routine.
void I2csIrqHandlerStatus (volatile FM_I2CS_TypeDef *pstcI2cs, stc_i2cs_intern_data_t *pstcInternData)
I2CS status interrupt service routine.
en_result_t I2cs_EnableIrq (volatile FM_I2CS_TypeDef *pstcI2cs, en_i2cs_irq_sel_t enIrqSel)
Enable I2CS interrupts.
en_result_t I2cs_DisableIrq (volatile FM_I2CS_TypeDef *pstcI2cs, en_i2cs_irq_sel_t enIrqSel)
Disable I2CS interrupts.
en_result_t I2cs_Init (volatile FM_I2CS_TypeDef *pstcI2cs, stc_i2cs_config_t *pstcConfig)
Initialization of I2CS module.
en_result_t I2cs_DeInit (volatile FM_I2CS_TypeDef *pstcI2cs, boolean_t bTouchNvic)
Deinitialisation of I2C Slave.
en_result_t I2cs_SendData (volatile FM_I2CS_TypeDef *pstcI2cs, uint8_t u8Data)
Write I2CS data buffer.
uint8_t I2cs_ReceiveData (volatile FM_I2CS_TypeDef *pstcI2cs)
Read I2CS data buffer.
en_result_t I2cs_ConfigAck (volatile FM_I2CS_TypeDef *pstcI2cs, en_i2cs_ack_t enAck)
Configure ACK signal sent to master.
en_i2cs_ack_t I2cs_GetAck (volatile FM_I2CS_TypeDef *pstcI2cs)
Get the ACK signal from slave.
boolean_t I2cs_GetStatus (volatile FM_I2CS_TypeDef *pstcI2cs, en_i2cs_status_t enStatus)
Get status of I2CS according to status type.
en_result_t I2cs_ClrStatus (volatile FM_I2CS_TypeDef *pstcI2cs, en_i2cs_status_t enStatus)
Clear status of I2CS according to status type.
en_i2cs_data_dir_t I2cs_GetDataDir (volatile FM_I2CS_TypeDef *pstcI2cs)
Get direction of I2CS data in slave mode.
Variables
stc_i2cs_instance_data_t m_astcI2csInstanceDataLut [(uint8_t)(PDL_PERIPHERAL_ENABLE_I2CS0==PDL_ON)]
Look-up table for all enabled I2CS instances and their internal data.
Detailed Description
Provided functions of I2CS module:
I2cs_Init()
I2cs_Init()
I2cs_EnableIrq()
I2cs_DisableIrq()
I2cs_SendData()
I2cs_ReceiveData()
I2cs_ConfigAck()
I2cs_GetAck()
I2cs_GetStatus()
I2cs_ClrStatus()
I2cs_GetDataDir()
I2cs_Init() is used to initialize an I2CS instance with parameter pstcConfig of type stc_i2cs_config_t.
I2cs_DeInit() is used to reset all I2CS related register. So this function is used after initialization by I2cs_Init().
I2cs_EnableIrq() enables I2C interrupt sources selected by enumeration type en_i2cs_irq_sel_t and I2cs_DisableIrq() disables the I2C interrupt sources selected by enumeration type en_i2cs_irq_sel_t.
I2cs_SendData() writes a byte data into I2CS transfer buffer and I2cs_ReceiveData() reads a byte data from I2CS receive buffer.
I2cs_ConfigAck() configures ACK signal when receive a data. I2cs_GetAck() gets the ACK signal status after receiving a ACK.
I2cs_GetStatus() gets the status selected by I2cs_GetStatus::enStatus and I2cs_ClrStatus() clears the I2C status selected, some status can only be cleared by hardware automatically.
I2cs_GetDataDir() gets the data direction of I2CS in the slave mode.
Define Documentation
#define I2CS0 (*((volatile stc_i2csn_t *) FM_I2CS0_BASE))
Definition at line 117 of file i2cs.h.
Referenced by I2csDeInitNvic(), and I2csInitNvic().
#define I2CS0_DATA_REG_ADDR (uint32_t)(&FM_I2CS0->TDR)
Definition at line 122 of file i2cs.h.
#define I2CS_INSTANCE_COUNT (uint8_t)(PDL_PERIPHERAL_ENABLE_I2CS0 == PDL_ON)
Definition at line 119 of file i2cs.h.
#define I2CS_IRQ_COND_RESTART_DETECTION 0u
Definition at line 128 of file i2cs.h.
Referenced by I2csIrqHandlerStatus().
#define I2CS_IRQ_COND_STOP_DETECTION 1u
Definition at line 129 of file i2cs.h.
Referenced by I2csIrqHandlerStatus().
#define stc_i2csn_t FM_I2CS_TypeDef
Definition at line 115 of file i2cs.h.
Referenced by I2csDeInitNvic(), and I2csInitNvic().
Typedef Documentation
typedef enum en_i2cs_ack en_i2cs_ack_t
I2CS ACK types.
typedef enum en_i2cs_data_dir en_i2cs_data_dir_t
I2CS data direction.
typedef enum en_i2cs_instance_index en_i2cs_instance_index_t
Enumeration to define an index for each enabled I2CS instance.
typedef enum en_i2cs_irq_sel en_i2cs_irq_sel_t
I2CS interrupt selection.
typedef enum en_i2cs_status en_i2cs_status_t
I2CS status types.
typedef struct stc_i2cs_config stc_i2cs_config_t
I2CS configuration structure.
typedef struct stc_i2cs_instance_data stc_i2cs_instance_data_t
I2CS instance data type.
typedef struct stc_i2cs_intern_data stc_i2cs_intern_data_t
I2CS module internal data, storing internal information for each enabled I2CS instance.
typedef struct stc_i2cs_irq_cb stc_i2cs_irq_cb_t
I2CS interrupt callback function.
typedef struct stc_i2cs_irq_en stc_i2cs_irq_en_t
I2CS interrupt enable structure.
Enumeration Type Documentation
enum en_i2cs_ack
I2CS ACK types.
Enumerator:
I2csAck
I2CS normal ACK.
I2csNAck
I2CS NACK.
Definition at line 135 of file i2cs.h.
enum en_i2cs_data_dir
I2CS data direction.
Enumerator:
I2csDataRx
Data from master to slave.
I2csDataTx
Data from slave to master.
Definition at line 202 of file i2cs.h.
enum en_i2cs_instance_index
Enumeration to define an index for each enabled I2CS instance.
Enumerator:
I2csInstanceIndexI2cs0
I2csInstanceIndexMax
I2csInstanceIndexUnknown
Definition at line 234 of file i2cs.h.
enum en_i2cs_irq_sel
I2CS interrupt selection.
Enumerator:
I2csTxIrq
I2CS TX interrupt.
I2csRxIrq
I2CS RX interrupt.
I2csCondIrq
I2CS condition detection interrupt.
I2csStatusIrq
I2CS status interrupt.
Definition at line 146 of file i2cs.h.
enum en_i2cs_status
I2CS status types.
Enumerator:
I2csStatus
I2CS status interrupt request flag.
I2csRxFull
I2CS RX buffer full interrupt request flag.
I2csTxEmpty
I2CS TX buffer empty interrupt request flag.
I2csFirstByteDetect
I2CS First byte detection.
I2csReservedByteDetect
I2CS reserved byte detection.
I2csActive
I2CS active.
I2csRestartDetect
I2CS re-start condition detection.
I2csStopDetect
I2CS stop condition detection.
I2csBusBusy
I2CS Bus busy status.
Definition at line 185 of file i2cs.h.
Function Documentation
en_result_t I2cs_ClrStatus (volatile FM_I2CS_TypeDef * pstcI2cs, en_i2cs_status_t enStatus)
Clear status of I2CS according to status type.
Parameters:
[in] pstcI2cs Pointer to I2CS instance
[in] enStatus I2CS status type
I2csStatus I2CS status interrupt request flag
I2csRxFull I2CS RX buffer full interrupt request flag
I2csTxEmpty I2CS TX buffer empty interrupt request flag
I2csFirstByteDetect I2CS First byte detection
I2csReservedByteDetect I2CS reserved byte detection
I2csActive I2CS active status
I2csRestartDetect I2CS re-start condition detection
I2cStopDetect I2CS stop condition detection
I2csBusBusy I2CS bus busy status
Return values:
Ok Status has been cleared normally
ErrorInvalidParameter If one of following conditions are met:
pstcI2cs == NULL
Note:
The following status can only be cleared by hardware behavior:
I2cRxFull
I2cTxEmpty
I2cFirstByteDetect
I2cReservedByteDetect
I2csRestartDetect
I2csStopDetect
I2cBusBusy
Definition at line 729 of file i2cs.c.
References I2csActive, I2csBusBusy, I2csFirstByteDetect, I2csReservedByteDetect, I2csRestartDetect, I2csRxFull, I2csStatus, I2csStopDetect, and I2csTxEmpty.
en_result_t I2cs_ConfigAck (volatile FM_I2CS_TypeDef * pstcI2cs, en_i2cs_ack_t enAck)
Configure ACK signal sent to master.
Parameters:
[in] pstcI2cs Pointer to I2C instance
[in] enAck ACK to be sent
I2cAck ACK will be sent as response signal
I2cNAck NACK will be sent as response signal
Return values:
Ok ACK signal has been successfully configured
ErrorInvalidParameter If one of following conditions are met:
pstcI2cs == NULL
This function is only meaningful when I2C is in slave mode
Definition at line 585 of file i2cs.c.
References I2csAck.
en_result_t I2cs_DeInit (volatile FM_I2CS_TypeDef * pstcI2cs, boolean_t bTouchNvic)
Deinitialisation of I2C Slave.
All used I2CS register are reset to their default values.
Parameters:
[in] pstcI2cs Pointer to I2CS instance register area
[in] bTouchNvic Touch NVIC or not
Return values:
Ok Process successfully done.
ErrorInvalidParameter If one of following conditions are met:
pstcI2cs == NULL
Definition at line 497 of file i2cs.c.
References I2csDeInitNvic(), and I2csGetInternDataPtr().
en_result_t I2cs_DisableIrq (volatile FM_I2CS_TypeDef * pstcI2cs, en_i2cs_irq_sel_t enIrqSel)
Disable I2CS interrupts.
Parameters:
[in] pstcI2cs Pointer to I2C instance
[in] enIrqSel enumeration of I2C interrupt selection
I2cTxIrq TX interrupt of I2CS
I2cRxIrq RX interrupt of I2CS
I2cStatusIrq status interrupt of I2C
I2cCondIrq condition interrupt of I2C
Return values:
Ok Interrupts has been disabled
ErrorInvalidParameter If one of following conditions are met:
pstcI2cs == NULL
Other invalid configuration
Definition at line 327 of file i2cs.c.
References I2csCondIrq, I2csRxIrq, I2csStatusIrq, and I2csTxIrq.
en_result_t I2cs_EnableIrq (volatile FM_I2CS_TypeDef * pstcI2cs, en_i2cs_irq_sel_t enIrqSel)
Enable I2CS interrupts.
Parameters:
[in] pstcI2cs Pointer to I2CS instance
[in] enIrqSel enumeration of I2CS interrupt selection
I2cTxIrq TX interrupt of I2CS
I2cRxIrq RX interrupt of I2CS
I2cStatusIrq status interrupt of I2C
I2cCondIrq condition interrupt of I2C
Return values:
Ok Interrupts has been enabled
ErrorInvalidParameter If one of following conditions are met:
pstcI2cs == NULL
Other invalid configuration
Definition at line 281 of file i2cs.c.
References I2csCondIrq, I2csRxIrq, I2csStatusIrq, and I2csTxIrq.
en_i2cs_ack_t I2cs_GetAck (volatile FM_I2CS_TypeDef * pstcI2cs)
Get the ACK signal from slave.
Parameters:
[in] pstcI2cs Pointer to I2C instance
Return values:
I2cAck Receive the ACK from I2C Slave
I2cNAck Receive the NACK from I2C Slave
This function applies in the I2C master mode.
Definition at line 610 of file i2cs.c.
References I2csAck, and I2csNAck.
en_i2cs_data_dir_t I2cs_GetDataDir (volatile FM_I2CS_TypeDef * pstcI2cs)
Get direction of I2CS data in slave mode.
Parameters:
[in] pstcI2cs Pointer to I2CS instance
Return values:
i2c_master_tx_slave_rx Master will send data to slave
i2c_slave_tx_master_rx Master will receive data from slave
This function can be called after receiving the device address from master in the slave mode.
Definition at line 779 of file i2cs.c.
References I2csDataRx, and I2csDataTx.
boolean_t I2cs_GetStatus (volatile FM_I2CS_TypeDef * pstcI2cs, en_i2cs_status_t enStatus)
Get status of I2CS according to status type.
Parameters:
[in] pstcI2cs Pointer to I2CS instance
[in] enStatus I2C status type
I2csStatus I2CS status interrupt request flag
I2csRxFull I2CS RX buffer full interrupt request flag
I2csTxEmpty I2CS TX buffer empty interrupt request flag
I2csFirstByteDetect I2CS First byte detection
I2csReservedByteDetect I2CS reserved byte detection
I2csActive I2CS active status
I2csRestartDetect I2CS re-start condition detection
I2cStopDetect I2CS stop condition detection
I2csBusBusy I2CS bus busy status
Return values:
FALSE If one of following conditions are met:
I2CS status interrupt request flag is clear [enStatus = I2csStatus]
I2CS receive buffer is not full [enStatus = I2cRxFull]
I2CS tranfer buffer is not empty [enStatus = I2cTxEmpty]
I2CS first byte is not detected [enStatus = I2cFirstByteDetect]
I2CS reserved address is not detected [enStatus = I2cReservedByteDetect]
I2CS not active [enStatus = I2csActive]
I2CS restart is not detected [enStatus = I2csRestart]
I2CS stop is not detected [enStatus = I2cStopDetect]
I2CS bus is idle [enStatus = I2cBusStatus]
TRUE If one of following conditions are met:
I2CS status interrupt request flag is set [enStatus = I2csStatus]
I2CS receive buffer is full [enStatus = I2cRxFull]
I2CS tranfer buffer is empty [enStatus = I2cTxEmpty]
I2CS first byte is detected [enStatus = I2cFirstByteDetect]
I2CS reserved address is detected [enStatus = I2cReservedByteDetect]
I2CS is active [enStatus = I2csActive]
I2CS restart is detected [enStatus = I2csRestart]
I2CS stop is detected [enStatus = I2cStopDetect]
I2CS bus is busy [enStatus = I2cBusStatus]
Definition at line 658 of file i2cs.c.
References I2csActive, I2csBusBusy, I2csFirstByteDetect, I2csReservedByteDetect, I2csRestartDetect, I2csRxFull, I2csStatus, I2csStopDetect, and I2csTxEmpty.
en_result_t I2cs_Init (volatile FM_I2CS_TypeDef * pstcI2cs, stc_i2cs_config_t * pstcConfig)
Initialization of I2CS module.
Set registers to active I2C Slave.
Parameters:
[in] pstcI2cs Pointer to I2CS instance register area
[in] pstcConfig I2CS configuration
Return values:
Ok Process successfully done.
ErrorInvalidParameter If one of following conditions are met:
pstcI2cs == NULL
pstcConfig == NULL
pstcMfsInternData == NULL (invalid or disabled MFS unit (PDL_PERIPHERAL_ENABLE_I2CS0))
Definition at line 375 of file i2cs.c.
References stc_i2cs_irq_en::bCondIrq, stc_i2cs_config::bEnableNoiseFilter, stc_i2cs_config::bEnableReservedAddr, stc_i2cs_config::bEnableSlaveAddr, stc_i2cs_irq_en::bRxIrq, stc_i2cs_irq_en::bStatusIrq, stc_i2cs_config::bTouchNvic, stc_i2cs_irq_en::bTxIrq, stc_i2cs_config::bWaitSelection, I2csGetInternDataPtr(), I2csInitNvic(), stc_i2cs_irq_cb::pfnCondIrqCb, stc_i2cs_intern_data::pfnCondIrqCb, stc_i2cs_irq_cb::pfnRxIrqCb, stc_i2cs_intern_data::pfnRxIrqCb, stc_i2cs_irq_cb::pfnStatusIrqCb, stc_i2cs_intern_data::pfnStatusIrqCb, stc_i2cs_irq_cb::pfnTxIrqCb, stc_i2cs_intern_data::pfnTxIrqCb, stc_i2cs_config::pstcIrqCb, stc_i2cs_config::pstcIrqEn, stc_i2cs_config::u8SetupTime, stc_i2cs_config::u8SlaveAddr, and stc_i2cs_config::u8SlaveMaskAddr.
uint8_t I2cs_ReceiveData (volatile FM_I2CS_TypeDef * pstcI2cs)
Read I2CS data buffer.
Parameters:
[in] pstcI2cs Pointer to I2CS instance
Return values:
Receive data
Definition at line 564 of file i2cs.c.
en_result_t I2cs_SendData (volatile FM_I2CS_TypeDef * pstcI2cs, uint8_t u8Data)
Write I2CS data buffer.
Parameters:
[in] pstcI2cs Pointer to I2CS instance
[in] u8Data Data to be sent
Return values:
Ok Data has been successfully sent
ErrorInvalidParameter If one of following conditions are met:
pstcI2cs == NULL
Definition at line 543 of file i2cs.c.
void I2csIrqHandlerRx (volatile FM_I2CS_TypeDef * pstcI2cs, stc_i2cs_intern_data_t * pstcInternData)
I2CS receive interrupt service routine.
Parameters:
pstcI2cs Pointer to I2CS instance
pstcInternData Pointer to I2CS internal data structure
This function is called on I2CS Receive IRQ.
Definition at line 182 of file i2cs.c.
References stc_i2cs_intern_data::pfnRxIrqCb.
void I2csIrqHandlerStatus (volatile FM_I2CS_TypeDef * pstcI2cs, stc_i2cs_intern_data_t * pstcInternData)
I2CS status interrupt service routine.
Parameters:
pstcI2cs Pointer to I2CS instance
pstcInternData Pointer to I2CS internal data structure
This function is called on I2CS status IRQ.
Definition at line 227 of file i2cs.c.
References I2CS_IRQ_COND_RESTART_DETECTION, I2CS_IRQ_COND_STOP_DETECTION, stc_i2cs_intern_data::pfnCondIrqCb, and stc_i2cs_intern_data::pfnStatusIrqCb.
void I2csIrqHandlerTx (volatile FM_I2CS_TypeDef * pstcI2cs, stc_i2cs_intern_data_t * pstcInternData)
I2CS transfer interrupt service routine.
Parameters:
pstcI2cs Pointer to I2CS instance
pstcInternData Pointer to I2CS internal data structure
This function is called on I2CS transfer IRQ.
Definition at line 204 of file i2cs.c.
References stc_i2cs_intern_data::pfnTxIrqCb.
Variable Documentation
stc_i2cs_instance_data_t m_astcI2csInstanceDataLut[(uint8_t)(PDL_PERIPHERAL_ENABLE_I2CS0==PDL_ON)]
Look-up table for all enabled I2CS instances and their internal data.
Definition at line 75 of file i2cs.c.