PDL for FM Family: SD Card Interface (SDIF)
SD Card Interface (SDIF)
Data Structures
struct stc_sdif_err_irq
SDIF error status types.
struct stc_sdif_err_irq_cb
SDIF error status callback functions.
struct stc_sdif_normal_irq
SDIF normal status types.
struct stc_sdif_normal_irq_cb
SDIF error status callback functions.
struct stc_sdif_auto_cmd_err
SDIF Auto Command error status.
struct stc_sdif_config
SDIF configuration.
struct stc_sdif_cmd_config
SDIF command configuration.
struct stc_sdif_data_config
SDIF data transfer configuration.
struct stc_sdif_intern_data
struct stc_sdif_instance_data
SDIF instance data type.
Defines
#define stc_sdifn_t FM_SDIF_TypeDef
#define SDIF0 (*((volatile stc_sdifn_t *) FM_SDIF_BASE))
#define SDIF_INSTANCE_COUNT (uint8_t)(PDL_PERIPHERAL_ENABLE_SD0 == PDL_ON)
Typedefs
typedef enum en_sdif_cmd_type en_sdif_cmd_type_t
SD command types.
typedef enum en_sdif_response_type en_sdif_response_type_t
SDIF response types.
typedef enum en_sd_data_timeout en_sdif_data_timeout_t
SD data timeout time.
typedef enum en_sdif_auto_cmd en_sdif_auto_cmd_t
SDIF auto command enable selection.
typedef struct stc_sdif_err_irq stc_sdif_err_irq_status_t
SDIF error status types.
typedef struct stc_sdif_err_irq stc_sdif_err_irq_en_t
typedef enum en_sdif_err_irq_sel en_sdif_err_irq_sel_t
SDIF error interrupt types.
typedef struct stc_sdif_err_irq_cb stc_sdif_err_irq_cb_t
SDIF error status callback functions.
typedef struct stc_sdif_normal_irq stc_sdif_normal_irq_status_t
SDIF normal status types.
typedef struct stc_sdif_normal_irq stc_sdif_normal_irq_en_t
typedef enum en_sdif_normal_irq_sel en_sdif_normal_irq_sel_t
SDIF normal interrupt types.
typedef struct
stc_sdif_normal_irq_cb stc_sdif_normal_irq_cb_t
SDIF error status callback functions.
typedef struct
stc_sdif_auto_cmd_err stc_sdif_auto_cmd_err_t
SDIF Auto Command error status.
typedef struct stc_sdif_config stc_sdif_config_t
SDIF configuration.
typedef struct stc_sdif_cmd_config stc_sdif_cmd_config_t
SDIF command configuration.
typedef struct stc_sdif_data_config stc_sdif_data_config_t
SDIF data transfer configuration.
typedef enum en_sdif_voltage_sel en_sdif_voltage_sel_t
SDIF voltage selection.
typedef enum en_sdif_reset en_sdif_reset_t
SDIF software reset types.
typedef enum en_sdif_instance_index en_sdif_instance_index_t
Enumeration to define an index for each enabled SDIF instance.
typedef struct stc_sdif_intern_data stc_sdif_intern_data_t
typedef struct
stc_sdif_instance_data stc_sdif_instance_data_t
SDIF instance data type.
Enumerations
enum en_sdif_cmd_type { SdifCmdAbort = 0u, SdifCmdResume = 1u, SdifCmdSuspend = 2u, SdifCmdNormal = 3u }
SD command types.
enum en_sdif_response_type { SdifResponseNone = 0u, SdifResponse136Bit = 1u, SdifResponse48Bit = 2u, SdifResponse48BitCheckBusy = 3u }
SDIF response types.
enum en_sd_data_timeout {
SdifTimeout_BaseClk_2_13 = 0u, SdifTimeout_BaseClk_2_14 = 1u, SdifTimeout_BaseClk_2_15 = 2u, SdifTimeout_BaseClk_2_16 = 3u,
SdifTimeout_BaseClk_2_17 = 4u, SdifTimeout_BaseClk_2_18 = 5u, SdifTimeout_BaseClk_2_19 = 6u, SdifTimeout_BaseClk_2_20 = 7u,
SdifTimeout_BaseClk_2_21 = 8u, SdifTimeout_BaseClk_2_22 = 9u, SdifTimeout_BaseClk_2_23 = 10u, SdifTimeout_BaseClk_2_24 = 11u,
SdifTimeout_BaseClk_2_25 = 12u, SdifTimeout_BaseClk_2_26 = 13u, SdifTimeout_BaseClk_2_27 = 14u
}
SD data timeout time.
enum en_sdif_auto_cmd { SdifAutoCmdDisable = 0u, SdifAutoCmd12Enable = 1u, SdifAutoCmd23Enable = 2u }
SDIF auto command enable selection.
enum en_sdif_err_irq_sel {
SdifCmdTimeoutErrIrq = 0u, SdifCmdCrcErrIrq = 1u, SdifCmdEndBitErrIrq = 2u, SdifCmdIndexErrIrq = 3u,
SdifDataTimeoutErrIrq = 4u, SdifDataCrcErrIrq = 5u, SdifDataEndBitErrIrq = 6u, SdifCurrentLimitErrIrq = 7u,
SdifAutoCmdErrIrq = 8u, SdifAdmaErrIrq = 9u, SdifTuningErrIrq = 10u
}
SDIF error interrupt types.
enum en_sdif_normal_irq_sel {
SdifCommandCompleteIrq = 0u, SdifTransferCompleteIrq = 1u, SdifBlockGapEventIrq = 2u, SdifDmaIrq = 3u,
SdifBufferWriteReadyIrq = 4u, SdifBufferReadReadyIrq = 5u, SdifCardInsertionIrq = 6u, SdifCardRemovalIrq = 7u,
SdifCardIrq = 8u
}
SDIF normal interrupt types.
enum en_sdif_voltage_sel { SdifVoltage18v = 0u, SdifVoltage30v = 1u, SdifVoltage33v = 2u }
SDIF voltage selection.
enum en_sdif_reset { SdifResetDataLine = 0u, SdifResetCmdLine = 1u, SdifResetAll = 2u }
SDIF software reset types.
enum en_sdif_instance_index { SdifInstanceIndexSdif0, SdifInstanceIndexMax }
Enumeration to define an index for each enabled SDIF instance.
Functions
static void SdifInitNvic (volatile FM_SDIF_TypeDef *pstcSdif)
Set NVIC Interrupt depending on SDIF instance.
static void SdifDeInitNvic (volatile FM_SDIF_TypeDef *pstcSdif)
Clear NVIC Interrupt depending on SDIF instance.
static stc_sdif_intern_data_t * SdifGetInternDataPtr (volatile FM_SDIF_TypeDef *pstcSdif)
Return the internal data for a certain SDIF instance.
void SdifIrqHandler (volatile FM_SDIF_TypeDef *pstcSdif, stc_sdif_intern_data_t *pstcSdifInternData)
SDIF instance interrupt service routine.
en_result_t Sdif_Init (volatile FM_SDIF_TypeDef *pstcSdif, stc_sdif_config_t *pstcConfig)
Initialize SD interface.
en_result_t Sdif_DeInit (volatile FM_SDIF_TypeDef *pstcSdif, boolean_t bTouchIrq, boolean_t bTouchIrqCb, boolean_t bTouchNvic)
De-Initialize SD interface.
en_result_t Sdif_EnableNormalIrq (volatile FM_SDIF_TypeDef *pstcSdif, en_sdif_normal_irq_sel_t enNormalIrqSel)
Enable SDIF normal interrupt.
en_result_t Sdif_DisableNormalIrq (volatile FM_SDIF_TypeDef *pstcSdif, en_sdif_normal_irq_sel_t enNormalIrqSel)
Disable SDIF normal interrupt.
en_result_t Sdif_EnableErrIrq (volatile FM_SDIF_TypeDef *pstcSdif, en_sdif_err_irq_sel_t enErrIrqSel)
Enable SDIF error interrupt.
en_result_t Sdif_DisableErrIrq (volatile FM_SDIF_TypeDef *pstcSdif, en_sdif_err_irq_sel_t enErrIrqSel)
Disable SDIF error interrupt.
en_result_t Sdif_GetErrStatus (volatile FM_SDIF_TypeDef *pstcSdif, stc_sdif_err_irq_status_t *pstcStatus)
Get error status of SDIF.
en_result_t Sdif_ClrErrStatus (volatile FM_SDIF_TypeDef *pstcSdif, stc_sdif_err_irq_status_t *pstcStatus)
Clear error status of SDIF.
en_result_t Sdif_GetNormalStatus (volatile FM_SDIF_TypeDef *pstcSdif, stc_sdif_normal_irq_status_t *pstcStatus)
Get normal status of SDIF.
en_result_t Sdif_ClrNormalStatus (volatile FM_SDIF_TypeDef *pstcSdif, stc_sdif_normal_irq_status_t *pstcStatus)
Clear normal status of SDIF.
en_result_t Sdif_GetAutoCommandErrStatus (volatile FM_SDIF_TypeDef *pstcSdif, stc_sdif_auto_cmd_err_t *pstcStatus)
Get error status of SDIF auto command.
en_result_t Sdif_EnableInternalClock (volatile FM_SDIF_TypeDef *pstcSdif)
Enable internal clock of SDIF.
en_result_t Sdif_DisableInternalClock (volatile FM_SDIF_TypeDef *pstcSdif)
Disable internal clock of SDIF.
en_result_t Sdif_EnableSdclk (volatile FM_SDIF_TypeDef *pstcSdif)
Enable SDCLK output.
en_result_t Sdif_DisableSdclk (volatile FM_SDIF_TypeDef *pstcSdif)
Disable SDCLK output.
en_result_t Sdif_SetClkDiv (volatile FM_SDIF_TypeDef *pstcSdif, uint16_t u16Div)
Set the clock division of SD clock.
en_result_t Sdif_SetBusWidth (volatile FM_SDIF_TypeDef *pstcSdif, boolean_t bEnable4BitMode)
Set the bus width of SD Bus.
en_result_t Sdif_SetBusSpeedMode (volatile FM_SDIF_TypeDef *pstcSdif, boolean_t bEnableHighSpeedMode)
Set the bus speed mode of SD Bus.
en_result_t Sdif_SelBusVoltage (volatile FM_SDIF_TypeDef *pstcSdif, en_sdif_voltage_sel_t enVoltage)
Select bus voltage of SD bus.
en_result_t Sdif_BusPowerOn (volatile FM_SDIF_TypeDef *pstcSdif)
Power on SD bus power.
en_result_t Sdif_BusPowerOff (volatile FM_SDIF_TypeDef *pstcSdif)
Power off SD bus power.
en_result_t Sdif_SendCommand (volatile FM_SDIF_TypeDef *pstcSdif, stc_sdif_cmd_config_t *pstcConfig)
Send SD command.
en_result_t Sdif_GetResponse (volatile FM_SDIF_TypeDef *pstcSdif, uint16_t *pu16ResponseData, uint8_t u8ResponseRegCount)
Get SD response.
en_result_t Sdif_InitDataTransfer (volatile FM_SDIF_TypeDef *pstcSdif, stc_sdif_data_config_t *pstcDataConfig)
Initialize data transfer.
uint32_t Sdif_ReadData (volatile FM_SDIF_TypeDef *pstcSdif)
Read data from SD data buffer port.
en_result_t Sdif_WriteData (volatile FM_SDIF_TypeDef *pstcSdif, uint32_t u32Data)
Write data to SD data buffer port.
en_result_t Sdif_StopAtBlockGap (volatile FM_SDIF_TypeDef *pstcSdif)
Stop data transfer during block gap.
en_result_t Sdif_RestartTransfer (volatile FM_SDIF_TypeDef *pstcSdif)
Restart data transfer.
boolean_t Sdif_PollCardInsert (volatile FM_SDIF_TypeDef *pstcSdif)
Poll card insertion status.
en_result_t Sdif_SoftwareReset (volatile FM_SDIF_TypeDef *pstcSdif, en_sdif_reset_t enReset)
Issue software reset to SD card.
boolean_t Sdif_CheckCommandInhit (volatile FM_SDIF_TypeDef *pstcSdif)
Check the status of CMD line.
boolean_t Sdif_CheckCommandWithDataInhit (volatile FM_SDIF_TypeDef *pstcSdif)
Check the status of DAT line.
en_result_t Sdif_SetWakeupFactor (volatile FM_SDIF_TypeDef *pstcSdif, boolean_t bCardRemovalWakeup, boolean_t bCardInsertWakeup, boolean_t bCardIrqWakeup)
Set the wakeup factor.
en_result_t Sdif_DisableNomralIrq (volatile FM_SDIF_TypeDef *pstcSdif, en_sdif_normal_irq_sel_t enIrqSel)
Variables
stc_sdif_instance_data_t m_astcSdifInstanceDataLut [(uint8_t)(PDL_PERIPHERAL_ENABLE_SD0==PDL_ON)]
Look-up table for all enabled ADC instances and their internal data.
stc_sdif_instance_data_t m_astcSdifInstanceDataLut [(uint8_t)(PDL_PERIPHERAL_ENABLE_SD0==PDL_ON)]
Look-up table for all enabled SD instances and their internal data.
Detailed Description
Provided functions of SDIF module:
Sdif_Init()
Sdif_DeInit()
Sdif_EnableInternalClock()
Sdif_DisableInternalClock()
Sdif_EnableSdclk()
Sdif_DisableSdclk()
Sdif_SetClkDiv()
Sdif_SetBusWidth()
Sdif_SetBusSpeedMode()
Sdif_SelBusVoltage()
Sdif_BusPowerOn()
Sdif_BusPowerOff()
Sdif_SendCommand()
Sdif_GetResponse()
Sdif_InitDataTransfer()
Sdif_ReadData()
Sdif_WriteData()
Sdif_StopAtBlockGap()
Sdif_RestartTransfer()
Sdif_GetErrStatus()
Sdif_ClrErrStatus()
Sdif_GetNormalStatus()
Sdif_ClrNormalStatus()
Sdif_GetAutoCommandErrStatus()
Sdif_CheckCommandInhit()
Sdif_CheckCommandWithDataInhit()
Sdif_PollCardInsert()
Sdif_SoftwareReset()
Sdif_Init() initializes a SD host interface instance. Sdif_DeInit() de-initializes a SD host interface instance.
Sdif_EnableInternalClock() Enables SD host internal clock, which makes SD host start work. Sdif_DisableInternalClock() disables SD host internal clock, which makes SD host stops work.
Sdif_EnableSdclk() enables SDCLK output and Sdif_DisableSdclk() disables SDCLK output.
The SD clock is first intialized in Sdif_Init() and can be changed by Sdif_SetClkDiv()
The bit width is first initialized in Sdif_Init() and can be changed by Sdif_SetBusWidth()
The bus speed mode is first initialized in Sdif_Init() and can be changed by Sdif_SetBusSpeedMode()
Sdif_SelBusVoltage() selects SD bus voltage, before Sdif_BusPowerOff() should be called to power off SD bus.
Sdif_BusPowerOn() power on SD bus and Sdif_BusPowerOff() power off SD bus.
Sdif_SendCommand() send the SD command specified by the structure type stc_sdif_cmd_config_t.
Sdif_GetResponse() gets the response data, the count of which is specified by the parameter Sdif_GetResponse::u8ResponseRegCount
Sdif_InitDataTransfer() initializes data transfer, this function must be called before data transfer.
Sdif_ReadData() reads the 32-bit data from data buffer port and Sdif_WriteData() writes 32-bit data to data buffer port.
Sdif_StopAtBlockGap() stops transfer during block gap in multi-block transfer() and Sdif_RestartTransfer() restarts data transfer
Sdif_GetErrStatus() gets the error interrupt status and Sdif_ClrErrStatus() clears error interrupt status.
Sdif_GetNormalStatus() gets the error interrupt status and Sdif_ClrNormalStatus() clears error interrupt status.
Sdif_GetAutoCommandErrStatus() gets the error status of Auto Command.
Sdif_CheckCommandInhit() check whether command without data can be sent. Sdif_CheckCommandWithDataInhit() check whether command with data can be sent.
Sdif_PollCardInsert() polls the card insertion status.
Sdif_SoftwareReset() issues software reset to SD card.
Define Documentation
#define SDIF0 (*((volatile stc_sdifn_t *) FM_SDIF_BASE))
Definition at line 163 of file sdif.h.
#define SDIF_INSTANCE_COUNT (uint8_t)(PDL_PERIPHERAL_ENABLE_SD0 == PDL_ON)
Definition at line 165 of file sdif.h.
Referenced by SdifGetInternDataPtr().
#define stc_sdifn_t FM_SDIF_TypeDef
Definition at line 162 of file sdif.h.
Typedef Documentation
typedef enum en_sdif_auto_cmd en_sdif_auto_cmd_t
SDIF auto command enable selection.
typedef enum en_sdif_cmd_type en_sdif_cmd_type_t
SD command types.
typedef enum en_sd_data_timeout en_sdif_data_timeout_t
SD data timeout time.
typedef enum en_sdif_err_irq_sel en_sdif_err_irq_sel_t
SDIF error interrupt types.
typedef enum en_sdif_instance_index en_sdif_instance_index_t
Enumeration to define an index for each enabled SDIF instance.
typedef enum en_sdif_normal_irq_sel en_sdif_normal_irq_sel_t
SDIF normal interrupt types.
typedef enum en_sdif_reset en_sdif_reset_t
SDIF software reset types.
typedef enum en_sdif_response_type en_sdif_response_type_t
SDIF response types.
typedef enum en_sdif_voltage_sel en_sdif_voltage_sel_t
SDIF voltage selection.
typedef struct stc_sdif_auto_cmd_err stc_sdif_auto_cmd_err_t
SDIF Auto Command error status.
typedef struct stc_sdif_cmd_config stc_sdif_cmd_config_t
SDIF command configuration.
typedef struct stc_sdif_config stc_sdif_config_t
SDIF configuration.
typedef struct stc_sdif_data_config stc_sdif_data_config_t
SDIF data transfer configuration.
typedef struct stc_sdif_err_irq_cb stc_sdif_err_irq_cb_t
SDIF error status callback functions.
typedef struct stc_sdif_err_irq stc_sdif_err_irq_en_t
typedef struct stc_sdif_err_irq stc_sdif_err_irq_status_t
SDIF error status types.
typedef struct stc_sdif_instance_data stc_sdif_instance_data_t
SDIF instance data type.
typedef struct stc_sdif_intern_data stc_sdif_intern_data_t
typedef struct stc_sdif_normal_irq_cb stc_sdif_normal_irq_cb_t
SDIF error status callback functions.
typedef struct stc_sdif_normal_irq stc_sdif_normal_irq_en_t
typedef struct stc_sdif_normal_irq stc_sdif_normal_irq_status_t
SDIF normal status types.
Enumeration Type Documentation
enum en_sd_data_timeout
SD data timeout time.
Enumerator:
SdifTimeout_BaseClk_2_13
Timeout time: Base clock*2^13.
SdifTimeout_BaseClk_2_14
Timeout time: Base clock*2^14.
SdifTimeout_BaseClk_2_15
Timeout time: Base clock*2^15.
SdifTimeout_BaseClk_2_16
Timeout time: Base clock*2^16.
SdifTimeout_BaseClk_2_17
Timeout time: Base clock*2^17.
SdifTimeout_BaseClk_2_18
Timeout time: Base clock*2^18.
SdifTimeout_BaseClk_2_19
Timeout time: Base clock*2^19.
SdifTimeout_BaseClk_2_20
Timeout time: Base clock*2^20.
SdifTimeout_BaseClk_2_21
Timeout time: Base clock*2^21.
SdifTimeout_BaseClk_2_22
Timeout time: Base clock*2^22.
SdifTimeout_BaseClk_2_23
Timeout time: Base clock*2^23.
SdifTimeout_BaseClk_2_24
Timeout time: Base clock*2^24.
SdifTimeout_BaseClk_2_25
Timeout time: Base clock*2^25.
SdifTimeout_BaseClk_2_26
Timeout time: Base clock*2^26.
SdifTimeout_BaseClk_2_27
Timeout time: Base clock*2^27.
Definition at line 201 of file sdif.h.
enum en_sdif_auto_cmd
SDIF auto command enable selection.
Enumerator:
SdifAutoCmdDisable
Auto command disable.
SdifAutoCmd12Enable
Auto command 12 enable.
SdifAutoCmd23Enable
Auto command 23 enable.
Definition at line 225 of file sdif.h.
enum en_sdif_cmd_type
SD command types.
Enumerator:
SdifCmdAbort
CMD12, CMD52 for writing "I/O Abort" in CCCR.
SdifCmdResume
CMD52 for writing "Function Select" in CCCR.
SdifCmdSuspend
CMD52 for writing "Bus Suspend" in CCCR.
SdifCmdNormal
Other commands.
Definition at line 175 of file sdif.h.
enum en_sdif_err_irq_sel
SDIF error interrupt types.
Enumerator:
SdifCmdTimeoutErrIrq
Command timeout error.
SdifCmdCrcErrIrq
Command CRC error.
SdifCmdEndBitErrIrq
Command end bit error.
SdifCmdIndexErrIrq
Command index error.
SdifDataTimeoutErrIrq
Data timeout error.
SdifDataCrcErrIrq
Data CRC error.
SdifDataEndBitErrIrq
Data end bit error.
SdifCurrentLimitErrIrq
Current limit error.
SdifAutoCmdErrIrq
Auto command error.
SdifAdmaErrIrq
ADMA error.
SdifTuningErrIrq
Tuning error.
Definition at line 265 of file sdif.h.
enum en_sdif_instance_index
Enumeration to define an index for each enabled SDIF instance.
Enumerator:
SdifInstanceIndexSdif0
SdifInstanceIndexMax
Definition at line 464 of file sdif.h.
enum en_sdif_normal_irq_sel
SDIF normal interrupt types.
Enumerator:
SdifCommandCompleteIrq
Command complete.
SdifTransferCompleteIrq
Transfer complete.
SdifBlockGapEventIrq
Block gap event.
SdifDmaIrq
DMA interrupt.
SdifBufferWriteReadyIrq
Buffer write ready.
SdifBufferReadReadyIrq
Buffer read ready.
SdifCardInsertionIrq
Card insertion.
SdifCardRemovalIrq
Card removal.
SdifCardIrq
Card interrupt.
Definition at line 331 of file sdif.h.
enum en_sdif_reset
SDIF software reset types.
Enumerator:
SdifResetDataLine
Only reset data circuit.
SdifResetCmdLine
Only reset command circuit.
SdifResetAll
Reset all SDIF host controller.
Definition at line 455 of file sdif.h.
enum en_sdif_response_type
SDIF response types.
Enumerator:
SdifResponseNone
No Response.
SdifResponse136Bit
Response Length 136.
SdifResponse48Bit
Response Length 48.
SdifResponse48BitCheckBusy
Response Length 48 check Busy after response.
Definition at line 188 of file sdif.h.
enum en_sdif_voltage_sel
SDIF voltage selection.
Enumerator:
SdifVoltage18v
SD bus voltge: 1.8V.
SdifVoltage30v
SD bus voltge: 3.0V.
SdifVoltage33v
SD bus voltge: 3.3V.
Definition at line 443 of file sdif.h.
Function Documentation
en_result_t Sdif_BusPowerOff (volatile FM_SDIF_TypeDef * pstcSdif)
Power off SD bus power.
This function stops power supply on SD bus
Parameters:
[in] pstcSdif SDIF instance
Return values:
Ok Power off normally
ErrorInvalidParameter pstcSdif == NULL
Definition at line 1200 of file sdif.c.
en_result_t Sdif_BusPowerOn (volatile FM_SDIF_TypeDef * pstcSdif)
Power on SD bus power.
This function starts power supply on SD bus
Parameters:
[in] pstcSdif SDIF instance
Return values:
Ok Power on normally
ErrorInvalidParameter pstcSdif == NULL
Definition at line 1176 of file sdif.c.
boolean_t Sdif_CheckCommandInhit (volatile FM_SDIF_TypeDef * pstcSdif)
Check the status of CMD line.
This function checks whether a commmand wiout data can be sent
Parameters:
[in] pstcSdif SDIF instance
Return values:
TRUE Command is ready to send
FALSE Command is inhitted to send
Definition at line 1566 of file sdif.c.
boolean_t Sdif_CheckCommandWithDataInhit (volatile FM_SDIF_TypeDef * pstcSdif)
Check the status of DAT line.
This function checks whether a commmand with data can be sent
Parameters:
[in] pstcSdif SDIF instance
Return values:
TRUE Command is ready to send
FALSE Command is inhitted to send
Definition at line 1582 of file sdif.c.
en_result_t Sdif_ClrErrStatus (volatile FM_SDIF_TypeDef * pstcSdif, stc_sdif_err_irq_status_t * pstcStatus)
Clear error status of SDIF.
This function clears the SDIF error status which is selected.
Parameters:
[in] pstcSdif SDIF instance
[in] pstcStatus Pointer to error status selection structure
Return values:
Ok Clear error status of SDIF normally
ErrorInvalidParameter If one of following cases matchs:
pstcSdif == NULL
pstcStatus == NULL
Definition at line 845 of file sdif.c.
References stc_sdif_err_irq::u16ErrStatus.
en_result_t Sdif_ClrNormalStatus (volatile FM_SDIF_TypeDef * pstcSdif, stc_sdif_normal_irq_status_t * pstcStatus)
Clear normal status of SDIF.
This function clears the SDIF normal status which is selected.
Parameters:
[in] pstcSdif SDIF instance
[in] pstcStatus Pointer to normal status selection structure
Return values:
Ok Clear normal status of SDIF normally
ErrorInvalidParameter If one of following cases matchs:
pstcSdif == NULL
pstcStatus == NULL
Definition at line 899 of file sdif.c.
References stc_sdif_normal_irq::u16NormalStatus.
en_result_t Sdif_DeInit (volatile FM_SDIF_TypeDef * pstcSdif, boolean_t bTouchIrq, boolean_t bTouchIrqCb, boolean_t bTouchNvic)
De-Initialize SD interface.
This function de-initializes an SDIF module
Parameters:
[in] pstcSdif SDIF instance
[in] bTouchIrq Disable IRQ or not
[in] bTouchIrqCb Reset callback functions in internal data or not
[in] bTouchNvic Disable NVIC or not
Return values:
Ok SDIF de-initialized normally
ErrorInvalidParameter pstcSdif == NULL
Definition at line 484 of file sdif.c.
References stc_sdif_err_irq_cb::pfnAdmaErrIrqCb, stc_sdif_err_irq_cb::pfnAutoCmdErrIrqCb, stc_sdif_normal_irq_cb::pfnBlockGapIrqCb, stc_sdif_normal_irq_cb::pfnBufferReadReadyIrqCb, stc_sdif_normal_irq_cb::pfnBufferWriteReadyIrqCb, stc_sdif_normal_irq_cb::pfnCardInsertIrqCb, stc_sdif_normal_irq_cb::pfnCardIrqCb, stc_sdif_normal_irq_cb::pfnCardRemovalIrqCb, stc_sdif_err_irq_cb::pfnCmdCrcErrIrqCb, stc_sdif_err_irq_cb::pfnCmdEndBitErrIrqCb, stc_sdif_err_irq_cb::pfnCmdIndexErrIrqCb, stc_sdif_err_irq_cb::pfnCmdTimeoutErrIrqCb, stc_sdif_normal_irq_cb::pfnCommandCompleteIrqCb, stc_sdif_err_irq_cb::pfnCurrentLimitErrIrqCb, stc_sdif_err_irq_cb::pfnDataCrcErrIrqCb, stc_sdif_err_irq_cb::pfnDataEndBitErrIrqCb, stc_sdif_err_irq_cb::pfnDataTimeoutErrIrqCb, stc_sdif_normal_irq_cb::pfnDmaIrqCb, stc_sdif_normal_irq_cb::pfnTransferCompleteIrqCb, stc_sdif_err_irq_cb::pfnTuningErrIrqCb, SdifDeInitNvic(), SdifGetInternDataPtr(), stc_sdif_intern_data::stcErrIrqCb, and stc_sdif_intern_data::stcNormalIrqCb.
en_result_t Sdif_DisableErrIrq (volatile FM_SDIF_TypeDef * pstcSdif, en_sdif_err_irq_sel_t enErrIrqSel)
Disable SDIF error interrupt.
This function disable the SDIF error interrupt which is selected.
Parameters:
[in] pstcSdif SDIF instance
[in] enErrIrqSel SDIF error interrupt selection
Return values:
Ok Disable error interrupt normally
ErrorInvalidParameter If one of following cases matchs:
pstcSdif == NULL
enErrIrqSel out of range
Definition at line 750 of file sdif.c.
References SdifAdmaErrIrq, SdifAutoCmdErrIrq, SdifCmdCrcErrIrq, SdifCmdEndBitErrIrq, SdifCmdIndexErrIrq, SdifCmdTimeoutErrIrq, SdifCurrentLimitErrIrq, SdifDataCrcErrIrq, SdifDataEndBitErrIrq, SdifDataTimeoutErrIrq, and SdifTuningErrIrq.
en_result_t Sdif_DisableInternalClock (volatile FM_SDIF_TypeDef * pstcSdif)
Disable internal clock of SDIF.
This function makes SD host controller stop working.
Parameters:
[in] pstcSdif SDIF instance
Return values:
Ok Internal clock of SDIF enabled normally
ErrorInvalidParameter pstcSdif == NULL
Definition at line 978 of file sdif.c.
en_result_t Sdif_DisableNomralIrq (volatile FM_SDIF_TypeDef * pstcSdif, en_sdif_normal_irq_sel_t enIrqSel)
en_result_t Sdif_DisableNormalIrq (volatile FM_SDIF_TypeDef * pstcSdif, en_sdif_normal_irq_sel_t enNormalIrqSel)
Disable SDIF normal interrupt.
This function disable the SDIF interrupt which is selected.
Parameters:
[in] pstcSdif SDIF instance
[in] enNormalIrqSel SDIF normal interrupt selection
Return values:
Ok Disable normal interrupt normally
ErrorInvalidParameter If one of following cases matchs:
pstcSdif == NULL
enNormalIrqSel out of range
Definition at line 626 of file sdif.c.
References SdifBlockGapEventIrq, SdifBufferReadReadyIrq, SdifBufferWriteReadyIrq, SdifCardInsertionIrq, SdifCardIrq, SdifCardRemovalIrq, SdifCommandCompleteIrq, SdifDmaIrq, and SdifTransferCompleteIrq.
en_result_t Sdif_DisableSdclk (volatile FM_SDIF_TypeDef * pstcSdif)
Disable SDCLK output.
SD host don't drive SDCLK line.
Parameters:
[in] pstcSdif SDIF instance
Return values:
Ok SDCLK output of SDIF disabled normally
ErrorInvalidParameter pstcSdif == NULL
Definition at line 1026 of file sdif.c.
en_result_t Sdif_EnableErrIrq (volatile FM_SDIF_TypeDef * pstcSdif, en_sdif_err_irq_sel_t enErrIrqSel)
Enable SDIF error interrupt.
This function enable the SDIF error interrupt which is selected.
Parameters:
[in] pstcSdif SDIF instance
[in] enErrIrqSel SDIF error interrupt selection
Return values:
Ok Enable error interrupt normally
ErrorInvalidParameter If one of following cases matchs:
pstcSdif == NULL
enErrIrqSel out of range
Definition at line 685 of file sdif.c.
References SdifAdmaErrIrq, SdifAutoCmdErrIrq, SdifCmdCrcErrIrq, SdifCmdEndBitErrIrq, SdifCmdIndexErrIrq, SdifCmdTimeoutErrIrq, SdifCurrentLimitErrIrq, SdifDataCrcErrIrq, SdifDataEndBitErrIrq, SdifDataTimeoutErrIrq, and SdifTuningErrIrq.
en_result_t Sdif_EnableInternalClock (volatile FM_SDIF_TypeDef * pstcSdif)
Enable internal clock of SDIF.
This function makes SD host controller start working.
Parameters:
[in] pstcSdif SDIF instance
Return values:
Ok Internal clock of SDIF enabled normally
ErrorInvalidParameter pstcSdif == NULL
Definition at line 952 of file sdif.c.
en_result_t Sdif_EnableNormalIrq (volatile FM_SDIF_TypeDef * pstcSdif, en_sdif_normal_irq_sel_t enNormalIrqSel)
Enable SDIF normal interrupt.
This function enable the SDIF interrupt which is selected.
Parameters:
[in] pstcSdif SDIF instance
[in] enNormalIrqSel SDIF normal interrupt selection
Return values:
Ok Enable normal interrupt normally
ErrorInvalidParameter If one of following cases matchs:
pstcSdif == NULL
enNormalIrqSel out of range
Definition at line 567 of file sdif.c.
References SdifBlockGapEventIrq, SdifBufferReadReadyIrq, SdifBufferWriteReadyIrq, SdifCardInsertionIrq, SdifCardIrq, SdifCardRemovalIrq, SdifCommandCompleteIrq, SdifDmaIrq, and SdifTransferCompleteIrq.
en_result_t Sdif_EnableSdclk (volatile FM_SDIF_TypeDef * pstcSdif)
Enable SDCLK output.
SD host drives SDCLK line.
Parameters:
[in] pstcSdif SDIF instance
Return values:
Ok SDCLK output of SDIF enabled normally
ErrorInvalidParameter pstcSdif == NULL
Definition at line 1002 of file sdif.c.
en_result_t Sdif_GetAutoCommandErrStatus (volatile FM_SDIF_TypeDef * pstcSdif, stc_sdif_auto_cmd_err_t * pstcStatus)
Get error status of SDIF auto command.
This function gets the SDIF error status of auto command
Parameters:
[in] pstcSdif SDIF instance
[in] pstcStatus Pointer to normal status selection structure
Return values:
Ok Auto command error status of SDIF gotten normally
ErrorInvalidParameter If one of following cases matchs:
pstcSdif == NULL
pstcStatus == NULL
Definition at line 927 of file sdif.c.
References stc_sdif_auto_cmd_err::u16AutoCmdErr.
en_result_t Sdif_GetErrStatus (volatile FM_SDIF_TypeDef * pstcSdif, stc_sdif_err_irq_status_t * pstcStatus)
Get error status of SDIF.
This function gets the SDIF error status.
Parameters:
[in] pstcSdif SDIF instance
[out] pstcStatus Pointer to error status selection structure
Return values:
Ok Get error status of SDIF normally
ErrorInvalidParameter If one of following cases matchs:
pstcSdif == NULL
pstcStatus == NULL
Definition at line 817 of file sdif.c.
References stc_sdif_err_irq::u16ErrStatus.
en_result_t Sdif_GetNormalStatus (volatile FM_SDIF_TypeDef * pstcSdif, stc_sdif_normal_irq_status_t * pstcStatus)
Get normal status of SDIF.
This function gets the SDIF normal status.
Parameters:
[in] pstcSdif SDIF instance
[out] pstcStatus Pointer to normal status selection structure
Return values:
Ok Get normal status of SDIF normally
ErrorInvalidParameter pstcSdif == NULL
Definition at line 871 of file sdif.c.
References stc_sdif_normal_irq::u16NormalStatus.
en_result_t Sdif_GetResponse (volatile FM_SDIF_TypeDef * pstcSdif, uint16_t * pu16ResponseData, uint8_t u8ResponseRegCount)
Get SD response.
This function receives response on CMD line
Parameters:
[in] pstcSdif SDIF instance
[out] pu16ResponseData pointer to response data
[in] u8ResponseRegCount Response register count
Return values:
Ok Response received normally
ErrorInvalidParameter pstcSdif == NULL or u8ResponseRegCount > 8u
Definition at line 1327 of file sdif.c.
en_result_t Sdif_Init (volatile FM_SDIF_TypeDef * pstcSdif, stc_sdif_config_t * pstcConfig)
Initialize SD interface.
This function initializes an SDIF module
Parameters:
[in] pstcSdif SDIF instance
[in] pstcConfig SDIF module configuration
Return values:
Ok SDIF initialized normally
ErrorInvalidParameter If one of following cases matchs:
pstcSdif == NULL
pstcConfig == NULL
Other invalid configuration
Definition at line 381 of file sdif.c.
References stc_sdif_config::bEnable4BitMode, stc_sdif_config::bEnableHighSpeed, stc_sdif_config::bSelAdma, stc_sdif_config::bTouchNvic, stc_sdif_err_irq_cb::pfnAdmaErrIrqCb, stc_sdif_err_irq_cb::pfnAutoCmdErrIrqCb, stc_sdif_normal_irq_cb::pfnBlockGapIrqCb, stc_sdif_normal_irq_cb::pfnBufferReadReadyIrqCb, stc_sdif_normal_irq_cb::pfnBufferWriteReadyIrqCb, stc_sdif_normal_irq_cb::pfnCardInsertIrqCb, stc_sdif_normal_irq_cb::pfnCardIrqCb, stc_sdif_normal_irq_cb::pfnCardRemovalIrqCb, stc_sdif_err_irq_cb::pfnCmdCrcErrIrqCb, stc_sdif_err_irq_cb::pfnCmdEndBitErrIrqCb, stc_sdif_err_irq_cb::pfnCmdIndexErrIrqCb, stc_sdif_err_irq_cb::pfnCmdTimeoutErrIrqCb, stc_sdif_normal_irq_cb::pfnCommandCompleteIrqCb, stc_sdif_err_irq_cb::pfnCurrentLimitErrIrqCb, stc_sdif_err_irq_cb::pfnDataCrcErrIrqCb, stc_sdif_err_irq_cb::pfnDataEndBitErrIrqCb, stc_sdif_err_irq_cb::pfnDataTimeoutErrIrqCb, stc_sdif_normal_irq_cb::pfnDmaIrqCb, stc_sdif_normal_irq_cb::pfnTransferCompleteIrqCb, stc_sdif_err_irq_cb::pfnTuningErrIrqCb, stc_sdif_config::pstcErrIrqCb, stc_sdif_config::pstcErrIrqEn, stc_sdif_config::pstcNormalIrqCb, stc_sdif_config::pstcNormalIrqEn, SdifGetInternDataPtr(), SdifInitNvic(), stc_sdif_intern_data::stcErrIrqCb, stc_sdif_intern_data::stcNormalIrqCb, stc_sdif_err_irq::u16ErrStatus, and stc_sdif_normal_irq::u16NormalStatus.
en_result_t Sdif_InitDataTransfer (volatile FM_SDIF_TypeDef * pstcSdif, stc_sdif_data_config_t * pstcDataConfig)
Initialize data transfer.
This function must be called before data transfer to initialize data transfer mode.
Parameters:
[in] pstcSdif SDIF instance
[in] pstcDataConfig pointer to data transfer configuration
Return values:
Ok Data is initialized normally
ErrorInvalidParameter pstcSdif == NULL or pstcDataConfig == NULL
Definition at line 1363 of file sdif.c.
References stc_sdif_data_config::bBlockCountEnable, stc_sdif_data_config::bEnableDma, stc_sdif_data_config::bMultipleBlock, stc_sdif_data_config::bRead, SdifTimeout_BaseClk_2_27, stc_sdif_data_config::u16BlockCount, stc_sdif_data_config::u16BlockSize, stc_sdif_data_config::u32AdmaDespTableAddress, and stc_sdif_data_config::u8DataTimeout.
boolean_t Sdif_PollCardInsert (volatile FM_SDIF_TypeDef * pstcSdif)
Poll card insertion status.
This function checks card is inserted or not
Parameters:
[in] pstcSdif SDIF instance
Return values:
TRUE Card is inserted
FALSE Card is removed
Definition at line 1505 of file sdif.c.
uint32_t Sdif_ReadData (volatile FM_SDIF_TypeDef * pstcSdif)
Read data from SD data buffer port.
This function reads 32-bit data from data buffer
Parameters:
[in] pstcSdif SDIF instance
Return values:
Data that is read
Definition at line 1415 of file sdif.c.
en_result_t Sdif_RestartTransfer (volatile FM_SDIF_TypeDef * pstcSdif)
Restart data transfer.
This function is used to restart data transfer when transfer is pending
Parameters:
[in] pstcSdif SDIF instance
Return values:
Ok Data restarts tranfer normally
ErrorInvalidParameter pstcSdif == NULL
Definition at line 1481 of file sdif.c.
en_result_t Sdif_SelBusVoltage (volatile FM_SDIF_TypeDef * pstcSdif, en_sdif_voltage_sel_t enVoltage)
Select bus voltage of SD bus.
This function selects the SD bus voltage
Parameters:
[in] pstcSdif SDIF instance
[in] enVoltage Voltage selection
Return values:
Ok Voltage selected normally
ErrorInvalidParameter pstcSdif == NULL or enVoltage out of range
Definition at line 1138 of file sdif.c.
References SdifVoltage18v, SdifVoltage30v, and SdifVoltage33v.
en_result_t Sdif_SendCommand (volatile FM_SDIF_TypeDef * pstcSdif, stc_sdif_cmd_config_t * pstcConfig)
Send SD command.
This function sends command on CMD line
Parameters:
[in] pstcSdif SDIF instance
[in] pstcConfig Pointer to command structure
Return values:
Ok Command sent normally
ErrorInvalidParameter pstcSdif == NULL or pstcConfig == NULL
Definition at line 1225 of file sdif.c.
References stc_sdif_cmd_config::bCmdCrcCheck, stc_sdif_cmd_config::bCmdIndexCheck, stc_sdif_cmd_config::bDataPresent, stc_sdif_cmd_config::enAutoCmdType, stc_sdif_cmd_config::enCmdType, stc_sdif_cmd_config::enResponseType, PDL_ZERO_STRUCT, SdifAutoCmd12Enable, SdifAutoCmd23Enable, SdifAutoCmdDisable, SdifCmdAbort, SdifCmdNormal, SdifCmdResume, SdifCmdSuspend, SdifResponse136Bit, SdifResponse48Bit, SdifResponse48BitCheckBusy, SdifResponseNone, stc_sdif_cmd_config::u32Argument, and stc_sdif_cmd_config::u8CmdIndex.
en_result_t Sdif_SetBusSpeedMode (volatile FM_SDIF_TypeDef * pstcSdif, boolean_t bEnableHighSpeedMode)
Set the bus speed mode of SD Bus.
This function changes the SD bus width.
Parameters:
[in] pstcSdif SDIF instance
[in] bEnableHighSpeedMode Enable high speed mode or not
Return values:
Ok Bus width is set normally
ErrorInvalidParameter pstcSdif == NULL
Definition at line 1105 of file sdif.c.
en_result_t Sdif_SetBusWidth (volatile FM_SDIF_TypeDef * pstcSdif, boolean_t bEnable4BitMode)
Set the bus width of SD Bus.
This function changes the SD bus width.
Parameters:
[in] pstcSdif SDIF instance
[in] bEnable4BitMode Enable 4-bit mode or not
Return values:
Ok Bus width is set normally
ErrorInvalidParameter pstcSdif == NULL
Definition at line 1078 of file sdif.c.
en_result_t Sdif_SetClkDiv (volatile FM_SDIF_TypeDef * pstcSdif, uint16_t u16Div)
Set the clock division of SD clock.
This function changes the SD clock division.
Parameters:
[in] pstcSdif SDIF instance
[in] u16Div Division value
Return values:
Ok Clock division is changed normally
ErrorInvalidParameter pstcSdif == NULL
Definition at line 1051 of file sdif.c.
en_result_t Sdif_SetWakeupFactor (volatile FM_SDIF_TypeDef * pstcSdif, boolean_t bCardRemovalWakeup, boolean_t bCardInsertWakeup, boolean_t bCardIrqWakeup)
Set the wakeup factor.
This function sets SD host wakeup factors.
Parameters:
[in] pstcSdif SDIF instance
[in] bCardRemovalWakeup Whether card removal triggers SD host wakeup
[in] bCardInsertWakeup Whether card insertion triggers SD host wakeup
[in] bCardIrqWakeup Whether card interrupt triggers SD host wakeup
Return values:
Ok SD host wakeup factor set normally
FALSE Command is inhitted to send
Definition at line 1601 of file sdif.c.
en_result_t Sdif_SoftwareReset (volatile FM_SDIF_TypeDef * pstcSdif, en_sdif_reset_t enReset)
Issue software reset to SD card.
This function issues software reset all command to SD card
Parameters:
[in] pstcSdif SDIF instance
[in] enReset Reset type
Return values:
Ok Software reset is done normally
ErrorInvalidParameter pstcSdif == NULL
Definition at line 1525 of file sdif.c.
References SdifResetAll, SdifResetCmdLine, and SdifResetDataLine.
en_result_t Sdif_StopAtBlockGap (volatile FM_SDIF_TypeDef * pstcSdif)
Stop data transfer during block gap.
This function is used to stop data trasnfer of multi-block transfer
Parameters:
[in] pstcSdif SDIF instance
Return values:
Ok Data stops tranfer normally
ErrorInvalidParameter pstcSdif == NULL
Definition at line 1457 of file sdif.c.
en_result_t Sdif_WriteData (volatile FM_SDIF_TypeDef * pstcSdif, uint32_t u32Data)
Write data to SD data buffer port.
This function writes 32-bit data to data buffer
Parameters:
[in] pstcSdif SDIF instance
[in] u32Data Data to be written
Return values:
Ok Data is written normally
ErrorInvalidParameter pstcSdif == NULL
Definition at line 1432 of file sdif.c.
static void SdifDeInitNvic (volatile FM_SDIF_TypeDef * pstcSdif) [static]
Clear NVIC Interrupt depending on SDIF instance.
Parameters:
pstcSdif Pointer to SDIF instance
Definition at line 328 of file sdif.c.
References PDL_DEFAULT_INTERRUPT_LEVEL.
Referenced by Sdif_DeInit().
static stc_sdif_intern_data_t * SdifGetInternDataPtr (volatile FM_SDIF_TypeDef * pstcSdif) [static]
Return the internal data for a certain SDIF instance.
Parameters:
pstcSdif Pointer to SDIF instance
Returns:
Pointer to internal data or NULL if instance is not enabled (or not known)
Definition at line 346 of file sdif.c.
References SDIF_INSTANCE_COUNT, and stc_sdif_instance_data::stcInternData.
Referenced by Sdif_DeInit(), and Sdif_Init().
static void SdifInitNvic (volatile FM_SDIF_TypeDef * pstcSdif) [static]
Set NVIC Interrupt depending on SDIF instance.
Parameters:
pstcSdif Pointer to SDIF instance
Definition at line 314 of file sdif.c.
Referenced by Sdif_Init().
void SdifIrqHandler (volatile FM_SDIF_TypeDef * pstcSdif, stc_sdif_intern_data_t * pstcSdifInternData)
SDIF instance interrupt service routine.
SDIF instance interrupt service routine, clear interrupt cause and
Parameters:
pstcSdif Pointer to SDIF instance
pstcSdifInternData Pointer to SDIF intern data
Definition at line 119 of file sdif.c.
References stc_sdif_err_irq_cb::pfnAdmaErrIrqCb, stc_sdif_err_irq_cb::pfnAutoCmdErrIrqCb, stc_sdif_normal_irq_cb::pfnBlockGapIrqCb, stc_sdif_normal_irq_cb::pfnBufferReadReadyIrqCb, stc_sdif_normal_irq_cb::pfnBufferWriteReadyIrqCb, stc_sdif_normal_irq_cb::pfnCardInsertIrqCb, stc_sdif_normal_irq_cb::pfnCardIrqCb, stc_sdif_normal_irq_cb::pfnCardRemovalIrqCb, stc_sdif_err_irq_cb::pfnCmdCrcErrIrqCb, stc_sdif_err_irq_cb::pfnCmdEndBitErrIrqCb, stc_sdif_err_irq_cb::pfnCmdIndexErrIrqCb, stc_sdif_err_irq_cb::pfnCmdTimeoutErrIrqCb, stc_sdif_normal_irq_cb::pfnCommandCompleteIrqCb, stc_sdif_err_irq_cb::pfnCurrentLimitErrIrqCb, stc_sdif_err_irq_cb::pfnDataCrcErrIrqCb, stc_sdif_err_irq_cb::pfnDataEndBitErrIrqCb, stc_sdif_err_irq_cb::pfnDataTimeoutErrIrqCb, stc_sdif_normal_irq_cb::pfnDmaIrqCb, stc_sdif_normal_irq_cb::pfnTransferCompleteIrqCb, stc_sdif_err_irq_cb::pfnTuningErrIrqCb, stc_sdif_intern_data::stcErrIrqCb, and stc_sdif_intern_data::stcNormalIrqCb.
Variable Documentation
stc_sdif_instance_data_t m_astcSdifInstanceDataLut[(uint8_t)(PDL_PERIPHERAL_ENABLE_SD0==PDL_ON)]
Initial value:
{
    {
        & (*((volatile  FM_SDIF_TypeDef  *) FM_SDIF_BASE)) ,
        {
            0u,
            0u,
        }
    },
}
Look-up table for all enabled ADC instances and their internal data.
Look-up table for all enabled SD instances and their internal data.
Definition at line 73 of file sdif.c.
stc_sdif_instance_data_t m_astcSdifInstanceDataLut[(uint8_t)(PDL_PERIPHERAL_ENABLE_SD0==PDL_ON)]
Look-up table for all enabled SD instances and their internal data.
Definition at line 73 of file sdif.c.