PDL for FM Family: Descriptor System Data Transfer Controller (DSTC)
Descriptor System Data Transfer Controller (DSTC)
Data Structures
struct stc_dstc_dreqenb
DREQENB structure.
struct stc_dstc_hwint
HWINT structure.
struct stc_dstc_hwintclr
HWINTCLR structure.
struct stc_dstc_dqmsk
DQMSK structure.
struct stc_dstc_dqmskclr
DQMSKCLR structure.
struct stc_dstc_des0
Definition of Descriptor 0 (DES0 - Transfer Basic Setting)
struct stc_dstc_des1_mode0
Definition of Descriptor 1 (DES1 - Number of Transfers) in Mode 0.
struct stc_dstc_des1_mode1
Definition of Descriptor 1 (DES1 - Number of Transfers) in Mode 1.
struct stc_dstc_des0123
Definition of Descriptor Group DES0 - DES3.
struct stc_dstc_des01234
Definition of Descriptor Group DES0 - DES4.
struct stc_dstc_des012345
Definition of Descriptor Group DES0 - DES5.
struct stc_dstc_des0123456
Definition of Descriptor Group DES0 - DES6.
struct stc_dstc_des01235
Definition of Descriptor Group DES0 - DES3, DES5.
struct stc_dstc_des01236
Definition of Descriptor Group DES0 - DES3, DES6.
struct stc_dstc_des012346
Definition of Descriptor Group DES0 - DES4, DES6.
struct stc_dstc_des012356
Definition of Descriptor Group DES0 - DES3, DES5, DES6.
struct stc_dstc_config
DSTC configuration.
struct stc_dstc_intern_data
DSTC Intern Data.
Defines
#define DSTC_TRANSITION_TIMEOUT 100000u
Timeout counter for DSTC mode transition.
#define DSTC_PCHK_CALC(x)
Parity checksum for DES0 PCHKS bits.
#define DSTC_IRQ_NUMBER_ADC0_PRIO 110u
DSTC interrupt numbers.
#define DSTC_IRQ_NUMBER_ADC0_SCAN 111u
#define DSTC_IRQ_NUMBER_ADC1_PRIO 112u
#define DSTC_IRQ_NUMBER_ADC1_SCAN 113u
#define DSTC_IRQ_NUMBER_BT0_IRQ0 16u
#define DSTC_IRQ_NUMBER_BT0_IRQ1 17u
#define DSTC_IRQ_NUMBER_BT1_IRQ0 18u
#define DSTC_IRQ_NUMBER_BT1_IRQ1 19u
#define DSTC_IRQ_NUMBER_BT2_IRQ0 20u
#define DSTC_IRQ_NUMBER_BT2_IRQ1 21u
#define DSTC_IRQ_NUMBER_BT3_IRQ0 22u
#define DSTC_IRQ_NUMBER_BT3_IRQ1 23u
#define DSTC_IRQ_NUMBER_BT4_IRQ0 24u
#define DSTC_IRQ_NUMBER_BT4_IRQ1 25u
#define DSTC_IRQ_NUMBER_BT5_IRQ0 26u
#define DSTC_IRQ_NUMBER_BT5_IRQ1 27u
#define DSTC_IRQ_NUMBER_BT6_IRQ0 28u
#define DSTC_IRQ_NUMBER_BT6_IRQ1 29u
#define DSTC_IRQ_NUMBER_BT7_IRQ0 30u
#define DSTC_IRQ_NUMBER_BT7_IRQ1 31u
#define DSTC_IRQ_NUMBER_CANFD 127u
#define DSTC_IRQ_NUMBER_EXTINT0 0u
#define DSTC_IRQ_NUMBER_EXTINT1 1u
#define DSTC_IRQ_NUMBER_EXTINT2 2u
#define DSTC_IRQ_NUMBER_EXTINT3 3u
#define DSTC_IRQ_NUMBER_EXTINT4 4u
#define DSTC_IRQ_NUMBER_EXTINT5 5u
#define DSTC_IRQ_NUMBER_EXTINT6 6u
#define DSTC_IRQ_NUMBER_EXTINT7 7u
#define DSTC_IRQ_NUMBER_EXTINT8 8u
#define DSTC_IRQ_NUMBER_EXTINT9 9u
#define DSTC_IRQ_NUMBER_EXTINT10 10u
#define DSTC_IRQ_NUMBER_EXTINT11 11u
#define DSTC_IRQ_NUMBER_EXTINT12 12u
#define DSTC_IRQ_NUMBER_EXTINT13 13u
#define DSTC_IRQ_NUMBER_EXTINT14 14u
#define DSTC_IRQ_NUMBER_EXTINT15 15u
#define DSTC_IRQ_NUMBER_HSSPI0_TX 125u
#define DSTC_IRQ_NUMBER_HSSPI0_RX 124u
#define DSTC_IRQ_NUMBER_I2S0_TX 121u
#define DSTC_IRQ_NUMBER_I2S0_RX 120u
#define DSTC_IRQ_NUMBER_I2S1_TX 123u
#define DSTC_IRQ_NUMBER_I2S1_RX 122u
#define DSTC_IRQ_NUMBER_MFS0_RX 89u
#define DSTC_IRQ_NUMBER_MFS0_TX 90u
#define DSTC_IRQ_NUMBER_MFS1_RX 91u
#define DSTC_IRQ_NUMBER_MFS1_TX 92u
#define DSTC_IRQ_NUMBER_MFS2_RX 93u
#define DSTC_IRQ_NUMBER_MFS2_TX 94u
#define DSTC_IRQ_NUMBER_MFS3_RX 95u
#define DSTC_IRQ_NUMBER_MFS3_TX 96u
#define DSTC_IRQ_NUMBER_MFS4_RX 97u
#define DSTC_IRQ_NUMBER_MFS4_TX 98u
#define DSTC_IRQ_NUMBER_MFS5_RX 99u
#define DSTC_IRQ_NUMBER_MFS5_TX 100u
#define DSTC_IRQ_NUMBER_MFS6_RX 101u
#define DSTC_IRQ_NUMBER_MFS6_TX 102u
#define DSTC_IRQ_NUMBER_MFS7_RX 103u
#define DSTC_IRQ_NUMBER_MFS7_TX 104u
#define DSTC_IRQ_NUMBER_MFT0_FRT0_PEAK 35u
#define DSTC_IRQ_NUMBER_MFT0_FRT0_ZERO 38u
#define DSTC_IRQ_NUMBER_MFT0_FRT1_PEAK 36u
#define DSTC_IRQ_NUMBER_MFT0_FRT1_ZERO 39u
#define DSTC_IRQ_NUMBER_MFT0_FRT2_PEAK 37u
#define DSTC_IRQ_NUMBER_MFT0_FRT2_ZERO 40u
#define DSTC_IRQ_NUMBER_MFT0_ICU0 41u
#define DSTC_IRQ_NUMBER_MFT0_ICU1 42u
#define DSTC_IRQ_NUMBER_MFT0_ICU2 43u
#define DSTC_IRQ_NUMBER_MFT0_ICU3 44u
#define DSTC_IRQ_NUMBER_MFT0_OCU0 45u
#define DSTC_IRQ_NUMBER_MFT0_OCU1 46u
#define DSTC_IRQ_NUMBER_MFT0_OCU2 47u
#define DSTC_IRQ_NUMBER_MFT0_OCU3 48u
#define DSTC_IRQ_NUMBER_MFT0_OCU4 49u
#define DSTC_IRQ_NUMBER_MFT0_OCU5 50u
#define DSTC_IRQ_NUMBER_MFT0_WFG10 32u
#define DSTC_IRQ_NUMBER_MFT0_WFG32 33u
#define DSTC_IRQ_NUMBER_MFT0_WFG54 34u
#define DSTC_IRQ_NUMBER_PCRC 126u
#define DSTC_IRQ_NUMBER_PPG0 70u
#define DSTC_IRQ_NUMBER_PPG2 71u
#define DSTC_IRQ_NUMBER_PPG4 72u
#define DSTC_IRQ_NUMBER_QPRC0_COUNT_INVERSION 79u
#define DSTC_IRQ_NUMBER_QPRC0_OUT_OF_RANGE 80u
#define DSTC_IRQ_NUMBER_QPRC0_PC_MATCH 76u
#define DSTC_IRQ_NUMBER_QPRC0_PC_MATCH_RC_MATCH 81u
#define DSTC_IRQ_NUMBER_QPRC0_PC_RC_MATCH 77u
#define DSTC_IRQ_NUMBER_QPRC0_UFL_OFL_Z 78u
#define DSTC_IRQ_NUMBER_USB0_EP1 105u
#define DSTC_IRQ_NUMBER_USB0_EP2 106u
#define DSTC_IRQ_NUMBER_USB0_EP3 107u
#define DSTC_IRQ_NUMBER_USB0_EP4 108u
#define DSTC_IRQ_NUMBER_USB0_EP5 109u
#define DSTC_IRQ_NUMBER_WC 88u
Typedefs
typedef enum en_dstc_cmd en_dstc_cmd_t
DSTC Commands.
typedef enum en_dstc_swpr en_dstc_swpr_t
Software Transfer Priority.
typedef enum en_dstc_est_error en_dstc_est_error_t
MONERS EST Error Code.
typedef void(* func_ptr_dstc_args_t)(en_dstc_est_error_t enEstError, uint16_t u16ErrorChannel, uint16_t u16ErrorDesPointer, boolean_t bSoftwareError, boolean_t bDoubleError, boolean_t bErrorStop)
Error Status Callback.
typedef struct stc_dstc_dreqenb stc_dstc_dreqenb_t
DREQENB structure.
typedef struct stc_dstc_hwint stc_dstc_hwint_t
HWINT structure.
typedef struct stc_dstc_hwintclr stc_dstc_hwintclr_t
HWINTCLR structure.
typedef struct stc_dstc_dqmsk stc_dstc_dqmsk_t
DQMSK structure.
typedef struct stc_dstc_dqmskclr stc_dstc_dqmskclr_t
DQMSKCLR structure.
typedef struct stc_dstc_des0 stc_dstc_des0_t
Definition of Descriptor 0 (DES0 - Transfer Basic Setting)
typedef struct stc_dstc_des1_mode0 stc_dstc_des1_mode0_t
Definition of Descriptor 1 (DES1 - Number of Transfers) in Mode 0.
typedef struct stc_dstc_des1_mode1 stc_dstc_des1_mode1_t
Definition of Descriptor 1 (DES1 - Number of Transfers) in Mode 1.
typedef struct stc_dstc_des0123 stc_dstc_des0123_t
Definition of Descriptor Group DES0 - DES3.
typedef struct stc_dstc_des01234 stc_dstc_des01234_t
Definition of Descriptor Group DES0 - DES4.
typedef struct stc_dstc_des012345 stc_dstc_des012345_t
Definition of Descriptor Group DES0 - DES5.
typedef struct stc_dstc_des0123456 stc_dstc_des0123456_t
Definition of Descriptor Group DES0 - DES6.
typedef struct stc_dstc_des01235 stc_dstc_des01235_t
Definition of Descriptor Group DES0 - DES3, DES5.
typedef struct stc_dstc_des01236 stc_dstc_des01236_t
Definition of Descriptor Group DES0 - DES3, DES6.
typedef struct stc_dstc_des012346 stc_dstc_des012346_t
Definition of Descriptor Group DES0 - DES4, DES6.
typedef struct stc_dstc_des012356 stc_dstc_des012356_t
Definition of Descriptor Group DES0 - DES3, DES5, DES6.
typedef struct stc_dstc_config stc_dstc_config_t
DSTC configuration.
typedef struct stc_dstc_intern_data stc_dstc_intern_data_t
DSTC Intern Data.
Enumerations
enum en_dstc_cmd {
CmdStandyRelease = 0u, CmdStandyTransition = 1u, CmdSwclr = 2u, CmdErclr = 3u,
CmdRbclr = 4u, CmdMkclr = 5u
}
DSTC Commands.
enum en_dstc_swpr {
PriorityHighest = 0u, Priority1_2 = 1u, Priority1_3 = 2u, Priority1_7 = 3u,
Priority1_15 = 4u, Priority1_31 = 5u, Priority1_63 = 6u, PriorityLowest = 7u
}
Software Transfer Priority.
enum en_dstc_est_error {
NoError = 0u, SourceAccessError = 1u, DestinationAccessError = 2u, ForcedTransferStop = 3u,
DesAccessError = 4u, DesOpenError = 5u, UnknownError = 6u
}
MONERS EST Error Code.
Functions
void Dstc_IrqHandler (void)
Interrupt Service Routine of DSTC.
en_result_t Dstc_ReleaseStandBy (void)
Release DSTC from Standby State.
en_result_t Dstc_Init (stc_dstc_config_t *pstcConfig)
Initializes the DSTC according the Configuration.
en_result_t Dstc_DeInit (boolean_t bTouchNvic)
De-Initializes the the DSTC.
en_result_t Dstc_SetHwdesp (uint8_t u8Channel, uint16_t u16HwDesp)
Initializes a DSTC channel.
uint16_t Dstc_ReadHwdesp (uint8_t u8Channel)
Read the HWDESP Address Offset of a Channel.
en_result_t Dstc_SetCommand (en_dstc_cmd_t enCommand)
Set a Command to CMD Register.
en_result_t Dstc_SwTrigger (uint16_t u16SwDesPointer)
Set SWDESP offset and trigger SW transfer.
en_result_t Dstc_SwTrqansferStartStatus (void)
Check Software Trigger Start State.
en_result_t Dstc_SetDreqenb (stc_dstc_dreqenb_t *pstcDreqenb)
Set DREQENB Register.
en_result_t Dstc_ReadDreqenb (stc_dstc_dreqenb_t *pstcDreqenb)
Read DREQENB Register.
en_result_t Dstc_SetDreqenbBit (uint8_t u8BitPos)
Set DREQENB Register Bit.
en_result_t Dstc_ClearDreqenbBit (uint8_t u8BitPos)
Clear DREQENB Register Bit.
en_result_t Dstc_ReadHwint (stc_dstc_hwint_t *pstcHwint)
Read HWINT Register.
en_result_t Dstc_SetHwintclr (stc_dstc_hwintclr_t *pstcHwintclr)
Set HWINTCLR Register.
boolean_t Dstc_ReadHwintBit (uint8_t u8BitPos)
Read HWINT Register Bit.
en_result_t Dstc_SetHwintclrBit (uint8_t u8BitPos)
Set HWINTCLR Register Bit.
en_result_t Dstc_ReadDqmsk (stc_dstc_dqmsk_t *pstcDqmsk)
Read DQMSK Register.
en_result_t Dstc_SetDqmskclr (stc_dstc_dqmskclr_t *pstcDqmskclr)
Set DQMSKCLR Register.
en_result_t Dstc_SetDqmskclrBit (uint8_t u8BitPos)
Set DQMSKCLR Register Bit.
void Dstc_AdcIrqHandler (uint8_t u8IrqChannel0, uint8_t u8IrqChannel1)
DSTC Peripheral Interrupt Service Routines.
void Dstc_BtIrqHandler (uint8_t u8IrqChannel0, uint8_t u8IrqChannel1)
BT.
void Dstc_CanfdIrqHandler (uint8_t u8IrqChannel0)
CAN-FD.
void Dstc_ExintIrqHandler (uint8_t u8IrqChannel)
EXT INT.
void Dstc_HsspiIrqHandler (uint8_t u8IrqChannel)
void Dstc_I2csIrqHandler (uint8_t u8IrqChannel)
I2C SLAVE.
void Dstc_I2sIrqHandler (uint8_t u8IrqChannel)
void Dstc_MfsRxIrqHandler (uint8_t u8IrqChannel)
MFS.
void Dstc_MfsTxIrqHandler (uint8_t u8IrqChannel)
void Dstc_MftFrtPeakIrqHandler (uint8_t u8IrqChannel)
MFT FRT.
void Dstc_MftFrtZeroIrqHandler (uint8_t u8IrqChannel)
void Dstc_MftOcuIrqHandler (uint8_t u8IrqChannel)
void Dstc_MftWfgIrqHandler (uint8_t u8IrqChannel)
void Dstc_MftIcuIrqHandler (uint8_t u8IrqChannel)
void Dstc_PcrcIrqHandler (uint8_t u8IrqChannel)
PCRC.
void Dstc_PpgIrqHandler (uint8_t u8IrqChannel)
PPG.
void Dstc_QprcIrqHandler (uint8_t u8IrqChannel)
QPRC.
void Dstc_WcIrqHandler (void)
Variables
static stc_dstc_intern_data_t stcDstcInternData
Detailed Description
Provided functions of DSTC:
Dstc_ReleaseStandBy()
Dstc_Init()
Dstc_ReadHwdesp()
Dstc_SetCommand()
Dstc_SwTrigger()
Dstc_SwTrqansferStartStatus()
Dstc_SetDreqenb()
Dstc_ReadDreqenb()
Dstc_SetDreqenbBit()
Dstc_ClearDreqenbBit()
Dstc_ReadHwint()
Dstc_SetHwintclr()
Dstc_SetHwintclrBit()
Dstc_ReadDqmsk()
Dstc_SetDqmskclr()
Dstc_SetDqmskclrBit()
Dstc_ReleaseStandBy() "wakes up" the DSTC from standby mode. Dsct_Init() initializes the DSTC with the user configuration (Priority Settings, Pointers to (Error) Callback Functions, etc.); Dstc_ReleaseStandBy() is called automatically via initialization. Dstc_ReadHwdesp() returns the DES area start address of a dedicated channel. Dstc_SetCommand() sets a command to the CMD register. Dstc_SwTrigger() performs a software trigger for a configured transfer. Dstc_SwTrqansferStartStatus() returns the status of a triggered Software transfer. Dstc_SetDreqenb() sets the DRQENB register set via the structure stc_dstc_dreqenb_t. Dstc_ReadDreqenb() returns the value of the DRQENB register to the given structure of the type of stc_dstc_dreqenb_t. Dstc_SetDreqenbBit() sets a bit in the 256-Bitfield of DRQENB register. Dstc_ClearDreqenbBit() clears a bit in the 256-Bitfield of DRQENB register. Dstc_ReadHwint() returns the contents of the HWINT register into a strucutre of the type of stc_dstc_hwint_t. Dstc_SetHwintclr() sets clear bits in the HWINTCLR register via the structure of the type of stc_dstc_hwintclr_t. Dstc_SetHwintclrbBit() sets clear bits in the 256-Bitfield of the HWINTCLR register. Dstc_ReadDqmsk() reads the contents of the DQMSK register into a structure of the type of stc_dstc_dqmsk_t. Dstc_SetDqmskclr() sets clear bits in the DQMSKCLR register via the structure of the type of stc_dstc_dqmskclr_t. Dstc_SetDqmskclrbBit() sets a clear bit in the 256-Bitfield of the DQMSKCLR register.
In dstc.h there are predefined DES structure types for every combination of the descriptors. Note that for DES1 two different structures are existing for mode0 and mode1. The user should use these structures within an enclosing structure, so that the descriptors are located on consecutive addresses. The address of this structure then should be used for stc_dstc_config_t::u32Destp.
Example:
struct stc_dstc_des_area
{
stc_dstc_des01236_t stcDesList0;
stc_dstc_des0123_t stcDesList1;
stc_dstc_des0123_t stcDesList2;
stc_dstc_des0123456_t stcDesList3;
. . .
};
Define Documentation
#define DSTC_IRQ_NUMBER_ADC0_PRIO 110u
DSTC interrupt numbers.
Definition at line 368 of file dstc.h.
Referenced by Dstc_AdcIrqHandler().
#define DSTC_IRQ_NUMBER_ADC0_SCAN 111u
Definition at line 369 of file dstc.h.
Referenced by Dstc_AdcIrqHandler().
#define DSTC_IRQ_NUMBER_ADC1_PRIO 112u
Definition at line 370 of file dstc.h.
Referenced by Dstc_AdcIrqHandler().
#define DSTC_IRQ_NUMBER_ADC1_SCAN 113u
Definition at line 371 of file dstc.h.
Referenced by Dstc_AdcIrqHandler().
#define DSTC_IRQ_NUMBER_BT0_IRQ0 16u
Definition at line 372 of file dstc.h.
Referenced by Dstc_BtIrqHandler().
#define DSTC_IRQ_NUMBER_BT0_IRQ1 17u
Definition at line 373 of file dstc.h.
Referenced by Dstc_BtIrqHandler().
#define DSTC_IRQ_NUMBER_BT1_IRQ0 18u
Definition at line 374 of file dstc.h.
Referenced by Dstc_BtIrqHandler().
#define DSTC_IRQ_NUMBER_BT1_IRQ1 19u
Definition at line 375 of file dstc.h.
Referenced by Dstc_BtIrqHandler().
#define DSTC_IRQ_NUMBER_BT2_IRQ0 20u
Definition at line 376 of file dstc.h.
Referenced by Dstc_BtIrqHandler().
#define DSTC_IRQ_NUMBER_BT2_IRQ1 21u
Definition at line 377 of file dstc.h.
Referenced by Dstc_BtIrqHandler().
#define DSTC_IRQ_NUMBER_BT3_IRQ0 22u
Definition at line 378 of file dstc.h.
Referenced by Dstc_BtIrqHandler().
#define DSTC_IRQ_NUMBER_BT3_IRQ1 23u
Definition at line 379 of file dstc.h.
Referenced by Dstc_BtIrqHandler().
#define DSTC_IRQ_NUMBER_BT4_IRQ0 24u
Definition at line 380 of file dstc.h.
Referenced by Dstc_BtIrqHandler().
#define DSTC_IRQ_NUMBER_BT4_IRQ1 25u
Definition at line 381 of file dstc.h.
Referenced by Dstc_BtIrqHandler().
#define DSTC_IRQ_NUMBER_BT5_IRQ0 26u
Definition at line 382 of file dstc.h.
Referenced by Dstc_BtIrqHandler().
#define DSTC_IRQ_NUMBER_BT5_IRQ1 27u
Definition at line 383 of file dstc.h.
Referenced by Dstc_BtIrqHandler().
#define DSTC_IRQ_NUMBER_BT6_IRQ0 28u
Definition at line 384 of file dstc.h.
Referenced by Dstc_BtIrqHandler().
#define DSTC_IRQ_NUMBER_BT6_IRQ1 29u
Definition at line 385 of file dstc.h.
Referenced by Dstc_BtIrqHandler().
#define DSTC_IRQ_NUMBER_BT7_IRQ0 30u
Definition at line 386 of file dstc.h.
Referenced by Dstc_BtIrqHandler().
#define DSTC_IRQ_NUMBER_BT7_IRQ1 31u
Definition at line 387 of file dstc.h.
Referenced by Dstc_BtIrqHandler().
#define DSTC_IRQ_NUMBER_CANFD 127u
Definition at line 388 of file dstc.h.
#define DSTC_IRQ_NUMBER_EXTINT0 0u
Definition at line 389 of file dstc.h.
Referenced by Dstc_ExintIrqHandler().
#define DSTC_IRQ_NUMBER_EXTINT1 1u
Definition at line 390 of file dstc.h.
Referenced by Dstc_ExintIrqHandler().
#define DSTC_IRQ_NUMBER_EXTINT10 10u
Definition at line 399 of file dstc.h.
Referenced by Dstc_ExintIrqHandler().
#define DSTC_IRQ_NUMBER_EXTINT11 11u
Definition at line 400 of file dstc.h.
Referenced by Dstc_ExintIrqHandler().
#define DSTC_IRQ_NUMBER_EXTINT12 12u
Definition at line 401 of file dstc.h.
Referenced by Dstc_ExintIrqHandler().
#define DSTC_IRQ_NUMBER_EXTINT13 13u
Definition at line 402 of file dstc.h.
Referenced by Dstc_ExintIrqHandler().
#define DSTC_IRQ_NUMBER_EXTINT14 14u
Definition at line 403 of file dstc.h.
Referenced by Dstc_ExintIrqHandler().
#define DSTC_IRQ_NUMBER_EXTINT15 15u
Definition at line 404 of file dstc.h.
Referenced by Dstc_ExintIrqHandler().
#define DSTC_IRQ_NUMBER_EXTINT2 2u
Definition at line 391 of file dstc.h.
Referenced by Dstc_ExintIrqHandler().
#define DSTC_IRQ_NUMBER_EXTINT3 3u
Definition at line 392 of file dstc.h.
Referenced by Dstc_ExintIrqHandler().
#define DSTC_IRQ_NUMBER_EXTINT4 4u
Definition at line 393 of file dstc.h.
Referenced by Dstc_ExintIrqHandler().
#define DSTC_IRQ_NUMBER_EXTINT5 5u
Definition at line 394 of file dstc.h.
Referenced by Dstc_ExintIrqHandler().
#define DSTC_IRQ_NUMBER_EXTINT6 6u
Definition at line 395 of file dstc.h.
Referenced by Dstc_ExintIrqHandler().
#define DSTC_IRQ_NUMBER_EXTINT7 7u
Definition at line 396 of file dstc.h.
Referenced by Dstc_ExintIrqHandler().
#define DSTC_IRQ_NUMBER_EXTINT8 8u
Definition at line 397 of file dstc.h.
Referenced by Dstc_ExintIrqHandler().
#define DSTC_IRQ_NUMBER_EXTINT9 9u
Definition at line 398 of file dstc.h.
Referenced by Dstc_ExintIrqHandler().
#define DSTC_IRQ_NUMBER_HSSPI0_RX 124u
Definition at line 406 of file dstc.h.
Referenced by Dstc_HsspiIrqHandler().
#define DSTC_IRQ_NUMBER_HSSPI0_TX 125u
Definition at line 405 of file dstc.h.
Referenced by Dstc_HsspiIrqHandler().
#define DSTC_IRQ_NUMBER_I2S0_RX 120u
Definition at line 408 of file dstc.h.
Referenced by Dstc_I2sIrqHandler().
#define DSTC_IRQ_NUMBER_I2S0_TX 121u
Definition at line 407 of file dstc.h.
Referenced by Dstc_I2sIrqHandler().
#define DSTC_IRQ_NUMBER_I2S1_RX 122u
Definition at line 410 of file dstc.h.
Referenced by Dstc_I2sIrqHandler().
#define DSTC_IRQ_NUMBER_I2S1_TX 123u
Definition at line 409 of file dstc.h.
Referenced by Dstc_I2sIrqHandler().
#define DSTC_IRQ_NUMBER_MFS0_RX 89u
Definition at line 411 of file dstc.h.
Referenced by Dstc_MfsRxIrqHandler().
#define DSTC_IRQ_NUMBER_MFS0_TX 90u
Definition at line 412 of file dstc.h.
Referenced by Dstc_MfsTxIrqHandler().
#define DSTC_IRQ_NUMBER_MFS1_RX 91u
Definition at line 413 of file dstc.h.
Referenced by Dstc_MfsRxIrqHandler().
#define DSTC_IRQ_NUMBER_MFS1_TX 92u
Definition at line 414 of file dstc.h.
Referenced by Dstc_MfsTxIrqHandler().
#define DSTC_IRQ_NUMBER_MFS2_RX 93u
Definition at line 415 of file dstc.h.
Referenced by Dstc_MfsRxIrqHandler().
#define DSTC_IRQ_NUMBER_MFS2_TX 94u
Definition at line 416 of file dstc.h.
Referenced by Dstc_MfsTxIrqHandler().
#define DSTC_IRQ_NUMBER_MFS3_RX 95u
Definition at line 417 of file dstc.h.
Referenced by Dstc_MfsRxIrqHandler().
#define DSTC_IRQ_NUMBER_MFS3_TX 96u
Definition at line 418 of file dstc.h.
Referenced by Dstc_MfsTxIrqHandler().
#define DSTC_IRQ_NUMBER_MFS4_RX 97u
Definition at line 419 of file dstc.h.
Referenced by Dstc_MfsRxIrqHandler().
#define DSTC_IRQ_NUMBER_MFS4_TX 98u
Definition at line 420 of file dstc.h.
Referenced by Dstc_MfsTxIrqHandler().
#define DSTC_IRQ_NUMBER_MFS5_RX 99u
Definition at line 421 of file dstc.h.
Referenced by Dstc_MfsRxIrqHandler().
#define DSTC_IRQ_NUMBER_MFS5_TX 100u
Definition at line 422 of file dstc.h.
Referenced by Dstc_MfsTxIrqHandler().
#define DSTC_IRQ_NUMBER_MFS6_RX 101u
Definition at line 423 of file dstc.h.
Referenced by Dstc_MfsRxIrqHandler().
#define DSTC_IRQ_NUMBER_MFS6_TX 102u
Definition at line 424 of file dstc.h.
Referenced by Dstc_MfsTxIrqHandler().
#define DSTC_IRQ_NUMBER_MFS7_RX 103u
Definition at line 425 of file dstc.h.
Referenced by Dstc_MfsRxIrqHandler().
#define DSTC_IRQ_NUMBER_MFS7_TX 104u
Definition at line 426 of file dstc.h.
Referenced by Dstc_MfsTxIrqHandler().
#define DSTC_IRQ_NUMBER_MFT0_FRT0_PEAK 35u
Definition at line 427 of file dstc.h.
Referenced by Dstc_MftFrtPeakIrqHandler().
#define DSTC_IRQ_NUMBER_MFT0_FRT0_ZERO 38u
Definition at line 428 of file dstc.h.
Referenced by Dstc_MftFrtZeroIrqHandler().
#define DSTC_IRQ_NUMBER_MFT0_FRT1_PEAK 36u
Definition at line 429 of file dstc.h.
Referenced by Dstc_MftFrtPeakIrqHandler().
#define DSTC_IRQ_NUMBER_MFT0_FRT1_ZERO 39u
Definition at line 430 of file dstc.h.
Referenced by Dstc_MftFrtZeroIrqHandler().
#define DSTC_IRQ_NUMBER_MFT0_FRT2_PEAK 37u
Definition at line 431 of file dstc.h.
Referenced by Dstc_MftFrtPeakIrqHandler().
#define DSTC_IRQ_NUMBER_MFT0_FRT2_ZERO 40u
Definition at line 432 of file dstc.h.
Referenced by Dstc_MftFrtZeroIrqHandler().
#define DSTC_IRQ_NUMBER_MFT0_ICU0 41u
Definition at line 433 of file dstc.h.
Referenced by Dstc_MftIcuIrqHandler().
#define DSTC_IRQ_NUMBER_MFT0_ICU1 42u
Definition at line 434 of file dstc.h.
Referenced by Dstc_MftIcuIrqHandler().
#define DSTC_IRQ_NUMBER_MFT0_ICU2 43u
Definition at line 435 of file dstc.h.
Referenced by Dstc_MftIcuIrqHandler().
#define DSTC_IRQ_NUMBER_MFT0_ICU3 44u
Definition at line 436 of file dstc.h.
Referenced by Dstc_MftIcuIrqHandler().
#define DSTC_IRQ_NUMBER_MFT0_OCU0 45u
Definition at line 437 of file dstc.h.
Referenced by Dstc_MftOcuIrqHandler().
#define DSTC_IRQ_NUMBER_MFT0_OCU1 46u
Definition at line 438 of file dstc.h.
Referenced by Dstc_MftOcuIrqHandler().
#define DSTC_IRQ_NUMBER_MFT0_OCU2 47u
Definition at line 439 of file dstc.h.
Referenced by Dstc_MftOcuIrqHandler().
#define DSTC_IRQ_NUMBER_MFT0_OCU3 48u
Definition at line 440 of file dstc.h.
Referenced by Dstc_MftOcuIrqHandler().
#define DSTC_IRQ_NUMBER_MFT0_OCU4 49u
Definition at line 441 of file dstc.h.
Referenced by Dstc_MftOcuIrqHandler().
#define DSTC_IRQ_NUMBER_MFT0_OCU5 50u
Definition at line 442 of file dstc.h.
Referenced by Dstc_MftOcuIrqHandler().
#define DSTC_IRQ_NUMBER_MFT0_WFG10 32u
Definition at line 443 of file dstc.h.
Referenced by Dstc_MftWfgIrqHandler().
#define DSTC_IRQ_NUMBER_MFT0_WFG32 33u
Definition at line 444 of file dstc.h.
Referenced by Dstc_MftWfgIrqHandler().
#define DSTC_IRQ_NUMBER_MFT0_WFG54 34u
Definition at line 445 of file dstc.h.
Referenced by Dstc_MftWfgIrqHandler().
#define DSTC_IRQ_NUMBER_PCRC 126u
Definition at line 446 of file dstc.h.
#define DSTC_IRQ_NUMBER_PPG0 70u
Definition at line 447 of file dstc.h.
Referenced by Dstc_PpgIrqHandler().
#define DSTC_IRQ_NUMBER_PPG2 71u
Definition at line 448 of file dstc.h.
Referenced by Dstc_PpgIrqHandler().
#define DSTC_IRQ_NUMBER_PPG4 72u
Definition at line 449 of file dstc.h.
Referenced by Dstc_PpgIrqHandler().
#define DSTC_IRQ_NUMBER_QPRC0_COUNT_INVERSION 79u
Definition at line 450 of file dstc.h.
Referenced by Dstc_QprcIrqHandler().
#define DSTC_IRQ_NUMBER_QPRC0_OUT_OF_RANGE 80u
Definition at line 451 of file dstc.h.
Referenced by Dstc_QprcIrqHandler().
#define DSTC_IRQ_NUMBER_QPRC0_PC_MATCH 76u
Definition at line 452 of file dstc.h.
Referenced by Dstc_QprcIrqHandler().
#define DSTC_IRQ_NUMBER_QPRC0_PC_MATCH_RC_MATCH 81u
Definition at line 453 of file dstc.h.
Referenced by Dstc_QprcIrqHandler().
#define DSTC_IRQ_NUMBER_QPRC0_PC_RC_MATCH 77u
Definition at line 454 of file dstc.h.
Referenced by Dstc_QprcIrqHandler().
#define DSTC_IRQ_NUMBER_QPRC0_UFL_OFL_Z 78u
Definition at line 455 of file dstc.h.
Referenced by Dstc_QprcIrqHandler().
#define DSTC_IRQ_NUMBER_USB0_EP1 105u
Definition at line 456 of file dstc.h.
#define DSTC_IRQ_NUMBER_USB0_EP2 106u
Definition at line 457 of file dstc.h.
#define DSTC_IRQ_NUMBER_USB0_EP3 107u
Definition at line 458 of file dstc.h.
#define DSTC_IRQ_NUMBER_USB0_EP4 108u
Definition at line 459 of file dstc.h.
#define DSTC_IRQ_NUMBER_USB0_EP5 109u
Definition at line 460 of file dstc.h.
#define DSTC_IRQ_NUMBER_WC 88u
Definition at line 461 of file dstc.h.
Referenced by Dstc_WcIrqHandler().
#define DSTC_PCHK_CALC (x)
Value:
((((x) & 0x0F000000ul) >> 24u) ^ \
                           (((x) & 0x00F00000ul) >> 20u) ^ \
                           (((x) & 0x000F0000ul) >> 16u) ^ \
                           (((x) & 0x0000F000ul) >> 12u) ^ \
                           (((x) & 0x00000F00ul) >>  8u) ^ \
                           (((x) & 0x000000F0ul) >>  4u))
Parity checksum for DES0 PCHKS bits.
Definition at line 148 of file dstc.h.
#define DSTC_TRANSITION_TIMEOUT 100000u
Timeout counter for DSTC mode transition.
Definition at line 145 of file dstc.h.
Referenced by Dstc_ReleaseStandBy().
Typedef Documentation
typedef enum en_dstc_cmd en_dstc_cmd_t
DSTC Commands.
typedef enum en_dstc_est_error en_dstc_est_error_t
MONERS EST Error Code.
typedef enum en_dstc_swpr en_dstc_swpr_t
Software Transfer Priority.
typedef void(* func_ptr_dstc_args_t)(en_dstc_est_error_t enEstError, uint16_t u16ErrorChannel, uint16_t u16ErrorDesPointer, boolean_t bSoftwareError, boolean_t bDoubleError, boolean_t bErrorStop)
Error Status Callback.
Definition at line 639 of file dstc.h.
typedef struct stc_dstc_config stc_dstc_config_t
DSTC configuration.
typedef struct stc_dstc_des0123456 stc_dstc_des0123456_t
Definition of Descriptor Group DES0 - DES6.
typedef struct stc_dstc_des012345 stc_dstc_des012345_t
Definition of Descriptor Group DES0 - DES5.
typedef struct stc_dstc_des012346 stc_dstc_des012346_t
Definition of Descriptor Group DES0 - DES4, DES6.
typedef struct stc_dstc_des01234 stc_dstc_des01234_t
Definition of Descriptor Group DES0 - DES4.
typedef struct stc_dstc_des012356 stc_dstc_des012356_t
Definition of Descriptor Group DES0 - DES3, DES5, DES6.
typedef struct stc_dstc_des01235 stc_dstc_des01235_t
Definition of Descriptor Group DES0 - DES3, DES5.
typedef struct stc_dstc_des01236 stc_dstc_des01236_t
Definition of Descriptor Group DES0 - DES3, DES6.
typedef struct stc_dstc_des0123 stc_dstc_des0123_t
Definition of Descriptor Group DES0 - DES3.
typedef struct stc_dstc_des0 stc_dstc_des0_t
Definition of Descriptor 0 (DES0 - Transfer Basic Setting)
typedef struct stc_dstc_des1_mode0 stc_dstc_des1_mode0_t
Definition of Descriptor 1 (DES1 - Number of Transfers) in Mode 0.
typedef struct stc_dstc_des1_mode1 stc_dstc_des1_mode1_t
Definition of Descriptor 1 (DES1 - Number of Transfers) in Mode 1.
typedef struct stc_dstc_dqmsk stc_dstc_dqmsk_t
DQMSK structure.
typedef struct stc_dstc_dqmskclr stc_dstc_dqmskclr_t
DQMSKCLR structure.
typedef struct stc_dstc_dreqenb stc_dstc_dreqenb_t
DREQENB structure.
typedef struct stc_dstc_hwint stc_dstc_hwint_t
HWINT structure.
typedef struct stc_dstc_hwintclr stc_dstc_hwintclr_t
HWINTCLR structure.
typedef struct stc_dstc_intern_data stc_dstc_intern_data_t
DSTC Intern Data.
Enumeration Type Documentation
enum en_dstc_cmd
DSTC Commands.
Enumerator:
CmdStandyRelease
Instructs DSTC to return from standby state into normal state.
CmdStandyTransition
Instructs DSTC to standby state.
CmdSwclr
Clears SWTR:SWST to '0'; negates SWINT interrupt signal.
CmdErclr
Clears MONERS:EST, MONERS:DER, and MONERS:ESTOP.
CmdRbclr
Clears DESP to which DSTP refers in previous transfer; Sets next DES; Clears HWDESP[n].
CmdMkclr
Clears all DQMSK[n].
Definition at line 594 of file dstc.h.
enum en_dstc_est_error
MONERS EST Error Code.
Enumerator:
NoError
No error occurred.
SourceAccessError
Source access error.
DestinationAccessError
Destination access error.
ForcedTransferStop
Transfer has been stopped compulsorily.
DesAccessError
DES access error.
DesOpenError
DES open error.
UnknownError
Undefined state, should never happen.
Definition at line 624 of file dstc.h.
enum en_dstc_swpr
Software Transfer Priority.
Enumerator:
PriorityHighest
Highest Priority.
Priority1_2
Priority 1/2 Transfer Right.
Priority1_3
Priority 1/2 Transfer Right.
Priority1_7
Priority 1/2 Transfer Right.
Priority1_15
Priority 1/2 Transfer Right.
Priority1_31
Priority 1/2 Transfer Right.
Priority1_63
Priority 1/2 Transfer Right.
PriorityLowest
Lowest Priority.
Definition at line 608 of file dstc.h.
Function Documentation
void Dstc_AdcIrqHandler (uint8_t u8IrqChannel0, uint8_t u8IrqChannel1)
DSTC Peripheral Interrupt Service Routines.
ADC
Definition at line 1316 of file dstc.c.
References DSTC_IRQ_NUMBER_ADC0_PRIO, DSTC_IRQ_NUMBER_ADC0_SCAN, DSTC_IRQ_NUMBER_ADC1_PRIO, DSTC_IRQ_NUMBER_ADC1_SCAN, Dstc_ReadHwintBit(), Dstc_SetHwintclrBit(), stc_dstc_intern_data::pfnDstcAdc0PrioCallback, stc_dstc_intern_data::pfnDstcAdc0ScanCallback, stc_dstc_intern_data::pfnDstcAdc1PrioCallback, stc_dstc_intern_data::pfnDstcAdc1ScanCallback, stc_dstc_intern_data::pfnDstcAdc2PrioCallback, and stc_dstc_intern_data::pfnDstcAdc2ScanCallback.
void Dstc_BtIrqHandler (uint8_t u8IrqChannel0, uint8_t u8IrqChannel1)
BT.
Definition at line 1408 of file dstc.c.
References DSTC_IRQ_NUMBER_BT0_IRQ0, DSTC_IRQ_NUMBER_BT0_IRQ1, DSTC_IRQ_NUMBER_BT1_IRQ0, DSTC_IRQ_NUMBER_BT1_IRQ1, DSTC_IRQ_NUMBER_BT2_IRQ0, DSTC_IRQ_NUMBER_BT2_IRQ1, DSTC_IRQ_NUMBER_BT3_IRQ0, DSTC_IRQ_NUMBER_BT3_IRQ1, DSTC_IRQ_NUMBER_BT4_IRQ0, DSTC_IRQ_NUMBER_BT4_IRQ1, DSTC_IRQ_NUMBER_BT5_IRQ0, DSTC_IRQ_NUMBER_BT5_IRQ1, DSTC_IRQ_NUMBER_BT6_IRQ0, DSTC_IRQ_NUMBER_BT6_IRQ1, DSTC_IRQ_NUMBER_BT7_IRQ0, DSTC_IRQ_NUMBER_BT7_IRQ1, Dstc_ReadHwintBit(), Dstc_SetHwintclrBit(), stc_dstc_intern_data::pfnDstcBt0Irq0Callback, stc_dstc_intern_data::pfnDstcBt0Irq1Callback, stc_dstc_intern_data::pfnDstcBt10Irq0Callback, stc_dstc_intern_data::pfnDstcBt11Irq0Callback, stc_dstc_intern_data::pfnDstcBt11Irq1Callback, stc_dstc_intern_data::pfnDstcBt12Irq0Callback, stc_dstc_intern_data::pfnDstcBt12Irq1Callback, stc_dstc_intern_data::pfnDstcBt13Irq0Callback, stc_dstc_intern_data::pfnDstcBt13Irq1Callback, stc_dstc_intern_data::pfnDstcBt14Irq0Callback, stc_dstc_intern_data::pfnDstcBt14Irq1Callback, stc_dstc_intern_data::pfnDstcBt15Irq0Callback, stc_dstc_intern_data::pfnDstcBt15Irq1Callback, stc_dstc_intern_data::pfnDstcBt1Irq0Callback, stc_dstc_intern_data::pfnDstcBt1Irq1Callback, stc_dstc_intern_data::pfnDstcBt2Irq0Callback, stc_dstc_intern_data::pfnDstcBt2Irq1Callback, stc_dstc_intern_data::pfnDstcBt3Irq0Callback, stc_dstc_intern_data::pfnDstcBt3Irq1Callback, stc_dstc_intern_data::pfnDstcBt4Irq0Callback, stc_dstc_intern_data::pfnDstcBt4Irq1Callback, stc_dstc_intern_data::pfnDstcBt5Irq0Callback, stc_dstc_intern_data::pfnDstcBt5Irq1Callback, stc_dstc_intern_data::pfnDstcBt6Irq0Callback, stc_dstc_intern_data::pfnDstcBt6Irq1Callback, stc_dstc_intern_data::pfnDstcBt7Irq0Callback, stc_dstc_intern_data::pfnDstcBt7Irq1Callback, stc_dstc_intern_data::pfnDstcBt8Irq0Callback, stc_dstc_intern_data::pfnDstcBt8Irq1Callback, stc_dstc_intern_data::pfnDstcBt9Irq0Callback, and stc_dstc_intern_data::pfnDstcBt9Irq1Callback.
void Dstc_CanfdIrqHandler (uint8_t u8IrqChannel0)
CAN-FD.
Definition at line 1640 of file dstc.c.
References Dstc_ReadHwintBit(), and Dstc_SetHwintclrBit().
en_result_t Dstc_ClearDreqenbBit (uint8_t u8BitPos)
Clear DREQENB Register Bit.
Parameters:
[in] u8BitPos Bit Position (IRQ Number)
Return values:
Ok DREQENB Bit set successfully
Definition at line 1148 of file dstc.c.
en_result_t Dstc_DeInit (boolean_t bTouchNvic)
De-Initializes the the DSTC.
Return values:
Ok DSTC de-initialized and in standby mode
Definition at line 920 of file dstc.c.
References CmdStandyTransition, Dstc_SetCommand(), PDL_DEFAULT_INTERRUPT_LEVEL, stc_dstc_intern_data::pfnErrorCallback, and stc_dstc_intern_data::pfnNotifySwCallback.
void Dstc_ExintIrqHandler (uint8_t u8IrqChannel)
EXT INT.
Definition at line 1675 of file dstc.c.
References DSTC_IRQ_NUMBER_EXTINT0, DSTC_IRQ_NUMBER_EXTINT1, DSTC_IRQ_NUMBER_EXTINT10, DSTC_IRQ_NUMBER_EXTINT11, DSTC_IRQ_NUMBER_EXTINT12, DSTC_IRQ_NUMBER_EXTINT13, DSTC_IRQ_NUMBER_EXTINT14, DSTC_IRQ_NUMBER_EXTINT15, DSTC_IRQ_NUMBER_EXTINT2, DSTC_IRQ_NUMBER_EXTINT3, DSTC_IRQ_NUMBER_EXTINT4, DSTC_IRQ_NUMBER_EXTINT5, DSTC_IRQ_NUMBER_EXTINT6, DSTC_IRQ_NUMBER_EXTINT7, DSTC_IRQ_NUMBER_EXTINT8, DSTC_IRQ_NUMBER_EXTINT9, Dstc_ReadHwintBit(), Dstc_SetHwintclrBit(), stc_dstc_intern_data::pfnDstcExint0Callback, stc_dstc_intern_data::pfnDstcExint10Callback, stc_dstc_intern_data::pfnDstcExint11Callback, stc_dstc_intern_data::pfnDstcExint12Callback, stc_dstc_intern_data::pfnDstcExint13Callback, stc_dstc_intern_data::pfnDstcExint14Callback, stc_dstc_intern_data::pfnDstcExint15Callback, stc_dstc_intern_data::pfnDstcExint16Callback, stc_dstc_intern_data::pfnDstcExint17Callback, stc_dstc_intern_data::pfnDstcExint18Callback, stc_dstc_intern_data::pfnDstcExint19Callback, stc_dstc_intern_data::pfnDstcExint1Callback, stc_dstc_intern_data::pfnDstcExint20Callback, stc_dstc_intern_data::pfnDstcExint21Callback, stc_dstc_intern_data::pfnDstcExint22Callback, stc_dstc_intern_data::pfnDstcExint23Callback, stc_dstc_intern_data::pfnDstcExint24Callback, stc_dstc_intern_data::pfnDstcExint25Callback, stc_dstc_intern_data::pfnDstcExint26Callback, stc_dstc_intern_data::pfnDstcExint27Callback, stc_dstc_intern_data::pfnDstcExint28Callback, stc_dstc_intern_data::pfnDstcExint29Callback, stc_dstc_intern_data::pfnDstcExint2Callback, stc_dstc_intern_data::pfnDstcExint30Callback, stc_dstc_intern_data::pfnDstcExint31Callback, stc_dstc_intern_data::pfnDstcExint3Callback, stc_dstc_intern_data::pfnDstcExint4Callback, stc_dstc_intern_data::pfnDstcExint5Callback, stc_dstc_intern_data::pfnDstcExint6Callback, stc_dstc_intern_data::pfnDstcExint7Callback, stc_dstc_intern_data::pfnDstcExint8Callback, and stc_dstc_intern_data::pfnDstcExint9Callback.
void Dstc_HsspiIrqHandler (uint8_t u8IrqChannel)
Definition at line 1858 of file dstc.c.
References DSTC_IRQ_NUMBER_HSSPI0_RX, DSTC_IRQ_NUMBER_HSSPI0_TX, Dstc_ReadHwintBit(), Dstc_SetHwintclrBit(), stc_dstc_intern_data::pfnDstcHsspi0RxCallback, and stc_dstc_intern_data::pfnDstcHsspi0TxCallback.
void Dstc_I2csIrqHandler (uint8_t u8IrqChannel)
I2C SLAVE.
Definition at line 1893 of file dstc.c.
References Dstc_ReadHwintBit(), Dstc_SetHwintclrBit(), stc_dstc_intern_data::pfnDstcI2cs0RxCallback, and stc_dstc_intern_data::pfnDstcI2cs0TxCallback.
void Dstc_I2sIrqHandler (uint8_t u8IrqChannel)
Definition at line 1925 of file dstc.c.
References DSTC_IRQ_NUMBER_I2S0_RX, DSTC_IRQ_NUMBER_I2S0_TX, DSTC_IRQ_NUMBER_I2S1_RX, DSTC_IRQ_NUMBER_I2S1_TX, Dstc_ReadHwintBit(), Dstc_SetHwintclrBit(), stc_dstc_intern_data::pfnDstcI2s0RxCallback, stc_dstc_intern_data::pfnDstcI2s0TxCallback, stc_dstc_intern_data::pfnDstcI2s1RxCallback, and stc_dstc_intern_data::pfnDstcI2s1TxCallback.
en_result_t Dstc_Init (stc_dstc_config_t * pstcConfig)
Initializes the DSTC according the Configuration.
Parameters:
[in] pstcConfig Pointer to DSTC Configuration
Return values:
Ok DSTC Initialized
ErrorNotReady DSTC standby initialization failed
ErrorInvalidParameter pstcConfig == NULL or other configuration wrong
ErrorAddressAlignment DES Base Address not aligned to 32 Bit
Definition at line 215 of file dstc.c.
References stc_dstc_config::bErInterruptEnable, stc_dstc_config::bErrorStopEnable, stc_dstc_config::bReadSkipBufferDisable, stc_dstc_config::bSwInterruptEnable, stc_dstc_config::bTouchNvic, Dstc_ReleaseStandBy(), stc_dstc_config::enSwTransferPriority, PDL_IRQ_LEVEL_DSTC, stc_dstc_config::pfnDstcAdc0PrioCallback, stc_dstc_intern_data::pfnDstcAdc0PrioCallback, stc_dstc_config::pfnDstcAdc0ScanCallback, stc_dstc_intern_data::pfnDstcAdc0ScanCallback, stc_dstc_config::pfnDstcAdc1PrioCallback, stc_dstc_intern_data::pfnDstcAdc1PrioCallback, stc_dstc_config::pfnDstcAdc1ScanCallback, stc_dstc_intern_data::pfnDstcAdc1ScanCallback, stc_dstc_config::pfnDstcAdc2PrioCallback, stc_dstc_intern_data::pfnDstcAdc2PrioCallback, stc_dstc_config::pfnDstcAdc2ScanCallback, stc_dstc_intern_data::pfnDstcAdc2ScanCallback, stc_dstc_config::pfnDstcBt0Irq0Callback, stc_dstc_intern_data::pfnDstcBt0Irq0Callback, stc_dstc_config::pfnDstcBt0Irq1Callback, stc_dstc_intern_data::pfnDstcBt0Irq1Callback, stc_dstc_config::pfnDstcBt10Irq0Callback, stc_dstc_intern_data::pfnDstcBt10Irq0Callback, stc_dstc_config::pfnDstcBt10Irq1Callback, stc_dstc_intern_data::pfnDstcBt10Irq1Callback, stc_dstc_config::pfnDstcBt11Irq0Callback, stc_dstc_intern_data::pfnDstcBt11Irq0Callback, stc_dstc_config::pfnDstcBt11Irq1Callback, stc_dstc_intern_data::pfnDstcBt11Irq1Callback, stc_dstc_config::pfnDstcBt12Irq0Callback, stc_dstc_intern_data::pfnDstcBt12Irq0Callback, stc_dstc_config::pfnDstcBt12Irq1Callback, stc_dstc_intern_data::pfnDstcBt12Irq1Callback, stc_dstc_config::pfnDstcBt13Irq0Callback, stc_dstc_intern_data::pfnDstcBt13Irq0Callback, stc_dstc_config::pfnDstcBt13Irq1Callback, stc_dstc_intern_data::pfnDstcBt13Irq1Callback, stc_dstc_config::pfnDstcBt14Irq0Callback, stc_dstc_intern_data::pfnDstcBt14Irq0Callback, stc_dstc_config::pfnDstcBt14Irq1Callback, stc_dstc_intern_data::pfnDstcBt14Irq1Callback, stc_dstc_config::pfnDstcBt15Irq0Callback, stc_dstc_intern_data::pfnDstcBt15Irq0Callback, stc_dstc_intern_data::pfnDstcBt15Irq1Callback, stc_dstc_config::pfnDstcBt1Irq0Callback, stc_dstc_intern_data::pfnDstcBt1Irq0Callback, stc_dstc_config::pfnDstcBt1Irq1Callback, stc_dstc_intern_data::pfnDstcBt1Irq1Callback, stc_dstc_config::pfnDstcBt2Irq0Callback, stc_dstc_intern_data::pfnDstcBt2Irq0Callback, stc_dstc_config::pfnDstcBt2Irq1Callback, stc_dstc_intern_data::pfnDstcBt2Irq1Callback, stc_dstc_config::pfnDstcBt3Irq0Callback, stc_dstc_intern_data::pfnDstcBt3Irq0Callback, stc_dstc_config::pfnDstcBt3Irq1Callback, stc_dstc_intern_data::pfnDstcBt3Irq1Callback, stc_dstc_config::pfnDstcBt4Irq0Callback, stc_dstc_intern_data::pfnDstcBt4Irq0Callback, stc_dstc_config::pfnDstcBt4Irq1Callback, stc_dstc_intern_data::pfnDstcBt4Irq1Callback, stc_dstc_config::pfnDstcBt5Irq0Callback, stc_dstc_intern_data::pfnDstcBt5Irq0Callback, stc_dstc_config::pfnDstcBt5Irq1Callback, stc_dstc_intern_data::pfnDstcBt5Irq1Callback, stc_dstc_config::pfnDstcBt6Irq0Callback, stc_dstc_intern_data::pfnDstcBt6Irq0Callback, stc_dstc_config::pfnDstcBt6Irq1Callback, stc_dstc_intern_data::pfnDstcBt6Irq1Callback, stc_dstc_config::pfnDstcBt7Irq0Callback, stc_dstc_intern_data::pfnDstcBt7Irq0Callback, stc_dstc_config::pfnDstcBt7Irq1Callback, stc_dstc_intern_data::pfnDstcBt7Irq1Callback, stc_dstc_config::pfnDstcBt8Irq0Callback, stc_dstc_intern_data::pfnDstcBt8Irq0Callback, stc_dstc_config::pfnDstcBt8Irq1Callback, stc_dstc_intern_data::pfnDstcBt8Irq1Callback, stc_dstc_config::pfnDstcBt9Irq0Callback, stc_dstc_intern_data::pfnDstcBt9Irq0Callback, stc_dstc_config::pfnDstcBt9Irq1Callback, stc_dstc_intern_data::pfnDstcBt9Irq1Callback, stc_dstc_config::pfnDstcMfs0RxCallback, stc_dstc_config::pfnDstcMfs0TxCallback, stc_dstc_intern_data::pfnDstcMfs0TxCallback, stc_dstc_config::pfnDstcMfs10RxCallback, stc_dstc_intern_data::pfnDstcMfs10RxCallback, stc_dstc_config::pfnDstcMfs10TxCallback, stc_dstc_intern_data::pfnDstcMfs10TxCallback, stc_dstc_config::pfnDstcMfs11RxCallback, stc_dstc_intern_data::pfnDstcMfs11RxCallback, stc_dstc_config::pfnDstcMfs11TxCallback, stc_dstc_intern_data::pfnDstcMfs11TxCallback, stc_dstc_config::pfnDstcMfs12RxCallback, stc_dstc_intern_data::pfnDstcMfs12RxCallback, stc_dstc_config::pfnDstcMfs12TxCallback, stc_dstc_intern_data::pfnDstcMfs12TxCallback, stc_dstc_config::pfnDstcMfs13RxCallback, stc_dstc_intern_data::pfnDstcMfs13RxCallback, stc_dstc_config::pfnDstcMfs13TxCallback, stc_dstc_intern_data::pfnDstcMfs13TxCallback, stc_dstc_config::pfnDstcMfs14RxCallback, stc_dstc_intern_data::pfnDstcMfs14RxCallback, stc_dstc_config::pfnDstcMfs14TxCallback, stc_dstc_intern_data::pfnDstcMfs14TxCallback, stc_dstc_config::pfnDstcMfs15RxCallback, stc_dstc_intern_data::pfnDstcMfs15RxCallback, stc_dstc_config::pfnDstcMfs15TxCallback, stc_dstc_intern_data::pfnDstcMfs15TxCallback, stc_dstc_config::pfnDstcMfs1RxCallback, stc_dstc_intern_data::pfnDstcMfs1RxCallback, stc_dstc_config::pfnDstcMfs1TxCallback, stc_dstc_intern_data::pfnDstcMfs1TxCallback, stc_dstc_config::pfnDstcMfs2RxCallback, stc_dstc_intern_data::pfnDstcMfs2RxCallback, stc_dstc_config::pfnDstcMfs2TxCallback, stc_dstc_intern_data::pfnDstcMfs2TxCallback, stc_dstc_config::pfnDstcMfs3RxCallback, stc_dstc_intern_data::pfnDstcMfs3RxCallback, stc_dstc_config::pfnDstcMfs3TxCallback, stc_dstc_intern_data::pfnDstcMfs3TxCallback, stc_dstc_config::pfnDstcMfs4RxCallback, stc_dstc_intern_data::pfnDstcMfs4RxCallback, stc_dstc_config::pfnDstcMfs4TxCallback, stc_dstc_intern_data::pfnDstcMfs4TxCallback, stc_dstc_config::pfnDstcMfs5RxCallback, stc_dstc_intern_data::pfnDstcMfs5RxCallback, stc_dstc_config::pfnDstcMfs5TxCallback, stc_dstc_intern_data::pfnDstcMfs5TxCallback, stc_dstc_config::pfnDstcMfs6RxCallback, stc_dstc_intern_data::pfnDstcMfs6RxCallback, stc_dstc_config::pfnDstcMfs6TxCallback, stc_dstc_intern_data::pfnDstcMfs6TxCallback, stc_dstc_config::pfnDstcMfs7RxCallback, stc_dstc_intern_data::pfnDstcMfs7RxCallback, stc_dstc_config::pfnDstcMfs7TxCallback, stc_dstc_intern_data::pfnDstcMfs7TxCallback, stc_dstc_config::pfnDstcMfs8RxCallback, stc_dstc_intern_data::pfnDstcMfs8RxCallback, stc_dstc_config::pfnDstcMfs8TxCallback, stc_dstc_intern_data::pfnDstcMfs8TxCallback, stc_dstc_config::pfnDstcMfs9RxCallback, stc_dstc_intern_data::pfnDstcMfs9RxCallback, stc_dstc_config::pfnDstcMfs9TxCallback, stc_dstc_intern_data::pfnDstcMfs9TxCallback, stc_dstc_config::pfnDstcMft0Frt0PeakCallback, stc_dstc_intern_data::pfnDstcMft0Frt0PeakCallback, stc_dstc_config::pfnDstcMft0Frt0ZeroCallback, stc_dstc_intern_data::pfnDstcMft0Frt0ZeroCallback, stc_dstc_config::pfnDstcMft0Frt1PeakCallback, stc_dstc_intern_data::pfnDstcMft0Frt1PeakCallback, stc_dstc_config::pfnDstcMft0Frt1ZeroCallback, stc_dstc_intern_data::pfnDstcMft0Frt1ZeroCallback, stc_dstc_config::pfnDstcMft0Frt2PeakCallback, stc_dstc_intern_data::pfnDstcMft0Frt2PeakCallback, stc_dstc_config::pfnDstcMft0Frt2ZeroCallback, stc_dstc_intern_data::pfnDstcMft0Frt2ZeroCallback, stc_dstc_config::pfnDstcMft0Icu0Callback, stc_dstc_intern_data::pfnDstcMft0Icu0Callback, stc_dstc_config::pfnDstcMft0Icu1Callback, stc_dstc_intern_data::pfnDstcMft0Icu1Callback, stc_dstc_config::pfnDstcMft0Icu2Callback, stc_dstc_intern_data::pfnDstcMft0Icu2Callback, stc_dstc_config::pfnDstcMft0Icu3Callback, stc_dstc_intern_data::pfnDstcMft0Icu3Callback, stc_dstc_config::pfnDstcMft0Ocu0Callback, stc_dstc_intern_data::pfnDstcMft0Ocu0Callback, stc_dstc_config::pfnDstcMft0Ocu1Callback, stc_dstc_intern_data::pfnDstcMft0Ocu1Callback, stc_dstc_config::pfnDstcMft0Ocu2Callback, stc_dstc_intern_data::pfnDstcMft0Ocu2Callback, stc_dstc_config::pfnDstcMft0Ocu3Callback, stc_dstc_intern_data::pfnDstcMft0Ocu3Callback, stc_dstc_config::pfnDstcMft0Ocu4Callback, stc_dstc_intern_data::pfnDstcMft0Ocu4Callback, stc_dstc_config::pfnDstcMft0Ocu5Callback, stc_dstc_intern_data::pfnDstcMft0Ocu5Callback, stc_dstc_config::pfnDstcMft0Wfg10Callback, stc_dstc_intern_data::pfnDstcMft0Wfg10Callback, stc_dstc_config::pfnDstcMft0Wfg32Callback, stc_dstc_intern_data::pfnDstcMft0Wfg32Callback, stc_dstc_config::pfnDstcMft0Wfg54Callback, stc_dstc_intern_data::pfnDstcMft0Wfg54Callback, stc_dstc_config::pfnDstcMft1Frt0PeakCallback, stc_dstc_intern_data::pfnDstcMft1Frt0PeakCallback, stc_dstc_config::pfnDstcMft1Frt0ZeroCallback, stc_dstc_intern_data::pfnDstcMft1Frt0ZeroCallback, stc_dstc_config::pfnDstcMft1Frt1PeakCallback, stc_dstc_intern_data::pfnDstcMft1Frt1PeakCallback, stc_dstc_config::pfnDstcMft1Frt1ZeroCallback, stc_dstc_intern_data::pfnDstcMft1Frt1ZeroCallback, stc_dstc_config::pfnDstcMft1Frt2PeakCallback, stc_dstc_intern_data::pfnDstcMft1Frt2PeakCallback, stc_dstc_config::pfnDstcMft1Frt2ZeroCallback, stc_dstc_intern_data::pfnDstcMft1Frt2ZeroCallback, stc_dstc_config::pfnDstcMft1Icu0Callback, stc_dstc_intern_data::pfnDstcMft1Icu0Callback, stc_dstc_config::pfnDstcMft1Icu1Callback, stc_dstc_intern_data::pfnDstcMft1Icu1Callback, stc_dstc_config::pfnDstcMft1Icu2Callback, stc_dstc_intern_data::pfnDstcMft1Icu2Callback, stc_dstc_config::pfnDstcMft1Icu3Callback, stc_dstc_intern_data::pfnDstcMft1Icu3Callback, stc_dstc_config::pfnDstcMft1Ocu0Callback, stc_dstc_intern_data::pfnDstcMft1Ocu0Callback, stc_dstc_config::pfnDstcMft1Ocu1Callback, stc_dstc_intern_data::pfnDstcMft1Ocu1Callback, stc_dstc_config::pfnDstcMft1Ocu2Callback, stc_dstc_intern_data::pfnDstcMft1Ocu2Callback, stc_dstc_config::pfnDstcMft1Ocu3Callback, stc_dstc_intern_data::pfnDstcMft1Ocu3Callback, stc_dstc_config::pfnDstcMft1Ocu4Callback, stc_dstc_intern_data::pfnDstcMft1Ocu4Callback, stc_dstc_config::pfnDstcMft1Ocu5Callback, stc_dstc_intern_data::pfnDstcMft1Ocu5Callback, stc_dstc_config::pfnDstcMft1Wfg10Callback, stc_dstc_intern_data::pfnDstcMft1Wfg10Callback, stc_dstc_config::pfnDstcMft1Wfg32Callback, stc_dstc_intern_data::pfnDstcMft1Wfg32Callback, stc_dstc_config::pfnDstcMft1Wfg54Callback, stc_dstc_intern_data::pfnDstcMft1Wfg54Callback, stc_dstc_config::pfnDstcMft2Frt0PeakCallback, stc_dstc_intern_data::pfnDstcMft2Frt0PeakCallback, stc_dstc_config::pfnDstcMft2Frt0ZeroCallback, stc_dstc_intern_data::pfnDstcMft2Frt0ZeroCallback, stc_dstc_config::pfnDstcMft2Frt1PeakCallback, stc_dstc_intern_data::pfnDstcMft2Frt1PeakCallback, stc_dstc_config::pfnDstcMft2Frt1ZeroCallback, stc_dstc_intern_data::pfnDstcMft2Frt1ZeroCallback, stc_dstc_config::pfnDstcMft2Frt2PeakCallback, stc_dstc_intern_data::pfnDstcMft2Frt2PeakCallback, stc_dstc_config::pfnDstcMft2Frt2ZeroCallback, stc_dstc_intern_data::pfnDstcMft2Frt2ZeroCallback, stc_dstc_config::pfnDstcMft2Icu0Callback, stc_dstc_intern_data::pfnDstcMft2Icu0Callback, stc_dstc_config::pfnDstcMft2Icu1Callback, stc_dstc_intern_data::pfnDstcMft2Icu1Callback, stc_dstc_config::pfnDstcMft2Icu2Callback, stc_dstc_intern_data::pfnDstcMft2Icu2Callback, stc_dstc_config::pfnDstcMft2Icu3Callback, stc_dstc_intern_data::pfnDstcMft2Icu3Callback, stc_dstc_config::pfnDstcMft2Ocu0Callback, stc_dstc_intern_data::pfnDstcMft2Ocu0Callback, stc_dstc_config::pfnDstcMft2Ocu1Callback, stc_dstc_intern_data::pfnDstcMft2Ocu1Callback, stc_dstc_config::pfnDstcMft2Ocu2Callback, stc_dstc_intern_data::pfnDstcMft2Ocu2Callback, stc_dstc_config::pfnDstcMft2Ocu3Callback, stc_dstc_intern_data::pfnDstcMft2Ocu3Callback, stc_dstc_config::pfnDstcMft2Ocu4Callback, stc_dstc_intern_data::pfnDstcMft2Ocu4Callback, stc_dstc_config::pfnDstcMft2Ocu5Callback, stc_dstc_intern_data::pfnDstcMft2Ocu5Callback, stc_dstc_config::pfnDstcMft2Wfg10Callback, stc_dstc_intern_data::pfnDstcMft2Wfg10Callback, stc_dstc_config::pfnDstcMft2Wfg32Callback, stc_dstc_intern_data::pfnDstcMft2Wfg32Callback, stc_dstc_config::pfnDstcMft2Wfg54Callback, stc_dstc_intern_data::pfnDstcMft2Wfg54Callback, stc_dstc_config::pfnDstcPpg0Callback, stc_dstc_intern_data::pfnDstcPpg0Callback, stc_dstc_config::pfnDstcPpg10Callback, stc_dstc_intern_data::pfnDstcPpg10Callback, stc_dstc_config::pfnDstcPpg12Callback, stc_dstc_intern_data::pfnDstcPpg12Callback, stc_dstc_config::pfnDstcPpg16Callback, stc_dstc_intern_data::pfnDstcPpg16Callback, stc_dstc_config::pfnDstcPpg18Callback, stc_dstc_intern_data::pfnDstcPpg18Callback, stc_dstc_config::pfnDstcPpg20Callback, stc_dstc_intern_data::pfnDstcPpg20Callback, stc_dstc_config::pfnDstcPpg2Callback, stc_dstc_intern_data::pfnDstcPpg2Callback, stc_dstc_config::pfnDstcPpg4Callback, stc_dstc_intern_data::pfnDstcPpg4Callback, stc_dstc_config::pfnDstcPpg8Callback, stc_dstc_intern_data::pfnDstcPpg8Callback, stc_dstc_config::pfnDstcQprc0CountInversionCallback, stc_dstc_intern_data::pfnDstcQprc0CountInversionCallback, stc_dstc_config::pfnDstcQprc0OutOfRangeCallback, stc_dstc_intern_data::pfnDstcQprc0OutOfRangeCallback, stc_dstc_config::pfnDstcQprc0PcMatchCallback, stc_dstc_intern_data::pfnDstcQprc0PcMatchCallback, stc_dstc_config::pfnDstcQprc0PcMatchRcMatchCallback, stc_dstc_intern_data::pfnDstcQprc0PcMatchRcMatchCallback, stc_dstc_config::pfnDstcQprc0PcRcMatchCallback, stc_dstc_intern_data::pfnDstcQprc0PcRcMatchCallback, stc_dstc_config::pfnDstcQprc0UflOflZCallback, stc_dstc_intern_data::pfnDstcQprc0UflOflZCallback, stc_dstc_config::pfnDstcQprc1CountInversionCallback, stc_dstc_intern_data::pfnDstcQprc1CountInversionCallback, stc_dstc_config::pfnDstcQprc1OutOfRangeCallback, stc_dstc_intern_data::pfnDstcQprc1OutOfRangeCallback, stc_dstc_config::pfnDstcQprc1PcMatchCallback, stc_dstc_intern_data::pfnDstcQprc1PcMatchCallback, stc_dstc_config::pfnDstcQprc1PcMatchRcMatchCallback, stc_dstc_intern_data::pfnDstcQprc1PcMatchRcMatchCallback, stc_dstc_config::pfnDstcQprc1PcRcMatchCallback, stc_dstc_intern_data::pfnDstcQprc1PcRcMatchCallback, stc_dstc_config::pfnDstcQprc1UflOflZCallback, stc_dstc_intern_data::pfnDstcQprc1UflOflZCallback, stc_dstc_config::pfnDstcQprc2CountInversionCallback, stc_dstc_intern_data::pfnDstcQprc2CountInversionCallback, stc_dstc_config::pfnDstcQprc2OutOfRangeCallback, stc_dstc_intern_data::pfnDstcQprc2OutOfRangeCallback, stc_dstc_config::pfnDstcQprc2PcMatchCallback, stc_dstc_intern_data::pfnDstcQprc2PcMatchCallback, stc_dstc_config::pfnDstcQprc2PcMatchRcMatchCallback, stc_dstc_intern_data::pfnDstcQprc2PcMatchRcMatchCallback, stc_dstc_config::pfnDstcQprc2PcRcMatchCallback, stc_dstc_intern_data::pfnDstcQprc2PcRcMatchCallback, stc_dstc_config::pfnDstcQprc2UflOflZCallback, stc_dstc_intern_data::pfnDstcQprc2UflOflZCallback, stc_dstc_config::pfnDstcQprc3CountInversionCallback, stc_dstc_intern_data::pfnDstcQprc3CountInversionCallback, stc_dstc_config::pfnDstcQprc3OutOfRangeCallback, stc_dstc_intern_data::pfnDstcQprc3OutOfRangeCallback, stc_dstc_config::pfnDstcQprc3PcMatchCallback, stc_dstc_intern_data::pfnDstcQprc3PcMatchCallback, stc_dstc_config::pfnDstcQprc3PcMatchRcMatchCallback, stc_dstc_intern_data::pfnDstcQprc3PcMatchRcMatchCallback, stc_dstc_config::pfnDstcQprc3PcRcMatchCallback, stc_dstc_intern_data::pfnDstcQprc3PcRcMatchCallback, stc_dstc_config::pfnDstcQprc3UflOflZCallback, stc_dstc_intern_data::pfnDstcQprc3UflOflZCallback, stc_dstc_config::pfnDstcUsb0Ep1Callback, stc_dstc_intern_data::pfnDstcUsb0Ep1Callback, stc_dstc_config::pfnDstcUsb0Ep2Callback, stc_dstc_intern_data::pfnDstcUsb0Ep2Callback, stc_dstc_config::pfnDstcUsb0Ep3Callback, stc_dstc_intern_data::pfnDstcUsb0Ep3Callback, stc_dstc_config::pfnDstcUsb0Ep4Callback, stc_dstc_intern_data::pfnDstcUsb0Ep4Callback, stc_dstc_config::pfnDstcUsb0Ep5Callback, stc_dstc_intern_data::pfnDstcUsb0Ep5Callback, stc_dstc_config::pfnDstcUsb1Ep1Callback, stc_dstc_intern_data::pfnDstcUsb1Ep1Callback, stc_dstc_config::pfnDstcUsb1Ep2Callback, stc_dstc_intern_data::pfnDstcUsb1Ep2Callback, stc_dstc_config::pfnDstcUsb1Ep3Callback, stc_dstc_intern_data::pfnDstcUsb1Ep3Callback, stc_dstc_config::pfnDstcUsb1Ep4Callback, stc_dstc_intern_data::pfnDstcUsb1Ep4Callback, stc_dstc_config::pfnDstcUsb1Ep5Callback, stc_dstc_intern_data::pfnDstcUsb1Ep5Callback, stc_dstc_config::pfnDstcWcCallback, stc_dstc_intern_data::pfnDstcWcCallback, stc_dstc_config::pfnErrorCallback, stc_dstc_intern_data::pfnErrorCallback, stc_dstc_config::pfnNotifySwCallback, stc_dstc_intern_data::pfnNotifySwCallback, Priority1_15, Priority1_2, Priority1_3, Priority1_31, Priority1_63, Priority1_7, PriorityHighest, PriorityLowest, and stc_dstc_config::u32Destp.
void Dstc_IrqHandler (void)
Interrupt Service Routine of DSTC.
< Error channel, if HS == 1; 0xFFFF, if HS == 0
Definition at line 96 of file dstc.c.
References CmdErclr, CmdSwclr, DesAccessError, DesOpenError, DestinationAccessError, Dstc_SetCommand(), ForcedTransferStop, NoError, stc_dstc_intern_data::pfnErrorCallback, stc_dstc_intern_data::pfnNotifySwCallback, SourceAccessError, and UnknownError.
void Dstc_MfsRxIrqHandler (uint8_t u8IrqChannel)
MFS.
Definition at line 1977 of file dstc.c.
References DSTC_IRQ_NUMBER_MFS0_RX, DSTC_IRQ_NUMBER_MFS1_RX, DSTC_IRQ_NUMBER_MFS2_RX, DSTC_IRQ_NUMBER_MFS3_RX, DSTC_IRQ_NUMBER_MFS4_RX, DSTC_IRQ_NUMBER_MFS5_RX, DSTC_IRQ_NUMBER_MFS6_RX, DSTC_IRQ_NUMBER_MFS7_RX, Dstc_ReadHwintBit(), Dstc_SetHwintclrBit(), stc_dstc_intern_data::pfnDstcMfs10RxCallback, stc_dstc_intern_data::pfnDstcMfs11RxCallback, stc_dstc_intern_data::pfnDstcMfs12RxCallback, stc_dstc_intern_data::pfnDstcMfs13RxCallback, stc_dstc_intern_data::pfnDstcMfs14RxCallback, stc_dstc_intern_data::pfnDstcMfs15RxCallback, stc_dstc_intern_data::pfnDstcMfs1RxCallback, stc_dstc_intern_data::pfnDstcMfs2RxCallback, stc_dstc_intern_data::pfnDstcMfs3RxCallback, stc_dstc_intern_data::pfnDstcMfs4RxCallback, stc_dstc_intern_data::pfnDstcMfs5RxCallback, stc_dstc_intern_data::pfnDstcMfs6RxCallback, stc_dstc_intern_data::pfnDstcMfs7RxCallback, stc_dstc_intern_data::pfnDstcMfs8RxCallback, and stc_dstc_intern_data::pfnDstcMfs9RxCallback.
void Dstc_MfsTxIrqHandler (uint8_t u8IrqChannel)
Definition at line 2087 of file dstc.c.
References DSTC_IRQ_NUMBER_MFS0_TX, DSTC_IRQ_NUMBER_MFS1_TX, DSTC_IRQ_NUMBER_MFS2_TX, DSTC_IRQ_NUMBER_MFS3_TX, DSTC_IRQ_NUMBER_MFS4_TX, DSTC_IRQ_NUMBER_MFS5_TX, DSTC_IRQ_NUMBER_MFS6_TX, DSTC_IRQ_NUMBER_MFS7_TX, Dstc_ReadHwintBit(), Dstc_SetHwintclrBit(), stc_dstc_intern_data::pfnDstcMfs0TxCallback, stc_dstc_intern_data::pfnDstcMfs10TxCallback, stc_dstc_intern_data::pfnDstcMfs11TxCallback, stc_dstc_intern_data::pfnDstcMfs12TxCallback, stc_dstc_intern_data::pfnDstcMfs13TxCallback, stc_dstc_intern_data::pfnDstcMfs14TxCallback, stc_dstc_intern_data::pfnDstcMfs15TxCallback, stc_dstc_intern_data::pfnDstcMfs1TxCallback, stc_dstc_intern_data::pfnDstcMfs2TxCallback, stc_dstc_intern_data::pfnDstcMfs3TxCallback, stc_dstc_intern_data::pfnDstcMfs4TxCallback, stc_dstc_intern_data::pfnDstcMfs5TxCallback, stc_dstc_intern_data::pfnDstcMfs6TxCallback, stc_dstc_intern_data::pfnDstcMfs7TxCallback, stc_dstc_intern_data::pfnDstcMfs8TxCallback, and stc_dstc_intern_data::pfnDstcMfs9TxCallback.
void Dstc_MftFrtPeakIrqHandler (uint8_t u8IrqChannel)
MFT FRT.
Definition at line 2199 of file dstc.c.
References DSTC_IRQ_NUMBER_MFT0_FRT0_PEAK, DSTC_IRQ_NUMBER_MFT0_FRT1_PEAK, DSTC_IRQ_NUMBER_MFT0_FRT2_PEAK, Dstc_ReadHwintBit(), Dstc_SetHwintclrBit(), stc_dstc_intern_data::pfnDstcMft0Frt0PeakCallback, stc_dstc_intern_data::pfnDstcMft0Frt1PeakCallback, stc_dstc_intern_data::pfnDstcMft0Frt2PeakCallback, stc_dstc_intern_data::pfnDstcMft1Frt0PeakCallback, stc_dstc_intern_data::pfnDstcMft1Frt1PeakCallback, stc_dstc_intern_data::pfnDstcMft1Frt2PeakCallback, stc_dstc_intern_data::pfnDstcMft2Frt0PeakCallback, stc_dstc_intern_data::pfnDstcMft2Frt1PeakCallback, and stc_dstc_intern_data::pfnDstcMft2Frt2PeakCallback.
void Dstc_MftFrtZeroIrqHandler (uint8_t u8IrqChannel)
Definition at line 2275 of file dstc.c.
References DSTC_IRQ_NUMBER_MFT0_FRT0_ZERO, DSTC_IRQ_NUMBER_MFT0_FRT1_ZERO, DSTC_IRQ_NUMBER_MFT0_FRT2_ZERO, Dstc_ReadHwintBit(), Dstc_SetHwintclrBit(), stc_dstc_intern_data::pfnDstcMft0Frt0ZeroCallback, stc_dstc_intern_data::pfnDstcMft0Frt1ZeroCallback, stc_dstc_intern_data::pfnDstcMft0Frt2ZeroCallback, stc_dstc_intern_data::pfnDstcMft1Frt0ZeroCallback, stc_dstc_intern_data::pfnDstcMft1Frt1ZeroCallback, stc_dstc_intern_data::pfnDstcMft1Frt2ZeroCallback, stc_dstc_intern_data::pfnDstcMft2Frt0ZeroCallback, stc_dstc_intern_data::pfnDstcMft2Frt1ZeroCallback, and stc_dstc_intern_data::pfnDstcMft2Frt2ZeroCallback.
void Dstc_MftIcuIrqHandler (uint8_t u8IrqChannel)
Definition at line 2541 of file dstc.c.
References DSTC_IRQ_NUMBER_MFT0_ICU0, DSTC_IRQ_NUMBER_MFT0_ICU1, DSTC_IRQ_NUMBER_MFT0_ICU2, DSTC_IRQ_NUMBER_MFT0_ICU3, Dstc_ReadHwintBit(), Dstc_SetHwintclrBit(), stc_dstc_intern_data::pfnDstcMft0Icu0Callback, stc_dstc_intern_data::pfnDstcMft0Icu1Callback, stc_dstc_intern_data::pfnDstcMft0Icu2Callback, stc_dstc_intern_data::pfnDstcMft0Icu3Callback, stc_dstc_intern_data::pfnDstcMft1Icu0Callback, stc_dstc_intern_data::pfnDstcMft1Icu1Callback, stc_dstc_intern_data::pfnDstcMft1Icu2Callback, stc_dstc_intern_data::pfnDstcMft1Icu3Callback, stc_dstc_intern_data::pfnDstcMft2Icu0Callback, stc_dstc_intern_data::pfnDstcMft2Icu1Callback, stc_dstc_intern_data::pfnDstcMft2Icu2Callback, and stc_dstc_intern_data::pfnDstcMft2Icu3Callback.
void Dstc_MftOcuIrqHandler (uint8_t u8IrqChannel)
Definition at line 2351 of file dstc.c.
References DSTC_IRQ_NUMBER_MFT0_OCU0, DSTC_IRQ_NUMBER_MFT0_OCU1, DSTC_IRQ_NUMBER_MFT0_OCU2, DSTC_IRQ_NUMBER_MFT0_OCU3, DSTC_IRQ_NUMBER_MFT0_OCU4, DSTC_IRQ_NUMBER_MFT0_OCU5, Dstc_ReadHwintBit(), Dstc_SetHwintclrBit(), stc_dstc_intern_data::pfnDstcMft0Ocu0Callback, stc_dstc_intern_data::pfnDstcMft0Ocu1Callback, stc_dstc_intern_data::pfnDstcMft0Ocu2Callback, stc_dstc_intern_data::pfnDstcMft0Ocu3Callback, stc_dstc_intern_data::pfnDstcMft0Ocu4Callback, stc_dstc_intern_data::pfnDstcMft0Ocu5Callback, stc_dstc_intern_data::pfnDstcMft1Ocu0Callback, stc_dstc_intern_data::pfnDstcMft1Ocu1Callback, stc_dstc_intern_data::pfnDstcMft1Ocu2Callback, stc_dstc_intern_data::pfnDstcMft1Ocu3Callback, stc_dstc_intern_data::pfnDstcMft1Ocu4Callback, stc_dstc_intern_data::pfnDstcMft1Ocu5Callback, stc_dstc_intern_data::pfnDstcMft2Ocu0Callback, stc_dstc_intern_data::pfnDstcMft2Ocu1Callback, stc_dstc_intern_data::pfnDstcMft2Ocu2Callback, stc_dstc_intern_data::pfnDstcMft2Ocu3Callback, stc_dstc_intern_data::pfnDstcMft2Ocu4Callback, and stc_dstc_intern_data::pfnDstcMft2Ocu5Callback.
void Dstc_MftWfgIrqHandler (uint8_t u8IrqChannel)
Definition at line 2468 of file dstc.c.
References DSTC_IRQ_NUMBER_MFT0_WFG10, DSTC_IRQ_NUMBER_MFT0_WFG32, DSTC_IRQ_NUMBER_MFT0_WFG54, Dstc_ReadHwintBit(), Dstc_SetHwintclrBit(), stc_dstc_intern_data::pfnDstcMft0Wfg10Callback, stc_dstc_intern_data::pfnDstcMft0Wfg32Callback, stc_dstc_intern_data::pfnDstcMft0Wfg54Callback, stc_dstc_intern_data::pfnDstcMft1Wfg10Callback, stc_dstc_intern_data::pfnDstcMft1Wfg32Callback, stc_dstc_intern_data::pfnDstcMft1Wfg54Callback, stc_dstc_intern_data::pfnDstcMft2Wfg10Callback, stc_dstc_intern_data::pfnDstcMft2Wfg32Callback, and stc_dstc_intern_data::pfnDstcMft2Wfg54Callback.
void Dstc_PcrcIrqHandler (uint8_t u8IrqChannel)
PCRC.
Definition at line 2625 of file dstc.c.
References Dstc_ReadHwintBit(), Dstc_SetHwintclrBit(), and stc_dstc_intern_data::pfnDstcPcrcCallback.
void Dstc_PpgIrqHandler (uint8_t u8IrqChannel)
PPG.
Definition at line 2652 of file dstc.c.
References DSTC_IRQ_NUMBER_PPG0, DSTC_IRQ_NUMBER_PPG2, DSTC_IRQ_NUMBER_PPG4, Dstc_ReadHwintBit(), Dstc_SetHwintclrBit(), stc_dstc_intern_data::pfnDstcPpg0Callback, stc_dstc_intern_data::pfnDstcPpg10Callback, stc_dstc_intern_data::pfnDstcPpg12Callback, stc_dstc_intern_data::pfnDstcPpg16Callback, stc_dstc_intern_data::pfnDstcPpg18Callback, stc_dstc_intern_data::pfnDstcPpg20Callback, stc_dstc_intern_data::pfnDstcPpg2Callback, stc_dstc_intern_data::pfnDstcPpg4Callback, and stc_dstc_intern_data::pfnDstcPpg8Callback.
void Dstc_QprcIrqHandler (uint8_t u8IrqChannel)
QPRC.
Definition at line 2738 of file dstc.c.
References DSTC_IRQ_NUMBER_QPRC0_COUNT_INVERSION, DSTC_IRQ_NUMBER_QPRC0_OUT_OF_RANGE, DSTC_IRQ_NUMBER_QPRC0_PC_MATCH, DSTC_IRQ_NUMBER_QPRC0_PC_MATCH_RC_MATCH, DSTC_IRQ_NUMBER_QPRC0_PC_RC_MATCH, DSTC_IRQ_NUMBER_QPRC0_UFL_OFL_Z, Dstc_ReadHwintBit(), Dstc_SetHwintclrBit(), stc_dstc_intern_data::pfnDstcQprc0CountInversionCallback, stc_dstc_intern_data::pfnDstcQprc0OutOfRangeCallback, stc_dstc_intern_data::pfnDstcQprc0PcMatchCallback, stc_dstc_intern_data::pfnDstcQprc0PcMatchRcMatchCallback, stc_dstc_intern_data::pfnDstcQprc0PcRcMatchCallback, stc_dstc_intern_data::pfnDstcQprc0UflOflZCallback, stc_dstc_intern_data::pfnDstcQprc1CountInversionCallback, stc_dstc_intern_data::pfnDstcQprc1OutOfRangeCallback, stc_dstc_intern_data::pfnDstcQprc1PcMatchCallback, stc_dstc_intern_data::pfnDstcQprc1PcMatchRcMatchCallback, stc_dstc_intern_data::pfnDstcQprc1PcRcMatchCallback, stc_dstc_intern_data::pfnDstcQprc1UflOflZCallback, stc_dstc_intern_data::pfnDstcQprc2CountInversionCallback, stc_dstc_intern_data::pfnDstcQprc2OutOfRangeCallback, stc_dstc_intern_data::pfnDstcQprc2PcMatchCallback, stc_dstc_intern_data::pfnDstcQprc2PcMatchRcMatchCallback, stc_dstc_intern_data::pfnDstcQprc2PcRcMatchCallback, and stc_dstc_intern_data::pfnDstcQprc2UflOflZCallback.
en_result_t Dstc_ReadDqmsk (stc_dstc_dqmsk_t * pstcDqmsk)
Read DQMSK Register.
Parameters:
[out] pstcDqmsk Pointer to DQMSK Structure
Return values:
Ok HWINT read-out successful
Definition at line 1253 of file dstc.c.
References stc_dstc_dqmsk::u32Dqmsk0, stc_dstc_dqmsk::u32Dqmsk1, stc_dstc_dqmsk::u32Dqmsk2, stc_dstc_dqmsk::u32Dqmsk3, stc_dstc_dqmsk::u32Dqmsk4, stc_dstc_dqmsk::u32Dqmsk5, stc_dstc_dqmsk::u32Dqmsk6, and stc_dstc_dqmsk::u32Dqmsk7.
en_result_t Dstc_ReadDreqenb (stc_dstc_dreqenb_t * pstcDreqenb)
Read DREQENB Register.
Parameters:
[out] pstcDreqenb Pointer to DREQENB Structure
Return values:
Ok DREQENB read-out successful
Definition at line 1107 of file dstc.c.
References stc_dstc_dreqenb::u32Dreqenb0, stc_dstc_dreqenb::u32Dreqenb1, stc_dstc_dreqenb::u32Dreqenb2, stc_dstc_dreqenb::u32Dreqenb3, stc_dstc_dreqenb::u32Dreqenb4, stc_dstc_dreqenb::u32Dreqenb5, stc_dstc_dreqenb::u32Dreqenb6, and stc_dstc_dreqenb::u32Dreqenb7.
uint16_t Dstc_ReadHwdesp (uint8_t u8Channel)
Read the HWDESP Address Offset of a Channel.
Parameters:
[in] u8Channel DSTC Channel to be initialized
Returns:
uint16_t Current HWDESP DES Offset
Definition at line 988 of file dstc.c.
en_result_t Dstc_ReadHwint (stc_dstc_hwint_t * pstcHwint)
Read HWINT Register.
Parameters:
[out] pstcHwint Pointer to HWINT Structure
Return values:
Ok HWINT read-out successful
Definition at line 1167 of file dstc.c.
References stc_dstc_hwint::u32Hwint0, stc_dstc_hwint::u32Hwint1, stc_dstc_hwint::u32Hwint2, stc_dstc_hwint::u32Hwint3, stc_dstc_hwint::u32Hwint4, stc_dstc_hwint::u32Hwint5, stc_dstc_hwint::u32Hwint6, and stc_dstc_hwint::u32Hwint7.
boolean_t Dstc_ReadHwintBit (uint8_t u8BitPos)
Read HWINT Register Bit.
Parameters:
[in] u8BitPos Bit Position (IRQ Number)
Return values:
TRUE HWINT bit set
FALSE HWINT bit not set
Definition at line 1212 of file dstc.c.
Referenced by Dstc_AdcIrqHandler(), Dstc_BtIrqHandler(), Dstc_CanfdIrqHandler(), Dstc_ExintIrqHandler(), Dstc_HsspiIrqHandler(), Dstc_I2csIrqHandler(), Dstc_I2sIrqHandler(), Dstc_MfsRxIrqHandler(), Dstc_MfsTxIrqHandler(), Dstc_MftFrtPeakIrqHandler(), Dstc_MftFrtZeroIrqHandler(), Dstc_MftIcuIrqHandler(), Dstc_MftOcuIrqHandler(), Dstc_MftWfgIrqHandler(), Dstc_PcrcIrqHandler(), Dstc_PpgIrqHandler(), Dstc_QprcIrqHandler(), and Dstc_WcIrqHandler().
en_result_t Dstc_ReleaseStandBy (void)
Release DSTC from Standby State.
Return values:
Ok DSTC released from standby mode
ErrorNotReady DSTC standby release failed
Definition at line 184 of file dstc.c.
References CmdStandyRelease, Dstc_SetCommand(), and DSTC_TRANSITION_TIMEOUT.
Referenced by Dstc_Init().
en_result_t Dstc_SetCommand (en_dstc_cmd_t enCommand)
Set a Command to CMD Register.
Parameters:
[in] enCommand Command of type of en_dstc_cmd_t
Return values:
Ok Command Set
ErrorInvalidParameter Wrong Command Enumerator used
Definition at line 1004 of file dstc.c.
References CmdErclr, CmdMkclr, CmdRbclr, CmdStandyRelease, CmdStandyTransition, and CmdSwclr.
Referenced by Dstc_DeInit(), Dstc_IrqHandler(), and Dstc_ReleaseStandBy().
en_result_t Dstc_SetDqmskclr (stc_dstc_dqmskclr_t * pstcDqmskclr)
Set DQMSKCLR Register.
Parameters:
[in] pstcDqmskclr Pointer to DQMSKCLR Structure
Return values:
Ok DQMSKCLR setting successful
Definition at line 1275 of file dstc.c.
References stc_dstc_dqmskclr::u32Dqmskclr0, stc_dstc_dqmskclr::u32Dqmskclr1, stc_dstc_dqmskclr::u32Dqmskclr2, stc_dstc_dqmskclr::u32Dqmskclr3, stc_dstc_dqmskclr::u32Dqmskclr4, stc_dstc_dqmskclr::u32Dqmskclr5, stc_dstc_dqmskclr::u32Dqmskclr6, and stc_dstc_dqmskclr::u32Dqmskclr7.
en_result_t Dstc_SetDqmskclrBit (uint8_t u8BitPos)
Set DQMSKCLR Register Bit.
Parameters:
[in] u8BitPos Bit Position (IRQ Number)
Return values:
Ok DQMSKCLR Bit set successfully
Definition at line 1297 of file dstc.c.
en_result_t Dstc_SetDreqenb (stc_dstc_dreqenb_t * pstcDreqenb)
Set DREQENB Register.
Parameters:
[in] pstcDreqenb Pointer to DREQENB Structure
Return values:
Ok DREQENB setting successful
Definition at line 1085 of file dstc.c.
References stc_dstc_dreqenb::u32Dreqenb0, stc_dstc_dreqenb::u32Dreqenb1, stc_dstc_dreqenb::u32Dreqenb2, stc_dstc_dreqenb::u32Dreqenb3, stc_dstc_dreqenb::u32Dreqenb4, stc_dstc_dreqenb::u32Dreqenb5, stc_dstc_dreqenb::u32Dreqenb6, and stc_dstc_dreqenb::u32Dreqenb7.
en_result_t Dstc_SetDreqenbBit (uint8_t u8BitPos)
Set DREQENB Register Bit.
Parameters:
[in] u8BitPos Bit Position (IRQ Number)
Return values:
Ok DREQENB Bit set successfully
Definition at line 1129 of file dstc.c.
en_result_t Dstc_SetHwdesp (uint8_t u8Channel, uint16_t u16HwDesp)
Initializes a DSTC channel.
Parameters:
[in] u8Channel DSTC Channel to be initialized
[in] u16HwDesp Offset to Channel Configuration
Return values:
Ok DSTC Initialized
ErrorInvalidParameter DES Address > 16K Bytes
ErrorAddressAlignment DES Address not aligned to 32 Bit
Definition at line 961 of file dstc.c.
en_result_t Dstc_SetHwintclr (stc_dstc_hwintclr_t * pstcHwintclr)
Set HWINTCLR Register.
Parameters:
[in] pstcHwintclr Pointer to HWINTCLR Structure
Return values:
Ok HWINTCLR setting successful
Definition at line 1189 of file dstc.c.
References stc_dstc_hwintclr::u32Hwintclr0, stc_dstc_hwintclr::u32Hwintclr1, stc_dstc_hwintclr::u32Hwintclr2, stc_dstc_hwintclr::u32Hwintclr3, stc_dstc_hwintclr::u32Hwintclr4, stc_dstc_hwintclr::u32Hwintclr5, stc_dstc_hwintclr::u32Hwintclr6, and stc_dstc_hwintclr::u32Hwintclr7.
en_result_t Dstc_SetHwintclrBit (uint8_t u8BitPos)
Set HWINTCLR Register Bit.
Parameters:
[in] u8BitPos Bit Position (IRQ Number)
Return values:
Ok HWINTCLR Bit set successfully
Definition at line 1234 of file dstc.c.
Referenced by Dstc_AdcIrqHandler(), Dstc_BtIrqHandler(), Dstc_CanfdIrqHandler(), Dstc_ExintIrqHandler(), Dstc_HsspiIrqHandler(), Dstc_I2csIrqHandler(), Dstc_I2sIrqHandler(), Dstc_MfsRxIrqHandler(), Dstc_MfsTxIrqHandler(), Dstc_MftFrtPeakIrqHandler(), Dstc_MftFrtZeroIrqHandler(), Dstc_MftIcuIrqHandler(), Dstc_MftOcuIrqHandler(), Dstc_MftWfgIrqHandler(), Dstc_PcrcIrqHandler(), Dstc_PpgIrqHandler(), Dstc_QprcIrqHandler(), and Dstc_WcIrqHandler().
en_result_t Dstc_SwTrigger (uint16_t u16SwDesPointer)
Set SWDESP offset and trigger SW transfer.
Parameters:
[in] u16SwDesPointer Address offset to DES
Return values:
Ok SWDESP set
ErrorInvalidParameter Offset > 16K Bytes
ErrorAddressAlignment Offset not 32-bit aligned
Definition at line 1043 of file dstc.c.
en_result_t Dstc_SwTrqansferStartStatus (void)
Check Software Trigger Start State.
Return values:
Ok SW Transfer ended
OperationInProgress SW Transfer pending
Definition at line 1067 of file dstc.c.
void Dstc_WcIrqHandler (void)
Definition at line 2851 of file dstc.c.
References DSTC_IRQ_NUMBER_WC, Dstc_ReadHwintBit(), Dstc_SetHwintclrBit(), and stc_dstc_intern_data::pfnDstcWcCallback.
Variable Documentation
stc_dstc_intern_data_t stcDstcInternData [static]
Definition at line 86 of file dstc.c.