PDL for FM Family: Dual Timer (DT)
Dual Timer (DT)
Data Structures
struct stc_dt_channel_config
Dt channel configuration.
struct stc_dt_intern_data
Datatype for holding internal data needed for DT.
struct stc_dt_instance_data
DT instance data type.
Defines
#define DT0 (*((volatile stc_dtn_t *) FM_DTIM_BASE))
#define DT_PRE_TIMER_DIV_1 (0x00)
#define DT_PRE_TIMER_DIV_16 (0x01)
#define DT_PRE_TIMER_DIV_256 (0x02)
Typedefs
typedef FM_DTIM_TypeDef stc_dtn_t
Redefinition of DT register structure.
typedef enum en_dt_mode en_dt_mode_t
Dt mode.
typedef enum en_dt_prescaler en_dt_prescaler_t
Dt Prescaler.
typedef enum en_dt_countersize en_dt_countersize_t
Dt Counter Size.
typedef enum en_dt_channel en_dt_channel_t
Dt channel number.
typedef struct
stc_dt_channel_config stc_dt_channel_config_t
Dt channel configuration.
typedef enum en_dt_instance_index en_dt_instance_index_t
Enumeration to define an index for each enabled Dual timer instance.
typedef struct stc_dt_intern_data stc_dt_intern_data_t
Datatype for holding internal data needed for DT.
typedef struct stc_dt_instance_data stc_dt_instance_data_t
DT instance data type.
Enumerations
enum en_dt_mode { DtFreeRun = 0u, DtPeriodic = 1u, DtOneShot = 2u }
Dt mode.
enum en_dt_prescaler { DtPrescalerDiv1 = 0u, DtPrescalerDiv16 = 1u, DtPrescalerDiv256 = 2u }
Dt Prescaler.
enum en_dt_countersize { DtCounterSize16 = 0u, DtCounterSize32 = 1u }
Dt Counter Size.
enum en_dt_channel { DtChannel0 = 0u, DtChannel1 = 1u, DtMaxChannels = 2u }
Dt channel number.
enum en_dt_instance_index { DtInstanceIndexDt0 = 0u, DtInstanceIndexMax }
Enumeration to define an index for each enabled Dual timer instance.
Functions
static stc_dt_intern_data_t * DtGetInternDataPtr (volatile stc_dtn_t **ppstcDt, uint8_t u8Ch)
Check pointer to Dual Timer instance and enable channel.
static void DtInitNvic (void)
Device dependent initialization of interrupts according CMSIS with level defined in pdl.h.
static void DtDeInitNvic (void)
Device dependent de-initialization of interrupts according CMSIS.
void DtIrqHandler (uint8_t u8Ch)
ISR callback for DT (channel 0 and 1)
en_result_t Dt_Init (stc_dt_channel_config_t *pstcConfig, uint8_t u8Ch)
Initialize DT.
en_result_t Dt_DeInit (uint8_t u8Ch, boolean_t bTouchNvic)
De-Initialize DT.
en_result_t Dt_EnableCount (uint8_t u8Ch)
Enable Timer Counter.
en_result_t Dt_DisableCount (uint8_t u8Ch)
Disable Timer Counter.
en_result_t Dt_EnableIrq (uint8_t u8Ch)
Enable Interrupt.
en_result_t Dt_DisableIrq (uint8_t u8Ch)
Disable Interrupt.
boolean_t Dt_GetIrqFlag (uint8_t u8Ch)
Get interrupt status The Function can return the interrupt status (TimerXRIS)
boolean_t Dt_GetMaskIrqFlag (uint8_t u8Ch)
Get mask interrupt status The Function can return the mask interrupt status (TimerXMIS)
en_result_t Dt_ClrIrqFlag (uint8_t u8Ch)
Clear interrupt status The Function clears the interrupt status.
en_result_t Dt_WriteLoadVal (uint32_t u32LoadVal, uint8_t u8Ch)
Write load value The Function writes the load value to load register.
en_result_t Dt_WriteBgLoadVal (uint32_t u32BgLoadVal, uint8_t u8Ch)
Write back-ground load value The Function writes the load value to back-ground load register.
uint32_t Dt_ReadCurCntVal (uint8_t u8Ch)
Read current count value The Function reads the value from value register.
Variables
static stc_dt_instance_data_t m_astcDtInstanceDataLut [DtInstanceIndexMax]
Look-up table for all enabled DT instances and their internal data.
Detailed Description
Provided functions of DT module:
Dt_Init()
Dt_DeInit()
Dt_EnableCount()
Dt_DisableCount()
Dt_EnableIrq()
Dt_DisableIrq()
Dt_GetIrqFlag()
Dt_GetMaskIrqFlag()
Dt_ClrIrqFlag()
Dt_WriteLoadVal()
Dt_WriteBgLoadVal()
Dt_ReadCurCntVal()
Dt_Init() must be used for configuration of a Dual Timer (DT) channel a structure with the type stc_dt_channel_config_t.
The interrupts can be configured in Dt_Init(), after initialization, the interrupt can be enabled or disabled with Dt_EnableIrq() and Dt_DisableIrq().
A DT Channel can be enabled by the function Dt_EnableCount(). Depending on the used mode, it is started in:
Free-run mode
Periodic mode
One-shot mode
With Dt_WriteLoadVal() the recent DT counter is set to the value given in the parameter Dt_WriteLoadVal::u32LoadVal. This works in each of the three operation modes.
With Dt_WriteBgLoadVal() the background reload value can be set, which is then set to the load value after the DT counter reaches the next 0.
With Dt_ReadCurCntVal() the current DT counter can be read.
Before deinitialization of the DT by Dt_DeInit(), it is recommended to disable all channels via Dt_DisableCount() and Dt_DisableIrq() before, to avoid a possible, unwanted interrupt.
Define Documentation
#define DT0 (*((volatile stc_dtn_t *) FM_DTIM_BASE))
Definition at line 196 of file dt.h.
Referenced by Dt_ClrIrqFlag(), Dt_DeInit(), Dt_DisableCount(), Dt_DisableIrq(), Dt_EnableCount(), Dt_EnableIrq(), Dt_GetIrqFlag(), Dt_GetMaskIrqFlag(), Dt_Init(), Dt_ReadCurCntVal(), Dt_WriteBgLoadVal(), Dt_WriteLoadVal(), and DtIrqHandler().
#define DT_PRE_TIMER_DIV_1 (0x00)
Definition at line 199 of file dt.h.
Referenced by Dt_Init().
#define DT_PRE_TIMER_DIV_16 (0x01)
Definition at line 200 of file dt.h.
Referenced by Dt_Init().
#define DT_PRE_TIMER_DIV_256 (0x02)
Definition at line 201 of file dt.h.
Referenced by Dt_Init().
Typedef Documentation
typedef enum en_dt_channel en_dt_channel_t
Dt channel number.
typedef enum en_dt_countersize en_dt_countersize_t
Dt Counter Size.
To select the size of the counter
typedef enum en_dt_instance_index en_dt_instance_index_t
Enumeration to define an index for each enabled Dual timer instance.
typedef enum en_dt_mode en_dt_mode_t
Dt mode.
To select between Free-run, Periodic, and One-Shot mode
typedef enum en_dt_prescaler en_dt_prescaler_t
Dt Prescaler.
To select clock divider
typedef struct stc_dt_channel_config stc_dt_channel_config_t
Dt channel configuration.
The DT configuration is done on a per channel basis
typedef struct stc_dt_instance_data stc_dt_instance_data_t
DT instance data type.
typedef struct stc_dt_intern_data stc_dt_intern_data_t
Datatype for holding internal data needed for DT.
typedef FM_DTIM_TypeDef stc_dtn_t
Redefinition of DT register structure.
Definition at line 124 of file dt.h.
Enumeration Type Documentation
enum en_dt_channel
Dt channel number.
Enumerator:
DtChannel0
channel 0
DtChannel1
channel 1
DtMaxChannels
Number of channels.
Definition at line 168 of file dt.h.
enum en_dt_countersize
Dt Counter Size.
To select the size of the counter
Enumerator:
DtCounterSize16
16 Bit counter size
DtCounterSize32
32 Bit counter size
Definition at line 158 of file dt.h.
enum en_dt_instance_index
Enumeration to define an index for each enabled Dual timer instance.
Enumerator:
DtInstanceIndexDt0
DtInstanceIndexMax
Definition at line 208 of file dt.h.
enum en_dt_mode
Dt mode.
To select between Free-run, Periodic, and One-Shot mode
Enumerator:
DtFreeRun
Free-running mode.
DtPeriodic
Periodic mode.
DtOneShot
One-shot mode.
Definition at line 132 of file dt.h.
enum en_dt_prescaler
Dt Prescaler.
To select clock divider
Enumerator:
DtPrescalerDiv1
Prescaler divisor 1.
DtPrescalerDiv16
Prescaler divisor 16.
DtPrescalerDiv256
Prescaler divisor 256.
Definition at line 145 of file dt.h.
Function Documentation
en_result_t Dt_ClrIrqFlag (uint8_t u8Ch)
Clear interrupt status The Function clears the interrupt status.
Parameters:
[in] u8Ch Channel number
Return values:
Ok Process successfully done.
ErrorInvalidParameter If one of following conditions are met:
u8Ch >= DtMaxChannels
pstcDtInternData == NULL (invalid or disabled DT unit (PDL_PERIPHERAL_ENABLE_DT))
Definition at line 675 of file dt.c.
References DT0, and DtGetInternDataPtr().
en_result_t Dt_DeInit (uint8_t u8Ch, boolean_t bTouchNvic)
De-Initialize DT.
This function de-initializes the specified channel of Dual Timer. Dt-DeInit() accesses the DT hardware register. They are reset.
Parameters:
[in] u8Ch Channel number
[in] bTouchNvic Touch NVIC or not
Return values:
Ok Process successfully done.
ErrorInvalidParameter If one of following conditions are met:
pstcDt == NULL
u8Ch >= DtMaxChannels
pstcDtInternData == NULL (invalid or disabled DT unit (PDL_PERIPHERAL_ENABLE_DT))
Definition at line 392 of file dt.c.
References DT0, DtDeInitNvic(), DtGetInternDataPtr(), and stc_dt_intern_data::pfnIrqCallbackIntern.
en_result_t Dt_DisableCount (uint8_t u8Ch)
Disable Timer Counter.
This function disables the timer counter.
Parameters:
[in] u8Ch Channel number
Return values:
Ok Process successfully done.
ErrorInvalidParameter If one of following conditions are met:
u8Ch >= DtMaxChannels
pstcDtInternData == NULL (invalid or disabled DT unit (PDL_PERIPHERAL_ENABLE_DT))
Definition at line 487 of file dt.c.
References DT0, and DtGetInternDataPtr().
en_result_t Dt_DisableIrq (uint8_t u8Ch)
Disable Interrupt.
This function disables the interruption.
Parameters:
[in] u8Ch Channel number
Return values:
Ok Process successfully done.
ErrorInvalidParameter If one of following conditions are met:
u8Ch >= DtMaxChannels
pstcDtInternData == NULL (invalid or disabled DT unit (PDL_PERIPHERAL_ENABLE_DT))
Definition at line 567 of file dt.c.
References DT0, and DtGetInternDataPtr().
en_result_t Dt_EnableCount (uint8_t u8Ch)
Enable Timer Counter.
This function enables the timer counter.
Parameters:
[in] u8Ch Channel number
Return values:
Ok Process successfully done.
ErrorInvalidParameter If one of following conditions are met:
u8Ch >= DtMaxChannels
pstcDtInternData == NULL (invalid or disabled DT unit (PDL_PERIPHERAL_ENABLE_DT))
Definition at line 448 of file dt.c.
References DT0, and DtGetInternDataPtr().
en_result_t Dt_EnableIrq (uint8_t u8Ch)
Enable Interrupt.
This function enables the interruption.
Parameters:
[in] u8Ch Channel number
Return values:
Ok Process successfully done.
ErrorInvalidParameter If one of following conditions are met:
u8Ch >= DtMaxChannels
pstcDtInternData == NULL (invalid or disabled DT unit (PDL_PERIPHERAL_ENABLE_DT))
Definition at line 527 of file dt.c.
References DT0, and DtGetInternDataPtr().
boolean_t Dt_GetIrqFlag (uint8_t u8Ch)
Get interrupt status The Function can return the interrupt status (TimerXRIS)
Parameters:
[in] u8Ch Channel number
Return values:
boolean_t:the interrupt status
Definition at line 603 of file dt.c.
References DT0, and DtGetInternDataPtr().
boolean_t Dt_GetMaskIrqFlag (uint8_t u8Ch)
Get mask interrupt status The Function can return the mask interrupt status (TimerXMIS)
Parameters:
[in] u8Ch Channel number
Return values:
boolean_t:the mask interrupt status
Definition at line 637 of file dt.c.
References DT0, and DtGetInternDataPtr().
en_result_t Dt_Init (stc_dt_channel_config_t * pstcConfig, uint8_t u8Ch)
Initialize DT.
This function initializes the specified channel of Dual Timer.
Parameters:
[in] pstcConfig Dual timer configuration
[in] u8Ch Channel number
Return values:
Ok Process successfully done.
ErrorInvalidParameter If one of following conditions are met:
pstcConfig == NULL
u8Ch >= DtMaxChannels
pstcDtInternData == NULL (invalid or disabled DT unit (PDL_PERIPHERAL_ENABLE_DT))
one or more enumerated values in pstcDt out of enumaration
Definition at line 261 of file dt.c.
References stc_dt_channel_config::bIrqEnable, stc_dt_channel_config::bTouchNvic, DT0, DT_PRE_TIMER_DIV_1, DT_PRE_TIMER_DIV_16, DT_PRE_TIMER_DIV_256, DtCounterSize16, DtCounterSize32, DtFreeRun, DtGetInternDataPtr(), DtInitNvic(), DtOneShot, DtPeriodic, DtPrescalerDiv1, DtPrescalerDiv16, DtPrescalerDiv256, stc_dt_channel_config::pfnIrqCallback, stc_dt_intern_data::pfnIrqCallbackIntern, stc_dt_channel_config::u8CounterSize, stc_dt_channel_config::u8Mode, and stc_dt_channel_config::u8PrescalerDiv.
uint32_t Dt_ReadCurCntVal (uint8_t u8Ch)
Read current count value The Function reads the value from value register.
Parameters:
[in] u8Ch Channel number
Return values:
uint32_t:current counter value
Definition at line 801 of file dt.c.
References DT0, and DtGetInternDataPtr().
en_result_t Dt_WriteBgLoadVal (uint32_t u32BgLoadVal, uint8_t u8Ch)
Write back-ground load value The Function writes the load value to back-ground load register.
Parameters:
[in] u32BgLoadVal Load value to set to back-ground load register
[in] u8Ch Channel number
Return values:
Ok Process successfully done.
ErrorInvalidParameter If one of following conditions are met:
u8Ch >= DtMaxChannels
pstcDtInternData == NULL (invalid or disabled DT unit (PDL_PERIPHERAL_ENABLE_DT))
Definition at line 760 of file dt.c.
References DT0, and DtGetInternDataPtr().
en_result_t Dt_WriteLoadVal (uint32_t u32LoadVal, uint8_t u8Ch)
Write load value The Function writes the load value to load register.
Parameters:
[in] u32LoadVal Load value to set to load register
[in] u8Ch Channel number
Return values:
Ok Process successfully done.
ErrorInvalidParameter If one of following conditions are met:
u8Ch >= DtMaxChannels
pstcDtInternData == NULL (invalid or disabled DT unit (PDL_PERIPHERAL_ENABLE_DT))
Definition at line 714 of file dt.c.
References DT0, and DtGetInternDataPtr().
static void DtDeInitNvic (void) [static]
Device dependent de-initialization of interrupts according CMSIS.
Definition at line 181 of file dt.c.
References PDL_DEFAULT_INTERRUPT_LEVEL.
Referenced by Dt_DeInit().
static stc_dt_intern_data_t * DtGetInternDataPtr (volatile stc_dtn_t ** ppstcDt, uint8_t u8Ch) [static]
Check pointer to Dual Timer instance and enable channel.
Parameters:
[in,out] ppstcDt Pointer of pointer to Dual Timer instance register area
[in] u8Ch Channel number
Return values:
Pointer to internal data or NULL if instance is not enabled. (or channel is invalid)
Definition at line 118 of file dt.c.
References DtInstanceIndexMax, DtMaxChannels, and stc_dt_instance_data::stcInternData.
Referenced by Dt_ClrIrqFlag(), Dt_DeInit(), Dt_DisableCount(), Dt_DisableIrq(), Dt_EnableCount(), Dt_EnableIrq(), Dt_GetIrqFlag(), Dt_GetMaskIrqFlag(), Dt_Init(), Dt_ReadCurCntVal(), Dt_WriteBgLoadVal(), and Dt_WriteLoadVal().
static void DtInitNvic (void) [static]
Device dependent initialization of interrupts according CMSIS with level defined in pdl.h.
Definition at line 153 of file dt.c.
References PDL_IRQ_LEVEL_DT_RTC_WC.
Referenced by Dt_Init().
void DtIrqHandler (uint8_t u8Ch)
ISR callback for DT (channel 0 and 1)
This callbacks are called by the global DT ISR whenever an DT triggers an interrupt (on channel 0 and/or 1). It calls the callback functions that has been given during Dt initialization (see Dt_Init() and stc_dt_channel_config_t) for each channel individually. If the pointer to a callback function is NULL, no call is performed.
The active interrupt request flags are cleared by the ISR
Parameters:
[in] u8Ch Channel number
Definition at line 219 of file dt.c.
References DT0, stc_dt_intern_data::pfnIrqCallbackIntern, and stc_dt_instance_data::stcInternData.
Variable Documentation
stc_dt_instance_data_t m_astcDtInstanceDataLut[DtInstanceIndexMax] [static]
Initial value:
{
    {
        & (*((volatile stc_dtn_t *) FM_DTIM_BASE)) ,
        0u
    }
}
Look-up table for all enabled DT instances and their internal data.
Definition at line 74 of file dt.c.