PDL for FM Family: I2S-Lite (I2SL)
I2S-Lite (I2SL)
Data Structures
struct stc_i2sl_irq_cb
I2S-Lite interrupt callback function.
struct stc_i2sl_irq_en
I2S interrupt enable structure.
struct stc_i2s_config
I2S configuration.
struct stc_i2sl_intern_data
I2S interrupt callback function.
struct stc_i2sl_instance_data
MFS instance data type.
Defines
#define stc_i2sln_t FM_MFS_CSIO_TypeDef
#define stc_i2slregn_t FM_I2SL_TypeDef
#define I2SL0 (*(volatile stc_i2sln_t *) FM_MFS4_CSIO)
#define I2SL1 (*(volatile stc_i2sln_t *) FM_MFS6_CSIO)
#define I2SLREG0 (*(volatile stc_i2slregn_t *) FM_I2SL0)
#define I2SLREG1 (*(volatile stc_i2slregn_t *) FM_I2SL1)
#define I2SL_INSTANCE_COUNT
Typedefs
typedef enum en_i2sl_clk_in en_i2sl_clk_in_t
typedef enum en_i2sl_mode en_i2sl_mode_t
typedef enum en_i2sl_frame_len en_i2sl_frame_len_t
typedef enum en_i2sl_fifo_width en_i2sl_fifo_width_t
typedef enum en_i2sl_fifo_sel en_i2sl_fifo_sel_t
I2S-Lite FIFO Selection.
typedef struct stc_i2sl_irq_cb stc_i2sl_irq_cb_t
I2S-Lite interrupt callback function.
typedef struct stc_i2sl_irq_en stc_i2sl_irq_en_t
I2S interrupt enable structure.
typedef enum en_i2sl_irq_sel en_i2sl_irq_sel_t
I2S interrupt enable structure.
typedef enum en_i2sl_fifo en_i2sl_fifo_t
i2s FIFO Number
typedef struct stc_i2s_config stc_i2sl_config_t
typedef enum en_i2sl_status en_i2sl_status_t
typedef struct stc_i2sl_intern_data stc_i2sl_intern_data_t
I2S interrupt callback function.
typedef struct
stc_i2sl_instance_data stc_i2sl_instance_data_t
MFS instance data type.
typedef enum en_i2sl_instance_index en_i2sl_instance_index_t
Enumeration to define an index for each enabled I2S-Lite instance.
Enumerations
enum en_i2sl_clk_in { I2slUsePclk = 0u, I2slUseExtClk = 1u }
enum en_i2sl_mode { I2slPhilipsMode = 0u, I2slMsbJustifiedMode = 1u }
enum en_i2sl_frame_len { I2slFrame16Bit = 0u, I2slFrame32Bit = 1u }
enum en_i2sl_fifo_width { I2slFifoWidth16Bit = 0u, I2slFifoWidth32Bit = 1u }
enum en_i2sl_fifo_sel { I2slTxFifo1RxFifo2 = 0u, I2slTxFifo2RxFifo1 = 1u }
I2S-Lite FIFO Selection.
enum en_i2sl_irq_sel { I2slRxFifoIrq = 0u, I2slTxFifoIrq = 1u }
I2S interrupt enable structure.
enum en_i2sl_fifo { I2slFifo1 = 0u, I2slFifo2 = 1u }
i2s FIFO Number
enum en_i2sl_status {
I2slTxFifoEmpty = 0u, I2slRxFifoFull = 1u, I2slRxFifoOverrun = 2u, I2slBusBusy = 3u,
I2slClockStatus = 4u
}
enum en_i2sl_instance_index { I2slInstanceIndexI2sl0, I2slInstanceIndexI2sl1, I2slInstanceIndexMax, I2slInstanceIndexUnknown = 0xFFu }
Enumeration to define an index for each enabled I2S-Lite instance.
Functions
static stc_i2sl_intern_data_t * I2slGetInternDataPtr (volatile FM_MFS_CSIO_TypeDef *pstcI2sl)
Return the internal data for a certain i2s instance.
static volatile FM_I2SL_TypeDef * I2slGetRegPtr (volatile FM_MFS_CSIO_TypeDef *pstcI2sl)
Return the internal data for a certain i2s register instance.
void I2sl_TxIrqHandler (volatile FM_MFS_CSIO_TypeDef *pstcI2sl, stc_i2sl_intern_data_t *pstcI2slInternData)
i2s instance transmiting interrupt service routine
void I2sl_RxIrqHandler (volatile FM_MFS_CSIO_TypeDef *pstcI2sl, stc_i2sl_intern_data_t *pstcI2slInternData)
i2s instance receiving interrupt service routine
static void I2slInitNvic (volatile FM_MFS_CSIO_TypeDef *pstcI2sl, boolean_t bRxIrq)
Set NVIC Interrupt depending on I2S instance.
static void I2slDeInitNvic (volatile FM_MFS_CSIO_TypeDef *pstcI2sl, boolean_t bRxIrq)
Clear NVIC Interrupt depending on I2S instance.
en_result_t I2sl_EnableIrq (volatile FM_MFS_CSIO_TypeDef *pstcI2sl, en_i2sl_irq_sel_t enIrqSel)
Enable I2S interrupts.
en_result_t I2sl_DisableIrq (volatile FM_MFS_CSIO_TypeDef *pstcI2sl, en_i2sl_irq_sel_t enIrqSel)
Disable I2S interrupt.
en_result_t I2sl_Init (volatile FM_MFS_CSIO_TypeDef *pstcI2sl, stc_i2sl_config_t *pstcConfig)
Initialize I2S.
en_result_t I2sl_DeInit (volatile FM_MFS_CSIO_TypeDef *pstcI2sl, boolean_t bTouchNvic)
Deinitialisation I2S.
en_result_t I2sl_Start (volatile FM_MFS_CSIO_TypeDef *pstcI2sl)
start I2S, enable i2s clock generate
en_result_t I2sl_Stop (volatile FM_MFS_CSIO_TypeDef *pstcI2sl)
stop I2S, disable i2s clock generate
en_result_t I2sl_EnableClockOut (volatile FM_MFS_CSIO_TypeDef *pstcI2sl)
Enable I2S Clock out.
en_result_t I2sl_DisableClockOut (volatile FM_MFS_CSIO_TypeDef *pstcI2sl)
Disable I2S Clock out.
boolean_t I2sl_GetStatus (volatile FM_MFS_CSIO_TypeDef *pstcI2sl, en_i2sl_status_t enStatus)
Get status of I2S-Lite according to status type.
en_result_t I2sl_ClrError (volatile FM_MFS_CSIO_TypeDef *pstcI2sl)
Clear overrun error flag.
en_result_t I2sl_WriteTxFifo (volatile FM_MFS_CSIO_TypeDef *pstcI2sl, uint32_t u32Data)
Write I2S data buffer.
uint32_t I2sl_ReadRxFifo (volatile FM_MFS_CSIO_TypeDef *pstcI2sl)
read I2S data buffer
en_result_t I2sl_ResetFifo (volatile FM_MFS_CSIO_TypeDef *pstcI2sl, en_i2sl_fifo_t enFifo)
Reset I2S FIFO.
en_result_t I2sl_SetFifoCount (volatile FM_MFS_CSIO_TypeDef *pstcI2sl, en_i2sl_fifo_t enFifo, uint8_t u8Count)
set I2S FIFO count
uint8_t I2sl_GetFifoCount (volatile FM_MFS_CSIO_TypeDef *pstcI2sl, en_i2sl_fifo_t enFifo)
Get I2S FIFO count.
Variables
stc_i2sl_instance_data_t m_astcI2slInstanceDataLut [(uint8_t)(PDL_PERIPHERAL_ENABLE_I2SL0==PDL_ON)+(uint8_t)(PDL_PERIPHERAL_ENABLE_I2SL1==PDL_ON)]
Look-up table for all enabled I2s instances and their internal data.
stc_i2sl_instance_data_t m_astcI2slInstanceDataLut [(uint8_t)(PDL_PERIPHERAL_ENABLE_I2SL0==PDL_ON)+(uint8_t)(PDL_PERIPHERAL_ENABLE_I2SL1==PDL_ON)]
Look-up table for all enabled I2S-Lite instances and their internal data.
Detailed Description
Provided functions of I2SL module:
I2sl_Init()
I2sl_DeInit()
I2sl_Start()
I2sl_Stop()
I2sl_GetStatus()
I2sl_ClrError()
I2sl_WriteTxFifo()
I2sl_ReadRxFifo()
I2sl_ResetFifo()
I2sl_Init() is used for configuration of a I2S-Lite (I2SL) channel with a structure of the type stc_i2sl_config_t.
I2sl_DeInit() is used to reset all registers of a I2SL channel.
I2sl_Start() starts output of I2S clock and I2sl_Stop() stops output of I2S clock.
I2sl_GetStatus() gets the status of I2S-Lite according to the status type en_i2sl_status_t.
I2sl_ClrError() clears error of I2SL.
I2sl_WriteTxFifo() writes the transmission FIFO of I2SL and I2sl_ReadRxFifo() read the transmission FIFO of I2SL. I2sl_ResetFifo() resets FIFO.
Define Documentation
#define I2SL0 (*(volatile stc_i2sln_t *) FM_MFS4_CSIO)
Definition at line 111 of file i2sl.h.
Referenced by I2slDeInitNvic(), and I2slInitNvic().
#define I2SL1 (*(volatile stc_i2sln_t *) FM_MFS6_CSIO)
Definition at line 112 of file i2sl.h.
Referenced by I2slDeInitNvic(), and I2slInitNvic().
#define I2SL_INSTANCE_COUNT
Value:
(uint8_t)(PDL_PERIPHERAL_ENABLE_I2SL0 == PDL_ON) + \
        (uint8_t)(PDL_PERIPHERAL_ENABLE_I2SL1 == PDL_ON)
Definition at line 127 of file i2sl.h.
Referenced by I2slGetInternDataPtr(), and I2slGetRegPtr().
#define I2SLREG0 (*(volatile stc_i2slregn_t *) FM_I2SL0)
Definition at line 124 of file i2sl.h.
#define I2SLREG1 (*(volatile stc_i2slregn_t *) FM_I2SL1)
Definition at line 125 of file i2sl.h.
#define stc_i2sln_t FM_MFS_CSIO_TypeDef
Definition at line 106 of file i2sl.h.
Referenced by I2slDeInitNvic(), and I2slInitNvic().
#define stc_i2slregn_t FM_I2SL_TypeDef
Definition at line 107 of file i2sl.h.
Referenced by I2sl_DeInit(), I2sl_DisableClockOut(), I2sl_EnableClockOut(), I2sl_GetStatus(), I2sl_Init(), I2sl_Start(), and I2sl_Stop().
Typedef Documentation
typedef enum en_i2sl_clk_in en_i2sl_clk_in_t
typedef enum en_i2sl_fifo_sel en_i2sl_fifo_sel_t
I2S-Lite FIFO Selection.
typedef enum en_i2sl_fifo en_i2sl_fifo_t
i2s FIFO Number
typedef enum en_i2sl_fifo_width en_i2sl_fifo_width_t
typedef enum en_i2sl_frame_len en_i2sl_frame_len_t
typedef enum en_i2sl_instance_index en_i2sl_instance_index_t
Enumeration to define an index for each enabled I2S-Lite instance.
typedef enum en_i2sl_irq_sel en_i2sl_irq_sel_t
I2S interrupt enable structure.
typedef enum en_i2sl_mode en_i2sl_mode_t
typedef enum en_i2sl_status en_i2sl_status_t
typedef struct stc_i2s_config stc_i2sl_config_t
typedef struct stc_i2sl_instance_data stc_i2sl_instance_data_t
MFS instance data type.
typedef struct stc_i2sl_intern_data stc_i2sl_intern_data_t
I2S interrupt callback function.
typedef struct stc_i2sl_irq_cb stc_i2sl_irq_cb_t
I2S-Lite interrupt callback function.
typedef struct stc_i2sl_irq_en stc_i2sl_irq_en_t
I2S interrupt enable structure.
Enumeration Type Documentation
enum en_i2sl_clk_in
Enumerator:
I2slUsePclk
I2S-Lite use PCLK as the source clock of divider.
I2slUseExtClk
I2S-Lite use external clock(input from pins) as the source clock.
Definition at line 135 of file i2sl.h.
enum en_i2sl_fifo
i2s FIFO Number
Enumerator:
I2slFifo1
FIFO No.1.
I2slFifo2
FIFO No.2.
Definition at line 220 of file i2sl.h.
enum en_i2sl_fifo_sel
I2S-Lite FIFO Selection.
Enumerator:
I2slTxFifo1RxFifo2
Transmit FIFO:FIFO1, Received FIFO:FIFO2.
I2slTxFifo2RxFifo1
Transmit FIFO:FIFO2, Received FIFO:FIFO1.
Definition at line 176 of file i2sl.h.
enum en_i2sl_fifo_width
Enumerator:
I2slFifoWidth16Bit
FIFO 16-bit access.
I2slFifoWidth32Bit
FIFO 32-bit access.
Definition at line 165 of file i2sl.h.
enum en_i2sl_frame_len
Enumerator:
I2slFrame16Bit
16 bits frame.
I2slFrame32Bit
32 bits frame.
Definition at line 155 of file i2sl.h.
enum en_i2sl_instance_index
Enumeration to define an index for each enabled I2S-Lite instance.
Enumerator:
I2slInstanceIndexI2sl0
I2slInstanceIndexI2sl1
I2slInstanceIndexMax
I2slInstanceIndexUnknown
Definition at line 292 of file i2sl.h.
enum en_i2sl_irq_sel
I2S interrupt enable structure.
Enumerator:
I2slRxFifoIrq
I2S-Lite RX interrupt.
I2slTxFifoIrq
I2S-Lite TX interrupt.
Definition at line 209 of file i2sl.h.
enum en_i2sl_mode
Enumerator:
I2slPhilipsMode
I2S-Lite Philips standard.
I2slMsbJustifiedMode
I2S-Lite MSB justified standard.
Definition at line 145 of file i2sl.h.
enum en_i2sl_status
Enumerator:
I2slTxFifoEmpty
TX FIFO status (empty or not)
I2slRxFifoFull
RX FIFO status (full or not)
I2slRxFifoOverrun
RX FIFO status (Overrun or not)
I2slBusBusy
I2S bus is transferring data or not.
I2slClockStatus
I2S clock is running or not.
Definition at line 258 of file i2sl.h.
Function Documentation
en_result_t I2sl_ClrError (volatile FM_MFS_CSIO_TypeDef * pstcI2sl)
Clear overrun error flag.
Parameters:
[in] pstcI2sl Pointer to I2SL instance
Return values:
Ok Error is cleared
ErrorInvalidParameter pstcI2sl = NULL
Definition at line 881 of file i2sl.c.
en_result_t I2sl_DeInit (volatile FM_MFS_CSIO_TypeDef * pstcI2sl, boolean_t bTouchNvic)
Deinitialisation I2S.
This function initializes an I2S module
Parameters:
[in] pstcI2sl I2S instance
[in] bTouchNvic Touch NVIC or not
Return values:
Ok I2S initialized normally
ErrorInvalidParameter if one of following cases matchs:
pstcI2sl == NULL
Other invalid configuration
Definition at line 662 of file i2sl.c.
References I2slDeInitNvic(), I2slGetRegPtr(), and stc_i2slregn_t.
en_result_t I2sl_DisableClockOut (volatile FM_MFS_CSIO_TypeDef * pstcI2sl)
Disable I2S Clock out.
Parameters:
[in] pstcI2sl Pointer to I2SL instance
Return values:
Ok Error is cleared
ErrorInvalidParameter pstcI2sl = NULL
Definition at line 795 of file i2sl.c.
References I2slGetRegPtr(), and stc_i2slregn_t.
en_result_t I2sl_DisableIrq (volatile FM_MFS_CSIO_TypeDef * pstcI2sl, en_i2sl_irq_sel_t enIrqSel)
Disable I2S interrupt.
Parameters:
[in] pstcI2sl Pointer to I2S instance
[in] enIrqSel I2S interrupt type
Return values:
Ok Interrupt has been disabled
ErrorInvalidParameter If one of following conditions are met:
pstcI2slo == NULL
pstcInt == NULL
Definition at line 437 of file i2sl.c.
References I2slRxFifoIrq, and I2slTxFifoIrq.
en_result_t I2sl_EnableClockOut (volatile FM_MFS_CSIO_TypeDef * pstcI2sl)
Enable I2S Clock out.
Parameters:
[in] pstcI2sl Pointer to I2SL instance
Return values:
Ok Error is cleared
ErrorInvalidParameter pstcI2sl = NULL
Definition at line 768 of file i2sl.c.
References I2slGetRegPtr(), and stc_i2slregn_t.
en_result_t I2sl_EnableIrq (volatile FM_MFS_CSIO_TypeDef * pstcI2sl, en_i2sl_irq_sel_t enIrqSel)
Enable I2S interrupts.
Parameters:
[in] pstcI2sl Pointer to I2S instance
[in] enIrqSel I2S interrupt type
Return values:
Ok Interrupt has been enabled
ErrorInvalidParameter If one of following conditions are met:
pstcI2sl == NULL
Other invalid configuration
Definition at line 400 of file i2sl.c.
References I2slRxFifoIrq, and I2slTxFifoIrq.
uint8_t I2sl_GetFifoCount (volatile FM_MFS_CSIO_TypeDef * pstcI2sl, en_i2sl_fifo_t enFifo)
Get I2S FIFO count.
Parameters:
[in] pstcI2sl Pointer to I2S instance
[in] enFifo FIFO1 or FIFO2
Return values:
FIFO count
This function gets the current data count in selected FIFO.
Note:
0xFF will be return value if FIFO index is error.
Definition at line 1029 of file i2sl.c.
References I2slFifo1.
boolean_t I2sl_GetStatus (volatile FM_MFS_CSIO_TypeDef * pstcI2sl, en_i2sl_status_t enStatus)
Get status of I2S-Lite according to status type.
Parameters:
[in] pstcI2sl Pointer to I2SL instance
[in] enStatus I2SL status type
I2slRxFifoFull I2SL receive FIFO full
I2slTxFifoEmpty I2SL tranfer FIFO empty
I2slRxFifoOverrun I2SL receive FIFO overrun
I2slBusBusy I2SL bus status
I2slClockStatus I2SL clock status
Return values:
FALSE If one of following conditions are met:
I2SL receive FIFO data count don't meet with FBYTE [enStatus = I2slRxFifoFull]
I2SL tranfer FIFO is not empty [enStatus = I2slTxFifoEmpty]
I2SL receive FIFO don't overrun [enStatus = UartTxIdle]
I2SL bus idle [enStatus = I2slBusBusy]
I2SL clock stops [enStatus = I2slClockStatus]
TRUE If one of following conditions are met:
I2SL receive FIFO data count meet with FBYTE [enStatus = I2slRxFifoFull]
I2SL tranfer FIFO is empty [enStatus = I2slTxFifoEmpty]
I2SL receive FIFO overruns [enStatus = UartTxIdle]
I2SL bus busy [enStatus = I2slBusBusy]
I2SL clock is running [enStatus = I2slClockStatus]
Definition at line 838 of file i2sl.c.
References I2slBusBusy, I2slClockStatus, I2slGetRegPtr(), I2slRxFifoFull, I2slRxFifoOverrun, I2slTxFifoEmpty, and stc_i2slregn_t.
en_result_t I2sl_Init (volatile FM_MFS_CSIO_TypeDef * pstcI2sl, stc_i2sl_config_t * pstcConfig)
Initialize I2S.
This function initializes an I2S module
Parameters:
[in] pstcI2sl I2S instance
[in] pstcConfig I2S module configuration
Return values:
Ok I2S initialized normally
ErrorInvalidParameter if one of following cases matchs:
pstcI2sl == NULL
pstcConfig == NULL
Other invalid configuration
Definition at line 481 of file i2sl.c.
References stc_i2s_config::bCkWsOutputEn, stc_i2s_config::bClkOutputEn, stc_i2s_config::bDataOutput, stc_i2s_config::bI2sWsPolarity, stc_i2s_config::bMaskBitOutput, stc_i2sl_irq_en::bRxFifoIrq, stc_i2s_config::bTouchNvic, stc_i2sl_irq_en::bTxFifoIrq, stc_i2s_config::enClkIn, stc_i2s_config::enFifoSel, stc_i2s_config::enFifoWidth, stc_i2s_config::enFrameLength, stc_i2s_config::enTransferMode, I2slFifoWidth16Bit, I2slFifoWidth32Bit, I2slFrame16Bit, I2slFrame32Bit, I2slGetInternDataPtr(), I2slGetRegPtr(), I2slInitNvic(), I2slMsbJustifiedMode, I2slPhilipsMode, I2slTxFifo1RxFifo2, I2slUseExtClk, I2slUsePclk, stc_i2sl_irq_cb::pfnRxFifoIrqCb, stc_i2sl_intern_data::pfnRxFifoIrqCb, stc_i2sl_irq_cb::pfnRxFifoOverrunIrqCb, stc_i2sl_intern_data::pfnRxFifoOverrunIrqCb, stc_i2sl_irq_cb::pfnTxFifoIrqCb, stc_i2sl_intern_data::pfnTxFifoIrqCb, stc_i2s_config::pstcI2slIrqCb, stc_i2s_config::pstcI2slIrqEn, stc_i2slregn_t, stc_i2s_config::u8ByteCount1, stc_i2s_config::u8ByteCount2, and stc_i2s_config::u8ClkInDiv.
uint32_t I2sl_ReadRxFifo (volatile FM_MFS_CSIO_TypeDef * pstcI2sl)
read I2S data buffer
Parameters:
[in] pstcI2sl Pointer to I2S instance
Return values:
Receive data
Definition at line 933 of file i2sl.c.
en_result_t I2sl_ResetFifo (volatile FM_MFS_CSIO_TypeDef * pstcI2sl, en_i2sl_fifo_t enFifo)
Reset I2S FIFO.
Parameters:
[in] pstcI2sl Pointer to I2S instance
[in] enFifo FIFO1 or FIFO2
Return values:
Ok FIFO has been successfully reset
ErrorInvalidParameter If one of following conditions are met:
pstcCsio == NULL
Definition at line 956 of file i2sl.c.
References I2slFifo1, and I2slFifo2.
void I2sl_RxIrqHandler (volatile FM_MFS_CSIO_TypeDef * pstcI2sl, stc_i2sl_intern_data_t * pstcI2slInternData)
i2s instance receiving interrupt service routine
I2S instance interrupt service routine, clear interrupt cause and
Parameters:
pstcI2sl Pointer to I2S instance
pstcI2slInternData Pointer to I2S intern data
Definition at line 195 of file i2sl.c.
References stc_i2sl_intern_data::pfnRxFifoIrqCb, and stc_i2sl_intern_data::pfnRxFifoOverrunIrqCb.
en_result_t I2sl_SetFifoCount (volatile FM_MFS_CSIO_TypeDef * pstcI2sl, en_i2sl_fifo_t enFifo, uint8_t u8Count)
set I2S FIFO count
Parameters:
[in] pstcI2sl Pointer to I2S instance
[in] enFifo FIFO1 or FIFO2
[in] u8Count FIFO count
Return values:
Ok FIFO has been successfully reset
ErrorInvalidParameter If one of following conditions are met:
pstcCsio == NULL
Definition at line 992 of file i2sl.c.
References I2slFifo1, and I2slFifo2.
en_result_t I2sl_Start (volatile FM_MFS_CSIO_TypeDef * pstcI2sl)
start I2S, enable i2s clock generate
Parameters:
[in] pstcI2sl Pointer to I2SL instance
Return values:
Ok Error is cleared
ErrorInvalidParameter pstcI2sl = NULL
Definition at line 714 of file i2sl.c.
References I2slGetRegPtr(), and stc_i2slregn_t.
en_result_t I2sl_Stop (volatile FM_MFS_CSIO_TypeDef * pstcI2sl)
stop I2S, disable i2s clock generate
Parameters:
[in] pstcI2sl Pointer to I2SL instance
Return values:
Ok Error is cleared
ErrorInvalidParameter pstcI2sl = NULL
Definition at line 741 of file i2sl.c.
References I2slGetRegPtr(), and stc_i2slregn_t.
void I2sl_TxIrqHandler (volatile FM_MFS_CSIO_TypeDef * pstcI2sl, stc_i2sl_intern_data_t * pstcI2slInternData)
i2s instance transmiting interrupt service routine
I2S instance interrupt service routine, clear interrupt cause and
Parameters:
pstcI2sl Pointer to I2S instance
pstcI2slInternData Pointer to I2S intern data
Definition at line 167 of file i2sl.c.
References stc_i2sl_intern_data::pfnTxFifoIrqCb.
en_result_t I2sl_WriteTxFifo (volatile FM_MFS_CSIO_TypeDef * pstcI2sl, uint32_t u32Data)
Write I2S data buffer.
Parameters:
[in] pstcI2sl Pointer to I2S instance
[in] u32Data Send data
Return values:
Ok Data has been successfully sent
ErrorInvalidParameter If one of following conditions are met:
pstcI2sl == NULL
Definition at line 905 of file i2sl.c.
static void I2slDeInitNvic (volatile FM_MFS_CSIO_TypeDef * pstcI2sl, boolean_t bRxIrq) [static]
Clear NVIC Interrupt depending on I2S instance.
Parameters:
pstcI2sl Pointer to I2S instance
bRxIrq TRUE: RX interrupt, FALSE: TX interrupt
Definition at line 307 of file i2sl.c.
References I2SL0, I2SL1, PDL_DEFAULT_INTERRUPT_LEVEL, and stc_i2sln_t.
Referenced by I2sl_DeInit().
static stc_i2sl_intern_data_t* I2slGetInternDataPtr (volatile FM_MFS_CSIO_TypeDef * pstcI2sl) [static]
Return the internal data for a certain i2s instance.
Parameters:
pstcI2sl Pointer to i2s instance
Returns:
Pointer to internal data or NULL if instance is not enabled (or not known)
Definition at line 115 of file i2sl.c.
References I2SL_INSTANCE_COUNT, and stc_i2sl_instance_data::stcInternData.
Referenced by I2sl_Init().
static volatile FM_I2SL_TypeDef* I2slGetRegPtr (volatile FM_MFS_CSIO_TypeDef * pstcI2sl) [static]
Return the internal data for a certain i2s register instance.
Parameters:
pstcI2sl Pointer to i2s instance
Returns:
Pointer to internal data or NULL if instance is not enabled (or not known)
Definition at line 139 of file i2sl.c.
References I2SL_INSTANCE_COUNT, and stc_i2sl_instance_data::pstcInstanceReg.
Referenced by I2sl_DeInit(), I2sl_DisableClockOut(), I2sl_EnableClockOut(), I2sl_GetStatus(), I2sl_Init(), I2sl_Start(), and I2sl_Stop().
static void I2slInitNvic (volatile FM_MFS_CSIO_TypeDef * pstcI2sl, boolean_t bRxIrq) [static]
Set NVIC Interrupt depending on I2S instance.
Parameters:
pstcI2sl Pointer to I2S instance
bRxIrq TRUE: RX interrupt, FALSE: TX interrupt
Definition at line 228 of file i2sl.c.
References I2SL0, I2SL1, PDL_IRQ_LEVEL_MFS4, PDL_IRQ_LEVEL_MFS6_I2CS0, and stc_i2sln_t.
Referenced by I2sl_Init().
Variable Documentation
stc_i2sl_instance_data_t m_astcI2slInstanceDataLut[(uint8_t)(PDL_PERIPHERAL_ENABLE_I2SL0==PDL_ON)+(uint8_t)(PDL_PERIPHERAL_ENABLE_I2SL1==PDL_ON)]
Initial value:
{
    {
        & (*(volatile  FM_MFS_CSIO_TypeDef  *) FM_MFS4_CSIO) ,
        & (*(volatile  FM_I2SL_TypeDef  *) FM_I2SL0) ,
        0u,
    },
    {
        & (*(volatile  FM_MFS_CSIO_TypeDef  *) FM_MFS6_CSIO) ,
        & (*(volatile  FM_I2SL_TypeDef  *) FM_I2SL1) ,
        0u,
    },
}
Look-up table for all enabled I2s instances and their internal data.
Look-up table for all enabled I2S-Lite instances and their internal data.
Definition at line 75 of file i2sl.c.
stc_i2sl_instance_data_t m_astcI2slInstanceDataLut[(uint8_t)(PDL_PERIPHERAL_ENABLE_I2SL0==PDL_ON)+(uint8_t)(PDL_PERIPHERAL_ENABLE_I2SL1==PDL_ON)]
Look-up table for all enabled I2S-Lite instances and their internal data.
Definition at line 75 of file i2sl.c.