PDL for FM Family: stc_dma_intern_data Struct Reference
stc_dma_intern_data Struct Reference
Direct Memory Access (DMA)
Datatype for holding internal data needed for DMA.
#include <dma.h>
Data Fields
func_ptr_t apfnDmaIrqCompletionCb [(PDL_PERIPHERAL_ENABLE_DMA0==PDL_ON)+(PDL_PERIPHERAL_ENABLE_DMA1==PDL_ON)+(PDL_PERIPHERAL_ENABLE_DMA2==PDL_ON)+(PDL_PERIPHERAL_ENABLE_DMA3==PDL_ON)+(PDL_PERIPHERAL_ENABLE_DMA4==PDL_ON)+(PDL_PERIPHERAL_ENABLE_DMA5==PDL_ON)+(PDL_PERIPHERAL_ENABLE_DMA6==PDL_ON)+(PDL_PERIPHERAL_ENABLE_DMA7==PDL_ON)]
DMA transfer completion callback pointer array.
func_ptr_arg1_t apfnDmaErrorIrqCb [(PDL_PERIPHERAL_ENABLE_DMA0==PDL_ON)+(PDL_PERIPHERAL_ENABLE_DMA1==PDL_ON)+(PDL_PERIPHERAL_ENABLE_DMA2==PDL_ON)+(PDL_PERIPHERAL_ENABLE_DMA3==PDL_ON)+(PDL_PERIPHERAL_ENABLE_DMA4==PDL_ON)+(PDL_PERIPHERAL_ENABLE_DMA5==PDL_ON)+(PDL_PERIPHERAL_ENABLE_DMA6==PDL_ON)+(PDL_PERIPHERAL_ENABLE_DMA7==PDL_ON)]
DMA error callback pointer array.
Detailed Description
Datatype for holding internal data needed for DMA.
Definition at line 409 of file dma.h.
Field Documentation
func_ptr_arg1_t apfnDmaErrorIrqCb[(PDL_PERIPHERAL_ENABLE_DMA0==PDL_ON)+(PDL_PERIPHERAL_ENABLE_DMA1==PDL_ON)+(PDL_PERIPHERAL_ENABLE_DMA2==PDL_ON)+(PDL_PERIPHERAL_ENABLE_DMA3==PDL_ON)+(PDL_PERIPHERAL_ENABLE_DMA4==PDL_ON)+(PDL_PERIPHERAL_ENABLE_DMA5==PDL_ON)+(PDL_PERIPHERAL_ENABLE_DMA6==PDL_ON)+(PDL_PERIPHERAL_ENABLE_DMA7==PDL_ON)]
DMA error callback pointer array.
Definition at line 412 of file dma.h.
Referenced by Dma_InitChannel(), and DmaIrqHandler().
func_ptr_t apfnDmaIrqCompletionCb[(PDL_PERIPHERAL_ENABLE_DMA0==PDL_ON)+(PDL_PERIPHERAL_ENABLE_DMA1==PDL_ON)+(PDL_PERIPHERAL_ENABLE_DMA2==PDL_ON)+(PDL_PERIPHERAL_ENABLE_DMA3==PDL_ON)+(PDL_PERIPHERAL_ENABLE_DMA4==PDL_ON)+(PDL_PERIPHERAL_ENABLE_DMA5==PDL_ON)+(PDL_PERIPHERAL_ENABLE_DMA6==PDL_ON)+(PDL_PERIPHERAL_ENABLE_DMA7==PDL_ON)]
DMA transfer completion callback pointer array.
Definition at line 411 of file dma.h.
Referenced by Dma_InitChannel(), and DmaIrqHandler().
The documentation for this struct was generated from the following file:
C:/Users/chzhang/Desktop/FM0 MCU/universial PDL/release_v11f_doxy/driver/dma/dma.h