PDL for FM Family: stc_exint_config Struct Reference
stc_exint_config Struct Reference
External Interrupts (EXINT)
EXINT configuration.
#include <exint.h>
Data Fields
boolean_t abEnable [(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT0==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT1==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT2==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT3==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT4==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT5==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT6==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT7==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT8==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT9==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT10==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT11==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT12==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT13==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT14==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT15==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT16==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT17==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT18==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT19==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT20==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT21==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT22==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT23==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT24==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT25==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT26==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT27==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT28==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT29==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT30==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT31==PDL_ON)]
TRUE: External Interrupt enable.
en_exint_level_t aenLevel [(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT0==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT1==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT2==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT3==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT4==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT5==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT6==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT7==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT8==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT9==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT10==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT11==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT12==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT13==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT14==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT15==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT16==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT17==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT18==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT19==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT20==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT21==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT22==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT23==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT24==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT25==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT26==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT27==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT28==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT29==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT30==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT31==PDL_ON)]
level detection, see en_exint_level_t for details
func_ptr_t apfnExintCallback [(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT0==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT1==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT2==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT3==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT4==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT5==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT6==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT7==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT8==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT9==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT10==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT11==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT12==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT13==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT14==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT15==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT16==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT17==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT18==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT19==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT20==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT21==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT22==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT23==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT24==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT25==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT26==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT27==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT28==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT29==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT30==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT31==PDL_ON)]
Callback pointers.
boolean_t bTouchNvic
TRUE: Enable NVIC, FALSE: don't enable NVIC,.
Detailed Description
EXINT configuration.
External Interrupt configuration
The EXINT configuration
Definition at line 174 of file exint.h.
Field Documentation
boolean_t abEnable[(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT0==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT1==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT2==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT3==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT4==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT5==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT6==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT7==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT8==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT9==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT10==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT11==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT12==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT13==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT14==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT15==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT16==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT17==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT18==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT19==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT20==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT21==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT22==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT23==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT24==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT25==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT26==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT27==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT28==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT29==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT30==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT31==PDL_ON)]
TRUE: External Interrupt enable.
Definition at line 176 of file exint.h.
Referenced by Exint_Init().
en_exint_level_t aenLevel[(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT0==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT1==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT2==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT3==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT4==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT5==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT6==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT7==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT8==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT9==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT10==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT11==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT12==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT13==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT14==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT15==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT16==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT17==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT18==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT19==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT20==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT21==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT22==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT23==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT24==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT25==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT26==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT27==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT28==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT29==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT30==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT31==PDL_ON)]
level detection, see en_exint_level_t for details
Definition at line 177 of file exint.h.
Referenced by Exint_Init().
func_ptr_t apfnExintCallback[(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT0==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT1==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT2==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT3==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT4==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT5==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT6==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT7==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT8==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT9==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT10==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT11==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT12==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT13==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT14==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT15==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT16==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT17==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT18==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT19==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT20==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT21==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT22==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT23==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT24==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT25==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT26==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT27==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT28==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT29==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT30==PDL_ON)+(uint8_t)(PDL_INTERRUPT_ENABLE_EXINT31==PDL_ON)]
Callback pointers.
Definition at line 178 of file exint.h.
Referenced by Exint_Init().
boolean_t bTouchNvic
TRUE: Enable NVIC, FALSE: don't enable NVIC,.
Definition at line 179 of file exint.h.
Referenced by Exint_Init().
The documentation for this struct was generated from the following file:
C:/Users/chzhang/Desktop/FM0 MCU/universial PDL/release_v11f_doxy/driver/exint/exint.h