PDL for FM Family: C:/Users/chzhang/Desktop/FM0 MCU/universial PDL/release_v11f_doxy/driver/wc/wc.c File Reference
C:/Users/chzhang/Desktop/FM0 MCU/universial PDL/release_v11f_doxy/driver/wc/wc.c File Reference
#include "wc.h"
Functions
static void WcInitNvic (FM_WC_TypeDef *pstcWc)
Set NVIC Interrupt depending on WC instance.
static void WcDeInitNvic (FM_WC_TypeDef *pstcWc)
Clear NVIC Interrupt depending on WC instance.
void Wc_IrqHandler (FM_WC_TypeDef *pstcWc)
Watch counter interrupt function.
en_result_t Wc_Pres_SelClk (FM_WC_TypeDef *pstcWc, stc_wc_pres_clk_t *pstcWcPresClk)
Select the input clock an and set the division clock to be output.
en_result_t Wc_Pres_EnableDiv (FM_WC_TypeDef *pstcWc)
Enable oscillation of the division clock.
en_result_t Wc_Pres_DisableDiv (FM_WC_TypeDef *pstcWc)
Disable oscillation of the division clock.
en_stat_flag_t Wc_Pres_GetDivStat (FM_WC_TypeDef *pstcWc)
Get the operation status of the division counter.
en_result_t Wc_Init (FM_WC_TypeDef *pstcWc, stc_wc_config_t *pstcWcConfig)
Select the input clock and set the division clock to be output.
en_result_t Wc_DeInit (FM_WC_TypeDef *pstcWc, boolean_t bTouchNvic)
De-Initialize WC.
en_result_t Wc_EnableCount (FM_WC_TypeDef *pstcWc)
Enable WC operation.
en_result_t Wc_DisableCount (FM_WC_TypeDef *pstcWc)
Disable WC operation.
en_result_t Wc_EnableIrq (FM_WC_TypeDef *pstcWc)
Enable WC underflow interrupt.
en_result_t Wc_DisableIrq (FM_WC_TypeDef *pstcWc)
Disable WC underflow interrupt.
en_result_t Wc_WriteReloadVal (FM_WC_TypeDef *pstcWc, uint8_t u8Val)
Set the counter value of WC.
uint8_t Wc_ReadCurCnt (FM_WC_TypeDef *pstcWc)
Read the value in the 6-bit down counter.
en_result_t Wc_ClearIrqFlag (FM_WC_TypeDef *pstcWc)
Clear WC underflow flag.
en_irq_flag_t Wc_GetIrqFlag (FM_WC_TypeDef *pstcWc)
Get WC underflow flag status.
en_stat_flag_t Wc_GetOperationFlag (FM_WC_TypeDef *pstcWc)
Get WC operation state.
Variables
static func_ptr_t pWcfnIrqCallback = NULL
Detailed Description
A detailed description is available at WC Module description
History:
2014-11-17 0.1 Edison Zhang First version for FM universal PDL.
Definition in file wc.c.
Function Documentation
en_result_t Wc_ClearIrqFlag (FM_WC_TypeDef * pstcWc)
Clear WC underflow flag.
The Function clear WCIF to 0 of WC
Parameters:
[in] pstcWc Pointer to WC instance
Return values:
Ok Clear WC underflow flag normally
ErrorInvalidParameter If one of following conditions are met:
pstcWc == NULL
Definition at line 559 of file wc.c.
Referenced by Wc_IrqHandler().
en_result_t Wc_DeInit (FM_WC_TypeDef * pstcWc, boolean_t bTouchNvic)
De-Initialize WC.
Clear all registers of WC
Parameters:
[in] pstcWc WC configuration
[in] bTouchNvic Touch NVIC or not
Return values:
Ok Write data successfully done or started.
ErrorInvalidParameter If one of following conditions are met:
pstcWc == NULL
Definition at line 373 of file wc.c.
References WcDeInitNvic().
en_result_t Wc_DisableCount (FM_WC_TypeDef * pstcWc)
Disable WC operation.
The Function can clear WCCR:WCEN to 0 of WC
Parameters:
[in] pstcWc Pointer to WC instance
Return values:
Ok Disable WC operation normally
Definition at line 429 of file wc.c.
en_result_t Wc_DisableIrq (FM_WC_TypeDef * pstcWc)
Disable WC underflow interrupt.
The Function can clear WCIE of WC
Parameters:
[in] pstcWc Pointer to WC instance
Return values:
Ok Disable WC underflow interrupt normally
ErrorInvalidParameter If one of following conditions are met:
pstcWc == NULL
Definition at line 483 of file wc.c.
en_result_t Wc_EnableCount (FM_WC_TypeDef * pstcWc)
Enable WC operation.
The Function can set WCCR:WCEN to 1 of WC
Parameters:
[in] pstcWc Pointer to WC instance
Return values:
Ok Enable WC operation normally
Definition at line 405 of file wc.c.
en_result_t Wc_EnableIrq (FM_WC_TypeDef * pstcWc)
Enable WC underflow interrupt.
The Function can set WCIE of WC
Parameters:
[in] pstcWc Pointer to WC instance
Return values:
Ok WC enabled successfully.
ErrorInvalidParameter If one of following conditions are met:
pstcWc == NULL
Definition at line 456 of file wc.c.
en_irq_flag_t Wc_GetIrqFlag (FM_WC_TypeDef * pstcWc)
Get WC underflow flag status.
The Function get value WCIF of WC
Parameters:
[in] pstcWc Pointer to WC instance
Return values:
PdlClr WCIF is 0, WC underflow does not occur
PdlSet WCIF is 1, WC underflow occurs
Definition at line 584 of file wc.c.
References PdlClr.
Referenced by Wc_IrqHandler().
en_stat_flag_t Wc_GetOperationFlag (FM_WC_TypeDef * pstcWc)
Get WC operation state.
The Function get value WCOP of WC
Parameters:
[in] pstcWc Pointer to WC instance
Return values:
PdlClr WCOP is 0, The WC is stopped
PdlSet WCOP is 1, The WC is active
Definition at line 607 of file wc.c.
References PdlClr.
en_result_t Wc_Init (FM_WC_TypeDef * pstcWc, stc_wc_config_t * pstcWcConfig)
Select the input clock and set the division clock to be output.
The Function can set SEL_OUT, SEL_IN of Watch counter prescaler (hereafter WCP)
Parameters:
[in] pstcWc Pointer to WC instance
[in] pstcWcConfig Pointer to WC configuration
Return values:
Ok The data is written to registers normally.
ErrorInvalidParameter If one of following conditions are met:
invalid value of pstcWcConfig->enCntClk
Definition at line 313 of file wc.c.
References stc_wc_config::bIrqEnable, stc_wc_config::bTouchNvic, stc_wc_config::enCntClk, stc_wc_config::pfnIrqCallback, pWcfnIrqCallback, stc_wc_config::u8ReloadValue, WcCntClkWcck0, WcCntClkWcck1, WcCntClkWcck2, WcCntClkWcck3, and WcInitNvic().
void Wc_IrqHandler (FM_WC_TypeDef * pstcWc)
Watch counter interrupt function.
Parameters:
[in] pstcWc Pointer to WC instance
Definition at line 140 of file wc.c.
References PdlSet, pWcfnIrqCallback, Wc_ClearIrqFlag(), and Wc_GetIrqFlag().
en_result_t Wc_Pres_DisableDiv (FM_WC_TypeDef * pstcWc)
Disable oscillation of the division clock.
The Function can clear CLK_EN:CLK_EN to 0 of WCP
Parameters:
[in] pstcWc Pointer to WC instance
Return values:
Ok Disable oscillation of the division clock normally
Definition at line 263 of file wc.c.
en_result_t Wc_Pres_EnableDiv (FM_WC_TypeDef * pstcWc)
Enable oscillation of the division clock.
The Function can set CLK_EN:CLK_EN to 1 of WCP
Parameters:
[in] pstcWc Pointer to WC instance
Return values:
Ok Enable oscillation of the division clock normally
Definition at line 239 of file wc.c.
en_stat_flag_t Wc_Pres_GetDivStat (FM_WC_TypeDef * pstcWc)
Get the operation status of the division counter.
The Function can get CLK_EN:CLK_EN_R to 0 of WCP
Parameters:
[in] pstcWc Pointer to WC instance
Return values:
PdlClr CLK_EN_R is 0, oscillation of the division clock is not performed
PdlSet CLK_EN R is 1, oscillation of the division clock is performed
Definition at line 288 of file wc.c.
References PdlClr.
en_result_t Wc_Pres_SelClk (FM_WC_TypeDef * pstcWc, stc_wc_pres_clk_t * pstcWcPresClk)
Select the input clock an and set the division clock to be output.
The Function can set SEL_OUT, SEL_IN of Watch counter prescaler (hereafter WCP)
Parameters:
[in] pstcWc Pointer to WC instance
[in] pstcWcPresClk WC prescaler clock configuration
Return values:
Ok Write data successfully done or started.
ErrorInvalidParameter If one of following conditions are met:
invalid value of pstcWcPresClk->enInputClk
invalid value of pstcWcPresClk->enOutputClk
Definition at line 168 of file wc.c.
References stc_wc_pres_clk::enInputClk, stc_wc_pres_clk::enOutputClk, WcPresInClkHighCr, WcPresInClkLowCr, WcPresInClkMainOsc, WcPresInClkSubOsc, WcPresOutClkArray0, WcPresOutClkArray1, WcPresOutClkArray2, WcPresOutClkArray3, WcPresOutClkArray4, WcPresOutClkArray5, and WcPresOutClkArray6.
uint8_t Wc_ReadCurCnt (FM_WC_TypeDef * pstcWc)
Read the value in the 6-bit down counter.
The Function can read value of WCRD of WC
Parameters:
[in] pstcWc Pointer to WC instance
Return values:
Current count value of WC
Definition at line 535 of file wc.c.
en_result_t Wc_WriteReloadVal (FM_WC_TypeDef * pstcWc, uint8_t u8Val)
Set the counter value of WC.
The Function can set value to WCRL of WC
Parameters:
[in] pstcWc Pointer to WC instance
[in] u8Val Set the reload count value
Return values:
Ok Set the counter value of WC normally
ErrorInvalidParameter If one of following conditions are met:
pstcWc == NULL
Definition at line 511 of file wc.c.
static void WcDeInitNvic (FM_WC_TypeDef * pstcWc) [static]
Clear NVIC Interrupt depending on WC instance.
Parameters:
[in] pstcWc Pointer to WC instance
Definition at line 111 of file wc.c.
References PDL_DEFAULT_INTERRUPT_LEVEL.
Referenced by Wc_DeInit().
static void WcInitNvic (FM_WC_TypeDef * pstcWc) [static]
Set NVIC Interrupt depending on WC instance.
Parameters:
[in] pstcWc Pointer to WC instance
Definition at line 81 of file wc.c.
References PDL_IRQ_LEVEL_DT_RTC_WC.
Referenced by Wc_Init().
Variable Documentation
func_ptr_t pWcfnIrqCallback = NULL [static]
Definition at line 67 of file wc.c.
Referenced by Wc_Init(), and Wc_IrqHandler().