PDL for FM Family: C:/Users/chzhang/Desktop/FM0 MCU/universial PDL/release_v11f_doxy/driver/wc/wc.h File Reference
C:/Users/chzhang/Desktop/FM0 MCU/universial PDL/release_v11f_doxy/driver/wc/wc.h File Reference
#include "mcu.h"
#include "pdl_user.h"
Data Structures
struct stc_wc_pres_clk
Structure to configure watch counter prescaler.
struct stc_wc_config
Structure to configure the watch counter.
Defines
#define stc_wcn_t FM_WC_TypeDef
#define WC0 (*((stc_wcn_t *) FM_WC_BASE))
Typedefs
typedef enum en_input_clk en_input_clk_t
Enumeration to define source clock of watch counter precaler.
typedef enum en_output_clk en_output_clk_t
Enumeration to define output clock of watch counter precaler.
typedef struct stc_wc_pres_clk stc_wc_pres_clk_t
Structure to configure watch counter prescaler.
typedef enum en_wc_cnt_clk en_wc_cnt_clk_t
Enumeration to set the clock of watch counter.
typedef struct stc_wc_config stc_wc_config_t
Structure to configure the watch counter.
Enumerations
enum en_input_clk { WcPresInClkSubOsc = 0u, WcPresInClkMainOsc = 1u, WcPresInClkHighCr = 2u, WcPresInClkLowCr = 3u }
Enumeration to define source clock of watch counter precaler.
enum en_output_clk {
WcPresOutClkArray0 = 0u, WcPresOutClkArray1 = 1u, WcPresOutClkArray2 = 2u, WcPresOutClkArray3 = 3u,
WcPresOutClkArray4 = 4u, WcPresOutClkArray5 = 5u, WcPresOutClkArray6 = 6u
}
Enumeration to define output clock of watch counter precaler.
enum en_wc_cnt_clk { WcCntClkWcck0 = 0u, WcCntClkWcck1 = 1u, WcCntClkWcck2 = 2u, WcCntClkWcck3 = 3u }
Enumeration to set the clock of watch counter.
Functions
en_result_t Wc_Pres_SelClk (FM_WC_TypeDef *pstcWc, stc_wc_pres_clk_t *pstcWcPresClk)
Select the input clock an and set the division clock to be output.
en_result_t Wc_Pres_EnableDiv (FM_WC_TypeDef *pstcWc)
Enable oscillation of the division clock.
en_result_t Wc_Pres_DisableDiv (FM_WC_TypeDef *pstcWc)
Disable oscillation of the division clock.
en_stat_flag_t Wc_Pres_GetDivStat (FM_WC_TypeDef *pstcWc)
Get the operation status of the division counter.
en_result_t Wc_Init (FM_WC_TypeDef *pstcWc, stc_wc_config_t *pstcWcConfig)
Select the input clock and set the division clock to be output.
en_result_t Wc_DeInit (FM_WC_TypeDef *pstcWc, boolean_t bTouchNvic)
De-Initialize WC.
en_result_t Wc_EnableCount (FM_WC_TypeDef *pstcWc)
Enable WC operation.
en_result_t Wc_DisableCount (FM_WC_TypeDef *pstcWc)
Disable WC operation.
en_result_t Wc_EnableIrq (FM_WC_TypeDef *pstcWc)
Enable WC underflow interrupt.
en_result_t Wc_DisableIrq (FM_WC_TypeDef *pstcWc)
Disable WC underflow interrupt.
en_result_t Wc_WriteReloadVal (FM_WC_TypeDef *pstcWc, uint8_t u8Val)
Set the counter value of WC.
uint8_t Wc_ReadCurCnt (FM_WC_TypeDef *pstcWc)
Read the value in the 6-bit down counter.
en_result_t Wc_ClearIrqFlag (FM_WC_TypeDef *pstcWc)
Clear WC underflow flag.
en_irq_flag_t Wc_GetIrqFlag (FM_WC_TypeDef *pstcWc)
Get WC underflow flag status.
en_stat_flag_t Wc_GetOperationFlag (FM_WC_TypeDef *pstcWc)
Get WC operation state.
void Wc_IrqHandler (FM_WC_TypeDef *pstcWc)
Watch counter interrupt function.
Detailed Description
Headerfile for WC functions
History:
2014-11-17 0.1 EZh First version for FM universal PDL.
Definition in file wc.h.
Define Documentation
#define stc_wcn_t FM_WC_TypeDef
Definition at line 122 of file wc.h.
#define WC0 (*((stc_wcn_t *) FM_WC_BASE))
Definition at line 123 of file wc.h.
Typedef Documentation
typedef enum en_input_clk en_input_clk_t
Enumeration to define source clock of watch counter precaler.
typedef enum en_output_clk en_output_clk_t
Enumeration to define output clock of watch counter precaler.
typedef enum en_wc_cnt_clk en_wc_cnt_clk_t
Enumeration to set the clock of watch counter.
typedef struct stc_wc_config stc_wc_config_t
Structure to configure the watch counter.
typedef struct stc_wc_pres_clk stc_wc_pres_clk_t
Structure to configure watch counter prescaler.
Enumeration Type Documentation
enum en_input_clk
Enumeration to define source clock of watch counter precaler.
Enumerator:
WcPresInClkSubOsc
Watch counter prescaler source clock: sub oscillator.
WcPresInClkMainOsc
Watch counter prescaler source clock: main oscillator.
WcPresInClkHighCr
Watch counter prescaler source clock: high-speed CR.
WcPresInClkLowCr
Watch counter prescaler source clock: low-speed CR.
Definition at line 129 of file wc.h.
enum en_output_clk
Enumeration to define output clock of watch counter precaler.
Enumerator:
WcPresOutClkArray0
WCCk3 WCCk2 WCCk1 WCCk0.
Watch counter prescaler output array0: 2^15/src clock, 2^14/src clock, 2^13/src clock, 2^12/src clock
WcPresOutClkArray1
Watch counter prescaler output array0: 2^25/src clock, 2^24/src clock, 2^23/src clock, 2^22/src clock.
WcPresOutClkArray2
Watch counter prescaler output array0: 2^4/src clock, 2^3/src clock, 2^2/src clock, 2/src clock.
WcPresOutClkArray3
Watch counter prescaler output array0: 2^8/src clock, 2^7/src clock, 2^6/src clock, 2^5/src clock.
WcPresOutClkArray4
Watch counter prescaler output array0: 2^12/src clock, 2^11/src clock, 2^10/src clock, 2^9/src clock.
WcPresOutClkArray5
Watch counter prescaler output array0: 2^19/src clock, 2^18/src clock, 2^17/src clock, 2^16/src clock.
WcPresOutClkArray6
Watch counter prescaler output array0: 2^23/src clock, 2^22/src clock, 2^21/src clock, 2^20/src clock.
Definition at line 143 of file wc.h.
enum en_wc_cnt_clk
Enumeration to set the clock of watch counter.
Enumerator:
WcCntClkWcck0
Watch counter source clock: WCCK0.
WcCntClkWcck1
Watch counter source clock: WCCK1.
WcCntClkWcck2
Watch counter source clock: WCCK2.
WcCntClkWcck3
Watch counter source clock: WCCK3.
Definition at line 172 of file wc.h.
Function Documentation
en_result_t Wc_ClearIrqFlag (FM_WC_TypeDef * pstcWc)
Clear WC underflow flag.
The Function clear WCIF to 0 of WC
Parameters:
[in] pstcWc Pointer to WC instance
Return values:
Ok Clear WC underflow flag normally
ErrorInvalidParameter If one of following conditions are met:
pstcWc == NULL
Definition at line 559 of file wc.c.
Referenced by Wc_IrqHandler().
en_result_t Wc_DeInit (FM_WC_TypeDef * pstcWc, boolean_t bTouchNvic)
De-Initialize WC.
Clear all registers of WC
Parameters:
[in] pstcWc WC configuration
[in] bTouchNvic Touch NVIC or not
Return values:
Ok Write data successfully done or started.
ErrorInvalidParameter If one of following conditions are met:
pstcWc == NULL
Definition at line 373 of file wc.c.
References WcDeInitNvic().
en_result_t Wc_DisableCount (FM_WC_TypeDef * pstcWc)
Disable WC operation.
The Function can clear WCCR:WCEN to 0 of WC
Parameters:
[in] pstcWc Pointer to WC instance
Return values:
Ok Disable WC operation normally
Definition at line 429 of file wc.c.
en_result_t Wc_DisableIrq (FM_WC_TypeDef * pstcWc)
Disable WC underflow interrupt.
The Function can clear WCIE of WC
Parameters:
[in] pstcWc Pointer to WC instance
Return values:
Ok Disable WC underflow interrupt normally
ErrorInvalidParameter If one of following conditions are met:
pstcWc == NULL
Definition at line 483 of file wc.c.
en_result_t Wc_EnableCount (FM_WC_TypeDef * pstcWc)
Enable WC operation.
The Function can set WCCR:WCEN to 1 of WC
Parameters:
[in] pstcWc Pointer to WC instance
Return values:
Ok Enable WC operation normally
Definition at line 405 of file wc.c.
en_result_t Wc_EnableIrq (FM_WC_TypeDef * pstcWc)
Enable WC underflow interrupt.
The Function can set WCIE of WC
Parameters:
[in] pstcWc Pointer to WC instance
Return values:
Ok WC enabled successfully.
ErrorInvalidParameter If one of following conditions are met:
pstcWc == NULL
Definition at line 456 of file wc.c.
en_irq_flag_t Wc_GetIrqFlag (FM_WC_TypeDef * pstcWc)
Get WC underflow flag status.
The Function get value WCIF of WC
Parameters:
[in] pstcWc Pointer to WC instance
Return values:
PdlClr WCIF is 0, WC underflow does not occur
PdlSet WCIF is 1, WC underflow occurs
Definition at line 584 of file wc.c.
References PdlClr.
Referenced by Wc_IrqHandler().
en_stat_flag_t Wc_GetOperationFlag (FM_WC_TypeDef * pstcWc)
Get WC operation state.
The Function get value WCOP of WC
Parameters:
[in] pstcWc Pointer to WC instance
Return values:
PdlClr WCOP is 0, The WC is stopped
PdlSet WCOP is 1, The WC is active
Definition at line 607 of file wc.c.
References PdlClr.
en_result_t Wc_Init (FM_WC_TypeDef * pstcWc, stc_wc_config_t * pstcWcConfig)
Select the input clock and set the division clock to be output.
The Function can set SEL_OUT, SEL_IN of Watch counter prescaler (hereafter WCP)
Parameters:
[in] pstcWc Pointer to WC instance
[in] pstcWcConfig Pointer to WC configuration
Return values:
Ok The data is written to registers normally.
ErrorInvalidParameter If one of following conditions are met:
invalid value of pstcWcConfig->enCntClk
Definition at line 313 of file wc.c.
References stc_wc_config::bIrqEnable, stc_wc_config::bTouchNvic, stc_wc_config::enCntClk, stc_wc_config::pfnIrqCallback, pWcfnIrqCallback, stc_wc_config::u8ReloadValue, WcCntClkWcck0, WcCntClkWcck1, WcCntClkWcck2, WcCntClkWcck3, and WcInitNvic().
void Wc_IrqHandler (FM_WC_TypeDef * pstcWc)
Watch counter interrupt function.
Parameters:
[in] pstcWc Pointer to WC instance
Definition at line 140 of file wc.c.
References PdlSet, pWcfnIrqCallback, Wc_ClearIrqFlag(), and Wc_GetIrqFlag().
en_result_t Wc_Pres_DisableDiv (FM_WC_TypeDef * pstcWc)
Disable oscillation of the division clock.
The Function can clear CLK_EN:CLK_EN to 0 of WCP
Parameters:
[in] pstcWc Pointer to WC instance
Return values:
Ok Disable oscillation of the division clock normally
Definition at line 263 of file wc.c.
en_result_t Wc_Pres_EnableDiv (FM_WC_TypeDef * pstcWc)
Enable oscillation of the division clock.
The Function can set CLK_EN:CLK_EN to 1 of WCP
Parameters:
[in] pstcWc Pointer to WC instance
Return values:
Ok Enable oscillation of the division clock normally
Definition at line 239 of file wc.c.
en_stat_flag_t Wc_Pres_GetDivStat (FM_WC_TypeDef * pstcWc)
Get the operation status of the division counter.
The Function can get CLK_EN:CLK_EN_R to 0 of WCP
Parameters:
[in] pstcWc Pointer to WC instance
Return values:
PdlClr CLK_EN_R is 0, oscillation of the division clock is not performed
PdlSet CLK_EN R is 1, oscillation of the division clock is performed
Definition at line 288 of file wc.c.
References PdlClr.
en_result_t Wc_Pres_SelClk (FM_WC_TypeDef * pstcWc, stc_wc_pres_clk_t * pstcWcPresClk)
Select the input clock an and set the division clock to be output.
The Function can set SEL_OUT, SEL_IN of Watch counter prescaler (hereafter WCP)
Parameters:
[in] pstcWc Pointer to WC instance
[in] pstcWcPresClk WC prescaler clock configuration
Return values:
Ok Write data successfully done or started.
ErrorInvalidParameter If one of following conditions are met:
invalid value of pstcWcPresClk->enInputClk
invalid value of pstcWcPresClk->enOutputClk
Definition at line 168 of file wc.c.
References stc_wc_pres_clk::enInputClk, stc_wc_pres_clk::enOutputClk, WcPresInClkHighCr, WcPresInClkLowCr, WcPresInClkMainOsc, WcPresInClkSubOsc, WcPresOutClkArray0, WcPresOutClkArray1, WcPresOutClkArray2, WcPresOutClkArray3, WcPresOutClkArray4, WcPresOutClkArray5, and WcPresOutClkArray6.
uint8_t Wc_ReadCurCnt (FM_WC_TypeDef * pstcWc)
Read the value in the 6-bit down counter.
The Function can read value of WCRD of WC
Parameters:
[in] pstcWc Pointer to WC instance
Return values:
Current count value of WC
Definition at line 535 of file wc.c.
en_result_t Wc_WriteReloadVal (FM_WC_TypeDef * pstcWc, uint8_t u8Val)
Set the counter value of WC.
The Function can set value to WCRL of WC
Parameters:
[in] pstcWc Pointer to WC instance
[in] u8Val Set the reload count value
Return values:
Ok Set the counter value of WC normally
ErrorInvalidParameter If one of following conditions are met:
pstcWc == NULL
Definition at line 511 of file wc.c.